### ISSUE TITLE
meet problem when parsing expression inside MySQL's IF function

### ISSUE THREAD

**Issue by yangziwen** [JSQLParser/JSqlParser#100]
Dear author, jsqlparser is really an exellent tool and thanks a lot for your efforts on it. Recently I meet a problem when parsing sql as follows and expect for your help.

SELECT IF(score >= 60, 'pass', 'failed') FROM tbl;

**Comment by wumpz** [comment]
Could you provide some exceptions?

**Comment by yangziwen** [comment]
The version of jsqlparser is 0.9.1 and I parse the sql in the following way
<pre>
CCJSqlParserUtil.parse("select if(score >= 60, 'pass', 'failed') from exam_record");
</pre>
then meet the exception as follows
<pre>
Caused by: net.sf.jsqlparser.parser.ParseException: Encountered " "(" "( "" at line 1, column 10.
Was expecting one of:
    <EOF> 
    "AS" ...
    "DO" ...
    "INTO" ...
    "FROM" ...
    "WHERE" ...
    "XML" ...
    "GROUP" ...
    "VALUE" ...
    "HAVING" ...
    "REPLACE" ...
    "TRUNCATE" ...
    "CAST" ...
    "PARTITION" ...
    "EXTRACT" ...
    "MATERIALIZED" ...
    "START" ...
    "CONNECT" ...
    "SIBLINGS" ...
    "COLUMN" ...
    "NULLS" ...
    "FIRST" ...
    "LAST" ...
    "ROWS" ...
    "RANGE" ...
    "FOLLOWING" ...
    "ROW" ...
    <S_IDENTIFIER> ...
    <S_QUOTED_IDENTIFIER> ...
    ";" ...
    "," ...
    "||" ...
    "^" ...
    "::" ...
    "::" ...
    "^" ...
    "||" ...
    "AS" ...
    <S_IDENTIFIER> ...
    <S_QUOTED_IDENTIFIER> ...
    "CAST" ...
    "DO" ...
    "EXTRACT" ...
    "FIRST" ...
    "FOLLOWING" ...
    "LAST" ...
    "MATERIALIZED" ...
    "NULLS" ...
    "PARTITION" ...
    "RANGE" ...
    "ROW" ...
    "ROWS" ...
    "SIBLINGS" ...
    "VALUE" ...
    "XML" ...
    "COLUMN" ...
    "REPLACE" ...
    "TRUNCATE" ...
    "," ...
    "INTO" ...
    "FROM" ...
    "WHERE" ...
    "START" ...
    "CONNECT" ...
    "GROUP" ...
    "HAVING" ...
    "::" ...
    "^" ...
    "||" ...
    "AS" ...
    <S_IDENTIFIER> ...
    <S_QUOTED_IDENTIFIER> ...
    "CAST" ...
    "DO" ...
    "EXTRACT" ...
    "FIRST" ...
    "FOLLOWING" ...
    "LAST" ...
    "MATERIALIZED" ...
    "NULLS" ...
    "PARTITION" ...
    "RANGE" ...
    "ROW" ...
    "ROWS" ...
    "SIBLINGS" ...
    "VALUE" ...
    "XML" ...
    "COLUMN" ...
    "REPLACE" ...
    "TRUNCATE" ...
    "TRUNCATE" ...
    "TRUNCATE" ...
    "TRUNCATE" ...
    "TRUNCATE" ...
    "TRUNCATE" ...
    "::" ...
    "^" ...
    "||" ...
    "::" ...
    "^" ...
    
	at net.sf.jsqlparser.parser.CCJSqlParser.generateParseException(CCJSqlParser.java:10444)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_consume_token(CCJSqlParser.java:10303)
	at net.sf.jsqlparser.parser.CCJSqlParser.Statement(CCJSqlParser.java:65)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:49)
	... 1 more
</pre>

It seems any relational operators(such as ">=") is not allowed, because a similar sql without the operator can be parsed correctly.

<pre>
CCJSqlParserUtil.parse("select if(is_qualified, 'pass', 'failed') from tbl");
</pre> 
For exmaple, `is_qualified` in the previous sql is a column with the value of 0 or 1.

**Comment by wumpz** [comment]
You are right. Relational operators are not yet supported as function parameter, only simple expressions.

**Comment by yangziwen** [comment]
So do you have any plan to support this in the near future? Please let me known, thanks.

**Comment by wumpz** [comment]
At the moment I have less time to work on JSqlParser, so I will investigate it in the following days. Depending on the time to spend on this problem, I will decide if and when to do it. So give me some more time.

**Comment by wumpz** [comment]
After looking into the grammar definition I come to the conclusion, that this not as simple, as it seems. So if you could stick to a case .. when, I would prefer not to support this type of function expression. Maybe it is something, you could provide? Pull requests are wellcome.

**Comment by ulyn** [comment]
I have also encountered the same problem.But I am difficult to change to case when expression.
It is a sad story that  you would prefer not to support this type of function expression.

**Comment by wumpz** [comment]
You know it is performance relevant. I had already some tries to implement this efficiently but did not succeed. So if there would be a proper solution I would happily integrate it.

**Comment by clevertension** [comment]
in mysql the [if] is both the mysql keyword and if expression, for example:
create table aaa if not exist;
select if(name,0,1) from table1;

so we should handle both two case

**Comment by tm-tomers** [comment]
Can providing a solution to this issue be re-considered? I'm experiencing this issue as well (using v1.1).
