### ISSUE TITLE
Discussion: Validation of SQL 

### ISSUE THREAD

**Issue by gitmotte** [JSQLParser/JSqlParser#1005]
Since there are multiple databases supported it would be possible to contruct or parse SQL which is not executable against those databases. I'm missing a concept to distinguish them. 

I found some Prefixed classes like OracleHint, some flags like PlainSelect.mySqlHintStraightJoin, ... 

What if we add a ValidationVisitor to the library - which could be used to check the parsed/build sql for validity of a specific database.

**Comment by wumpz** [comment]
That would be indeed a benefit. And since JSqlParsers core of being multi database capable will not change the implementation this as a visitor seems the right way to go. Additional I want to add here some points that could be validated as well besides the compatibility with specific database systems:

* validate against a database schema (used columns, tables, ...)
* validate scope of selected objects (a database schema needs to be there)
** and build a relationbetween columns and tables (`select a,b from mytab1, mytab2`)

**Comment by gitmotte** [comment]
Validation against database metadata is a second step, sure. But there is not always a schema present and we should not relate an it.
Btw. Fetching metadata is also database - specific.

If a connection is present we can test the Statement against it and let the database validate those things.

**Comment by gitmotte** [comment]
I did a small improvement on deparser-api during analyses - hope its a step forward ...
https://github.com/JSQLParser/JSqlParser/pull/1007

**Comment by gitmotte** [comment]
> That would be indeed a benefit. And since JSqlParsers core of being multi database capable will not change the implementation this as a visitor seems the right way to go.

I thought about your statement that the core will not change to be multi database capable.
This could end up in a grammar which is not maintainable any more. I thought about a pluggable system to add own constructs, extension points for non-standard syntax or multiple database specific parsers making the validation for a database obsolete, because the parser cannot parse syntax valid within other databases and the model could be specific to each database  too. Interfaces can force common model-fields and other users are able to add extensions by adding a library to the classpath. A factory can be used to choose the correct parser. This change can be on top of a multi database capable parser variant, which could be replaced step by step by a parser trying to parse against a set of parsers for probing a syntax.

**Comment by wumpz** [comment]
I thought also about maintaining multiple grammars but decided against it, at least for now. Within the bracket discussion that was a point as well. Now The parser has a flag, to switch something on or off. 

Assume you go the multigrammar way. Where would you make the cut? Even between the versions of one database are differences. Or is there a way if plugging two different grammars together or build a grammar up out of even smaller grammar blocks?

Imho the multidatabase part is one of the key benefits of this parser.

**Comment by gitmotte** [comment]
> I thought also about maintaining multiple grammars but decided against it, at least for now. Within the bracket discussion that was a point as well. Now The parser has a flag, to switch something on or off.
>
> Assume you go the multigrammar way. Where would you make the cut? Even between the versions of one database are differences. Or is there a way if plugging two different grammars together or build a grammar up out of even smaller grammar blocks?
> 
> Imho the multidatabase part is one of the key benefits of this parser.

we could combine those things by 
* adding on/off switches for features and/or a set of features defined new within a new database-version (or outdated by this version) 
* and make a cut for other database-systems by providing a new grammar. 

yes, most database-systems share a common syntax based on sql-92, sql-96, .. that would produce a lot of code which is duplicated, but without the downside to impact all parsers. Unfortunately I do not know at the moment a system plugging multiple grammars together - seems there are no include/override mechanisms in java-cc (or antlr4) (?)

probably a database-system could be a feature-set too, i.e.

postgresql (all features of all versions?)
- postgresql12 extends postgresql11
 * feature-x=off
 * feature-y=new
- postgresql11
 * feature-x=deprecated

mysql
-mysql8
 * feature-y=new

feature-x (mysql8, postgresql11, postgresql12, ... )
feature-y

**Comment by gitmotte** [comment]
@wumpz please have a look at newest proposal for 
* an extensible validation visitor framework (ValidationCapability and its subtypes FeatureSetValidation, DatabaseMetaDataValidation, AllowedTypesValidation)
* FeatureConfiguration/Feature/FeatureSet class 

branch https://github.com/gitmotte/JSqlParser/tree/github.validate within packages
* net.sf.jsqlparser.util.validation
* net.sf.jsqlparser.parser.feature
