### ISSUE TITLE
jsqlparse 的解析不是非常友好

### ISSUE THREAD

**Issue by anylys** [JSQLParser/JSqlParser#1008]
1.jsqlparse 解析sql,想判断之前的sql是否已经有某个条件,如果已经有条件,则不添加重复的条件,很显然,这不好实现
2.对于select * from user,config  这种语句,并不能像druid一样,非常的能理解

**Comment by wumpz** [comment]
Our developer team is English speaking. Sorry.

**Comment by wumpz** [comment]
Sorry, unable to understand this issue.
