### ISSUE TITLE
License information

### ISSUE THREAD

**Issue by azapps** [JSQLParser/JSqlParser#101]
You should add a license information to the project. The original software is licensed under Apache 2.0 and LGPL: http://sourceforge.net/projects/jsqlparser/

The LPGL forces you to license the fork also under LGPL

**Comment by wumpz** [comment]
But is has the license information LGPL. So why do you think  there is none? LGPL forces the forks to be that as well, but you could use the library at will in commercial projects. So  where is the problem?

**Comment by azapps** [comment]
Ahh sorry I just found it :P I expected to find it in the readme/license file.

**Comment by wumpz** [comment]
Good point. I will include it in the readme.

**Comment by azapps** [comment]
Thank you ;)
