### ISSUE TITLE
function DATE_ADD parse failed

### ISSUE THREAD

**Issue by DaiZZZZZ** [JSQLParser/JSqlParser#1010]
**Describe the bug**
 sql parse failed = "select DATE_ADD(now(), INTERVAL rand() \* 3 DAY)",
sql parse succeed = "select DATE_ADD(now(), INTERVAL 3 \* rand() DAY)"

**To Reproduce**
1. select DATE_ADD(now(), INTERVAL rand()*3 DAY)
2. Parsing this SQL using JSqlParser with this statements
3. `Caused by: net.sf.jsqlparser.JSQLParserException
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:65)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:40)
	at com.gunma.sql.SqlParseTest.sqlParse(SqlParseTest.java:102)
	... 47 more
Caused by: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "(" "("
    at line 1, column 16.

Was expecting one of:

    "&"
    ","
    "::"
    ";"
    "<<"
    ">>"
    "ACTION"
    "ANY"
    "AS"
    "BYTE"
    "CASCADE"
    "CAST"
    "CHANGE"
    "CHAR"
    "CHARACTER"
    "COLLATE"
    "COLUMN"
    "COLUMNS"
    "COMMENT"
    "COMMIT"
    "CONNECT"
    "CYCLE"
    "DESCRIBE"
    "DISABLE"
    "DO"
    "DUPLICATE"
    "ENABLE"
    "END"
    "EXCEPT"
    "EXTRACT"
    "FALSE"
    "FIRST"
    "FN"
    "FOLLOWING"
    "FOR"
    "FROM"
    "GROUP"
    "HAVING"
    "INDEX"
    "INSERT"
    "INTERSECT"
    "INTERVAL"
    "INTO"
    "ISNULL"
    "KEY"
    "LAST"
    "MATERIALIZED"
    "MINUS"
    "NEXTVAL"
    "NO"
    "NOLOCK"
    "NULLS"
    "OPEN"
    "ORDER"
    "OVER"
    "PARTITION"
    "PATH"
    "PERCENT"
    "PRECISION"
    "PRIMARY"
    "PRIOR"
    "RANGE"
    "READ"
    "REPLACE"
    "ROW"
    "ROWS"
    "SCHEMA"
    "SEPARATOR"
    "SESSION"
    "SIBLINGS"
    "SIZE"
    "START"
    "TABLE"
    "TEMP"
    "TEMPORARY"
    "TOP"
    "TRUE"
    "TRUNCATE"
    "TYPE"
    "UNION"
    "UNSIGNED"
    "VALIDATE"
    "VALUE"
    "VALUES"
    "VIEW"
    "WHERE"
    "WINDOW"
    "XML"
    "ZONE"
    "["
    "^"
    "|"
    <EOF>
    <K_DATETIMELITERAL>
    <K_DATE_LITERAL>
    <S_CHAR_LITERAL>
    <S_IDENTIFIER>
    <S_QUOTED_IDENTIFIER>

	at net.sf.jsqlparser.parser.CCJSqlParser.generateParseException(CCJSqlParser.java:25031)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_consume_token(CCJSqlParser.java:24875)
	at net.sf.jsqlparser.parser.CCJSqlParser.Statement(CCJSqlParser.java:91)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:63)
	... 49 more`

**Expected behavior**

**System**
 - drds , underlying  mysql 5.x
- java8
- JSqlParser version 3.2

**Comment by wumpz** [comment]
By the way 

    select DATE_ADD(now(), INTERVAL rand * 3 DAY)

parses as well. Seems to be some kind of Lookahead problem.

**Comment by wumpz** [comment]
JSqlParser does not support expressions within an interval expression. The problem with my stated last parsing example is, that it will parse 

    Interval rand 

and
   
    3 DAY

as two interval expressions. The later is accepted without the *interval* keyword.

**Comment by zyplayer** [comment]
sql parse failed:
select DATE_SUB(NOW(), INTERVAL DAYOFWEEK(NOW())-1 DAY)

**Comment by manticore-projects** [comment]
Works with 4.1:
```sql
SELECT Date_Sub( Now(), INTERVAL DAYOFWEEK(NOW()) - 1 DAY )
;
```
