### ISSUE TITLE
net.sf.jsqlparser.parser.ParseException : unsupport  unpivot

### ISSUE THREAD

**Issue by JhonLnee** [JSQLParser/JSqlParser#1011]
**Describe the bug**
net.sf.jsqlparser.parser.ParseException : unsupport  unpivot

**To Reproduce**
1. Example SQL : select ctype, cnt from temp unpivot (cnt for ctype in (ARRANGE, FAULT))
2. Parsing this SQL using JSqlParser with this statements

**Comment by wumpz** [comment]
JsqlParser 4 parses this.
