### ISSUE TITLE
error with connect_by_root statement

### ISSUE THREAD

**Issue by lukeSky3434** [JSQLParser/JSqlParser#1016]
SELECT fai.event_time,
         CONNECT_BY_ROOT fai.alarm_id AS alarm_id
  FROM m_failures fai
  WHERE CONNECT_BY_ISLEAF = 1
  CONNECT BY PRIOR fai.alarm_id = fai.parent_alarm_id
  START WITH fai.parent_alarm_id IS NULL

This statement is correct, but I am getting an Exception

Exception in thread "main" net.sf.jsqlparser.JSQLParserException
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:65)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:40)
	at com.knapp.analytics.generator.sql.parser.ParserTest2.main(ParserTest2.java:45)
Caused by: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "." "."

It seems that the parser does not allow alias names for such a construct

**Comment by lukeSky3434** [comment]
The parsing is not working, is it possible to set the body of a WithItem with such an not parseable statement?

			Select stmt = (Select) CCJSqlParserUtil.parse(sql);
			WithItem w = new WithItem();
			w.setName(file.getName());
			w.setSelectBody(stmt.getSelectBody());

**Comment by wumpz** [comment]
The parser does not support this kind of oracle hints for a hierarchical query. **CONNECT BY PRIOR** is supported I think but *connect_by_root* and **CONNECT_BY_ISLEAF = 1** are not.

**Comment by lukeSky3434** [comment]
Is there any possibility on my side to set such a statement in the body of the WithItem?

**Comment by wumpz** [comment]
I don't see any. Maybe you should go to some SQL building library til this feature is implemented. Do you want to provide a pull request?

**Comment by AnEmortalKid** [comment]
I'm working on a patch for this, currently have the connect_by_root operator/expression working. Need to work on adding the pseudo-columns next.
