### ISSUE TITLE
The table name `cache ` is not recognized

### ISSUE THREAD

**Issue by qmdx** [JSQLParser/JSqlParser#1017]
The table name `cache ` is not recognized

`jsqlparser version  3.2`

![17142414](https://user-images.githubusercontent.com/1481125/87755304-5603c480-c839-11ea-9837-463e0665782f.jpg)

**Comment by AnEmortalKid** [comment]
@qmdx can you add a minimal sql that would reproduce this?

**Comment by qmdx** [comment]
> @qmdx can you add a minimal sql that would reproduce this?

select * from cache

**Comment by wumpz** [comment]
Cache is a keyword. To add it as a valid object name the RelObjectName productions have to be modified. Sometimes change is unfortunately hard.

**Comment by qmdx** [comment]
@wumpz
But previous versions are supported

**Comment by wumpz** [comment]
Additional keywords are introduced by supporting new syntactical constructs. So some former identifiers could be now keywords.

**Comment by qmdx** [comment]
Okay, that's closed
