### ISSUE TITLE
Being blocked while parsing a sql with many if keywords

### ISSUE THREAD

**Issue by sixtar** [JSQLParser/JSqlParser#1019]
**Describe the bug**
The program will be blocked if you parse a sql with many if keywords. we encounter this problem in our product environment.

**To Reproduce**
a simplified sql:
```sql
select
IF(1=1 ,IF(1=1 , IF(1=1  , IF(1=1  ,IF(1=1  , IF(1=1  , IF(1=1  ,IF(1=1  , IF(1=1  , IF(1=1  ,IF(1=1  , IF(1=1  ,IF(1=1  , IF(1=1  ,IF(1=1  , IF(1=1  ,IF(1=1  ,IF(1=1  , IF(1=1  ,IF(1=1  , IF(1=1  , IF(1=1  , IF(1=1  , IF(1=1  , IF(1=1  , IF(1=1  ,2 ,IF(1=1  , IF(1=1  ,IF(1=1  , IF(1=1  ,IF(1=1  , IF(1=1  ,IF(1=1  , IF(1=1  ,IF(1=1  , IF(1=1  , IF(1=1  ,IF(1=1  ,IF(1=1  , IF(1=1  ,1 , 2), 1) , 2) , 1), 1), 2) ,1 ), 1) , 1),1 ) ,2 ), 1) , 1),2 ) ),2 ),1 ),2 ),2 ),2 ),2 ) , 1), 1) ,2 ) ,1 ),1 ) ,1 ),1 ) ,2 ),2 ) ,2 ),1 ),2 ) ,1 ),1 ),2 ) ,2 ),2 ),2 ) ,2 )
from dual
```
This sql can be executed correctly and has a result equalling to "2". However,when you use JSqlParser to parse it,the program will be blocked for a very long time and the cpu usage will arise.

**System**
- Java Version 1.8
- JSqlParser version 3.2

**Comment by wumpz** [comment]
This is I indeed a problem and exists due to the relation expression handling as parameters. However I am thinking about a performant change.

**Comment by wumpz** [comment]
The latest version does indeed speed up some of the normal function processings but those conditional parameters are unfortunately hard to tackle.

**Comment by manticore-projects** [comment]
Since 4.1 this will work well for up to 10 levels:
```java
    @Test
    public void testNestedIfIssue1019() throws JSQLParserException {
      assertSqlCanBeParsedAndDeparsed("select\n"
          + "IF(1=1 ,IF(1=1 , IF(1=1  , IF(1=1  ,IF(1=1  , IF(1=1  , IF(1=1  ,IF(1=1  , IF(1=1  , IF(1=1  ,2 ),1 ),2 ) ,1 ),1 ),2 ) ,2 ),2 ),2 ) ,2 )\n"
          + "from dual", true);
    }
```
--> passes within 2 seconds.

However, any deeper nesting will fail to parse when "AllowComplexParsing" is set to false. It will fail immediately without a delay.
If you forcefully set  "AllowComplexParsing", it will hang (for a a very long time).
