### ISSUE TITLE
MySQL backticks

### ISSUE THREAD

**Issue by azapps** [JSQLParser/JSqlParser#103]
MySQL supports backticks for escaping table names. They should be removed from the table/column names.

```sql
CREATE TABLE `animals` (id INT NOT NULL);
```

Yields to the table name \`animals\` instead of animals

**Comment by wumpz** [comment]
The parser definitly supports backticks. If not you could not parse the statement. So where do you get the table name from?

**Comment by azapps** [comment]
Yeah it understands the backticks but does not strip them away

I am doing something like
```CCJSqlParserUtil.parse("CREATE TABLE `animals` (id INT NOT NULL);").getTable().getName()``` 

it returns "\`animals\`"

**Comment by azapps** [comment]
Ok it seems correct to preserve the quotations in this project.
I will just strip them away were I need to.
