### ISSUE TITLE
Failure to parse insert

### ISSUE THREAD

**Issue by voidt** [JSQLParser/JSqlParser#1030]
**Describe the bug**
Throw exception like this when parsing insert statement.
`Caused by: net.sf.jsqlparser.parser.ParseException: Encountered " <S_IDENTIFIER> "t "" at line 1, column 82.
Was expecting one of:
    "SELECT" ...
    "(" ...
    "(" ...`

**To Reproduce**
1. Example SQL 
    `insert into tablename t (t.A, t.B) values(1, 1);`
2. Parsing this SQL using JSqlParser with this statements
3. Exception
    net.sf.jsqlparser.JSQLParserException

**Expected behavior**

**System**
 - Database you are using
- Java Version 1.8
- JSqlParser version 0.9

**Comment by wumpz** [comment]
JSqlParser 0.9 was long ago ... ;)
