### ISSUE TITLE
DECIMAL(current date) is not  support 

### ISSUE THREAD

**Issue by xiaobashagua** [JSQLParser/JSqlParser#1034]
select DECIMAL(current date) as sysdate from sysibm.sysdummy1;   
DECIMAL(current_date)   ok；【DB2】
DECIMAL(current_date)  error;【DB2】

**Comment by wumpz** [comment]
Could you provide the parse exception?

**Comment by wumpz** [comment]
```sql
select DECIMAL(current_date) as sysdate from sysibm.sysdummy1;
```
this one parses using JSqlParser 4.
