### ISSUE TITLE
MySQL inline primary keys

### ISSUE THREAD

**Issue by azapps** [JSQLParser/JSqlParser#104]
The parser does not find the primary key in the following statement:

``` sql
CREATE TABLE animals (
id INT PRIMARY KEY NOT NULL
);
```

this statement is of course not a problem:

``` sql
CREATE TABLE animals (
id INT NOT NULL,
PRIMARY KEY (id));
```

The same thing occurs obviously also with inline Indexes.

I don't know if that is easy to fix. And it does not have a high priority for me ;)

**Comment by wumpz** [comment]
I tried your SQL and JSqlParser was able to parse it. So what do you mean with: " does not find the primary key"? The create table statement ist parsed in a very specific way. The primary key are stored as column definition addition. Maybe you looked at the wrong place within the createTable object?

**Comment by azapps** [comment]
Ok, yes that is true. I can access the primary key constrain via `getColumnSpecStrings()`. But it would be nicer to have it in the `getIndexes()` of the table. But this shouldn't be possible to do without post-processing!?

**Comment by wumpz** [comment]
Sure it would be better. Is this something you could provide? Pull requests are wellcome.

**Comment by azapps** [comment]
I've never worked wit JavaCC but will try to implement this when I find some time ;)

**Comment by wumpz** [comment]
Closing for now. Never had time to resolve this.
