### ISSUE TITLE
Support 'ADD CONSTRAINT.... ON DELETE <RESTRICT, CASCADE, UPDATE>

### ISSUE THREAD

**Issue by dprutean** [JSQLParser/JSqlParser#1042]
Statements like this are failling: 

ALTER TABLE dbo.StockTaskPartSku ADD CONSTRAINT FK_StockTaskPartSku_PartSku FOREIGN KEY ( PartSkuID ) REFERENCES dbo.PartSku( ID ) ON DELETE restrict ON UPDATE restrict;

Can we support them ?

**Comment by gitmotte** [comment]
this is implemented with  [latest snapshot version 4.0](https://github.com/JSQLParser/JSqlParser#extensions-in-the-latest-snapshot-version-40)

**Comment by wumpz** [comment]
I will close this.
