### ISSUE TITLE
Class not found

### ISSUE THREAD

**Issue by yueru** [JSQLParser/JSqlParser#1043]
Excuse me, 
Where is the CCJSqlParser class ? I have not found it on the master branch.

**Comment by FoxInNorth** [comment]
U can check JSqlParserCC.jjt   
CCJSqlParser class will be generated from JSqlParserCC.jjt by JavaCC.
U can build the project with maven:  mvn package

**Comment by wumpz** [comment]
The complete release is available at maven central: `https://search.maven.org/artifact/com.github.jsqlparser/jsqlparser/3.2/jar`.
