### ISSUE TITLE
Parser error with SQL function with arguments where string-concat is also placed 

### ISSUE THREAD

**Issue by ranjit-p** [JSQLParser/JSqlParser#1044]
**Describe the bug**
Attempt to parse SELECT statement with a condition line INSTR(FIELD_NAME,','||?||',') is failing with the error - 

> net.sf.jsqlparser.JSQLParserException
> 	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:51)
> 	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:40)
> 	at SelectSqlParser.main(SelectSqlParser.java:24)
> Caused by: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "(" "("
>     at line 1, column 153.
> 
> Was expecting one of:
> 
>     "&"
>     "&&"
>     ")"
>     "::"
>     "<<"
>     ">>"
>     "AND"
>     "COLLATE"
>     "CONNECT"
>     "EXCEPT"
>     "FOR"
>     "GROUP"
>     "HAVING"
>     "INTERSECT"
>     "MINUS"
>     "ORDER"
>     "START"
>     "UNION"
>     "["
>     "^"
>     "|"
> 
> 	at net.sf.jsqlparser.parser.CCJSqlParser.generateParseException(CCJSqlParser.java:21726)
> 	at net.sf.jsqlparser.parser.CCJSqlParser.jj_consume_token(CCJSqlParser.java:21573)
> 	at net.sf.jsqlparser.parser.CCJSqlParser.FromItem(CCJSqlParser.java:5175)
> 	at net.sf.jsqlparser.parser.CCJSqlParser.PlainSelect(CCJSqlParser.java:3602)
> 	at net.sf.jsqlparser.parser.CCJSqlParser.SetOperationList(CCJSqlParser.java:3795)
> 	at net.sf.jsqlparser.parser.CCJSqlParser.SelectBody(CCJSqlParser.java:3477)
> 	at net.sf.jsqlparser.parser.CCJSqlParser.Select(CCJSqlParser.java:3470)
> 	at net.sf.jsqlparser.parser.CCJSqlParser.SingleStatement(CCJSqlParser.java:124)
> 	at net.sf.jsqlparser.parser.CCJSqlParser.Statement(CCJSqlParser.java:75)
> 	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:49)
> 	... 2 more
> Caused by:
> net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "(" "("
>     at line 1, column 153.
> 
> Was expecting one of:
> 
>     "&"
>     "&&"
>     ")"
>     "::"
>     "<<"
>     ">>"
>     "AND"
>     "COLLATE"
>     "CONNECT"
>     "EXCEPT"
>     "FOR"
>     "GROUP"
>     "HAVING"
>     "INTERSECT"
>     "MINUS"
>     "ORDER"
>     "START"
>     "UNION"
>     "["
>     "^"
>     "|"
> 
> 	at net.sf.jsqlparser.parser.CCJSqlParser.generateParseException(CCJSqlParser.java:21726)
> 	at net.sf.jsqlparser.parser.CCJSqlParser.jj_consume_token(CCJSqlParser.java:21573)
> 	at net.sf.jsqlparser.parser.CCJSqlParser.FromItem(CCJSqlParser.java:5175)
> 	at net.sf.jsqlparser.parser.CCJSqlParser.PlainSelect(CCJSqlParser.java:3602)
> 	at net.sf.jsqlparser.parser.CCJSqlParser.SetOperationList(CCJSqlParser.java:3795)
> 	at net.sf.jsqlparser.parser.CCJSqlParser.SelectBody(CCJSqlParser.java:3477)
> 	at net.sf.jsqlparser.parser.CCJSqlParser.Select(CCJSqlParser.java:3470)
> 	at net.sf.jsqlparser.parser.CCJSqlParser.SingleStatement(CCJSqlParser.java:124)
> 	at net.sf.jsqlparser.parser.CCJSqlParser.Statement(CCJSqlParser.java:75)
> 	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:49)
> 	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:40)
> 	at SelectSqlParser.main(SelectSqlParser.java:24)

**To Reproduce**
1. Example SQL
`SELECT SP_ID FROM ST_PR WHERE INSTR(','||SP_OFF||',',','||?||',')>0`
2. Parsing this SQL using JSqlParser with this statements
`net.sf.jsqlparser.statement.Statement select = (Statement) CCJSqlParserUtil.parse(SQL);`
3. Exception
`As mentioned under bug description`
**Expected behavior**

> The parsing of the particular SQL should happen, and not throw exception. Suppose the SQL is 

> `SELECT SP_ID FROM ST_PR WHERE INSTR(SP_OFF,?)>0`

> the parsing works perfectly fine.

**System**
 - Database you are using

> Any database - presently using Oracle 12c

- Java Version

> 1.8

- JSqlParser version

> 3.0

**Comment by wumpz** [comment]
JSqlParser does parse this perfectly well, if you insert spaces at the right places. The problem in your case is that JSqlParser does accept '?|' as a JSON pattern.

**Comment by ranjit-p** [comment]
Thanks. Didn't try with the 
`SELECT SP_ID FROM ST_PR WHERE INSTR(','||SP_OFF||',',','|| ? ||',')>0`
Adding the whitespace between the double-pipe and question-mark character is making the parsing work without any exception.

Please note, we have this JSqlParser layer included in a general framework, and at the moment we do not have any control on the SQL strings coming in to the framework. It looks like we may have to do a string replace of **|?|** to **_| ? |_** within our framework, if JSqlParser is expected to follow any such standard pattern on the SQL string it handles.

But, wouldn't this particular string pattern be a case that could be considered handling within JSqlParser? Or, is there already a method available in JSqlParser to forcibly escape JSON pattern?

**Comment by jeremywalsh** [comment]
Another example without ? marks:

select CONCAT(field1, RIGHT(('0000000' || field2), 7)) as a_result from table

**Comment by jeremywalsh** [comment]
I think this has more to do with the word RIGHT, maybe its getting confused by collision with the phrase "RIGHT JOIN".  I thought at first it was not dealing well with nested function calls, but if the "right" above was "rtrim", I think it works fine.

**Comment by ranjit-p** [comment]
> I think this has more to do with the word RIGHT, maybe its getting confused by collision with the phrase "RIGHT JOIN". I thought at first it was not dealing well with nested function calls, but if the "right" above was "rtrim", I think it works fine.

`String sSQL = "select CONCAT(field1, RIGHT(('0000000' || field2), 7)) as a_result from someTable";`
is not giving the exception in the line below, as it gives with a `||?||`, 
`net.sf.jsqlparser.statement.Statement select = (net.sf.jsqlparser.statement.Statement) net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(sSQL);` 
Version - jsqlparser-3.0.jar.

**Comment by jeremywalsh** [comment]
@ranjit-p  I believe I mistakenly was using an old version of the library, my coworker discovered it today and I havent' been able to get back and test yet.

**Comment by wumpz** [comment]
So should we close this?

**Comment by jeremywalsh** [comment]
No issues here

**Comment by ranjit-p** [comment]
For the general framework scenario where we are applying the JSqlParser, so far it has been challenging for us to identify the incorrectly made SQL constructs (with regard to _||?||_ cases) and make changes. Also, a coding guideline, review checklist is also something we are thinking of. It would've really helped if there was some means to pass some flags to JSqlParser parsing method to override or escape _'?|'_ as a JSON pattern.

**Comment by wumpz** [comment]
To be honest I am not convinced that this should somehow be implemented. However, if you want some kinds of tokens to be blocked, you could easily remove this part from the grammar (line 2661) or make your own decision, how the actual token should be treated (grammar line 413).

**Comment by ranjit-p** [comment]
Sorry, couldn't figure out the line numbers, and the context of the grammar related details that is being asked to be looked into. Is it in is a specific class in the JSqlParser library?

**Comment by wumpz** [comment]
There is one jjt file in the project. This is a javacc (jjtree) grammar file. The parser classes are generated in the normal maven build.Cheers Tobias
-------- Ursprüngliche Nachricht --------Von: ranjit-p <notifications@github.com> Datum: 24.11.20  19:32  (GMT+01:00) An: JSQLParser/JSqlParser <JSqlParser@noreply.github.com> Cc: Tobias <t.warneke@gmx.net>, Comment <comment@noreply.github.com> Betreff: Re: [JSQLParser/JSqlParser] Parser error with SQL function with
  arguments where string-concat is also placed  (#1044) 
Sorry, couldn't figure out the line numbers, and the context of the grammar related details that is being asked to be looked into. Is it in is a specific class in the JSqlParser library?

**Comment by ranjit-p** [comment]
Thank you. Commenting line 2661 made it work. But, it has not been possible to work on decision area around line 413. 
We were trying to see if there was some global level condition that can be passed on to the decision area around 413, but due to lack of jjtree knowledge we weren't even able to move into this JJT code.

**Comment by wumpz** [comment]
Sorry I did not describe it well. Line 413 shows how a semantic decision is done for the token manager to somehow accept another token. This type of *method* should be introduced within this 2661 rule to make a better decision. But this is kind of difficult, because you are discard the actual token, push it back into the data stream and accept another token instead. So you should know, what you are doing.
