### ISSUE TITLE
Jsqlparser can support  Kylin and  impala and hive?

### ISSUE THREAD

**Issue by autumn-luo** [JSQLParser/JSqlParser#1048]
Jsqlparser can support  Kylin and  impala and hive?

**Comment by AnEmortalKid** [comment]
If you can add grammar to it, yes, probably

**Comment by wumpz** [comment]
JSqlParser is a general parser with features of multiple databases. The development is feature driven. So please specify SQL features and not complete database grammars.

**Comment by wumpz** [comment]
So which features do you need?
