### ISSUE TITLE
Alter table → add primary key/index

### ISSUE THREAD

**Issue by azapps** [JSQLParser/JSqlParser#105]
JSqlParser can not parse statements like this here:

```sql
ALTER TABLE animals
  ADD PRIMARY KEY (id);

ALTER TABLE `schema_migrations`
  ADD UNIQUE KEY `unique_schema_migrations` (`version`);
```

Sorry for creating a lot of issues

**Comment by wumpz** [comment]
No problem. This is the way to do it, to create issues.

**Comment by wumpz** [comment]
Are you positive that alter table ... add unique key ... does work? All documentation stats 
alter table ... add unique ...   (without the key keyword).

**Comment by azapps** [comment]
Yes, `ADD UNIQUE KEY` works. And the [documentation](http://dev.mysql.com/doc/refman/5.1/en/alter-table.html) states this too: 
```sql
  | ADD [CONSTRAINT [symbol]]
        UNIQUE [INDEX|KEY] [index_name]
        [index_type] (index_col_name,...) [index_option] ...
```

Also without the `KEY` it does not parse.
```sql
ALTER TABLE `schema_migrations`
  ADD UNIQUE `unique_schema_migrations` (`version`);
```
Yields to
```
ParseException Encountered " <S_IDENTIFIER> "UNIQUE "" at line 3, column 7.
Was expecting:
    "COLUMN" ...
```
If I see it correctly the `Alter` parser supports only modifying columns.
