### ISSUE TITLE
Extend grammar to support functions with multiple argument lists

### ISSUE THREAD

**Issue by vofque** [JSQLParser/JSqlParser#1050]
I'm trying to use JSqlParser for Clickhouse requests which supports functions with multiple argument lists like func(a, b)(c, d).
Is it possible to extend grammar to support such functions? Could you give a hint about how to do that?

**Comment by wumpz** [comment]
Sure. This would be no problem: you should adapt the function production: `Function Function() #Function:` starting at line 3725 of the grammar file.
