### ISSUE TITLE
execute statement does not support qualified name

### ISSUE THREAD

**Issue by xsgao-github** [JSQLParser/JSqlParser#1054]
**Describe the bug**
This code errors out: `net.sf.jsqlparser.parser.CCJSqlParserUtil.parse("EXEC sch.proc 'p0'")` Because Execute statement does not support qualified name, e.g. schema.proc. In Execute.java, name is only a string instead of a Table object.

**To Reproduce**
1. Execute this Java code. `net.sf.jsqlparser.parser.CCJSqlParserUtil.parse("EXEC sch.proc 'p0'")`
2. Exception: `net.sf.jsqlparser.parser.ParseException: Encountered " "." ". "" at line 1, column 9.`

**Expected behavior**
Execute should support qualified names.

**System**
- SQL
- 1.8
- latest

**Comment by wumpz** [comment]
This is fixed since #684. I think this should be working at least with version 3.0 of JSqlParser. So which version do you use? I tested this with JSqlParser 4.0-SNAPSHOT and it worked.

**Comment by wumpz** [comment]
So could we close this issue?

**Comment by AnEmortalKid** [comment]
I vote close @wumpz
