### ISSUE TITLE
net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "." "."

### ISSUE THREAD

**Issue by bai020** [JSQLParser/JSqlParser#1067]
Caused by: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "." "."

version：3.2
SQL：
select t0_.full_station_id as col_0_0_, t0_.connector_name as col_1_0_, t0_.connector_type as col_2_0_, t0_.is_removed as col_3_0_, t2_.city_name as col_4_0_, t0_.voltage_upper_limits as col_5_0_, t0_.voltage_lower_limits as col_6_0_, t0_.current as col_7_0_, t0_.dd_status as col_8_0_, t0_.op_connector_statusas col_9_0_, t1_.id as col_10_0_, t1_.operator_id as col_11_0_, t1_.operator_name as col_12_0_, t2_.address as col_13_0_, t2_.dd_status as col_14_0_, t2_.station_name as col_15_0_, t2_.station_id as col_16_0_, stationequ3_.equipment_id as col_17_0_, t2_.city_area_code as col_18_0_, t2_.merchant_id as col_19_0_, t2_.station_lat as col_20_0_, t2_.station_lng as col_21_0_, t2_.gate_lat as col_22_0_, t2_.gate_lng as col_23_0_ from table0 t0_ 
cross join table1 t1_ 
cross join table2 t2_ 
cross join table3 stationequ3_ 
where t0_.connector_id=? and stationequ3_.full_equipment_id=t0_.full_equipment_id and t2_.full_station_id=t0_.full_station_id and t1_.operator_id=t2_.operator_id

method：
 public static Set<String> getTableNamesBySql(String sql) {
        CCJSqlParserManager parser = new CCJSqlParserManager();
        Set<String> tableNames = new HashSet<>();
        try{
            Statement stmt = parser.parse(new StringReader(sql));
            if (stmt instanceof Select) {
                Select selectStatement = (Select) stmt;
                TablesNamesFinder tablesNamesFinder = new TablesNamesFinder();
                List tableList = tablesNamesFinder.getTableList(selectStatement);
                for (Iterator iter = tableList.iterator(); iter.hasNext();) {
                    tableNames.add(iter.next().toString());
                }
            }
        }catch (JSQLParserException e){
            log.error("parser sql error for metric trace={} sql:{}", TraceContext.getInstance().getTraceId(), sql, e);
        }
        return tableNames;
    }

**Comment by cur3n4** [comment]
This might be due to the column named current, try to escape t0_.current as `t0_.current`.

**Comment by bai020** [comment]
Thank you !
I'm going to try to change the structure of the following table;
