### ISSUE TITLE
Logical Operator Precedence (QUESTION)

### ISSUE THREAD

**Issue by ebocher** [JSQLParser/JSqlParser#1070]
**Describe the question**

I have a doubt about operator precedence
Indeed the following code
```java
CCJSqlParserUtil.parseCondExpression("TYPE=1 or TYPE= 2 and OS=25", false);
```
return OrExpression

Shouldn't this be

return AndExpression due to the higher precedence of And ?

**To Reproduce**

CCJSqlParserUtil.parseCondExpression("TYPE=1 or TYPE= 2 and OS=25", false);

**System**
 - Database you are using
- Java Version : >8 
- JSqlParser version : 3.2

**Comment by wumpz** [comment]
IMHO no, since the evaluation of those trees is done from the leaves to the root. Therefore the **AND** is processed first. For example, if you process a numeric expression like **5 + 3 * 2** then you will get something like:

    ADDITION
           5
           MULTIPLICATION
                 3
                 2

**Comment by ebocher** [comment]
Thanks
I close it
