### ISSUE TITLE
Has already support sql like SELECT * INTO newtable FROM table1 WHERE 1=1;? 

### ISSUE THREAD

**Issue by wat1r** [JSQLParser/JSqlParser#1071]
JSqlParser helps a lot ,  pretty good.

I reviewed then closed issues and opened issues want to find the examples like 
```
SELECT *
INTO newtable
FROM table1
WHERE 1=1;
```

the `newtable`  **should not be exists**

find some cases like 
https://github.com/JSQLParser/JSqlParser/issues/950
https://github.com/JSQLParser/JSqlParser/issues/65

in issue-950 , the example is good

issue-950  implements the sql like  ` insert into  new_table select * from old_table`   
which  the `new_table `   **should be  exists**;

Has already support sql like 
```
SELECT * INTO newtable FROM table1 WHERE 1=1;
```
? 

version : 3.1

**Comment by wumpz** [comment]
This kind of statement is supported. Unfortunately I am not sure in which version it was included. However the corresponding commit seems to be from 2014.

**Comment by wat1r** [comment]
You mean the nearly  latest version  3.1 may not support this kind of sql?
I

**Comment by wumpz** [comment]
No. I meant this should be included at least since version 2 or so. 3.1 should definitely support this. If not, then there is another problem I guess.

**Comment by wat1r** [comment]
Thanks, I using the following code like this: 
```sql
        sql = "SELECT * INTO newtable FROM table1 WHERE 1=1";
        Select select = (Select) CCJSqlParserUtil.parse(sql);
        PlainSelect plainSelect = (PlainSelect) select.getSelectBody();
        System.out.printf("SSS");
```

**Comment by wumpz** [comment]
JSqlParser 4.0 parses this.
