### ISSUE TITLE
 SQL-Ausnahme analysieren

### ISSUE THREAD

**Issue by zero-wsh** [JSQLParser/JSqlParser#1074]
**Describe the bug**
Parsing SQL exception, the SQL can be executed normally, the database used is sqlserver2012

**To Reproduce**
1. Example SQL
select *  from t_user with (nolock)
2. Parsing this SQL using JSqlParser with this statements
CCJSqlParserUtil.parse(originalSql)
3. Exception

**Expected behavior**

**System**
 - Database you are using
- Java Version 1.8
- JSqlParser version 3.1

**Comment by wumpz** [comment]
Since version 3.2 this should work. There these SQLServer hints were introduced.
