### ISSUE TITLE
Regression in parsing statement with column named 'sequence' in versions 3.2 and 4.0-SNAPSHOT

### ISSUE THREAD

**Issue by leonardoarcari** [JSQLParser/JSqlParser#1075]
**Describe the bug**
Starting from `3.2` release, I'm no longer able to parse a `SELECT` statement where a column is named `sequence`.

As far as I can see from previous issues, this is related to `SEQUENCE` keyword introduced in `3.2`, but not added to `RelObjectName()` production in [JSQLParserCC.jit](https://github.com/JSQLParser/JSqlParser/blob/master/src/main/jjtree/net/sf/jsqlparser/parser/JSqlParserCC.jjt)

**To Reproduce**

*Example SQL*
```sql
select a.sequence from all_procedures a
```

*Parsing this SQL using JSqlParser with this statements*
```java
import net.sf.jsqlparser.JSQLParserException;
import net.sf.jsqlparser.parser.CCJSqlParserUtil;
import net.sf.jsqlparser.statement.Statement;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertThrows;

public class TestSqlParser {
  static final String failingQuery = "select a.sequence from all_procedures a";

  @Test
  void testFailingParsing() throws JSQLParserException {
    assertThrows(
        JSQLParserException.class,
        () -> {
          CCJSqlParserUtil.parse(failingQuery);
        });
  }

  @Test
  void testEscapedParsing() throws JSQLParserException {
    final String escaped = failingQuery.replace("a.sequence", "a.\"sequence\"");
    final Statement statement = CCJSqlParserUtil.parse(escaped);
    assertNotNull(statement);
  }
}
```

*Exception*
```java
JSQLParserException.class
```

**Expected behavior**
This is being parsed fine in `3.1`, prior to `SEQUENCE` keyword introduction

**System**
 - Database you are using: `Oracle 12c`
- Java Version: `11`
- JSqlParser version: `3.2` and `4.0-SNAPSHOT`

**Comment by wumpz** [comment]
That is because since version 4 JSqlParser supports a **create sequence** statement. Therefore **sequence** is a new keyword. I will make this possible again.
