### ISSUE TITLE
net.sf.jsqlparser.parser.ParseException  Encountered unexpected token: "exists" "EXISTS"

### ISSUE THREAD

**Issue by feipengcheng** [JSQLParser/JSqlParser#1076]
SELECT
            lv.NAME,
            lv.unit,
            lv.phone,
            lv.type,
            lvg.card_no,
            lvg.place,
            exists(select 1 from location_warn lw where lw.card_no = lvg.card_no and hand_time is null) ifWarn,
            lvg.in_time,
            lvg.out_time

        FROM
            location_visitor_log lvg
        LEFT JOIN location_visitor lv ON lv.id = lvg.visitor_id

net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "exists" "EXISTS"
    at line 8, column 13.

Was expecting one of:

    "!"
    "("
    "*"
    "+"
    "-"
    ":"
    "?"
    "@"
    "@@"
    "ACTION"
    "ANY"
    "BYTE"
    "CASCADE"
    "CASE"
    "CAST"
    "CHANGE"
    "CHAR"
    "CHARACTER"
    "COLUMN"
    "COLUMNS"
    "COMMENT"
    "COMMIT"
    "CREATE"
    "CURRENT"
    "CYCLE"
    "DESCRIBE"
    "DISABLE"
    "DO"
    "DOUBLE"
    "DUPLICATE"
    "ENABLE"
    "END"
    "EXTRACT"
    "FALSE"
    "FIRST"
    "FN"
    "FOLLOWING"
    "GROUP"
    "GROUP_CONCAT"
    "IF"
    "IIF"
    "INDEX"
    "INSERT"
    "INTERVAL"
    "ISNULL"
    "KEY"
    "LAST"
    "LEFT"
    "LIMIT"
    "MATCH"
    "MATERIALIZED"
    "NEXTVAL"
    "NO"
    "NOLOCK"
    "NOT"
    "NULL"
    "NULLS"
    "OFFSET"
    "ON"
    "OPEN"
    "OPTIMIZE"
    "ORDER"
    "OVER"
    "PARTITION"
    "PATH"
    "PERCENT"
    "PRECISION"
    "PRIMARY"
    "PRIOR"
    "PROCEDURE"
    "RANGE"
    "READ"
    "REPLACE"
    "RIGHT"
    "ROW"
    "ROWS"
    "SCHEMA"
    "SEPARATOR"
    "SESSION"
    "SET"
    "SIBLINGS"
    "SIZE"
    "START"
    "TABLE"
    "TEMP"
    "TEMPORARY"
    "TOP"
    "TRUE"
    "TRUNCATE"
    "TYPE"
    "UNSIGNED"
    "VALIDATE"
    "VALUE"
    "VALUES"
    "VIEW"
    "XML"
    "ZONE"
    "{"
    "{d"
    "{t"
    "{ts"
    "~"
    <K_DATETIMELITERAL>
    <K_DATE_LITERAL>
    <K_TIME_KEY_EXPR>
    <S_CHAR_LITERAL>
    <S_DOUBLE>
    <S_HEX>
    <S_IDENTIFIER>
    <S_LONG>
    <S_QUOTED_IDENTIFIER>

**Comment by wumpz** [comment]
Which version of JSQLParser do you use? I tested the following SQL that should be a minimized example of yours and it got processed just fine:

    SELECT mycol, EXISTS (SELECT mycol FROM mytable) mycol2 FROM mytable

**Comment by wumpz** [comment]
So may we close this one?
