### ISSUE TITLE
net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: ">" ">" 

### ISSUE THREAD

**Issue by ZhouLiDong** [JSQLParser/JSqlParser#1077]
（1）exception：
net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: ">" ">" 

（2）test code
` CCJSqlParser parser = new CCJSqlParser(new StringProvider("SELECT 1 > 0 "));
        Statements statements = parser.Statements();
        System.out.println(statements);`

（3）System
- Java 8
- JSqlParser 1.2~3.1

**Comment by wumpz** [comment]
So I guess you figured out, that this is supported now?
