### ISSUE TITLE
[JSQLParserException] When sql contains "format" function,CCJSqlParserUtil.parse will throw exception

### ISSUE THREAD

**Issue by kayeez** [JSQLParser/JSqlParser#1078]
**Describe the bug**
When sql contains "format" function,CCJSqlParserUtil.parse will throw exception

**To Reproduce**
1. Example SQL:
    select FORMAT(date, 'yyyy-MM') as year_month from mine_table
2. Parsing this SQL using JSqlParser with this statements
    CCJSqlParserUtil.parse(sourceSQL)
3. Exception
    net.sf.jsqlparser.JSQLParserException
    Caused by: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "FORMAT" "FORMAT"
**Expected behavior**
1.explain why does this exception is throwed
2.Will it be fixable
3.What can i do for not throwing this exception

**System**
 - Database you are using:SQLServer
- Java Version:1.8
- JSqlParser version:3.2

**Comment by wumpz** [comment]
This was closed within #1040. Therefore, you have to use version 4.0-SNAPSHOT or wait til it is released.
