### ISSUE TITLE
JSqlParser not support Mysql MATCH AGAINST

### ISSUE THREAD

**Issue by willzhujian** [JSQLParser/JSqlParser#1079]

**Comment by wumpz** [comment]
So could you provide an example SQL?

**Comment by happyWhl** [comment]
> So could you provide an example SQL?

Me, too。this sql:
SELECT
	count( id ) 
FROM
	sync_bulletin 
where
	MATCH ( user_scope ) against ( '1111111' )

**Comment by lanfen100** [comment]
@wumpz 
Has the problem been solved ?

**Comment by wumpz** [comment]
No. Not yet. PRs are welcome. Sorry. Have not much time.

**Comment by manticore-projects** [comment]
Works with latest 4.2, you can try it [online and interactively here](http://jsqlformatter.manticore-projects.com/jsqlformatter/demo.html?args=-c%20MoUQMiDCAqAEkHsCuA7ALgClgSwCawEoAoAMQCUB5AWVgGcBPFAYwH0AjJAG04FM1sURAOoAJEGRCwqAQWiQRsDElo8ATi1pMEABx4FY0gOLSAkgDlgcDAHIAjPYe3rxANxA+).

**Comment by yiky84119** [comment]
NOT WORK 4.6 ?

**Comment by manticore-projects** [comment]
Works.
