### ISSUE TITLE
SQL "update" statement does not recognize queries as array indexes

### ISSUE THREAD

**Issue by freya022** [JSQLParser/JSqlParser#1083]
**Describe the bug**
SQL "update" statement with an array index are not recognized

**To Reproduce**
1. Example SQL
`update utilisateur set listes[(select cardinality(listes))] = 1;`
2. Parsing this SQL using JSqlParser with this statements
```java
final String query = "update utilisateur set listes[(select cardinality(listes))] = 1;";
final List<ValidationError> validate = Validation.validate(List.of(DatabaseType.POSTGRESQL), query);
```
3. Exception
```
Exception in thread "main" net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "[" "["
    at line 1, column 30.

Was expecting one of:

    ","
    "="

	at net.sf.jsqlparser.parser.CCJSqlParser.generateParseException(CCJSqlParser.java:26615)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_consume_token(CCJSqlParser.java:26454)
	at net.sf.jsqlparser.parser.CCJSqlParser.Update(CCJSqlParser.java:1382)
```

**Expected behavior**
The query should be valid

This SQL statement is valid though :
`select messages from liste where login = 'test' order by messages[(select cardinality(messages) from liste where idliste = 1)] asc;`

**System**
- Database you are using : PostgreSQL 13
- Java Version : 15
- JSqlParser version : 4.0-SNAPSHOT

**Comment by wumpz** [comment]
This is not (yet) supported. PRs are wellcome.

**Comment by manticore-projects** [comment]
Greetings!

Apologies for responding so late, I really do not use Arrays in Databases.
However,  I stumbled over this when refactoring a lot of the Grammar for a 5.0 relase: `UPDATE ... SET ( UPDATESET )* ` with `UPDATESET := COLUMN = EXPRESSION`, we strictly expect columns here.

So am I correct, that we are still referring to a `COLUMN`, but one that is defined as an `ARRAY` and so we actually will need to amend the `COLUMN` production (for allowing arrays, and not just identifiers)?

**Comment by manticore-projects** [comment]
> we actually will need to amend the `COLUMN` production (for allowing arrays, and not just identifiers)

I just did that and it seems to work!
