### ISSUE TITLE
When is validation supported by jsqlparser in Maven warehouse？

### ISSUE THREAD

**Issue by yidou120** [JSQLParser/JSqlParser#1086]
**Expected behavior**
When is validation supported by jsqlparser in Maven warehouse？
Jsql validation is not supported in jsql3.0.The latest version of jsqlparser in Maven is 3.2，but not 4.0,so not the validation function.

**Comment by wumpz** [comment]
The validation is part of JSqlParser 4. This version is not yet released. You could use version 4.0-SNAPSHOT, which is released at sonatype.

**Comment by wumpz** [comment]
Look at #1069.
