### ISSUE TITLE
CCJSqlParserUtil.parse(originalSql) Exception

### ISSUE THREAD

**Issue by yao752915708** [JSQLParser/JSqlParser#1088]
Describe the bug
I use the mybatis, and My sql in xml is SELECT p.*,rhp.house_id FROM rel_house_person rhp  INNER JOIN person p ON rhp.person_id = p.if  WHERE rhp.house_id in (  select house_id from rel_house_person  where person_id=:personId and current_occupant =:current)  and rhp.current_occupant =:currentOccupant
so I use the CCJSqlParserUtil.parse(originalSql); to parse my sql, but it throw exception

To Reproduce

SELECT p.*,rhp.house_id FROM rel_house_person rhp  INNER JOIN person p ON rhp.person_id = p.if  WHERE rhp.house_id in (  select house_id from rel_house_person  where person_id=:personId and current_occupant =:current)  and rhp.current_occupant =:currentOccupant

CCJSqlParserUtil.parse(originalSql);
Exception

**Comment by wumpz** [comment]
The problem was the use of **current** as a parameter name. This is now allowed within the latest JSqlParser 4.0-SNAPSHOT.

**Comment by yao752915708** [comment]
thanks
