### ISSUE TITLE
Exception with 'Create Domain' statements

### ISSUE THREAD

**Issue by wise-coders** [JSQLParser/JSqlParser#1090]
Using JSqlParser 3.2 I get an exception when parsing: 

```
create domain TNOTIFICATION_ACTION as ENUM ('ADD', 'CHANGE', 'DEL')

Encountered unexpected token: "create" "CREATE"
    at line 1, column 1.
```

**Comment by wumpz** [comment]
Thats right, because this statement is not supported by JSqlParser.

PRs are welcome.

**Comment by AnEmortalKid** [comment]
@wise-coders  if you want a bit of hints on how you could add this, I did something similar for view here: https://github.com/JSQLParser/JSqlParser/pull/977
