### ISSUE TITLE
AST Tree design

### ISSUE THREAD

**Issue by tech8exp** [JSQLParser/JSqlParser#1092]
This is not an issue, rather, it is just a question to understand the design of AST nodes.

I noticed that access and expression nodes have links to each others... similar to the picture below. 

![image](https://user-images.githubusercontent.com/76964427/103568550-be03a100-4e93-11eb-8038-2d5163d514ce.png)

My question is: Is that just for easy traversal, for instance, if one is on expression node and has to jump to access node or vice  versa then it is easier with bi directional links? OR is there an other reason for these bi directional links?

**Comment by wumpz** [comment]
Easy traversal is one argument. For instance, while using the visitor pattern to traverse the parse objects sometimes it is necessary to e.g. get the exact textual position which is stored in the AST tree node.

**Comment by wumpz** [comment]
So does this answer your question.
