### ISSUE TITLE
Union with selects wrapped in parenthesis doesn't parse on 4.1

### ISSUE THREAD

**Issue by tomershay** [JSQLParser/JSqlParser#1094]
**Describe the bug**
The following query fails parsing in v4.1, while it worked with previous versions.
It seems that the parser fails only when the two queries in the union are wrapped with parenthesis.

Parser fails with:
```
SELECT
  *
FROM
  (
    (
      SELECT
        A
      FROM
        tbl
    )
    UNION
      DISTINCT (
        SELECT
          B
        FROM
          tbl2
      )
  ) AS union1

```

Parser doesn't fail with:
```
SELECT
  *
FROM
  (
      SELECT
        A
      FROM
        tbl
    UNION
      DISTINCT
        SELECT
          B
        FROM
          tbl2
  ) AS union1

```

**Comment by tomershay** [comment]
Update after exploring further - it seems this issue started after these changes were applied: 36d0b7420fe92252c4b6dd62707bceb5efafc5b9
When manually semi-reverting the changes in `FromItem()`, the parser successfully parsed the query in the sample above.
It seems that `SubSelect()` should be looked for before `FromItem()`, as otherwise some use cases are missed.

**Comment by tomershay** [comment]
hi @wumpz, any thoughts on how this can be fixed? I'll be happy to contribute a PR, though need some guidance in regards to the logic behind the original refactoring at 36d0b7420fe92252c4b6dd62707bceb5efafc5b9 to make sure I go at it with the right mindset. thanks!

**Comment by wumpz** [comment]
Let me look into it.

At first I don't want to lose the performance gain. This is a very problematic case, since flipping SubSelect and FromItem needs a complete Lookahead of SubSelect and this would introduce problems again.

**Comment by wumpz** [comment]
I deployed a new version, so to say a first try to tackle this problem. Your SQL is parsed, but deeper hierarchies are not yet supported.

**Comment by tomershay** [comment]
Confirmed it's working for one level, thank you for the quick fix!
Any thoughts on how to tackle deeper hierarchies support?
I'll have a look to see if I can make any progress on that as well.

**Comment by wumpz** [comment]
I am still on it. The deeper levels should be no problem. But it's too late now.

**Comment by wumpz** [comment]
I have the next version deployed. now deeper hierarchies are parsed. But the deparsing is not like the original.

**Comment by tomershay** [comment]
Thank you for the quick follow up on this, very useful changes!

**Comment by wumpz** [comment]
So can I close this issue?

**Comment by tomershay** [comment]
Yes, thanks again.
