### ISSUE TITLE
can't parse the sql  that  delete multiple tables at the same time.

### ISSUE THREAD

**Issue by fanchuanlin** [JSQLParser/JSqlParser#1096]
**Describe the bug**
can't parse delete sql

**To Reproduce**
1. my sql statement is [delete r.\*,au.\* from test_role r left join test_role_auth au on r.id=au.roleid where r.id=100]
2. Parsing this SQL using JSqlParser with this statements
3. Exception [Encountered unexpected token: "." "."]

**Expected behavior**
i used [CCJSqlParserUtil.parse] to parse my sql statement, but i got an exception

**System**
- mysql
- jdk 1.8
- 4.0

**Comment by wumpz** [comment]
This is not (yet) supported of JSqlParser.

**Comment by fanchuanlin** [comment]
thank you
