### ISSUE TITLE
The SQL script contains field names that begin with a number to resolve exceptions

### ISSUE THREAD

**Issue by arvinsir** [JSQLParser/JSqlParser#1097]
**Describe the bug**
Gets all table names in the SQL script, and resolves an error when the SQL script returns a result with a field that begins with a number
获取SQL脚本中的所有表名，当SQL脚本返回结果中有数字开头的字段就会解析报错

**To Reproduce**
1. example： select a.5ggzx as ggzx from gz_table a;
2. database: mysql
3. TablesNamesFinder.getTableList((Select) Statement)

**Expected behavior**
I would like to support SQL scripts to return a list of results that begin with a number. Thank you

**System**
 - mysql
- Java 8
- JSqlParser 4.0

**Comment by wumpz** [comment]
Sorry, but JSqlParser does not parse these column names, it will throw an exception. Those special column names are not valid column names.

**Comment by arvinsir** [comment]
First of all, thank you very much for your reply. In practice, IT is true that there are column names that start with numbers, MySQL database does not do mandatory verification, and the field names are set by non-IT personnel. In this case, what should I do if I want to get the table names?

**Comment by wumpz** [comment]
Indeed mysql does support this. If I would introduce this, it would really complicate JSqlParsers grammar. IMHO this is no option.
