### ISSUE TITLE
PostgreSQL nextval()

### ISSUE THREAD

**Issue by dprutean** [JSQLParser/JSqlParser#1098]
PostgreSQL reversed engineer schema includes nextval as a function, like below. Is it possible to support this?

CREATE TABLE pagila_dev.actor (
    actor_id integer DEFAULT nextval('pagila_dev.actor_actor_id_seq'::regclass) NOT NULL,
    first_name text NOT NULL,
    last_name text NOT NULL,
    last_update timestamp with time zone DEFAULT now() NOT NULL
)

**Comment by wumpz** [comment]
PRs are welcome ...
