### ISSUE TITLE
Got JSQLParserException  when use MySQL BINARY keywords in select clause

### ISSUE THREAD

**Issue by RollsBean** [JSQLParser/JSqlParser#1101]
### Describe the bug

I'm using MySQL 5.7, Mybatis-plus and Java, i defined a `<select>` sql and used `BINARY` in sql, but when run this mapper, it throw _net.sf.jsqlparser.JSQLParserException_ <br/>  

**Stacktrace:**

```java
 ... 46 more
Caused by: net.sf.jsqlparser.JSQLParserException
  at net.sf.jsqlparser.parser.CCJSqlParserUtil.parseStatements(CCJSqlParserUtil.java:137)
  at com.baomidou.mybatisplus.core.parser.AbstractJsqlParser.parser(AbstractJsqlParser.java:60)
  ... 57 more
Caused by: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "BINARY" "BINARY"
    at line 5, column 13.

Was expecting one of:

    "!"
    "("
    "NOT"
```

### To Reproduce

1. Create test table SQL

```sql
create table `charset_test`(
  `id` int, 
  `type` varchar(16)
)ENGINE=InnoDB AUTO_INCREMENT=61 DEFAULT CHARSET=utf8 ;

insert into `charset_test`(id, type) values(1, 'user'),(2,'USER');
```
2. Example SQL

```sql
select type from charset_test where type = 'user';
```
<br/>

3. Exception

```
Caused by: net.sf.jsqlparser.JSQLParserException
  at net.sf.jsqlparser.parser.CCJSqlParserUtil.parseStatements(CCJSqlParserUtil.java:137)
```
<br/>

### Expected behavior

MySQL 5.7 support `BINARY` keyword for case sensitive purpose, so _jsqlparser_ should parse the above sql without any parse exception.<br/>

### System

 - Database you are using `MySQL 5.7`
- Java Version `JRE 1.8`
- JSqlParser version: `com.github.jsqlparser:jsqlparser:3.1`
- Mybaits-plus: `3.3.1`

**Comment by ImSejin** [comment]
I have same problem.

**Comment by manticore-projects** [comment]
Please use proper quotes " instead of ` and it will work:
```sql
CREATE TABLE "charset_test" (
    id           INT
    , type       VARCHAR (16)
) ENGINE = INNODB AUTO_INCREMENT = 61 DEFAULT CHARSET = UTF8
;

INSERT INTO "charset_test" (
    id
    , type )
VALUES ( (1, 'user'), (2, 'USER') )
;
```

You can also [test it here online](http://217.160.215.75:8080/jsqlformatter/demo.html?args=-c%20MIJQogggKmAEUQEIBk4CIDGALAhgJwGcBTAFwH0SiCS1YAKAKFmdgEsATFrrgSQDkoTFgBpYJAJ4AHIt2YA1CCGAAJRfQCMANgCUDbbDB8A4vzgBeWPz4B5ACKJYEAKpRrZfqDABZQ1FgXNdVhbMAAxZ2Q-FUUAZTA-CxdQgA4GAG4GBn44kD9+V1hMXEJSCioaeiFmDirYUQlpWF0FZCcwGPoNUQByAFdiPG7tUToAJh6nHKGm9KA+)

**Comment by ImSejin** [comment]
@manticore-projects 

In my case, `BINARY` keyword is in query and this parser don't work properly.

**Comment by manticore-projects** [comment]
Greetings.

Please share your particular example, otherwise I won't be able to
advise.
Best regards
Andreas

**Comment by ImSejin** [comment]
I raise the issue. #1198

**Comment by wumpz** [comment]
So can we close this?

**Comment by ImSejin** [comment]
@wumpz 

I'm ok but I'm not issuer.

**Comment by RollsBean** [comment]
@wumpz  Sorry for late response, i have checked issue [#1198](https://github.com/JSQLParser/JSqlParser/issues/1198) and will test in my local, please close this issue, thanks.
