### ISSUE TITLE
Jsqlparser can support hive or spark sql

### ISSUE THREAD

**Issue by haha174** [JSQLParser/JSqlParser#1102]
INSERT overwrite table  t.b partition(p1=1,p2=2,mth_beg_dt) as
select * from t.b1
distribute by column1

**Comment by wat1r** [comment]
@haha174  yours is similar to this case https://github.com/JSQLParser/JSqlParser/issues/833

**Comment by jovistruck** [comment]
Create Table DDL for hive, with `STORED AS PARQUET` results in 
> JSQLParserException: Encountered unexpected token: "PARQUET"
