### ISSUE TITLE
Recognize CREATE FUNCTION statement

### ISSUE THREAD

**Issue by itadventurer** [JSQLParser/JSqlParser#111]
``` sql

CREATE FUNCTION fun(query_from_time date) RETURNS TABLE(foo double precision, bar double precision)
    LANGUAGE plpgsql
    AS $$
      BEGIN
       RETURN QUERY
      WITH bla AS (
        SELECT * from foo)
      Select * from bla;
      END;
      $$;
```

http://www.postgresql.org/docs/9.1/static/sql-createfunction.html

For me it would be enough if JSql sees that its a function and has the content of the function as a string.

This seems quite hard because we need to be able to recognize changes of escape characters and so on.

**Comment by Tornadotuan** [comment]
I guess there´s no solution for the problem found yet?
Btw. are PostgreSQL stored procedure supported in general?

**Comment by wumpz** [comment]
There is no solution for JSQLPARSER. Usage of functions within sqls is supported.

**Comment by pietergent** [comment]
any info on this?

**Comment by wumpz** [comment]
Unfortunately there is no progress here.
