### ISSUE TITLE
Qualified and/or quoted identifiers in foreign key statement

### ISSUE THREAD

**Issue by StefanJannCH** [JSQLParser/JSqlParser#1111]
**Describe the bug**
I observed that statements for creating foreign keys are not supported by Parser if the statement contains a qualified tablename or a quoted identifier.

**To Reproduce**
1. Example SQL

Case one:
`ALTER TABLE PUBLIC.C ADD FOREIGN KEY ( x ) REFERENCES PUBLIC.A (a);`

Case two:
`ALTER TABLE PUBLIC.C ADD FOREIGN KEY ( x ) REFERENCES "A" (a);`

Case three:
`ALTER TABLE PUBLIC.C ADD FOREIGN KEY ( x ) REFERENCES "PUBLIC"."A" (a);`

2. Parsing this SQL using JSqlParser with this statements

`CCJSqlParserUtil.parseStatements(sql).getStatements();`

3. Exception

Case one:
`Encountered unexpected token: "PUBLIC" "PUBLIC"
    at line 2, column 58.

Was expecting:

    <S_IDENTIFIER>
`

Case two:
`Encountered unexpected token: "\"A\"" <S_QUOTED_IDENTIFIER>
    at line 2, column 58.

Was expecting:

    <S_IDENTIFIER>
`
Case three:
`Encountered unexpected token: "\"PUBLIC\"" <S_QUOTED_IDENTIFIER>
    at line 2, column 58.

Was expecting:

    <S_IDENTIFIER>
`

**Expected behavior**

All three cases are valid SQL statements that are working when executed against the database. So it would be nice if the Parser could parse those as well.

**System**
- Database you are using
HSQLDB

- Java Version
11
- JSqlParser version
4.0

**Comment by manticore-projects** [comment]
Please retest with JSQLParser 4.1 or later.
I have been able to parse all 3 samples and [you can test it online here](http://jsqlformatter.manticore-projects.com/jsqlformatter/demo.html?args=-c%20IIGQKgogSgBGwCEQRgBwK4CMA2BLAxgHT4BQM5MwAIlTAGIDyUEAkgOIByMA0hAJowAFAA8AlGQqTmdaBA4BhCAGVKQgIbiA3CRKhIseEhQYcBYhPLVajZuy68BI8ZKkQZzBcpgAiYN-VaOnrQcIjIaFh4RKSSVvRMrJw8-EJiFi7Ssp4q3gAKAKpILPLehL7+ghokmkA+)
