### ISSUE TITLE
Can I keep my annotations when parsing SQL into objects?

### ISSUE THREAD

**Issue by liuxiswt** [JSQLParser/JSqlParser#1113]
Hi, developers, because the SQL I work with is very complex, I will add a lot of comments to the SQL.But when I use JSQLParser, it automatically removes the annotations from the body.Please, can I keep my annotations in the parsed object?  Thank you very much and I am looking forward to your reply

**Comment by wumpz** [comment]
Unfortunately, this is not possible, since comments are parsed as special tokens that are finally skipped. However, it is possible to intercept those special tokens: https://www.cs.purdue.edu/homes/hosking/javacc/doc/tokenmanager.html.

**Comment by liuxiswt** [comment]
Thank you very much for your reply. I will try to use the interception scheme to restore the annotations, because I think I still need the SQL annotations, because it will be very convenient for me to read the SQL.
