### ISSUE TITLE
Support SEQUENCES

### ISSUE THREAD

**Issue by itadventurer** [JSQLParser/JSqlParser#112]
``` sql
CREATE SEQUENCE foo_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE foo_seq OWNED BY foo.id;
```
- http://www.postgresql.org/docs/9.4/static/sql-createsequence.html
- http://www.postgresql.org/docs/9.4/static/sql-altersequence.html

**Comment by pumpkinlink** [comment]
+1 for PL/SQL SEQUENCE

**Comment by AnEmortalKid** [comment]
I believe in some fashion this has been completed @wumpz !

**Comment by wumpz** [comment]
@itadventurer @AnEmortalKid This one has completed indeed. Thanks for your patch, @AnEmortalKid. I have to admit, that I did not deploy the changes. The deployment runs as I write.
