### ISSUE TITLE
PostgreSQL [create table DDL ] parse geometry field fail

### ISSUE THREAD

**Issue by linkoog** [JSQLParser/JSqlParser#1121]
`
CREATE TABLE "public"."device_bayonet_copy1" (
  "id" int8 NOT NULL,
  "device_code" varchar(128) COLLATE "pg_catalog"."default",
  "longitude_latitude" varchar(128) COLLATE "pg_catalog"."default",
  "longitude_latitude_gis" "public"."geometry",
  "direction" varchar(128) COLLATE "pg_catalog"."default",
  "brand" varchar(128) COLLATE "pg_catalog"."default",
  "test" "information_schema"."time_stamp",
  CONSTRAINT "device_bayonet_copy1_pkey" PRIMARY KEY ("id")
)
`

 [longitude_latitude_gis、test]   field   parse  fail。

**Comment by manticore-projects** [comment]
Works with PR #1778, I believe commit [32ec561](https://github.com/JSQLParser/JSqlParser/pull/1778/commits/32ec56114c1fbc4601d563c83071e7fc81963d2f) did the trick.
