### ISSUE TITLE
Outdated Javadoc

### ISSUE THREAD

**Issue by LorenzBuehmann** [JSQLParser/JSqlParser#1122]
https://github.com/JSQLParser/JSqlParser/blob/bcc683ab8791b7104c6c17cea454056d6a6b33d8/src/main/java/net/sf/jsqlparser/parser/CCJSqlParserUtil.java#L45-L47

The option mentioned in the linked Javadoc doesn't exists anymore and I assume it now works via `withConfiguration(FeatureConfiguration configuration)` according to https://github.com/JSQLParser/JSqlParser/blob/bcc683ab8791b7104c6c17cea454056d6a6b33d8/src/main/jjtree/net/sf/jsqlparser/parser/JSqlParserCC.jjt#L71-L74

**Comment by wumpz** [comment]
No, it works like described.

**Comment by LorenzBuehmann** [comment]
Ok. maybe I'm dumb and misunderstand something, but maybe you can then tell me where the method `withSquareBracketQuotation(true)` is for the class `CCJSqlParser`?

I'm pretty sure that the option has been removed in this commit: 
https://github.com/JSQLParser/JSqlParser/commit/8c735be5b179e51ebf02624ca91bd538cefc8079#diff-d323df58a0300a038ac87b328bf05b8255ff06e6b5d0e9aeae641fa566e4068c
Look at how the `JSqlParserCC.jjt ` has been changed.

All I'm saying is that the Javadoc example
```
{@code 
      * CCJSqlParserUtil.parse("select * from [mytable]", parser -> parser.withSquareBracketQuotation(true)); 
      * } 
```
 doesn't match the code changes as the `Consumer<CCJSqlParser>` can't be used with the non-existing method.
