### ISSUE TITLE
Parsing exception for nested WITH 

### ISSUE THREAD

**Issue by rhuddbiz** [JSQLParser/JSqlParser#1123]
**Describe the bug**
Postgres supports nested WITH in SQL Statement

**To Reproduce**

WITH a AS ( WITH a AS ( select 1 ) SELECT 2 )  SELECT * from a

java.sql.SQLException: Encountered unexpected token: "WITH" "WITH"
    at line 1, column 13.

Was expecting one of:

    "("
    "VALUES"
    <K_SELECT>

**Expected behavior**
Running SQL Query in Postgres returns  -> single row with value "2"

**System**
 - Testing against Postgres 
- Java Version 11
Failed with  JSqlParser version 3.2 and 4.0

**Comment by rhuddbiz** [comment]
"PostgreSQL 12.6"

**Comment by wumpz** [comment]
This is not (yet) supported. PRs are welcome.

**Comment by manticore-projects** [comment]
Solved by PR #1221

**Comment by manticore-projects** [comment]
Can we close this now? It has been merged and tested.

**Comment by rhuddbiz** [comment]
I'll upgrade to the new version and check this weekend ! Sorry for the delay. If you have this tested with my sample, feel free to close the ticket yourself.

**Comment by rhuddbiz** [comment]
confirmed this is solved in version 4.1
