### ISSUE TITLE
Parsing error when parsing syntactically correct query

### ISSUE THREAD

**Issue by jphpeete** [JSQLParser/JSqlParser#1124]
**Describe the bug**
JSQLParserException when parsing a syntactically correct postgreSQL query. The issue is parentheses around the ORDER BY clause.

**To Reproduce**
1. example SQL:
> SELECT col1, col2 FROM table ORDER BY (col1, col2)
2. Parsing this SQL using JSqlParserUtil
3. JSQLParserException

**Expected behavior**
A correct parse should be the correct outcome.

**System**
- PostgreSQL 12
- Java Version 15
- JSqlParser version 1.2 and 4.0

**Comment by wumpz** [comment]
At least in JSqlParser 4.1-SNAPSHOT this is parsable.

**Comment by manticore-projects** [comment]
Not reproducible with the latest version of JSQLParser.
