### ISSUE TITLE
Support PostgreSQL casting

### ISSUE THREAD

**Issue by azapps** [JSQLParser/JSqlParser#113]
``` sql
CREATE TABLE foo (
    reason character varying(255) DEFAULT 'Test'::character varying NOT NULL
);
```

http://www.postgresql.org/docs/9.4/static/sql-expressions.html#SQL-SYNTAX-TYPE-CASTS

**Comment by Muji-** [comment]
Any updates on this error, any hints on how to extend the grammar to support this

**Comment by wumpz** [comment]
Parameters within a create table statement are simply parsed as string lists. It is not a very sophisticated parsing. The changes should be in Create table rule within the jj file. If you think about a patch, don't forget the deparsers. Most of the tests try to parse and deparse and compare the results to assure specials like brackets or optionally syntactic sugar are recognized and reconstructed. Cheers  Tobias

**Comment by wumpz** [comment]
A long way to go ...
