### ISSUE TITLE
Support expressions with ":".

### ISSUE THREAD

**Issue by LonwoLonwo** [JSQLParser/JSqlParser#1134]
**Describe the bug**
Some Databases, like Informix, have a sign ":" as delimiter name of the database and schema name.
https://www.ibm.com/support/knowledgecenter/en/SSGU8G_14.1.0/com.ibm.sqls.doc/ids_sqs_1652.htm 
This is not a completely accurate link, but here the use of a colon is mentioned.

**To Reproduce**
use "SELECT * FROM stores_demo:informix.accounts;" with Informix database and get
```
net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: ":" ":"
    at line 2, column 17.
at net.sf.jsqlparser.parser.CCJSqlParser.generateParseException(CCJSqlParser.java:26538)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_consume_token(CCJSqlParser.java:26377)
	at net.sf.jsqlparser.parser.CCJSqlParser.Statement(CCJSqlParser.java:91)
```
https://github.com/dbeaver/dbeaver/issues/11590

**Expected behavior**
Please add colon support as a separator between the database name and the schema name.

**System**
 - Informix Dynamic Server 14.10.FC4W1
-  jsqlparser:4.0

**Comment by wumpz** [comment]
I kind of introduced this parsing half way. Now you are able to parse it, but the deparser is not there. Producing the source SQL results in the point way again.

**Comment by wumpz** [comment]
@LonwoLonwo Does it work?

**Comment by LonwoLonwo** [comment]
Hello, @wumpz 
Sorry for late response.
Yes, it works for parsing.
I don't now your workflow, so I just say - ticket can be closed.

**Comment by manticore-projects** [comment]
Closed on behalf of the author.

**Comment by manticore-projects** [comment]
@LonwoLonwo 

we are facing a problem here: in any modern RDBMS `:` is a Json Operator for `EXTRACT FROM PATH` e. g.:

```sql
-- DataBricks/Snowflake
SELECT c1:price j
    FROM VALUES('{ "price": 5 }') AS T(c1);

-- Postgres
SELECT c1::JSON -> 'price' j
    FROM VALUES('{ "price": 5 }') AS T(c1);
```

It is impossible to support both at the same time, but we could apply a Configuration Switch, e. g. an `INFORMIX` mode for you. 
I definitely need this JSON support, but I also want to support your needs -- so please make a wish on what would be the best way forward on this rather exotic feature.

**Comment by manticore-projects** [comment]
I have solved it by allowing `:` for `Table` names only, while `:` will return a `JSOnExpression` everywhere else.
