### ISSUE TITLE
impala syntax cannot be parsed

### ISSUE THREAD

**Issue by ZzzHzzZ** [JSQLParser/JSqlParser#1136]
sql:
SELECT round(1-sum(case when skip='1' then 1 else 0 end)/count(1), 4) AS playratio
   FROM 
	 (SELECT 
	         cgid,
			 udf.impala_get_json_object(hint_, '$.skip') skip
	  FROM test)t 
   GROUP BY cgid

code like this:
Select select = (Select) CCJSqlParserUtil.parse(sql);

Exception:
net.sf.jsqlparser.JSQLParserException: Encountered unexpected token: "(" "("
    at line 1, column 13.

Was expecting one of:

    "&"
    ","
    "::"
    ";"
    "<<"
    ">>"
    "ACTION"
    "ANY"
    "AS"
    "BYTE"
    "CASCADE"
    "CAST"
    "CHANGE"
    "CHAR"
    "CHARACTER"
    "COLLATE"
    "COLUMN"
    "COLUMNS"
    "COMMENT"
    "COMMIT"
    "CONNECT"
    "CYCLE"
    "DESC"
    "DESCRIBE"
    "DISABLE"
    "DIV"
    "DO"
    "DUPLICATE"
    "ENABLE"
    "END"
    "EXCEPT"
    "EXCLUDE"
    "EXTRACT"
    "FALSE"
    "FIRST"
    "FN"
    "FOLLOWING"
    "FOR"
    "FORMAT"
    "FROM"
    "GROUP"
    "HAVING"
    "INDEX"
    "INSERT"
    "INTERSECT"
    "INTERVAL"
    "INTO"
    "ISNULL"
    "KEY"
    "LAST"
    "MATERIALIZED"
    "MINUS"
    "NEXTVAL"
    "NO"
    "NOLOCK"
    "NULLS"
    "OF"
    "OPEN"
    "ORDER"
    "OVER"
    "PARTITION"
    "PATH"
    "PERCENT"
    "PRECISION"
    "PRIMARY"
    "PRIOR"
    "RANGE"
    "READ"
    "REPLACE"
    "ROW"
    "ROWS"
    "SCHEMA"
    "SEPARATOR"
    "SEQUENCE"
    "SESSION"
    "SIBLINGS"
    "SIZE"
    "START"
    "TABLE"
    "TEMP"
    "TEMPORARY"
    "TO"
    "TOP"
    "TRUE"
    "TRUNCATE"
    "TYPE"
    "UNION"
    "UNSIGNED"
    "VALIDATE"
    "VALUE"
    "VALUES"
    "VIEW"
    "WHERE"
    "WINDOW"
    "XML"
    "ZONE"
    "["
    "^"
    "|"
    <EOF>
    <K_DATETIMELITERAL>
    <K_DATE_LITERAL>
    <S_CHAR_LITERAL>
    <S_IDENTIFIER>
    <S_QUOTED_IDENTIFIER>

	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parseStatement(CCJSqlParserUtil.java:165)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:59)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:37)
	at com.wanmei.df.common.util.sql.SqlDealUtils.getSourceOrderBy(SqlDealUtils.java:405)
	at com.wanmei.df.common.util.sql.SqlDealUtils.getPageSql(SqlDealUtils.java:229)
	at com.wanmei.df.common.util.sql.SqlDealUtils.getDealSql(SqlDealUtils.java:149)
	at com.wanmei.df.common.util.sql.SqlDealUtils.main(SqlDealUtils.java:77)

jsqlparser version: 4.0

**Comment by wumpz** [comment]
The problem here is not the syntax, but **skip** is a keyword and cannot yet be used as a column name. I am on it.
