### ISSUE TITLE
Support EXECUTE FUNCTION/PROCEDURE

### ISSUE THREAD

**Issue by morvael** [JSQLParser/JSqlParser#1141]
I think there is support for EXECUTE name syntax. Is it possible to add support for EXECUTE PROCEDURE name (...) and EXECUTE FUNCTION name (...) syntax?

**Comment by wumpz** [comment]
PRs are welcome. `Execute()` production should be easily extended to support this procedure / function syntax.

**Comment by manticore-projects** [comment]
Todo: Implement `<K_EXECUTE> [ <K_FUNCTION> | <K_PROCEDURE> ]  ... `

**Comment by daxwang** [comment]
hi  guys, how about this now?

**Comment by manticore-projects** [comment]
[Works with JSQLParser-4.8)[http://jsqlformatter.manticore-projects.com/jsqlformatter/demo.html?args=-c%20KIDWGEFUBVgAgGYFcB2BjALgSwPYsaprigPooCGAtgKYAUAlAFADcjjoEM8ADgE45pqAEyS9qBdNjxkqdJsyA]
