### ISSUE TITLE
Incorrect recognition of RANGE in CREATE TABLE statement

### ISSUE THREAD

**Issue by azapps** [JSQLParser/JSqlParser#115]
```sql
CREATE TABLE foo (
    name character varying(255),
    range character varying(255),
    start_range integer,
    end_range integer
);
```

Yields to
```
Encountered " "RANGE" "range "" at line 3, column 5.
Was expecting one of:
    "KEY" ...
    "INDEX" ...
    "FOREIGN" ...
    "CONSTRAINT" ...
    <S_IDENTIFIER> ...
    <S_QUOTED_IDENTIFIER> ...
    "CONSTRAINT" ...
```

**Comment by azapps** [comment]
Similarly it recognizes KEY in the create table statement:
```sql
CREATE TABLE bar (
    key character varying(255) NOT NULL
);
```

**Comment by NKame** [comment]
"KEY" is a reserved word in SQL-92 and SQL:1999, "RANGE" is a reserved word in SQL:2003. So the recognition is correct depending on the SQL version :)

**Comment by azapps** [comment]
Yeah, they are reserved in the particular standard but JSQLParser supports also non-standard operations.

According to http://www.postgresql.org/docs/9.4/static/sql-keywords-appendix.html

| Keyword     | PostgreSQL          | SQL:2011          | SQL:2008        | SQL-92      |
|---------|--------------|--------------|--------------|----------|
| `KEY`   | non-reserved | non-reserved | non-reserved | reserved |
| `RANGE` | non-reserved | reserved     | reserved     |       |

So I would say JSQLParser should recognize this correctly ;)
