### ISSUE TITLE
Oracle hints lost on INSERT, UPDATE and MERGE statement

### ISSUE THREAD

**Issue by manticore-projects** [JSQLParser/JSqlParser#1150]
While we can access the Oracle hints in PLAIN SELECT, there does not seem to be such an access for INSERT, UPDATE, MERGE, DELETE statements like:
```sql
UPDATE /*+parallel*/ foo
INSERT /*+parallel append*/ INTO foo
MERGE /*+parallel*/ INTO foo
```

This is especially sad as the impact can be very big and these Oracle hints are also not preserved as comments.

Should not all these statements support getOracleHint() similarly to PLAIN SELECT?
Am I missing something here?

Thank you already for looking into it.

**Comment by manticore-projects** [comment]
Addressed in PR #1153.
Cheers

**Comment by minskya** [comment]
@manticore-projects wasn't it better if was supported also on select?

**Comment by manticore-projects** [comment]
> @manticore-projects wasn't it better if was supported also on select?

`SELECT` is supported of course and has been working before already.
