### ISSUE TITLE
Formatter based on JSQLParser: [manticore JSQLFormatter](https://github.com/manticore-projects/jsqlformatter)

### ISSUE THREAD

**Issue by manticore-projects** [JSQLParser/JSqlParser#1152]
Thank you for providing JSQLParser, it is just awesome.
Frustrated by the shortcomings of the available SQL Formatters (regarding WITH, UNION, SUB SELECTS, complex Functions), I have started to work on a Java Based SQL Formatter based on JSQLParser.

After one week of work, here is my first result: [manticore JSQLFormatter](https://github.com/manticore-projects/jsqlformatter).

It handles fairly complex SELECT, INSERT, UPDATE and MERGE statements already and I am working on supporting all statements and adding more formatting options.
It also illustrates how to actually use JSQLParser, which I had to find out by a lot of 'trial'n error' in the absence of the API documentation.

Will appreciate your feedback and am interested in any statements, which still will fail.
Thank you again for JSQLParser!

**Comment by manticore-projects** [comment]
[Version 0.1.2](https://github.com/manticore-projects/jsqlformatter) got CREATE TABLE, CREATE INDEX, CREATE VIEW and DELETE statements working.
Providing now an Ueber-JAR (including an amended version of JSQLParser) because of the pending PR.

Any chance to get this accepted and released? Otherwise my tests keep failing and folks can't build from source.

**Comment by wumpz** [comment]
Looks good. You are following a different approach than my first thoughts. I for myself probably would have included those formatting stuff into the deparsers.

**Comment by manticore-projects** [comment]
Just released  [Version 0.1.3](https://github.com/manticore-projects/jsqlformatter/releases/tag/0.1.3) with Native Binaries for Linux and Windows and some really cool ANSI syntax highlighting:
![image](https://user-images.githubusercontent.com/18080123/115195511-0c723e00-a119-11eb-8035-4b70dd3d0da7.png)

Please help me out on the PRs because my CI keeps failing as long as the corrections are not published.
Do you have any idea, how I could work around that, while the PRs are waiting?

**Comment by wumpz** [comment]
I merged already a couple. Is this still relevant? The rest I will merge I think in a few hours.

**Comment by manticore-projects** [comment]
Unfortunately, my CI for JSQLFormatter will keep failing whenever I send a PR for JSQLParser.
Because I find the issues when formatting my thousands of SQL statements (although I believe we made some massive progress already) and then fix them locally, send the PR and will need to wait.

Not much we can do about, I guess although things should settle soon.
Btw, am working on getting our stuff into Netbeans, so you will be able to format your SQL in netbeans soonest -- all with your software!

**Comment by wumpz** [comment]
👍🏼

**Comment by manticore-projects** [comment]
We did: our stuff is in Netbeans -- pending a PR, you know how long this can take :-)


https://user-images.githubusercontent.com/18080123/116778749-09266d00-aa9e-11eb-826c-de254bbfc27e.mp4

**Comment by manticore-projects** [comment]
You can try now your parser online and interactively: http://217.160.215.75:8080/jsqlformatter/demo.html
It will show you automatically where the Parser fails and you can modify your statements interactively.

https://user-images.githubusercontent.com/18080123/117129006-566d4c00-adc8-11eb-988e-8de8e1c81598.mp4
