### ISSUE TITLE
Inserted values contain single quotes, ccjsqlparse was down.

### ISSUE THREAD

**Issue by xiaoxiemagic** [JSQLParser/JSqlParser#1155]
version: 
jsqlparse-1.4 or jsqlparse 3.2

sql like this:
insert into table (id, col_name) values (1, 'this\'s value');

**Comment by xiaoxiemagic** [comment]
version: 
jsqlparse-1.4

**Comment by manticore-projects** [comment]
This is an invalid SQL statement.
You will need to quote the inner single quote correctly or use concatenation and Chr();

**Comment by xiaoxiemagic** [comment]
> This is an invalid SQL statement.
> You will need to quote the inner single quote correctly or use concatenation and Chr();

sorry, there missing a backslash

sql like this:
insert into table (id, col_name) values (1, 'this\'s value');

**Comment by xiaoxiemagic** [comment]
ok thx, my usage is wrong
