### ISSUE TITLE
fail parse sql like select xx from table where contains((a,b,c), 'text') 

### ISSUE THREAD

**Issue by zyp461476492** [JSQLParser/JSqlParser#1160]
**Describe the bug**
can't parse sql like contains((a,b,c), '') | freetext((a,b,c), '') 

**contains** and **freetext** is sqlserver fulltext query keyword
**To Reproduce**
1. select title,body from articles where contains ((title, body), 'text')
2. CCJSqlParserUtil.parse(sql)
3. net.sf.jsqlparser.JSQLParserException: Encountered unexpected token: "(" "("
    at line 1, column 201.Was expecting one of:

    "&"
    "&&"
    "::"
    ";"

**Expected behavior**
correct parse sql

**System**
 - sqlserver
- jdk11
- 3.1 or 4.0

**Comment by wumpz** [comment]
V4.1-SNAPSHOT is able to parse this

**Comment by zyp461476492** [comment]
> V4.1-SNAPSHOT is able to parse this

Thanks~
