### ISSUE TITLE
Nested CASE WHEN Statement costs lots of time.

### ISSUE THREAD

**Issue by ZhaoRuidong** [JSQLParser/JSqlParser#1162]
**Describe the bug**
When I parses a sql with Casewhen nested statement，as the number of nested layers increased, it cost lots of time.Is there any way to fix this?

**To Reproduce**
CREATE VIEW VIEW_NAME1 AS
SELECT CASE
           WHEN WDGFLD.PORTTYPE = 1 THEN 'INPUT PORT'
           ELSE (CASE
                     WHEN WDGFLD.PORTTYPE = 1 THEN 'INPUT PORT'
                     ELSE (CASE
                               WHEN WDGFLD.PORTTYPE = 1 THEN 'INPUT PORT'
                               ELSE (CASE
                                         WHEN WDGFLD.PORTTYPE = 1 THEN 'INPUT PORT'
                                         ELSE (CASE
                                                   WHEN WDGFLD.PORTTYPE = 1 THEN 'INPUT PORT'
                                                   ELSE (CASE
                                                             WHEN WDGFLD.PORTTYPE = 1 THEN 'INPUT PORT'
                                                             ELSE (CASE
                                                                       WHEN WDGFLD.PORTTYPE = 1 THEN 'INPUT PORT'
                                                                       ELSE (CASE
                                                                                 WHEN WDGFLD.PORTTYPE = 1
                                                                                     THEN 'INPUT PORT'
                                                                                 ELSE (CASE
                                                                                           WHEN WDGFLD.PORTTYPE = 1
                                                                                               THEN 'INPUT PORT'
                                                                                           ELSE (CASE
                                                                                                     WHEN WDGFLD.PORTTYPE = 1
                                                                                                         THEN 'INPUT PORT'
                                                                                                     ELSE (CASE WHEN WDGFLD.PORTTYPE = 1 THEN 'INPUT PORT' ELSE '0' END) END) END) END) END) END) END) END) END) END) END COLUMNALIAS
FROM TABLE1 

**Expected behavior**

**System**
 -  Oracle
- jdk 1.8
- JSqlParser version 4.0

**Comment by ZhaoRuidong** [comment]
I test with different nested layers in statement.
2 Time cost:210
3 Time cost:250
4 Time cost:309
5 Time cost:417
6 Time cost:573
7 Time cost:1178
8 Time cost:2132
9 Time cost:4656
10 Time cost:15114
11 Time cost:57838

**Comment by ZhaoRuidong** [comment]
I found it is due to bracket after "ELSE" token. If i remove all brackets it parsers fast.

**Comment by wumpz** [comment]
If you build JSqlParser, then you will see similar tests. Unfortunately, til now I was not able to solve this. Look into `NestedBracketsPerformanceTest.java`.

**Comment by manticore-projects** [comment]
@Wumz Please have a look at #1038 which states that JavaCC 21 does fix "Nested syntactic lookahead".
Would that not solve these cases of nested CASE statements WIDTH statements and Brackets?

**Comment by manticore-projects** [comment]
I have corrected that, your particular Test Case parser now in less than 0.2 seconds.
Please note: The brackets around the nested Case When expressions are redundant (but we support both ways with/without brackets). You can test your statement [here online and interactively](http://217.160.215.75:8080/jsqlformatter/demo.html?args=-c%20MIJQogggKmAEBqBJMB1WA3AlgUwO4H0A7AQwFtsBGAKFltggGVYGwAZMYKWYRsGugYKGCUACTAA5WLgAmAcwBmAGxkA6AA4B7AE4AXXQE912WAF5Y1YVesCo4qQHJEEgAoBVLi4DyIKA-42gbBsLNy8AUGRYpLS8spqWnqGxmYWEZEZsHYxTq4esN6+-pmRIXA8LOklgdFSsooqGjr6RibmltWd2Y7O7p4+flWdVmVhlcPVtbENCc3JbWkTE92wuX0FA8VLGaMVfNudU-XxTUmtqR0Hwytr+YWDVyW74Y-DR3GNiS0p7UOvmTdendNn9-tZnuMwW97NMTl95hdQVCMoC8v0ikjkSNWKE9pisTZ3jNTt8FpcCUtUet7lsKdUIfs6UsiXC5udfkzHlTgRjORMGfi+TUYcdPmyfoshVyYbd0Q8pfyceUXgqDiyxWcJeTVQduXLaTrhqMHAAGA2G0oSAAigsNkhtFpG1ttdPtLqhboVnqZ3uRvse-v5zqDVtgAGNNEoAK6kEhKTDEADOfwAYiAvABZWC6YgAIyUlCoAG4gA+)

You can also get the patched JSQLParser Binary from there, while the PR is pending.

**Comment by manticore-projects** [comment]
Can we close this now?

**Comment by wumpz** [comment]
As you have a "fixes issue" within your PRs commit, the normal behaviour is to close it.
