### ISSUE TITLE
Oracle composite column syntax for ROLLUP & CUBE queries

### ISSUE THREAD

**Issue by tim-morillon** [JSQLParser/JSqlParser#1168]
The parser doesn't seem to support composite columns in Oracle Rollup/Cube queries.

1. A query with composite columns stated in the rollup/cube clause will not parse, such as 
          _select sum(a) as amount, b, c  from TEST_TABLE group by rollup ((a,b),c)_
    Where as the plain version with composite colums parses fine
          _select sum(a) as amount, b, c  from TEST_TABLE group by rollup (a,b,c)_

**System**
 - Oracle
- Java 8
- JSqlParser version 4.0

**Comment by wumpz** [comment]
Thats right. PRs are welcome.

**Comment by manticore-projects** [comment]
Solved by PR #1218.
