### ISSUE TITLE
When adding batches, after rewriting SQL, an error is reported Parameter'__frch_item_0' not found. Available parameters are [collection, list]

### ISSUE THREAD

**Issue by JavaJiangWei** [JSQLParser/JSqlParser#1174]
**Describe the bug**
This is the SQL I rewritten. When adding batches, after rewriting SQL, an error is reported Parameter'__frch_item_0' not found. Available parameters are [collection, list]. But it will report an error Parameter'__frch_item_0' not found. Available parameters are [collection, list]

**To Reproduce**
NEW SQL:INSERT INTO user (username, password, tenant_id) VALUES (?, ?, 1000), (?, ?, 1000), (?, ?, 1000)

**Expected behavior**

**Comment by manticore-projects** [comment]
I have just tried that with JSQLParser 4.1+ from Git and have not been able to reproduce any issue.
The following test runs flawless:
```java
@Test
  public void testMultipleInserts() throws JSQLParserException {
    String sqlStr =
        "INSERT INTO user (username, password, tenant_id) VALUES (?, ?, 1000), (?, ?, 1000), (?, ?, 1000)";
    assertSqlCanBeParsedAndDeparsed(sqlStr, true);
  }
```

Please double check the JSQLParser version you are using and try to pull from GIT when in doubt.
When using Maven, use the Snapshot artifact please. When confirmed, please close the issue.

Aside that, Oracle Multiple Inserts are not supported yet and fail indeed, I will open a separate issue for this.
```java
@Test
  @Ignore
  public void testOracleMultipleInserts() throws JSQLParserException {
    String sqlStr =
        "INSERT ALL\n"
            + "  INTO suppliers (supplier_id, supplier_name) VALUES (1000, 'IBM')\n"
            + "  INTO suppliers (supplier_id, supplier_name) VALUES (2000, 'Microsoft')\n"
            + "  INTO suppliers (supplier_id, supplier_name) VALUES (3000, 'Google')\n"
            + "SELECT * FROM dual;";
    assertSqlCanBeParsedAndDeparsed(sqlStr, true);
  }
```

**Comment by wumpz** [comment]
So could we close this?
