### ISSUE TITLE
"group by ()" cause parsing exception

### ISSUE THREAD

**Issue by xsgao-github** [JSQLParser/JSqlParser#1176]
**Describe the bug**
Cannot parse this statement `select sum(c) from t group by ()`.

**To Reproduce**
1. `net.sf.jsqlparser.parser.CCJSqlParserUtil.parse("select sum(c) from t group by ()")`
2. Exception - `Caused by: net.sf.jsqlparser.parser.ParseException: Encountered " "(" "( "" at line 1, column 31.`

**Expected behavior**
Not sure if `group by ()` is SQL compliant, but tested on SQL/PostgreSQL, they both support it.

**System**
 - Database you are using - SQL/PostgreSQL
- Java Version - 1.8
- JSqlParser version - 4.0

**Comment by manticore-projects** [comment]
Greetings.

While "supported by PostgreSQL" is a strong argument for implementing this "feature", I still wonder: Why would anyone want to write code like that? What does the `group by()` add to the statement? Am I right to assume, PostgreSQL would silently drop it and just executes
```sql
select sum(c)
from t
```

instead? If so, why not write the SQL exactly like this? Is any RDBMS expecying the empty `group by ()` clause?
Please correct me when I am wrong, but I kind of hesitate to spend my time on supporting 'dead code'.

**Comment by xsgao-github** [comment]
I also mentioned that SQL server also support that. Didn’t test other db.

I don’t know why someone write it in this way, but Tableau does.

**Comment by manticore-projects** [comment]
H2 supports it too, both as 
```sql
select id_instrument, count(*)
from cfe.instrument
group by (id_instrument);
```

as well as 
```sql
select count(*)
from cfe.instrument
group by ();
```

So be it.

**Comment by manticore-projects** [comment]
Can we close this please, it has been solved, tested and merged.
