### ISSUE TITLE
Canot parse select concat((select case when create_date_time < sysdate() then '123' end from dual), 'abc') as test from t

### ISSUE THREAD

**Issue by ondev** [JSQLParser/JSqlParser#1182]
select concat((select case when create_date_time < sysdate() then '123' end from dual), 'abc') as test from t

will get the parse exception:
JSQLParserException: Encountered unexpected token: "(" "("
    at line 1, column 14.

**Comment by manticore-projects** [comment]
Definitely works with 4.1 latest git, I have just tried.

**Comment by wumpz** [comment]
It works with 4.0 release. So check, which version you are using.

**Comment by manticore-projects** [comment]
Can't we close this now?
