### ISSUE TITLE
Parsing fails for conditions with brackets in SELECT clause

### ISSUE THREAD

**Issue by tomershay** [JSQLParser/JSqlParser#1194]
**Describe the bug**
The parser fails to parse conditions as select items, when they have brackets around them.

**To Reproduce**
The following query is parsed ok:
`SELECT col IS NULL FROM tbl`
But this query fails to parse:
`SELECT (col IS NULL) FROM tbl`

The same happens with other conditions such as `SELECT (a=b)...` and more complex conditions with AND/OR operators.

**System**
 - MySQL / PostgreSQL
- JSqlParser version: latest master

**Comment by manticore-projects** [comment]
Fixed by PR #1200.
We must use a ComplexExpressionList instead of a SimpleExpressionList. I have also added your particular test case.

**Comment by manticore-projects** [comment]
Can't we close this now?

**Comment by tomershay** [comment]
@manticore-projects, thank you for the fix!
