### ISSUE TITLE
Can't parse select * from test1 a left join test2 b on a.id = b.id where a.id = 1

### ISSUE THREAD

**Issue by ondev** [JSQLParser/JSqlParser#1195]
I have update the JSqlParser to the latest code on the github.
parse 
`
select * from test1 a left join test2 b on a.id = b.id where a.id = 1
`
will get error
`
JSQLParserException: Encountered unexpected token: "=" "="
    at line 1, column 49.
`

**Comment by manticore-projects** [comment]
I can not confirm that, please [try
yourself](http://217.160.215.75:8080/jsqlformatter/demo.html?args=-c%20MoUQMiDCAqAEBUAoAYgJQPIFlYBcCmAzjgIywCGisVsEycAUugJIByuhOATLAEaXUD0bMgDoAlgBNYAXl7iJiAOoAJEKhDl5M2MUQBuIA+)

The statement is parsed without any error and formatted correctly.

**Comment by wumpz** [comment]
So can we close this?

**Comment by manticore-projects** [comment]
Solution provided and no further question has been asked.
