### ISSUE TITLE
Single-line comment in mysql statement does not support # symbol

### ISSUE THREAD

**Issue by cxfly** [JSQLParser/JSqlParser#1197]
**Describe the bug**
      Single-line comment in mysql statement does not support # symbol

**To Reproduce**
1. Example SQL
       #tbds_sales_room\r\nalter table tbds_sales_room add `sale_type` tinyint(4) NOT NULL DEFAULT '0'
2. Parsing this SQL using JSqlParser with this statements
        String sql = "--tbds_sales_room\r\nalter table tbds_sales_room add `sale_type` tinyint(4) NOT NULL DEFAULT '0'";
        CCJSqlParserManager parserManager = new CCJSqlParserManager();
        Statement stmt =parserManager.parse(new StringReader(sql));
        System.out.println( stmt);
3. Exception
     net.sf.jsqlparser.JSQLParserException: Encountered unexpected token: "#tbds_sales_room" <S_IDENTIFIER>

**System**
 - Database you are using
            MySQL
- Java Version
     1.8
- JSqlParser version
   jsqlparser-4.0.jar

I found a solution, modify file
/jsqlparser/src/main/jjtree/net/sf/jsqlparser/parser/JSqlParserCC.jjt

from

SPECIAL_TOKEN:
{
   < LINE_COMMENT: "--"(~["\r","\n"])*>
|  < MULTI_LINE_COMMENT: "/*" (~["*"])* "*" ("*" | (~["*","/"] (~["*"])* "*"))* "/">
}

to

SPECIAL_TOKEN:
{
   < LINE_COMMENT: ("--" | "#")(~["\r","\n"])*>
|  < MULTI_LINE_COMMENT: "/*" (~["*"])* "*" ("*" | (~["*","/"] (~["*"])* "*"))* "/">
}

**Comment by manticore-projects** [comment]
Unfortunately, your sample is inconsistent regarding the #.
However, you statement will work fine:
```sql
--#tbds_sales_room
ALTER TABLE tbds_sales_room
    ADD sale_type TINYINT (4) NOT NULL
;
```
You can [test it here interactively](http://217.160.215.75:8080/jsqlformatter/demo.html?args=-c%20LTDEBcCMBMGcH1YEMA2BTBAnA9tgtgFACCAMgCoCiASgARlEBCJFNUciqG8O+BN-NIgBEhNZOnjgAngAc0dAJIA5AJrKyNABQAWAJQ0lAeQ1KAqiRIEA3EA+)

The proper Java String representation was:
```java
String queryStr = 
	  "--#tbds_sales_room\n"
	+ "ALTER TABLE tbds_sales_room\n"
	+ "    ADD sale_type TINYINT (4) NOT NULL\n"
	+ ";\n";
```
You can also get it from the Online Demo, right mouse click --> popup menu --> `Copy  Java String Code`.
There are StringBuffer Options and MessageFormat Options as well.

**Comment by wumpz** [comment]
JSqlParser is a multi database sql dialect parser. So `#` is a valid part of an identifier name. Therefore we are not able to support # starting comments. This is a valid statement:

```sql
SELECT * FROM #tab1
```

**Comment by manticore-projects** [comment]
Answered and no further question has been asked.
