### ISSUE TITLE
Support Postgresql multiple parenthesis (())

### ISSUE THREAD

**Issue by grib0** [JSQLParser/JSqlParser#120]
This request doesn't parse :

```sql
select avg((123.250) ::numeric)

```
although this one is ok :

```sql
select avg(123.250 ::numeric)
```

**Comment by wumpz** [comment]
Do you have an exception? Just thinking over it I would say, it should work.

**Comment by wumpz** [comment]
I included your statement as a test and it parses perfectly well. Could you provide an exception?

**Comment by grib0** [comment]
Sorry, I simplyfied my test too much :

**Comment by wumpz** [comment]
You found a mayer flaw in JSqlParsers grammar. This does not work as well: 
```sql
select (1/2)::numeric
```
I am on it but due to this grammar change I want to improve the tests there.

**Comment by grib0** [comment]
Great job, I'll test this version today or tomorrow.
Regards.
