### ISSUE TITLE
SpecialOracleTest currently creates a lot of noise

### ISSUE THREAD

**Issue by manticore-projects** [JSQLParser/JSqlParser#1201]
During Build/Testing some Oracle related tests are executed and are expected/accepted to fail. For example
```
May 20, 2021 6:22:12 AM net.sf.jsqlparser.statement.select.SpecialOracleTest testAllSqlsParseDeparse
INFO: testing for_update07.sql
net.sf.jsqlparser.JSQLParserException: Encountered unexpected token: "," ","
    at line 11, column 19.

Was expecting one of:

    ";"
    "FOR"
    "NOWAIT"
    "ORDER"
    <EOF>
```

Would it not be better to quieten or deactivate these tests, until we have time to look into these?

**Comment by wumpz** [comment]
I want to keep it there as a reminder. :)

**Comment by manticore-projects** [comment]
Am I not good enough? :))

Ok, no big deal. But please allow me to re-arrange the failing
statements into a sepatate Test like
"OutstandingOracleComplianceTest.java" which will fail completely
(until we will have solved it).

**Comment by wumpz** [comment]
Maybe we should simply log at fine level and make an external logging.properties.
