### ISSUE TITLE
ParseExection/ValidatonError when using a query that contains subquery with a UNION

### ISSUE THREAD

**Issue by lambrechtsm** [JSQLParser/JSqlParser#1202]
**Describe the bug**
A ParseException is thrown when we validate a query that contains a UNION (ALL) in a subquery

**To Reproduce**
1. Example SQL

select subq.systemType, sum(subq.amount)
  	from (
  		(select TestMe.systemType, TestMe.amount * 5
		   from TestMe TestMe
		  where TestMe.flag = 1)
        union all
		(select TestMe.systemType, TestMe.amount
		   from TestMe TestMe
		  where TestMe.flag = 2)
	) as subq
group by subq.systemType

2. Parsing this SQL using JSqlParser with this statements

Assertions.assertThat(new Validation(Collections.singleton(DatabaseType.SQLSERVER), queryToValidate).validate()).isEmpty();

Where queryToValidate contains the query mentioned above

3. Exception

<[ValidationError [
statement=select subq.systemType, sum(subq.amount)
from ((select TestMe.systemType, TestMe.amount * 5
from TestMe TestMe
where TestMe.flag = 1)
union all
(select TestMe.systemType, TestMe.amount
from TestMe TestMe
where TestMe.flag = 2)) as subq
group by subq.systemType
capability=parsing
errors=[ParseException: Cannot parse statement: Encountered unexpected token: "union" "UNION"
    at line 5, column 1.

Was expecting one of:

    ")"
    ","
    
..... etc.

**Expected behavior**
The query mentioned above is a valid query and executes correctly on both SQL Server and H2 databases, so I would not expect a ValidationError.

**System**
 - Database you are using: 
   H2 and Microsoft SQL Server
- Java Version: 
   8
- JSqlParser version: 
   4.0

**Comment by manticore-projects** [comment]
Greetings.

You query parses correctly with the latest Snapshot, which you can [try online and interactively here.](http://217.160.215.75:8080/jsqlformatter/demo.html?args=-c%20MoUQMiDCAqAEsGcCuAjAjgOgQTwQFwFMBbPbABwICh4aaAaWYJIgCkVUwEMiB7JAOzywAlJQBiAJQDyAWVhtG4KHFiF8RAllyES5KrQOHYDNXg0ZufQdSO27AKlgBWG4cmzVBdQU-fXBgHUACRAJEF8zTQAzABtOAHNYAF5YAEZ-WgBVADkASSls2ABBMDAMmlAIGHhTcxx8YlIKcrtjCPNLATwW2Hc5Wp8BnuDQ8IGMWITk2AAmEWLgdnRKAHFpTIAFWAAhAE0lzHqdJqoAbiA+)

Please close this issue after having confirmed the solution.
Cheers.

**Comment by lambrechtsm** [comment]
Hi manticore-projects,

thanks for the update and indeed the issue is fixed (same issue as https://github.com/JSQLParser/JSqlParser/issues/1094) in upcoming release 4.1. I will close this issue.

Grtz,

Marcel
