### ISSUE TITLE
Count statements after Error Recovery.

### ISSUE THREAD

**Issue by manticore-projects** [JSQLParser/JSqlParser#1203]
From the test suite:
```java
@Test
    public void testStatementsErrorRecovery3() throws JSQLParserException, ParseException {
        String sqls = "select * from mytable; select * from;select * from mytable2";
        CCJSqlParser parser = new CCJSqlParser(new StringReader(sqls));
        parser.setErrorRecovery(true);
        Statements parseStatements = parser.Statements();

        assertEquals(2, parseStatements.getStatements().size());
    }
```

Please why would you like to expect a count=2, but not count=3?
I count myself: 1 good statement, 1 bad statement  and 1 good statement. Where is my understanding wrong please?

**Comment by wumpz** [comment]
The intend was to count the good statements, so to say the parsed statements. But sure it would be an improvement to give the **count (good) + count(bad)** as well.

**Comment by manticore-projects** [comment]
Yes, this is how I saw and I have changed that already.
For this particular Test Case, the answer would be: 3 
while the second Statement would be null.

This should reveal all needed information.
