### ISSUE TITLE
Can not parse "CREATE INDEX ... USING BTREE"

### ISSUE THREAD

**Issue by ZZMarquis** [JSQLParser/JSqlParser#1207]
**Describe the bug**

**To Reproduce**
1. Example SQL
      CREATE UNIQUE INDEX name_ind ON t_test(name) USING BTREE
2. Parsing this SQL using JSqlParser with this statements
3. Exception
      net.sf.jsqlparser.JSQLParserException: Encountered unexpected token: "BTREE" <S_IDENTIFIER>

**Expected behavior**

**System**
 - Database you are using
     MySQL
- Java Version
     1.8.0_162
- JSqlParser version
     4.0

**Comment by manticore-projects** [comment]
Works fine with latest Snapshot 4.1, you can [test it online and interactively.](http://217.160.215.75:8080/jsqlformatter/demo.html?args=-c%20MIJQogggKmAECqA5AkgRXnZiAiYAasAdgIYC2ApgPoCWhAJgFCzOwDyisALpZ+QM6cAFETLlYASgQBlLAHFYAISjgwDANxA+)
