### ISSUE TITLE
Parser fails when using "json" in table identifier

### ISSUE THREAD

**Issue by doruchiulan** [JSQLParser/JSqlParser#1212]
**Describe the bug**
net.sf.jsqlparser.JSQLParserException: Encountered unexpected token: "." "."
    at line 1, column 35.

Was expecting one of:

    ";"
    <EOF> (state=,code=0)

**To Reproduce**
describe file_azbs.productcategory.json

**Expected behavior**
Query should be parsed

**System**
 - HiveServer2
- Java Version: 1.8
- JSqlParser version: 4.0

Describe file_azbs.productcategory.csv works

**Comment by wumpz** [comment]
The problem was the use of  `json`, which is a keyword in JSqlParser. Now that works.

**Comment by doruchiulan** [comment]
@wumpz is this expected in next 4.1 release ? Are there any nightly maven builds which are publicly available ? Thanks a lot for the prompt response/fix.

**Comment by wumpz** [comment]
This is included in 4.1-SNAPSHOT so the target release is 4.1. I will deploy the snapshot so you can test it.

**Comment by doruchiulan** [comment]
Man, you're a gold mine. Thank you so much. Do I need to add any special repository to maven ?
