### ISSUE TITLE
JSQLParser fails on this valid query on Sybase IQ. Cannot find why!

### ISSUE THREAD

**Issue by salonijuneja** [JSQLParser/JSqlParser#1213]
select cast(null as char(128)) as "PKTABLE_CAT","PKUser"."user_name" as "PKTABLE_SCHEM","PKTable"."table_name" as "PKTABLE_NAME","PKColumn"."column_name" as "PKCOLUMN_NAME",cast(null as char(128)) as "FKTABLE_CAT","FKUser"."user_name" as "FKTABLE_SCHEM","FKTable"."table_name" as "FKTABLE_NAME","FKColumn"."column_name" as "FKCOLUMN_NAME",cast((select "count"() from "SYS"."SYSFKCOL" as "other" where "foreign_table_id" = "SYSFOREIGNKEY"."foreign_table_id" and "foreign_key_id" = "SYSFOREIGNKEY"."foreign_key_id" and "primary_column_id" <= "SYSFKCOL"."primary_column_id") as smallint) as "KEY_SEQ",cast("isnull"((select if "referential_action" = 'C' then 0 else if "referential_action" = 'N' then 2 else 3 endif endif from "SYS"."SYSTRIGGER" where "table_id" = "SYSFOREIGNKEY"."primary_table_id" and "foreign_table_id" = "SYSFOREIGNKEY"."foreign_table_id" and "foreign_key_id" = "SYSFOREIGNKEY"."foreign_key_id" and "event" = 'C'),1) as smallint) as "UPDATE_RULE",cast("isnull"((select if "referential_action" = 'C' then 0 else if "referential_action" = 'N' then 2 else 3 endif endif from "SYS"."SYSTRIGGER" where "table_id" = "SYSFOREIGNKEY"."primary_table_id" and "foreign_table_id" = "SYSFOREIGNKEY"."foreign_table_id" and "foreign_key_id" = "SYSFOREIGNKEY"."foreign_key_id" and "event" = 'D'),1) as smallint) as "DELETE_RULE","SYSFOREIGNKEY"."role" as "FK_NAME",if "SYSFOREIGNKEY"."primary_index_id" = 0 then "SYSCONSTRAINT"."constraint_name" else "SYSINDEX"."index_name" endif as "PK_NAME",cast(if "SYSFOREIGNKEY"."check_on_commit" = 'Y' then 5 else 6 endif as smallint) as "DEFERRABILITY"   from "SYS"."SYSTABLE" as "PKTable" left outer join "SYS"."SYSUSER" as "PKUser" on "PKTable"."creator" = "PKUser"."user_id" join "SYS"."SYSFOREIGNKEY" on "PKTable"."table_id" = "SYSFOREIGNKEY"."primary_table_id" left outer join "SYS"."SYSTABLE" as "FKTable" on "SYSFOREIGNKEY"."foreign_table_id" = "FKTable"."table_id" left outer join "SYS"."SYSUSER" as "FKUser" on "FKTable"."creator" = "FKUser"."user_id" left outer join "SYS"."SYSFKCOL" on "SYSFOREIGNKEY"."foreign_table_id" = "SYSFKCOL"."foreign_table_id" and "SYSFOREIGNKEY"."foreign_key_id" = "SYSFKCOL"."foreign_key_id" left outer join "SYS"."SYSCOLUMN" as "FKColumn" on "FKColumn"."table_id" = "FKTable"."table_id" and "SYSFKCOL"."foreign_column_id" = "FKColumn"."column_id" left outer join "SYS"."SYSCOLUMN" as "PKColumn" on "PKColumn"."table_id" = "PKTable"."table_id" and "PKColumn"."column_id" = "SYSFKCOL"."primary_column_id" left outer join "SYS"."SYSINDEX" on "SYSFOREIGNKEY"."primary_table_id" = "SYSINDEX"."table_id" and "SYSFOREIGNKEY"."primary_index_id" = "SYSINDEX"."index_id" left outer join "SYS"."SYSCONSTRAINT" on "SYSCONSTRAINT"."table_object_id" = "PKTable"."object_id" and "SYSCONSTRAINT"."constraint_type" = 'P'   where "FKUser"."user_name" = 'xyz'   and "FKTable"."table_name" = 'ABC'   order by 1 asc,2 asc,3 asc,9 asc

**Comment by manticore-projects** [comment]
```
cast("isnull" ...
```
You can test any statement [here online and interactively](jsqlformatter.manticore-projects.com/jsqlformatter/demo.html?args=-c%20M4UwNiDGAuAEkENjQBQDsCuYyyfAFggE4oCMATABwCU1uwsARAAoDSAKgIIBCAMgKIB9AMKd2jAFAAaFqwCqoIowB0jDIsFoEAWxCN6TNlz5CAysIAS-ALKSZRhACMIKxtCcRNOvQdnGBggBynNb8drLCAPZgGNporpDRsWheuvp4EQDyvHLWgUEhYdKIyOhYOHiQhCQUNHQZAGIcPAGi4tKMTQogSqrqPak+jc0mguZWth1N7B56qu7OIIPpDJ0jAcGh4U1RMXEJSXHLvjvZufmbRVIlqCigEDBMiRho0IwodABmRJHaTKYATVMrkBplOvBWTEi0HwPX0AHdYUQQExPpFkQBLADmKQWngxABN9ABef5AhqZABK-AAkgBxQKsfgA1xozE4wR4paE9JoAmo9EgbEpADWIAAnoIebBSYxQRTqfTGczWYLhYIxZLpQg+UwAA5EDHaYiSxJ7FLSgA8svlrGE2VcBqNJsEZuSUqJ9QYwGN2Axry9TCZALG-AAinYbihGBjgJhsO87uAoHAMZ8mMjPj0QK8MQgwIIEDAMZF4jLYAByYQV2AwnOwAAMsHAoFgaYzICzyNz+cLxdLJMrgRrdbQsHIzbArYAzM2+e2cwT299fmTgapQexKfS6fxKQikSi3LMPYO5eSqbSGcHHYbjURJVzT7hdYw2UKOU-pTaL4rryrVHfdUvyJF9+TfNUOU1Z8fzBS8lRvQDINFCVnx1cCQAANxzN5yyrCtqCkUhAx9fMwH9aBA0YORmAAETEIRKTkARIyQVAYzjcpE3uFM23TRhM2zHsCyLaASzLUl8NrWExybFsUXbATOyEsTe1E8TBwrYdpPrCd5NgWdFwXed0xXP5z3XCytx3PcD2zJgQLPeV4P-FlVCde9HxPbVXyAz9vNA2CFSvZU3Ig9lcQC3lwL8lCtUCtdgoQgDwo-OK0NfLCcM02iCKIkjfXIgNfFo-gBHYRjmLCGRnL-ULXB+FwTlYAotikRTapCxDGA8l1-QJEAAA8YMbHSxws+1AlMLdOBpQJxFURI0GQIgEAo459IsubSoADVcfqho2kzfDYVqrijDrfy6lKqigEVBFLV1fm0DFcMkgERxk2AAFZJ1bAA2Ocl3TPBSL9YqMlKho90pHgaV4Gl2BZWAJDMtcQSBfwwhOjhZn0CQIE+OBIgwaAelgAArSJ-XRjcgTkUxbJx7olFgUtDFxxYEmRBBoHRM82BZ1x+iIZ8JCpmmLIxuC6pvNnxocLn5ii8sLKS1zb2dB9ORVgnO2J0nyYl8bQWlrHITWGYuflxKXPqpCIp1xYRstvHled6U9aJtnDaISnqZNoFpYZpnhiFm3XaVxhIB5vnWdlLpFGFjRPcJg2yb943abVu0HQjzrkrC2KnfxBKc-tCEHbSkvuVA9DbdllLi+g79EtzyvUvVFvQK99OjYD7PQQr84LZ2Q4y3ZtZdmSVxHNV6Y3ePD269fW0K9VR23SOVup-Hg5zTFtOfYz-3JdNunzDOPILbYaf9gj2+9-d0uBc5lxn9r6KObv+JFvHl214OncneF0W8LQ9yPiTE+WcpYX22vwPa+crqF01p5GuACgTwL2h-DK4EC4a2AVrLUfJDo71BFg-aJDhqp31sffuZ8g4X0mtNWGc1xBIMvlNGabDZ4nkiI4CmKYXaK3fowfhgiYC4LXMw7h80DjLWgKtda0BxR6h8JJZgNYJCInsmsIWfQNBaDSHhSAxpBAEl5ggGs9dI6iKfEY9RlYeDVjZkQAaftHDilgKQegkApATiQH42cgSpAAE5fFAA+). It will indicate where the parser fails.

**Comment by manticore-projects** [comment]
The statement is so beautiful in its own special way that I would like to add it as a stress test to JSQLformatter. Would you like to allow me please?

Below is your statement in [SQL Standard compliant Syntax](jsqlformatter.manticore-projects.com/jsqlformatter/demo.html?args=-c%20MoUQMiDCAqAEuQILGgCgHIFUxls2AxgBYCGATrKgIwBMAHAJQN7CwBEACgNLSIBCEAPpJobAFDxJkgDTtumAM4BTMmwB0bAK7KyggHYkAtkrYs5PfkOCQAEiACy4qVNmceJAEYAbExoAunj76RiZmbrwCIILoiPYgTs7wrtyQAPZemoZ66mwE6Zl6wcam+G6QAPJgmPbo0bHxEomwskgoGNi4+MTklLSMzKUAYhaRwoiijYmuw4oqOdoqRaFDI1a2DglT7MPQgb5sAd5KSyWsbDuWUTFxm87TXGkZWTl5T4UGxWHDFVU1dTeTO4IZBoVCgCAwdh5TR6PxsVDMQYAJXK9nYwAAmsAcpjgN9Kqd2Kk-EQ5rAAOp2JEgdgAM1SZCUAEsAOaFQ5BJkAE1MAF50VjBuVqQBJADi6C4IAxOXpjNZ7L2gm5JXQABE6QzmWzBABrJQAT2VPNg-LYuKFoolUplGjl2sK+qNKrw6vYAAcyEzDOQja8CsbTAAeM0Wh4EjSe72+wT+rKBgasBQ+rxeJmwxPsG2CUAARVuLmBbTyJB8CgISlQYPAUDgrRplJA6HYjNpKiUsKZpcEJAIfiZqWyptgAHJICPYNA7M2AAywcCgIsN6ctpRtxmd7u9-uDvmj9ATqdN2A0edgRcAZnnbqbGuRqIF2I0uOgSPFYpASNMjep7A5xxdUNBWFEBxUlaUcijH0yCNf9A1dDU2HtBVBDgwDH0tUDrQgu0tRQtCTUQN0kLwnUnXgoC8RAsCbVlUjHUNeCiMQpQADcOzhYcxxHBhZCoTNk1LNMMzCTAODVcYoiRbAGiaZoizQEsywrKtwVrJcKRXNhW3bTcvB7PsByHfluMnFc5wXGl60049tLXXT+y3Qzdy4g8zOPU9LNgK9b2vO8UTRc0sRxLFX3fT9vypGkDiVdCgqoq1wNtNgoJjAjVUQ5CdXS4d4swmicJI+VstiwjiKyhjnRNSj8uw5KKr1RiXWY9g2I4vcRzVHi+IElNhL8TM2DVGtoCkmSCxkDDqLqnIyHSZYzmGf5ZKaFpkBAQE5KkRtmzy6aksgr1oOdPQuSUAAPCjYBnTatsSI9dtxCp0BQJFEBFdBRA0PI9AUPwyBIdM-BOW67q8+KPuGgANHJ0zOy6PhMUHnF80puGWiakgU1BrJ2qbEto77SQIXVBEHWNUkMQwmU4kyMUPFcAFYz0XAA2PyzEE1MgcG4bBk-N6+BFMARWgGUxHvQLcRClBLkJcI9luCBBjgcpMFGpFYAAKXKD7HxlzBQC-MJ5B0THYHKXbuF2I4XkZEg-AZPc3FmVQNAWXQVUBHW9fimXaoO5HLfMG2fByHKav2wmUqOtLSqVkAVYt9XP213XHuC59Qrlr53FtoOM4SrCDtw4rFSOK7zjzsP-HjwFldVlPNZ9wuDaN+WZjNgvtmr-YCHtx3VFyzu5ndnRA3rxPG41tPfelrO8XDMBzeDvaCcKhqI4wpe6LL1C67u+AWrX4vo4a8i4rDH5d4dRqqoTpO1Znlv9YXn5qnQDuHnyZ5u6rx4Cjh3jsPXuQCK5e0Pghbe19S63zjIUOK3wf7ZG+sgieUgG7J2funV+8V341HlikZBK8rbfzeGAzk1UQ6K1ruAnkyMpDHyIeQ1BbxK5XwjDHaMMEKZsIgZITBT9U4vz9gvSGIAYZ-wtFHQqqUeFbwhuqCRFCAL0MgcfaR69kpyJOvDdhWJxEww0HDC66CBFTywcInBoi8GW1eu9T6JDHzPXsR9L6MUK6pA8AAKyUH2Su1saFsC8b4-x-C7oaKxC418Dj3E-T+gDIGqEDTulCCZDgI4xA-miiPN2Whx6Iw6gQH0gguQOxIJkxhxEdhBLgoUri-BxxiGFMNTWfAMRSCoCwSADDJqnmQD0yBsgrwDN6VjAAnN0sQABuIAA+)
```sql
SELECT  CAST(NULL AS char (128)) AS "PKTABLE_CAT"
        , "PKUser"."user_name" AS "PKTABLE_SCHEM"
        , "PKTable"."table_name" AS "PKTABLE_NAME"
        , "PKColumn"."column_name" AS "PKCOLUMN_NAME"
        , CAST(NULL AS char (128)) AS "FKTABLE_CAT"
        , "FKUser"."user_name" AS "FKTABLE_SCHEM"
        , "FKTable"."table_name" AS "FKTABLE_NAME"
        , "FKColumn"."column_name" AS "FKCOLUMN_NAME"
        , CAST((SELECT "count"() FROM "SYS"."SYSFKCOL" AS "other" WHERE "foreign_table_id" = "SYSFOREIGNKEY"."foreign_table_id" AND "foreign_key_id" = "SYSFOREIGNKEY"."foreign_key_id" AND "primary_column_id" <= "SYSFKCOL"."primary_column_id") AS smallint) AS "KEY_SEQ"
        , CAST(coalesce((SELECT CASE WHEN "referential_action" = 'C' THEN 0 ELSE CASE WHEN "referential_action" = 'N' THEN 2 ELSE 3 END END FROM "SYS"."SYSTRIGGER" WHERE "table_id" = "SYSFOREIGNKEY"."primary_table_id" AND "foreign_table_id" = "SYSFOREIGNKEY"."foreign_table_id" AND "foreign_key_id" = "SYSFOREIGNKEY"."foreign_key_id" AND "event" = 'C'), 1) AS smallint) AS "UPDATE_RULE"
        , CAST(coalesce((SELECT CASE WHEN "referential_action" = 'C' THEN 0 ELSE CASE WHEN "referential_action" = 'N' THEN 2 ELSE 3 END END FROM "SYS"."SYSTRIGGER" WHERE "table_id" = "SYSFOREIGNKEY"."primary_table_id" AND "foreign_table_id" = "SYSFOREIGNKEY"."foreign_table_id" AND "foreign_key_id" = "SYSFOREIGNKEY"."foreign_key_id" AND "event" = 'D'), 1) AS smallint) AS "DELETE_RULE"
        , "SYSFOREIGNKEY"."role" AS "FK_NAME"
        , CASE
                WHEN "SYSFOREIGNKEY"."primary_index_id" = 0
                    THEN "SYSCONSTRAINT"."constraint_name"
                ELSE "SYSINDEX"."index_name"
            END AS "PK_NAME"
        , CAST(CASE WHEN "SYSFOREIGNKEY"."check_on_commit" = 'Y' THEN 5 ELSE 6 END AS smallint) AS "DEFERRABILITY"
FROM "SYS"."SYSTABLE" AS "PKTable"
    LEFT OUTER JOIN "SYS"."SYSUSER" AS "PKUser"
        ON "PKTable"."creator" = "PKUser"."user_id"
    JOIN "SYS"."SYSFOREIGNKEY"
        ON "PKTable"."table_id" = "SYSFOREIGNKEY"."primary_table_id"
    LEFT OUTER JOIN "SYS"."SYSTABLE" AS "FKTable"
        ON "SYSFOREIGNKEY"."foreign_table_id" = "FKTable"."table_id"
    LEFT OUTER JOIN "SYS"."SYSUSER" AS "FKUser"
        ON "FKTable"."creator" = "FKUser"."user_id"
    LEFT OUTER JOIN "SYS"."SYSFKCOL"
        ON "SYSFOREIGNKEY"."foreign_table_id" = "SYSFKCOL"."foreign_table_id"
            AND "SYSFOREIGNKEY"."foreign_key_id" = "SYSFKCOL"."foreign_key_id"
    LEFT OUTER JOIN "SYS"."SYSCOLUMN" AS "FKColumn"
        ON "FKColumn"."table_id" = "FKTable"."table_id"
            AND "SYSFKCOL"."foreign_column_id" = "FKColumn"."column_id"
    LEFT OUTER JOIN "SYS"."SYSCOLUMN" AS "PKColumn"
        ON "PKColumn"."table_id" = "PKTable"."table_id"
            AND "PKColumn"."column_id" = "SYSFKCOL"."primary_column_id"
    LEFT OUTER JOIN "SYS"."SYSINDEX"
        ON "SYSFOREIGNKEY"."primary_table_id" = "SYSINDEX"."table_id"
            AND "SYSFOREIGNKEY"."primary_index_id" = "SYSINDEX"."index_id"
    LEFT OUTER JOIN "SYS"."SYSCONSTRAINT"
        ON "SYSCONSTRAINT"."table_object_id" = "PKTable"."object_id"
            AND "SYSCONSTRAINT"."constraint_type" = 'P'
WHERE "FKUser"."user_name" = 'cma_data'
    AND "FKTable"."table_name" = 'ABC'
ORDER BY    1 ASC
            , 2 ASC
            , 3 ASC
            , 9 ASC
;
```

**Comment by manticore-projects** [comment]
According to the [Sybase Documentation](http://infocenter.sybase.com/help/index.jsp?topic=/com.sybase.infocenter.dc38151.1510/html/iqrefbb/CACHAIGD.htm) there is indeed am `IF ... THEN... ELSE .. ENDIF` expression in Sybase.

Although there is also Standard Compliant [CASE WHEN Expression](http://infocenter.sybase.com/help/index.jsp?topic=/com.sybase.infocenter.dc38151.1510/html/iqrefbb/CACHAIGD.htm)

We actually could implement this Sybase specific expression, if it does not collide with any other expression.

**Comment by salonijuneja** [comment]
Sure, you can definitely add it as a stress test. It would be helpful if you could implement this :)

**Comment by manticore-projects** [comment]
> Sure, you can definitely add it as a stress test. It would be helpful if you could implement this :)

Sybase is pretty much dead, but I will keep it on the list with low priority.

Please care to to explain:
```
SELECT "count"() FROM 
```

Why the quotes and why not using a regular `count()` aggregate function?

```
cast("isnull"(...))
```
Why the quotes and why not using a regular ` COALESCE()` function? (I do not care much about `Isnull()` vs ` COALESCE()` but I need to understand why you quote some functions.)

**Comment by wumpz** [comment]
IMHO I think including this "old school" `if then else` instead of `case when` should not be done. A replace with the newer method seems to be appropriate.

**Comment by manticore-projects** [comment]
I have implemented MS SQL Servers `IF ... THEN ... ELSE` flow control for statements, which would collide with that redudantant SYBASE syntax. So I close this as "Unsupported/Won't Fix".
