### ISSUE TITLE
Encountered unexpected token, value end with backlash '\'

### ISSUE THREAD

**Issue by tuonghv** [JSQLParser/JSqlParser#1214]
**Describe the bug**
Can not parse with value end with backlash

**To Reproduce**
1. Example SQL:
    
`  insert into "BOOKS_ADMIN"."PRODUCTS"("ID","NAME","DESCRIPTION","WEIGHT","A2") values (1001,'scooter','moinhat\',3.14,'TEST_VALUE')`
   
 * However this statement below is fine because no Varchar value afterwards
  
`  insert into "BOOKS_ADMIN"."PRODUCTS"("ID","NAME","DESCRIPTION","WEIGHT") values (1001,'scooter','moinhat\',3.14)`
  
2. Parsing this SQL using JSqlParser with this statements
   
`  insert into "BOOKS_ADMIN"."PRODUCTS"("ID","NAME","DESCRIPTION","WEIGHT","A2") values (1001,'scooter','moinhat\',3.14,'TEST_VALUE')`
   
3. Exception
   Got errors below
   
> err: net.sf.jsqlparser.JSQLParserException: Encountered unexpected token: "TEST_VALUE" <S_IDENTIFIER>
>     at line 1, column 119.
> 
> Was expecting one of:
> 
>     "&"
>     ")"
>     ","
>     "::"
>     "<<"
>     ">>"
>     "COLLATE"
>     "["
>     "^"
>     "|"

   
**Expected behavior**
   expected no error, it is a normal sql for Oracle database 

**System**
 - Database you are using: Oracle 11g
- Java Version: 8
- JSqlParser version: 4.0

**Comment by manticore-projects** [comment]
Duplicate  of issue #1209
