### ISSUE TITLE
Get the position of an AST item in the input

### ISSUE THREAD

**Issue by Wisser** [JSQLParser/JSqlParser#1219]
Is it possible to determine the position (start and end index in the SQL string to be parsed) of an item in the AST?
E.g.: I parse "Select a, b from t" and get (7, 11) as position for the "SelectItemsList".

**Comment by manticore-projects** [comment]
Yes. Look at the AST Test case. It shows you how to access the nodes.

Best regards
Andreas

**Comment by Wisser** [comment]
That's great!
Thanks for the quick reply.

**Comment by Wisser** [comment]
Unfortunately, this does not work for all items. 
Or am I missing something?

For example, I encountered the following problems:

FromItem (PlainSelect#getFromItem) is not an ASTNodeAccess.
Expression (PlainSelect#getWhere) is null for complex expressions.
