### ISSUE TITLE
remove some codacy rules

### ISSUE THREAD

**Issue by wumpz** [JSQLParser/JSqlParser#1220]
Have a look at the project's PMD config. I marked the rules in palce
fro Codazy only and would like to suggest to remove these from Codazy.
It is not a bad thing at all, but some of the rules really create more
headache then helping.

**Comment by manticore-projects** [comment]
One remark: more important than adding/removing rules would be a synchronization between the PMD project config and Codacy.
It will be much easier to get notified while compiling/building and see explicitly, which exception was raised.

Right now, you push valid code and see the exception only implicitly and much later and start to dig.

**Comment by wumpz** [comment]
Is it possible that codacy somehow readys out projects pmd configuration. Keeping both in sync is somehow boring.

**Comment by manticore-projects** [comment]
If I read [this documentation](https://docs.codacy.com/repositories-configure/code-patterns/) correctly, then Codacy would detect the files `ruleset.xml` or `apex-ruleset.xml` automatically and apply these rules.

Looks like we would have to rename the current file `pmd-rules.xml` to `ruleset.xml` (am sorry, I did not know that when creating this file). 

I also think, there is an option to export the applied PMD Rules from Codacy (and to store this file in your project).
