### ISSUE TITLE
use MySQL fulltext, throw exception

### ISSUE THREAD

**Issue by Yeahfun** [JSQLParser/JSqlParser#1223]
**Describe the bug**
use MySQL fulltext, throw
net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "match" "MATCH"

**To Reproduce**
2021-06-04 17:31:54.223 WARN 748 --- [o-10003-exec-10] c.b.m.e.p.i.PaginationInnerInterceptor : optimize this sql to a count sql has exception, sql:"select
c.*,
match (name) against (?) as full_text
from
commodity c
where
match (name) against (?)
and c.deleted = 0
order by
full_text desc", exception:
net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "match" "MATCH"
at line 3, column 4.

Was expecting one of:

"!"
"("
"*"
"+"
"-"
"?"
"@"
"@@"
"ACTION"
"ANY"
"BYTE"
"CASCADE"
"CASE"
"CAST"
"CHANGE"
"CHAR"
"CHARACTER"
"COLUMN"
"COLUMNS"
"COMMENT"
"COMMIT"
"CREATE"
"CURRENT"
"CYCLE"
"DESC"
"DESCRIBE"
"DISABLE"
"DIV"
"DO"
"DOUBLE"
"DUPLICATE"
"ENABLE"
"END"
"EXCLUDE"
"EXISTS"
"EXTRACT"
"FALSE"
"FIRST"
"FN"
"FOLLOWING"
"FORMAT"
"GROUP"
"GROUP_CONCAT"
"IF"
"INDEX"
"INSERT"
"INTERVAL"
"ISNULL"
"KEY"
"LAST"
"LEFT"
"LIMIT"
"MATERIALIZED"
"NEXTVAL"
"NO"
"NOLOCK"
"NOT"
"NULL"
"NULLS"
"OF"
"OFFSET"
"ON"
"OPEN"
"OPTIMIZE"
"ORDER"
"OVER"
"PARTITION"
"PATH"
"PERCENT"
"PRECISION"
"PRIMARY"
"PRIOR"
"PROCEDURE"
"PUBLIC"
"RANGE"
"READ"
"REPLACE"
"RIGHT"
"ROW"
"ROWS"
"SCHEMA"
"SEPARATOR"
"SEQUENCE"
"SESSION"
"SET"
"SIBLINGS"
"SIZE"
"START"
"TABLE"
"TABLES"
"TEMP"
"TEMPORARY"
"TO"
"TOP"
"TRUE"
"TRUNCATE"
"TYPE"
"UNSIGNED"
"VALIDATE"
"VALUE"
"VALUES"
"VIEW"
"XML"
"XMLSERIALIZE"
"ZONE"
"{d"
"{t"
"{ts"
"~"
<K_DATETIMELITERAL>
<K_DATE_LITERAL>
<K_TIME_KEY_EXPR>
<S_CHAR_LITERAL>
<S_DOUBLE>
<S_HEX>
<S_IDENTIFIER>
<S_LONG>
<S_QUOTED_IDENTIFIER>

**Expected behavior**

**System**
 - MySQL8
- Java 1.8
- JSqlParser 4.0

**Comment by manticore-projects** [comment]
MySQL `MATCH() AGAINST()` full text operations are not supported (yet).

**Comment by manticore-projects** [comment]
Actually, it seems I was wrong: There is already a`FullTextSearch` Expression implemented. I will check this out.

**Comment by wumpz** [comment]
At the moment only string literals are allowed for the against expression: `match (name) against ('test')` works.

**Comment by funyule** [comment]
这就非常尴尬，在1.2版本上居然有一个使用全文检索成功，我拿到另一个项目就运行和这个issue同样的问题。能力太差，没看出来问题 = =。

**Comment by funyule** [comment]
tested at 3.2, `match (name) against ({0})` is not allowed, `match (name) against ('test')` is working

**Comment by manticore-projects** [comment]
Solved, please test it thoroughly as I do not use such Full Text Search expressions myself.
Please close this issue when verified.
