### ISSUE TITLE
Support PostgreSQL substring

### ISSUE THREAD

**Issue by philipp94831** [JSQLParser/JSqlParser#124]
``` sql
SELECT substring(mycolumn from 1 for 5)
FROM mytable
```

[Documentation](http://www.postgresql.org/docs/9.4/static/functions-string.html#FUNCTIONS-STRING-SQL)

**Comment by wumpz** [comment]
Is this subexpression "from 5 to 6" something that can be used in general or is this bound to substring? I try to avoid making a keyword out of "substring" to get this conditional behaviour. Cheers Tobias

**Comment by philipp94831** [comment]
At first, I made a little syntax mistake, it's `from 1 for 5`
I'm not sure wether this can be used in general in PostgreSQL, at least it's used with `overlay`, too

**Comment by wumpz** [comment]
this was solved recently by a pull request
