### ISSUE TITLE
To Do List: Missing Oracle specific statements

### ISSUE THREAD

**Issue by manticore-projects** [JSQLParser/JSqlParser#1245]
This is just a reminder for myself, so far I found the following Oracle specific statements missing:

- ~~`ALTER SYSTEM`~~ Fixed by PR #1288
- ~~`RENAME table TO ...`~~ Fixed by PR #1286
- ~~`PURGE ...`~~ Fixed by PR #1287
- ~~`ALTER TABLE ...` `DROP` for multiple columns~~ fixed by PR #1379
- ~~`ALTER TABLE ...` `ADD` for multiple columns~~ fixed, it is working in JSQLFormatter
- `INSERT` for multiple values
- ~~`ALTER TABLE ... MOVE TABLESPACE ...`~~ fixed by PR #1293

Please feel free to add to the list. I would want to implement these statements eventually.

**Comment by AnEmortalKid** [comment]
More oracle things missing as far as I remember: https://docs.oracle.com/cd/B19306_01/server.102/b14200/queries003.htm

**Comment by wumpz** [comment]
For sure. And from I think nearly 300 test sqls at the moment 172 are parsed successfully. Look into SelectOracleTest.

**Comment by manticore-projects** [comment]
> More oracle things missing as far as I remember: https://docs.oracle.com/cd/B19306_01/server.102/b14200/queries003.htm

Greetings, please clarify because I think that `Hierarchical Queries` have been implemented yet and I also have added support for `CONNECT_BY_ROOT` via PR #1282. What is left open please?

**Comment by manticore-projects** [comment]
> For sure. And from I think nearly 300 test sqls at the moment 172 are parsed successfully. Look into SelectOracleTest.

Good chunk from the failing tests is about Oracle's `MultiInsert`. How do you want me to approach this:
a) refactor and amend the existing `Insert` or
b) provide a new `MultiInsert` instead (including the standard compliant multiple `VALUES` syntax)

At the moment I tend to go route b) but am a kind of undecided. Please advise.
