### ISSUE TITLE
JSQLParserException on ClickHouse Sql 

### ISSUE THREAD

**Issue by Jerry-max199** [JSQLParser/JSqlParser#1248]
**Describe the bug**
when  i call CCJSqlParserHelper.parse(Sql) function to parse ClickHouse sql,It throws an exception like this:
Exception in thread "main" net.sf.jsqlparser.JSQLParserException: Encountered unexpected token: "(" "("
    at line 7, column 5.

Was expecting one of:

    "&"
    ","
    "::"
    ";"
    "<<"
    ">>"
    "ACTION"
**To Reproduce**
1. the Exception sql :
select
	t1.`dt` as t1_dt,
	t1.`sign` as t1_sign,
	sum(cast (cast( t1.`sign` as Nullable(char))   as  Nullable(decimal(30, 10)))) as "t1_sum_sign"
from
	tableName t1
group by
	t1.`dt`,
	t1.`sign`
but  when  i modify the sql as follow 
select
	t1.`dt` as t1_dt,
	t1.`sign` as t1_sign,
	sum(cast (cast( t1.`sign` as char)   as  decimal(30, 10) )) as "t1_sum_sign"
from
	tableName t1
group by
	t1.`dt`,
	t1.`sign`
it parse sucessfully!
Does it not supported ClickHouse Sql grammar like Nullable?

**System**
 - ClickHouse
- 1.8
- 4.0

**Comment by wumpz** [comment]
I corrected the grammar that Nullable(char) is now parseable.

**Comment by Jerry-max199** [comment]
> 
> 
> I corrected the grammar that Nullable(char) is now parseable.
