### ISSUE TITLE
Parser fails on a query containing current timestamp function

### ISSUE THREAD

**Issue by salonijuneja** [JSQLParser/JSqlParser#1249]
Query containing current timestamp failing with error:

[Tried out interactively](jsqlformatter.manticore-projects.com/jsqlformatter/demo.html?args=-c%20LTAEDMEMEsBsFMAmoAuB7CaBOBbSLQBnFSLFAKAGUBRAGWoGEAVUAKnIDEAlAeQFlU8YgDpIAIwDG5AOoAJal2qgJaWKAB8oZQFcsWeADsCKaDiEkcAB3IBuciAgwEydJlz5QhxEA+)

**Comment by manticore-projects** [comment]
Kudos for trying.
You forgot the `_` in `current_timestamp`, the query should be invalid without it.

[This is the correct version](http://jsqlformatter.manticore-projects.com/jsqlformatter/demo.html?args=-c%20MoUQMiDCAqAEBUAoAYgJQPIFlYBcCmAzjgHQCGARgMaIDqAEiKiLJQPYA2sAfCwK4BO-PADscAfRwBLALaEcpaQAdEAbiA+)

Please close when you are able to confirm it.

**Comment by salonijuneja** [comment]
Thanks!
Yes, current_timestamp works but current timestamp is also valid atleast in DB2 and IQ (tested).
eg. DB2: https://www.ibm.com/docs/en/db2-for-zos/11?topic=registers-current-timestamp
IQ: http://infocenter.sybase.com/help/index.jsp?topic=/com.sybase.help.sqlanywhere.12.0.1/dbreference/current-timestamp-special-wsqlref.html

**Comment by manticore-projects** [comment]
Thank you for pointing this out, it looks like a more generic topic: https://www.ibm.com/docs/en/db2-for-zos/11?topic=elements-special-registers

I do not think we have any support for this DB2 `SPECIAL REGISTERS` yet. Although I have a great sympathy for DB2 and Sybase (real databases!, not this hipster ....) I have never used these specific syntax.

I think it could be supported eventually, but someone has to find the time to write a new `DB2SpecialRegisterExpression`.
First step maybe: change the name of this issue accordingly and then we can put it onto the To-Do List.

**Comment by manticore-projects** [comment]
I have implemented the Date/Time related `Special Registers`.

**Comment by salonijuneja** [comment]
Thanks for implementing the change. This will released in 4.2 right. Asking as we don't use snapshots :(

**Comment by manticore-projects** [comment]
Unfortunately we just missed the 4.1 release.
Only @wumpz  can decide what next, sorry.

**Comment by manticore-projects** [comment]
Closed via PR #1252
