### ISSUE TITLE
Enable 'value' as column name

### ISSUE THREAD

**Issue by philipp94831** [JSQLParser/JSqlParser#125]
It would be nice if value (and other keywords?) would be supported as a column name because

~~~sql
CREATE TABLE mytable (
  value INTEGER
)
~~~

gives a `ParseException`

**Comment by wumpz** [comment]
There are already multiple keywords allowed here. Nevertheless IMHO I consider this a bad practice. As you may have seen function names "left"  and "right" were introduced recently. But with every keyword as a column name, table name or whatever the readability of your SQL decreases. However I will look into it. Tobias

**Comment by philipp94831** [comment]
Thank you very much :)

**Comment by wumpz** [comment]
In fact your example was parsed successfully.

~~~sql
CREATE TABLE mytable (
  value INTEGER
)
~~~

But *values* as a column name did not work. Could you check that? Using the actual SNAPSHOT both *values* and *value* should be recognized.
