### ISSUE TITLE
Parser  throwing error on query containing  double slash //

### ISSUE THREAD

**Issue by Prerna27agrawal** [JSQLParser/JSqlParser#1250]
Sample Query-
Select test.* from(Select * from sch.PERSON_TABLE  // root test
 ) as test

Error-
Encountered unexpected token: "/" "/" at line 2,column 10.

**Comment by manticore-projects** [comment]
Greetings.

Please state which RDBMS is used and the purpose of the `//` -- most people here speak Oracle and a bit Postgresql.

**Comment by wumpz** [comment]
This statement is parsed perfectly well. Since `//`starts a one line comment, you have to be sure that `) as test` is following in the next line. 
Which version of JSqlParser do you use?

**Comment by Prerna27agrawal** [comment]
Version 4

**Comment by manticore-projects** [comment]
> This statement is parsed perfectly well. Since `//`starts a one line comment, you have to be sure that `) as test` is following in the next line.
> Which version of JSqlParser do you use?

Guys, you are confusing the hell out of me: Is the `//` just a comment annotation (in USQL?) or is it supposed to be some relevant part of the table name `sch.PERSON_TABLE // root` ?

**Comment by manticore-projects** [comment]
Sorry for verbosity, this is the complete picture with JSQLParser 4.1 Snapshot:

![image](https://user-images.githubusercontent.com/18080123/124064436-f5c45d80-da5e-11eb-96fa-b8febcbad05f.png)

**Comment by Prerna27agrawal** [comment]
Yes Using as a comment

**Comment by Prerna27agrawal** [comment]
That is my usecase  using // as comment 
 it is not able to parse .


> Sorry for verbosity, this is the complete picture with JSQLParser 4.1 Snapshot:
> 
> ![image](https://user-images.githubusercontent.com/18080123/124064436-f5c45d80-da5e-11eb-96fa-b8febcbad05f.png)

That is my usecase  using // as comment 
 it is not able to parse .

**Comment by Prerna27agrawal** [comment]
Using as comment is my usecase
It is not able to parse // when used as comment in the query

**Comment by Prerna27agrawal** [comment]
Using the 4.1 version now but still // giving error
yup using ) as test in the next line

**Comment by wumpz** [comment]
OMG. My fault. At the moment JSqlParser only supports `--` for one line comments. I will improve.

**Comment by manticore-projects** [comment]
> OMG. My fault. At the moment JSqlParser only supports `--` for one line comments. I will improve.

This relates to my suggestion from yesterday: Maybe we want to scope, which RDBMS we really want to support and focus on. Just to tell the end users what they can expect.

I for myself was not expecting any support for `//` comments (simply because it is quite exotic).

**Comment by wumpz** [comment]
version 4.2-SNAPSHOT
