### ISSUE TITLE
MariaDB: RENAME TABLE is not a supported statement

### ISSUE THREAD

**Issue by j6f1** [JSQLParser/JSqlParser#1253]
```RENAME TABLE table TO ...``` is missing for MariaDB. Unfortunately ```ALTER TABLE table RENAME TO ...``` does not work either.

https://mariadb.com/kb/en/rename-table/

**Steps to reproduce:**

1. Add SQL script to rename a table. For example, ```RENAME TABLE IF EXISTS xyz TO zyx;```
2. Parse the SQL... ```Statements statements = CCJSqlParserUtil.parseStatements(sqlString);```

Exception:
```
Caused by: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "RENAME" "RENAME"
    at line 344, column 1.
Was expecting one of:
    "("
    ";"
    "ALTER"
    "BEGIN"
    "CALL"
    "COMMENT"
    "COMMIT"
    "CREATE"
    "DECLARE"
    "DELETE"
    "DESCRIBE"
    "DROP"
    "EXEC"
    "EXECUTE"
    "EXPLAIN"
    "GRANT"
    "INSERT"
    "MERGE"
    "REPLACE"
    "RESET"
    "ROLLBACK"
    "SAVEPOINT"
    "SET"
    "SHOW"
    "TRUNCATE"
    "UPDATE"
    "UPSERT"
    "USE"
    "VALUES"
    "WITH"
    <EOF>
    <K_SELECT>
```

**Comment by wumpz** [comment]
PRs are welcome. Look into the *Replace* production. You could do something similar.
