### ISSUE TITLE
Update ignore and delete ignore not parseable

### ISSUE THREAD

**Issue by Todd102030** [JSQLParser/JSqlParser#1254]
**Describe the bug**
Update ignore and delete ignore statements throw exception when parsing.

**To Reproduce**
1. Example SQL
update ignore tRequirement set VendorItem=? where cn=@cn and VendorItem=?

2. Parsing this SQL using JSqlParser with this statements
SimpleNode node = (SimpleNode) CCJSqlParserUtil.parseAST(sqlInput);

3. Exception
Encountered unexpected token: "ignore" "IGNORE"
    at line 1, column 8.

**Expected behavior**
Expected to parse similarly to statements without the "ignore" keyword

**System**
 - MySQL 8.0
- Java Version - JDK 8
- JSqlParser version - 4.1

Thanks for all your work on this library, it's really great!

**Comment by wumpz** [comment]
So this is only about *update* statements? PRs are welcome. Grammar line 950 should be the start.
