### ISSUE TITLE
Performance issue with some H2 queries containing COALESCE clause

### ISSUE THREAD

**Issue by akilovich** [JSQLParser/JSqlParser#1260]
Hi. Our users [experience](https://github.com/dbeaver/dbeaver/issues/13141) some performance issues with H2 queries (see below). 

**Steps to reproduce the behavior:**
Run this query:
```sql
select 
  cast((
    select coalesce(
      json_arrayagg(json_array("v0") order by "t"."v0"),
      json_array(null on null)
    )
    from (
      select 2 "v0"
      union
      select 4 "ID"
    ) "t"
  ) as text);
```
It takes a considerable amount of time for JSqlParser to parse this query. Profiling shows that the parser spends a ton of time inside `net.sf.jsqlparser.parser.CCJSqlParser.jj_add_error_token()`. However, the query 
```sql
select 
  cast((
    select 
      json_arrayagg(json_array("v0") order by "t"."v0")
    from (
      select 2 "v0"
      union
      select 4 "ID"
    ) "t"
  ) as text);
```
(without `COALESCE()`) is parsed without any problems. See the ticket in the link above for some more profiling info.

**System**
 - H2
- SapMachine 11.0.11, AdoptOpenJDK 11.0.11
- JSqlParser 4.1

**Comment by manticore-projects** [comment]
Greetings, thank you for reporting. I have responded to the original case on the DBeaver's site already.
Two things:

1) Luka's original query seems to parse fine here (0.14 secs for parsing and deparsing). If this is not sufficient, please state the acceptable constraints.

2) The query above seems to be wrong (maybe copy'n paste error). Luka's original query parses, the query above does not parse:
```java
@Test(timeout = 20000)
    public void testIssue1260() throws JSQLParserException {
      // This parses just fine within 0.14 seconds  
      assertSqlCanBeParsedAndDeparsed(
        "select \n" +
        "  cast((\n" +
        "    select \n" +
        "      json_arrayagg(json_array(\"v0\") order by \"t\".\"v0\")\n" +
        "    from (\n" +
        "      select 2 \"v0\"\n" +
        "      union\n" +
        "      select 4 \"ID\"\n" +
        "    ) \"t\"\n" +
        "  ) as text)", true);
      
      // This does not parse, please double check
      assertSqlCanBeParsedAndDeparsed(
        "select \n" +
        "  cast((\n" +
        "    select coalesce(\n" +
        "      json_arrayagg(json_array(\"v0\") order by \"t\".\"v0\")" +
          
        // issue with the following 2 lines not part of the original request. are these valid?
        // ",\n" +
        //"      json_array(null on null)\n" +
        "    )\n" +
        "    from (\n" +
        "      select 2 \"v0\"\n" +
        "      union\n" +
        "      select 4 \"ID\"\n" +
        "    ) \"t\"\n" +
        "  ) as text)", true);
    }
```

**Comment by akilovich** [comment]
Thank you for your investigation.
