### ISSUE TITLE
sql parser exception when with double quotation marks

### ISSUE THREAD

**Issue by maitong** [JSQLParser/JSqlParser#1264]
**Describe the bug**

**To Reproduce**
1. Example SQL
        SELECT id,account,real_name,mobile,email,mobile_account,created_at,status,merchant_type,type FROM user WHERE deleted = 0 and account like "%"'bbc'"%" and merchant_id = 182979 and type = 2 and id != 25000167979 order by created_at desc;
2. Parsing this SQL using JSqlParser with this statements
        CCJSqlParserUtil.parse(String.class);
3. Exception
         Was expecting one of:

    "&"
    "&&"
    "::"
    ";"
    "<<"
    ">>"
    "AND"
    "AT"
    "COLLATE"
    "CONNECT"
    "ESCAPE"
    "FOR"
    "GROUP"
    "HAVING"
    "OR"
    "ORDER"
    "START"
    "XOR"
    "["
    "^"
    "|"
    <EOF>

	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parseStatement(CCJSqlParserUtil.java:190)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:63)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:38)
**Expected behavior**

**System**
 - mysql 5.7.17
- Java 1.8.0_221
- JSqlParser 4.2

**Comment by manticore-projects** [comment]
Your quotes are wrong. This one would be correct
```sql
SELECT  id
        , account
        , real_name
        , mobile
        , email
        , mobile_account
        , created_at
        , status
        , merchant_type
        , type
FROM user
WHERE deleted = 0
    AND account LIKE '%\"bbc\"%'
    AND merchant_id = 182979
    AND type = 2
    AND id != 25000167979
ORDER BY created_at DESC
;
```

[Test it here online and interactively.](http://jsqlformatter.manticore-projects.com/jsqlformatter/demo.html?args=-c%20MoUQMiDCAqAEsEsAmAoe70BpYEMDGeA9gK4B2ALmhlrAE4CmOANgPqk4C29V1s2HhAEYIm3XvGz0OOET2r8hI+i3xEylcX1h4GOcvSQqN47AGdye4qbkZ+9WngAWOCi3IBPAA5iTsD95QAMQAlAHkAWVgrexQAdQAJEGCQWCR6UX0kWABeWAAGOQBBADkAEVwCEgpYMABJAGkUgHIAUgAdACJBQTxOlqaistguB2dXZBzYAEYADgAmAE4AdgXB8v96Sbm1xCyAQly5gFY806mANhWVlFDg0qTYACEATW1dTKNYe+BIFABuIA+)

Please close after confirmation.

**Comment by maitong** [comment]
> Your quotes are wrong. This one would be correct
> 
> ```sql
> SELECT  id
>         , account
>         , real_name
>         , mobile
>         , email
>         , mobile_account
>         , created_at
>         , status
>         , merchant_type
>         , type
> FROM user
> WHERE deleted = 0
>     AND account LIKE '%\"bbc\"%'
>     AND merchant_id = 182979
>     AND type = 2
>     AND id != 25000167979
> ORDER BY created_at DESC
> ;
> ```
> 
> [Test it here online and interactively.](http://jsqlformatter.manticore-projects.com/jsqlformatter/demo.html?args=-c%20MoUQMiDCAqAEsEsAmAoe70BpYEMDGeA9gK4B2ALmhlrAE4CmOANgPqk4C29V1s2HhAEYIm3XvGz0OOET2r8hI+i3xEylcX1h4GOcvSQqN47AGdye4qbkZ+9WngAWOCi3IBPAA5iTsD95QAMQAlAHkAWVgrexQAdQAJEGCQWCR6UX0kWABeWAAGOQBBADkAEVwCEgpYMABJAGkUgHIAUgAdACJBQTxOlqaistguB2dXZBzYAEYADgAmAE4AdgXB8v96Sbm1xCyAQly5gFY806mANhWVlFDg0qTYACEATW1dTKNYe+BIFABuIA+)
> 
> Please close after confirmation.

yes，this would be correct when use like '%\"bbc\"%'，  like "%"'bbc'"%" be supported when use mybatis or navicat premium，me want to use in mybatis interceptor parser this sql

**Comment by manticore-projects** [comment]
You will need to mangle your SQL before sending it to JSQLParser and replace the MyBatis Quotes with proper SQL compliant quotes. There is no other solution available (at the moment).

**Comment by maitong** [comment]
> You will need to mangle your SQL before sending it to JSQLParser and replace the MyBatis Quotes with proper SQL compliant quotes. There is no other solution available (at the moment).

i get it, thanks

**Comment by ChenZheOnePiece** [comment]
```
SELECT
	id,
	flag,
	created_by,
	created_date,
	modified_by,
	modified_date,
	address,
	avatar,
	avatar_content,
	birthday,
	blog,
	email,
	gender,
	id_number,
	integral,
	login_name,
	nickname,
	phone_num,
	remark,
	state,
	tag,
	user_index,
	user_name,
	experience,
	balance 
FROM
	user_info 
WHERE
	flag = 1 
	AND login_name LIKE "%" ? "%"
```
How to write SQL like this

**Comment by wumpz** [comment]
You could use the *concat* function of mysql. This has the advantage to be implemented in multiple database types.

```sql
select
*
from user_info
where flag = 1 and login_name like concat('%', ?, '%')
```

**Comment by ChenZheOnePiece** [comment]
SQL needs to be compatible with Oracle MySQL PG    ,if in xml   "%"#{name}"%" It is universal .Is there any other way to have this effect

**Comment by wumpz** [comment]
Double quotation marks are not allowed there for Oracle and Postgresql. **concat** is a two parameter funciton in Oracle, therefore: 

``´sql
concat(concat('%', ?), '%')
```

should do the trick.

**Comment by manticore-projects** [comment]
Can we close this as answered and explained?

**Comment by wumpz** [comment]
Since there is not action for over a year ...
