### ISSUE TITLE
StatementVisitor not visisting the whole query

### ISSUE THREAD

**Issue by simkoc** [JSQLParser/JSqlParser#1266]
**Describe the bug**
I want to count the amount of subqueries (i.e., Delete, Select, ...) in a parsed query. However, the visitor seems to only visit the first element which is inconsistent [with my understanding of the visitor pattern](https://en.wikipedia.org/wiki/Visitor_pattern#Java_example). 

**To Reproduce**
Visitor Implementation (in Scala):
```
class SubqueryCounterVisitor extends StatementVisitorAdapter {
  var counter = 0
  override def visit(delete: Select): Unit = {
    counter += 1
  }
  override def visit(delete: Delete): Unit = {
    counter += 1
  }
  override def visit(delete: Update): Unit = {
    counter += 1
  }
  override def visit(delete: Insert): Unit = {
    counter += 1
  }
}
```

Visitor usage
```
val query1 = "SELECT column FROM ttest"
val query2 = "SELECT column FROM ttest WHERE elem IN (SELECT id FROM etest)"
val visitor1 = new SubqueryCounterVisitor()
val visitor2 = new SubqueryCounterVisitor()
CCJSqlParserUtil.parse(query1).accept(visitor1)
CCJSqlParserUtil.parse(query2).accept(visitor2)
println(visitor1.counter)
println(visitor2.counter)
```

**Expected behavior**

Both visitor have a counter of 1 but the second should have a counter of visitor 2.

**Comment by manticore-projects** [comment]
As far as I understand it (I will look into the code for details later), `SubSelect` != `Select` Statement.
You would need to add the particular `SubSelect` Expression and `SubSelect` FromItem to your visitor.

**Comment by wumpz** [comment]
This subselect is not a statement in itself. The statementvisitor only gets called for the so called primary statement (`select column from ...`).
In this example I use the table name finder because it has a nearly complete visitor implementation:

```java
String sql = "SELECT column FROM ttest WHERE elem IN (SELECT id FROM etest)";

Statement statement = CCJSqlParserUtil.parse(sql);

TablesNamesFinder tablesNamesFinder = new TablesNamesFinder() {
    @Override
    public void visit(SubSelect subSelect) {
        System.out.println("subselect " + subSelect.toString());
        super.visit(subSelect); 
    }

    @Override
    public void visit(Select select) {
        System.out.println("select " + select.toString());
        super.visit(select); 
    }

};
tablesNamesFinder.getTableList(statement);
```

This delivers:

```
select SELECT column FROM ttest WHERE elem IN (SELECT id FROM etest)
subselect (SELECT id FROM etest)
```

You get the idea.

**Comment by manticore-projects** [comment]
Can we close this as answered and explained?
