### ISSUE TITLE
Parsing syntax 'UNION ALL'  ERROR

### ISSUE THREAD

**Issue by Style1002** [JSQLParser/JSqlParser#1268]
**Describe the bug**

sql = (SELECT __time FROM traffic_protocol_stat_log LIMIT 1) UNION ALL (SELECT __time FROM traffic_protocol_stat_log  **ORDER BY __time** LIMIT 1)

After CCJSqlParserUtil.parse(sql)

sql = (SELECT __time FROM traffic_protocol_stat_log LIMIT 1) UNION ALL (SELECT __time FROM traffic_protocol_stat_log LIMIT 1) **ORDER BY __time**

**To Reproduce**
![image](https://user-images.githubusercontent.com/39426398/125766714-49ee4889-2bdf-4a74-ab62-c28d6aa8cb57.png)

**System**
- Database：apache druid
- Java Version：1.8
- JSqlParser version：4.0

Thanks！

**Comment by wumpz** [comment]
JSqlParser treats the *order by* statement as the global one.  What does this internal `order by` mean?

**Comment by Style1002** [comment]
> JSqlParser treats the _order by_ statement as the global one. What does this internal `order by` mean?

It's just example.
order by statement as one of，not as the global.
And the SQL cannot be executed after parsing.

**Comment by Style1002** [comment]
> > JSqlParser treats the _order by_ statement as the global one. What does this internal `order by` mean?
> 
> It's just example.
> order by statement as one of，not as the global.
> And the SQL cannot be executed after parsing.

JSqlParser 3.0 version is correct

**Comment by manticore-projects** [comment]
Greetings,  I have just tested your example with 4.2 Snapshot from Git:
```java
@Test
    public void testUnionLimitOrderByIssue1255() throws JSQLParserException {
        String sqlStr = "(SELECT __time FROM traffic_protocol_stat_log LIMIT 1) UNION ALL (SELECT __time FROM traffic_protocol_stat_log ORDER BY __time LIMIT 1)";
        
        Statement stmt = CCJSqlParserUtil.parse(sqlStr);
        System.out.println(stmt.toString());
        
        assertSqlCanBeParsedAndDeparsed(sqlStr, true);
    }
```

The test succeeds, I even double checked the result of the `toString()` myself.
What exactly is the problem please?

**Comment by Style1002** [comment]
> Greetings, I have just tested your example with 4.2 Snapshot from Git:
> 
> ```java
> @Test
>     public void testUnionLimitOrderByIssue1255() throws JSQLParserException {
>         String sqlStr = "(SELECT __time FROM traffic_protocol_stat_log LIMIT 1) UNION ALL (SELECT __time FROM traffic_protocol_stat_log ORDER BY __time LIMIT 1)";
>         
>         Statement stmt = CCJSqlParserUtil.parse(sqlStr);
>         System.out.println(stmt.toString());
>         
>         assertSqlCanBeParsedAndDeparsed(sqlStr, true);
>     }
> ```
> 
> The test succeeds, I even double checked the result of the `toString()` myself.
> What exactly is the problem please?
> 
> Please close the case, when verified.

Our Feedback are Correct, The test Succeeds when  changed the Version from 4.0 to 4.1
Thanks!
