### ISSUE TITLE
Oracle hierarchical query with CONNECT_BY_ROOT

### ISSUE THREAD

**Issue by mikeshaw0917** [JSQLParser/JSqlParser#1269]
**Describe the bug**
I'm using JSQLParser on my project and having issues parsing connect_by_root query. Parser is failing.

**To Reproduce**
1. "  SELECT CONNECT_BY_ROOT last_name as name, salary FROM employees WHERE  department_id = 110 CONNECT BY PRIOR employee_id = manager_id";
2. Parsing this SQL using JSqlParser with this statements
 @Test
    public void testOracleHierarchicalQuery1442() throws JSQLParserException {
        String sql = "SELECT CONNECT_BY_ROOT last_name as name, salary FROM employees WHERE  department_id = 110 CONNECT BY PRIOR employee_id = manager_id";
        validateNoErrors(sql, 1, DatabaseType.ORACLE);
    }

3. Exception

**Expected behavior**

**System**
 - Oracle 11g
- 8
- JSqlParser version - 4.1

**Comment by wumpz** [comment]
`CONNECT_BY_ROOT` is not (yet) imported

**Comment by manticore-projects** [comment]
Please give it a thorough testing as I do not work myself with hierarchical queries and lack the practical experience.
Cheers.
