### ISSUE TITLE
Support local variables for tables

### ISSUE THREAD

**Issue by janmotl** [JSQLParser/JSqlParser#127]
Currently local variables work very in from clauses:
`SELECT @col1 FROM t1`
in where clauses:
`SELECT col1 FROM t1 WHERE col1=@condition1`
but fails in from clauses:
`SELECT col1 FROM @t1`

And local variables in from clauses are valid as well. Example from https://msdn.microsoft.com/en-us/library/ms188927.aspx:
`SELECT EmpID, OldVacationHours, NewVacationHours, ModifiedDate
FROM @MyTableVar;`

**Comment by wumpz** [comment]
duplicate
