### ISSUE TITLE
Oracle User function in a SQL query is not working

### ISSUE THREAD

**Issue by mikeshaw0917** [JSQLParser/JSqlParser#1270]
**Describe the bug**
Trying to use Oracle function call in a SELECT query and cannot parse the statement.

**To Reproduce**
1. Example SQ - select r.*, test.numeric_function (  p_1 => r.param1
                                   , p_2 => r.param2 )  as resultaat2
from results r
2. Parsing this SQL using JSqlParser with this statements
3. Exception - Cannot parse 

**Expected behavior**

**System**
 - Oracle 11g
- Java Version - 8
- JSqlParser version - 4.1

**Comment by wumpz** [comment]
This parameter name mapping via `=>` is not (yet) possible.
