### ISSUE TITLE
The sqlserver 'IF' keyword cannot be parsed.

### ISSUE THREAD

**Issue by WillTang2018** [JSQLParser/JSqlParser#1273]
**Describe the bug**
The sqlserver 'IF' keyword cannot be parsed.

**To Reproduce**
1. IF OBJECT_ID('tOrigin', 'U') IS NOT NULL DROP TABLE tOrigin
2. String sql1="IF OBJECT_ID('tOrigin', 'U') IS NOT NULL DROP TABLE tOrigin";
    Statements stmts = CCJSqlParserUtil.parseStatements(sql1);
3. Exception
Exception in thread "main" net.sf.jsqlparser.JSQLParserException: Encountered unexpected token: "IF" "IF"
    at line 1, column 1.

**Expected behavior**
Can I parse IFs?

System
Database = sqlserver
Java Version = 1.8
JSqlParser version = tested with 4.0

**Comment by manticore-projects** [comment]
```sql
IF Boolean_expression   
     { sql_statement | statement_block }   
[ ELSE   
     { sql_statement | statement_block } ]   
```

is not supported yet as it works in Transact SQL only.

**Comment by manticore-projects** [comment]
I have implemented it for you, please give it a try and feed back.
Attention: Only `statements`, no `statement_blocks` yet.
