### ISSUE TITLE
net.sf.jsqlparser.JSQLParserException: Encountered unexpected token: "modify" "MODIFY"

### ISSUE THREAD

**Issue by zero-wsh** [JSQLParser/JSqlParser#1280]
**Describe the bug**
parser error.

**To Reproduce**
1. Example SQL: select id,name,modify from t_table
2. Parsing this SQL using JSqlParser with this statements
3. Exception

**Expected behavior**
parser success.

**System**
 - sqlserver2012
- Java 1.8
- JSqlParser 4.1

**Comment by manticore-projects** [comment]
Greetings.

`MODIFY` is a preserved keyword and you would need to quote such a column-name.
Also, when using `SquaredBracketQuotation` `[` `]` you will need to explicitly activate it in the Parser as it collides with the more common Array Constructors.

Please close this case after verification as this not an error.

**Comment by zero-wsh** [comment]
Can you give an example

**Comment by manticore-projects** [comment]
Greetings.

your can activate Transact-SQL compliant SquaredBracketQuotation like this:
```java
boolean useSquareBracketQuotation = true;
String statementSql = "select id,name, [modify] from t_table";

Statement statement = CCJSqlParserUtil.parse(
    statementSql
    , parser -> parser.withSquareBracketQuotation(useSquareBracketQuotation)
);
```
