### ISSUE TITLE
net.sf.jsqlparser.JSQLParserException: Encountered unexpected token: "[" "["

### ISSUE THREAD

**Issue by zero-wsh** [JSQLParser/JSqlParser#1281]
**Describe the bug**
parser error.

**To Reproduce**
1. Example SQL: select id,name,[order] from t_table
2. Parsing this SQL using JSqlParser with this statements
3. Exception

**Expected behavior**
keword query parser success.

**System**
 - sqlserver2012
- Java 1.8
- JSqlParser 4.1

**Comment by manticore-projects** [comment]
Greetings.

When using `SquaredBracketQuotation` `[` `]` you will need to explicitly activate it in the Parser as it collides with the more common Array Constructors.

Please close this case after verification as this not an error.

**Comment by zero-wsh** [comment]
I don't know how to operate. 
![image](https://user-images.githubusercontent.com/44697042/126584374-22d69f44-dc57-46ab-9e5b-b4591b002991.png)

**Comment by manticore-projects** [comment]
Greetings.

your can activate Transact-SQL compliant SquaredBracketQuotation like this:
```java
boolean useSquareBracketQuotation = true;
String statementSql = "select id,name,[order] from t_table";

Statement statement = CCJSqlParserUtil.parse(
    statementSql
    , parser -> parser.withSquareBracketQuotation(useSquareBracketQuotation)
);
```
