### ISSUE TITLE
Support JPQL positional parameters

### ISSUE THREAD

**Issue by alessiostalla** [JSQLParser/JSqlParser#129]
The format is ?n where n is an integer > 0: https://docs.oracle.com/html/E24396_01/ejb3_langref.html#ejb3_langref_pos_params

So far in our use cases JSqlParser understands HQL/JPQL just fine, even if it's not its goal. If it's not hard, supporting positional parameters would spare us some ugly workarounds.

**Comment by wumpz** [comment]
This should be no problem. I will look into it.
