### ISSUE TITLE
failed to parse update queries into AST tree

### ISSUE THREAD

**Issue by TsukimiRini** [JSQLParser/JSqlParser#1298]
It's more of a question instead of bug report. I'm tring to get the hierachical structure of SQL queries with Jsqlparser. At first I thought it would be perfect to use the `parseAST` method. But I found that it doesn't work well for many queries like update and insert.

I tried to parse queries with TablesNamesFinder but it seems that I need to override all the `visit` functions to achieve it, which is not my first choice. And I also need to get the range of every element/token in the query, but I can hardly get the position data from some of `Statement` elements like `Update`.

Any idea about how to generate a hierachical structure with range information? 

Thanks!

**Comment by manticore-projects** [comment]
Greetings.

If I was in your shoes, then indeed I would take the DeParser Implementation and overwrite all the visit() methods and build the Syntax Tree and persist the position within each method.

**Comment by TsukimiRini** [comment]
I'm confused about the "persist the position within each method" part, how can i persist the data when there is no field for it in elements?

I'm new to JSqlparser, so sorry if my question is silly

**Comment by manticore-projects** [comment]
The Deparser will rebuild the SQL String from the Java Objects, mostly by appending to a String Buffer.
For your challenge you would:
a) append to a Tree Model and know the String length of each Node
b) calculate the String Position of each Node by traversing the tree up to the root

**Comment by manticore-projects** [comment]
> how can i persist the data when there is no field for it in elements?

I would implement a special TreeNode, which holds a) the Java Object itself and b) the String representation and then traverse through the tree.

**Comment by TsukimiRini** [comment]
I see...I will give it a try. Thank you very much!
