### ISSUE TITLE
How to access all the variables ?

### ISSUE THREAD

**Issue by yangyangyyy** [JSQLParser/JSqlParser#130]
I was trying to transform all the variables in a query from lower case to upper case. this includes DROP, CREATE, UPDATE, INSERT. what is the best way to visit all the variables? if I were to traverse the trees, it would be painful since Create, Update , Drop all have different classes, and there are multiple places in each where a variable would appear.

a hacky way would be modify the .jj file and I only need to stick a code in the parser for S_VARIABLE

**Comment by wumpz** [comment]
JSqlParser provides the visitor pattern to achieve this. Look at the examples. There is one, replacing all Strings within a statement. Recently some adapter classes for the visitor interfaces were introduced, to reduce the pain of implementing all this stuff.

**Comment by wumpz** [comment]
Did that help you? Could we close this issue?

**Comment by yangyangyyy** [comment]
Yes thanks!

**Comment by yangyangyyy** [comment]
actually, I just looked into the tablesNamesFinder    ,  it seems the
framework still lacks a convenient means for users to traverse one
particular type of entity:

for example if u call Select.accept(visitor), the implementation is simply
visitor.visit(this)  , the framework does not provide recursive calling of
visit() for the children entities, and it's rather cumbersome to do this on
the user, plus it's repetitive.

for example if I want to visit all the Expression's,  you have to pass a
SelectVisitor to Select.accept(), and inside the visit() def, have to code
yourself to visit all the Where, GROUPBY  with "this". this recursive
calling is an exact copy of the grammar definition, and need not be
hand-written a second time. at least this kind of traversal should be
code-generated.

the ideal scenario I want, for the above example, is that if I want to
change all the Expression's to upper case, then I just go to the CFG def
for Expression in .jj file, and modify the behavior in one place. if this
is to be done in java, I hope it can be done in just one place, without the
necessity to write the recursive calls under Select.

Thanks
Yang

**Comment by wumpz** [comment]
That is why the example I mentioned uses the deparsers, were most of the recursion is implemented. The TableNameFinder is optimized for its task and not for a complete recursion.

**Comment by yangyangyyy** [comment]
I see, I was looking at the wrong example.

then it seems that the "Deparser" name should probably be changed to
something like "traverser" to reflect their more generic purpose. also the
example given has a line
" expressionDeParser.setSelectVisitor(deparser);
"
should probably be removed. I tried commenting it out, code still works
fine. that line itself causes more confusion.

thanks
Yang

**Comment by wumpz** [comment]
Here is an example for your task. You should keep the line **expressionDeParser.setSelectVisitor(deparser)**. The SelectDeparser within the ExpressionDeParser is used for sub selects. 

But I agree with you, that this traversal is more complicated than it should be. The adapters are going in the right direction but are far from complete.

~~~java
        String sql ="SELECT ('test' + @mytext) as col1, col2 FROM mytable WHERE id = @id";
        Select select = (Select) CCJSqlParserUtil.parse(sql);
        
        //Start of value modification
        StringBuilder buffer = new StringBuilder();
        ExpressionDeParser expressionDeParser = new ExpressionDeParser() {

            @Override
            public void visit(UserVariable var) {
                var.setName(var.getName().toUpperCase());
            }
        };
        SelectDeParser deparser = new SelectDeParser(expressionDeParser,buffer );
        expressionDeParser.setSelectVisitor(deparser);
        expressionDeParser.setBuffer(buffer);
        select.getSelectBody().accept(deparser);
        //End of value modification

        System.out.println(select.toString());
        //Result is: SELECT ('test' + @MYTEXT) AS col1, col2 FROM mytable WHERE id = @ID
~~~

**Comment by yangyangyyy** [comment]
I see, thanks!
