### ISSUE TITLE
Can't parse with query inner join

### ISSUE THREAD

**Issue by longht95** [JSQLParser/JSqlParser#1302]
I have statement :
SELECT * FROM TABLE1 tb1 
	INNER JOIN TABLE2 tb2
		INNER JOIN TABLE3 tb3
			INNER JOIN TABLE4 tb4
			ON (tb3.aaa = tb4.aaa)
		ON (tb2.aaa = tb3.aaa)
	ON (tb1.aaa = tb2.aaa)

I try :
Select select = (Select) CCJSqlParserUtil.parse("SELECT * FROM TABLE1 tb1 "
				+ "INNER JOIN TABLE2 tb2 "
				+ "INNER JOIN TABLE3 tb3 "
				+ "INNER JOIN TABLE4 tb4 "
				+ "ON (tb3.aaa = tb4.aaa) "
				+ "ON (tb2.aaa = tb3.aaa) "
				+ "ON (tb1.aaa = tb2.aaa)");

**Expected behavior**
Exception in thread "main" net.sf.jsqlparser.JSQLParserException: Encountered unexpected token: "ON" "ON"
    at line 1, column 115.
**System**
 - Database you are using : Oracle
- Java Version : 1.8
- JSqlParser version : 4.1

**Comment by manticore-projects** [comment]
Greetings.

unfortunately I am not sure if your Statement is valid.
Changing it into valid syntax will work:
```sql
SELECT *
FROM table1 tb1
    INNER JOIN (TABLE2 tb2 INNER JOIN (TABLE3 tb3 INNER JOIN TABLE4 tb4 ON tb3.aaa = tb4.aaa) ON tb2.aaa = tb3.aaa)
        ON tb1.aaa = tb2.aaa
;
```

[You can test it here online and interactively](http://jsqlformatter.manticore-projects.com/jsqlformatter/demo.html?args=-c%20MoUQMiDCAqAEBUAoAYgJQPIFlYBcCGARgDYCmAjLgWYrLbAJIByjIqsAUuk7ABTQCCAIQgAmSmKYs2nbnyEQAzJSWTWHLo1gDhIACyV96TTgIKAdHkuwAvAYuWAlLCPj7eG8rcOadXy5Nkbh4mIm6IANxAA+)

**Comment by longht95** [comment]
Thanks for your support,
But this is statement is valid.
You can check it below :
[sqlstatement](http://jsqlformatter.manticore-projects.com/jsqlformatter/demo.html?args=-c%20LTAEDMEMEsBsFMAmoAuB7CaBOBbSLQBnFSLFAKAGUBRAGWoGEAVUAKnIDEAlAeQFlyTAIIAhegEZUAI1jjyoBaACSAORXUuoAFI9VoYWOoAmabCPzFl1es069B+gGZTji5YU8VoABQoZRgDoAYzRYAFccADtJAF4XYNCI6IBKN1BPHz9ZBPCokziswJDcyKNUgHUACQ1qcizxHKTY0HEjRwBuchAIGARkdExcfFB4SMQgA+)
check valid SQL oracle :
https://www.eversql.com/sql-syntax-check-validator/

Do you have an idea for this issue?
Maybe, convert the statement to JSQLParse have read it.

**Comment by manticore-projects** [comment]
JSQLParser does expect the extra-brackets around the nested joins, although this might be subject to a change/improvement because in fact the RDBMS do not expect these extra-brackets.

JSQLParser does not support your initial statement.

**Comment by manticore-projects** [comment]
according to https://docs.oracle.com/cd/E11882_01/server.112/e41084/statements_10002.htm#BABGHCBD
![image](https://user-images.githubusercontent.com/18080123/129436025-724f4515-5a23-4287-a8d7-647ada476b03.png)

my assumption on the syntax seems to be correct.

**Comment by manticore-projects** [comment]
I have just check in H2
```sql
select *
from risk.instrument a
inner join risk.instrument b
inner join risk.instrument c
on b.id_instrument=c.id_instrument
on a.id_instrument = b.id_instrument
```

It is indeed a valid statement and we will need to refactor the JOIN expressions accordingly.

**Comment by longht95** [comment]
I look forward to your updates

**Comment by longht95** [comment]
Dear @manticore-projects ,
How to get a version to have the resolver

**Comment by manticore-projects** [comment]
> How to get a version to have the resolver

Greetings, either pull from the PR (which has not been accepted yet) or use the attached **unoffical** snapshot I built for you.
[jsqlparser-4.2-SNAPSHOT_UNOFFICAL.jar.zip](https://github.com/JSQLParser/JSqlParser/files/7109458/jsqlparser-4.2-SNAPSHOT_UNOFFICAL.jar.zip)
