### ISSUE TITLE
'withSquareBracketQuotation(true)' cannot work on fields that name start with a number.

### ISSUE THREAD

**Issue by Fourcks** [JSQLParser/JSqlParser#1304]
**Describe the bug**
withSquareBracketQuotation cannot work on fields that start with a number,like [3d]/[2n]
**To Reproduce**
1. Example SQL:
the sql running with error : `SELECT [id],[2n] FROM [table]`
the sql running without error : `SELECT [id],[n2t] FROM [table]`

2. Parsing this SQL using JSqlParser with this statements:
`CCJSqlParserUtil.parse(sql,parser ->parser.withSquareBracketQuotation(true));`

3. Exception
`Exception in thread "main" net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "[" "["`
    `at line 1, column 13.`
`Was expecting:`
`    "*"`
`	at net.sf.jsqlparser.parser.CCJSqlParser.generateParseException(CCJSqlParser.java:26917)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_consume_token(CCJSqlParser.java:26753)
	at net.sf.jsqlparser.parser.CCJSqlParser.SelectItem(CCJSqlParser.java:5522)
	at net.sf.jsqlparser.parser.CCJSqlParser.SelectItemsList(CCJSqlParser.java:5388)
	at net.sf.jsqlparser.parser.CCJSqlParser.PlainSelect(CCJSqlParser.java:4737)
	at net.sf.jsqlparser.parser.CCJSqlParser.SetOperationList(CCJSqlParser.java:4960)
	at net.sf.jsqlparser.parser.CCJSqlParser.SelectBody(CCJSqlParser.java:4631)
	at net.sf.jsqlparser.parser.CCJSqlParser.Select(CCJSqlParser.java:4626)
	at net.sf.jsqlparser.parser.CCJSqlParser.SingleStatement(CCJSqlParser.java:155)
	at net.sf.jsqlparser.parser.CCJSqlParser.Statement(CCJSqlParser.java:83)
	at com.example.demo.DemoApplication.main(DemoApplication.java:24)`

**Expected behavior**
`SELECT [id],[2n] FROM [table]`  should be properly parsed
The '**at line 1, column 13**.' in the error means [2n] is not parsed properly

I also have some columns with numbers as names, like [1]/[4]/[16].
I hope they can be properly parsed.

**System**
- DB : SQL Server 2016 (SP1)
- jdk: 1.8.0_281
- JSQLParser : 4.1

- mybatis : 3.4.6
- pagehelper : 5.2.1

I don’t know why the previous designers designed the database field names like this.
This database is used by several applications,so I cant modify the filed name.

**Comment by manticore-projects** [comment]
Greetings.

Column- or Table-Names starting with a digit are not supported by JSQLParser and also valid for the most RDBMS.
Maybe you would like to send a PR.

**Comment by Fourcks** [comment]
Thank you for your reply.

For now,I don't have enough ability to send a PR to fix it or make it meet my expectations.
`SELECT "2n" FROM "table"` is worked without error.I thought I should use it.

Is it that you have no plans to support this?
Pitful sqlserver.Nobody loves.
If there are no other problems/question, this issue can be closed.

**Comment by manticore-projects** [comment]
> `SELECT "2n" FROM "table"` is worked without error.I thought I should use it.

Glad this works for you, the squared bracket quotation is quite a dirty approach to implement SQL Server compatibility. `[` `]` are used for arrays and that's where the digits become a problem.

> Is it that you have no plans to support this?

Honest answer to my best knowledge: Nobody is working on that. 

> If there are no other problems/question, this issue can be closed.

Thank you for the feedback,
