### ISSUE TITLE
ExistsExpression always return isNot = false

### ISSUE THREAD

**Issue by longht95** [JSQLParser/JSqlParser#1305]
**Describe the bug**
ExistsExpression boolean isNot always return is false

**To Reproduce**
1. Example SQL
Select
  *
FROM
  table1 tbl1
WHERE
  NOT EXISTS (
    SELECT
      *
    FROM
      table2 tbl2
    WHERE
      tbl2.col4 = tbl1.col4
  )
2. Parsing this SQL using JSqlParser with this statements
I using CCJSqlParserUtil.parse(sql),
expression.accept(new ExpressionVisitorAdapter() {
@Override
			public void visit(ExistsExpression expr) {
				// TODO Auto-generated method stub
				super.visit(expr);
				System.out.println("IS NOT OR NO:"+ expr.getStringExpression());
				System.out.println("IS NOT OR NO:"+ expr.isNot());
}
});

**Expected behavior**
boolean isNot = true when the statement is NOT EXISTS and false when EXISTS

**System**
 - Database you are using : Oracle
- Java Version : 1.8
- JSqlParser version : 4.1

**Comment by manticore-projects** [comment]
Greetings,

this is a misunderstanding on your end:
```java
    @Test
    public void isNot() throws JSQLParserException {
        String sqlStr = "SELECT * FROM foo WHERE NOT EXISTS(select 1)";

        Select select = (Select) CCJSqlParserUtil.parse(sqlStr);
        PlainSelect plainSelect = (PlainSelect) select.getSelectBody();
        NotExpression notExpression = (NotExpression) plainSelect.getWhere();

        ExistsExpression existsExpression = (ExistsExpression) notExpression.getExpression();
        assertFalse(existsExpression.isNot());
    }
```

The `NOT` is an expression on its own and for that reason the `EXISTS` expression must have `isNot==false`.
Think of it as a kind of `NOT ( EXISTS ( ...) ) `.
