### ISSUE TITLE
improving the grammar .jj file

### ISSUE THREAD

**Issue by yangyangyyy** [JSQLParser/JSqlParser#131]
I was looking at the JSqlParser.jj file  and saw that Column():  definition
repeats a lot of the definition of Table():

so I tried to change Column to the following:

    (
        [LOOKAHEAD(2) table = Table() "." ]  columnName=RelObjectName()
    )

but the generated parser fails to recognize a simple select like

SELECT  footable.foocolumn

it complains that it's expecting "." but got EOF

if I increase the LOOKAHEAD() length for Column() and Table(),    the error changed , saying that it was expecting "FROM" , "AS" ...etc       

I thought increasing LOOKAHEAD()  value should not affect the correctness of the parser as long as the value is long enough so that parser is able to make decisions between several choices? let's say  the parser absolutely needs a lookahead value of 4, setting it to 100 should not change the behavior of code, right?

**Comment by wumpz** [comment]
Withou digging to much into your problem the reasons for keeping column and table separate are: first it is a sematic desicion and second in future releases JSqlParser will allow more keywords vor column names than for tablenames. A good example here is *left* when you run into a conflict using it as a tablename
~~~
select * from left join ..
~~~
