### ISSUE TITLE
UPDATE does not work with Complex Expression Lists

### ISSUE THREAD

**Issue by manticore-projects** [JSQLParser/JSqlParser#1316]
Details as below, all these samples work on H2 and I will look into it.

```sql
CREATE TABLE test (
    a        VARCHAR (1)
    , b      VARCHAR (1)
)
;
-- queries are supported
update test
set (a, b) = (select '1', '2');

-- value lists are not supported
update test
set (a, b) = values( '1', '2');

-- simple expression lists are not supported
update test
set (a, b) = ('1', '2');

-- complex expression lists are not supported
update test
set (a, b) = (1, (select 2));
```

_Originally posted by @manticore-projects in https://github.com/JSQLParser/JSqlParser/discussions/1313#discussioncomment-1242208_

**Comment by manticore-projects** [comment]
Re-opened when "big boy" updates are not parsed correctly:
```sql

-- UPDATE SETS ISSUE 1316
UPDATE prpjpaymentbill b
SET (   b.packagecode
        , b.packageremark
        , b.agentcode ) =   (   SELECT  p.payrefreason
                                        , p.classcode
                                        , p.riskcode
                                FROM prpjcommbill p
                                WHERE p.policertiid = 'SDDH200937010330006366' ) -- this is supposed to be UpdateSet 1
     , b.payrefnotype = '05' -- this is supposed to be UpdateSet 2
     , b.packageunit = '4101170402' -- this is supposed to be UpdateSet 3
WHERE b.payrefno = 'B370202091026000005'
;
```

The example above is getting parsed and de-parsed, but incorrectly: we will end up with one `UpdateSet` holding 3 `Expressions` instead of 3 `UpdateSets` holding one `Expression` each.

**Comment by wumpz** [comment]
I am ready to release JSqlParser 4.2. There is a project where I want to collect all remaining issues for this release.

**Comment by manticore-projects** [comment]
Fun fact: I was contemplating since Friday how I could convince you to release 4.2 -- fire at will please!

**Comment by wumpz** [comment]
I will reevaluate those remaining issues within my release project. I think I could close those without any implementation since their age.

**Comment by manticore-projects** [comment]
> I will fix this particular issue before your wake up tomorrow.

Delivered as promised although this was a nasty one.
