### ISSUE TITLE
Validation of statement of adding a foreign key fails with ParseException: Cannot parse statement: Encountered unexpected token: "." "."

### ISSUE THREAD

**Issue by AmitAmely** [JSQLParser/JSqlParser#1321]
My Code:
```
	@Test
	public void testJSQLParserValidation()
	{
		String sql = "ALTER TABLE someschema.table2 ADD FOREIGN KEY (table1_pk) REFERENCES someschema.table1 (pk);";
		Validation validation = new Validation(List.of(DatabaseType.POSTGRESQL), sql);
		List<ValidationError> errors = validation.validate();
		Assert.assertTrue( errors.toString(), errors.isEmpty());

	}
```

Result:

```
java.lang.AssertionError: [ValidationError [
statement=ALTER TABLE someschema.table2 ADD FOREIGN KEY (table1_pk) REFERENCES someschema.table1 (pk);
capability=parsing
errors=[ParseException: Cannot parse statement: Encountered unexpected token: "." "."
    at line 1, column 80.

Was expecting one of:

    "("
    ","
    ";"
    <EOF>
]
]]
```

Same for Oracle. This statement can be executed successfully on both.

**Comment by manticore-projects** [comment]
Greetings.

Please double check which version of JSQLParser you are using.
JSQLParser 4.1 parses your statement without any problems and you can [test it online here](http://jsqlformatter.manticore-projects.com/jsqlformatter/demo.html?args=-c%20IIGQKgogSgBGwCEQRgZwPYFsCmqDGAFtpgIYB0ALiQEYA22ATAFAyszAAiHMAYgPJQIASQDiAORgBpCAE0YACip1sARgD6ABwDWAShZsDgntAhiAwhADKMJfRULtegNxA+)

Please close the case after confirmation.

**Comment by AmitAmely** [comment]
Indeed, I used v4.0 and now after upgrading it works
