### ISSUE TITLE
Validation of a statement for renaming a table fails with ParseException: Cannot parse statement: Encountered unexpected token: "to" "TO"

### ISSUE THREAD

**Issue by AmitAmely** [JSQLParser/JSqlParser#1323]
My code:
```
	@Test
	public void testJSQParser()
	{
		String sql = "alter table public.table2 rename to table3;";
		Validation validation = new Validation(List.of(DatabaseType.POSTGRESQL), sql);
		List<ValidationError> errors = validation.validate();
		Assert.assertTrue(errors.toString(), errors.isEmpty());
	}
```
Result:
```
java.lang.AssertionError: [ValidationError [
statement=alter table public.table2 rename to table3;
capability=parsing
errors=[ParseException: Cannot parse statement: Encountered unexpected token: "to" "TO"
    at line 1, column 34.

Was expecting:

    "COLUMN"
]
]]
```
Same with Oracle. This statement can be executed in both.

**Comment by manticore-projects** [comment]
```sql
alter table public.table2 rename to table3;
```

is supported with recent JSQLParser 4.2-Snapshot, which you would need to fetch/compile from GIT please.

**Comment by AmitAmely** [comment]
Fetched and compiled JSQLParser 4.2-Snapshot, still seeing the same error.

**Comment by AmitAmely** [comment]
@manticore-projects Your fix is wrong. E.G. this test passes:
```
  @Test
  public void testValidator() throws JSQLParserException {
    String sqlStr = "RENAME oldTableName TO newTableName";

    ValidationTestAsserts.validateNoErrors(sqlStr, 1, DatabaseType.ORACLE);
  }
```
  However, if you execute this expression on a real Oracle DB you get this:
`  SQL Error [3001] [0A000]: ORA-03001: unimplemented feature`

In both Oracle and PostgreSQL, table renaming is an alter expression.

**Comment by manticore-projects** [comment]
Greetings.

Kudos for digging into the sources and  finding the test.
However:

1) your ticket was explicitly about parsing the `RENAME oldName TO newName` statement, which works and succeeds
2) regarding the Validator, this statement is Oracle compliant but you will need to ask other developers regarding the implementation details, especially when this test was supposed to fail with other RDBMS. I do not use the Validator myself. PRs are welcome.

> In both **Oracle** and PostgreSQL, table renaming is an alter expression.

I do not think so: https://docs.oracle.com/cd/B19306_01/server.102/b14200/statements_9019.htm
![image](https://user-images.githubusercontent.com/18080123/131591345-bad8f789-c1b2-4ad0-9cbe-a41a8a28baa0.png)
