### ISSUE TITLE
MySQL parse failure with query hints

### ISSUE THREAD

**Issue by priyankvashist** [JSQLParser/JSqlParser#1325]
I am getting error while parsing the MySQL with query hints:

SQL: `SELECT col FROM table USE INDEX(primary)`

Error while parsing:
`Exception in thread "main" net.sf.jsqlparser.JSQLParserException: Encountered unexpected token: "primary" "PRIMARY"
    at line 1, column 33.

Was expecting one of:

    <S_IDENTIFIER>
    <S_QUOTED_IDENTIFIER>

	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parseAST(CCJSqlParserUtil.java:84)
	at ParserDemo.main(ParserDemo.java:75)
Caused by: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "primary" "PRIMARY"
    at line 1, column 33.`

Changing primary to another string like primary1 works.

**Comment by manticore-projects** [comment]
Greetings,

`primary` is a reserved keyword and you will need to quote it when using as name:
```sql
SELECT col FROM table USE INDEX("primary");
```

Please close this issue after verification.

**Comment by wumpz** [comment]
I was not aware, that MySql is using the same syntax like Microsoft SqlParser. So happy, that this works here too. 
The keyword could be included in the allowed keywords for object names list (RelObjectNames production).

**Comment by manticore-projects** [comment]
> The keyword could be included in the allowed keywords for object names list (RelObjectNames production).

It is already, please refer to line 1609 of the recent Grammar.

**Comment by priyankvashist** [comment]
Thanks for the reply! It works with quoted string.

This will require me to change the input sql which I was trying to avoid.
Is it fine to make following change in grammar since its only called in MySQL query hint method: 
`String Identifier():
{
	Token tk = null;
}
{
	(tk=<S_IDENTIFIER>
    | tk=<S_QUOTED_IDENTIFIER>
    | tk=<K_PRIMARY>)
    { return tk.image; }
}`

**Comment by manticore-projects** [comment]
> Is it fine to make following change in grammar since its only called in MySQL query hint method:

It appears to me that the production `Identifier()` is redundant and `RelObjectnameWithoutValue()` should be used instead (which also defines a lot of keywords allowed for Object Names).
