### ISSUE TITLE
distinct onSelectItems is null

### ISSUE THREAD

**Issue by wuguowei19880907** [JSQLParser/JSqlParser#1328]
jsqlparser 3.2 + java 8 + oracle

My sql text is 'SELECT distinct(phone),name FROM admin_user'. 
I want to know the distinct columns,but I get null when i use 'distinct.getOnSelectItems()'
![image](https://user-images.githubusercontent.com/19338820/132200247-79d5de89-c72b-4bd3-ac80-561b7b82150a.png)

I also test the sql 'SELECT distinct phone,name FROM admin_user', and it is null too!

**Comment by wumpz** [comment]
Those `onSelectItems` are set if you are using the `distinct on` syntax. For your case `(phone)` this is only a column name in parenthesis after the `distinct` keyword. So your statement should be:

```sql
SELECT distinct on (phone) phone, name FROM admin_user
```

**Comment by wuguowei19880907** [comment]
> Those `onSelectItems` are set if you are using the `distinct on` syntax. For your case `(phone)` this is only a column name in parenthesis after the `distinct` keyword. So your statement should be:
> 
> ```sql
> SELECT distinct on (phone) phone, name FROM admin_user
> ```

In oracle `distinct on` is not a correct syntax. 
I just want to know `which columns is distinct`

**Comment by manticore-projects** [comment]
> In oracle `distinct on` is not a correct syntax.

In your original request you use `distinct(phone)` which is not Oracle **officially** compliant either:
![image](https://user-images.githubusercontent.com/18080123/132292854-a3c55931-84bd-4ba1-aec3-0beb7631ab32.png)
Your can find further discussion here: https://community.oracle.com/tech/developers/discussion/2323735/distinct-function-as-in-select-distinct-column

In Oracle this  `distinct(phone)` will be silently translated into:
```sql
SELECT DISTINCT phone, name FROM admin_user;
```

Now, regarding to JSQLParser `Distinct(column)` is **any** `FUNCTION` while `DISTINCT column` is a property of the `PlainSelect`.

> I just want to know `which columns is distinct`

When using `DISTINCT` correctly, all columns are distinct.

**Comment by manticore-projects** [comment]
@wumpz: Should we not discourage such keywords to be used/parsed as Function Names?

**Comment by wumpz** [comment]
The problem here is that we have to a certain degree to the SQLs out there. Since distinct could be a column name it will be used from somebody. I would keep it.

**Comment by manticore-projects** [comment]
> The problem here is that we have to a certain degree to the SQLs out there. Since distinct could be a column name it will be used from somebody. I would keep it.

I fully understand your point. Problem is: in my opinion the reported issue has some merit. The actual SQL is: `SELECT DISTINCT (column) FROM table` and `DISTINCT` is not a function. It works on Oracle and H2.

How do we teach JSQLParser to read '<K_DISTINCT> BracketExpression( column ) ' instead of 'Function( column )' when we do not block such identifiers for Function Names at least (while allowing it for columns).

**Comment by wumpz** [comment]
@manticore-projects Your assumption is wrong. `distinct (phone)` in this context is not parsed as a function with parameter `phone` but like we expect it as a `distinct` flag for the select statement and `(phone)` is a *PrimaryExpression*. So JSqlParser was already taught to do so. 

As I said. I would keep it.

```
Call:	Statement
  Call:	SingleStatement
    Call:	Select
      Call:	SelectBody
        Call:	SetOperationList
          Call:	PlainSelect
            Consumed token: <<K_SELECT>: "SELECT" at line 1 column 1>
            Call:	getOracleHint
            Return: getOracleHint
            Consumed token: <"DISTINCT" at line 1 column 8>
            Call:	SelectItemsList
              Call:	SelectItem
                Call:	SelectExpressionItem
                  Call:	Condition
                    Call:	SQLCondition
                      Call:	SimpleExpression
                        Call:	ConcatExpression
                          Call:	BitwiseAndOr
                            Call:	AdditiveExpression
                              Call:	MultiplicativeExpression
                                Call:	BitwiseXor
                                  Call:	PrimaryExpression
                                    Consumed token: <"(" at line 1 column 17>
                                    Call:	ComplexExpressionList
                                      Call:	Expression
                                        Call:	XorExpression
                                          Call:	OrExpression
                                            Call:	AndExpression
                                              Call:	Condition
                                                Call:	SQLCondition
                                                  Call:	SimpleExpression
                                                    Call:	ConcatExpression
                                                      Call:	BitwiseAndOr
                                                        Call:	AdditiveExpression
                                                          Call:	MultiplicativeExpression
                                                            Call:	BitwiseXor
                                                              Call:	PrimaryExpression
                                                                Call:	Column
                                                                  Call:	RelObjectNameList
                                                                    Call:	RelObjectNameExt
                                                                      Call:	RelObjectName
                                                                        Call:	RelObjectNameWithoutValue
                                                                          Consumed token: <<S_IDENTIFIER>: "phone" at line 1 column 18>
                                                                        Return: RelObjectNameWithoutValue
                                                                      Return: RelObjectName
                                                                    Return: RelObjectNameExt
                                                                  Return: RelObjectNameList
                                                                Return: Column
```

@wuguowei19880907 So like @manticore-projects already mentioned, all selected expressions will be the distinct columns or expressions. So you will get it like:

```java
final Select select = (Select) parserManager.parse(new StringReader(statement));
final PlainSelect selectBody = (PlainSelect) select.getSelectBody();
final List<SelectItem> selectItems = selectBody.getSelectItems();
```

The `selectItems` are distinct.

**Comment by manticore-projects** [comment]
> @manticore-projects Your assumption is wrong. `distinct (phone)` in this context is not parsed as a function with parameter `phone` but like we expect it as a `distinct` flag for the select statement and `(phone)` is a _PrimaryExpression_.

I stand corrected and I am sorry. I should have tested it properly instead assuming.
Thank you for the clarification.

**Comment by wumpz** [comment]
No problem here. I am right now introducing a test that ensures exactly this behavior.

**Comment by wumpz** [comment]
@wuguowei19880907 So can we close this one, since it seems to be a misunderstanding of how JSqlParser works on your statement.
