### ISSUE TITLE
release version 4.2 of JSqlParser

### ISSUE THREAD

**Issue by wumpz** [JSQLParser/JSqlParser#1331]
@manticore-projects please could you check the readme.md file under **Extensions in the latest SNAPSHOT version 4.2**, if all of your changes, and there were a lot, are already included here? From this part I generate usually the release changelog.

**Comment by wumpz** [comment]
JSqlParser 4.2-SNAPSHOT deployed

**Comment by manticore-projects** [comment]
Yes, I did that already in the "Prepare 4.2" PR. Although I added only enhancements, not fixes.

**Comment by wumpz** [comment]
That's ok. So I will release in the next couple of hours.

**Comment by wumpz** [comment]
Released. It will take some time until the new version is published to maven central.

**Comment by manticore-projects** [comment]
Massive job, well done! Cheers.
