### ISSUE TITLE
JSqlParser 4.2 SQLServer无法使用 [表名]，在1.0版本中可以

### ISSUE THREAD

**Issue by qpxiwo1937** [JSQLParser/JSqlParser#1332]
net.sf.jsqlparser.JSQLParserException: Encountered unexpected token: "." "."
    at line 1, column 120.

Was expecting one of:

    ";"
    "ACTION"
    "ACTIVE"
    "ALGORITHM"
    "ARCHIVE"
    "ARRAY"
    "AS"
    "BYTE"
    "CASCADE"
    "CASE"
    "CAST"
    "CHANGE"
    "CHAR"
    "CHARACTER"
    "CHECKPOINT"
    "COLUMN"
    "COLUMNS"
    "COMMENT"
    "COMMIT"
    "CONNECT"
    "COSTS"
    "CYCLE"
    "DBA_RECYCLEBIN"
    "DESC"
    "DESCRIBE"
    "DISABLE"
    "DISCONNECT"
    "DIV"
    "DO"
    "DUMP"
    "DUPLICATE"
    "ENABLE"
    "END"
    "EXCLUDE"
    "EXTRACT"
    "FALSE"
    "FILTER"
    "FIRST"
    "FLUSH"
    "FN"
    "FOLLOWING"
    "FOR"
    "FORMAT"
    "GROUP"
    "HAVING"
    "HISTORY"
    "INDEX"
    "INSERT"
    "INTERVAL"
    "ISNULL"
    "JSON"
    "KEY"
    "LAST"
    "LEADING"
    "LINK"
    "LOCAL"
    "LOG"
    "MATERIALIZED"
    "NO"
    "NOLOCK"
    "NULLS"
    "OF"
    "OPEN"
    "OVER"
    "PARALLEL"
    "PARTITION"
    "PATH"
    "PERCENT"
    "PIVOT"
    "PRECISION"
    "PRIMARY"
    "PRIOR"
    "QUIESCE"
    "RANGE"
    "READ"
    "RECYCLEBIN"
    "REGISTER"
    "REPLACE"
    "RESTRICTED"
    "RESUME"
    "ROW"
    "ROWS"
    "SCHEMA"
    "SEPARATOR"
    "SEQUENCE"
    "SESSION"
    "SHUTDOWN"
    "SIBLINGS"
    "SIGNED"
    "SIZE"
    "SKIP"
    "START"
    "SUSPEND"
    "SWITCH"
    "SYNONYM"
    "TABLE"
    "TEMP"
    "TEMPORARY"
    "TIMEOUT"
    "TO"
    "TOP"
    "TRUE"
    "TRUNCATE"
    "TYPE"
    "UNQIESCE"
    "UNSIGNED"
    "USER"
    "VALIDATE"
    "VALUE"
    "VALUES"
    "VIEW"
    "WINDOW"
    "XML"
    "ZONE"
    <EOF>
    <K_DATETIMELITERAL>
    <K_DATE_LITERAL>
    <K_NEXTVAL>
    <K_STRING_FUNCTION_NAME>
    <S_CHAR_LITERAL>
    <S_IDENTIFIER>
    <S_QUOTED_IDENTIFIER>

	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parseStatement(CCJSqlParserUtil.java:190)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:63)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:38)
	at com.clinbrain.dip.sqlparse.CCJHandlerSqlParse.parseSql(CCJHandlerSqlParse.java:29)
	at com.clinbrain.dip.util.SqlParseUtil.parseSql(SqlParseUtil.java:30)
	at com.clinbrain.dip.util.SqlParseUtil.main(SqlParseUtil.java:51)

**Comment by manticore-projects** [comment]
Greetings,

please post the query. Only then we can try to help you.

**Comment by qpxiwo1937** [comment]
> 你好，
> 
> 请发布查询。只有这样，我们才能尽力帮助您。

是 post请求
![414EEF06-0D9F-4cde-8604-89A405122E81](https://user-images.githubusercontent.com/38752256/132669067-5c00ad22-b58e-4295-84f8-95532f3a7e7f.png)

**Comment by manticore-projects** [comment]
If you want me to test your query, then please post it as plain text.
In the meantime, please activate `Squared Bracket Quotation`:
```java
CCJSqlParserUtil.parse("select * from mytable", parser -> parser.withSquareBracketQuotation(true));
```

**Comment by qpxiwo1937** [comment]
可以了，之前用的 CCJSqlParserUtil.parse(sql)；Think you!

**Comment by manticore-projects** [comment]
I assume, this has resolved the issue.
