### ISSUE TITLE
No support for alter expressions of renaming tables

### ISSUE THREAD

**Issue by AmitAmely** [JSQLParser/JSqlParser#1333]
In PostgreSQL, the only supported table renaming syntax is:
ALTER TABLE  [IF EXISTS] [<schema_name>.]<old_table_name> RENAME TO <new_table_name>

Same for Oracle, when renaming tables across schemas, excluding the IF EXISTS option.

When trying to validate such expression, you get the error detailed in #1323

**Comment by manticore-projects** [comment]
Greetings.

Unfortunately I am not sure what to make out of your report because the following test succeeds:
```java
  @Test
  public void testValidator() throws JSQLParserException {
    String sqlStr = "RENAME oldTableName TO newTableName";
    TestUtils.assertSqlCanBeParsedAndDeparsed(sqlStr, true);

      // this needs to succeed
      ValidationTestAsserts.validateNoErrors(sqlStr, 1, DatabaseType.ORACLE);

      // this should fail when not supported in Postgres
      ValidationTestAsserts.validateNoErrors(sqlStr, 1, DatabaseType.POSTGRESQL);

      sqlStr = "ALTER TABLE public.oldTableName TO newTableName";
      TestUtils.assertSqlCanBeParsedAndDeparsed(sqlStr, true);

      //  should fail when not supported in Oracle
      ValidationTestAsserts.validateNoErrors(sqlStr, 1, DatabaseType.ORACLE);

      // this needs to succeed
      ValidationTestAsserts.validateNoErrors(sqlStr, 1, DatabaseType.POSTGRESQL);
  }
```

Although we agree that the Validition is incomplete because it should fail on Oracle for the `ALTER TABLE ... RENAME TO ...` and for Postgres on the `RENAME ... TO ...`.
We have explained before they you are invited to amend the Validation Rules.

Please elaborate your expectations.

**Comment by manticore-projects** [comment]
I think I get it now.
The challenge was, that `ALTER TABLE ... RENAME TO ...` was not supported (with emphasize on `RENAME`). I have fixed that. Thank you for reporting.

**Comment by AmitAmely** [comment]
The fix covers the `RENAME TO <new_table_name>` but not the `ALTER TABLE **IF EXISTS**`

**Comment by manticore-projects** [comment]
> The fix covers the `RENAME TO <new_table_name>` but not the `ALTER TABLE` **`IF EXISTS`**

Point taken, I will add that. Thanks for feeding back.

**Comment by manticore-projects** [comment]
I have added the `IF EXISTS` clause.

**Comment by AmitAmely** [comment]
So where is the missing validation code? the Version + Feature classes?

**Comment by manticore-projects** [comment]
Unfortunately I do not know this myself.
@gitmotte  has implemented that, maybe he can help.

**Comment by gitmotte** [comment]
> So where is the missing validation code? the Version + Feature classes and the AlterValidator?

Correct. All validators derive from AbstractValidator, there you can find the methods
* validateFeature
* validateFeatureAndName
* ...
