### ISSUE TITLE
support for @@ json function from posgres

### ISSUE THREAD

**Issue by xiaoyunwu** [JSQLParser/JSqlParser#1337]
It seems that the following json function is not supported:
SELECT jdoc->'guid', jdoc->'name' FROM api WHERE jdoc @@ '$.tags[*] == "qui"';
SELECT jdoc->'guid', jdoc->'name' FROM api WHERE jdoc @> '{"company": "Magnafone"}';

Json is an important data type, the support for these will be useful.

**Comment by wumpz** [comment]
What version of JSqlParser do you use? I was able to parse your statements without any problems.

So do you get another exception?

**Comment by manticore-projects** [comment]
You can also [test it online here against latest JSQLParser](http://jsqlformatter.manticore-projects.com/jsqlformatter/demo.html?args=-c%20MoUQMiDCAqAEsCsAmB7AxgWgHwHIDmArgJZI4BQ8llANIqprgHYCGAtgKbkBiASgPIBZWMwAORMgHUAEiB4g66WAAElsHABIAdABdmeAM4BtAFQBdWAF4LsAEQBHYjfIBuMm9AQY8ZOmz5ipBRUNAoMOCwc3PxCouLSsvI+aMpYagDeNmgorCLMjACeNgBctgJ6LABmKIzsNgC+LkA+)

Seems to work fine.
