### ISSUE TITLE
 [column] can be used in 【alter&changed column】

### ISSUE THREAD

**Issue by coderstory** [JSQLParser/JSqlParser#1343]
look this sql , ```COLUMN``` has an ```CHANGE``` in front of it
CHANGE can use key word COLUMN
generate by navicat

>ALTER TABLE `rcp_dev_application`.`qweqwe` 
>CHANGE **COLUMN** `wqewqe` `wqewqeqww` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci >NULL DEFAULT NULL AFTER `id`
> OK
> times: 0.014s
![4@W@2EC@JBQP2M8{J I0VC0](https://user-images.githubusercontent.com/11525359/134328991-53f77ad3-6eef-42dc-a684-9a82e389a0c1.png)

but in jsqlparse 

can not generate this key word

![QQ截图20210922183847](https://user-images.githubusercontent.com/11525359/134329257-93d5e538-cd12-4a9a-9efa-b2d6aabbecbf.png)

**Comment by manticore-projects** [comment]
Your example parses completely fine with JSQLParser 4.2 and your can [test it here online and interactivaly](http://jsqlformatter.manticore-projects.com/jsqlformatter/demo.html?args=-c%20IIGQKgogSgBGwCEQRgJwMYAcD6ATApgG7YCGmmANgJbokAuVA9gHYB0AjgO75f4BQMQTADCACWAA5AOIphAeRABVALISYndvg351m7V04wAasChjTMABQAmAKy2AlCPFRgwyLADKEMDEVgAMQAOZQQAFhEFEGBIP0CQ8OwABgBOJKTsYABJbGEsmAlFEBAYABEIAOAi30LimGAAjxgs0r4AbiA+)

**Comment by coderstory** [comment]
> Your example parses completely fine with JSQLParser 4.2 and your can [test it here online and interactivaly](http://jsqlformatter.manticore-projects.com/jsqlformatter/demo.html?args=-c%20IIGQKgogSgBGwCEQRgJwMYAcD6ATApgG7YCGmmANgJbokAuVA9gHYB0AjgO75f4BQMQTADCACWAA5AOIphAeRABVALISYndvg351m7V04wAasChjTMABQAmAKy2AlCPFRgwyLADKEMDEVgAMQAOZQQAFhEFEGBIP0CQ8OwABgBOJKTsYABJbGEsmAlFEBAYABEIAOAi30LimGAAjxgs0r4AbiA+)

i want to add key word **column** to this sql 
i set **AlterExpression.hasColumn(true)** but not take effect
so  i **AlterExpression.setOptionalSpecifier("COLUMN")**;
**hasColumn** not effective in changed mode

-----

i want to new a SQL and not parse a sql str ,
example  
Alter alter = new Alter();
