### ISSUE TITLE
implicit cast to "double precision" is not supported

### ISSUE THREAD

**Issue by sixinli** [JSQLParser/JSqlParser#1344]
**Describe the bug**

**To Reproduce**
1. `SELECT double precision '1'`
2. Parsing this SQL using JSqlParser with this statements
3. `org.junit.ComparisonFailure: Expected query to parse but it failed to parse (error: Encountered unexpected token: "\'1\'" <S_CHAR_LITERAL>`

**Expected behavior**
query to parse

**System**
 - postgres
- 15
- 4.1

**Comment by manticore-projects** [comment]
This kind of implicit cast is not supported (yet).
Please consider to use a Standard Compliant explicit cast:
```sql
SELECT cast( '1' AS DOUBLE)
```

**Comment by manticore-projects** [comment]
This also seems to work:
```SQL
SELECT '1'::Double
;
```

**Comment by wumpz** [comment]
**double precision** is definitly supported 

```sql
select 1::double precision
```

however, this syntax `double precision '1' `is not.

**Comment by manticore-projects** [comment]
I am closing this since it is not support and won't be supported (unless any genius provided a PR).
