### ISSUE TITLE
can't parse empty select

### ISSUE THREAD

**Issue by sixinli** [JSQLParser/JSqlParser#1345]
**Describe the bug**

**To Reproduce**
1. `select;`
2. Parsing this SQL using JSqlParser with this statements
3. `org.junit.ComparisonFailure: Expected query to parse but it failed to parse (error: Encountered unexpected token:<EOF> at line 1, column 6.`

**Expected behavior**
query to parse

**System**
 - postgres
- 15
- 4.1

**Comment by manticore-projects** [comment]
`Select` will need a body at least. EBNF is:
```
Select   ::= SelectBody
```

I am not going to change that.
