### ISSUE TITLE
count(table.*) not parsing

### ISSUE THREAD

**Issue by sixinli** [JSQLParser/JSqlParser#1346]
**Describe the bug**

**To Reproduce**
1. `SELECT COUNT(myTable.*) FROM myTable`
2. Parsing this SQL using JSqlParser with this statements
3. Exception
`org.junit.ComparisonFailure: Expected query to parse but it failed to parse (error: Encountered unexpected token: "(" "("`

**Expected behavior**
query to parse

**System**
- postgres
- 15
- 4.1

**Comment by manticore-projects** [comment]
Confirmed, I will have to fix that.
