### ISSUE TITLE
No support <=> of mysql!

### ISSUE THREAD

**Issue by x-chuiao** [JSQLParser/JSqlParser#1347]
**Describe the bug**
if condition has any '<=>' operator in mysql,it will throw 'net.sf.jsqlparser.JSQLParserException: Encountered unexpected token'  with '"<=" <OP_MINORTHANEQUALS>' or ' "(" "(" ' exception for  what surround it.

**To Reproduce**
code:
```java
        String sql = "";
        try {
            Statement parse = CCJSqlParserUtil.parse(sql);
            Select parse1 = (Select) parse;
            SelectBody selectBody = parse1.getSelectBody();
            System.out.println(selectBody);
        } catch (JSQLParserException e) {
            e.printStackTrace();
        }
```

case 1:    SELECT col from table WHERE col <=> 2
it throws net.sf.jsqlparser.JSQLParserException: Encountered unexpected token: "<=" <OP_MINORTHANEQUALS>

case 2:    SELECT IFNULL((select col from table WHERE col <=> 2),0)
it throws  net.sf.jsqlparser.JSQLParserException: Encountered unexpected token: "(" "("

**Expected behavior**
support this operator,it's a usual and simple operator,thanks!

**System**
- mysql 5.7
- jdk 1.8
- JSqlParser 1.2 and 4.2

**Comment by manticore-projects** [comment]
Greetings.

MySQL specific "NULLSAFE EQUALS" Operator has not been implemented yet, but your PR would be most welcome and I stand ready to assist you when contributing.

**Comment by x-chuiao** [comment]
well,Thanks!
