### ISSUE TITLE
Split and analyze multiple SQL

### ISSUE THREAD

**Issue by It-xiaoni** [JSQLParser/JSqlParser#1366]
I now have a scenario that is the online management of SQL scripts. I need to parse all SQL of a file string into a list for item by item parsing. Now I haven't found a useful method. Do you support it? Or can I use ";" as the end of a single SQL? Hope to get some support.

**Comment by manticore-projects** [comment]
Greetings.

`net.sf.jsqlparser.parser.CCJSqlParserUtil#parseStatements(java.lang.String)` is your friend:

```java
/**
     * Parse a statement list.
     *
     * @return the statements parsed
     */
    public static Statements parseStatements(String sqls) throws JSQLParserException {
        boolean allowComplexParsing = getNestingDepth(sqls)<=ALLOWED_NESTING_DEPTH;
        
        CCJSqlParser parser = newParser(sqls).withAllowComplexParsing(allowComplexParsing);
        return parseStatements(parser);
    }
```
