### ISSUE TITLE
use interface in ColumnDefinition

### ISSUE THREAD

**Issue by sixinli** [JSQLParser/JSqlParser#1367]
it seems like since https://github.com/JSQLParser/JSqlParser/pull/1274/files#diff-7a533138e54adbf0baac5356d4b7d4a6d192300199ef50eede004f706fd35de3R104 `ColumnDefinition` accepts `ExpressionVisitorAdapter`
https://github.com/JSQLParser/JSqlParser/blob/c89cf21641d672b1ea5e724b3c6f3497429ce97a/src/main/java/net/sf/jsqlparser/statement/create/table/ColumnDefinition.java#L104-L106

is it possible to have it take one of the interfaces instead? 

(just noticed also, they seem to be referencing each other, `ExpressionVisitorAdapter#visit` calls `ColumnDefinition#accept`)

**Comment by manticore-projects** [comment]
Greetings,

this seems to have been cleaned up with revision commit c89cf21641d672b1ea5e724b3c6f3497429ce97a in 2021 already. I am closing this.
