### ISSUE TITLE
Unable to parse Postgres query with json_object function

### ISSUE THREAD

**Issue by SerialVelocity** [JSQLParser/JSqlParser#1371]
**Describe the bug**
Since 4.2, queries fail to parse that use the built-in Postgres functions. Looks like this was caused by #1263.

**To Reproduce**
1. Example SQL
```
SELECT json_object('{a, 1, b, 2}');
SELECT json_object('{{a, 1}, {b, 2}}');
SELECT json_object('{a, b}', '{1,2 }');

SELECT * FROM json_object('{a, 1, b, 2}');
SELECT * FROM json_object('{{a, 1}, {b, 2}}');
SELECT * FROM json_object('{a, b}', '{1,2 }');
```
2. Parsing this SQL using JSqlParser with these statements
3. Exception
```
Encountered unexpected token: "json_object" "JSON_OBJECT"
```

**Expected behavior**
The queries to parse as a function. This is a new bug as it used to work in 4.1

**System**
- Database you are using Postgres
- Java Version 11
- JSqlParser version 4.1 / 4.2

**Comment by SerialVelocity** [comment]
Yeah, implementing the SQL:2016 standard is good. It's just a shame backwards compatibility for existing functions was removed though when implementing it (especially since only Oracle supports the syntax so far afaik, and has been a built-in function in Postgres since way before that standard even existed).

**Comment by manticore-projects** [comment]
Ben,

nobody has removed anything. Before it has been incidentally "working" simply due to the fact that the function has not been parsed at all. Since we added the SQL:2016 standard compliant function and parse it, the Postgresql specific functions fails.

Since I have a lots of sympathy for PostgreSQL in general, lets work together on implementing a PostgreSQL specific exception here.

**Comment by manticore-projects** [comment]
Greetings.

No, worries, we are good.

On your first concern "Customized Parser for each RDBMS": I am working on a template based proto type.

On the "Prostgres compliant JSON_OBJECT function": I will try to implement this change next week and would return to you for testing when ready. As I said before: I definitely would like to achieve PostgreSQL support and compliance (although I never had the chance to use PostgreSQL as all our clients insist in Oracle).
