### ISSUE TITLE
$$text with space$$ inside function doesnt work

### ISSUE THREAD

**Issue by sixinli** [JSQLParser/JSqlParser#1372]
**To Reproduce**
1. `SELECT UPPER($$some text$$)`
2. Parsing this SQL using JSqlParser with this statements
3. 
```
org.junit.ComparisonFailure: Expected query to parse but it failed to parse (error: Encountered unexpected token: "(" "("
    at line 1, column 13.
```

**Expected behavior**
query to parse

**System**
 - postgres
- Java11
- JSqlParser 4.1

**Comment by manticore-projects** [comment]
`$$` for quoting is not supported. Only `'` are valid String Value Quotes.
You would need to mangle your SQL before sending in the JSQLParser to make `$$` that work.

**Comment by sixinli** [comment]
will it be supported in the future? its a frequently used postgres syntax to avoid escaping quotes
