### ISSUE TITLE
Expressions aren't parsed properly inside CASE clause

### ISSUE THREAD

**Issue by SerialVelocity** [JSQLParser/JSqlParser#1375]
**Describe the bug**
Expressions aren't parsed properly inside `CASE` clause

**To Reproduce**
Steps to reproduce the behaviour:
1. Example SQL
```
SELECT * FROM t1 WHERE CASE WHEN 1 = 1 THEN c1 = 'a' ELSE c2 = 'b' AND c4 = 'd' END;
```
2. Parsing this SQL using JSqlParser with this statements
3. Exception
```
Encountered unexpected token: "AND" "AND"
(line 1 column 68)
```
It's the `AND c4 = 'd'`

**Expected behaviour**
For the query to be parsed correctly

**System**
- Database you are using Postgresql
- Java Version 11
- JSqlParser version 4.2

**Comment by wumpz** [comment]
There are only simple expressions allowed here (at the moment).

**Comment by wumpz** [comment]
However, its a just question or issue. Since it is a possibility to compress the expression to calculate complex boolean expressions, it makes sense.

**Comment by SerialVelocity** [comment]
Thanks for fixing this! Sorry for the late reply, it was an issue we have since we parse user queries and transitioning over to using this library to parse the queries means we need to try and get existing queries to work.

**Comment by manticore-projects** [comment]
No big deal, whatever query fails parsing, please just keep sending for assessment.
