### ISSUE TITLE
limit / offset should auto try cast to int

### ISSUE THREAD

**Issue by sixinli** [JSQLParser/JSqlParser#1376]
**Describe the bug**

**To Reproduce**
1. `select 1 offset '0'`
2. Parsing this SQL using JSqlParser with this statements
3. Exception
```
org.junit.ComparisonFailure: Expected query to parse but it failed to parse (error: Encountered unexpected token: "\'0\'" <S_CHAR_LITERAL>
    at line 1, column 19.
```

**Expected behavior**
query to parse fine

**System**
 - postgres
- Java 11
- JSqlParser 4.2

**Comment by wumpz** [comment]
Character literals are not allowed as parameter there. Using an integer should do fine.

**Comment by manticore-projects** [comment]
Duplicate of #933
