### ISSUE TITLE
Support row constructors and row comparison with relational comparison operators

### ISSUE THREAD

**Issue by tejksat** [JSQLParser/JSqlParser#138]
#### Row constructors
http://docs.oracle.com/cd/E17952_01/refman-5.0-en/row-subqueries.html states:
> The expressions (1,2) and ROW(1,2) are sometimes called row constructors. The two are equivalent. The row constructor and the row returned by the subquery must contain the same number of values.

#### Row comparison
> Scalar or column subqueries return a single value or a column of values. A row subquery is a subquery variant that returns a single row and can thus return more than one column value. Legal operators for row subquery comparisons are:
> 
> ```=  >  <  >=  <=  <>  !=```
>
> Here are two examples:
```sql
> SELECT * FROM t1
>   WHERE (col1,col2) = (SELECT col3, col4 FROM t2 WHERE id = 10);
> SELECT * FROM t1
>   WHERE ROW(col1,col2) = (SELECT col3, col4 FROM t2 WHERE id = 10);
```

Semantics of these operators could be found in http://docs.oracle.com/cd/E17952_01/refman-5.0-en/comparison-operators.html. Extract from the description of operator equal:
> For row comparisons, ```(a, b) = (x, y)``` is equivalent to:
> 
> ```(a = x) AND (b = y)```

#### ```IN``` operator

http://docs.oracle.com/cd/E17952_01/refman-5.0-en/row-subqueries.html mentiones use of ```IN``` operator in the context of row subqueries:
> The following query answers the request, “find all rows in table t1 that also exist in table t2”:
```sql
> SELECT column1,column2,column3
>   FROM t1
>   WHERE (column1,column2,column3) IN
>          (SELECT column1,column2,column3 FROM t2);
```

**Comment by wumpz** [comment]
Could you check the new Snapshot version.
