### ISSUE TITLE
postgres `@` for abs number doesn't work

### ISSUE THREAD

**Issue by sixinli** [JSQLParser/JSqlParser#1392]
**Describe the bug**

**To Reproduce**
1. `select @(-1)`
2. Parsing this SQL using JSqlParser with this statements
3.
```
org.junit.ComparisonFailure: Expected query to parse but it failed to parse (error: Encountered unexpected token: "(" "("
    at line 1, column 9.
```

**Expected behavior**
query parses, docs here https://www.postgresql.org/docs/9.5/functions-math.html

`select abs(-1)` works 

**System**
 - postgres
- Java11
- JSqlParser 4.2

**Comment by wumpz** [comment]
Sorry, but to be honest regarding readability this is IMHO a disaster. :/
