### ISSUE TITLE
Sql Parse Exception ( JSQLParserException )

### ISSUE THREAD

**Issue by rac021** [JSQLParser/JSqlParser#1417]
**Describe the bug**

**To Reproduce**
1. Example SQL

```
SELECT EXTRACT(EPOCH FROM timestamp_UTC) AS timestamp, site, variable FROM (SELECT extract(year from timestamp_UTC) AS year, t.id, t.timestamp_UTC, variable, value, 'Galibier' AS site FROM meteo_data_galibier t,LATERAL(VALUES('T', t.airT_C_avg),('Tmin', t.airT_C_min),('Tmax',t.airT_C_max),('RH',t.RH),('WS',t.ws_kmh_avg), ('WSmax',t.ws_kmh_max),('WD',t.winddir_deg_smp),('Slr',t.slr_kW_moy),('PP',NULL)) s(variable, value) UNION SELECT extract(year from timestamp_UTC) AS year, t.id, timestamp_UTC, variable, value,'Rochenoire' AS site FROM meteo_data_rochenoire t,LATERAL(VALUES('T', t.airT_C_avg),('Tmin', t.airT_C_min),('Tmax',t.airT_C_max),('RH',t.RH),('WS',t.ws_kmh_avg), ('WSmax',t.ws_kmh_max),('WD',t.winddir_deg_smp),('Slr',t.slr_kW_moy), ('PP',t.prcp_mm_tot)) s(variable, value) ) AS tmp WHERE variable='T'  ;

```
2. Parsing this SQL using JSqlParser with this statements

```
Select select  = (Select)  parserManager.parse( new StringReader( sqlQuery ) ) ;

```
3. Exception

```
Encountered unexpected token: "," ","
    at line 1, column 245.

Was expecting one of:

    ")"
    "EXCEPT"
    "INTERSECT"
    "MINUS"
    "ORDER"
    "UNION"
```

**Expected behavior**
No parse Exception !

**System**
 - Database you are using : Postgres 13.4
- Java Version : 11
- JSqlParser version : 4.0

**Comment by manticore-projects** [comment]
Greetings, your query works with JSQLParser 4.3 Snapshot and you can [test it online and interactively](http://jsqlformatter.manticore-projects.com/jsqlformatter/demo.html?args=-c%20MoUQMiDCAqAEsgBrQEoEEYAoEAUDykAErAGIp4CysALgJYC2ApgM7UCG9ADgPoCu1AY1gBKWGmA0GLdlwBQ8BQoA0sZrWqN5i5bABubAE602AIwA2mspVjZYoCDHhJUGaNgCejQ6XJU6TVg4efiFRcVhPQy1tGJ1qADpaABNo2JiVBP9pIL5BVLTFFX0jUwt8gvgitjNeTQr02AByAHFq2hNaRgNGsQk1DXL4KyomDQB7biS2dm4AczaOrppB7RUwNGgQdDBMADU0MABVEAlMRuhGjPi2WgNobkhuNl1Z4RUz6HpaADtLmmvbvdHl9vm8bOd6GwAB5-BI3O4PbiQqFgs4oQiw+Lo1GNADqwExAHdmNwANb0AAWTxeOPxyKJJPJVORtIAIkSfkkkrdJoxZtxmFwccAzN0rsxRWTcUixu4cTgcH8AHKHMBgYSiZiYYrGcyMKo1RjCFaHJUASTwSpW9igcAQyHQWAiXgMPmsWUCXFyoV6zqi9VW-2SKzSGSknuCeQDhT0hl1ZWjOn0hpDsRUjRQYwEFMY3zGt0YPXC-TqsWGsFGjAmUxmBizObzBeWAbWGy2Bz2B2Op3OmPhQOpr3eEJ+fcBiJBOM+0LHCOB0Jx6Mx2OH+IZZMpg9pwHpV2JG+ZC9X7L3nO5Bl5-MFnGFosxEovpOl9Fl8sVV04BgEPHo9G41DGagNVUbU41KfVY0NUQwgkag5FxQgthAWMSj1WAAF4mguWQAG4gA+).

**Comment by rac021** [comment]
Great ! Thank you
