### ISSUE TITLE
TokenMgrError

### ISSUE THREAD

**Issue by leftAttack** [JSQLParser/JSqlParser#1430]
Hello, when using your sqlparser, an error occurs when the SQL alias contains Chinese characters.
net.sf.jsqlparser.parser.TokenMgrError: Lexical error at line 3, column 17. Encountered: "\u554a" (21834), after : ""
We look forward to your reply

**Comment by wumpz** [comment]
Hi, this is strange. Look at #302. Which version of JSqlParser do you use? IMHO all letter areas of UTF-8 character set are processed.

**Comment by manticore-projects** [comment]
Closed, since no further question has been asked.
