### ISSUE TITLE
Postgres "->" not support "?"

### ISSUE THREAD

**Issue by rarechit** [JSQLParser/JSqlParser#1434]
**Describe the bug**

` String sql = "SELECT ti.*\n" +
                "        FROM ticket_info ti\n" +
                "         WHERE  ti.tenant_id = ?\n" +
                "                    AND (ti.form_value -> '23s'):: jsonb\n" +
                "                   ?| (array[?,?,?,?,?])";
        Select selectStatement = (Select) CCJSqlParserUtil.parse(sql);
        System.out.println(selectStatement.toString());`

if i do this, it's ok;
if change `ti.form_value -> '23s'` to `ti.form_value -> ?`, it's throw a exception.
![image](https://user-images.githubusercontent.com/34651023/143981196-25f3ddaf-0263-493d-9bbb-32482ecee363.png)

**Expected behavior**

**System**
 - Database you are using
  postgres 9.6
- Java Version 1.8
- JSqlParser version 4.2

**Comment by wumpz** [comment]
That's right. At the moment those JSonExpressions only support character literals and longs. PRs are welcome.

**Comment by manticore-projects** [comment]
[Works with JSQLParser 4.6](http://jsqlformatter.manticore-projects.com/jsqlformatter/demo.html?args=-c%20MoUQMiDCAqAEAuBLAdAKgFADEBKB5AsgogMYDWApvAPqIB2AZgPZHoDqAEiNiEcvObQCGtaogAmsALywA-OlgLYAQQByAEVgAKJMiYAnALZUAboIA2AV3IBaAHwByAEwBmAM72AlAC4vAK1eMtABGsgA+WsrY2EoAmgDaMgA0sslJKbIAurAe6ADcQA), closed.
