### ISSUE TITLE
Handle "WITH TIES" query functionnality

### ISSUE THREAD

**Issue by JulienCheny** [JSQLParser/JSqlParser#1435]
Hi,

I really like the job done here. I have only one case not handled by the parser : 
The **WITH TIES functionnality** of the **SELECT TOP** clause (https://www.sqlservertutorial.net/sql-server-basics/sql-server-select-top/).

### Example :
```SQL
SELECT TOP 3 WITH TIES *
FROM MyTable 
ORDER BY ID;
```

### Error raised :
net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "with" "WITH"

### Temporary solution
Preprocess the query by removing the matching regex **with\\s\*?ties**

```Java
queryStr= queryStr.replaceAll("(?i)with\\s*?ties", "");
```

**Comment by wumpz** [comment]
As I understand this, it is some kind of flag of `top` for SQLServer. Right?  

https://docs.microsoft.com/de-de/sql/t-sql/queries/top-transact-sql?view=sql-server-ver15

So this should not be hard to implement. PRs are welcome.
