### ISSUE TITLE
Support for CURRENT function in DB2 

### ISSUE THREAD

**Issue by zoeoros** [JSQLParser/JSqlParser#144]
Hi,
in DB2 you can use the function CURRENT DATE, CURRENT TIMESTAMP, CURRENT TIME.... to obtain the current date value, but this expression fails in jsqlparser.
Reference: 
https://www-01.ibm.com/support/knowledgecenter/SSEPGG_9.7.0/com.ibm.db2.luw.sql.ref.doc/doc/r0005870.html?cp=SSEPGG_9.7.0%2F2-10-2-5-4&lang=en

Ex:
UPDATE PROJECT
     SET PRENDATE = CURRENT DATE
     WHERE PROJNO = 'MA2111'

INSERT INTO IN_TRAY
     VALUES (CURRENT TIMESTAMP, :SRC, :SUB, :TXT)

SELECT CLASS_CODE FROM CL_SCHED
     WHERE STARTING > CURRENT TIME

Thanks!

**Comment by wumpz** [comment]
implemented in version 0.9.6-SNAPSHOT
