### ISSUE TITLE
ALTER TABLE tablename AD brand varchar(100); doesnt fail in validation.

### ISSUE THREAD

**Issue by atharmutallib** [JSQLParser/JSqlParser#1447]
**Description**
ALTER TABLE tablename AD brand varchar(100); doesn't fail in the validation even though syntax error in keyword ADD. Since 4.2 version it passes before until 4.1 it use to fail in validation.

**To Reproduce**
1. ALTER TABLE tablename AD brand varchar(100);
2. Parsing this SQL using JSqlParser with the statement: validate(sql, FeaturesAllowed.ALTER);
3. No Exception or errors

**Expected behavior**
Validation errors should exists or Exception should be thrown.

**System**
 - DB2
- Java Version: 8
- JSqlParser version: 4.3

**Comment by manticore-projects** [comment]
Greetings.

your observation is actually a `Feature`, but not a bug.
Explanation: `ALTER TABLE ...` has very rich syntax in various RDBMS, impossible to implement them all.
Example: Oracle's `ALTER TABLE tablename MOVE tablespace`

We do not want to fail those statements even when we do no parse them. Thus we route them through as a Token List via `AlterOperation.UNSPECIFIC`. In the result, your statement is parsed and deparsed (just without a meaning) and so the Validation does not fail.

Although you could explicitly test for `AlterOperation.UNSPECIFIC` and then take action.

**Comment by manticore-projects** [comment]
No further questions or feedback provided, closed.

**Comment by atharmutallib** [comment]
Why was it failing earlier in version 4.2?
Which was a valid result is validation failing

**Comment by manticore-projects** [comment]
Greetings.

> Why was it failing earlier in version 4.1?

Because there was no `AlterOperation.UNSPECIFIC` which caught any unknown/unsupported `Alter Table` commands.

> Which was a valid result that is validation failing in such a scenario. Now it is not in 4.2+

"in such a scenario" also `ALTER TABLE ... MOVE ...` failed (wrongly).
The correct solution was to check for 1) failure and also 2)  `AlterOperation.UNSPECIFIC` and to deem your statement `invalid` for both events.

**Comment by atharmutallib** [comment]
Ok. Do you have a sample to explicitly test for AlterOperation.UNSPECIFIC?

**Comment by manticore-projects** [comment]
> Do you have a sample to explicitly test for AlterOperation.UNSPECIFIC?

```java
 String sqlStr = "ALTER TABLE tablename AD brand varchar(100)";
        Alter alter = (Alter) CCJSqlParserUtil.parse(sqlStr);
        for (AlterExpression alterExpression: alter.getAlterExpressions()) {
          if ( alterExpression.getOperation().equals( AlterOperation.UNSPECIFIC )) {
               System.out.println(" Unspecific Operation found, maybe invalid");
            }
        }
```

Cheers.

**Comment by atharmutallib** [comment]
Thanks a lot. 

Works like before. I highly appreciate your help.

In the DatabaseType enum list, I don't see DB2. Will it be part of future releases?

**Comment by manticore-projects** [comment]
Your are most welcome.

> In the DatabaseType enum list, I don't see DB2. Will it be part of future releases?

Honestly, this is difficult to answer.
In my personal opinion, and **explicitly not speaking for the JSQLParser project**: The Validation framework is a great idea but seems to be difficult to maintain. So unless a strong contributor shows up and invests effort into it, it is unlikely to happen. My own interest is in parsing and formatting SQL (only).

**Comment by wumpz** [comment]
@atharmutallib If you provide a feature class (like net.sf.jsqlparser.util.validation.feature.MySqlVersion) for DB2 I would happily add this database to the validation list. But as @manticore-projects already mentioned, the main focus of JSqlParser is in parsing SQLs so maintaining the validation framework for concrecte databases or even versions of them is falling behind or is left to the users to provide PRs.

**Comment by atharmutallib** [comment]
Thanks.

I have created a feature class for DB2. See if it is OK.
[feature DB2.zip](https://github.com/JSQLParser/JSqlParser/files/7854123/feature.DB2.zip)

.

**Comment by wumpz** [comment]
Please provide a pull request. I will review this and we can discuss possible or needed improvements.
