### ISSUE TITLE
Cast :: operator in limit or offset is not supported

### ISSUE THREAD

**Issue by pmioulet** [JSQLParser/JSqlParser#1448]
```
var query_simple = "select 1 limit 1::int offset 1::int";
CCJSqlParserUtil.parse(query_simple);
```
It looks like limit and offset do not support casting of the arguments as the code above will end up with an exception.

I also noticed that offsets don't support arithmetic operations as below code will also result in an error:

```
var query_simple = "select 1 limit 1 offset 5*10";
 CCJSqlParserUtil.parse(query_simple);
```

Both are supported by postgres.

**Comment by manticore-projects** [comment]
Greetings.

What version of JSQL Parser have you tested please?
`Complex Expressions` for `LIMIT` have added recently and should work in 4.3.

**Comment by pmioulet** [comment]
My bad i just checked, I noticed both these features work in 4.3, I was using 4.2, thanks for the reply
