### ISSUE TITLE
Apache 2 license dropped

### ISSUE THREAD

**Issue by marianormuro** [JSQLParser/JSqlParser#145]
Hi guys, this is a issue with license. Since the fork started it has been licensed under LGPL. The original JSQLParser was dual licensed under LGPL and Apache 2.0. This makes it impossible for users of the original jsqlparser to use your current implementation or contribute when they do it in the context of Apache 2 licenses.

This is the case of our project (https://github.com/ontop/ontop) at the moment. We realized this and realized we might get into trouble. Sarah from our team contributed with issue #60 some time ago.

Have you considered using the dual licensing scheme again for a next release? 

Thank you in advance,
Mariano

**Comment by wumpz** [comment]
Just for curiosity. Why someone cannot use and modify a lgpl project and use it in an apache licensed one?

**Comment by marianormuro** [comment]
Apparently this requires publication of the modified source-code to be licensed as lgpl too. Because of this, legal departments in companies that use an apache 2 project freak out when they see dependencies to even LGPL libraries. Theres the potential of wrongly using the code by the developers of internal projects and potential for liabilities. This is the case with some of ontop's users (our project).

**Comment by wumpz** [comment]
So not the usage but the modification without pushing back to the original/fork is the problem? So what modifications do you need?

**Comment by marianormuro** [comment]
Hi Tobias, In our case, the modifications/bugfixes that we have needed from jsqlparser we have pushed to the main development tree. There is no issue for our project in that respect.

The issue is that lawyers in some companies (large ones) will refuse to authorize the use of projects that have dependencies to an LGPL. The issue is that having a dependency to jsqlparser is seen as a weakness of the project. In the lawyers point of view, if company C uses project X (with apache license) and project X violates jsqlparser LGPL license, then company C is exposed to a lawsuit by using project X. So developers, researchers, etc in company C end-up unable to use projects like this.

Although in principle, an LGPL dependency is not a problem if there is no violation of license (e.g., publishers of project X never modify jsqlparser, or push back to the original repository), It can be very hard to convince corporate lawyers to project X that the developers of the project wont violate LGPL's clauses. Hence, having LGPL dependencies is always problematic for projects that want to reach every kind of developer (including industry). Thats why many large projects like hadoop, postgres, eclipse, Git, svn, etc., are developed under very liberal licenses, mostly Apache 2.0, MIT, BSD.

Thats why we are asking to revise this issue, we are having exactly this problem right now. We are trying to establish a collaboration with this big company, so we can develop the project together but the LGPL can be an issue. We just noticed that it is an issue, since before it was dual. So we thought of asking if it would be possible to revise the license in a new minor release, and to keep it dual (LGPL and Apache 2) as it was before. This would allow us to continue collaborating with our colleagues that company and continue using jsqlparser in the project (contributing with extension an bugfixes as before). 

Do you think this would be possible?

**Comment by wumpz** [comment]
Yep
 I don't think it is a problem. I was not aware of these troubles an LGPL license could cause. In JSQLPARSERs case I removed the Apache license to clean things up when I made this fork. So let me read a bit into this matter to choose the right way or license to follow. Cheers Tobias

**Comment by marianormuro** [comment]
Thank you so much Tobias, we appreciate it very very much. 

A useful link on the topic, https://en.wikipedia.org/wiki/Multi-licensing (covers in detail the different uses of dual licenses)

**Comment by wumpz** [comment]
So it seems the Apache 2 license is appropriate. I will build it in again. Give me some time to do it. The next release will have both licenses again.

Hope that helps and thx for using JSqlParser.

;)

**Comment by marianormuro** [comment]
It does Tobias, it helps a great deal actually. And thank you for leading
jsql, we really depend on it (and im sure lots of people do). We'll try
continue contributing.

- M

On Wed, Jul 1, 2015 at 6:18 PM, Tobias <notifications@github.com> wrote:

> So it seems the Apache 2 license is appropriate. I will build it in again.
> Give me some time to do it. The next release will have both licenses again.
>
> Hope that helps and thx for using JSqlParser.
>
> ;)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/JSQLParser/JSqlParser/issues/145#issuecomment-117839977>
> .
>



-- 

Mariano Rodriguez Muro
http://www.rodriguez-muro.com
https://w3-connections.ibm.com/profiles/html/profileView.do?uid=3G3860897

Research Staff, IBM Research
IBM T.J. Watson research center
Yorktown heights, NY. USA
+1-914-945-2607

home: mariano.muro@gmail.com
work: mrodrig@us.ibm.com

**Comment by wumpz** [comment]
License revived. Could you check if it fits your needs? T

**Comment by marianormuro** [comment]
This works perfect Tobias, thank you so much
