### ISSUE TITLE
Regression validating cases like avg(*) in JSQLParser 4.3

### ISSUE THREAD

**Issue by Pashulity** [JSQLParser/JSqlParser#1451]
**Describe the bug**

Version 4.3 of JSQLParser seems to introduce a regression in the way what Function.getParameters() returns.

**To Reproduce**

Pass sql expression `select avg(*) from table t`, parse it to `Select` and invoke `Function.getParameters()` on SelectExpressionItem` which describes `avg(*)` function

**Expected behavior**

In 4.2 `Function.getParameters()` returns null.
In 4.3 `Function.getParameters()` returns `List` of `AllColumns` with size 1

System

Java Version: openjdk-17
JSqlParser version: 4.3

**Comment by manticore-projects** [comment]
Greetings.

Unfortunately I do not understand your concern, as this is a correction of the previous wrong behavior. Why exactly would you want to receive `NULL` instead of `AllColumns` here?

**Comment by Pashulity** [comment]
> Greetings.
> 
> Unfortunately I do not understand your concern, as this is a correction of the previous wrong behavior. Why exactly would you want to receive `NULL` instead of `AllColumns` here?

Because version 4.2 returns null. You changed the behavior in 4.3

**Comment by Pashulity** [comment]
> Greetings.
> 
> Unfortunately I do not understand your concern, as this is a correction of the previous wrong behavior. Why exactly would you want to receive `NULL` instead of `AllColumns` here?

There is no information about this in release notes (e.g fixed bug XXX-YYY).

**Comment by manticore-projects** [comment]
On Wed, 2021-12-29 at 07:13 -0800, Pashulity wrote:
> Because version 4.2 returns null. 

Which has been wrong obviously.

> You changed the behavior in 4.3

This can happen, when correcting broken stuff.

**Comment by manticore-projects** [comment]
> There is no information about this in release notes (e.g. fixed bug XXX-YYY).

https://github.com/JSQLParser/JSqlParser/releases states:
**added use of * or mytable.* as a function parameter**

**Comment by Pashulity** [comment]
> __added use of * or mytable._ as a function parameter_*

It was not so obvious imho.

But thank you anyway!
