### ISSUE TITLE
Will you increase your support for hive

### ISSUE THREAD

**Issue by summerjj32** [JSQLParser/JSqlParser#1452]
Will you increase your support for hive，

**Comment by manticore-projects** [comment]
Greetings.

As for any open source project, there are 2 possible ways to get functions implemented:

a) someone with own interest (in hive) volunteers and contributes working code
b) someone with particular requirements (about hive) sponsors the developers to implement those (e. g. setting a bounty)

**Comment by manticore-projects** [comment]
Closed, since no further question has been asked.
