### ISSUE TITLE
sql parse error

### ISSUE THREAD

**Issue by linyuliang** [JSQLParser/JSqlParser#147]
SELECT
    a.*, b.username,
    b.client_type,
    b.vender,
    b.remasks,
    b.ipv4
FROM
    (
        SELECT
            a.sta_mac,
            ap_mac,
            b. NAME,
            a.rssi,
            a.avg_tx_pkt_rate,
            a.avg_rx_pkt_rate,
            a.tx_kbyte_time,
            a.packet_loss_rate,
            a.downFlow,
            a. TIMESTAMP,
            a.ssid
        FROM
            t_sta_rate_analysis a,
            t_ap b,
            t_ap_area c,
            sys_organization d
        WHERE
            a. TIMESTAMP BETWEEN DATE_SUB(?, INTERVAL ? MINUTE)
        AND ?
        AND a.ap_mac = b.mac
        AND b.area_id = c.id
        AND c.org_id = d.id
        AND c.org_id = ?
        AND b.area_id IN (
            SELECT
                id
            FROM
                t_ap_area a
            WHERE
                a.parent_ids LIKE CONCAT("%/", ?, "/%")
            UNION
                SELECT
                    ?
        )
        ORDER BY
            a. TIMESTAMP DESC
    ) a
LEFT JOIN t_sta b ON a.sta_mac = b.mac
WHERE
    1 = 1
GROUP BY
    a.sta_mac

**Comment by wumpz** [comment]
Could you provide an exception? Is this the smallest available problem sql?

**Comment by linyuliang** [comment]
I use mysql
1. "select 1" 
    without from table
    NullPointerException
2."SELECT * from test_table a WHERE a. TIMESTAMP BETWEEN DATE_SUB(?, INTERVAL ? MINUTE)" 
    net.sf.jsqlparser.parser.ParseException: Encountered " <S_IDENTIFIER> "a "" at line 1, column 34.

**Comment by wumpz** [comment]
Which version of JSqlParser do you use?

1. JSqlParser V0.9.x parses "select 1" successfully. NPE should be within the rest of your code. 
2. At the moment JSqlParser does not support a placeholder within interval expressions. INTERVAL ? MINUTE does not work, but INTERVAL '5' MINUTE succeeds.

**Comment by linyuliang** [comment]
V0.9.2
I used shardbatis with mybatis, so the sql for parse is INTERVAL ? MINUTE

**Comment by wumpz** [comment]
Pull requests are welcome. 😉

**Comment by wumpz** [comment]
works in the actual version 4
