### ISSUE TITLE
Can not parse Functional Base Index

### ISSUE THREAD

**Issue by thrkrdk** [JSQLParser/JSqlParser#1472]
In Oracle ve Postgresql functional-bases indexes are not parsed. Will this type indexes be parsed in the future?

**oracle**
 create index MY_INDEX on emp(NVL(ename, 'null'));

**postgresql**
 create index MY_INDEX on emp(coalesce(ename, 'null'));
 

**System**
 - Oracle 18, Postgrsql 9.6
- Java 15
-  SqlParser  4.2

Thank you.

**Comment by wumpz** [comment]
Both statements are parsed using JSqlParser 4.3.

**Comment by thrkrdk** [comment]
@wumpz  thank you it's work.
When I parsed the statements, I think column name is wrong. You can see in SS. 
Should it be like that ?
![image](https://user-images.githubusercontent.com/7022571/152743671-ed103985-b174-4976-83db-0d91caeeb590.png)

**Comment by wumpz** [comment]
Essentially due to multiple constructs JSqlParser has to deal with, this is how it is recognized.
