### ISSUE TITLE
PGSQL CCJSqlParserUtil.parse can't parse || 

### ISSUE THREAD

**Issue by cjran704** [JSQLParser/JSqlParser#1473]
**Describe the bug**
PGSQL CCJSqlParserUtil.parse can't parse || 

**To Reproduce**
1. select id,name from test where name like '%'||?||'%'
2. JSqlParser 4.3
3. net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "||" <OP_CONCAT>

**Expected behavior**

**System**
 - Postgresql 11.8
- jdk 1.8
- JSqlParser 4.3

**Comment by wumpz** [comment]
*?|* is a JSON operator in JSqlParser. The parser cannot split ?|| to ? ||. So you will be able to parse the expression if you insert whitespaces:

```sql
select id,name from test where name like '%' || ? || '%'
```

**Comment by manticore-projects** [comment]
Closed, since no further question has been asked.
