### ISSUE TITLE
need is expression

### ISSUE THREAD

**Issue by doukai** [JSQLParser/JSqlParser#1475]
Hi
i have a boolean type column name `bool_col`
bool_col in where need jdbc parameter: 
`WHERE bool_col IS :boolParam`
so in need a expression to support: 
`<leftExpression> IS <rightExpression>`
Any idea about it?
Thanks~

**Comment by wumpz** [comment]
This is already halfway implemented. Look into

line 3299:  `Expression IsBooleanExpression(Expression leftExpression):`

At the moment this one supports only true / false but named jdbc parameters should not be a problem to implement. 

Do you want to provide a PR?
