### ISSUE TITLE
TSQL - Aliasing using "=" 

### ISSUE THREAD

**Issue by goranschwarz** [JSQLParser/JSqlParser#1476]
**Describe the bug**
Not sure if this is supported (column aliasing using equal sign)   
I know it's not ANSI standard, but **a lot** of TSQL statements looks like this!!!

**To Reproduce**
1. Example SQL:  `select  col1 = 'some value'` 
2. Exception
```
net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "=" "="
    at line 1, column 14.

Was expecting one of:

    "&"
    ","
    "::"
    ";"
    "<<"
    ">>"
    "ACTION"
    "ANY"
    "AS"
    "BYTE"
    "CASCADE"
    "CAST"
    "CHANGE"
    "CHAR"
    "CHARACTER"
    "COLLATE"
    "COLUMN"
    "COLUMNS"
    "COMMENT"
    "COMMIT"
    "CONNECT"
    "CYCLE"
    "DESCRIBE"
    "DISABLE"
    "DO"
    "DUPLICATE"
    "ENABLE"
    "END"
    "EXCEPT"
    "EXTRACT"
    "FALSE"
    "FIRST"
    "FN"
    "FOLLOWING"
    "FOR"
    "FROM"
    "GROUP"
    "HAVING"
    "INDEX"
    "INSERT"
    "INTERSECT"
    "INTERVAL"
    "INTO"
    "ISNULL"
    "KEY"
    "LAST"
    "MATERIALIZED"
    "MINUS"
    "NEXTVAL"
    "NO"
    "NOLOCK"
    "NULLS"
    "OPEN"
    "ORDER"
    "OVER"
    "PARTITION"
    "PATH"
    "PERCENT"
    "PRECISION"
    "PRIMARY"
    "PRIOR"
    "RANGE"
    "READ"
    "REPLACE"
    "ROW"
    "ROWS"
    "SCHEMA"
    "SEPARATOR"
    "SESSION"
    "SIBLINGS"
    "SIZE"
    "START"
    "TABLE"
    "TEMP"
    "TEMPORARY"
    "TOP"
    "TRUE"
    "TRUNCATE"
    "TYPE"
    "UNION"
    "UNSIGNED"
    "VALIDATE"
    "VALUE"
    "VALUES"
    "VIEW"
    "WHERE"
    "WINDOW"
    "XML"
    "ZONE"
    "["
    "^"
    "|"
    <EOF>
    <K_DATETIMELITERAL>
    <K_DATE_LITERAL>
    <S_CHAR_LITERAL>
    <S_IDENTIFIER>
    <S_QUOTED_IDENTIFIER>
```

**Expected behavior**
That the parser can handle *old* syntax for column aliasing   
I know it's not ANSI standard, but **a lot** of TSQL statements looks like this!!!

**System**
 - SQL Server (any veraion) and Sybase ASE (any version)
- Java Version 8
- JSqlParser version: jsqlparser-3.2.jar  (I know it's a bit old, and I will upgrade when I have the time, and if my feature request is implemented, I will upgrade ASAP)

**Comment by wumpz** [comment]
JSqlParser 4.3 is able to parse this. However, this is not an alias but JSqlParser recognizes this as a condition. Are you sure this is a TSQL alias? I know those as assignments.

**Comment by goranschwarz** [comment]
Here are some example, on both TSQL assignment and aliasing...
I'm using the  global variable `@@version` as a string constant (but only the first 50 chars, because the sting is *a bit longer* than that :)

**Plain ANSI SQL using 'as'**
`select substring(@@version, 1, 50) as version`
Result
```
+--------------------------------------------------+
|version                                           |
+--------------------------------------------------+
|Microsoft SQL Server 2019 (RTM-CU13) (KB5005679) -|
+--------------------------------------------------+
```

**TSQL aliasing using 'equal'**
`select version = substring(@@version, 1, 50)`
Result
```
+--------------------------------------------------+
|version                                           |
+--------------------------------------------------+
|Microsoft SQL Server 2019 (RTM-CU13) (KB5005679) -|
+--------------------------------------------------+
```

**TSQL assignment AND aliasing 'equal'**
```
declare @ver varchar(50)                  -- declare a variable
select @ver = substring(@@version, 1, 50) -- assign the variable
select version1=@ver, @ver as version2    -- creating a ResultSet using both TSQL equal-aliasing and ANSI-aliasing
```
Result
```
+--------------------------------------------------+--------------------------------------------------+
|version1                                          |version2                                          |
+--------------------------------------------------+--------------------------------------------------+
|Microsoft SQL Server 2019 (RTM-CU13) (KB5005679) -|Microsoft SQL Server 2019 (RTM-CU13) (KB5005679) -|
+--------------------------------------------------+--------------------------------------------------+
```

**Comment by wumpz** [comment]
But the examples you send are no aliases but assignments. JSqlParser is able to parse this

```sql
select @col1 = 'some value'
```

So you need to explicitly use this `@`.

**Comment by goranschwarz** [comment]
My example was showing both variable assignment and a tsql column alias

Here is another example where I do **only** column alias (2 examples, which produces the same output)

First example is a TSQL column alias, which **do not work** in JSqlParser
```
1> select col1 = 'col1-value'
+----------+
|col1      |
+----------+
|col1-value|
+----------+
```

Second example is using ansi column aliasing, which of course works in JSqlParser
```
1> select 'col1-value' as col1
+----------+
|col1      |
+----------+
|col1-value|
+----------+
```

**Comment by wumpz** [comment]
OK. That was new to me. Thx for the clarification. However, JSqlParser is able to parse your statements, but as I said, it will not result in an **alias** like parse tree. If you can accept, that your alias is in JSqlParser view a **condition**, you can use it. 

There are databases that parse your statement as a condition and are computing boolean values, as if they were in the **where** statement.

```sql
select 3 = 4
select a = b
select a = 5 + 3
```

So I think we will not make a change to produce an aliased expression in your sense.

In my view it still is an assignment to a variable name that you can use in your statement. But that are only names, right?

**Comment by goranschwarz** [comment]
This sounds ok
