### ISSUE TITLE
Several create function statements are stuck in a single statement

### ISSUE THREAD

**Issue by qiujiangkun** [JSQLParser/JSqlParser#1477]
**Describe the bug**
Several create function statements are stuck in a single statement

**To Reproduce**
```scala
  def parse(sql: String): Seq[AstNode] = {
    var collected = ArrayBuffer[AstNode]()

    val stmts = CCJSqlParserUtil.parseStatements(sql)
    stmts.getStatements.asScala.foreach {
      case table: CreateTable   => collected += parseCreateTable(table)
      case func: CreateFunction => collected += parseCreateFunction(func)
      case _                    =>
    }
    collected.toSeq
  }
```
```sql
CREATE OR REPLACE FUNCTION func_example(foo integer)
RETURNS integer AS $$
BEGIN
  RETURN foo + 1;
END
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION func_example2(IN foo integer, OUT bar integer)
AS $$
BEGIN
    SELECT foo + 1 INTO bar;
END
$$ LANGUAGE plpgsql;

```
![image](https://user-images.githubusercontent.com/33482468/154742346-55fb7c65-2db4-448c-a18f-b6194641ae5a.png)

**Expected behavior**

**System**
 - Database you are using: Postgres
- Java Version JDK 1.8
- JSqlParser version 4.3

**Comment by wumpz** [comment]
Thats right. Look into line 6248. JSqlParser does not parse the statements but reads all tokens from $$ to $$. Unfortunately whitespaces are skipped.

**Comment by manticore-projects** [comment]
Fixed this issue, functions/procedures can end now in two ways:

1) `<BEGIN> ... <END> ( ; | EOF)`
2) `<$$> ... <$$> ... ( ; | EOF)`
