### ISSUE TITLE
CCJSqlParserUtil.parseCondExpression returns incorrect class for the IN condition.

### ISSUE THREAD

**Issue by LonwoLonwo** [JSQLParser/JSqlParser#1482]
**Describe the bug**
The method CCJSqlParserUtil.parseCondExpression(expression, allowPartialParse) returns incorrect value for this condition:

`test_table_enum.f1_enum IN ('TEST2'::test."test_enum")`

It returns class `Column` with value `test_table_enum.f1_enum`,
instead of `InExpression`

We use this method in DBeaver for data filter statement creating, and the lack of the correct class leads to this issue: https://github.com/dbeaver/dbeaver/issues/15626 

By the way, this statement parsed fine:

`test_table_enum.f1_enum IN ('TEST2'::test.test_enum)`

So I think that issue is in quotes around data type name. Quotes around table name or schema name also do not lead to a mistake.

**System**
 - PostgreSQL 13
 - 11
 - JSqlParser version 4.3

**Comment by wumpz** [comment]
You were right. Thx for using JSqlParser. I corrected this and allowed quoted identifiers at your specific position of this cast.

**Comment by LonwoLonwo** [comment]
Thanks @wumpz 

I will wait for release.
