### ISSUE TITLE
JSQLParserException

### ISSUE THREAD

**Issue by donye86** [JSQLParser/JSqlParser#1488]
"C:\Program Files\Java\jdk1.8.0_91\bin\java.exe" -javaagent:C:\rym\develop\IDE\ideaIC-2021.1.1.win\lib\idea_rt.jar=56708:C:\rym\develop\IDE\ideaIC-2021.1.1.win\bin -Dfile.encoding=UTF-8 -classpath "C:\Program Files\Java\jdk1.8.0_91\jre\lib\charsets.jar;C:\Program Files\Java\jdk1.8.0_91\jre\lib\deploy.jar;C:\Program Files\Java\jdk1.8.0_91\jre\lib\ext\access-bridge-64.jar;C:\Program Files\Java\jdk1.8.0_91\jre\lib\ext\cldrdata.jar;C:\Program Files\Java\jdk1.8.0_91\jre\lib\ext\dnsns.jar;C:\Program Files\Java\jdk1.8.0_91\jre\lib\ext\jaccess.jar;C:\Program Files\Java\jdk1.8.0_91\jre\lib\ext\jfxrt.jar;C:\Program Files\Java\jdk1.8.0_91\jre\lib\ext\localedata.jar;C:\Program Files\Java\jdk1.8.0_91\jre\lib\ext\nashorn.jar;C:\Program Files\Java\jdk1.8.0_91\jre\lib\ext\sunec.jar;C:\Program Files\Java\jdk1.8.0_91\jre\lib\ext\sunjce_provider.jar;C:\Program Files\Java\jdk1.8.0_91\jre\lib\ext\sunmscapi.jar;C:\Program Files\Java\jdk1.8.0_91\jre\lib\ext\sunpkcs11.jar;C:\Program Files\Java\jdk1.8.0_91\jre\lib\ext\zipfs.jar;C:\Program Files\Java\jdk1.8.0_91\jre\lib\javaws.jar;C:\Program Files\Java\jdk1.8.0_91\jre\lib\jce.jar;C:\Program Files\Java\jdk1.8.0_91\jre\lib\jfr.jar;C:\Program Files\Java\jdk1.8.0_91\jre\lib\jfxswt.jar;C:\Program Files\Java\jdk1.8.0_91\jre\lib\jsse.jar;C:\Program Files\Java\jdk1.8.0_91\jre\lib\management-agent.jar;C:\Program Files\Java\jdk1.8.0_91\jre\lib\plugin.jar;C:\Program Files\Java\jdk1.8.0_91\jre\lib\resources.jar;C:\Program Files\Java\jdk1.8.0_91\jre\lib\rt.jar;C:\Users\zhengqy\IntelliJIDEAProjects\MysqlToPG\target\classes;C:\Users\zhengqy\.m2\repository\commons-io\commons-io\2.11.0\commons-io-2.11.0.jar;C:\Users\zhengqy\.m2\repository\com\github\jsqlparser\jsqlparser\4.2\jsqlparser-4.2.jar" org.zqy.MysqlDdl2PgDdlUtil
DROP TABLE IF EXISTS `u_call_record`;
CREATE TABLE `u_call_record`  (
  `card_user_id` int(11) NOT NULL,
  `device_id` int(11) NOT NULL,
  `call_start_at` int(11) NOT NULL DEFAULT CURRENT_TIMESTAMP(11),
  `card_user_name` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  `sim_id` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  `called_number` varchar(12) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  `called_nickname` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  `talk_time` smallint(8) NULL DEFAULT NULL,
  `area_name` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  `area_service_id` int(11) NULL DEFAULT NULL,
  `operator_id` int(4) NULL DEFAULT NULL,
  `status` tinyint(4) NULL DEFAULT NULL,
  `create_at` timestamp NULL DEFAULT NULL,
  `place_user` varchar(16) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  PRIMARY KEY (`card_user_id`, `device_id`, `call_start_at`) USING BTREE,
  INDEX `ucr_index_area_name`(`area_name`) USING BTREE,
  INDEX `ucr_index_area_service_id`(`area_service_id`) USING BTREE,
  INDEX `ucr_index_called_number`(`called_number`) USING BTREE,
  INDEX `ucr_index_create_at`(`create_at`) USING BTREE,
  INDEX `ucr_index_operator_id`(`operator_id`) USING BTREE,
  INDEX `ucr_index_place_user`(`place_user`) USING BTREE,
  INDEX `ucr_index_sim_id`(`sim_id`) USING BTREE,
  INDEX `ucr_index_status`(`status`) USING BTREE,
  INDEX `ucr_index_talk_time`(`talk_time`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = Dynamic;
++++++++++开始转换SQL语句+++++++++++++
Exception in thread "main" net.sf.jsqlparser.JSQLParserException: Encountered unexpected token: "USING" "USING"
    at line 18, column 44.

Was expecting one of:

    ")"
    ","

	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parseStatements(CCJSqlParserUtil.java:215)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parseStatements(CCJSqlParserUtil.java:203)
	at org.zqy.MysqlDdl2PgDdlUtil.main(MysqlDdl2PgDdlUtil.java:26)
Caused by: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "USING" "USING"
    at line 18, column 44.

Was expecting one of:

    ")"
    ","

	at net.sf.jsqlparser.parser.CCJSqlParser.generateParseException(CCJSqlParser.java:30694)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_consume_token(CCJSqlParser.java:30527)
	at net.sf.jsqlparser.parser.CCJSqlParser.CreateTable(CCJSqlParser.java:14894)
	at net.sf.jsqlparser.parser.CCJSqlParser.SingleStatement(CCJSqlParser.java:281)
	at net.sf.jsqlparser.parser.CCJSqlParser.Statements(CCJSqlParser.java:871)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parseStatements(CCJSqlParserUtil.java:213)
	... 2 more

Process finished with exit code 1

**Comment by wumpz** [comment]
Within your create statement are two problems:

1.  `INDEX ucr_index_sim_id(sim_id) USING BTREE`
2.  `CHARACTER SET = utf8mb4`

PRs are wellcome.
