### ISSUE TITLE
can not parser union select clause in insert  query

### ISSUE THREAD

**Issue by young0098** [JSQLParser/JSqlParser#1491]
I mock a simple insert query like this
 insert into table1 (tf1,tf2,tf2)
((select sf1,sf2,sf3 from s1) union (select rf1,rf2,rf2 from r1)) 
and get  follow paseexception:
net.sf.jsqlparser.JSQLParserException: Encountered unexpected token: "union" "UNION"
    at line 2, column 31.
Was expecting one of:

    "&"
    ")"
    ","
    "::"
    "<<"
    ">>"
    "COLLATE"
    "["
    "^"
    "|"

	net.sf.jsqlparser.parser.CCJSqlParserUtil.parseStatement(CCJSqlParserUtil.java:190)
	net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:63)
	net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:38)

**System**
 - Postgresql
- Java 1.8
- JSqlParser 4.2

**Comment by manticore-projects** [comment]
Greetings.

The brackets are the problem, without the brackets it works:
```sql
INSERT INTO table1 (
    tf1
    , tf2
    , tf2 )
SELECT  sf1
        , sf2
        , sf3
FROM s1
UNION
SELECT  rf1
        , rf2
        , rf2
FROM r1
;
```

**Comment by manticore-projects** [comment]
In my opinion, we need to refactor the whole `INSERT` production to make this work.
Currently, it supports `(` `SELECT` `)` (with maximum one embracing set of bracket). But in fact, this should be an `EXPRESSION` with possible many embracing brackets (e. g. `INSERT INTO ... ( ( ( SELECT ... FROM ... ) ) )`)
