### ISSUE TITLE
解析器无法识别JSON_OBJECT使用表字段

### ISSUE THREAD

**Issue by 532780857** [JSQLParser/JSqlParser#1496]
<img width="984" alt="image" src="https://user-images.githubusercontent.com/39074601/160780369-d9508f48-07af-413e-8920-d90ca6e1995b.png">
如图，tb_team表的account动态赋值给JSON_OBJECT时报错

**Comment by 532780857** [comment]
可否提供补丁或者发布一个版本给我先用

**Comment by 532780857** [comment]
阿里渣渣java研发组群主到此一游，留下计划，下次再来，群号:831363708

**Comment by wumpz** [comment]
Please in English.

**Comment by manticore-projects** [comment]
Duplicate #1504
