### ISSUE TITLE
spanish tables

### ISSUE THREAD

**Issue by fphilip** [JSQLParser/JSqlParser#150]
Any idea how i do to resolve this?

    @Test
    public void test_encoding_spanish() throws JSQLParserException {
        CCJSqlParserManager _parser = new CCJSqlParserManager();
        Statement _statement = _parser.parse(new StringReader("select * from años"));

            if (_statement != null && _statement instanceof Select) {
                Select _select = (Select) _statement;

            }

    }

**Comment by wumpz** [comment]
You have a token rule  additional_letters. Include your Spanish letters there and you are done.

**Comment by wumpz** [comment]
could you test the new snapshot?
