### ISSUE TITLE
ValidationException occurs when accessing the column with table's alias

### ISSUE THREAD

**Issue by qwefgh90** [JSQLParser/JSqlParser#1502]
**Describe the bug**
When accessing the column with table's alias, ValidationException occurs because of the wrong validation order.

**To Reproduce**
1. SQL
```
        var errors = parserUtils.validate(
                "select b.id, name ,(select name from Blog where name = 'sadf') as name2 \n" +
                        ", category, owner, b.update_time \n" +
                        "from Blog as b \n" +
                        "left join Content\n" +
                        "ON b.id = Content.blog_id  \n" +
                        "where name = 'sadf' order by Content.title desc"
                ,capa
        );
```

2. Parsing this SQL using JSqlParser with this statements
```
        Validation validation = new Validation(Arrays.asList(capability()), stmt);
        List<ValidationError> errors = validation.validate();
        return errors;
```
3. Produce wrong results after validation().
```
capability=meta data
errors=[ValidationException: b.id does not exist., UnexpectedValidationException: name: cannot validate column-name. detail: fully qualified name must not be null, UnexpectedValidationException: name: cannot validate column-name. detail: fully qualified name must not be null, ValidationException: b.update_time does not exist.]
]]
```

**Expected behavior**
b.id, b.update_time must exist. and It should not throw `ValidationException`.

**System**
 - Database you are using: mysql 8
- Java Version: jdk 13
- JSqlParser version: v4.3

**Comment by qwefgh90** [comment]
```
It is solved, after making changes in SelectValidator.java by extending it.
```
        // Comment a wrong line. (1)
        //  validateOptionalList(plainSelect.getSelectItems(), () -> this, (e, v) -> e.accept(v));

        validateOptionalFromItem(plainSelect.getFromItem());
        validateOptionalFromItems(plainSelect.getIntoTables());
        validateOptionalJoins(plainSelect.getJoins());

        // Moved here (2)
        validateOptionalList(plainSelect.getSelectItems(), () -> this, (e, v) -> e.accept(v));
```

```

**Comment by wumpz** [comment]
Could you help me to reproduce your problem? Using this test I was not able to get your behavior:

I introduced this in **SelectValidatorTest** and this test succeeds. What is different?

```java
@Test
    public void testValidateIssue1502() throws JSQLParserException {
        validateNoErrors(
                 "select b.id, name ,(select name from Blog where name = 'sadf') as name2 " +
                        ", category, owner, b.update_time " +
                        "from Blog as b " +
                        "left join Content " +
                        "ON b.id = Content.blog_id " +
                        "where name = 'sadf' order by Content.title desc",
                1, DatabaseType.POSTGRESQL);
    }
```

**Comment by qwefgh90** [comment]
@wumpz 
This problem can be reproduced when using `JdbcDatabaseMetaDataCapability`.
A following new test fails in `src/test/java/net/sf/jsqlparser/util/validation/metadata/DatabaseMetaDataValidationTest.java`.
```java
@Test
public void testValidationMetadataSelectWithColumnsAndAlias() throws JSQLParserException, SQLException {
String sql =  "select my.id from mytable as my";
JdbcDatabaseMetaDataCapability meta = new JdbcDatabaseMetaDataCapability(connection, NamesLookup.UPPERCASE);
validateNoErrors(sql, 1, DatabaseType.H2, meta); // no errors
}
```

**Comment by wumpz** [comment]
Thx for giving such help.
