### ISSUE TITLE
parse "CURRENT_TIMESTAMP(3)" error

### ISSUE THREAD

**Issue by patinousward** [JSQLParser/JSqlParser#1507]
CCJSqlParserUtil.parse("update btrip_payment set update_time =  CURRENT_TIMESTAMP(3) where id = 1");

version:4.2

![image](https://user-images.githubusercontent.com/53301480/162477725-6efa8397-d9ff-47e8-ac36-b22851a9365b.png)

**Comment by wumpz** [comment]
JSqlParser only supports `CURRENT_TIMESTAMP` without parameters. Which database supports this?

**Comment by patinousward** [comment]
> update btrip_payment set update_time = CURRENT_TIMESTAMP(3) where id = 1



> JSqlParser only supports `CURRENT_TIMESTAMP` without parameters. Which database supports this?



> JSqlParser only supports `CURRENT_TIMESTAMP` without parameters. Which database supports this?



> JSqlParser only supports `CURRENT_TIMESTAMP` without parameters. Which database supports this?



> JSqlParser only supports `CURRENT_TIMESTAMP` without parameters. Which database supports this?



> JSqlParser only supports `CURRENT_TIMESTAMP` without parameters. Which database supports this?

mysql support

**Comment by patinousward** [comment]
> JSqlParser only supports `CURRENT_TIMESTAMP` without parameters. Which database supports this?

msyql support

**Comment by patinousward** [comment]
> JSqlParser only supports `CURRENT_TIMESTAMP` without parameters. Which database supports this?

mysql support

**Comment by wumpz** [comment]
Any chance you want to provide a PR?

**Comment by manticore-projects** [comment]
Actually, it is just a Keyword problem again: When `<K_TIME_KEY_EXPR>` was explicitly allowed as Function Name, then `CURRENT_TIMESTAMP(3)` would be read as a Function and parsed properly.

The Keyword PR #1382 solves this problem.
