### ISSUE TITLE
JSQLParser Version : 4.4  hql alter table  can not be parsed

### ISSUE THREAD

**Issue by Zhumin-lv-wn** [JSQLParser/JSqlParser#1524]
**SQL Example**
- Simplyfied Query Exmple, focusing on the failing feature
```sql
 ALTER TABLE tablename add column (field  string)
```

**Software Information**
- JSqlParser version
- Database (hive )

**Comment by manticore-projects** [comment]
Greetings.

Thank you for your report. Unfortunately HIVE seems to prefer its own SQL dialect far away from the SQL Standard:
```sql
ALTER TABLE name ADD COLUMNS (col_spec[, col_spec ...])
```

Pay attention to the `COLUMNS` keyword.

Its not supported by JSQLParser and you would need to either send a PR or sponsor an implementation to make Hive support happening.

**Comment by manticore-projects** [comment]
From https://www.ibm.com/analytics/hadoop/hive: "Hive enables SQL developers to write Hive Query Language (HQL) statements that are **similar** to standard SQL statements for data query and analysis."

Emphasis is on **similar**. I

**Comment by Zhumin-lv-wn** [comment]
Has been resolved
