### ISSUE TITLE
JSQLParser 4.4 : SELECT query containing 'extended' cannot be parsed. Is 'extended' a reserved word ?

### ISSUE THREAD

**Issue by ptrussart** [JSQLParser/JSqlParser#1525]
Hi,

I'm migrating from an old 0.8 version of JSQLParser to 4.4 and I have this issue but I cannot find any documentation related to this.
Everytime I use the word 'extended' in a FROM clause or as a part of a WHERE clause, I have a JSQLParserException: Encountered unexpected token .

My question is simple is 'extended' a reserved word ? Is it a bug ?

**SQL Example**

```sql
select * from documents where extended.country = 'ES'
select * from extended
```

**Software Information**
- JSqlParser 4.4

**Comment by manticore-projects** [comment]
Greetings,

`EXTENDED` is a preserved keyword and needs to be quotes.
You can [try here online](http://jsqlformatter.manticore-projects.com/jsqlformatter/demo.html?args=-c%20MoUQMiDCAqAEBUAoAYgJQPIFlYBMD2AxgK4C2ApgHYAuAzogOoASIqIsARGQB5WU5k52AOgJ4i1AE4BPWAF5YAchDAFiANyJNoCDAQoM2Tjz4D26oA+)

**Comment by manticore-projects** [comment]
On Mon, 2022-05-02 at 06:23 -0700, ptrussart wrote:
> Can I ask you why is it preserved ? 

Because every single Define Keyword needs explicitly be allowed first -
- and this has not been done for EXTENDED.
Although there is a pending PR dealing exactly with that problem, you
may want to give that a try.

> It is not in "standard" SQL right ?

No. 

Best regards
Andreas

**Comment by ptrussart** [comment]
Thank you for your answer.
