### ISSUE TITLE
JSQLParser Version :4.4 RDBMS : mysql

### ISSUE THREAD

**Issue by siaron** [JSQLParser/JSqlParser#1529]
**Failing SQL Feature**
- Example: `SELECT username FROM users WHERE username LIKE '%' ? '%'` can't be parsed

**Comment by manticore-projects** [comment]
Greetings,

your syntax is invalid (at least on any common RDBMS).
The following statements would achieve:
```sql
SELECT username
FROM users
WHERE username LIKE '%' || ? || '%'
;


SELECT username
FROM users
WHERE username LIKE Concat( '%', ?, '%' )
;
```

**Comment by manticore-projects** [comment]
Closed, when no further question has been asked.
