### ISSUE TITLE
Failed to parse valid "SELECT" statement containing "IS NOT NULL"

### ISSUE THREAD

**Issue by nkubala** [JSQLParser/JSqlParser#153]
I'm trying to do some simple table parsing in SELECT statements using `CCJSqlParserUtil.parse(sql)`; however, when I qualify a column name with "IS NOT NULL", I get the following exception: 

`Encountered " "IS" "IS "" at line 1, column 366.`

An example of the SQL that gives me this error:

`SELECT DISTINCT l.id, l.exchanged_line_item_id IS NOT NULL AS exchanged JOIN orders AS o ON l.order_id = o.id WHERE o.uuid = ?`

Stack Trace:

```
	at net.sf.jsqlparser.parser.CCJSqlParser.generateParseException(CCJSqlParser.java:9257)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_consume_token(CCJSqlParser.java:9130)
	at net.sf.jsqlparser.parser.CCJSqlParser.Statement(CCJSqlParser.java:63)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:49)
```

**Comment by wumpz** [comment]
Column names with white spaces have to be in quotation marks. This is not a valid SQL you try to parse. Therfore JsqlParser does not accept it or parse it. Try something like select mytable."col not is null" as accepted from ... cheers Tobias

**Comment by nkubala** [comment]
Thanks for the quick reply Tobias.

This is valid SQL syntax, since MySQL allows selecting (from any field) a boolean that dictates whether the particular field is null, rather than the actual value contained within the field itself. It is equivalent to selecting the value, and then performing a null check on it; but in one step.

Including the `IS NOT NULL` within the quotations marks allows it to be parsed properly by JSQLParser....but the query is then rejected by MySQL, since it is now looking for a column called `exchanged_line_item_id IS NOT NULL` in the table.

**Comment by wumpz** [comment]
Understand. It is kind of a condition you select. You are right, Jsqlparsee does not support this kind of expression.  As a work around you could use a case when. Tobias

**Comment by nkubala** [comment]
No worries, I'm just filtering them out in my code before parsing. Thanks

**Comment by wumpz** [comment]
So could we close this one for now?

**Comment by nkubala** [comment]
well I still think it's an issue with the parser (it probably thinks the `IS NOT NULL` is part of the column name), but it's pretty easy to work around. so I'll close it for now. I may try and fix it myself later on if I can get around to it :)
