### ISSUE TITLE
Encountered unexpected token: "(" "("

### ISSUE THREAD

**Issue by zhoubin7** [JSQLParser/JSqlParser#1530]
SELECT
	sum(CASE WHEN pcr.pcall_times MOD 60 = 0 THEN
		pcr.pcall_times ELSE ( FLOOR( pcr.pcall_times / 60 ) + 1 ) * 60 
		END  ) AS 'call_times',
		sum( pcall_times ) AS 'actual_call_times' 
	FROM
		t_phone_call_record AS pcr 
WHERE
	pcall_times > 0

Caused by: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "(" "("
    at line 2, column 17.

Was expecting one of:

    "&"
    ")"
    "::"
    "<<"
    ">>"
    "COLLATE"
    "["
    "^"
    "|"

**Comment by manticore-projects** [comment]
Greetings.

The keyword `MOD` is not allowed/supported in this context. Without it, your statement works:
```sql
SELECT  Sum( CASE
                WHEN pcr.pcall_times % 60 = 0
                    THEN pcr.pcall_times
                ELSE ( Floor( pcr.pcall_times / 60 ) + 1 ) * 60
            END ) AS 'call_times'
        , Sum( pcall_times ) AS 'actual_call_times'
FROM t_phone_call_record AS pcr
WHERE pcall_times > 0
;
```

What RDBMS is using `MOD` as Modulus Operator please?

**Comment by zhoubin7** [comment]
> 问候。
> 
> `MOD`在此上下文中不允许/支持该关键字。没有它，您的陈述有效：
> 
> ```sql
> SELECT   Sum (CASE 
>                 WHEN pcr . pcall_times % 60  =  0 
>                     THEN pcr . pcall_times 
>                 ELSE ( Floor( pcr . pcall_times  /  60 ) +  1 ) *  60 
>             END ) AS  ' call_times ' 
>         , Sum ( pcall_times ) AS  ' actual_call_times '
>  FROM t_phone_call_record AS pcr
> 在哪里pcall_times >  0 
> ;
> ```
> 
> 请问什么 RDBMS`MOD`用作模运算符？我发现它只是一个功能`Mod()`，它可以工作。

Thank you very much for heThank you very much for helping me solve this disaster

**Comment by manticore-projects** [comment]
Welcome, cheers.
