### ISSUE TITLE
travis-ci stopped working for this repository, still credits available

### ISSUE THREAD

**Issue by wumpz** [JSQLParser/JSqlParser#1536]
* maybe move to github actions (compare)

**Comment by wumpz** [comment]
GitHub actions activated. We will closely look which one performs better.

**Comment by manticore-projects** [comment]
On Mon, 2022-05-16 at 02:35 -0700, Tobias wrote:
> GitHub actions activated. We will closely look which one performs
> better.

I can confirm, that this works (using Maven).
Well done!
