### ISSUE TITLE
Encountered unexpected token: "with" "WITH"

### ISSUE THREAD

**Issue by zhipengfu1** [JSQLParser/JSqlParser#1537]
version: 4.2

sql: (with a as (select 1 from dual) select * from a)

error info:
net.sf.jsqlparser.JSQLParserException: Encountered unexpected token: "with" "WITH"
    at line 1, column 2.
Was expecting one of:
    "("
    "VALUES"
    <K_SELECT>
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parseStatement(CCJSqlParserUtil.java:190)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:63)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:38)

how can i resolve this problem

**Comment by wumpz** [comment]
You are lucky. Recently this was solved in JSqlParser 4.5-SNAPSHOT. A release is not yet available, however, I deployed the snapshot, so you can test it.

**Comment by zhipengfu1** [comment]
> You are lucky. Recently this was solved in JSqlParser 4.5-SNAPSHOT. A release is not yet available, however, I deployed the snapshot, so you can test it.

thanks for your reply ,expect 4.5 version

**Comment by manticore-projects** [comment]
Solved.
