### ISSUE TITLE
begin end

### ISSUE THREAD

**Issue by DexterPoker** [JSQLParser/JSqlParser#1540]
https://github.com/JSQLParser/JSqlParser/blob/6cff161dacc1e6feeccce709ca08220e576836be/src/main/java/net/sf/jsqlparser/statement/Block.java#L31

in oracle 19c
‘begin end;‘ its needs the semicolon otherwise oracle showed the error code “pls-00103”.
Is there an option to provide.

**Comment by manticore-projects** [comment]
Greetings!

Thanks for the information, I would implement this accordingly.

**Comment by manticore-projects** [comment]
Closed, since no further question has been asked.
