### ISSUE TITLE
Encountered unexpected token: "not" "NOT"

### ISSUE THREAD

**Issue by zhoubin7** [JSQLParser/JSqlParser#1542]
SELECT
         
        o.id,
        o.create_time,
        o.update_time,
        o.trade_time,
        o.version,
        o.order_sn,
        o.order_type,
        o.price,
        o.fee,
        o.tax,
        o.promotion_discount,
        o.coupon_discount,
        o.offset_amount,
        o.order_amount,
        o.amount_paid,
        o.refund_amount,
        o.quantity,
        o.memo,
        o.expire,
        o.is_use_coupon,
        o.is_allocated_stock,
        o.pay_type,
        o.member_id,
        o.delete_state,
        o.complate_date,
        o.order_state,
        o.lock_state,
        o.shipping_type,
        o.invoice,
        o.promotion_names,
        o.order_delivery_state,
        o.shipped_quantity,
        o.shipping_method_id,
        o.freight,
        o.receiver_name,
        INSERT (o.receiver_phone,4,4,'****') as 'receiverPhone',
        o.receiver_province,
        o.receiver_city,
        o.receiver_region,
        o.receiver_detail_address,
        o.area_id,
        o.review_state,
        o.return_state,
        o.evaluation_state,
        o.refund_state,
        o.pay_method,
        o.pay_method_name,
        o.pay_type_name,
        o.returned_quantity,
        o.reward_point,
        o.exchange_point,
        o.is_exchange_point,
        o.parent_id,
        o.coupon_code_id,
        o.warehouse_id,
        o.is_sync_courier,
        o.is_after_sales,
        o.wechat_id,
        o.sys_user_id,
        o.is_initiate_block,
        o.recommender_id
     
        FROM
        t_orders o
         WHERE 1=1
        AND o.delete_state=0
        
        
            and o.order_type not in (SELECT CONVERT(dict_value, UNSIGNED INTEGER) FROM sys_dict_data WHERE dict_type = 'order_type_filter_distributor') 
        order by o.id desc

Caused by: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "not" "NOT"
    at line 71, column 30.

Was expecting one of:

    "&"
    "::"
    ";"
    "<<"
    ">>"
    "COLLATE"
    "CONNECT"
    "EMIT"
    "GROUP"
    "HAVING"
    "START"
    "["
    "^"
    "|"
    <EOF>

**Comment by manticore-projects** [comment]
Greetings.

This term is not supported:
```sql
INSERT (o.receiver_phone,4,4,'****') as 'receiverPhone'
```

**Comment by zhoubin7** [comment]
> 问候。
> 
> 不支持此术语：
> 
> ```sql
> INSERT (o.receiver_phone,4,4,'****') as 'receiverPhone'
> ```
I'm sure there's something wrong here

`and o.order_type not in (SELECT CONVERT(dict_value, UNSIGNED INTEGER) FROM sys_dict_data WHERE dict_type = 'order_type_filter_distributor')`

Can't nested functions parse??

**Comment by manticore-projects** [comment]
Greetings.

Nested functions are supported, although `UNSIGNED INTEGER` is not.
You can play with your statement [online and interactively here](http://jsqlformatter.manticore-projects.com/jsqlformatter/demo.html?args=-c%20MoUQMiDCAqAEsHsB0BLAJgKHt7AaRSAxgE4CmAhgC6kD6lKAtqVjngQK4AOaVt9TLVrHzJKxcmj6NmQ+CKQA3UsQDOKBADtBreQmKTiNFVtnCCeg3QCenGbPmdiKQnaHyAZqVc6ClcgA9tHAdiBAYEek0aNBQVQgR2DUogtmR4riiYuISklLlzd3cVUkoacnDE5NNdfWUyitzqgnKc0s5ydDyzZDJ3RLR61q75AEd2ciSUSithgiZw2eRSf04UMkXUFRp2Ypp0zk0N2LKAGxOEQl4BlUoLgGsN9qtrWw35gCM6zqbkSROS2g3XgbeIMTgnXjRYE-JAWOpA6gbc6EO5GPyImEqAAWKE4qw0AHMXt5ggQUBoFAhnCTUkhHGEIuoNDQNOVSCoNnDDH8UEpiM8ETT8shsbjbAMxhN6NMNqK8eSiUxKFiEANvvYCO4yCgCViqhqeqQXLy6qyBE0APQAKlgAEkAHKgABKcAAFIbjXyaJwVRpSLgACyB3AAcit4atIYAlLByCpYCGyJ7lAAFX2kEP4K0WghJ0gmwz0hTklwbPMFvZTGYw8tesgEpllo35r2SPwoE5lNBoMgqDkw8hkcg0dVuXOkYukADuaOhBqQZEo7GIzMFGwn5BO40iq-RQu6C9IfQ01z3j3IzyVKswMKeNCvqpZbPPz2mtif5vni+Xfol40mMo1tOg4DAc5L6mOSz+IQWITAStBgY087HMsMFwQhVJIZBdKDqQSQjje877FE8SSARGxTrhKo7LQo4+MgxwqFYGiEHsCROMoRxbOQ7jUIYKibuyFFGrBpR0aSIpWFsNGGOJtLHOSUwoJC7zIg8QGgkwJ5fJgABiToAPIALKwKUXLxggGAAOoABIgE6ICwAAjLAAC8znaAAgvaAAiBB-ACs7UG5sAAAxeb55i1IYb6kLA9oGXADqwK62CgBAMCwJAmh8pQqUxIQpQKJu7D+rA1oAKqOraADi9ogD52awOBpDwcQsBRl0pjdbI+nGbATFbAVpQ8H4XU9RN8C2fZjnDcSIUhlyxI0O4HZ8dEsRiCg7zsLcxAhh1GAGU6Pn2bAABCACaZJoLAp3AJAGAANwYK96VQHA2UUsoeWwHNxVbmVLVtYdfUmYNG2FVCY3TQ5f3OKUsULUtsUrWtdRZFtO17SGz1AA+).

I have commented out the unsupported parts.

**Comment by zhoubin7** [comment]
> 问候。
> 
> 支持嵌套函数，但`UNSIGNED INTEGER`不支持。[您可以在此处以在线方式和交互](http://jsqlformatter.manticore-projects.com/jsqlformatter/demo.html?args=-c%20MoUQMiDCAqAEsHsB0BLAJgKHt7AaRSAxgE4CmAhgC6kD6lKAtqVjngQK4AOaVt9TLVrHzJKxcmj6NmQ+CKQA3UsQDOKBADtBreQmKTiNFVtnCCeg3QCenGbPmdiKQnaHyAZqVc6ClcgA9tHAdiBAYEek0aNBQVQgR2DUogtmR4riiYuISklLlzd3cVUkoacnDE5NNdfWUyitzqgnKc0s5ydDyzZDJ3RLR61q75AEd2ciSUSithgiZw2eRSf04UMkXUFRp2Ypp0zk0N2LKAGxOEQl4BlUoLgGsN9qtrWw35gCM6zqbkSROS2g3XgbeIMTgnXjRYE-JAWOpA6gbc6EO5GPyImEqAAWKE4qw0AHMXt5ggQUBoFAhnCTUkhHGEIuoNDQNOVSCoNnDDH8UEpiM8ETT8shsbjbAMxhN6NMNqK8eSiUxKFiEANvvYCO4yCgCViqhqeqQXLy6qyBE0APQAKlgAEkAHKgABKcAAFIbjXyaJwVRpSLgACyB3AAcit4atIYAlLByCpYCGyJ7lAAFX2kEP4K0WghJ0gmwz0hTklwbPMFvZTGYw8tesgEpllo35r2SPwoE5lNBoMgqDkw8hkcg0dVuXOkYukADuaOhBqQZEo7GIzMFGwn5BO40iq-RQu6C9IfQ01z3j3IzyVKswMKeNCvqpZbPPz2mtif5vni+Xfol40mMo1tOg4DAc5L6mOSz+IQWITAStBgY087HMsMFwQhVJIZBdKDqQSQjje877FE8SSARGxTrhKo7LQo4+MgxwqFYGiEHsCROMoRxbOQ7jUIYKibuyFFGrBpR0aSIpWFsNGGOJtLHOSUwoJC7zIg8QGgkwJ5fJgABiToAPIALKwKUXLxggGAAOoABIgE6ICwAAjLAAC8znaAAgvaAAiBB-ACs7UG5sAAAxeb55i1IYb6kLA9oGXADqwK62CgBAMCwJAmh8pQqUxIQpQKJu7D+rA1oAKqOraADi9ogD52awOBpDwcQsBRl0pjdbI+nGbATFbAVpQ8H4XU9RN8C2fZjnDcSIUhlyxI0O4HZ8dEsRiCg7zsLcxAhh1GAGU6Pn2bAABCACaZJoLAp3AJAGAANwYK96VQHA2UUsoeWwHNxVbmVLVtYdfUmYNG2FVCY3TQ5f3OKUsULUtsUrWtdRZFtO17SGz1AA+) 方式玩弄您的陈述。[](http://jsqlformatter.manticore-projects.com/jsqlformatter/demo.html?args=-c%20MoUQMiDCAqAEsHsB0BLAJgKHt7AaRSAxgE4CmAhgC6kD6lKAtqVjngQK4AOaVt9TLVrHzJKxcmj6NmQ+CKQA3UsQDOKBADtBreQmKTiNFVtnCCeg3QCenGbPmdiKQnaHyAZqVc6ClcgA9tHAdiBAYEek0aNBQVQgR2DUogtmR4riiYuISklLlzd3cVUkoacnDE5NNdfWUyitzqgnKc0s5ydDyzZDJ3RLR61q75AEd2ciSUSithgiZw2eRSf04UMkXUFRp2Ypp0zk0N2LKAGxOEQl4BlUoLgGsN9qtrWw35gCM6zqbkSROS2g3XgbeIMTgnXjRYE-JAWOpA6gbc6EO5GPyImEqAAWKE4qw0AHMXt5ggQUBoFAhnCTUkhHGEIuoNDQNOVSCoNnDDH8UEpiM8ETT8shsbjbAMxhN6NMNqK8eSiUxKFiEANvvYCO4yCgCViqhqeqQXLy6qyBE0APQAKlgAEkAHKgABKcAAFIbjXyaJwVRpSLgACyB3AAcit4atIYAlLByCpYCGyJ7lAAFX2kEP4K0WghJ0gmwz0hTklwbPMFvZTGYw8tesgEpllo35r2SPwoE5lNBoMgqDkw8hkcg0dVuXOkYukADuaOhBqQZEo7GIzMFGwn5BO40iq-RQu6C9IfQ01z3j3IzyVKswMKeNCvqpZbPPz2mtif5vni+Xfol40mMo1tOg4DAc5L6mOSz+IQWITAStBgY087HMsMFwQhVJIZBdKDqQSQjje877FE8SSARGxTrhKo7LQo4+MgxwqFYGiEHsCROMoRxbOQ7jUIYKibuyFFGrBpR0aSIpWFsNGGOJtLHOSUwoJC7zIg8QGgkwJ5fJgABiToAPIALKwKUXLxggGAAOoABIgE6ICwAAjLAAC8znaAAgvaAAiBB-ACs7UG5sAAAxeb55i1IYb6kLA9oGXADqwK62CgBAMCwJAmh8pQqUxIQpQKJu7D+rA1oAKqOraADi9ogD52awOBpDwcQsBRl0pjdbI+nGbATFbAVpQ8H4XU9RN8C2fZjnDcSIUhlyxI0O4HZ8dEsRiCg7zsLcxAhh1GAGU6Pn2bAABCACaZJoLAp3AJAGAANwYK96VQHA2UUsoeWwHNxVbmVLVtYdfUmYNG2FVCY3TQ5f3OKUsULUtsUrWtdRZFtO17SGz1AA+)
> 
> 我已经注释掉了不受支持的部分。

Thanks
