### ISSUE TITLE
Any recommended projects for NodeJS / JavaScript

### ISSUE THREAD

**Issue by rathboma** [JSQLParser/JSqlParser#1544]
Hey folks,

I maintain [Beekeeper Studio](/beekeeper-studio/beekeeper-studio), which is built in Electron using JavaScript.

I'd love to use this powerful SQL parser, but unfortunately I don't have Java available to me (unless I jump through some nasty hoops).

Does anyone know of a translation of this project to JavaScript, or a JavaScript library with similar functionality? I currently help maintain [Sql Query Identifier](https://github.com/sqlectron/sql-query-identifier), but it really needs to be rebuilt as a 'real' parser.

My last resort is to rewrite the library in TypeScript :scream:, but that sounds terrible!

**Comment by manticore-projects** [comment]
Greetings!

JSQLParser is Java 8 -- so in theory you could try to compile/translate it to JS or WebAssembly using TeaVM. I have not tried that though. 

This looks also good: https://github.com/i-net-software/JWebAssembly
