### ISSUE TITLE
Share/deploy the Auto Generated Sources on top of the Actual Sources

### ISSUE THREAD

**Issue by manticore-projects** [JSQLParser/JSqlParser#1546]
https://github.com/i-net-software/JWebAssembly/issues/43 refers.

How can we share the auto-generated Sources?

**Comment by wumpz** [comment]
Within jsqlparser-4.5-SNAPSHOT-sources.jar all sources are collected. This file is available at maven as well: https://repo1.maven.org/maven2/com/github/jsqlparser/jsqlparser/4.4/jsqlparser-4.4-sources.jar.

**Comment by manticore-projects** [comment]
Indeed, the Maven Build contains it, while the Gradle build does not. I have to check out the Gradle build and add the generated Sources there.
