### ISSUE TITLE
Parse extra blank character when parse to Select

### ISSUE THREAD

**Issue by Betternan** [JSQLParser/JSqlParser#1547]
String sql = 
```
"SELECT TO_CHAR(date,'YYYY-MM-DD'), sum(total)  group by TO_CHAR(date,'YYYY-MM-DD')"
```

After parsing: **Select select = (Select) CCJSqlParserUtil.parse(sql)**;

I found the PlainSelect is changed with **extra blank** between two parameters in the **TO_CHAR** function:
```
SELECT TO_CHAR(date, 'YYYY-MM-DD'), sum(total)  group by TO_CHAR(date, 'YYYY-MM-DD')
```
So is there any way to avoid this **extra blank** after parsing, and just keep the original String?

**Comment by manticore-projects** [comment]
Greetings.

Thank you for reporting. Three thoughts:

1) JSQLParser is a PARSER at first -- and yes, the De-Parser can slightly differ from the original statement. It is NOT meant to produce char-wise the exact statement, only the same grammar/keywords and context.
(Strictly speaking, there are even 1 or 2 occurrences where the Grammar itself is modified regarding deprecated keywords.)

2) In your particular case though, it can be changed/fixed.

3) You can try `toString()` vs the `SELECT Deparser`, it is even possible that the extra white-space shows only in one variant.

**Comment by manticore-projects** [comment]
On a side note: If you look for a strict formatting (considering the extra whitespace an error), then [JSQLFormatter](https://github.com/manticore-projects/jsqlformatter) based on JSQLParser might be an option. I am the author of that Formatter.
