### ISSUE TITLE
SqlTranslator#call does not pass true for all column for functions starting 4.3.

### ISSUE THREAD

**Issue by FCsean** [JSQLParser/JSqlParser#1548]
The actual call done is now `sqlTranslator.call("f", false, false, "*")`.

This was working pre-4.3. 

May check with the following test.

```java
@InjectMocks
private SqlTranslatingSqlTransformer cut;

@Mock
private SqlTranslator sqlTranslator;

@Test
void shouldIndicateAllColumnsWhenTransformingFunction() {
  cut.transformSql("select f(*) from t");
  then(sqlTranslator).should().call(eq("f"), anyBoolean(), eq(true), any());
}
```

**Comment by manticore-projects** [comment]
Greetings!

Unfortunately, I am totally lost on what challenge you are facing exactly. Please elaborate on:
1) Your observation vs.
2) Your expectation with
3) a self containing example (I have no idea what SqlTranslator you are referring to).

That said, the `ALL Column` interpretation of `*` has been changed between 4.3 and now. It has been moved to is own Expression. Maybe your challenge is related to this refactoring.

**Comment by FCsean** [comment]
Sorry, mixed up my code. Created a test to align the expected case.

The following test passes prior to version 4.3. On 4.3 and above it now fails.
```java
@Test
void shouldSetAllColumnsToTrue() throws Exception {
  JSqlParser jSqlParser = new CCJSqlParserManager();
  try (Reader statementReader = new StringReader("select f(*) from t")) {
    Statement parse = jSqlParser.parse(statementReader);
    StringBuilder builder = new StringBuilder();
    parse.accept(new StatementDeParser(new ExpressionDeParser() {
      @Override
      public void visit(Function function) {
        super.visit(function);
        Assertions.assertEquals(true, function.isAllColumns());
      }
    }, new SelectDeParser(), builder));
  }
}
```

**Comment by manticore-projects** [comment]
`function.isAllColumns()` <-- This one.

It will likely show an Expression `AllColumn` now.

**Comment by FCsean** [comment]
Hmm, I'm confused.

Based on [Function.java](https://github.com/JSQLParser/JSqlParser/blob/fc5a9a3dbb91e8e77122f953c2f29c0e028479d1/src/main/java/net/sf/jsqlparser/expression/Function.java#L64), it's still returning a boolean.
```java


    public boolean isAllColumns() {
        return allColumns;
    }

    public void setAllColumns(boolean b) {
        allColumns = b;
    }
```

Or do you mean I should use the following method instead?
[ExpressionDeParser](https://github.com/JSQLParser/JSqlParser/blob/fc5a9a3dbb91e8e77122f953c2f29c0e028479d1/src/main/java/net/sf/jsqlparser/util/deparser/ExpressionDeParser.java#L980)
```java
    @Override
    public void visit(AllColumns allColumns) {
        buffer.append(allColumns.toString());
    }
```

I find it weird that `Function#isAllColumns` is not marked as deprecated or removed if it's not expected to be used anymore though.

**Comment by manticore-projects** [comment]
On Tue, 2022-05-31 at 01:22 -0700, FCsean wrote:
> Or do you mean I should use the following method instead?
> ExpressionDeParser
>     @Override
>     public void visit(AllColumns allColumns) {
>         buffer.append(allColumns.toString());
>     }

Yes.

> I find it weird that Function#isAllColumns is not marked as
> deprecated or removed if it's not expected to be used anymore though.

Yes, and I am going to improve that today.
Backward compatibility can and should be maintained here.

Cheers

**Comment by manticore-projects** [comment]
```java
@Test
    void shouldSetAllColumnsToTrue() throws Exception {
        JSqlParser jSqlParser = new CCJSqlParserManager();
        try (Reader statementReader = new StringReader("select f(*) from t")) {
            Statement parse = jSqlParser.parse(statementReader);
            StringBuilder builder = new StringBuilder();
            parse.accept(new StatementDeParser(new ExpressionDeParser() {
                @Override
                public void visit(Function function) {
                    super.visit(function);

                    // this is deprecated, please do not use it
                    Assertions.assertEquals(true, function.isAllColumns());

                    // this is the correct way since JSQLParser 4.4
                    Assertions.assertEquals(true, function.getParameters().getExpressions().get(0) instanceof AllColumns);
                }
            }, new SelectDeParser(), builder));
        }
    }
```

Cheers!

**Comment by manticore-projects** [comment]
Sorry, I think there is a major misunderstanding here:

```sql
select f(*) from t
```
--> Function.isAllColumns() should return FALSE, but the first Parameter should be of the Type `AllColumn`

```sql
SELECT count(ALL col1 + col2) FROM mytable
```
--> Function.isAllColumns() should return True

**Comment by manticore-projects** [comment]
I have honestly no idea, how/why you test succeeded prior 4.3.
However, the correct test would be
```java
    @Test
    void shouldSetAllColumnsToTrue() throws Exception {
        JSqlParser jSqlParser = new CCJSqlParserManager();
        try (Reader statementReader = new StringReader("select f(*) from t")) {
            Statement parse = jSqlParser.parse(statementReader);
            StringBuilder builder = new StringBuilder();
            parse.accept(new StatementDeParser(new ExpressionDeParser() {
                @Override
                public void visit(Function function) {
                    super.visit(function);

                    // Function.isAllColumns() refers to the ALL keyword in: Count(ALL *)
                    Assertions.assertFalse(function.isAllColumns());

                    // this is the correct way since JSQLParser 4.4
                    Assertions.assertTrue(function.getParameters().getExpressions().get(0) instanceof AllColumns);
                }
            }, new SelectDeParser(), builder));
        }
    }
```

Sorry for the mess, I got very confused by myself.

**Comment by FCsean** [comment]
I see, thank you very much, that clears it. It's confusing since they have the same name.

To clarify though, prior to 4.4, what would be the code counterpart for 
`function.getParameters().getExpressions().get(0) instanceof AllColumns`?

Thanks!
