### ISSUE TITLE
 when incondition is a subselect that can't prase

### ISSUE THREAD

**Issue by afuchrisma** [JSQLParser/JSqlParser#1555]
forexample  
SELECT t.* from  order_test t
	WHERE t.amount in ((select max(amount) from order_test),(select min(amount) from order_test))
	
when use CCJSqlParserUtil.parse method that can‘t prase

**Comment by manticore-projects** [comment]
Greetings.

Please try a recent version of JSQLParser.
Your statement parses just fine with JSQLParser 4.4 and you can [try it online here.](http://jsqlformatter.manticore-projects.com/jsqlformatter/demo.html?args=-c%20MoUQMiDCAqAEAuA6AVAKAGICUDyBZWA9gE4AmApkQPrxkDO8CqA6gBIiYgKICGAtgQFcAdgwCSAOVgAKabDmgIMWLm4APGX0EjYASlRyDho8cNY8hUhWp0GOgDSyDCqHFwBLIRv7Db+k-4DAoLkzfGJyKhp6XV1UAG4gA+)

```sql
SELECT t.*
FROM order_test t
WHERE t.amount IN ( (   SELECT Max( amount )
                        FROM order_test ), (    SELECT Min( amount )
                                                FROM order_test ) )
;
```

**Comment by afuchrisma** [comment]
thanks~  It's working
