### ISSUE TITLE
JSQLParser 4.2 up to 4.4 hava a problem

### ISSUE THREAD

**Issue by afuchrisma** [JSQLParser/JSqlParser#1556]
hi~
 JSQLParser 4.2 up to 4.4 vesion,  I have a problem，net.sf.jsqlparser.expression.Function  toString method
 When the database dialect is MySQL，when i want to assemble SQL totalcount , there are some differences,  as shown in the picture 
<img width="761" alt="图片" src="https://user-images.githubusercontent.com/17420690/172329042-bcfa3340-4f93-4ff0-9b34-9347838ea95c.png">
How can I solve this problem  give me some advice

**Comment by amigalev** [comment]
@afuchrisma 

In my case I've changed the code snipped

```
Function countExpression = new Function();
countExpression.setName("count");
countExpression.setAllColumns(true);
```

 To this one:

``` 
Function countExpression = new Function();
countExpression.setName("count");
countExpression.setParameters(new ExpressionList(new AllColumns()));
```

Hope it will help

**Comment by manticore-projects** [comment]
Greetings,

we have changed `*` from a Function property into an Expression `AllColumns`, which also supports Table References, e.g. `f( a.* )`.

Just access the Function's parameters and set or get the Expression of each parameter and test for `AllColumns` Expression.

**Comment by manticore-projects** [comment]
Closed, since no further questions asked.
