### ISSUE TITLE
Support for Oracle "MERGE INTO ... " statement

### ISSUE THREAD

**Issue by itwise-yjyoon** [JSQLParser/JSqlParser#156]
## Using jsqlparser version
0.9.3

## Query
MERGE INTO bonuses B
USING (
  SELECT employee_id, salary
  FROM employee
  WHERE dept_no =20) E
ON (B.employee_id = E.employee_id)
WHEN MATCHED THEN
  UPDATE SET B.bonus = E.salary * 0.1
WHEN NOT MATCHED THEN
  INSERT (B.employee_id, B.bonus)
  VALUES (E.employee_id, E.salary * 0.05)  

## Test suite
    @Test
    public void testOracleMergeIntoStatement() throws JSQLParserException {
        String sql = "MERGE INTO bonuses B\n" +
                "USING (\n" +
                "  SELECT employee_id, salary\n" +
                "  FROM employee\n" +
                "  WHERE dept_no =20) E\n" +
                "ON (B.employee_id = E.employee_id)\n" +
                "WHEN MATCHED THEN\n" +
                "  UPDATE SET B.bonus = E.salary * 0.1\n" +
                "WHEN NOT MATCHED THEN\n" +
                "  INSERT (B.employee_id, B.bonus)\n" +
                "  VALUES (E.employee_id, E.salary * 0.05)  ";

        Statement statement = CCJSqlParserUtil.parse(sql);
    }

## Exception Message
Caused by:
net.sf.jsqlparser.parser.ParseException: Encountered " <S_IDENTIFIER> "MERGE "" at line 1, column 1.
Was expecting one of:
    "SET" ...
    "DROP" ...
    "WITH" ...
    "DELETE" ...
    "SELECT" ...
    "INSERT" ...
    "UPDATE" ...
    "REPLACE" ...
    "TRUNCATE" ...
    "ALTER" ...
    "EXEC" ...
    "EXECUTE" ...
    "(" ...

**Comment by wumpz** [comment]
Merge is at the moment not supported. But I will look into it.

**Comment by itwise-yjyoon** [comment]
Thank you for your consideration :+1: 
I hope to show the paradise :)

**Comment by wumpz** [comment]
Implementation in progress .. ;) look at branch merge-impl. This parses already but does not store all values.

**Comment by wumpz** [comment]
Could you check the first implementation?
