### ISSUE TITLE
new StringValue("'") error

### ISSUE THREAD

**Issue by YesNoBut** [JSQLParser/JSqlParser#1566]
use new StringValue("'")  with version 4.4
Exception in thread "main" java.lang.StringIndexOutOfBoundsException: String index out of range: -1

**Comment by manticore-projects** [comment]
Greetings.

You will need to provide much more information, about what you are trying to achieve, what has been observed and what was expected.

**Comment by YesNoBut** [comment]
I use version 4.4

I want to convert the data queried from the database into an insert statement through  `StringValue`.

If the data in the database is ', `new StringValue` will report an error exception. The exception information is: java lang.StringIndexOutOfBoundsException: String index out of range: -1。

I read the source code and found a problem:
`if (escapedValue.startsWith("'") && escapedValue.endsWith("'")) {`
`    value = escapedValue.substring(1, escapedValue.length() - 1);`
`    return;`
`}`

I want the final effect to be that SQL statements can be produced normally.

**Comment by manticore-projects** [comment]
```java
if (escapedValue.startsWith("'") && escapedValue.endsWith("'")) {
value = escapedValue.substring(1, escapedValue.length() - 1);
return;
}
```

Thank you for the hint and finding. We will fix that of course,

**Comment by wumpz** [comment]
Could you test the behaviour. Is it now like you expected it?

**Comment by YesNoBut** [comment]
Great, the problem has been solved.
