### ISSUE TITLE
I suggest to support oracle procedure

### ISSUE THREAD

**Issue by cooloong** [JSQLParser/JSqlParser#157]
Any plan to add procedure support in jsqlparser?
Procedure may use 'declare', 'cursor',,'begin end' 'Loop','open cursor', 'Pipe line','Varray', 'ROWTYPE' and so on.

**Comment by wumpz** [comment]
No plans so far. The differences for specific databases (Oracle, SqlServer, PostgreSQL, ...) are so huge and this is not SQL anymore, it would be a programming language parser. Anyway, why would you need it? Tobias
