### ISSUE TITLE
The ->> operation in postgresql does not work properly

### ISSUE THREAD

**Issue by offSwitch** [JSQLParser/JSqlParser#1571]
select visit_hour,json_array_elements(into_sex_json)->>'name',json_array_elements(into_sex_json)->>'value' from period_market

**Comment by wumpz** [comment]
The problem here is that JSqlParser does only support:

column ->> literal

a function as a first "parameter" is not supported. Something you want to provide. PRs are welcome.

**Comment by yasu1209** [comment]
I'm using the latest version 4.6 and this problem seems not solved yet.
Would it be possible to be fixed in the future?

**Comment by manticore-projects** [comment]
Unfortunately, allowing `Function()` is not possible as it will break performance reason. I think, this one is beyond any refactoring and tricks. A new and clean Grammar would be needed to achieve that.

**Comment by yasu1209** [comment]
> Unfortunately, allowing `Function()` is not possible as it will break performance reason. I think, this one is beyond any refactoring and tricks. A new and clean Grammar would be needed to achieve that.

Thank you for your reply. 
I'll check my code to see if it can be refactored.

**Comment by manticore-projects** [comment]
PR  #1745 allows `Function() --> Literal` as long as the Function is simple (no nested expressions as parameters).
