### ISSUE TITLE
Get Table Object List instead of full qualified table name list from a statement

### ISSUE THREAD

**Issue by detienneZN** [JSQLParser/JSqlParser#1574]
TablesNamesFinder class allows us  to retrieve tables names from a statement with the getTableList method.

For our needs, we would like to get directly table object List instead of full qualified table name list, in order to get name and schema separately.
For instance with the following method  : public List < Table > getTables(Statement statement)

Is it possible to add this feature to the TablesNamesFinder or another way ?

Actually I created a TableFinder class inheriting from TablesNamesFinder, like following, but I think it's not the best way : 

`

> public class TableFinder extends TablesNamesFinder {
> 
>   private Map<String, Table> tables;
> 
>   public TableFinder() {
>     tables = new HashMap<>();
>   }
> 
>   @Override
>   public List<String> getTableList(Statement statement) {
>     return super.getTableList(statement);
>   }
> 
>   public @NotNull List < Table > getTables(Statement statement) {
>     final List<String> tableNames = getTableList(statement);
>     return (tableNames != null) ? tableNames.stream().map(key -> tables.get(key)).collect(Collectors.toList()) : Collections.emptyList();
>   }
> 
>   @Override
>   public void visit(Table table) {
>     super.visit(table);
>     tables.put(table.getFullyQualifiedName(), table);
>   }
> }

`

**Comment by wumpz** [comment]
TableNamesFinder uses its method:

```java
protected String extractTableName(Table table) { ... }
```

to extract the needed table name format. This method is called for every found `Table` object. Therefore you could override this method to collect the `Table` objects into a list.

**Comment by manticore-projects** [comment]
Closed, since no further questions asked.
