### ISSUE TITLE
parameter yyyy recgonize as column in datepart function

### ISSUE THREAD

**Issue by xiaowoniuxixi** [JSQLParser/JSqlParser#1578]
String sql= SELECT DATEPART(yyyy,TB_4537."fetch_date");

Statement sqlStmt = CCJSqlParserUtil.parse(new StringReader(sql));

debug result is :  yyyy is a column, it should as StringValue

ps： database is sqlserver

**Comment by manticore-projects** [comment]
Greetings.

If you will want a `StringValue` you will need to provide a single quoted String, e.g.:
```sql
SELECT DATEPART('yyyy',TB_4537."fetch_date");
```

There is no support for any RDBMS specific constants like `yyyy` may be on SQL Server.

**Comment by manticore-projects** [comment]
This is very possible, but also far away from any standard or common approach. We do not claim to be a MS-SQLServer/T-SQL Parser.
You are welcome though to submit a code change.
