### ISSUE TITLE
Postgresql "ANALYZE table" not supported?

### ISSUE THREAD

**Issue by d2a-raudenaerde** [JSQLParser/JSqlParser#1579]
I'm trying to parse a sql-script with multiple statements, and some statements are `analyze sometable` statements. These are not recognized by the parser?

See for the syntax:
https://www.postgresql.org/docs/current/sql-analyze.html

Simple test:

            CCJSqlParser parser = newParser("analyze table1");
            parser.withAllowComplexParsing(true);
            for (Statement st :parser.Statements().getStatements())
            {
                System.out.println(st);
            }

**Comment by wumpz** [comment]
Thats right. JSqlParser does not know this. PRs are welcome.

**Comment by d2a-raudenaerde** [comment]
Working on it :)
