### ISSUE TITLE
Postgresql named window support: FROM ... WINDOW name support

### ISSUE THREAD

**Issue by d2a-raudenaerde** [JSQLParser/JSqlParser#1581]
See: https://www.postgresql.org/docs/current/tutorial-window.html

```
SELECT sum(salary) OVER w, avg(salary) OVER w
  FROM empsalary
  WINDOW w AS (PARTITION BY depname ORDER BY salary DESC);
```

Currenty fails as it expects WINDOW after the OVER.

**Comment by wumpz** [comment]
This is not (yet) supported. PRs are welcome or do you want to support the implementation of this feature in other ways?

**Comment by d2a-raudenaerde** [comment]
I'm not sure how to implement it yet, I took a quick look at `WindowElement()` . I'll think about it a bit :)

**Comment by d2a-raudenaerde** [comment]
@wumpz what other ways of support were you thinking of?  I have a rather large set of real-world Postgresql scripts I can test against  (that is how I found the other issues as well)

**Comment by manticore-projects** [comment]
@d2a-raudenaerde: In my understanding there are two ways to get features implemented -- either write the code and submit a PR or sponsor an implementation. Especially when you ask for features, which do not have any direct benefits for the developers, a bounty might attract the needed interest.

Its one thing to freely share code, which I wrote mainly for my own needs. Its a different thing to work on someone else's requirements.

**Comment by d2a-raudenaerde** [comment]
@manticore-projects my time costs money as well, so I totally understand :) How would funding building features work? I could not find much info except a 'sponsor' tag, which I assume goes to Tobias?

**Comment by manticore-projects** [comment]
You are welcome. Tobias started this projects and did all the heavy lifting.
If you like to sponsor him some coffees or beers, we definitely will feel encouraged to work harder on Postgres related issues. (We both like PostgreSQL a lot, but do not use it for our daily business. Although MS SQL would cost you dearly -- just kidding.)

If you want to have something more binding with clear deliverables, please state your offer and expectations here.
When there is a d'accord, you still send to Tobias and we would sort it internally. 

I will also pick up the idea again, to place Bounties more prominently on the page.

Thanks for considering!

**Comment by d2a-raudenaerde** [comment]
I think I'm going to buy both of you beers / coffee :) I'm not a business myself, but I will ask my employer (when he's back from holidays) if we can do more official support stuff.

**Comment by manticore-projects** [comment]
A sponsorship for a more complete Postgres Grammar would be most welcome and deserved to be shown prominently.
Thanks for your moral support too.

**Comment by wumpz** [comment]
I am on it.
