### ISSUE TITLE
Missing support for presto : TABLESAMPLE BERNOULLI clause

### ISSUE THREAD

**Issue by ctdcj** [JSQLParser/JSqlParser#1593]
SELECT * FROM fact_halllogin_detail TABLESAMPLE BERNOULLI (10) where dt>=20220710 limit 10

Exception: 
Encountered unexpected token: "BERNOULLI" <S_IDENTIFIER>
    at line 1, column 49.

Was expecting one of:

    ";"
    "CONNECT"
    "EMIT"
    "GROUP"
    "HAVING"
    "PIVOT"
    "START"
    "WINDOW"
    <EOF>

**Comment by manticore-projects** [comment]
Greetings. 
You will need to provide much more information please:
1) What RDBMS
2) What Version of JSQLParser
3) What should the `BERNOULLI(10)` represent, it seems to be far from any SQL dialect I know

**Comment by kfdjsakfdjk** [comment]
Greetings.
I am using jsqlparser version 4.4 and the corresponding database is prestodb.
