### ISSUE TITLE
parser sql : create table id faile

### ISSUE THREAD

**Issue by liushangqing9803** [JSQLParser/JSqlParser#1596]
CREATE TABLE `student2` (
  `id` int(10) NOT NULL COMMENT 'ID',
  `name` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '名称',
  `sex` varchar(4) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '性别',
  `birth` year(4) DEFAULT NULL,
  `department` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL,
  `address` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `id` (`id`),
  index `name` (`name`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='学生表'

-------------------------------
exception:
Caused by: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "USING" "USING"
    at line 10, column 21.

Was expecting one of:

    ")"
    ","

**Comment by manticore-projects** [comment]
Greetings.

This clause `index name (name) USING BTREE` is not supported.
Best regards
Andreas

**Comment by liushangqing9803** [comment]
thank you,do you plan to support it later

**Comment by wumpz** [comment]
@liushangqing9803 JSqlParser 4.5-SNAPSHOT is already able to parse your statement. However, looking into it I discovered a nasty bug parsing indexes within `create table`. This I want to solve first. After success, the 4.5 release has a go.
