### ISSUE TITLE
Insert.getItemsList deprecated and broken in 4.5

### ISSUE THREAD

**Issue by jcamerin** [JSQLParser/JSqlParser#1603]
### Discussed in https://github.com/JSQLParser/JSqlParser/discussions/1602

<div type='discussions-op-text'>

<sup>Originally posted by **jcamerin** July 25, 2022</sup>
I recently tried to upgrade from 4.4 to 4.5 and one of my unitTests that relies on Insert.getItemsList began failing.  In 4.5, this method is marked as deprecated, but there is nothing I could find in the release notes related to this change/deprecation, and there is not any commentary in the source code WRT what replaces this functionality, i.e. what I should use instead of getItemsList.  
Does anyone know what the related change is and what I should be using instead of getItemsList?</div>

The below code experiences different outcomes in 4.4 vs 4.5
With 4.4, the first condition returns true, i.e. getItemsList returns a MultiExpressionList with 2 expressionLists of size 11.
With 4.5, the getItemsList returns an ExpressionList of size 2 instead of a MultiExpressionList.  There is no way to differentiate the two use cases / outcomes with version 4.5 of the parser library.

`Insert insert = (Insert) new CCJSqlParserManager().parse(new StringReader(sqlString));`
`ExpressionList expressionList;
`if (insert.getItemsList() instanceof MultiExpressionList) {`
`    expressionList = ((MultiExpressionList) insert.getItemsList()).getExprList().get(0);`
`} else {`
`    expressionList = (ExpressionList) insert.getItemsList();`
 `}`
`assertEquals("Expected 11 items in expressionList", 11, expressionList.size());`

SqlString = 
insert into 
    accelerator.messagegears_push_render_error  (
		activity_id,
		request_id,
		correlation_id,
		device_id,
		service,
		application_id,
		activity_timestamp,
		job_category,
		recipient_id,
		error_code,
		error_message) 
values (
  '57e01e05-f10c-48aa-bd29-8a0912e72d40', 
  't25610-0b74f4c6-fe21-411f-bba9-82818bf1c31b', 
  'My Job Id: 101010', 
 '12345678', 
  'FCM', 
  '12345', 
  '2022-07-25T21:11:01', 
  'example job category', 
  'example recipient id', 
  'error1', 
  'errorMessage1' 
),(
  '57e01e05-f10c-48aa-bd29-8a0912e72d40', 
  't25610-0b74f4c6-fe21-411f-bba9-82818bf1c31b', 
  'My Job Id: 101010', 
 '12345678', 
  'FCM', 
  '12345', 
  '2022-07-25T21:11:01', 
  'example job category', 
  'example recipient id', 
  'error2', 
  'errorMessage2' 
);

**Comment by manticore-projects** [comment]
There you go:
```java
Insert insert = (Insert) CCJSqlParserUtil.parse(sqlStr);
SetOperationList setOperationList = (SetOperationList) insert.getSelect().getSelectBody();
ValuesStatement valuesStatement = (ValuesStatement) setOperationList.getSelects().get(0);
ItemsList itemsList = valuesStatement.getExpressions();
```

**Comment by manticore-projects** [comment]
Would visualizing the AST help you?

![image](https://user-images.githubusercontent.com/18080123/180909132-83a285c6-865a-42a5-921c-09b99c32a26d.png)

**Comment by manticore-projects** [comment]
I have quickly drafted something for you:

1) [Open the online JSQLFormatter UI](http://jsqlformatter.manticore-projects.com/jsqlformatter/demo.html?args=-c%20JYOwzgpgTgLgBKGB7AUAQwMYYgG2m5KAOgFsIww0BzCGtKMAfQAcBXMAC0aghABNojaFCRQ4ACnQYYwAG7AYAT0bA+AGhQ8Ajq3IwV6lBlE8cBYEhAGNA+dmspIUOxA1pmzHMAznLDzDLySowyZGAwaCTMGgBWSABGjD4wtKKKGjwYwMzAvPqqGsKiSUgChVAiUIxhlDQAlCiyaDi6YBIoAOQArADsEAAMAIwDXQC0AGaD-RijACwAHGhoo-F8AEwAnKOL-RuDaxA9a3yz-R0aHTBrXQBsU6P98T2z47MYNxMQa4Nzg4PjK3iaC28zW80G83ikwwAGZBvFzp0ALKKOAAKQScAAknwAFxwKaEs4XfYw2a3HrzREdABiAGEkdTSeTqWt+ms1g8eqNrgAVb64v64obUiAAD0inggcDi8TgyVSUEUoolUTwcEy2VyIHgqlFFVEg31lSR5FqECNKDqakk3T6QxGEymMwWSxW6xBaF2+0Ox1O1Kut3uj2er3en2+v3+gOB2zBEKhg1h8OpKPRmJx+KJUyZazJFKpF3pjJJeZZFzZHK5PK6-MGgvrIou4sl6tl8oIiuVzdVUo1ECyOTyCD4xtEazHUFNFGoXw6VoA3CgUKAnLqdahMNg8FACKJSGbZ3QGCx2FwePxBEUxJIAnIFMoCpoIDo9A5jBVcL4rE-bN4IA4TguG4HheMkFg-oYd5BMooR6JKsQJEknZUGkGQDlqeQONeJRlCgOE1LODRNC05DtHaAzDP0YyTNMcyLMsqybNsXp7AcRwnMSnSBnc-QPE8LxvB84xfD8sx-AC8RAiC8aQtCcIIhcaYYnKmYEkMGm5vmNyUtSxZaeWnSVpy-TcnyApCk2nQtmq0rtgqqFKiqrbSpqQ46iOk5Gs2BpToeNCWtatq9JRjq0S6DHusxOxsb6nEBtcvH8aGQkRmJEkxjJ4JyUmCmpqiKnYni6lEgZBZ6QyZWsuyJlmbWFmNt51m9m2mIOWkzm2f2g7arqo4+ZUE4DaI07mhOi5AA)

2) Edit your statement or paste a new one

3) Add the left bottom, click on `SHOW AST` button. It should give you a Tree View on the SQL Parser Java Object Hierarchy.

Please do let me know any issues or change requests.

**Comment by manticore-projects** [comment]
Greetings, I have improved it a bit:
1) Ignore Token Fields (or else StackOverflow)
2) Tweak the appearance of Columns
3)  Also consider the SuperClass Fields

In the result it starts to become quite useful and shows the AST of [very complex Statements.](http://jsqlformatter.manticore-projects.com/jsqlformatter/demo.html?args=-c%20MoUQMiDCAqAEsHsDOBXJBTATgKHnvANLEgDYB0SAjiQPoCWAJrvoceVbQBYCGSnNAN24kU6Zi1hEEABwB23ALZiJ8IgBdumAObo14lkXQlu0jAxoYAxglkMk+-OrpKamdAu51ZXrdgBiAEoA8gCysAIAJBhISHQ2NCQ2WjJIbPoAkgBymSABsABSQVnhUegxcbLEDnhBmWwUjLAAvMQNTCosAIKZACL1GJh0wgDEza0DQyTD2ADqABK5ILBqzuiu7p7eslqwAHywAAzYANzY2JABIJ3QSwBq6SAzxACeSGSYKLJbWhbU+p3AWCgCAwPBvNBYeRKaodVT9Rgw2FEKhkdAAD3QlhQKxs9lhKmR5GMSDUNBQ0gY3DUaxW0PxEkJFGo9Ha9Mc-WZPD4gmEokRHSkckUyjZrA02l0-IJsCMJjMFkxNjsUoZy1W6w8Xh8KoMxEoTNoADMUCQSNS0XoOoFQiVorF4oltik0mysjk8oVipEOHqdfhanqDSyxqQgwjXdlcgUinVvWV7ZU8aL4AHQ7EGCG2n6VN0+mmsJNRi03hMRoj5os1S43JrvntDiczthQHBpNwdLEAF7oWAAVl7jbOLdgJC8ZTo3dgAEYAOxHU5nAD0ACpsEgEEo1JwfLBLJhuJ3nqd15vt9td-vD8eN7ozzs9wej2ub1udw+r9hl4umwBaH-EF87wvR9TmBKA4CBFAACMSUwAAKW14wqMgIUwKF0CIKciAADlgABKWBUPQxEiDjcobDIZBUMQVABhI2AekVBh0AQsiEwoLABCwbNVQAch6EAenSSBrkE3iiH43ieN1XjgDmTpLh6cTYFkqTkz4oJePw4hOO4gVbWoTR0G4MgGDoJAAGt1m4OxYDMyzrOVfTvUMtwTKglBDUNLAaB0NRUg8ryfL8pNVWAaDYNY0pyNkMhEksCyAHdPDUTDMIObT4qSlL6LY5DpEwBBLHjWBpHDaU8viZK6DUVEuNkNQZXqy0KqiVzjKDc1Go4fxgjCSrZBoaqWrhFzjDc-RSOihNZgWS5EJioMbIYNwYjGMajJM5bVtC2BcwW9iOBoLl+CEEQexaDa3LIE6eXO-5egO5D03W6aKiGlKs3wfaBooDQ1DQMZeM6GB0luEA1LwH63qqz70Ga2AAEIWl4yxR3QBrYCUGJ23QKSggCAS8gAIQATXwX6suGvbgEgHUprtZCiOFQdm3AcCVPRTEGOJkJgBoOSFMEmgAAUgiCMAyBFgBVAIAHEljg3jldgAAfVXYG2kr1ZUggtJ126ztENWNeV5TlcgZW8OOKTrX6trxuM2bKyOxowHSABpJZeIATk7KdPIKgQ1AAJmkCyQ6k04gA)

@Wumpz: I was really interested in hearing from you you, how this compares to the Token/Nodes AST approach, which I understand was never complete, but slow? Maybe we can replace or supersede it?
