### ISSUE TITLE
Could not parse complex COALESCE/CAST

### ISSUE THREAD

**Issue by d2a-raudenaerde** [JSQLParser/JSqlParser#1607]
This bit of (Postgresql valid) SQL fails:
```
select
t0.*
,	cr.code
from
mytable t0
join 	othertable cr ON cr.code = '1234'
where	
   COALESCE (cast(to_date(to_char(t0.datum_ontslagen,'YYYYMMDD'),'YYYYMMDD')||' '||t0.tijd_ontslagen as timestamp), current_timestamp(0)) - 
      cast(to_date(to_char(t0.datum_opname,'YYYYMMDD'),'YYYYMMDD')||' '||t0.tijd_opname as timestamp)
   >= (SELECT somefunction()) * interval '1 hours' 


```

net.sf.jsqlparser.JSQLParserException: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "(" "("
    at line 8, column 13.

**Comment by manticore-projects** [comment]
Greetings.

I think its this one: `current_timestamp(0)` -- current_timestamp needs to be whitelisted as keyword so it can be interpreted as a function name.

There is a 6 month old PR regarding a proper keyword handling. But it has not gotten much interested yet.

**Comment by d2a-raudenaerde** [comment]
Ah (sorry for the editting)
I'll check the PR.

**Comment by manticore-projects** [comment]
What I can do: I can update the PR to reflect the latest release and then you can give it a try.

**Comment by d2a-raudenaerde** [comment]
That would be nice :)

**Comment by manticore-projects** [comment]
Tomorrow first thing in the morning, I am running late here. cheers.

**Comment by d2a-raudenaerde** [comment]
No hurry! :)

**Comment by d2a-raudenaerde** [comment]
Btw: it is not a keyword according to the docs, but rather a function:
 
[ CURRENT_TIMESTAMP(precision)](https://www.postgresql.org/docs/current/functions-datetime.html)

**Comment by d2a-raudenaerde** [comment]
So, maybe instead of building support, we need to _remove_ the `K_TIME_KEY_EXPR` so the parser just parses a function?

**Comment by d2a-raudenaerde** [comment]
I removed it and the parse rules involving it, and now it parses fine :) 
If something like the `TimeKeyExpression` is needed somewhere, I think the `Function` parse rules could use some IF statement matching the functions name and return a `TimeFunction` (as that would be a more correct name)?

**Comment by d2a-raudenaerde** [comment]
Mmm. It fails the `CURRENT TIME` test for db2  (is that even valid SQL?) 
That can be fixed by instead of removing the K_TIME_KEY_EXPR, we keep it but only the tokens with a ' ' (so the `_` will be handled by the function parsing rules)

**Comment by d2a-raudenaerde** [comment]
Btw: the sql standard does have a special case for these datetime functions:

```
<datetime value function> ::=
		<current date value function>
	|	<current time value function>
	|	<current timestamp value function>
	|	<current local time value function>
	|	<current local timestamp value function>

<current date value function> ::= CURRENT_DATE

<current time value function> ::= CURRENT_TIME [ <left paren> <time precision> <right paren> ]

<current local time value function> ::= LOCALTIME [ <left paren> <time precision> <right paren> ]

<current timestamp value function> ::= CURRENT_TIMESTAMP [ <left paren> <timestamp precision> <right paren> ]

<current local timestamp value function> ::= LOCALTIMESTAMP [ <left paren> <timestamp precision> <right paren> ]
```

**Comment by d2a-raudenaerde** [comment]
I think it would be rather straight-forward to implement these rules, and allow the tokens to be both with underscore, and without.

**Comment by manticore-projects** [comment]
> I think it would be rather straight-forward to implement these rules, and allow the tokens to be both with underscore, and without.

With and without underscore is supported already.

**Comment by d2a-raudenaerde** [comment]
Ah ok, I will be patient and wait for you PR :)

**Comment by manticore-projects** [comment]
The PR https://github.com/JSQLParser/JSqlParser/pull/1382 is there already, I just need to resolve conflicts. You can read through the lengthy discussion already for understanding what it does and how it works.

**Comment by manticore-projects** [comment]
Still relevant with JSQLParser 4.6 Snapshot.

**Comment by d2a-raudenaerde** [comment]
Cool, thanks!
