### ISSUE TITLE
TenantLineInnerInterceptor Could not support "Replace" grammer like "replace into table_xx values ..."

### ISSUE THREAD

**Issue by JuneMare** [JSQLParser/JSqlParser#1612]
I execute "replace INTO b_house ( id, `name1`) values ( (#{house.id} ,#{house.name1})" in multiple tenant mode，using "TenantLineInnerInterceptor" to help me，but it cannot work. because there is no related code...

at com.baomidou.mybatisplus.extension.parser.JsqlParserSupport#processParser：

if (logger.isDebugEnabled()) {
            logger.debug("SQL to parse, SQL: " + sql);
        }
        if (statement instanceof Insert) {
            this.processInsert((Insert) statement, index, sql, obj);
        } else if (statement instanceof Select) {
            this.processSelect((Select) statement, index, sql, obj);
        } else if (statement instanceof Update) {
            this.processUpdate((Update) statement, index, sql, obj);
        } else if (statement instanceof Delete) {
            this.processDelete((Delete) statement, index, sql, obj);
        }
        sql = statement.toString();
        if (logger.isDebugEnabled()) {
            logger.debug("parse the finished SQL: " + sql);
        }
        return sql;

just Insert，Select，Delete and Update，There is not Replace block..

**Comment by wumpz** [comment]
But this does not seem to be a JSqlParser problem but a mybatisplus extension problem.

**Comment by manticore-projects** [comment]
No feedback and no further questions asked. Closed.
