### ISSUE TITLE
Failed to parse  "ALTER TABLE table1 RENAME table2;"

### ISSUE THREAD

**Issue by linjiulin** [JSQLParser/JSqlParser#1613]
When I use "ALTER TABLE table1 RENAME table2;" to rename the table, it parse failed by JSqlParser.

```
ALTER TABLE yxyh_basic_info_tmp RENAME yxyh_basic_info;
```
```
net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "RENAME" <S_IDENTIFIER>
    at line 2, column 19.

Was expecting one of:

    "ADD"
    "ALGORITHM"
    "ALTER"
    "CHANGE"
    "DROP"
    "MODIFY"

```

**Comment by luoffei** [comment]
ALTER TABLE table_name RENAME TO new_table_name;

**Comment by manticore-projects** [comment]
Greetings,

unfortunately you seem to use very old versions of JSQLParser.
Please retry with JSQLParser 4.5 or 4.6-Snapshot as I am able to parse it. [You can try online.](http://jsqlformatter.manticore-projects.com/jsqlformatter/demo.html?args=-c%20IIGQKgogSgBGwCEQRgFwIYCMA2BTA+gHboC2uMUEAcsALIpgDyMhuA7vhjgcWQNxA)
