### ISSUE TITLE
解析时候异常（ QL parsing problem）

### ISSUE THREAD

**Issue by qq1461607240** [JSQLParser/JSqlParser#1618]
![image](https://user-images.githubusercontent.com/76995270/185290864-8f321bd2-14a1-4754-8504-e1db8eff6fcb.png)

**Comment by wumpz** [comment]
Please describe the error. English should be used here. Don't use a screenshot. We do not want to copy the SQLs and stuff.

**Comment by manticore-projects** [comment]
No feedback and no further questions asked. Closed.
