### ISSUE TITLE
add support for @@spid on SQL Server

### ISSUE THREAD

**Issue by donshop11** [JSQLParser/JSqlParser#162]
the following query fails to parse:

SELECT @@SPID AS 'ID', SYSTEM_USER AS 'Login Name', USER AS 'User Name'

Caused by: net.sf.jsqlparser.parser.ParseException: Encountered " "@@" "@@ "" at line 1, column 8.

@@spid is described here:
https://msdn.microsoft.com/en-us/library/ms189535.aspx

**Comment by wumpz** [comment]
So in general what is the difference between @@ and @? Is @@ allowed only for specific names (here spid)?

**Comment by donshop11** [comment]
there seems to be a bunch of those:
https://msdn.microsoft.com/en-us/library/ms173823.aspx

all built-in
