### ISSUE TITLE
How to retrieve updateSets of InsertConflictAction

### ISSUE THREAD

**Issue by leotu** [JSQLParser/JSqlParser#1630]
- https://www.postgresql.org/docs/current/sql-insert.html

```txt
"...UPDATE SET column"
```
Code: [InsertConflictAction.java](https://github.com/JSQLParser/JSqlParser/blob/b392733f25468f1b09b408820fcd02fab328f6b9/src/main/java/net/sf/jsqlparser/statement/insert/InsertConflictAction.java)

There is no public method to get variable "updateSets".

```java
public class InsertConflictAction {
    ConflictActionType conflictActionType;

    private final ArrayList<UpdateSet> updateSets = new ArrayList<>();
    Expression whereExpression;
...
}
```

```txt
InsertConflictAction conflictAction = insert.getConflictAction();
Missing method ==> conflictAction.getUpdateSets() ?
```

**Comment by manticore-projects** [comment]
Greetings.

> There is no public method to get variable "updateSets".

There certainly is in JSQLParser 4.6 SNAPSHOT:
![image](https://user-images.githubusercontent.com/18080123/190361060-5e1330f4-c582-4868-bdc0-2485027b3bd5.png)


What version of JSQLParser are you using please.
You can [try it online here](http://jsqlformatter.manticore-projects.com/jsqlformatter/demo.html?args=-c%20JIOQygogSgKgBKGB5OATAlgZwC4Cd0BGArtgPa6ZwAUGqANGgHYCGAtgKYCUAUHH3ADUAggBkAqhDDUArAwDkAcXQAvVqTgxczRpgDmAG1IFm+uZwZUAbPKGZMpAMbpm2dqjgBhUqwAOJdIy6DMCMDma8-EggnlEAYiLAHvA06KiccAAiKGIAChlCMBBwkPCoLBxwALxwEAAaHuIZEBkAdGVs7ADcQA)

**Comment by leotu** [comment]
jsqlparser version 4.5

**Comment by manticore-projects** [comment]
I have issued PR #1632 
You can use the attached Snapshot JAR as a remedy.
[jsqlparser-4.5-SNAPSHOT.zip](https://github.com/JSQLParser/JSqlParser/files/9574744/jsqlparser-4.5-SNAPSHOT.zip)

Thank you again for your report!
