### ISSUE TITLE
Insert ON CONFLICT parsed failed when composite primary multi columns

### ISSUE THREAD

**Issue by leotu** [JSQLParser/JSqlParser#1633]
Ref: #1630 

Failed when composite primary keys  (id_1+id_2)  --> "ON CONFLICT (id_1, id_2)"

```sql
INSERT into test_data (id_1, id_2, my_string_1, my_string_2)
VALUES ('id_1_A', 'id_2_A', 'my_string_1-new', 'my_string_2-new')
ON CONFLICT (id_1, id_2) DO UPDATE 
SET my_string_1 = 'my_string_1-update', my_string_2 = 'my_string_2-update';
```
Screenshot:
<img width="900" alt="截圖 2022-09-16 11 46 10" src="https://user-images.githubusercontent.com/1053138/190553216-83842319-cf8b-4471-a4b4-f2df8e0c45e1.png">

DB tools validation successfully: 

(1) Left is schema, right is sample data:
<img width="1536" alt="截圖 2022-09-16 11 44 40" src="https://user-images.githubusercontent.com/1053138/190553422-b31665dd-3550-423d-8c5d-0810aa1a2bbc.png">

(2) Executed successfully:
<img width="1066" alt="截圖 2022-09-16 11 45 23" src="https://user-images.githubusercontent.com/1053138/190553512-5a072188-909c-40c0-aa8f-3f81cf423bed.png">

(3) Update sample data:
<img width="1018" alt="截圖 2022-09-16 11 45 44" src="https://user-images.githubusercontent.com/1053138/190553596-d076dec8-817d-4f7b-ad79-09a237568ca8.png">

**Comment by manticore-projects** [comment]
Duplicate #955

**Comment by manticore-projects** [comment]
Please can someone have a look at the [PostgreSQL Documentation](https://www.postgresql.org/docs/current/sql-insert.html) and explain to me, where exactly it allows multiple columns?!
