### ISSUE TITLE
add support for Collate in SELELCT for SQL Server

### ISSUE THREAD

**Issue by donshop11** [JSQLParser/JSqlParser#164]
support syntax like:

SELECT u.name  COLLATE Latin1_General_CI_AS AS User
FROM users u

exception: Encountered " <S_IDENTIFIER> "Latin1_General_CI_AS "" at line 1, column 24.

which converts the string's value on the fly...

**Comment by donshop11** [comment]
again I don't think the collate itself is not that interesting to parse. I only need to make the statement parse successfully.

**Comment by donshop11** [comment]
closed it by mistake

**Comment by donshop11** [comment]
another beautiful [real-life] example for Collate, this time in an order by ...

select row_number() over (order by name COLLATE Latin1_General_CI_AS_KS asc) row_num from T

**Comment by rogerio-ar-costa** [comment]
I am having the same issue in a prototype I am working on:
`Select from Table1 where colA COLLATE Latin1_General_CI_AI = 'VALUÉ';`

**Comment by donshop11** [comment]
any planned support for COLLATE?

**Comment by wumpz** [comment]
Not so far. Pull requests are wellcome.
