### ISSUE TITLE
Cannot deal with double parenthesis correctly

### ISSUE THREAD

**Issue by chenlujjj** [JSQLParser/JSqlParser#1647]
How to reproduct:
```Java
 String sql = "SELECT t, groupArray((`log.level`, c)) AS groupArr FROM ( SELECT (intDiv(toFloat64(timestamp) * 1000, (8 * 1000)) * (8 * 1000)) AS t, `log.level`, count(*) as c FROM billions.`ops.billions.fakelog` WHERE timestamp >= toDateTime64(1666093108, 3) AND timestamp <= toDateTime64(1666096708, 3) GROUP BY t, `log.level` ORDER BY t, `log.level`) GROUP BY t ORDER BY t";
        CCJSqlParserUtil.parse(sql);
```

Exception:
```
Caused by: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "(" "("
    at line 1, column 21.
```

**Comment by manticore-projects** [comment]
Greetings.

Your statement parses completely fine with JSQLParser 4.6 Snapshot and [you can try it online here.](http://jsqlformatter.manticore-projects.com/jsqlformatter/demo.html?args=-c%20MoUQMiDCAqAEsBcBQ9WoDSwOICcD2ArgA4CGOOJAngBSy0AGANngOYB0jApgG6eP2YAxrACUo2AEFgsFvmJkcSAGIAlAPIBZOvFAQY8WgEkAdggAmAS261oeAGbMSCAGwAWWggsBbTgGcEJF5E4gBUsACMAAzRmLQAHLBhUdHiYmHxiRHRkamS0shohUWwmEysHDx89CjFtZiQhKa0YWJSsII1RaqasABGFoyMFnjGvmz0eERj-YPDo2x2JADWfKzVtQDqABIgKiCI3n4BQbAAfAC8sLZmTpyePm604c4vkQCcAMxRcZgfop21SQAOQAIgcfP5AsEADyXa63e6cR4RF7Od7OADskR+sD+IgBaCw6gAqgAFWAAIQAmmgCoD6aVmOwuLx+ATUGoVCDdpSaag6fS6rAyszKvx-kS1GTeYgkJzuSoZcgANxAA)

**Comment by manticore-projects** [comment]
No feedback and no further questions asked. Closed.
