### ISSUE TITLE
Encountered unexpected token: "if" "IF"  "=" 

### ISSUE THREAD

**Issue by boop542** [JSQLParser/JSqlParser#1648]
fisrt question
Original SQL: 
SELECT
        1 as query_type,
        a.id as bill_id,
        a.bill_code,
        td.trade_money as bill_money,
        td.trade_money,
        a.inputer_name,
        t.trade_type,
        t.status AS trade_status,
        if(a.status=2||a.status=4,1,0) as expired,
        a.status AS asset_status,
        a.output_time,
        t.create_time AS trade_date,
        a.expire_date,
        ABS(TIMESTAMPDIFF(DAY, a.output_time, a.expire_date)) AS days,
        t.trade_no,
        t.creator_id
        FROM asset AS a
        JOIN trade_detail AS td
        ON a.id = td.pre_bill_id
        JOIN trade AS t
        ON td.trade_no = t.trade_no
         WHERE t.trade_type = 1
            AND t.status IN (2, 3, 4, 5)
            AND a.outputer_id = ?
                and a.bill_code = ?
        and a.output_time >= ?
        and a.output_time <=?
        and a.expire_date >=?
        and a.expire_date <=?
        and t.create_time >=?
        and t.create_time <=?
        and t.trade_no = ?
        and a.status in (0,1,3,5) 
        order by output_time asc
when useing jsqlparser parser this sql then throw a exception:Encountered unexpected token: "if" "IF"

Caused by: net.sf.jsqlparser.JSQLParserException
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parseStatements(CCJSqlParserUtil.java:137)
	at com.baomidou.mybatisplus.core.parser.AbstractJsqlParser.parser(AbstractJsqlParser.java:60)
	... 47 more
Caused by: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "if" "IF"
    at line 10, column 9.

Was expecting one of:

    "!"
    "("
    "*"
    "+"
    "-"
    "?"
    "@"
    "@@"
    "ACTION"
    "ANY"
    "BYTE"
    "CASCADE"
    "CASE"
    "CAST"
    "CHANGE"
    "CHAR"
    "CHARACTER"
    "COLUMN"
    "COLUMNS"
    "COMMENT"
    "COMMIT"
    "DESCRIBE"
    "DO"
    "DUPLICATE"
    "ENABLE"
    "END"
    "EXTRACT"
    "FALSE"
    "FIRST"
    "FN"
    "FOLLOWING"
    "GROUP_CONCAT"
    "INDEX"
    "INSERT"
    "INTERVAL"
    "ISNULL"
    "KEY"
    "LAST"
    "MATERIALIZED"
    "NEXTVAL"
    "NO"
    "NOT"
    "NULL"
    "NULLS"
    "OPEN"
    "OVER"
    "PARTITION"
    "PATH"
    "PERCENT"
    "PRECISION"
    "PRIMARY"
    "PRIOR"
    "RANGE"
    "READ"
    "REPLACE"
    "ROW"
    "ROWS"
    "SEPARATOR"
    "SESSION"
    "SIBLINGS"
    "SIZE"
    "START"
    "TABLE"
    "TEMP"
    "TEMPORARY"
    "TOP"
    "TRUE"
    "TRUNCATE"
    "TYPE"
    "UNSIGNED"
    "VALUE"
    "VALUES"
    "XML"
    "ZONE"
    "{d"
    "{t"
    "{ts"
    "~"
    <K_DATETIMELITERAL>
    <K_DATE_LITERAL>
    <K_TIME_KEY_EXPR>
    <S_CHAR_LITERAL>
    <S_DOUBLE>
    <S_HEX>
    <S_IDENTIFIER>
    <S_LONG>
    <S_QUOTED_IDENTIFIER>

another question
Original SQL:
SELECT
        b2.id AS node_id,
        a.outputer_id,
        a.outputer_name,
        a.output_time as output_date,
        a.factor_id,
        b2.owner_id,
        b2.owner_name,
        t.inputer_id AS pledge_ent_id,
        t.inputer_name AS pledge_ent_name,
        b2.bill_code,
        b2.bill_money,
        b.root_id,
        td2.bill_id AS parent,
        b2.create_time AS owner_date,
        td2.trade_no,
        b2.bill_level,
        t.trade_type,
        t.status AS trade_status,
        (select pledge_type from bill_pledge_operation s where s.trade_no =  t.trade_no AND s.STATUS = 1 ORDER BY create_time desc limit 1) AS pledge_type,
        (select date_format(create_time,'%Y-%m-%d') from bill_pledge_operation s where s.trade_no =  t.trade_no AND s.STATUS = 1 ORDER BY create_time desc limit 1) AS unbind_pledge_date,
        tpe.pledge_date,
        (t.outputer_id  =  b2.owner_id) AS is_remain
        FROM
        trade_detail AS td
        JOIN bill AS b
        ON b.id = td.bill_id
        JOIN bill AS b2
        ON b2.root_id = b.root_id
        JOIN trade_detail AS td2
        ON td2.pre_bill_id = b2.id
        JOIN trade AS t
        ON t.trade_no = td2.trade_no
        JOIN asset AS a
        ON a.id = b.root_id
        LEFT JOIN trade_pledge_ext AS tpe
        ON tpe.trade_no = td2.trade_no
         WHERE  td.bill_code = ?
                AND td.trade_no = ?
            AND t.status in (4,5) 
        ORDER BY b2.bill_level
		
when useing jsqlparser parser this sql then throw a exception:Encountered unexpected token: "=" "="

Caused by: net.sf.jsqlparser.JSQLParserException
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parseStatements(CCJSqlParserUtil.java:137)
	at com.baomidou.mybatisplus.core.parser.AbstractJsqlParser.parser(AbstractJsqlParser.java:60)
	... 61 more
Caused by: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "=" "="
    at line 23, column 25.

Was expecting one of:

    "&"
    ")"
    "::"
    "<<"
    ">>"
    "COLLATE"
    "["
    "^"
    "|"
	
	**if, = mysql syntax is not supported. I think we can use case when instead, but it is not the best solution.
	How to solve these problems?**

**Comment by manticore-projects** [comment]
Greetings.

This is not about the `if()` but about expression parameters.
it should be solved since a few days. please try the latest JSQLParser Snapshot from Source.

**Comment by manticore-projects** [comment]
Actually, there are two issues with your statement:

1) Expression Function Parameters
```sql
SELECT if(a.status=2 OR a.status=4,1,0)
```

This has been solved already and you can download the latest source and build it.

2) Concatenation `||` vs. Boolean `OR`

```sql
SELECT if(a.status=2 || a.status=4,1,0)
```

This is invalid because the `||` Operator indicated String concatenation. Please use `OR` for boolean comparison.

![image](https://user-images.githubusercontent.com/18080123/196642749-dbce54a6-70a5-4fa2-9753-61edfa7bd627.png)

**Comment by boop542** [comment]
I've tried，Thank you for your help
