### ISSUE TITLE
The syntax for interval expression is incomplete

### ISSUE THREAD

**Issue by GeeGee2006** [JSQLParser/JSqlParser#165]
The syntax for interval expression defined in *.jjt file: 

IntervalExpression IntervalExpression() : {
	IntervalExpression interval = new IntervalExpression();
	Token token;
}
{
	&lt;K_INTERVAL&gt;  token=&lt;S_CHAR_LITERAL&gt; { interval.setParameter(token.image); }
    [ LOOKAHEAD(2) token = &lt;S_IDENTIFIER&gt; { interval.setIntervalType(token.image); } ]
	{
		return interval;
	}
}

But per the documentation in mysql official site (http://dev.mysql.com/doc/refman/5.1/en/date-and-time-functions.html#function_date-add), the interval expression syntax format is:
'interval' &lt;expr&gt; &lt;type&gt;

the &lt;expr&gt; can be a numeric value or an expression which results in a numeric value or character literal. 

As a workaround without class modification, currently I modify the syntax as follows to avoid the statement parse failure. It should work under most situation. 

IntervalExpression IntervalExpression() : {
	IntervalExpression interval = new IntervalExpression();
	Token token;
}
{
	&lt;K_INTERVAL&gt; 
	(
		token=&lt;S_LONG&gt; { interval.setParameter(token.image); }
		| token=&lt;S_DOUBLE&gt; { interval.setParameter(token.image); }
		| token=&lt;S_CHAR_LITERAL&gt; { interval.setParameter(token.image); }
	)
    [ LOOKAHEAD(2) token = &lt;S_IDENTIFIER&gt; { interval.setIntervalType(token.image); } ]
	{
		return interval;
	}
}

**Comment by wumpz** [comment]
Jsqlparser supports different db systems. Maybe it is incomplete for mysql the grammar was definitely derived from real world examples. Tobias

**Comment by lufaxadmin** [comment]
Any plan to fix it?

**Comment by wumpz** [comment]
Not yet. I am on holiday. For the moment first ocean second jsqlparser. 😉 Cheers Tobias

**Comment by wumpz** [comment]
Took a slightly modified version of your patch. Thx for using JSqlParser.
