### ISSUE TITLE
JSqlParser can't parse DATABASE function in mysql.

### ISSUE THREAD

**Issue by vipcxj** [JSQLParser/JSqlParser#1650]
```sql
        select count(*)
        from information_schema.columns
        where table_name = 'extend_value_info'
          and column_name = 'extend_value_str'
          and table_schema = DATABASE();
```
throws:
```
Caused by: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "=" "="
    at line 5, column 28.

Was expecting one of:

    "&"
    "::"
    ";"
    "<<"
    ">>"
    "COLLATE"
    "CONNECT"
    "EMIT"
    "GROUP"
    "HAVING"
    "START"
    "["
    "^"
    "|"
    <EOF>

	at net.sf.jsqlparser.parser.CCJSqlParser.generateParseException(CCJSqlParser.java:33398) ~[jsqlparser-4.5.jar:na]
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_consume_token(CCJSqlParser.java:33231) ~[jsqlparser-4.5.jar:na]
	at net.sf.jsqlparser.parser.CCJSqlParser.Statement(CCJSqlParser.java:167) ~[jsqlparser-4.5.jar:na]
	at net.sf.jsqlparser.parser.CCJSqlParserManager.parse(CCJSqlParserManager.java:23) ~[jsqlparser-4.5.jar:na]
	... 54 common frames omitted
```
Is there any workround?
I try to around the DATABASE with "``" like this:
```sql
        select count(*)
        from information_schema.columns
        where table_name = 'extend_value_info'
          and column_name = 'extend_value_str'
          and table_schema = `DATABASE()`;
```
Then mysql can't parse it.

**Comment by manticore-projects** [comment]
Greetings!

Please download/use the Keywords PR #1382 which supports proper Whitelisting of non-reserved keywords. [Your statement will work as shown here](http://jsqlformatter.manticore-projects.com/jsqlformatter/demo.html?args=-c%20MoUQMiDCAqAEkHsCuA7ALgClgKlgSgCgAxAJQHkBZWASxQDMEAnAWwEM1qEUB9AZwGMAFgFM2AOn4IANkmYpeBAOoAJECRCw0rAEZTh3FK2bDYAXlgByYQA80wlABNuAN1Yz9tBhYKxfsAIIAcgAisJIycgZGJuZWtvZOru58aIzefgEhmjp6fEKirGawwew6rLzCGIQA3EA)

**Comment by vipcxj** [comment]
@manticore-projects  When this pr will be merged? It seems that almost a year passed and this pr hasn't been merged. What' problem?

**Comment by manticore-projects** [comment]
> @manticore-projects When this pr will be merged? It seems that almost a year passed and this pr hasn't been merged. What' problem?

I can't say for sure. Maybe @wumpz has many things on his plate. Unfortunately I can't merge it as I am just an interested user.
