### ISSUE TITLE
Failed to parse SQL Server ddl (alter table a_test add c1 int, c2 int, c3 int)

### ISSUE THREAD

**Issue by wangziyang** [JSQLParser/JSqlParser#1651]
An error is reported when calling （the public static Statement parse(String sql, Consumer<CCJSqlParser> consumer) ）method

net.sf.jsqlparser.JSQLParserException: Encountered unexpected token: "c2" <S_IDENTIFIER>
    at line 1, column 31.

Was expecting one of:

    "ADD"
    "ALGORITHM"
    "ALTER"
    "CHANGE"
    "COMMENT"
    "DROP"
    "MODIFY"
    "RENAME"

	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parseStatement(CCJSqlParserUtil.java:190)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:63)

**Comment by manticore-projects** [comment]
Greetings.

The supported `ALTER TABLE` syntax is shown here: https://manticore-projects.com/JSQLParser/_static/JSqlParserCC.xhtml#AlterExpression

If you wanted to used multiple `ALTER EXPRESSIONs` (which is supported), the  comma-separate them and start each with the Command. E. g.
```sql
ALTER TABLE ADD ,,,, ADD ..., ADD ...
;
```

**Comment by manticore-projects** [comment]
No feedback and no further questions asked. Closed.
