### ISSUE TITLE
how to parse "order by xxx" to OrderByElement object

### ISSUE THREAD

**Issue by sunmingsheng** [JSQLParser/JSqlParser#1658]
How can I parse the phrase "order by id desc, cnt desc" into an OrderByElement object using "JsqlParser"?

**Comment by manticore-projects** [comment]
greetings.

`Show AST` is your friend:

http://jsqlformatter.manticore-projects.com/jsqlformatter/demo.html?args=-c%20M4UwNiDGAuAECMAoAZgJwPYFtYBMCuAhmLAO4AWIqIsBAvAEZA

![image](https://user-images.githubusercontent.com/18080123/199849939-642c2af3-150d-45d0-8151-01cc5912092a.png)

**Comment by manticore-projects** [comment]
No feedback and no further questions asked. Closed.
