### ISSUE TITLE
JSQL Parser not able to parse insert of blob in Mysql

### ISSUE THREAD

**Issue by amolskh** [JSQLParser/JSqlParser#166]
When we try to insert a blob in MYSQL database.
We get some query of this format
INSERT INTO TABLE VALUES('1',"DSDD", x'EFBFBDC7AB');

because of  x'EFBFBDC7AB' JSQL is not able to parse the string .. Is there any workaround or fix for the same?

**Comment by wumpz** [comment]
x'..' is some kind of hex representation of a blob value. MySQL allows here more then other databases. Standard seems to be 0xfffff. 

I will look into into. At the moment it is a little busy around here so it will take some time. :)

HexValues are not yet allowed in JSqlParser but I think would be a valuable improvement. 

Is it correct, that DSDD is quoted by double quotation marks?

Tobias

**Comment by amolskh** [comment]
DSDD  is just sample query you can ignore...
Main thing is blob  x'EFBFBDC7AB' which i was trying to draw your attention too

Is there any other way JSQL can parse blob queries?

**Comment by wumpz** [comment]
You could change your SQL using placeholders ( **INSERT INTO TABLE VALUES('1',"DSDD",?)** ), but a real solution is on the way. Should not be to hard to implement. As I said, time is at the moment an issue. You could try to motivate me ;).  Cheers Tobias

**Comment by amolskh** [comment]
Not sure about motivation

Actually its kind of urgent for me so I was trying to fix both issues 166, 167.  I have taken latest source code and from what I understand I need to edit JSqlParserCC.jjt
However I am not sure what syntax its using is it ANTLR?  Any guide or tutorial to understand and edit the same

**Comment by amolskh** [comment]
Thanks  a lot. 
When would the next release be and get pushed to maven Repo

**Comment by wumpz** [comment]
First I actualized the snapshot.

**Comment by wumpz** [comment]
The release could be done according to the new features and fixes within this snapshot.
