### ISSUE TITLE
How do I parse a custom SQL expression

### ISSUE THREAD

**Issue by wjxfhxy** [JSQLParser/JSqlParser#1664]
I have a custom SQL conditional expression, like this

types:123456

and I want to translate to 

types='123456'

so, I write  code like this:

val ret = CCJSqlParserUtil.parseCondExpression("types:123456") //return: types

but I got a result "types"

How can I do this?

**Comment by manticore-projects** [comment]
Greetings,

I do not think that this is supported. No RDBMS I know provides assignments like that.
You would need to provide much more context when looking for substantial assistance.

**Comment by wjxfhxy** [comment]
Because I have a query system, non-professional users want to spell simple query statements when using, so I have redefined some expressions

These expressions look like SQL, but are easier to type than SQL

And I want to turn this handy SQL into real SQL on the server side

Does JSQLParser provide such a custom conversion capability at the time of lexing, or at what stage

**Comment by manticore-projects** [comment]
> Because I have a query system, non-professional users want to spell simple query statements when using, so I have redefined some expressions
> 
> These expressions look like SQL, but are easier to type than SQL

Well, that's in the eye of the beholder -- but I don't want to discourage you.

> And I want to turn this handy SQL into real SQL on the server side
Then you will need to write your own "look like SQL" parser, since JSQLParser is about parsing real SQL.

> Does JSQLParser provide such a custom conversion capability at the time of lexing, or at what stage
Simple answer: No.

**Comment by wjxfhxy** [comment]
I asked the product manager to change the requirements
