### ISSUE TITLE
JSQL can't escape Single Quote

### ISSUE THREAD

**Issue by amolskh** [JSQLParser/JSqlParser#167]
I am having query

UPDATE tablename SET  NAME='Customer 2',ADDRESS='Address \' ddad2',AUTH_KEY='samplekey' WHERE  ID=2;

I am fine if we need to do

UPDATE tablename SET  NAME='Customer 2',ADDRESS='Address \\' ddad2',AUTH_KEY='samplekey' WHERE  ID=2;

This query worked fine on mysql workbench or other SQL agents.. But when I try to parse the Query in JSQL it dosent manage to parse.. Is there any other alternative??

Can you tell me meaning of these 2 regex
For both defects i think i need to play around with these regex

|   < S_CHAR_LITERAL: "'" (~["'"])* "'" ("'" (~["'"])* "'")*>
|   < S_QUOTED_IDENTIFIER: "\"" (~["\n","\r","\""])+ "\"" | ("`" (~["\n","\r","`"])+ "`") | ( "[" ~["0"-"9","]"] (~["\n","\r","]"])* "]" ) >

**Comment by amolskh** [comment]
I think using query in this format fixes it 
UPDATE tablename SET NAME='Customer 2',ADDRESS='Address '' ddad2',AUTH_KEY='samplekey' WHERE ID=2;

**Comment by wumpz** [comment]
Right. JSqlParser only supports usage of double quotation ('') and not backslash escaping.

**Comment by wumpz** [comment]
So could we close this one, as you provided a solution?

**Comment by amolskh** [comment]
ok sure
