### ISSUE TITLE
net.sf.jsqlparser.JSQLParserException: Encountered unexpected token: CURRENT_TIMESTAMP（3）

### ISSUE THREAD

**Issue by zxj058** [JSQLParser/JSqlParser#1670]
sql has update_time=CURRENT_TIMESTAMP(3)  is error

CURRENT_TIMESTAMP() is ok

Will the new version support this feature?

**Comment by manticore-projects** [comment]
Greetings, this has been corrected in MASTER a few days ago.
Please use the recent JSQLParser 4.6 Snapshot.
