### ISSUE TITLE
inner join and join should be marked as inner

### ISSUE THREAD

**Issue by Hccake** [JSQLParser/JSqlParser#1671]
```sql
SELECT * FROM table JOIN otherTable ON table.ID = otherTable.FK
```

equal to

```sql
SELECT * FROM table INNER JOIN otherTable ON table.ID = otherTable.FK
```

But after parsing through jsqlparse, the `net.sf.jsqlparser.statement.select.Join` object will not be marked as inner and there is no other attribute to mark the type.

**Comment by Hccake** [comment]
`LEFT JOIN` equal to `LEFT OUTER JOIN`, and `LEFT JOIN` in `net.sf.jsqlparser.statement.select.Join` be marked as left，`LEFT OUTER JOIN` be marked as left and outer.

Should `JOIN` also have a separate attribute for marking?

**Comment by manticore-projects** [comment]
Greetings.

Please use a recent Version of JSQLParser 4.5 or 4.6-Snapshot because your example works without any problem.
[You can try it here.](http://jsqlformatter.manticore-projects.com/jsqlformatter/demo.html?args=-c%20MoUQMiDCAqAEBUAoAYgJQPIFlYBcCGARgDYCmisFsAUugJIBysA9jgBYkBO+xZlfs6Rt1IA6AJYATWAF5mbTsJIiAZgGtEAbkTbQEGAhQZsi8pQb0QqanUYt2XQqVP8BQx0sky59xSvUagA)

**Comment by Hccake** [comment]
Hello, there is no problem with parsing, it just means that the type of Join cannot be easily distinguished.

For `INNER JOIN`, the attribute `inner` is marked true:

- ![image](https://user-images.githubusercontent.com/20430677/203237677-591d1a52-a9c6-4a2e-aa09-a2c03cadd848.png)


but for `JOIN`, no attribute is marked:

- ![image](https://user-images.githubusercontent.com/20430677/203232900-f5c59f43-7d09-4ab4-a73b-7344b08898b5.png)


Currently, I can only confirm the type of the join by obtaining the firstToken of the ASTNode:
  ```java
   join.getASTNode().jjtGetFirstToken().toString().equalsIgnoreCase("JOIN")
  ```

expect an attribute to mark the `JOIN`.

**Comment by manticore-projects** [comment]
Greetings.

The class `Join` has a public method `isInner()` which definitly works as intended, because otherwise the De-parsers would fail:

```java
public String toString() {
        StringBuilder builder = new StringBuilder();

        if (isSimple() && isOuter()) {
            builder.append("OUTER ").append(rightItem);
        } else if (isSimple()) {
            builder.append(rightItem);
        } else {
            if (isNatural()) {
                builder.append("NATURAL ");
            }

            if (isRight()) {
                builder.append("RIGHT ");
            } else if (isFull()) {
                builder.append("FULL ");
            } else if (isLeft()) {
                builder.append("LEFT ");
            } else if (isCross()) {
                builder.append("CROSS ");
            }

            if (isOuter()) {
                builder.append("OUTER ");
 ---->>  } **else if (isInner())** {           <------------------
                builder.append("INNER ");
            } else if (isSemi()) {
                builder.append("SEMI ");
            }

            if (isStraight()) {
                builder.append("STRAIGHT_JOIN ");
            } else if (isApply()) {
                builder.append("APPLY ");
            } else {
                builder.append("JOIN ");
            }

            builder.append(rightItem).append((joinWindow != null) ? " WITHIN " + joinWindow : "");
        }

        for (Expression onExpression: onExpressions) {
            builder.append(" ON ").append(onExpression);
        }
        if (usingColumns.size()>0) {
            builder.append(PlainSelect.getFormatedList(usingColumns, "USING", true, true));
        }

        return builder.toString();
    }
```

**Comment by manticore-projects** [comment]
I think, I do understand your actual question now better: You want to de-parse to `INNER JOIN` even when only `JOIN` (without `INNER`) has been provided.
Answer is: No, because it would depend on the RDBMS is `INNER JOIN` had exactly the same meaning as `JOIN` and its not guaranteed. Although you can implement your own Deparser, which translates any `JOIN` into a full `INNER JOIN`.

**Comment by Hccake** [comment]
Thank you for your reply.

`JOIN` really should not be marked as `inner` after parsing, but can we add an attribute to distinguish it? For example, add a `singel` attribute.

**Comment by manticore-projects** [comment]
> but can we add an attribute to distinguish it

Not needed. The absence of any other attribute set clearly indicates what is going on. Please follow the logic of the `toString()` method shown above.

**Comment by Hccake** [comment]
Ok, I understand, then I still use `ASTNode#firstToken` to judge whether it is only `JOIN` (without `INNER`).

Thanks for your help.
