### ISSUE TITLE
Parser takes table alias as DB2 reserved keyword

### ISSUE THREAD

**Issue by mlindhout** [JSQLParser/JSqlParser#1672]
Parsing this simple query fails:
```
SELECT cs.* FROM customer cs
```
by saying: **JSQLParserException: Encountered unexpected token: "cs" <K_ISOLATION>**, as does it for al the other DB2 reserved keywords for isolation (cs, ur, rs, rr): https://www.ibm.com/docs/en/db2-for-zos/11?topic=locks-choosing-isolation-option

Couldn't find a feature toggle for disabling this DB2 syntax?

**Comment by manticore-projects** [comment]
Greetings.

Please try latest JSQLParser 4.6 Snapshot as this challenge has been resolved.
[You can try it online here.](http://jsqlformatter.manticore-projects.com/jsqlformatter/demo.html?args=-c%20MoUQMiDCAqAEDGBnAdAKlgMQEoHkCyCArogC4D2AtgKYBOCiQA)

**Comment by mlindhout** [comment]
Nice, has this SNAPSHOT somewhere been published?

**Comment by mlindhout** [comment]
👍
