### ISSUE TITLE
Redshift MATERIALIZED VIEW with AUTO REFRESH is not supported

### ISSUE THREAD

**Issue by zaza** [JSQLParser/JSqlParser#1684]
Using the ["AUTO REFRESH" clause for a materialized view in Redshift](https://docs.aws.amazon.com/redshift/latest/dg/materialized-view-create-sql-command.html) is not supported by JSqlParser. 

Trying to parse a statement like this:
`CREATE MATERIALIZED VIEW AUTO REFRESH YES foo AS SELECT * FROM bar`
results in:

```
net.sf.jsqlparser.JSQLParserException: Encountered unexpected token: "CREATE" "CREATE"
    at line 1, column 1.

Was expecting one of:

    "("
    "ALTER"
    "CALL"
    "COMMENT"
    "COMMIT"
    "DECLARE"
    "DELETE"
    "DESCRIBE"
    "DROP"
    "EXEC"
    "EXECUTE"
    "EXPLAIN"
    "GRANT"
    "INSERT"
    "MERGE"
    "PURGE"
    "RENAME"
    "RESET"
    "ROLLBACK"
    "SAVEPOINT"
    "SET"
    "SHOW"
    "TRUNCATE"
    "UPDATE"
    "UPSERT"
    "USE"
    "VALUES"
    "WITH"
    <K_SELECT>

	at app//net.sf.jsqlparser.parser.CCJSqlParserUtil.parseStatement(CCJSqlParserUtil.java:190)
	at app//net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:63)
	at app//net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:38)
	... 86 more
Caused by: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "CREATE" "CREATE"
    at line 1, column 1.
```

With the `AUTO REFRESH YES` clause removed the statement is parsed just fine.

**Comment by wumpz** [comment]
That's right? Any chance you provide a PR or sponsor this feature?

**Comment by zaza** [comment]
This is the PR with an attempt to fix this, see https://github.com/JSQLParser/JSqlParser/pull/1691

Let me know if there are any other changes you would like to see included.
