### ISSUE TITLE
Parsing "CREATE MATERIALIZED VIEW IF NOT EXISTS ..." is not supported

### ISSUE THREAD

**Issue by zaza** [JSQLParser/JSqlParser#1686]
Parsing a string creating materialized view with "IF NOT EXISTS" clause fails with an error. It appears that `Feature.createViewMaterializedIfNotExists` is missing, which would be similar to `createViewMaterialized` and `createTableIfNotExists`.

**Comment by wumpz** [comment]
This one should be done after the materialized fine-tuning you proposed, right? However, this validation framework is somehow behind the *normal* JSqlParser development. So there are more missing pieces for sure.

**Comment by zaza** [comment]
I created https://github.com/JSQLParser/JSqlParser/pull/1690 but please let me know if I missed anything. This is my first contribution to this project. I do plan to tackle the other issues I recently reported, but wanted to do it one by one.
