### ISSUE TITLE
Encountered unexpected token: "||";    oracle || expression can not work     !!!!

### ISSUE THREAD

**Issue by XuYouquan** [JSQLParser/JSqlParser#1687]
for example
```  
  public static void main(String[] args) throws JSQLParserException {
        String str1 = "select  * from teacher where teacher.code = ?";
        CCJSqlParserUtil.parse(str1);

        String str2 = "select  * from teacher where teacher.code like '%'||?||'%'";
        CCJSqlParserUtil.parse(str2);

        String str3 = "select  teacher.* from teacher where teacher.code = ? and exists(select 1 from person person on person.id=teacher.person_id and person.name_zh like '%'||?||'%')";
        CCJSqlParserUtil.parse(str3);
    }
```
first sucess, second and third failed

**Comment by manticore-projects** [comment]
Greetings.

Please add proper White Space between the Oracle Concat Operator, otherwise it will clash with [supported JSON operators](https://www.postgresql.org/docs/9.5/functions-json.html) `?|`.

```sql
-- Works with proper Whitespace in between the Operator
select  * from teacher where teacher.code like '%' || ? || '%';

-- But fails when read as JSON Operator without Whitespace
select  * from teacher where teacher.code like '%'||?||'%';
```

**Comment by XuYouquan** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我已收到您的来信,我会尽快回复.

**Comment by XuYouquan** [comment]
> Greetings.
> 
> Please add proper White Space between the Oracle Concat Operator, otherwise it will clash with [supported JSON operators](https://www.postgresql.org/docs/9.5/functions-json.html) `?|`.
> 
> ```sql
> -- Works with proper Whitespace in between the Operator
> select  * from teacher where teacher.code like '%' || ? || '%';
> 
> -- But fails when read as JSON Operator without Whitespace
> select  * from teacher where teacher.code like '%'||?||'%';
> ```

Thank you reply me.

select  * from teacher where teacher.code like '%' || ? || '%';  
this sql can work.

but next sql failed yet
        String str3 = "select  teacher.* from teacher where teacher.code = ? and exists(select 1 from person person on person.id=teacher.person_id and person.name_zh like '%' || ? || '%')";
        CCJSqlParserUtil.parse(str3);

failed message net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "exists" "EXISTS"

BEST WISHES!

**Comment by manticore-projects** [comment]
Certainly, your sub query is invalid/incomplete. There is a `ON` without any `JOIN`:
```sql
select 1 from person person on person.id=teacher.person_id and person.name_zh like '%' || ? || '%'
```

Correct syntax would look like this:
```sql
SELECT teacher.*
FROM teacher
WHERE teacher.code = ?
    AND EXISTS (    SELECT 1
                    FROM person
                        INNER JOIN teacher
                            ON person.id = teacher.person_id
                                AND person.name_zh LIKE '%' || ? || '%' )
;
```

[You can test this here online and interactively.](http://jsqlformatter.manticore-projects.com/jsqlformatter/demo.html?args=-c%20MoUQMiDCAqAEAuBTAhgYwBaIE4DoBUAUAGIBKA8gLIIobYEDqAEiCSNWprqgPYAmisALywA-AVgTYAQQByAEVggAGgElg0YLAAUk2KAgxYARnG6z53aUqwADtgDO3AHamLbiypkyWsAFJlPdlosV3cw8zIZWwdnHABLXiEgzhw7LEcnAH0E0PC8s1kFNIycJ2QAW0RMgC90WDAVAGk2AHIAUhbYAB8u0W7e9s6ASgIAbiA)

**Comment by XuYouquan** [comment]
> Certainly, your sub query is invalid/incomplete. There is a `ON` without any `JOIN`:
> 
> ```sql
> select 1 from person person on person.id=teacher.person_id and person.name_zh like '%' || ? || '%'
> ```
> 
> Correct syntax would look like this:
> 
> ```sql
> SELECT teacher.*
> FROM teacher
> WHERE teacher.code = ?
>     AND EXISTS (    SELECT 1
>                     FROM person
>                         INNER JOIN teacher
>                             ON person.id = teacher.person_id
>                                 AND person.name_zh LIKE '%' || ? || '%' )
> ;
> ```
> 
> [You can test this here online and interactively.](http://jsqlformatter.manticore-projects.com/jsqlformatter/demo.html?args=-c%20MoUQMiDCAqAEAuBTAhgYwBaIE4DoBUAUAGIBKA8gLIIobYEDqAEiCSNWprqgPYAmisALywA-AVgTYAQQByAEVggAGgElg0YLAAUk2KAgxYARnG6z53aUqwADtgDO3AHamLbiypkyWsAFJlPdlosV3cw8zIZWwdnHABLXiEgzhw7LEcnAH0E0PC8s1kFNIycJ2QAW0RMgC90WDAVAGk2AHIAUhbYAB8u0W7e9s6ASgIAbiA)

oh, i see. i mistake. sub query is invalid. thank you very much.
