### ISSUE TITLE
CCJSqlParserUtil.parse( sql )     problem

### ISSUE THREAD

**Issue by zhuzi-tt** [JSQLParser/JSqlParser#1698]
version：  4.4

SQL：
SELECT
	`table_schema`,
	`table_name`,
	`table_type`,
	`engine`,
	`row_format`,
	`table_comment`,
	`table_collation`,
	`version`,
	`create_time` 
FROM
	`information_schema`.`tables` 
WHERE
	`table_schema` =(SELECT DATABASE()) 
ORDER BY
	`create_time` DESC 
	LIMIT 10;

Statement parse = CCJSqlParserUtil.parse(sql);

exception:
exception:
java.util.concurrent.ExecutionException: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "=" "="
    at line 14, column 23.

Was expecting one of:

    "&"
    "::"
    ";"
    "<<"
    ">>"
    "COLLATE"
    "CONNECT"
    "EMIT"
    "GROUP"
    "HAVING"
    "START"
    "["
    "^"
    "|"
    <EOF>

**Comment by zhuzi-tt** [comment]
test  code:  

    public static void main(String[] args) throws JSQLParserException {
        Statement parse = CCJSqlParserUtil.parse(
                "SELECT " +
                "table_schema," +
                "table_name," +
                "table_type," +
                "engine," +
                "row_format," +
                "table_comment," +
                "table_collation," +
                "version," +
                "create_time " +
                "FROM " +
                "information_schema.tables " +
                "WHERE " +
                "table_schema =(SELECT DATABASE()) " +
                "ORDER BY " +
                "create_time DESC");
        System.out.println(parse);
    }

**Comment by manticore-projects** [comment]
Greetings,

please use JSQLFormatter 4.6 Snapshot, which features a much better keyword handling.
[You can try it online here.](http://jsqlformatter.manticore-projects.com/jsqlformatter/demo.html?args=-c%20MoUQMiDCAqAEsBcCGAjANgUwPoGcDGAFhgLZIBQ8llANIqplgHZLEYVU13rYICeADmw6cMjAOYBLRkOGxaAJwD2AdywAzRfNIJ2w2sm5Y8i4q0Y7Zcrg2No0SBBMWNdHWgDcM8nE5eXaePIYDjwSrGQAYgBKAPIAsrBSGloOvriEJEgAdAaYOGQA6gASIFEg1tj4RKSwALywABTwoBAwsAAiDqhIOBgNAJSw-WQxUe2lsABCAJqwgcEIoawdIMCQZGAAknGbcACMAAxkANxAA)

Please close the issue after confirmation.

**Comment by wumpz** [comment]
Using the actual 4.6-SNAPSHOT version you are able to parse it. @manticore-projects changed the handling of brackets, so this `table_schema = (select database())` is parsed.

**Comment by wumpz** [comment]
At the moment I deploy the actual snapshot.

**Comment by manticore-projects** [comment]
Closed as answered and solved.
