### ISSUE TITLE
GROUP BY GROUPING SETS support

### ISSUE THREAD

**Issue by wumpz** [JSQLParser/JSqlParser#17]
We used "GROUPING SETS" and parser gives error for this.
Additionally, GROUP BY ROLLUP and GROUP BY CUBE may be supported with this, their syntax is similar.

 A DB2 SQL sample using "GROUPING SETS":

SELECT WEEK(SALES_DATE) AS WEEK,
         DAYOFWEEK(SALES_DATE) AS DAY_WEEK,
         SALES_PERSON, SUM(SALES) AS UNITS_SOLD  
  FROM SALES 
  WHERE WEEK(SALES_DATE) = 13
  GROUP BY GROUPING SETS ( (WEEK(SALES_DATE), SALES_PERSON),
                           (DAYOFWEEK(SALES_DATE), SALES_PERSON))
  ORDER BY WEEK, DAY_WEEK, SALES_PERSON

http://pic.dhe.ibm.com/infocenter/db2luw/v10r1/index.jsp?topic=%2Fcom.ibm.db2.luw.sql.ref.doc%2Fdoc%2Fr0059215.html

It is also supported by SQL Server and Oracle:
http://blogs.msdn.com/b/craigfr/archive/2007/10/11/grouping-sets-in-sql-server-2008.aspx
http://www.oracle-base.com/articles/misc/rollup-cube-grouping-functions-and-grouping-sets.php

**Comment by thebiguno** [comment]
We just ran into this issue in DB2.  Any chance that this would be added in 2.0?

Thanks!

**Comment by thebiguno** [comment]
Some sample SQL statements:

`SELECT COL_1, COL_2, COL_3, COL_4, COL_5, COL_6 FROM TABLE_1 GROUP  BY GROUPING SETS((COL_1, COL_2, COL_3, COL_4), (COL_5, COL_6)))` (basic example)

`SELECT COL_1, 
	COL_2, 
	COL_3, 
	EXTRACT(YEAR FROM my_function(COL_3)) AS Extracted_Year, 
	QUARTER(my_function(COL_3)) AS Extracted_Quarter, 
	EXTRACT(MONTH FROM my_function(COL_3)) AS Extracted_Month
FROM TABLE_1
WHERE
	EXTRACT(YEAR FROM my_function(COL_3)) > EXTRACT(YEAR FROM CAST(COL_4 AS DATE)) - 3
	AND EXTRACT(MONTH FROM my_function(COL_3)) <= EXTRACT(MONTH FROM CAST(COL_4 AS DATE))
GROUP BY
	GROUPING SETS(
		(COL_1, COL_2, COL_3, EXTRACT(YEAR FROM my_function(COL_3)), EXTRACT(MONTH FROM my_function(COL_3))),
		(COL_1, COL_2, COL_3, EXTRACT(YEAR FROM my_function(COL_3)), QUARTER(my_function(COL_3))),
		(COL_1, COL_2, COL_3, EXTRACT(YEAR FROM my_function(COL_3))),
		(COL_1, CASE WHEN COL_2 = '1234' THEN 'FOO' ELSE 'BAR' END)
	)
` (more complex sample; includes statements such as function, case, etc in the grouping set)

I don't have any examples of GROUP BY ROLLUP / GROUP BY CUBE in my report library, unfortunately.

**Comment by wumpz** [comment]
Is it right, that grouping sets are any list of expressions including an empty expression?

**Comment by thebiguno** [comment]
According to https://docs.oracle.com/cd/E49933_01/server.770/es_eql/src/reql_aggregation_grouping_sets.html :

>The GROUPING SETS syntax is:
>GROUPING SETS(groupingSetList)
>where groupingSetList is a single attribute, a comma-separated list of multiple attributes, CUBE, ROLLUP, or () to specify an empty group. The empty group generates a total. Note that nested grouping sets are not allowed.
>For example:
>GROUP BY GROUPING SETS(a, (b), (c, d), ())

From that, I would say that the empty expression is allowed.

Even if some DBs do not accept it, I feel that it should still parse correctly.
