### ISSUE TITLE
BigQuery except syntax

### ISSUE THREAD

**Issue by gabrielefantini** [JSQLParser/JSqlParser#1700]
Hi,
I found that the BigQuery except() syntax is not supported yet.
Do you plan to support it in the future?

**Comment by manticore-projects** [comment]
Greetings!

This is far away from any standard or common SQL.
But you can send us a PR or sponsor an implementation.

**Comment by manticore-projects** [comment]
I will work on it since I got some appetite for `DuckDB` and `ClickHouse`.

**Comment by hayssams** [comment]
Oh great thank you
