### ISSUE TITLE
Throwing exception for table alias 

### ISSUE THREAD

**Issue by nitinp11** [JSQLParser/JSqlParser#1701]
I am passing withAllowComplexSqlParsing true and withSquareBracketQuotation true but still it is throwing exception

ex.
1) Select col from schema.Table[Table_Suffix] T -> Unexpected Token "T"
2) Select col from schema.Table[Table_Suffix] as T -> Unexpected Token "as" "AS"
3) Select col from [schema]Table[Table_Suffix] as T -> Unexpected Token [Table_Suffix]  -> Most of the queries we have like this

**Comment by manticore-projects** [comment]
Greetings.

Your syntax looks very unusual and is not supported:
```sql
Select col from schema.Table[Table_Suffix] T;
Select col from [schema]Table[Table_Suffix] as T;
```

Supported T-SQL Syntax was:
```sql
Select [columnName] from [schemaName].[tableName] as T;
Select [columnName] from [catalogName].[schemaName].[tableName] as T;
```
[All supported Syntax is illustrated here.](https://www.manticore-projects.com/JSQLParser/syntax.html)

You will want to elaborate on your particular Database System and Syntax since it is unknown to us.

**Comment by nitinp11** [comment]
Thanks for replying !! 
We are having such sql syntax from hive DB

**Comment by manticore-projects** [comment]
Greetings.

Hive is largely unsupported although there have been many requests for supporting Hive here. Just browse the Issue List.

Since we do not use Hive for ourselves, Hive support will only happen when a third party sponsors an implementation.

**Comment by nitinp11** [comment]
Okay Thanks !!
