### ISSUE TITLE
There are aggregate functions in the subquery：string_agg

### ISSUE THREAD

**Issue by Lvbuqing** [JSQLParser/JSqlParser#1705]
I use the postgres database

![image](https://user-images.githubusercontent.com/32841009/210129050-41784432-d502-4ea8-8169-b9f2d4171031.png)
--------------------------
![image](https://user-images.githubusercontent.com/32841009/210129111-03084d69-e2b6-4841-a6aa-63f6751c94b0.png)

**Comment by manticore-projects** [comment]
Please provide your query as plain text.On 31 Dec 2022 08:31, Lvbuqing ***@***.***> wrote:
I use the postgres database

**Comment by Lvbuqing** [comment]
Sorry, my brother, I just used version 4.4，

I upgraded to 4.5 and solved my problem.

I'm sorry to bother you

**Comment by Lvbuqing** [comment]
Can I use version 4.5 in the production environment (official environment)?
I heard that there is a bug in version 4.5?
 The home page doesn't say you can use version 4.5 directly.

![image](https://user-images.githubusercontent.com/32841009/210289181-9b4ed82d-6e17-4629-9d29-17ff59ad52af.png)

**Comment by wumpz** [comment]
@Lvbuqing The released version is *4.5*. Sorry, I forgot to update the readme.

**Comment by Lvbuqing** [comment]
Maybe the readme file has not been updated, which makes others think that version 4.5 cannot be used。
thank you。
January 5, 2023 11:02:21
