### ISSUE TITLE
Encountered unexpected token: "Authorization" "AUTHORIZATION"

### ISSUE THREAD

**Issue by losador** [JSQLParser/JSqlParser#1707]
Got 
`net.sf.jsqlparser.JSQLParserException: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "Authorization" "AUTHORIZATION"` 
exception when trying to parse comment on table:
`COMMENT ON TABLE "Authorization" IS 'smth';`
It works when Authorization renamed to Authorizations

**Comment by manticore-projects** [comment]
Please use JSQLParser 4.6-SNAPSHOT, which has much better keyword handling.
[You can try it online here.](http://jsqlformatter.manticore-projects.com/jsqlformatter/demo.html?args=-c%20MIeQsmCiByAqAEJr1gQQEIBlLwESoFcAXACwHsAnASwC8BDIqsgO13gEkBleAcgGcAtqR4AoANxA)

**Comment by losador** [comment]
Can i use it in my project now?

**Comment by manticore-projects** [comment]
[Sure. Just change the maven artifact to snapshot.](http://217.160.215.75:8080/jsqlformatter/JSQLParser/usage.html#maven-artifacts)

**Comment by losador** [comment]
Its does not working with gradle

**Comment by manticore-projects** [comment]
Sure it does:
```
repositories {
    maven {
        url = uri('https://oss.sonatype.org/content/groups/public/')
    }
}

dependencies {
    implementation 'com.github.jsqlparser:jsqlparser:4.6-SNAPSHOT'
}
```

**Comment by losador** [comment]
Thanks, ill try a new version
