### ISSUE TITLE
COPY statement for Postgres is not supported.

### ISSUE THREAD

**Issue by gumberankush** [JSQLParser/JSqlParser#1709]
For example, the following statement is not supported
```
COPY public.vehicle (vehicleid, licenseplate, year, color, makeid, modelid, ownerid) FROM stdin;
```

**Comment by wumpz** [comment]
Right. JSqlParser does not support this. This iseems not to be a SQL construct.

**Comment by gumberankush** [comment]
@wumpz This is the statement from Postgres database. Are there any plans to handle this in future?

**Comment by manticore-projects** [comment]
Duplicate  #569
