### ISSUE TITLE
support alias for udfs with multi output columns

### ISSUE THREAD

**Issue by zuxqoj** [JSQLParser/JSqlParser#171]
when a apache-hive UDTF [https://cwiki.apache.org/confluence/display/Hive/DeveloperGuide+UDTF] output multi columns, we can not use alias for them in jsql parser, see this flowing sql:

select stack(1, key, value, key, value) as (a, b, c, d) from src limit 5;

**Comment by litianwang** [comment]
I have the same problem.

**Comment by ted-wq-x** [comment]
@litianwang me too

**Comment by wumpz** [comment]
You can apply multi columns to an alias, so

    myalias(a, b, c, d) 

works. But an alias name has to be specified.

**Comment by manticore-projects** [comment]
Duplicate #821
