### ISSUE TITLE
CCJSqlParserManager.parse error :Encountered unexpected token: "UNIQUE" "UNIQUE"

### ISSUE THREAD

**Issue by Hale-CHIOU** [JSQLParser/JSqlParser#1710]
I want to get table name from this sql:

```
create table demoTable
(
    id   bigint auto_increment primary key,
    name varchar(8) not null,
    age  int        not null,
    constraint uk_demo
        unique (name, age)
)
```
,but when code run to this place
```
TablesNamesFinder tablesNamesFinder = new TablesNamesFinder();
            Statement statement = pm.parse(new StringReader(sql));
```
console show the following error:
```
Encountered unexpected token: "UNIQUE" "UNIQUE"
    at line 19, column 2.

Was expecting one of:

    "ACTION"
    "ACTIVE"
    "ALGORITHM"
    "ARCHIVE"
    "ARRAY"
    "BYTE"
```
my jsql version is 4.2

**Comment by wumpz** [comment]
JSqlParser 4.6-SNAPSHOT is able to parse your statement.

**Comment by manticore-projects** [comment]
Closed since its working with the most recent version and no further questions have been asked.

**Comment by znnspace** [comment]
JSqlParser 4.6, This question also arises

**Comment by manticore-projects** [comment]
Statement is parsed correctly with JSQLParser 4.7 Snapshot.
[You can try it online here.](http://jsqlformatter.manticore-projects.com/jsqlformatter/demo.html?args=-c%20MIJQogggKmAEUQEIBk4BMCmBbA9gFwEMAjAGw1gAoAoWW2ASzTuecQEkBxNgOShdggBVKAHkA+j1BgAsmF6wACiDbSIIAJqwA0mHU06AGlgA7AlnL8AamuAAJNZQAcASljcRfboOTJ9tIwQA5hb8PHz8tO6e3r7MRsAi3ADKUCAQYbAArgDWYpi4fiyC3GwAioJwFCZmGAHBsM5UjQDcQA)

**Comment by znnspace** [comment]
![image](https://github.com/JSQLParser/JSqlParser/assets/25051018/4e79bb29-610c-4dab-9ae1-e35cb85125d2)

**Comment by manticore-projects** [comment]
You use a different statement obviously. Please share your statement and then I will be able to point out what exactly the problem is.
