### ISSUE TITLE
Encountered unexpected token: "temporary" "TEMPORARY"

### ISSUE THREAD

**Issue by pansong291** [JSQLParser/JSqlParser#1712]
MySQL:
```
drop temporary table if exists tmp_MwYT8N0z
```

**Comment by manticore-projects** [comment]
Greetings.

[The supported syntax are shown here.](https://manticore-projects.com/JSQLParser/syntax.html#drop)

**Comment by manticore-projects** [comment]
Leave it open as a reminder. I would look into it when I have a time.
