### ISSUE TITLE
Oracle - Alternative Quoting Mechanism (''Q'') for String Literals - parsing error

### ISSUE THREAD

**Issue by PowalaX** [JSQLParser/JSqlParser#1718]
Parsing Oracle statement:
  COMMENT ON COLUMN EMP.NAME IS q'{Name}';

CCJSqlParserUtil.parseStatements error:
net.sf.jsqlparser.JSQLParserException: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "Q" <S_IDENTIFIER>
    at line 1, column 31.

But, it's OK:
 select q'{Its good!}' from dual;

Another parsing error: 
  select q'{It's good!}' from dual;

**Comment by manticore-projects** [comment]
Greetings!

please check the [COMMENT Statement](https://manticore-projects.com/JSQLParser/syntax.html#comment).
It expects a [CHAR_LITERAL](https://manticore-projects.com/JSQLParser/syntax.html#s-char-literal) which does not understand the `q` Escape sequence.

Your `SELECT` example is not working either, just accidentally parsed as an `ALIAS`:
![image](https://user-images.githubusercontent.com/18080123/214807855-be7b25aa-74cb-45bf-8927-fa91d398fd03.png)

**Comment by manticore-projects** [comment]
Greetings!

I have fixed it partially via PR #1722 allowing at least common brackets such as `q'{..}'`, `q'[..]'`, `q'(..)'` and `q''..''`. A generic solution supporting any character is not (easily?) possible with JavaCC.
