### ISSUE TITLE
Project start up issue

### ISSUE THREAD

**Issue by 558632** [JSQLParser/JSqlParser#1720]
Hello,
build of project fails with exception. Could anyone advice me with this issue?
![Snímka obrazovky 2023-01-26 115154](https://user-images.githubusercontent.com/91661473/214818284-cfe92af9-c9d4-4a22-9c71-dba8f2f7785a.png)

**Comment by manticore-projects** [comment]
Greetings.

Looks like a problem with the JDK Version, maybe Gradle is not supported with your JDK.
You may try JDK 8/11/17.

**Comment by manticore-projects** [comment]
Closing this as not related to JSQLParser itself.
