### ISSUE TITLE
Can you support "lateral view explode"

### ISSUE THREAD

**Issue by xuyang198711** [JSQLParser/JSqlParser#1723]
Can you support "lateral view explode"?

**Comment by manticore-projects** [comment]
Greetings.

You would need to point out at least the RDBMS and specific syntax definition.

**Comment by xuyang198711** [comment]
hi~
hive.

Lateral View Syntax
lateralView: LATERAL VIEW udtf(expression) tableAlias AS columnAlias (‘,’ columnAlias)* 
fromClause: FROM baseTable (lateralView)*

Description
Lateral view is used in conjunction with user-defined table generating functions such as explode(). As mentioned in Built-in Table-Generating Functions, a UDTF generates zero or more output rows for each input row. A lateral view first applies the UDTF to each row of base table and then joins resulting output rows to the input rows to form a virtual table having the supplied table alias.

eg 
SELECT pageid, adid FROM pageAds LATERAL VIEW explode(adid_list) adTable AS adid;

**Comment by manticore-projects** [comment]
Greetings.

Thank you for the update. There are a few open issues on supporting `HIVE`, which seems to be special in many regards. As far as I understand, it's not a real RDBMS but rather a SQL interface to Hadoop.

So you either can provide or sponsor an implementation for support `HIVE` dialect.

**Comment by manticore-projects** [comment]
Duplicate #239
