### ISSUE TITLE
parsing failed by "sel"

### ISSUE THREAD

**Issue by wengchi0816** [JSQLParser/JSqlParser#1724]
parsing failed like as : 

String sql ="select a.* from schema.SDIR a  WHERE apip = ''  order by sel";
Select select1 = (Select) CCJSqlParserUtil.parse(sql);   //failed

because  keyword "sel" ,THX.

**Comment by manticore-projects** [comment]
Please see https://jsqlparser.github.io/JSqlParser/keywords.html
`SEL` is a restricted keyword and you will need to quote it properly:

```sql
SELECT a.*
FROM schema.sdir a
WHERE apip = ''
ORDER BY 'sel'
;
```

[Try it online here.](http://jsqlformatter.manticore-projects.com/jsqlformatter/demo.html?args=-c%20MoUQMiDCAqAECGA6AVAKAGICUDyBZWAzgMYAWApgLZIEAmAlgE4KoDqAEiJiAgA50+wAvLADkI1NkwARTrABCATVEEyAG3EBuIA)

**Comment by wengchi0816** [comment]
I understand, thank you.
