### ISSUE TITLE
[BUG] JSQLParser Version 4.5 : PostgreSQL : Encountered unexpected token: "%" "%"

### ISSUE THREAD

**Issue by volwap** [JSQLParser/JSqlParser#1726]
### Failing SQL Feature:
- Can't properly parse the statement when using pg_trgm
- Example: `word %> :query` or `word %>> :query` can't be parsed
- Table F.25. pg_trgm Operators https://www.postgresql.org/docs/current/pgtrgm.html 

### SQL Example:
- Simplified Query Example, focusing on the failing feature
```
SELECT word FROM words WHERE word %> :query ORDER BY word_similarity(word, :query) DESC, word
```

### Software Information:
- JSqlParser version 4.5
- Database PostgreSQL

### Stack Trace:
```
net.sf.jsqlparser.JSQLParserException: Encountered unexpected token: "%" "%"
    at line 1, column 41.

Was expecting one of:

    "&"
    "::"
    ";"
    "<<"
    ">>"
    "COLLATE"
    "CONNECT"
    "EMIT"
    "GROUP"
    "HAVING"
    "START"
    "["
    "^"
    "|"
    <EOF>
```

**Comment by manticore-projects** [comment]
Greetings!

Thank you for the good and detailed report.
Those specific Postgres pg_trgm Operators are not supported, as they are far away from any standard. Its really unfortunate that those operators were introduced instead of more compatible functions.

You can either provide or sponsor an implementation.

**Comment by volwap** [comment]
Yes, this is a potsgres extension that becomes available out of the box after executing `CREATE EXTENSION pg_trgm`.
Thanks for the quick response! I found a workaround where the parser is not needed.
