### ISSUE TITLE
Parse error on functions using the IN keyword

### ISSUE THREAD

**Issue by Inphi** [JSQLParser/JSqlParser#173]
I'm getting a ParseException when parsing:
"SELECT position("-" IN row_key) FROM hbase".

After trying out some more queries, i've deduced that JSqlParser isn't handling expressions (SimpleExpressions) containing the "IN" token. The grammar, JSqlParserCC.jjt, doesn't accept IN as a lookahead for a SimpleExpression, but only accepts '&' and '|'. This may explain why the query doesn't work.

**Comment by wumpz** [comment]
Maybe PrimaryExpression would be a better place. But I am not sure if this would result in the right usage of "x in y". One could write an SQL like

select x in y from my table

Would that be correct? Does this deliver a boolean? On the other hand for position it is a simple type of specifying the parameters, when you will some kind of syntactic sugar.

**Comment by Inphi** [comment]
"select x in y from mytable" is valid SQL according to SQL2003 (see http://savage.net.au/SQL/sql-2003-2.bnf.html), though, I don't know of if any vendor implements it. The Position syntax is typically used as a sugar for functions like CHARINDEX (for MSSQL) or LOCATE (for MYSQL). However, the vendor i'm using, Apache Drill, doesn't provide alternatives, which means position(substr IN str) is my only option. 
As far as I can tell from the SQL2003 bnf, the position syntax is indeed valid.

**Comment by wumpz** [comment]
Sorry for the late answer. It was new to me that "select x in y from mytable" is valid. Then PrimaryExpression would be the right place to start. I think it would cause a lot of lookahead troubles because of InExpression:

select * from mytable where a in b in (select true from mytable2)

**Comment by Inphi** [comment]
Yes you're right, PrimaryExpression is better.
The lookahead will be a bit tricky as there are a bunch of conflicts with the other choices. If you're worried about the performance of a naive choice like "LOOKAHEAD(InExpression()) {...}", you could add it as the final choice, so that it's only used as a last resort.

**Comment by wumpz** [comment]
already solved
