### ISSUE TITLE
Parser fail to parse BigQuery statement

### ISSUE THREAD

**Issue by gabrielefantini** [JSQLParser/JSqlParser#1734]
### Grammar or Syntax Description
The statement uses a BigQuery syntax. The ```(``` after the ```as``` generates the error. If I remove the parenthesis the parser recognizes the statement.

### SQL Example
```
create or replace table payment
    OPTIONS()
    as (
with stg_customers as (
  select
    customer_id,
    email
  from customers_tmp
),
stg_payments as (
  select
    customer_id,
    store_id,
    film_id,
    actor_id,
    amount,
    EXTRACT(MONTH FROM payment_date) as month,
    EXTRACT(YEAR FROM payment_date) as year
  from payment_tmp
)
select
  customer_id,
  email as customer_email,
  store_id,
  film_id,
  actor_id,
  amount,
  month,
  year
from stg_customers
left join stg_payments using (customer_id)
);
```

### Additional context
The used JSQLParser Version --> 4.2

**Comment by manticore-projects** [comment]
Greetings,

works with JSQLParser 4.6 Snapshot. [You can test it online here.](http://jsqlformatter.manticore-projects.com/jsqlformatter/demo.html?args=-c%20MYJwpghgLmAED2JbgA4BsLDlCAjNcKEAngLZgB2UAULHbAPIAKAKgJIMByAygBQCUtehADOsXtQDuASygALWCKgBzAPrAArkvjkQY0eKEiwBYDXqxN23aukATADRC6YUhGlohAMxA7LWqB0wPVUoUhRqficlNSIySih9MQk6Y1NzeitAm3snC21wW0dnWC8PUiK84TNESpKIUngNKiq6AFEADRYAJQBBAGEWXgBZLhYACVgAMW6GYdg48ipVO2gwflgDRqo5VthOnoGhgE023u7p2fnFhJW1jYNiSBBvX1IFkiWoUPDI6jSwGYhFkgiA6i43B5NmIQTZXO40FUCmBwaVyqjMIEwbkhA0mi0hNt5FUnhAXj4-DF1AFQSJqAQvFBYAAreDSCiKFSqG5UMRadnKcSw4JFQT8ADc1CAA)

**Comment by gabrielefantini** [comment]
Thanks a lot for the answer.
Have a nice day.
