### ISSUE TITLE
[BUG] JSQLParser 4.6 : count(*) is not interpreted as a Function with allColumn true anymore

### ISSUE THREAD

**Issue by tmortagne** [JSQLParser/JSqlParser#1736]
### Failing SQL Feature:

I upgraded from JSqlParser 4.2 to 4.6 (mainly because of #1444) and there seems to be a change in the way `count(*)` is parsed: `Function#isAllColumns` now returns false.

To reproduce:

```
Select select = (Select) CCJSqlParserUtil.parse("select count(*) from XWikiSpace");
PlainSelect plainSelect = (PlainSelect) select.getSelectBody();
Function function = (Function) plainSelect.getSelectItems().get(0);
function.isAllColumns();
```

**Comment by manticore-projects** [comment]
Seems to be an oversight, I will look into this.

**Comment by manticore-projects** [comment]
Greetings.

I am not sure about this and think there is a confusion between `SELECT Function( ALL a, b, c)` and `SELECT Function(*)` or `SELECT Function(a.*)`.

**Comment by manticore-projects** [comment]
If you want to know, if `AllColumns` or `AllTableColumns` was used then:

```java
    if (parameters!=null) {
            List<Expression> expressions = parameters.getExpressions();
            // Not sure about this, I assume that AllColumns can be used only alone without further parameters
            if (expressions.size()==1) {
                Expression expression = expressions.get(0);
                return expression instanceof AllColumns || expression instanceof AllTableColumns;
            }
        }
```

**Comment by tmortagne** [comment]
Indeed, isAllColumns seems obvious back then for this example (epecially since I did not know about the `ALL` keyword), but there is no reason for this information to be at table function level.

Thanks for the suggestions.

**Comment by manticore-projects** [comment]
So can we close this please?

**Comment by tmortagne** [comment]
Yes, looks like something to close.
