### ISSUE TITLE
How to ignore The  #{0-9a-zA-Z-_}

### ISSUE THREAD

**Issue by javaoffers** [JSQLParser/JSqlParser#1738]
Always check against the **Latest SNAPSHOT of JSQLParser** and the [Syntax Diagram](https://jsqlparser.github.io/JSqlParser/syntax.html)

### Failing SQL Feature:
![image](https://user-images.githubusercontent.com/63859342/222662786-aa9c3f02-1fd0-4cfc-91b7-4faa4d62aad9.png)

### SQL Example:
![image](https://user-images.githubusercontent.com/63859342/222662954-58bcc263-6dd8-4c33-b8d0-08e4acf40a82.png)

How can I set it so that he ignores the expression in #{xx} . 
 ( String p = "(\\#\\{[0-9a-zA-Z-_]+\\})";)

### Software Information:
- mysql

### Tips:
Please write in English and avoid Screenshots (as we can't copy and paste content from it).
[Try your example online with the latest JSQLParser](http://217.160.215.75:8080/jsqlformatter/demo.html) and share the link in the error report.
Do provide Links or References to the specific Grammar and Syntax you are trying to use.

**Comment by manticore-projects** [comment]
Greetings.

Supported Parameter Syntax are `:parameterName` or `?` or `?1`. Your construct `#{...}` is not supported.
You could apply a simple `String#replace(...)` before parsing your query or use standard compliant syntax.

**Comment by javaoffers** [comment]
What should I do if I want to modify the placeholder symbol For example, insert into user (name, phone_num) values (?,?) After parsing, insert into user (name, phone_num) values (?, encrypt (?)) , the phone_ num placeholder  is processed.  At present, I have rewritten JdbcParameter Is there any other way? thanks

**Comment by manticore-projects** [comment]
For placeholders, its more common to use `${..}` or `$..`.

**Comment by javaoffers** [comment]
> 
yes, But for now we're intercepting the underlying sql. Because the framework in the company doesn't use ${...}.

**Comment by javaoffers** [comment]
Now I add a tag in the JdbcParameter attribute, the tag of the default value is "?" . And the "?" in the toString method I'm going to replace it with tag. We modified the tag to meet our  requirements.

**Comment by manticore-projects** [comment]
Closed since it seems to have been explained and solved.
