### ISSUE TITLE
[BUG] JSQLParser fetch next statement can't support name parameter parser

### ISSUE THREAD

**Issue by gderemetz** [JSQLParser/JSqlParser#1739]
### Failing SQL Feature:
fetch next statement can't support name parameter parser

### SQL Example:
```
SELECT table_schema 
FROM information_schema.tables 
fetch next :variable rows only;
```

### Software Information:
- JSqlParser version : 4.6
- Database : Oracle

**Comment by manticore-projects** [comment]
Greetings.

https://jsqlparser.github.io/JSqlParser/syntax.html#fetch

Good catch, it seems to support `SimpleParameter` only -- which is a mistake of course.
I will correct it, thanks for reporting.

**Comment by gderemetz** [comment]
thank you for the quick response
Can you give me an estimate of how long it will take to fix the bug?

**Comment by manticore-projects** [comment]
I'll do that tomorrow.
