### ISSUE TITLE
[FEATURE] support expressions where after called function two and more fields can be called

### ISSUE THREAD

**Issue by nikolayandr** [JSQLParser/JSqlParser#1742]
### Grammar or Syntax Description
- Allow defining calling of function where returned attribute also might have inner attributes
- Example: `f1(arguments).f2.f3 = 1` clause is not supported yet

### SQL Example
- Simplified Query Example, focusing on the failing feature
    ```f1(arguments).f2.f3 = 1```

- `net.sf.jsqlparser.JSQLParserException: Encountered unexpected token: "=" "="
    at line 1, column 21. Was expecting one of: "("`

### Additional context
used version: 4.6

### Tips:

Use `net.sf.jsqlparser.parser.CCJSqlParserUtil#parseCondExpression(java.lang.String)` to parse condition
The current workaround to get it somehow working is: `f1(arguments).f2.f3() = 1`

**Comment by manticore-projects** [comment]
Greetings.

Thank you for the feature request. I think is a Duplicate #1050.
What RDBMS does support such syntax please?  `Clickhouse` is not too well supported at the moment and like this won't change unless an implementation is provided or a sponsor shows up.

**Comment by manticore-projects** [comment]
Seeing the country, all possible support is a must. I have provided an implementation based on my limited understanding.
Please test it thoroughly and feel most welcome to add further samples or details.

**Comment by nikolayandr** [comment]
Hi @manticore-projects 

I appreciate your help and thanks for supporting Ukraine. I confirm your changes make it possible to parse conditions mentioned in this feature request

> What RDBMS does support such syntax please? 
So, actually no one RDBMS, I'm working on project where there is a necessity to convert
syntactic structures that represent a path of fields from graphql types to datomic specific datalog query, let me show you some example:

```
enum Role {
 ADMIN
 CUSTOMER
}
type Organization{
 code: String
 users(role: Role): [User!]
}

type User {
  code: String @unique
  favoriteProducts: [Product!]
}

type Product {
  name: String @localized
  code: String
}
```

Query to get organizations which have admin users which have favorite product with specific code

`users(ADMIN).favoriteProducts.code = @code`

The above query parsed by jsqlparser and converted into datomic query

**Comment by manticore-projects** [comment]
No problem, I would work on those statements just to show my little bit of morale support.
Would take 1-3 days though, depending on the workload.

**Comment by nikolayandr** [comment]
Hi @manticore-projects, an interesting case happens after upgrading from `4.7` to `4.8`. I confirm `4.8` still supports expressions like `f1(arguments).f2.f3 = 1`  but it also was possible to successfully convert expressions like `f1(a1=1).f2.f3 = 1` using `4.7.`, which is not possible after upgrading to `4.8`. 

Unsuccess case on 4.8
![image](https://github.com/JSQLParser/JSqlParser/assets/4941456/e2800918-a4b8-443a-b4dc-94beb1ac8ff5)

Success case on 4.7.
![image](https://github.com/JSQLParser/JSqlParser/assets/4941456/f2495c62-7f3c-4f9f-9426-b52a448de51c)

Sorry for boring you with such a rare case

**Comment by nikolayandr** [comment]
@manticore-projects 

Even one more interesting case, the next expression `f1(a1=1).f2 = 1` is succesfully parsed on 4.6(the version before supporing the current feature) and  `4.7`:
![image](https://github.com/JSQLParser/JSqlParser/assets/4941456/a660e345-797e-4ff7-aeea-aaae0d4c6064)

but the same expression is not parsed correctly on `4.8`:
![image](https://github.com/JSQLParser/JSqlParser/assets/4941456/25e8b828-145d-4c03-af9d-39ceaf8bd000)

Looks like it is a more generic issue not exactly related to the current feature support request
