### ISSUE TITLE
[BUG] JSQLParser 4.6: RDBMS : SetStatement getName returns Object instead of String or NameExpr

### ISSUE THREAD

**Issue by rhuddbiz** [JSQLParser/JSqlParser#1746]
### Software Information:
- JSqlParser 4.6

net.sf.jsqlparser.statement.SetStatement.getName() returns Object whereas in 4.5 it returned a String. There is no method that returns a getName method maybe should return NameExpr instead of String, I'm not sure of the expected behavoir, but the Object seems incorrect.

**Comment by manticore-projects** [comment]
Greetings.

It is explicitly defined as an `Object` for making variable assignments possible, such as:

```sql
set @Flag = 1
```

or

```sql
SET @@global.time_zone = '01:00'
```

Whenever you get an Object, you can use `toString()` to get your expected String.

**Comment by rhuddbiz** [comment]
Ok, but why upcast from NameExp to Object ? I'd prefer to work with a NameExp which is the internal variable type .

**Comment by manticore-projects** [comment]
> Ok, but why upcast from NameExp to Object ? I'd prefer to work with a NameExp which is the internal variable type .

The `Name` of the `NameExp` can be a `UserVariable` or a `String`.
The method `getName` returns this `Name` of the `NameExpression`, but not the `NameExpression` itself.

Although it would make sense to provide a Getter/Setter for the `NameExpression`

**Comment by rhuddbiz** [comment]
The commit looks like it will solve my issue, thank you so much !
