### ISSUE TITLE
[BUG] JSQLParser Version 4.6 : PostgreSQL : Encountered unexpected token: "," "," when parse upsert sql

### ISSUE THREAD

**Issue by Venus-WXP** [JSQLParser/JSqlParser#1749]
Always check against the **Latest SNAPSHOT of JSQLParser** and the [Syntax Diagram](https://jsqlparser.github.io/JSqlParser/syntax.html)

### Failing SQL Feature:
I use the plain PostgreSQL upsert syntax.

### SQL Example:
- Simplified Query Example, focusing on the failing feature
    ```sql
    INSERT INTO re_rule_mapping ( id, created_time, last_modified_time, rule_item_id, department_id, scene, operation )
                VALUES
                    ( '1', now( ), now( ), '1', '11', 'test', 'stop7' ),
                    ( '2', now( ), now( ), '2', '22', 'test2', 'stop8' ) ON CONFLICT ( rule_item_id, department_id, scene ) 
                DO UPDATE
                SET operation = excluded.operation
    ```
but change to the following sql works perfectly:
```sql
INSERT INTO re_rule_mapping ( id, created_time, last_modified_time, rule_item_id, department_id, scene, operation )
                VALUES
                    ( '1', now( ), now( ), '1', '11', 'test', 'stop7' ),
                    ( '2', now( ), now( ), '2', '22', 'test2', 'stop8' ) ON CONFLICT ON CONSTRAINT uk_re_rule_mapping
                DO UPDATE
                SET operation = excluded.operation
```

Note: [rule_item_id, department_id, scene]  is a unique constraint named 'uk_re_rule_mapping' in my db table

### Software Information:
- JSqlParser version 4.6
- Database (PostgreSQL15)

### Tips:
Errors:
```log
net.sf.jsqlparser.JSQLParserException: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "," ","
    at line 4, column 88.

Was expecting:

    ")"


	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parseStatement(CCJSqlParserUtil.java:263)
```

**Comment by manticore-projects** [comment]
Greetings.

`ON CONFLICT ( rule_item_id, department_id, scene ) ` is not supported for multiple columns.

Duplicate #1633

**Comment by Venus-WXP** [comment]
> Greetings.
> 
> `ON CONFLICT ( rule_item_id, department_id, scene ) ` is not supported for multiple columns.
> 
> Duplicate #1633

Ok, thanks
