### ISSUE TITLE
Support for REFERENCES keyword in a CREATE TABLE

### ISSUE THREAD

**Issue by gregvalcourt** [JSQLParser/JSqlParser#175]
I'd like to see support for REFERENCES keyword in a CREATE TABLE. I'm getting ParseExceptions when trying to parse my table creating scripts.

**Comment by wumpz** [comment]
Could you give a concrete SQL using REFERENCES?

**Comment by gregvalcourt** [comment]
create table test (
   id long, 
   fkey long references another_table(id)
);

**Comment by wumpz** [comment]
I tested it within v0.9.5 and it parsed successfully. I guess 0.9.4 should work because there were no modifications regarding this. Maybe there is a different reason.
