### ISSUE TITLE
[BUG] JSQLParser 4.4 : PostgreSQL : the word 'RS' is a reserved keyword? sql sentence contained 'RS' can't be parsed.

### ISSUE THREAD

**Issue by young0098** [JSQLParser/JSqlParser#1750]
Always check against the **Latest SNAPSHOT of JSQLParser** and the [Syntax Diagram](https://jsqlparser.github.io/JSqlParser/syntax.html)

### Failing SQL Feature:
- Brief description of the failing SQL feature
- Example: `RS` can't be parsed

### SQL Example:
- Simplified Query Example, focusing on the failing feature
    ```sql
    select rs from table1
    ```

### Software Information:
- JSqlParser 4.4
- Database (PostgreSQL )

###Parse Error Msg:
net.sf.jsqlparser.JSQLParserException: Encountered unexpected token: "rs" <K_ISOLATION>
    at line 1, column 8.

Was expecting one of:

    "*"
    "STRAIGHT_JOIN"

### Tips:
Please write in English and avoid Screenshots (as we can't copy and paste content from it).
[Try your example online with the latest JSQLParser](http://217.160.215.75:8080/jsqlformatter/demo.html) and share the link in the error report.
Do provide Links or References to the specific Grammar and Syntax you are trying to use.

**Comment by manticore-projects** [comment]
Greetings,

please [try with JSQLParser-4.6](http://jsqlformatter.manticore-projects.com/jsqlformatter/demo.html?args=-c%20MoUQMiDCAqAEBOBnAUAMQEoHkCysAuAhgEYA2ApgIzIDcQA) which has a better Keyword handling.

It works with JSQLParser 4.6.
