### ISSUE TITLE
[BUG] JSQLParser 4.6 : MySQL : JSON_OBJECTAGG fails with table prefixes

### ISSUE THREAD

**Issue by tomershay** [JSQLParser/JSqlParser#1753]
The following query parses ok:
`SELECT JSON_OBJECTAGG( KEY foo VALUE bar) FROM dual`

But this one doesn't (only change is adding prefixes to column names:
`SELECT JSON_OBJECTAGG( KEY q.foo VALUE q.bar) FROM dual`

Also, this alternative is valid but fail parsing:
`SELECT JSON_OBJECTAGG(foo, bar) FROM dual`

**Comment by manticore-projects** [comment]
[This is the current implementation](https://jsqlparser.github.io/JSqlParser/syntax.html#jsonaggregatefunction).

**Comment by manticore-projects** [comment]
At least in Oracle, this seem to have changed only recently: https://docs.oracle.com/en/database/oracle/oracle-database/21/sqlrf/JSON_OBJECTAGG.html

**Comment by manticore-projects** [comment]
Sorry for taking so long!
