### ISSUE TITLE
[BUG] JSQLParser Version : RDBMS : Encountered unexpected token: "\n\n\n" <ST_SEMICOLON>

### ISSUE THREAD

**Issue by HaijieChen** [JSQLParser/JSqlParser#1756]
Always check against the **Latest SNAPSHOT of JSQLParser** and the [Syntax Diagram](https://jsqlparser.github.io/JSqlParser/syntax.html)

### Failing SQL Feature:
- Encountered unexpected token: "\n\n\n" <ST_SEMICOLON>

### SQL Example:
- Simplified Query Example, focusing on the failing feature
    ```sql
     INSERT INTO s_user_territory_name  ( id,


created_user,

last_modified_user,

territory_name,
territory_name_list,
territory_id,
territory_id_list )  VALUES  ( ?,


?,

?,

?,
?,
?,
? )
    ```

### Software Information:
- JSqlParser version ：4.6
- Database ： MYSQL

**Comment by manticore-projects** [comment]
Greetings.

in general [example parses just fine.](http://jsqlformatter.manticore-projects.com/jsqlformatter/demo.html?args=-c%20JIOQygogSgKgBKGB5OBnA+gV1QUwE7oAu+eAloQPZ4Ce6AdgIYC2OcAFAFBzdykAmXHgBo4AYzw4GxPllx5B3EQBsGqQuiYU+pAGakcM7PgVwRxPGUo16zHCbMlyVWoxbolpNfbjnLz9Pzevk7W-O6ehHAAlBwAagCCADIAqhBg7DxwAPwiOdkmmZm5xfmFZabZ0RwA3EA)

However, two empty lines are interpreted as Statement terminator, so you will want to avoid those redundant empty lines.

**Comment by HaijieChen** [comment]
ok thanks,But  Mybatis-plus use jsqlparser.    It can not resove   this sql  as " where Lower(field)=?" with jsqlparser 4.4. So   I upgrade to 4.6. But Mysql-Plus  generate Insert sql have two empty lines. I'm going crazy.
Thank For  Response.

**Comment by manticore-projects** [comment]
> But Mysql-Plus generate Insert sql have two empty lines

Maybe report this as an issue to `Mybatis-plus`. I do not see any good reason why a SQL statement should contain 2 empty lines.

**Comment by HaijieChen** [comment]
Ok,I will do it.
