### ISSUE TITLE
"{d 'yyyy-mm-dd'}" dates not generated correctly

### ISSUE THREAD

**Issue by miguelocarvajal** [JSQLParser/JSqlParser#176]
I have an issue where a SQL statement that contains:

BETWEEN {d '2015-09-19'} AND {d '2015-09-24'}

generates

BETWEEN net.sf.jsqlparser.expression.DateValue@6b769be2 AND net.sf.jsqlparser.expression.DateValue@5607f775

DateValue class does not have the toString method, I'm just not sure what the best way to implement this would be.

**Comment by wumpz** [comment]
You are right. Missed it. Within the actual SNAPSHOT it should work. Cheers and thx for using JSqlParser.
