### ISSUE TITLE
How to convert Statement to Expression

### ISSUE THREAD

**Issue by kevin2000** [JSQLParser/JSqlParser#1764]
the target sql is "select * from table2 where id in (SELECT id FROM table1 WHERE find_in_set(100, ancestors))"

the follow code will throw exception that  Statement cant convert to Expression
InExpression expression = new InExpression();
expression.setLeftExpression(new Column(deptColumn));
 Statement subSelect = CCJSqlParserUtil.parse("SELECT id FROM table1 WHERE find_in_set(100, ancestors)");
expression.setRightExpression((Expression) subSelect);

**Comment by manticore-projects** [comment]
Greetings.

Yes, your observation is correct because `SubSelect` is an `Expression`, but not a `Statement`.
So you have to options:

1) Build a new `SubSelect` using the Java API.
2) Parse the `SubSelect` as an Expression:
```java
SubSelect subSelect = (SubSelect) CCJSqlParserUtil.parseExpression("SELECT id FROM table1 WHERE find_in_set(100, ancestors)");
InExpression expression = new InExpression();
expression.setLeftExpression(new Column(deptColumn));
expression.setRightExpression( subSelect );
```

**Comment by manticore-projects** [comment]
It's just pure coincidence, that I have provided PR #1754 which changes exactly that behaviour and makes the former `SubSelect` a normal Statement (and Expression). 

So when you checkout this PR #1754, the following will work:
```java
    @Test
    void testSubJoinParsing() throws JSQLParserException {
        String sqlStr = "SELECT id FROM table1 WHERE find_in_set(100, ancestors)";
        Select select = (Select)  CCJSqlParserUtil.parse(sqlStr);

        InExpression inExpression = new InExpression();
        inExpression.setLeftExpression(new Column("id"));
        inExpression.setRightExpression( select );

        Assertions.assertEquals("id IN SELECT id FROM table1 WHERE find_in_set(100, ancestors)", inExpression.toString());
    }
```
