### ISSUE TITLE
[BUG] JSQLParser Version : 4.6 : please add convert() support

### ISSUE THREAD

**Issue by xm0012008** [JSQLParser/JSqlParser#1767]
Always check against the **Latest SNAPSHOT of JSQLParser** and the [Syntax Diagram](https://jsqlparser.github.io/JSqlParser/syntax.html)

### Failing SQL Feature:
- convert(student_name using gbk)  can't be parsed
- Exception in thread "main" net.sf.jsqlparser.JSQLParserException: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "(" "("
    at line 1, column 54.

### SQL Example:
- Simplified Query Example, focusing on the failing feature
    ```sql
    select * from tb_student_information order by convert(student_name using gbk) COLLATE gbk_chinese_ci desc
    ```

### Software Information:
-  4.6
- mysql

### Tips:
Please write in English and avoid Screenshots (as we can't copy and paste content from it).
[Try your example online with the latest JSQLParser](http://217.160.215.75:8080/jsqlformatter/demo.html) and share the link in the error report.
Do provide Links or References to the specific Grammar and Syntax you are trying to use.

**Comment by manticore-projects** [comment]
"ChatGPT, show how to implement a SQL:2016 compliant CONVERT expression in JSQLParser"

**Comment by manticore-projects** [comment]
Duplicate #1257

**Comment by xm0012008** [comment]
thanks!
