### ISSUE TITLE
[BUG] JSQLParser Version 4.6: CCJSqlParserUtil.parse adds extra space in Select Column when it has a CAST to datatype

### ISSUE THREAD

**Issue by jovistruck** [JSQLParser/JSqlParser#1769]
### Failing SQL Feature:
`CCJSqlParserUtil.parse(sql)` adds a space to the CAST data type
 
E.g. 
` CAST(NOW() AS varchar(29)) AS cdap_consol_load_date` 
is returned as 
` CAST(NOW() AS varchar (29)) AS cdap_consol_load_date`

### SQL Example:
```
SELECT 
  CAST(NOW() AS varchar(29)) AS cdap_consol_load_date
FROM db.op_case
```

### Software Information:
- JSqlParser version: 4.6

### Tips:
Execution
```
        String sql = "SELECT \n" +
                "        CAST(NOW() AS varchar(29)) AS cdap_consol_load_date\n" +
                "       FROM db.op_case";

        System.out.println(CCJSqlParserUtil.parse(sql));
        //Bug:space added -> SELECT CAST(NOW() AS varchar (29)) AS cdap_consol_load_date FROM db.op_case
```

**Comment by manticore-projects** [comment]
Yes, but we do not consider this wrong or a bug since de-parsing any parsed statement is fully at the discretion of JSQLParser.

**Comment by manticore-projects** [comment]
Won't fix.
