### ISSUE TITLE
Reserved keyword as alias

### ISSUE THREAD

**Issue by tbrielle** [JSQLParser/JSqlParser#177]
Hi,

First of all, thank you for your great parser !

Some users import a set of predefined TSQL statements in my application that are executing fine within MSSQL. Unfortunately some of them fail in parsing with JSQLParser (0.9.4) during the import.

Example:

```sql
SELECT * FROM mytable1 t JOIN mytable2 AS prior ON t.id = prior.id
```

MSSQL seems to be a little bit more lenient and accepts the "prior" reserved keyword as an alias. As a workaround, I can tell these users to add square brackets to the alias like this:

```sql
SELECT * FROM mytable1 t JOIN mytable2 AS [prior] ON t.id = [prior].id
```

But it is hard for me to explain this constraint while the query is running fine in their SQL Server Management Studio.
Is there any chance that JSQLParser could support reserved keywords in aliases in the future ?

Thank you

**Comment by wumpz** [comment]
Jdqlparser allows already some keywords there. Prior could be added very easily. I will look into it.

**Comment by tbrielle** [comment]
Great news ! Thank you very much for your prompt reply.
