### ISSUE TITLE
[BUG] "WITH" item using "GROUP BY" clause cannot be parsed

### ISSUE THREAD

**Issue by csakhogy** [JSQLParser/JSqlParser#1774]
### Failing SQL Feature:
- ParseException: Encountered unexpected token: "group" "GROUP"
- Example: `WITH` item using GROUP BY (and optionally HAVING) clause(s) cannot be parsed

### SQL Example:
with mytbl as (select owner, count(*) from all_tables group by owner)
select *
from mytbl

### Software Information:
- JSqlParser version 4.60
- Oracle v19c

**Comment by manticore-projects** [comment]
Greetings.

I can not reproduce your concern as it parses without any problem here.
[You can test it online and interactively.](http://jsqlformatter.manticore-projects.com/jsqlformatter/demo.html?args=-c%20OoSQKgEgBAtgngFwEYBsoEEDKUAUAoKQowzAUQBlSBhMQgewHcA7AUwCcDivuAaKKugFcmCHFABUUAJSduAMQBKAeQCyUAIYoUAfQTrULAM6yuAcWUBVAApQAQgE0ojVm2l4ylGhLyLVsRKh4ANxAA)

**Comment by csakhogy** [comment]
Sorry, my fault, I over-simplified the sample SQL script. The bug appears when the statement has both GROUP BY and HAVING and one changes the order of them which is - somewhat in contrast to SQL standards - allowed in Oracle dialect.
To be closed.

**Comment by manticore-projects** [comment]
@Todo: Implement Oracle's `HAVING` before `GROUP BY` .
