### ISSUE TITLE
[BUG] "(INNER) JOIN" is not recognized by isInner() method

### ISSUE THREAD

**Issue by csakhogy** [JSQLParser/JSqlParser#1775]
### Failing SQL Feature:
- Join.isInner() method does not return TRUE as expected when the optional keyword 'INNER' is ommitted from SQL-standard syntax "(INNER) JOIN".

### SQL Example:
 - tbd

### Software Information:
- JSqlParser version: 4.60
- Database: any

### Tips:
none.

**Comment by manticore-projects** [comment]
Yes, because `Join.isInner()` solely indicates if the `INNER` keyword is present but does not give any information about the execution plan. See, we need to De-Parse the `JOIN` expression and need to know if to print (or not) the `INNER` keyword.

**Comment by csakhogy** [comment]
Would not be useful having "by default" a method that tells they type of Join component of SQL script? Or is there such I have not found yet? Though I easily overcome this by a helper method calling all availabe .IsInner(), .isLeft(), etc, binary "questions"...
