### ISSUE TITLE
[FEATURE] lateral view

### ISSUE THREAD

**Issue by minskya** [JSQLParser/JSqlParser#1777]
### Grammar or Syntax Description
- LATERAL VIEW [ OUTER ] generator_function ( expression [ , ... ] ) [ table_alias ] AS column_alias [ , ... ]

### SQL Example
CREATE TABLE person (id INT, name STRING, age INT, class INT, address STRING);
INSERT INTO person VALUES
    (100, 'John', 30, 1, 'Street 1'),
    (200, 'Mary', NULL, 1, 'Street 2'),
    (300, 'Mike', 80, 3, 'Street 3'),
    (400, 'Dan', 50, 4, 'Street 4');

SELECT * FROM person
    LATERAL VIEW EXPLODE(ARRAY(30, 60)) tableName AS c_age
    LATERAL VIEW EXPLODE(ARRAY(40, 80)) AS d_age;

### Additional context
This is to support something close to spark syntax 
https://spark.apache.org/docs/latest/sql-ref-syntax-qry-select-lateral-view.html#syntax

**Comment by manticore-projects** [comment]
Duplicate https://github.com/JSQLParser/JSqlParser/issues/239
Duplicate #1723
