### ISSUE TITLE
Support "RETURNING INTO" part of Insert/Update/Delete statement

### ISSUE THREAD

**Issue by ZhengguanLi** [JSQLParser/JSqlParser#1780]
Hello,

We are using JSqlParser to parse Oracle PL/SQL statement, and the statement with `returning ... into ...` can't be parsed. For example: `begin insert into table (col1) values (sysdate) returning id into new_id; commit; end`. Please add support of `RETURNING INTO` clause in INSERT/UPDATE/DELETE statement.
```
Encountered unexpected token: "into" "INTO"
    at line 1, column 57.

Was expecting one of:
    "&"
    "::"
    "<<"
    ">>"
    "["
    "^"
    "|"
    "<ST_SEMICOLON>"
```

**Comment by manticore-projects** [comment]
Greetings.

`INSERT INTO ... RETURNING ...` is actually [supported](https://manticore-projects.com/JSQLParser/syntax.html#insert) but without the the Oracle specific ` RETURNING ... INTO ...`.
I will add it.

**Comment by ZhengguanLi** [comment]
Do we have a rough date on when this feature can be added or which version? Thanks!

**Comment by manticore-projects** [comment]
Tomorrow evening, Version 5.0 SNAPSHOT.

**Comment by manticore-projects** [comment]
Done via [4fb1cfb](https://github.com/JSQLParser/JSqlParser/pull/1778/commits/4fb1cfbde1462082a6031c5a7f402880558cb9a8) with PR #1778
