### ISSUE TITLE
[BUG] JSQLParser Version : RDBMS : failing feature description

### ISSUE THREAD

**Issue by swansrp** [JSQLParser/JSqlParser#1782]
Always check against the **Latest SNAPSHOT of JSQLParser** and the [Syntax Diagram](https://jsqlparser.github.io/JSqlParser/syntax.html)

### Failing SQL Feature:
- I have a sqlserver sql which field name is the sqlserver keyword, but it cant be parse correctly.
- such as select [name] from table where 1=1
- [name] will be pointed as a mistake

### SQL Example:
- Simplified Query Example, focusing on the failing feature
SELECT  
 SLAName,ParentAccountIdYomiName,bidr_provinceidName,ParentContactIdYomiName,bidr_organizationidName,bidr_bidxecutoridYomiName,bidr_customer_repidName,bidr_customer_repidYomiName,bidr_areaidName,SLAInvokedIdName,OriginatingLeadIdYomiName,bidr_engineeringidName,bidr_bidfileproposedownerYomiName,CampaignIdName,OriginatingLeadIdName,PriceLevelIdName,bidr_level2or3managementteamidYomiName,bidr_bidauthorizedagentYomiName,bidr_countryidName,bidr_bidtechpicYomiName,bidr_intendedprojectmgridName,bidr_bidfileproposedownerName,ParentContactIdName,bidr_bidxecutoridName,bidr_bidtechleadingunitName,ParentAccountIdName,bidr_cityidName,bidr_temporaryprojectleaderidName,bidr_signcompanyName,bidr_countyidName,bidr_nextstageidName,bidr_bidauthorizedagentName,bidr_leadcompanyleaderteamidYomiName,bidr_intendedprojectmgridYomiName,bidr_signcompanyYomiName,bidr_ownerbusinessunitidName,bidr_temporaryprojectleaderidYomiName,bidr_leadcompanyleaderteamidName,CreatedByName,CreatedByYomiName,CreatedOnBehalfByName,CreatedOnBehalfByYomiName,ModifiedByName,ModifiedByYomiName,ModifiedOnBehalfByName,ModifiedOnBehalfByYomiName,TransactionCurrencyIdName,bidr_level2or3managementteamidName,bidr_provinceunionoverseaareaidName,bidr_bidtechpicName,OwnerId,OwnerIdName,OwnerIdYomiName,OwnerIdDsc,OwnerIdType,OwningUser,OwningTeam,AccountId,AccountIdName,AccountIdYomiName,ContactId,ContactIdName,ContactIdYomiName,OpportunityId,CreatedOn,CreatedBy,ModifiedOn,ModifiedBy,CreatedOnBehalfBy,ModifiedOnBehalfBy,OwningBusinessUnit,EmailAddress,ImportSequenceNumber,OverriddenCreatedOn,TimeZoneRuleVersionNumber,UTCConversionTimeZoneCode,[Name],ProcessId,...
  FROM Opportunity    
 WHERE (OriginatingLeadId = ?)
net.sf.jsqlparser.JSQLParserException: Encountered unexpected token: "," ","
    at line 2, column 1611.
### Software Information:
- JSqlParser version 4.6
- Database (MS SQL Server)

### Tips:
Please write in English and avoid Screenshots (as we can't copy and paste content from it).
[Try your example online with the latest JSQLParser](http://217.160.215.75:8080/jsqlformatter/demo.html) and share the link in the error report.
Do provide Links or References to the specific Grammar and Syntax you are trying to use.

**Comment by manticore-projects** [comment]
Duplicate #1781

**Comment by swansrp** [comment]
Thanks a lot for your help
