### ISSUE TITLE
Possible WebSite improvements

### ISSUE THREAD

**Issue by daredevil2033** [JSQLParser/JSqlParser#1784]
- Mode switch has three buttons (half-full circle, sun, crescent) but only two change the mode (crescent doesn't)
- sphinx-tabs-tab color doesn't account for dark mode (used in [Compile from Source Code](https://jsqlparser.github.io/JSqlParser/usage.html#compile-from-source-code) and [Build Dependencies](https://jsqlparser.github.io/JSqlParser/usage.html#build-dependencies))
- Syntax Railroad diagrams don't account for dark mode
- Some of the Syntax Railroad diagrams are obstructed (such as [JsonFunction](https://jsqlparser.github.io/JSqlParser/syntax.html#jsonfunction), [JsonAggregateFunction](https://jsqlparser.github.io/JSqlParser/syntax.html#jsonaggregatefunction), [CreateTable](https://jsqlparser.github.io/JSqlParser/syntax.html#createtable) and [AlterExpression](https://jsqlparser.github.io/JSqlParser/syntax.html#alterexpression))
- Some of the Syntax EBNF diagrams are obstructed (such as [Ll](https://jsqlparser.github.io/JSqlParser/syntax.html#ll) and [Lu](https://jsqlparser.github.io/JSqlParser/syntax.html#lu))

**Comment by manticore-projects** [comment]
Thanks for reporting.

> * Mode switch has three buttons (half-full circle, sun, crescent) but only two change the mode (crescent doesn't)

This comes from the used Sphinx Theme and I honestly don't know how to fix that.
 
> * sphinx-tabs-tab color doesn't account for dark mode (used in [Compile from Source Code](https://jsqlparser.github.io/JSqlParser/usage.html#compile-from-source-code) and [Build Dependencies](https://jsqlparser.github.io/JSqlParser/usage.html#build-dependencies))

This comes from the used Sphinx Theme and I honestly don't know how to fix that.
 
> * Syntax Railroad diagrams don't account for dark mode

Yes, this one is a problem. We will need to look into the `svg.css` if it can be amended for `dark mode`.

> * Some of the Syntax Railroad diagrams are obstructed (such as [JsonFunction](https://jsqlparser.github.io/JSqlParser/syntax.html#jsonfunction), [JsonAggregateFunction](https://jsqlparser.github.io/JSqlParser/syntax.html#jsonaggregatefunction), [CreateTable](https://jsqlparser.github.io/JSqlParser/syntax.html#createtable) and [AlterExpression](https://jsqlparser.github.io/JSqlParser/syntax.html#alterexpression))

Yes, but the only solution was to refactor the Productions in the Grammar.
Especially the `ALTER TABLE...` and `CREATE TABLE...` need some serious work.

> * Some of the Syntax EBNF diagrams are obstructed (such as [Ll](https://jsqlparser.github.io/JSqlParser/syntax.html#ll) and [Lu](https://jsqlparser.github.io/JSqlParser/syntax.html#lu))

I will look into this one. Also the Spelling is broken and needs to be fixed.
