### ISSUE TITLE
[BUG] statement with input user parameter cannot be parsed

### ISSUE THREAD

**Issue by csakhogy** [JSQLParser/JSqlParser#1785]
### Failing SQL Feature:
SQl Statement including an input parameter (that is being defined via user prompt during execution) cannot be parsed and throws ParseException:  Encountered unexpected token "=" "="

### SQL Example:
select * from all_tables 
where owner = &myowner

Note: AFAIK such input parameter might also contain a dot at the end (e.g. &myowner.).

### Software Information:
- JSqlParser version 4.60
- Oracle v19

**Comment by manticore-projects** [comment]
Greetings.


I have amended the `JDBCNamedParameter` to support the `&` character, but no way the parameter's name will end with a `.` since it is used as list separator for name fragments.
