### ISSUE TITLE
[BUG] JSQLParser 4.6: PostgreSQL - Schema not parsable if comment contains ";"

### ISSUE THREAD

**Issue by ndepomereu** [JSQLParser/JSqlParser#1788]
Hi,

Using 4.6, I try to parse a SQL schema, but it fails silently because commented line contains ";" separators.

This is the famous dvdrental database (PostgreSQL Tutorial).
Examples of comments that make fail the parse:

```
--
-- Name: mpaa_rating; Type: TYPE; Schema: public; Owner: postgres
--

CREATE TYPE public.mpaa_rating AS ENUM (
    'G',
    'PG',
    'PG-13',
    'R',
    'NC-17'
);
```

When I remove the comments, all is OK I'm sure it's not another issue with the schemas I parse.

Best,
N.

**Comment by manticore-projects** [comment]
Excusez moi, I just understand what you are asking for: the problem is not about the `CREATE TYPE ...` (will be parsed as `Unsupported Statement`?!) but rather about the `Multi Line Commend` containing `;` statement separator.

I will see what I can do.

**Comment by manticore-projects** [comment]
I am sorry but I don not understand the challenge yet. The following test case fails as expected:
```java
    @Test
    void testCreateTypeIssue1788() throws JSQLParserException {
        String sqlStr =
                "--\n"
                + "-- Name: mpaa_rating; Type: TYPE; Schema: public; Owner: postgres\n"
                + "--\n"
                + "\n"
                + "CREATE TYPE public.mpaa_rating AS ENUM (\n"
                + "    'G',\n"
                + "    'PG',\n"
                + "    'PG-13',\n"
                + "    'R',\n"
                + "    'NC-17'\n"
                + ");";
        final Statement statement = TestUtils.assertSqlCanBeParsedAndDeparsed(sqlStr, true);
        Assertions.assertTrue(statement instanceof UnsupportedStatement);
    }
```

```
net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "CREATE" "CREATE"
    at line 5, column 1.
```

Due to the fact, that `CREATE TYPE` is not supported. No issues with the comments though?

**Comment by ndepomereu** [comment]
Yes; I'm sorry, I should have been more specific and chose a `create table`: 
it's only the comments that are causing the problem...

Yes, I'm parsing Statements, but my data are not alimented, as if they were empty. No Exception was thrown.
I just loop on a:
`String[] statements = sqlSchema.split(";");`

Best,
N.

**Comment by manticore-projects** [comment]
```java
    @Test
    void testSelectIssue1788() throws JSQLParserException {
        String sqlStr =
                "--\n"
                + "-- Name: mpaa_rating; Type: TYPE; Schema: public; Owner: postgres\n"
                + "--\n"
                + "\n"
                + "SELECT 1";
        TestUtils.assertSqlCanBeParsedAndDeparsed(sqlStr, true);
    }
```

Succeeds, no problem with the comments. Please elaborate your observation.

**Comment by ndepomereu** [comment]
Just did it.  Do you want more code?

**Comment by manticore-projects** [comment]
There seems to be a major misunderstanding: From what you have explained, it looks to me like you are splitting a large Text by ";" into chunks and then you feed those chunks into JSQLParser. You ignore the fact, that your Text can contain Comments with ";" and so you split wrongly.

There are 2 alternatives:

1) use the REGEXes shown above to work around the comments before you split into statements

2) or use JSQLParser to parse the whole text and to find statements, e. g.

```java
        String sqls = "select * from mytable; select from;";

        CCJSqlParser parser = new CCJSqlParser(new StringProvider(sqls));
        parser.setErrorRecovery(true);
        Statements parseStatements = parser.Statements();

        assertEquals(2, parseStatements.getStatements().size());

        assertTrue(parseStatements.getStatements().get(0) instanceof Select);

        assertNull(parseStatements.getStatements().get(1));
```

**Comment by ndepomereu** [comment]
Dumb-me! You are right!
I forgot *before* writing the issue that I did the statement split (I thought it was done insideJSQLParser), so, of course, it's not all related to JSQLParser.
And it was optimistic, not to say worse, to imagine there would be no ";" in comments when splitting!!! 
;-)

Sorry for the misconception, but the issue was for me very useful because of your point 2 that now allows me to correctly parse more than one Statement!

Best,
N.

**Comment by manticore-projects** [comment]
Please have a look at the following illustration: https://manticore-projects.com/JSQLFormatter/samples.html#comments especially the 2nd statement.

Semicolons `;` can appear anywhere and JSQLParser handles the situation correctly.
Aside that, those statements have actually been split using the REGEXes shown above (as part of the JSQLFormatter project).

**Comment by manticore-projects** [comment]
> Dumb-me! You are right! I forgot _before_ writing the issue that I did the statement split (I thought it was done insideJSQLParser), so, of course, it's not all related to JSQLParser. And it was optimistic, not to say worse, to imagine there would be no ";" in comments when splitting!!! ;-)
> 
> Sorry for the misconception, but the issue was for me very useful because of your point 2 that now allows me to correctly parse more than one Statement!
> 
> Best, N.

Happens to the best, no worries.
You will still run into trouble when statements are not supported (like the `CREATE TYPE ...`).
So splitting the statements by yourself and then only feeding the chunks into JSQLParser is not a bad approach. I do it so myself for JSQLFormatter. But you will need some REGEX kung fu.

**Comment by ndepomereu** [comment]
Yes, right.
Thanks again!
