### ISSUE TITLE
[BUG] JSQLParser Version 4.6  - PostgreSQL:  "::" notation not supported in nextval

### ISSUE THREAD

**Issue by ndepomereu** [JSQLParser/JSqlParser#1789]
Hi,

With 4.6 I try to parse a PostgreSQL schema, it fails on this kind of table:

```
Statement in Error No 2: 
CREATE TABLE public.actor (
    actor_id integer DEFAULT nextval('public.actor_actor_id_seq'::regclass) NOT NULL,
    first_name character varying(45) NOT NULL,
    last_name character varying(45) NOT NULL,
    last_update timestamp without time zone DEFAULT now() NOT NULL
)
Exception of Error No 2: 
Encountered unexpected token: "::" "::"
```
Seems the :: notation is not suported in nextval.

Best,
N.

**Comment by manticore-projects** [comment]
Greetings, thank you for reporting.

I will fix this today, since there is a similar issue already.
Duplicate #1098
Duplicate #1022

**Comment by manticore-projects** [comment]
Fixed via Commit https://github.com/JSQLParser/JSqlParser/pull/1778/commits/d20c8e94de64e2ad6f1fcee58daf3c1de6a58148 with PR #1778 

Cheers!
