### ISSUE TITLE
[BUG] JSQLParser Version : 4.4 RDBMS :  mysql  Encountered unexpected token: "apply" "APPLY"

### ISSUE THREAD

**Issue by zjmJavaByte** [JSQLParser/JSqlParser#1793]
Always check against the **Latest SNAPSHOT of JSQLParser** and the [Syntax Diagram](https://jsqlparser.github.io/JSqlParser/syntax.html)

### Failing SQL Feature:
- Encountered unexpected token: "apply" "APPLY"
- When I remove the `apply` field and perform the parsing, no errors are reported

### SQL Example:
- Simplified Query Example, focusing on the failing feature
    ```sql
    -- Replace with your ACTUAL example
   UPDATE om_calendar_act_info SET action_calendar_id =?,act_time =?,sys_code =?,apply =?,act_name =?,begin_date =?,end_date =?,STATUS =?,is_commit =?,activity_details =?,images =?,materials =?,hr_bh =?,hr_name =?,create_time =?,update_user =?,update_time =? WHEREid =? AND del =0
    ```

### Software Information:
- JSqlParser version is 4.4
- Database is mysql
### Tips:
Please write in English and avoid Screenshots (as we can't copy and paste content from it).
[Try your example online with the latest JSQLParser](http://217.160.215.75:8080/jsqlformatter/demo.html) and share the link in the error report.
Do provide Links or References to the specific Grammar and Syntax you are trying to use.

**Comment by manticore-projects** [comment]
Greetings.

[please try JSQLParser 4.6](http://jsqlformatter.manticore-projects.com/jsqlformatter/demo.html?args=-c%20KoBQIgggKgogBAewLYH0DGBDANgUwHYAmGATihmgC4oCWeAZggFADKMUc5F1Ce62+RUtQJwAvHAD8jODLgAaDpRRckOMZOmyFAZwCe29AgJrxU2fI4AHS1l3qzWxVTwZV9zTIUAjHAHNaKEQUJhrmCgKBGMHuYXDaFFEArtoxjtQGaMhI1BSpnk7UAG45uoE4CdRYKaYeFtRIGL441aGODcHE1NgtDvkAFqRefXkWAygubjWxaMQ4UTjK9SG9FomWQQvJOMQjCmsbi5MaAOoAEjAASvDCIxAAcmBwxljqAAyMANxAA) which parses your statement fine.

4.4 has had `APPLY` defined as a reserved keyword.

**Comment by zjmJavaByte** [comment]
> Greetings.
> 
> [please try JSQLParser 4.6](http://jsqlformatter.manticore-projects.com/jsqlformatter/demo.html?args=-c%20KoBQIgggKgogBAewLYH0DGBDANgUwHYAmGATihmgC4oCWeAZggFADKMUc5F1Ce62+RUtQJwAvHAD8jODLgAaDpRRckOMZOmyFAZwCe29AgJrxU2fI4AHS1l3qzWxVTwZV9zTIUAjHAHNaKEQUJhrmCgKBGMHuYXDaFFEArtoxjtQGaMhI1BSpnk7UAG45uoE4CdRYKaYeFtRIGL441aGODcHE1NgtDvkAFqRefXkWAygubjWxaMQ4UTjK9SG9FomWQQvJOMQjCmsbi5MaAOoAEjAASvDCIxAAcmBwxljqAAyMANxAA) which parses your statement fine.
> 
> 4.4 has had `APPLY` defined as a reserved keyword.

When I upgraded to version 4.6, the following error occurred `Encountered unexpected token: "\n\n\n" <ST_SEMICOLON>` . I was using the 'sql' generated automatically by the `mybatisplus` framework. and I did see a lot of' \n 'through debug

**Comment by manticore-projects** [comment]
Greetings!

That is correct, in JSQLParser 4.6, two empty rows `.*\n\n\n` terminate a statement.
(And I still will need a good argument why anyone would need 2 empty rows within one statement.)

```
sql
select 1 from dual

select 2 from dual
```
gives 2 statements (without typing semicolons `;`)
