### ISSUE TITLE
[BUG] JSQLParser Version : 4.6 RDBMS : validate insert into values  errors

### ISSUE THREAD

**Issue by zoyation** [JSQLParser/JSqlParser#1795]
### Failing SQL Feature:
 `insert into tablea(id) values(1)` can't pass then validate

### Example:
    ```sql
    Validation validation = new Validation(Arrays.asList(FeaturesAllowed.INSERT),"insert into tablea(id) values(1)");
    List<ValidationError> error = validation.validate();
    //validation.validate().size()==1 error info: values not allowed
    ```

### Software Information:
- JSqlParser version 4.6
- Database (Oracle, MS SQL Server, H2, PostgreSQL, IBM DB2 )

**Comment by manticore-projects** [comment]
Greetings.

As far as I understand it, you would also need to allow the Features `VALUES` (or `SELECT`) as well as a database dialect.
In my own opinion, without a database dialect the Validation does not make sense because you will just parse the statement.

**Comment by zoyation** [comment]
Greetings.
&nbsp;Thanks!
&nbsp; As you say I know how to modify my code with 4.6, and the old version 4.1 support it, wish the latest&nbsp; version may support more with old version!&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年5月25日(星期四) 下午3:45
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [JSQLParser/JSqlParser] [BUG] JSQLParser Version : 4.6 RDBMS : validate insert into values  errors (Issue #1795)





 
Greetings.
 
As far as I understand it, you would also need to allow the Features VALUES (or SELECT) as well as a database dialect.
 In my own opinion, without a database dialect the Validation does not make sense because you will just parse the statement.

**Comment by manticore-projects** [comment]
Closed, since no further questions asked.
