### ISSUE TITLE
[BUG] JSQLParser Version : RDBMS : failing parsing CALL statement without parameters

### ISSUE THREAD

**Issue by ZhengguanLi** [JSQLParser/JSqlParser#1799]
### Failing SQL Feature:
-  `CALL my_procedure()` without parameters can't be parsed

### SQL Example:
- Simplified Query Example, focusing on the failing feature
    ```sql
    CALL my_procedure();
    ```
- Exception:
   ```
    net.sf.jsqlparser.JSQLParserException: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: ")" ")"
    at line 1, column 33.

    Was expecting one of:

    "!"
    "("
    "+"
    "-"
    "CONNECT_BY_ROOT"
    "NOT"
    "NULL"
    "XMLSERIALIZE"
    "{d"
    "{t"
    "{ts"
    "~"
    <S_CHAR_LITERAL>
    <S_DOUBLE>
    <S_HEX>
    <S_LONG>
   ```

### Software Information:
- JSqlParser version v4.6
- Oracle

### Tips:
Oracle CALL: https://docs.oracle.com/cd/E24693_01/server.11203/e17118/statements_4008.htm

**Comment by manticore-projects** [comment]
Please use JSQLFormatter 4.7 SNAPSHOT, [you can try it here online.](http://jsqlformatter.manticore-projects.com/jsqlformatter/demo.html?args=-c%20MIQQMmAEC2CeD6AHATgewMYFMAmBXZmkAFAJQBQA3EA)

```text
SQL Text
 └─Statements: statement.execute.Execute
    └─ParenthesedExpressionList: ()
```

**Comment by manticore-projects** [comment]
Solved and no further questions asked.

**Comment by ZhengguanLi** [comment]
Sorry to bother, but I tried 4.7-SNAPSHOT today, still got the same error

**Comment by ZhengguanLi** [comment]
@manticore-projects
