### ISSUE TITLE
[BUG] JSQLParser Version : 4.6 : insert values error

### ISSUE THREAD

**Issue by phial3** [JSQLParser/JSqlParser#1801]
### Failing SQL Feature:
- Brief description of the failing SQL feature
- Example: `values` can't be parsed

### SQL Example:
- Simplified insert
```sql
insert into tb0 values (1)
```
- insert item to values
- expected: 
```sql
insert into tb0 values (1, 2, '3', 4.0)
```
- actual:
```sql
insert into tb0 values (1), 2, '3', 4.0
```

### Software Information:
- JSqlParser version : 4.6
- Database : mysql

### Tips:
<img width="814" alt="image" src="https://github.com/JSQLParser/JSqlParser/assets/27754514/b4db9a32-a79f-43ca-ac60-0a6a7cb78ac4">

<img width="718" alt="image" src="https://github.com/JSQLParser/JSqlParser/assets/27754514/e6e17948-1834-443f-8d20-e9a76acb8420">

**Comment by manticore-projects** [comment]
Greetings.

Unfortunately it is not clear to me, what your concern is about.
With JSQLParser 4.7 SNAPSHOT, [all your statements parse and you can try it here](http://jsqlformatter.manticore-projects.com/jsqlformatter/demo.html?args=-c%20JIOQygogSgKgBKGB5OAXARgBgFADUCCAMgKoRhwAUcAjHAJTYDc2oksCIyaWeRp5VOEOrYhY8WIA0cAEyiJC6QHIAzEvkLx0gCwA6TPSYtw0eIhQYcBEmSFVaDTXGlynytRok79TIA).

Please elaborate, if I miss anything. Please avoid Screenshots, they do not help.

**Comment by phial3** [comment]
done
