### ISSUE TITLE
[BUG] 4.6: RDBMS : ParseException: Encountered unexpected token: "ORDER" "ORDER"

### ISSUE THREAD

**Issue by scrollsyou** [JSQLParser/JSqlParser#1803]
### Failing SQL Feature:
- There is a parsing error when there are three consecutive line breaks in SQL.
- Example: `"SELECT * FROM user \n\n" +
                    "WHERE del_flag=0\n" +
                    "\n" +
                    "\n" +
                    " ORDER BY create_time DESC"` can't be parsed

### SQL Example:
- Simplified Query Example, focusing on the failing feature
   
 ```java
@Test
    public void testCountParse(){
        try {
            String rawSql = "SELECT * FROM user \n\n" +
                    "WHERE del_flag=0\n" +
                    "\n" +
                    "\n" +
                    " ORDER BY create_time DESC";
            Select createTable = (Select) CCJSqlParserUtil.parse(rawSql);
        } catch (JSQLParserException e) {
            throw new RuntimeException(e);
        }
    }
```

### Software Information:
- JSqlParser 4.6

**Comment by manticore-projects** [comment]
2 empty rows will terminate the statement. Just remove the \n\n\n and your statement will be parsed fine.On 6 Jun 2023 11:19, youshushu ***@***.***> wrote:
Failing SQL Feature:
There is a parsing error when there are three consecutive line breaks in SQL.Example: "SELECT * FROM user \n\n" + "WHERE del_flag=0\n" + "\n" + "\n" + " ORDER BY create_time DESC" can't be parsed
SQL Example:
Simplified Query Example, focusing on the failing feature
@Test
   public void testCountParse(){
       try {
           String rawSql = "SELECT * FROM user \n\n" +
                   "WHERE del_flag=0\n" +
                   "\n" +
                   "\n" +
                   " ORDER BY create_time DESC";
           Select createTable = (Select) CCJSqlParserUtil.parse(rawSql);
       } catch (JSQLParserException e) {
           throw new RuntimeException(e);
       }
   }
Software Information:
JSqlParser 4.6

**Comment by scrollsyou** [comment]
Thank you. I thought it was a bug because this SQL is generated by another program and called to the SQL parser. If that's the case, I'll fix it in the generator.

**Comment by manticore-projects** [comment]
I lodged a ticket at my batis plus already. They seem to generate statements with redundant empty lines - for no good reason. On 6 Jun 2023 12:46, youshushu ***@***.***> wrote:
Thank you. I thought it was a bug because this SQL is generated by another program and called to the SQL parser. If that's the case, I'll fix it in the generator.
