### ISSUE TITLE
[BUG?] JSQLParser Version 4.6 : Statement with  trailing empty lines fail on macOs, pass on Windows

### ISSUE THREAD

**Issue by ndepomereu** [JSQLParser/JSqlParser#1808]
Hi,

Using 4.6 stable version, I get this error when trying to parse a schema under macOs with Java 11:
[JSQLParser.txt](https://github.com/JSQLParser/JSqlParser/files/11849019/JSQLParser.txt)

This works perfectly on Windows 10.

Here is the sample schema file parsed unser macOs, but that comes from Windows:
[schema.txt](https://github.com/JSQLParser/JSqlParser/files/11849075/schema.txt)

It seems there are some special characters (?), but I can't find or remove them, whatever I try.

This kind of error is systemic when I try to parse a schema file on macOs that has been created under Windows.
The error never happens on Windows.

Best,
N.

**Comment by ndepomereu** [comment]
You are right! 
I put a trace, and there empty lines before my statements. 
I will remove them reading line by line before passing the statement 

It's weird it does cause a problem with Windows, I would have checked like you said if I had the behavior with Windows...

Just in case you want to give a look:

```
   private void process() throws JSQLParserException {

        sqlSchema = SqlRewriter.removeComments(sqlSchema);
        sqlSchema = SqlRewriter.removeNextval(sqlSchema);
        sqlSchema = SqlRewriter.removeStartWith(sqlSchema);

        String[] statements = sqlSchema.split(";");
        CCJSqlParserManager parserManager = new CCJSqlParserManager();

        for (String statement : statements) {
            if (!statement.trim().isEmpty()) {
                
                // used for diagnosis:
                //JOptionPane.showMessageDialog(null, ":" + statement + ":");
                
                // ONLY create table or create index!
                if (!SchemaExtractorUtil.isCreateTableOrIndexStatement(statement)) {
                    continue;
                }

                Statement parsedStatement = null;
                try {
                    parsedStatement = parserManager.parse(new StringReader(statement));
                } catch (JSQLParserException jSQLParserException) {
                    //System.err.println("Exception on statement hat has been skipped:");
                    //System.err.println(statement));  
                    this.jSQLParserExceptionList.add(jSQLParserException);
                    this.statementSkipped.add(statement);
                    boolean throwExceptionNow = false;
                    if (throwExceptionNow) {
                        throw new JSQLParserException("Parse Error on Statement: " + statement);
                    }
                    continue;
                }

		// Etc...
```


Thanks

**Comment by manticore-projects** [comment]
Greetings again.

You could JSQLParser parse all Statements like:
```java
Statements statements = CCJSqlParserUtil.parserStatements(sqlStr);
```

Please see: https://manticore-projects.com/JSQLParser/javadoc_snapshot.html#net-sf-jsqlparser-statement-statements

Anything unsupported or un-parseable will be returned would be returned as `UnsupportedStatement` and all termination and line-breaking would be on the parser.

If you really want to split the Statements by yourself, a much more complex Regulare Expression will be needed to deal with comments, quoted strings etc.

**Comment by manticore-projects** [comment]
Explained.
