### ISSUE TITLE
Some DB-specific dialects produce parsing exceptions

### ISSUE THREAD

**Issue by disrvptor** [JSQLParser/JSqlParser#181]
I've found the following statements, which are legal MySQL sql generate parsing errors

 * `DROP TABLE IF EXISTS 'my_table';` - Parse chokes on `IF`
 * `CREATE TABLE 'my_table' ...` - Character literals for table names
 * `CREATE TABLE my_table ( 'id' bigint(20) ...` - Character literals for column names
 * `CREATE TABLE my_table ( id beignet(20) NOT NULL AUTO_INCREMENT, PRIMARY KEY ('id') ...` - Character literals in primary key definitions
 * `LOCK TABLES 'my_table' WRITE;` - Lock is an unknown identifier, I'm guessing unlock (`UNLOCK TABLES;`) is too
 * Character literals for table and column names on INSERT statements too. Most likely everywhere.

**Comment by wumpz** [comment]
- Character literals for table names or any objects name will not go into JSqlParser ( look at #168, regarding SQLServer it is an deprecated feature)
---> As for MySQL look at https://dev.mysql.com/doc/refman/5.0/en/identifiers.html : "The identifier quote character is the backtick (“`”):" Maybe it is a copy paste error from you? SQLFiddle does not run as well: http://sqlfiddle.com/#!9/6f69bc/7 
- drop if exists is simply not implemented
- lock / unlock is not implemented

**Comment by disrvptor** [comment]
Doh! For some reason the backticks got converted to ticks. I'll re-test with backticks.

Will you update the grammar to understand `drop if exists` and `lock`/`unlock`? No problems, I can compensate either way, just curious.

Thanks!

**Comment by wumpz** [comment]
At the moment I have only little time to spare. You know, something to do for food ;). At least ~drop if exists~ shoulnd't be to hard to implement.
