### ISSUE TITLE
[BUG] JSQLParser Version :4.6,Encountered unexpected token: "MEMBER" <S_IDENTIFIER>

### ISSUE THREAD

**Issue by nreger** [JSQLParser/JSqlParser#1811]
Always check against the **Latest SNAPSHOT of JSQLParser** and the [Syntax Diagram](https://jsqlparser.github.io/JSqlParser/syntax.html)

### Failing SQL Feature:
- Brief description of the failing SQL feature
- Example: `WITH ROLLUP` can't be parsed

### SQL Example:
- Simplified Query Example, focusing on the failing feature
    ```sql
    SELECT p.person_inspect_id,
               p.person_test_number,
               p.reservation_inspect_state,
               p.person_info_id,
               p.person_user_name,
               p.person_user_mobile,
               p.person_gender,
               p.person_age,
               p.person_id_card_number,
               p.person_inspect_time,
               p.person_money,
               p.person_units_id,
               p.person_unit_name,
               p.tj_package_id_list,
               p.tj_single_id_list,
               p.is_used,
               p.tenant,
               p.branch_courts,
               p.quota,
               p.quota_flag,

               item.id,
               item.test_num,
               item.tj_package_id,
               item.package_name,
               item.package_gender_suite,
               item.tj_charge_item_id,
               item.item_name,
               item.item_spell_code,
               item.item_price,
               item.item_coupon_price,
               item.item_coupon_rate,
               item.logic_delete,
               item.department_id,
               item.department_name,
               item.item_suit_gender,
               item.empty_stomach,
               item.project_type,
               item.is_save_urine,
               item.age_fit_max,
               item.age_fit_min,
               item.project_state,
               item.charge_method,
               item.charge_state,
               item.tj_id,

               pi.precautions,
               if(item.id is null, 1, 0)                                                            as empty_flag,
               if(item.id is not null and item.tj_package_id is null, 1, 2)                         as item_type,
               if(item.id is not null and item.tj_package_id is null, 1, null)                      as single_item_type,
               if(item.id is not null and item.tj_package_id is null, item.tj_charge_item_id,
                  null)                                                                             as single_item_tj_id,
               if(item.id is not null and item.tj_package_id is null, item.item_name, null)         as single_item_name,
               if(item.id is not null and item.tj_package_id is null, item.item_coupon_price,
                  null)                                                                             as single_item_coupon_price,
               if(item.id is not null and item.tj_package_id is null, item.item_suit_gender,
                  null)                                                                             as single_item_suit_gender,
               if(item.id is not null and item.tj_package_id is null, pi.precautions,
                  null)                                                                             as single_precautions

        FROM health_check_person p
                 LEFT JOIN health_check_person_item item
                           ON p.person_test_number = item.test_num AND p.branch_courts = item.branch_courts AND
                              item.logic_delete = 0 AND CAST(item.tj_package_id AS SIGNED) MEMBER OF (p.tj_package_id_list) = 1

        LEFT JOIN health_check_package_item pi
        ON CAST(pi.tj_package_id AS SIGNED) MEMBER OF(p.tj_package_id_list) = 1 AND pi.logic_delete = 0 AND pi.tenant = 'sdszy'
            AND pi.tj_package_id = item.tj_package_id
            AND pi.tj_package_charge_id = item.tj_charge_item_id

        WHERE p.person_test_number
        IN
         (  
            '1000081563'
         ) 
          AND p.logic_delete = 0
          AND p.is_used = 0
        ORDER BY p.created_time desc
    ```

### Software Information:
- JSqlParser version 4.6
- Database ( MySQL 8.0.32 )

### Tips:
can't use MEMBER OF

**Comment by manticore-projects** [comment]
Greetings.

This has been incorporated into latest Snapshot JSQL Parser-4.7 already [and you can test it online here.](http://jsqlformatter.manticore-projects.com/jsqlformatter/demo.html?args=-c%20MoUQMiDCAqAEsAcB0CCmAnAzgewHYH0BLXTNAYwBciATAKHgYYBpEUMcCLVMrcBXALYAjDPUbNW6bhgBuAQwqE8REuSo8FqMeNgtkaLMuIAzbDW3i9bQwT6YM+XHIFad8KwY747DgdiGEADaubh7sygDmqLjUom66rJ7KclEWjGE2NPhkcujUjoIi6GkS+uEExKSolPiKLiXuieX4frioAJ4NCWWZfLiEFJjm8RlefQOOziE6VhQAVvgIcmQA1imoWYGEPF2zC5jEEcGb2xS7rNve9nQjrFxOuGe3yELocrhkABbZ2Hzog+dkABHPjYChyQFIEFguT4YyBFLnAaoARIQg3UKwZGorg8AoCJFcHELJardbDTHYlDLNZRSb1W5U0m0jZRGIOTB8ZGElFIebZT65OnYikzLFEtFE+nTSzi3kiqqBQI-WI81EihDoQhkGXpOXqqVkX4IZSa7W6iRUkVGvgmghvLhqpCBbARbX4WLBR2MiWxJb-FyPUWyql+3IUQO8KZOhVcqhs2LFH28lEICjtfA8bACZafJ2a7BzapUdNoGNDTByGQbP7EC2NKnk4wTHMADydTZbxHz6ELxcz4O9lIlXyFGxcFE+2AxYqpo-QdI0Q9nEv56MBhBQUhyfEUeEw5wAksYABT6tHUWCH4CwAByAFUwGAWABGFgABlgAEpYABBG+pumcIIhER6nue6JXjet4APJwA+T5dIwv63gAIue-LMuSkHXnej7PrAb6wAATN+f43iKpb1gkx5nlal64bB8H4UhDAoehVKYTS2EMdB+GviwCFgGR-6wAcuBHBslHtGWty0RBvF3nBeGIfEyFoRhJLccKilCSwnELPOwpSuign4SJN7iZJRBSmuM6yvJ9FQUpzGqWp8DsZpizaVJun8RBUpOC4ZlPhZYmHMcIpBdRLCORKOHQcpQmsR5GkGd5ZI6c5ekBSiPy2qaWo6iFwk-qJVmRYaxqFeaYF0fFulJSx7mpRxq5aZlvnZf5VpSpyEwJhgJVhRVUl9XG+CDUmmJxfKjWuWAKV-ml7UZSyNDdU+eibpq1RyLuSgkMNZWWRFGy7Tue4kLQABiABKMEALKwJ8qByIEk4CtUKyLOUiAWBAN1wAAUjBh63i9b0fd8Xzfb9mTYvqXQwRDPReLivCFBgsAALwYdwmMEi1y3oS8bwfDDvz-JguPnq87xfPl1NLZ5VIum6ZAeqgXqoLT74sxpkD-tAJ7pVhWWicAh4AOK3iAqE-o9ICPQAQiAd2wDBN2wCeyBcZ1Jw8D+eMvgDIBA7AoPg5D72fbDqxrdhRKIIQyMQ0LwAiwgm76+tkGSzLcsK7ASuq+rmva7rfIdX7+RbEbtMviTLvOq67qeqgXB88n3t8tE7wULTADkmDUJgABe7RFznPsxzxtNiz5G2ebnvvkkZXV4+lHc2Xl64AOoABLqyATSZBj+JFLQADcQA)

```sql
SELECT  p.person_inspect_id
        , p.person_test_number
        , p.reservation_inspect_state
        , p.person_info_id
        , p.person_user_name
        , p.person_user_mobile
        , p.person_gender
        , p.person_age
        , p.person_id_card_number
        , p.person_inspect_time
        , p.person_money
        , p.person_units_id
        , p.person_unit_name
        , p.tj_package_id_list
        , p.tj_single_id_list
        , p.is_used
        , p.tenant
        , p.branch_courts
        , p.quota
        , p.quota_flag
        , item.id
        , item.test_num
        , item.tj_package_id
        , item.package_name
        , item.package_gender_suite
        , item.tj_charge_item_id
        , item.item_name
        , item.item_spell_code
        , item.item_price
        , item.item_coupon_price
        , item.item_coupon_rate
        , item.logic_delete
        , item.department_id
        , item.department_name
        , item.item_suit_gender
        , item.empty_stomach
        , item.project_type
        , item.is_save_urine
        , item.age_fit_max
        , item.age_fit_min
        , item.project_state
        , item.charge_method
        , item.charge_state
        , item.tj_id
        , pi.precautions
        , If( item.id IS NULL, 1, 0 ) AS empty_flag
        , If( item.id IS NOT NULL
            AND item.tj_package_id IS NULL, 1, 2 ) AS item_type
        , If( item.id IS NOT NULL
            AND item.tj_package_id IS NULL, 1, NULL ) AS single_item_type
        , If( item.id IS NOT NULL
            AND item.tj_package_id IS NULL, item.tj_charge_item_id, NULL ) AS single_item_tj_id
        , If( item.id IS NOT NULL
            AND item.tj_package_id IS NULL, item.item_name, NULL ) AS single_item_name
        , If( item.id IS NOT NULL
            AND item.tj_package_id IS NULL, item.item_coupon_price, NULL ) AS single_item_coupon_price
        , If( item.id IS NOT NULL
            AND item.tj_package_id IS NULL, item.item_suit_gender, NULL ) AS single_item_suit_gender
        , If( item.id IS NOT NULL
            AND item.tj_package_id IS NULL, pi.precautions, NULL ) AS single_precautions
FROM health_check_person p
    LEFT JOIN health_check_person_item item
        ON p.person_test_number = item.test_num
            AND p.branch_courts = item.branch_courts
            AND item.logic_delete = 0
            AND CAST(item.tj_package_id AS SIGNED) MEMBER OF (p.tj_package_id_list) = 1
    LEFT JOIN health_check_package_item pi
        ON CAST(pi.tj_package_id AS SIGNED) MEMBER OF (p.tj_package_id_list) = 1 AND pi.logic_delete = 0 AND pi.tenant = 'sdszy' AND pi.tj_package_id = item.tj_package_id AND pi.tj_package_charge_id = item.tj_charge_item_id
WHERE p.person_test_number
;
```

**Comment by manticore-projects** [comment]
Your original statement as a problem at line 71 though:
```sql
WHERE p.person_test_numberSELECT p.person_inspect_id,
```

![image](https://github.com/JSQLParser/JSqlParser/assets/18080123/cec8e6c4-5cb6-404e-83df-6fbb0f5fe121)

**Comment by nreger** [comment]
![image](https://github.com/JSQLParser/JSqlParser/assets/129590836/c09cb1d8-a0c6-4d7a-8f07-f11e1a9e3b79)
![image](https://github.com/JSQLParser/JSqlParser/assets/129590836/6ee316e1-ae67-4886-b783-70d563fd5d78)
![image](https://github.com/JSQLParser/JSqlParser/assets/129590836/540f7d37-8b86-4361-8043-0797fd8f92f0)

**Comment by nreger** [comment]
SORRY , true sql:

```sql
SELECT p.person_inspect_id,
               p.person_test_number,
               p.reservation_inspect_state,
               p.person_info_id,
               p.person_user_name,
               p.person_user_mobile,
               p.person_gender,
               p.person_age,
               p.person_id_card_number,
               p.person_inspect_time,
               p.person_money,
               p.person_units_id,
               p.person_unit_name,
               p.tj_package_id_list,
               p.tj_single_id_list,
               p.is_used,
               p.tenant,
               p.branch_courts,
               p.quota,
               p.quota_flag,

               item.id,
               item.test_num,
               item.tj_package_id,
               item.package_name,
               item.package_gender_suite,
               item.tj_charge_item_id,
               item.item_name,
               item.item_spell_code,
               item.item_price,
               item.item_coupon_price,
               item.item_coupon_rate,
               item.logic_delete,
               item.department_id,
               item.department_name,
               item.item_suit_gender,
               item.empty_stomach,
               item.project_type,
               item.is_save_urine,
               item.age_fit_max,
               item.age_fit_min,
               item.project_state,
               item.charge_method,
               item.charge_state,
               item.tj_id,

               pi.precautions,
               if(item.id is null, 1, 0)                                                            as empty_flag,
               if(item.id is not null and item.tj_package_id is null, 1, 2)                         as item_type,
               if(item.id is not null and item.tj_package_id is null, 1, null)                      as single_item_type,
               if(item.id is not null and item.tj_package_id is null, item.tj_charge_item_id,
                  null)                                                                             as single_item_tj_id,
               if(item.id is not null and item.tj_package_id is null, item.item_name, null)         as single_item_name,
               if(item.id is not null and item.tj_package_id is null, item.item_coupon_price,
                  null)                                                                             as single_item_coupon_price,
               if(item.id is not null and item.tj_package_id is null, item.item_suit_gender,
                  null)                                                                             as single_item_suit_gender,
               if(item.id is not null and item.tj_package_id is null, pi.precautions,
                  null)                                                                             as single_precautions

        FROM health_check_person p
                 LEFT JOIN health_check_person_item item
                           ON p.person_test_number = item.test_num AND p.branch_courts = item.branch_courts AND
                              item.logic_delete = 0 AND CAST(item.tj_package_id AS SIGNED) MEMBER OF (p.tj_package_id_list) = 1

        LEFT JOIN health_check_package_item pi
        ON CAST(pi.tj_package_id AS SIGNED) MEMBER OF(p.tj_package_id_list) = 1 AND pi.logic_delete = 0 AND pi.tenant = 'sdszy'
            AND pi.tj_package_id = item.tj_package_id
            AND pi.tj_package_charge_id = item.tj_charge_item_id

        WHERE p.person_test_number
        IN
         (  
            '1000081563'
         ) 
          AND p.logic_delete = 0
          AND p.is_used = 0
        ORDER BY p.created_time desc
```

**Comment by manticore-projects** [comment]
[Please see Maven Coordinates for Snapshot](http://217.160.215.75:8080/h2migrationtool/JSQLParser/usage.html#build-dependencies):

```xml
<repositories>
    <repository>
        <id>jsqlparser-snapshots</id>
        <snapshots>
            <enabled>true</enabled>
        </snapshots>
        <url>https://oss.sonatype.org/content/groups/public/</url>
    </repository>
</repositories>
<dependency>
    <groupId>com.github.jsqlparser</groupId>
    <artifactId>jsqlparser</artifactId>
    <version>4.7-SNAPSHOT</version>
</dependency>
```

**Comment by manticore-projects** [comment]
> SORRY , true sql:

[Online trial `true sql`](http://jsqlformatter.manticore-projects.com/jsqlformatter/demo.html?args=-c%20MoUQMiDCAqAEsAcB0CCmAnAzgewHYH0BLXTNAYwBciATAKHgYYBpEUMcCLVMrcBXALYAjDPUbNW6bhgBuAQwqE8REuSo8FqMeNgtkaLMuIAzbDW3i9bQwT6YM+XHIFad8KwY747DgdiGEADaubh7sygDmqLjUom66rJ7KclEWjGE2NPhkcujUjoIi6GkS+uEExKSolPiKLiXuieX4frioAJ4NCWWZfLiEFJjm8RlefQOOziE6VhQAVvgIcmQA1imoWYGEPF2zC5jEEcGb2xS7rNve9nQjrFxOuGe3yELocrhkABbZ2Hzog+dkABHPjYChyQFIEFguT4YyBFLnAaoARIQg3UKwZGorg8AoCJFcHELJardbDTHYlDLNZRSb1W5U0m0jZRGIOTB8ZGElFIebZT65OnYikzLFEtFE+nTSzi3kiqqBQI-WI81EihDoQhkGXpOXqqVkX4IZSa7W6iRUkVGvgmghvLhqpCBbARbX4WLBR2MiWxJb-FyPUWyql+3IUQO8KZOhVcqhs2LFH28lEICjtfA8bACZafJ2a7BzapUdNoGNDTByGQbP7EC2NKnk4wTHMADydTZbxHz6ELxcz4O9lIlXyFGxcFE+2AxYqpo-QdI0Q9nEv56MBhBQUhyfEUeEw5wAksYABT6tHUWCH4CwAByAFUwGAWABGFgABlgAEpYABBG+pumcIIhER6nue6JXjet4APJwA+T5dIwv63gAIue-LMuSkHXnej7PrAb6wAATN+f43iKpb1gkx5nlal64bB8H4UhDAoehVKYTS2EMdB+GviwCFgGR-6wAcuBHBslHtGWty0RBvF3nBeGIfEyFoRhJLccKilCSwnELPOwpSuign4SJN7iZJRBSmuM6yvJ9FQUpzGqWp8DsZpizaVJun8RBUpOC4ZlPhZYmHMcIpBdRLCORKOHQcpQmsR5GkGd5ZI6c5ekBSiPy2qaWo6iFwk-qJVmRYaxqFeaYF0fFulJSx7mpRxq5aZlvnZf5VpSpyEwJhgJVhRVUl9XG+CDUmmJxfKjWuWAKV-ml7UZSyNDdU+eibpq1RyLuSgkMNZWWRFGy7Tue4kLQABiABKMEALKwJ8qByIEk4CtUKyLOUiAWBAN1wAAUjBh63i9b0fd8Xzfb9mTYvqXQwRDPReLivCFBgsAALwYdwmMEi1y3oS8bwfDDvz-JguPnq87xfPl1NLZ5VIum6ZAeqgXqoLT74sxpkD-tAJ7pVhWWicAh4AOK3iAqE-o9ICPQAQiAd2wDBN2wCeyBcZ1Jw8D+eMvgDIBA7AoPg5D72fbDqxrdhRKIIQyMQ0LwAiwgm76+tkGSzLcsK7ASuq+rmva7rfIdX7+RbEbtMviTLvOq67qeqgXB88n3t8tE7wULTADkmDUJgABe7RFznPsxzxtNiz5G2ebnvvkkZXV4+lHc2Xl64AOoABLqyATSZBj+JFFeENnkXL7vgv74ABwvgArAAbAAzNXX4WC3qcc1zPN83vGnIJcPiXnj-MwXdqHhyrACarBkFImj5HUvP38AkC0AA3EAA)

**Comment by nreger** [comment]
> > SORRY , true sql:
> 
> [Online trial `true sql`](http://jsqlformatter.manticore-projects.com/jsqlformatter/demo.html?args=-c%20MoUQMiDCAqAEsAcB0CCmAnAzgewHYH0BLXTNAYwBciATAKHgYYBpEUMcCLVMrcBXALYAjDPUbNW6bhgBuAQwqE8REuSo8FqMeNgtkaLMuIAzbDW3i9bQwT6YM+XHIFad8KwY747DgdiGEADaubh7sygDmqLjUom66rJ7KclEWjGE2NPhkcujUjoIi6GkS+uEExKSolPiKLiXuieX4frioAJ4NCWWZfLiEFJjm8RlefQOOziE6VhQAVvgIcmQA1imoWYGEPF2zC5jEEcGb2xS7rNve9nQjrFxOuGe3yELocrhkABbZ2Hzog+dkABHPjYChyQFIEFguT4YyBFLnAaoARIQg3UKwZGorg8AoCJFcHELJardbDTHYlDLNZRSb1W5U0m0jZRGIOTB8ZGElFIebZT65OnYikzLFEtFE+nTSzi3kiqqBQI-WI81EihDoQhkGXpOXqqVkX4IZSa7W6iRUkVGvgmghvLhqpCBbARbX4WLBR2MiWxJb-FyPUWyql+3IUQO8KZOhVcqhs2LFH28lEICjtfA8bACZafJ2a7BzapUdNoGNDTByGQbP7EC2NKnk4wTHMADydTZbxHz6ELxcz4O9lIlXyFGxcFE+2AxYqpo-QdI0Q9nEv56MBhBQUhyfEUeEw5wAksYABT6tHUWCH4CwAByAFUwGAWABGFgABlgAEpYABBG+pumcIIhER6nue6JXjet4APJwA+T5dIwv63gAIue-LMuSkHXnej7PrAb6wAATN+f43iKpb1gkx5nlal64bB8H4UhDAoehVKYTS2EMdB+GviwCFgGR-6wAcuBHBslHtGWty0RBvF3nBeGIfEyFoRhJLccKilCSwnELPOwpSuign4SJN7iZJRBSmuM6yvJ9FQUpzGqWp8DsZpizaVJun8RBUpOC4ZlPhZYmHMcIpBdRLCORKOHQcpQmsR5GkGd5ZI6c5ekBSiPy2qaWo6iFwk-qJVmRYaxqFeaYF0fFulJSx7mpRxq5aZlvnZf5VpSpyEwJhgJVhRVUl9XG+CDUmmJxfKjWuWAKV-ml7UZSyNDdU+eibpq1RyLuSgkMNZWWRFGy7Tue4kLQABiABKMEALKwJ8qByIEk4CtUKyLOUiAWBAN1wAAUjBh63i9b0fd8Xzfb9mTYvqXQwRDPReLivCFBgsAALwYdwmMEi1y3oS8bwfDDvz-JguPnq87xfPl1NLZ5VIum6ZAeqgXqoLT74sxpkD-tAJ7pVhWWicAh4AOK3iAqE-o9ICPQAQiAd2wDBN2wCeyBcZ1Jw8D+eMvgDIBA7AoPg5D72fbDqxrdhRKIIQyMQ0LwAiwgm76+tkGSzLcsK7ASuq+rmva7rfIdX7+RbEbtMviTLvOq67qeqgXB88n3t8tE7wULTADkmDUJgABe7RFznPsxzxtNiz5G2ebnvvkkZXV4+lHc2Xl64AOoABLqyATSZBj+JFFeENnkXL7vgv74ABwvgArAAbAAzNXX4WC3qcc1zPN83vGnIJcPiXnj-MwXdqHhyrACarBkFImj5HUvP38AkC0AA3EAA)

Thank you very much for your help. I will wait for the official version of 4.7

**Comment by manticore-projects** [comment]
Closing, since it has been solved already.
