### ISSUE TITLE
Escape character ERROR

### ISSUE THREAD

**Issue by WUWEI111222333** [JSQLParser/JSqlParser#1812]
if sql contains a Escape character like  '\'' ，the parse will occur error
the sql is :
INSERT INTO `recycle_record` (`id`,`order_no`,`site_id`,`ic_no`,`ic_card_id`,`provider_id`,`car_no`,`trace_source_code`,`trade_time`,`in_time`,`out_time`,`weight_gross`,`weight_tare`,`weight_net`,`weight_deduct`,`weight_settlement`,`product_code`,`product_name`,`product_type`,`deduct`,`price`,`total`,`rater`,`rater_id`,`reviewer`,`reviewer_id`,`reviewer_time`,`pay_status`,`pay_method`,`pay_time`,`deleted`,`data_source`,`equipment_code`,`equipment_id`,`create_time`,`modify_time`,`payer_id`,`payer_name`,`remark`,`project_id`,`data_type`,`creator_id`,`creator_name`,`bno`,`receiving_name`,`receiving_account`,`pay_amount`,`data_sync`,`batch_no`,`pay_review_id`,`pay_review_name`,`pay_msg`,`pay_review_time`,`adjustment_status`,`ic_name`,`ic_card_type`,`reviewer_mode`,`inventory_channel`,`third_data_push_status`,`quality_order_no`) VALUES (262846,'RK20230625000316',30013,'LYZH13589001',270005,180036,'',NULL,'2023-06-25 00:00:00.000',NULL,NULL,210.00,0.00,210.00,NULL,210.00,'A00','纸张',1,NULL,0.800,168.00,NULL,NULL,'',NULL,'2023-06-25 11:26:00',3,4,'2023-06-25 23:24:45',0,3,NULL,NULL,'2023-06-25 11:25:38','2023-06-25 23:24:44',30525,'傅益玲','\'',NULL,2,NULL,NULL,'83653692186728700711687663398101','','',0.00,2,NULL,NULL,NULL,NULL,NULL,0,'董建军',1,2,2,0,NULL);

**Comment by manticore-projects** [comment]
Greetings,

if you want to use single quote `'` in strings, then you will need to quote/escape it like `''''` or `'\''`.
Then your statement will parse fine and [your can try it online here.](http://jsqlformatter.manticore-projects.com/jsqlformatter/demo.html?args=-c%20JIOQygogSgKgBKGB5OAnApgYwJ6YDboD6GmA9qgCZwAUAUHA3AJYX2MA0c5F6qhAdqTYNOAZyYAXIi2FxOTTAKGM5zRZgCGlQjJWcADqlIA3Frx2s9cTX0GzOE1BsxFRpAK6oXhMj3txHDR5CCSYAW3R-Jn4Q8MirDwlYiP8Ad3QmAHMACyTMo1FRNIycpIkteI44dKzcgXQJYtqkngp3TEarGtLCUQaJAgj+TqrDUjaOn3HKkTgxiaT+DRSrefay7H0Z1Vb1-0MFbYdScrx-JylUc41Li3P0U3R0q6sMR+e714emJ-NQldGGmwvXKEncRVWQMIEQk2XG+yh-yOcB4BCkliqFBuGl6Hi8yPQAEd3Ex9EMkr4CcTSeTPlVMBgbkQkf4wuMmAAzYEsyHYcy6QF82zLZEYMJaADW+yMACssEkBbMseUQptkQz0DdyHTZhqtcKAbMAEZ2L4uJimfiZAQi+7my3W5xkdzDBHA5YeV1WZU40TYfiYfxGm6YbJKN3Eb5PHWqfRQt4-VI2w2xqFhUSZCMJ6M8qpBGXgiS00Sg8FRRRLFPydRaCiqrb3d7mNl+KzRYzoYbkYGhjT8fjoM5WWFMbQ+wj6cFhks3MtWYkaPCSYHccyCOAASloADUAIIAGQAqhAwDQVAAmABs54AHAAWS+cADkUAA0ueAAzngDMH+vAFYPyA78AEZLyfThfw-EDv1kFQrCffcAE0AC0AAkYP-G8AE4gJAiC4HPAB2ICP3-TgQJvYDLzg+DZifAiQEPfd92fT8fwAWj-Djz3-OAgIALkEoCADpSKfWi6M4JiWOk5jWMIkCPzEj9JPgzhlKAzhzyUlS5JYtSrB0zSP2fXcgIIp9AA6-QACfQkuipLgED9IU5SqNUhz1Kcy8bz0uAZIUgLDKqBiXLYr9vy4y8eL4kCQIEq8hI-ezPKqb9ODvcLOO43jCO-BK7wEu9-xS1LVFMuB0v8+TgtmAKssinLYvi3iBO-G9LPYxrotyn8CqKu9StSyCyN459AFCFQApt0AJudLIYobPLCwiXNq1R6rgJ8b2-S9-227CdJvS8iNvEiPyIuKfKIy9L2-b9sJvJT8OfBaHOejS-PPValvWoKyrq+Slo8v7n0AYxDAC+9QBsxQI5zCK+5b+JczdaAAbiAA)

**Comment by WUWEI111222333** [comment]
thanks for your answer, but i have already  quote/escape it with '\''.
can you help me ,why the sql will occur error:    

INSERT INTO `recycle_record` (a,b,c,d,e,f) VALUES ('\'',NULL,2,NULL,NULL,'83653692186728700711687663398101');
![image](https://github.com/JSQLParser/JSqlParser/assets/35459358/393b9350-04ab-4dbf-88ed-8d666fe13db8)

**Comment by manticore-projects** [comment]
> hanks for your answer, but i have already quote/escape it with '''.

No, you have not: it would be `''''` not `'''` because one `'` opens the string, one `'` escapes, one `'` for the character and one `'` to close the string.

**Comment by WUWEI111222333** [comment]
it still can not work:
![image](https://github.com/JSQLParser/JSqlParser/assets/35459358/56e95163-9a05-4d28-bad2-d67e3ec98c40)

and i try it with java:
![image](https://github.com/JSQLParser/JSqlParser/assets/35459358/adcc5d9e-8d1c-448e-ab74-f25d521b2ae3)

the code is :
```java
String sql = "INSERT INTO recycle_record (a,b,c,d,e,f) VALUES ('\'',NULL,2,NULL,NULL,'83653692186728700711687663398101');";
        System.out.println(sql);

        CCJSqlParser ccjSqlParser = new CCJSqlParser(sql);
        FeatureConfiguration featureConfiguration = new FeatureConfiguration();
        featureConfiguration.setValue(Feature.allowBackslashEscapeCharacter,true);
        ccjSqlParser.withConfiguration(featureConfiguration);
        CCJSqlParserUtil.parseStatements(ccjSqlParser);
```

**Comment by manticore-projects** [comment]
https://manticore-projects.com/JSQLParser/usage.html#define-the-parser-features

```java
// Allow Back-slash escaping
sqlStr="SELECT ('\\'Clark\\'', 'Kent')";
Statement stmt2 = CCJSqlParserUtil.parse(
        sqlStr
        , parser -> parser
            .withBackslashEscapeCharacter(true)
);
```

**Comment by WUWEI111222333** [comment]
your sql is ok.but i wonder why my sql is wrong:

```java
String sql = "INSERT INTO recycle_record (a,b,c,d,e,f) VALUES ('\\'',NULL,2,NULL,NULL,'83653692186728700711687663398101');";
        String sql = "INSERT INTO recycle_record (a,f) VALUES ('\\'','83653692186728700711687663398101');";
//        String sql = "SELECT ('\\'Clark\\'', 'Kent')";

        Statement parse = CCJSqlParserUtil.parse(sql, ccjSqlParser -> ccjSqlParser.withBackslashEscapeCharacter(true));
        System.out.println(parse);
```

**Comment by manticore-projects** [comment]
Yours looks ok to me too and it should work.
I will analyze this in detail tomorrow.

**Comment by WUWEI111222333** [comment]
thanks so much !

**Comment by manticore-projects** [comment]
Only the specific `'\\''` (without any character after the `'`) does not work:

```sql
-- works
INSERT INTO recycle_record (a,f) VALUES ('\'anything', 'abc');
-- fails
INSERT INTO recycle_record (a,f) VALUES ('\'', 'abc');
```

The explanation is simple: the `''` after the slash `\` is read as SQL standard compliant escape.
I will look for a way working around this, but its complicated. Good catch though!

**Comment by WUWEI111222333** [comment]
good work, i am looking for a new version.
