### ISSUE TITLE
[BUG] JSQLParser 4.4 : HIVE SQL: no response

### ISSUE THREAD

**Issue by caoes** [JSQLParser/JSqlParser#1819]
Always check against the **Latest SNAPSHOT of JSQLParser** and the [Syntax Diagram](https://jsqlparser.github.io/JSqlParser/syntax.html)

Failing SQL Feature:
SQL is an error statement, the Program nonresponse 

SQL:
select 
concat('{','"dffs":"',if(dffs is null,'',cast(dffs as string),'","djr":"',if(djr is null,'',cast(djr as string),'","djrq":"',if(djrq is null,'',cast(djrq as string),'","thjssj":"',if(thjssj is null,'',cast(thjssj as string),'","thkssj":"',if(thkssj is null,'',cast(thkssj as string),'","sjc":"',if(sjc is null,'',cast(sjc as string),'","ldhm":"',if(ldhm is null,'',cast(ldhm as string),'","lxdh":"',if(lxdh is null,'',cast(lxdh as string),'","md":"',if(md is null,'',cast(md as string),'","nr":"',if(nr is null,'',cast(nr as string),'","nrfl":"',if(nrfl is null,'',cast(nrfl as string),'","nrwjid":"',if(nrwjid is null,'',cast(nrwjid as string),'","sfbm":"',if(sfbm is null,'',cast(sfbm as string),'","sjly":"',if(sjly is null,'',cast(sjly as string),'","wtsd":"',if(wtsd is null,'',cast(wtsd as string),'","xb":"',if(xb is null,'',cast(xb as string),'","xfjbh":"',if(xfjbh is null,'',cast(xfjbh as string),'","xfjid":"',if(xfjid is null,'',cast(xfjid as string),'","xm":"',if(xm is null,'',cast(xm as string),'","zhut":"',if(zhut is null,'',cast(zhut as string),'","zt":"',if(zt is null,'',cast(zt as string),'"}')
from tab 

Software Information:
- JSqlParser version 4.4
- Database HIVE

SQL is an error statement,when executed parser.Statement(), it's long time too wait, it's no response .

**Comment by manticore-projects** [comment]
Greetings.

Please use JSQLParser 4.7 SNAPSHOT.
It will return immediately, although with a parsing error:

```java
    @Test
    void testIssue1819() throws JSQLParserException {
        String sqlStr = "select\n" +
                " concat('{','\"dffs\":\"',if(dffs is null,'',cast(dffs as string),'\",\"djr\":\"',if(djr is null,'',cast(djr as string),'\",\"djrq\":\"',if(djrq is null,'',cast(djrq as string),'\",\"thjssj\":\"',if(thjssj is null,'',cast(thjssj as string),'\",\"thkssj\":\"',if(thkssj is null,'',cast(thkssj as string),'\",\"sjc\":\"',if(sjc is null,'',cast(sjc as string),'\",\"ldhm\":\"',if(ldhm is null,'',cast(ldhm as string),'\",\"lxdh\":\"',if(lxdh is null,'',cast(lxdh as string),'\",\"md\":\"',if(md is null,'',cast(md as string),'\",\"nr\":\"',if(nr is null,'',cast(nr as string),'\",\"nrfl\":\"',if(nrfl is null,'',cast(nrfl as string),'\",\"nrwjid\":\"',if(nrwjid is null,'',cast(nrwjid as string),'\",\"sfbm\":\"',if(sfbm is null,'',cast(sfbm as string),'\",\"sjly\":\"',if(sjly is null,'',cast(sjly as string),'\",\"wtsd\":\"',if(wtsd is null,'',cast(wtsd as string),'\",\"xb\":\"',if(xb is null,'',cast(xb as string),'\",\"xfjbh\":\"',if(xfjbh is null,'',cast(xfjbh as string),'\",\"xfjid\":\"',if(xfjid is null,'',cast(xfjid as string),'\",\"xm\":\"',if(xm is null,'',cast(xm as string),'\",\"zhut\":\"',if(zhut is null,'',cast(zhut as string),'\",\"zt\":\"',if(zt is null,'',cast(zt as string),'\"}')\n" +
                " from tab";
        Statement stmt = CCJSqlParserUtil.parse(
                sqlStr
                , parser -> parser
                        .withAllowComplexParsing(true)
                        .withTimeOut(6000)
        );
    }
```

**Comment by manticore-projects** [comment]
As I wrote above: Please use JSQLParser 4.7 Snapshot which returns the parsing error immediately.
