### ISSUE TITLE
[FEATURE] Support Postgres ON CONFLICT(col1, col2) syntax.

### ISSUE THREAD

**Issue by onukristo** [JSQLParser/JSqlParser#1820]
### Grammar or Syntax Description

JSQLParser fails to parse Postgres queries with multi-parameter "ON CONFLICT" statement.

### SQL Example

```sql
insert into fin_unique_tw_task_key(task_id,key_hash,key) values(?, ?, ?) on conflict (key_hash, key) do nothing
```

```
Caused by: net.sf.jsqlparser.JSQLParserException: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "," ","
    at line 1, column 95.

Was expecting:

    ")"
```

### Additional context
JSQLParser version: 4.6.
Postgres sql.

https://www.postgresql.org/docs/12/sql-insert.html
"index_expression
Similar to index_column_name, but used to infer expressions on table_name columns appearing within index definitions (not simple columns). Follows CREATE INDEX format. SELECT privilege on any column appearing within index_expression is required."

**Comment by manticore-projects** [comment]
Greetings.

This has been fixed already in JSQLParser 4.7 SNAPHSHOT and [you can test it online here.](http://jsqlformatter.manticore-projects.com/jsqlformatter/demo.html?args=-c%20JYOwzgpgTgLgBKGB7OAzUB9AriYBHLCDGAd2IEMwBrDKiATwAoZKbgATAGjvowAtKfbgwCUcAFAA3cgBtCYRgH5OcZarHikIOAGMtqGcB3xGPfoJU8x7FCCQw+oAOZA)

**Comment by onukristo** [comment]
Thank you :)

**Comment by manticore-projects** [comment]
Closed as solved.
