### ISSUE TITLE
 [BUG] JSQLParser 4.7-SNAPSHOT : Oracle : failing parsing CALL statement without parameters

### ISSUE THREAD

**Issue by ZhengguanLi** [JSQLParser/JSqlParser#1824]
This is a followup, duplicate of #1799 

### Failing SQL Feature:
-  `CALL my_procedure()` without parameters can't be parsed

### SQL Example:
- Simplified Query Example, focusing on the failing feature
    ```sql
    CALL my_procedure();
    ```
- Exception:
   ```
    net.sf.jsqlparser.JSQLParserException: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: ")" ")"
    at line 1, column 33.

    Was expecting one of:

    "!"
    "("
    "+"
    "-"
    "CONNECT_BY_ROOT"
    "NOT"
    "NULL"
    "XMLSERIALIZE"
    "{d"
    "{t"
    "{ts"
    "~"
    <S_CHAR_LITERAL>
    <S_DOUBLE>
    <S_HEX>
    <S_LONG>
   ```

### Software Information:
- JSqlParser version v4.7-SNAPSHOT
- Oracle

### Tips:
Oracle CALL: https://docs.oracle.com/cd/E24693_01/server.11203/e17118/statements_4008.htm

**Comment by manticore-projects** [comment]
Solved in JSQLParser 4.7 SNAPSHOT already. [You can try it here online.](http://jsqlformatter.manticore-projects.com/jsqlformatter/demo.html?args=-c%20MIQQMmAEC2CeD6AHATgewMYFMAmBXZmkAFAJQBQA3EA)

**Comment by ZhengguanLi** [comment]
I am using `(PlainSelect) CCJSqlParserUtil.parse(sqlStr)` with 4.7-SNAPHOT version,  I guess there is a inconsistency between when using in code and using in demo?

**Comment by manticore-projects** [comment]
Sorry, but you can not just forcefully cast into a `PlainSelect` without checking what `instance of` returns.
Your statement is no `Select` or `Query` but an `Execute` statement.

You can use `SHOW AST` to see the hierarchy of java objects:
![image](https://github.com/JSQLParser/JSqlParser/assets/18080123/a98e53f0-da38-45b2-bd79-f7a0dbc79a11)
