### ISSUE TITLE
[BUG] JSQLParser Version 4.6: Cannot parse MERGE statement

### ISSUE THREAD

**Issue by Tianqi1006** [JSQLParser/JSqlParser#1831]
### Failing SQL Feature:
- `MERGE` can't be parsed

### SQL Example:
```sql
MERGE Products AS TARGET USING UpdatedProducts AS SOURCE ON (TARGET.ProductID = SOURCE.ProductID)
```

### Software Information:
- JSqlParser version: 4.6

The error looks like this:

> Cannot parse statement: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "MERGE" "MERGE"
    at line 1, column 1.

Was expecting one of:

    "ALTER"
    "ANALYZE"
    "CALL"
    "COMMENT"
    "COMMIT"
    "DECLARE"
    "DESCRIBE"
    "DROP"
    "EXEC"
    "EXECUTE"
    "EXPLAIN"
    "GRANT"
    "PURGE"
    "RENAME"
    "RESET"
    "ROLLBACK"
    "SAVEPOINT"
    "SET"
    "SHOW"
    "TRUNCATE"
    "USE"
    <ST_SEMICOLON>

Does anyone have any idea what might be wrong with the above SQL MERGE statement? Thanks a lot in advance!

**Comment by manticore-projects** [comment]
Greetings.

Your `Merge` is missing the `WHEN MATCHED | WHEN NOT MATCHED` clauses.
[Please see here](https://manticore-projects.com/JSQLParser/syntax_snapshot.html#merge)

Without it your statement is invalid.

**Comment by manticore-projects** [comment]
Closing, since no further questions has been asked.

**Comment by Tianqi1006** [comment]
Thanks a lot for your examples @manticore-projects, I added the  `WHEN MATCHED` and `WHEN NOT MATCHED` clauses but it seemed to still show a ParseException error, do you know what I misunderstood? Thank you very much for your time!

The SQL statement I passed in:
`MERGE TargetProducts AS Target USING SourceProducts AS Source ON Source.ProductID = Target.ProductID WHEN NOT MATCHED BY Target THEN INSERT (ProductID,ProductName, Price) VALUES (Source.ProductID,Source.ProductName, Source.Price) WHEN MATCHED THEN UPDATE SET Target.ProductName = Source.ProductName, Target.Price = Source.Price WHEN NOT MATCHED BY Source THEN DELETE;`

**Comment by manticore-projects** [comment]
Greetings!

There is not `DELETE` clause in a Merge statement. Please look up the valid syntax here: https://manticore-projects.com/JSQLParser/syntax_snapshot.html#merge
