### ISSUE TITLE
[BUG] JSQLParser Version 4.6: Informix : Encountered unexpected token: "," ","

### ISSUE THREAD

**Issue by martin7569** [JSQLParser/JSqlParser#1832]
### Failing SQL Feature:
- can not parser the col[m, n] syntax

### SQL Example:
- Simplified Query Example, focusing on the failing feature
    ```sql
    select age, name, gender, citiy_code
    from user_info where city_code[1, 4] = '3301'
    ```

### Software Information:
- JSqlParser version 4.6
- Informix

### Error Info:
```java
net.sf.jsqlparser.JSQLParserException: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "," ","
    at line 19, column 16.

Was expecting one of:

    "&"
    ":"
    "::"
    "<<"
    ">>"
    "COLLATE"
    "["
    "]"
    "^"
    "|"

```

**Comment by manticore-projects** [comment]
Greetings.

If you need support for Informix specific syntax, you will need to provide or sponsor an implementation.

**Comment by SheldonKubor** [comment]
Greetings.

I have found that current version can support `col[m, n]`, maybe this issue can be closed?

**Comment by manticore-projects** [comment]
> Greetings.
> 
> I have found that current version can support `col[m, n]`, maybe this issue can be closed?

Lol!
So sorry I did not even recall that I implemented similar stuff before.

Always test any exception in the Online Formatter first. We get a lot of false reports against ancient versions of JSQLParser.

**Comment by manticore-projects** [comment]
Works with recent JSQLParser 4.8 and [you can test it online here.](http://jsqlformatter.manticore-projects.com/jsqlformatter/demo.html?args=-c%20MoUQMiDCAqAEsEMDmBTAUPTmA0sB2CAtullrqngCYoBOGp8uAxgJYAuLAngPpMD21NADEASgHkAsrACuAZ1rcWeAGZ80AdQASIESFis2PftQDaARlwAWALqwAvLADkAZmcAGM47QBuIA)
