### ISSUE TITLE
[BUG] JSQLParser 4.7-SNAPSHOT: Oracle: Unable to parse Full-Width Characters

### ISSUE THREAD

**Issue by ZhengguanLi** [JSQLParser/JSqlParser#1834]
### Failing SQL Feature:
- Unable to parse Full-Width Characters
- Example: `SELECT 1，2 FROM dual` can’t be parsed
### SQL Example:
- Simplified Query Example, focusing on the failing feature
    ```sql
    SELECT 1，2 FROM dual
    ```
### Software Information:
- JSqlParser 4.7-SNAPSHOT
- Oracle

JSQLFormatter online URL looks not correct, http://217.160.215.75:8080/jsqlformatter/demo.html which should be http://217.160.215.75:8080/jsqlformatter/JSQLFormatter/demo.html? And it keep saying "Session Ended ....".  I am using `(PlainSelect) CCJSqlParserUtil.parse(sqlStr)`, it throws error:
```java
net.sf.jsqlparser.parser.TokenMgrException: Lexical error at line 1, column 9.  Encountered: ‘65292’ (65292),
```

For this syntax, looks like Oracle add this support from 11g, related articles(no official doc from Oracle found):
- https://medium.com/@oracleblog/10g%E4%B9%8B%E5%90%8E%E6%94%AF%E6%8C%81%E4%B8%AD%E6%96%87%E9%80%97%E5%8F%B7%E4%BD%9C%E4%B8%BA%E6%9F%A5%E8%AF%A2%E5%88%86%E9%9A%94%E7%AC%A6-47fcaabc9e16 (please use Google Translate)
- https://medium.com/@Wflki/sql-injection-oracle-and-full-width-characters-13bb86fc034a

Not sure if this is needed to support the feature or take it as a bug or simply ignore it as it is pretty uncommon, just report it

**Comment by manticore-projects** [comment]
Greetings.

What exactly does "Full width characters" mean?
Using plain ASCII, [your statement works](http://jsqlformatter.manticore-projects.com/jsqlformatter/demo.html?args=-c%20MoUQMiDCAqAEsEYBQ9WoDSwExIGICUB5AWVgBMBXAQwBskBuIA)

However, when I copy your example it fails and I do not see where exactly it is different.

**Comment by manticore-projects** [comment]
> And it keep saying "Session Ended ...."

Thank you, fixed. I had to restart the Web Application Server.
