### ISSUE TITLE
[FEATURE] Support TABLE statement which added since MySQL 8.0.19

### ISSUE THREAD

**Issue by 134130** [JSQLParser/JSqlParser#1836]
### Grammar or Syntax Description
- `TABLE` statement is not supported yet
- `tableStatement ::= TABLE table_name [ORDER BY column_name] [LIMIT number [OFFSET number]]`

### SQL Example
- Simplified Query Example, focusing on the failing feature
	```sql
	TABLE columns;
	TABLE columns LIMIT 10;
	TABLE columns LIMIT 10 OFFSET 10;
	TABLE columns ORDER BY column_name;
	TABLE columns ORDER BY column_name LIMIT 10;
	TABLE columns ORDER BY column_name LIMIT 10 OFFSET 10;
	```

### Additional context
The used JSQLParser Version : `4.6` (4.7-snapshot also not supported yet)
State the applicable RDBMS and version : `MySQL 8.0.23`
Links to the reference documentation : https://dev.mysql.com/doc/refman/8.0/en/table.html

**Comment by 134130** [comment]
`DML` `MySQL`

**Comment by manticore-projects** [comment]
Greetings.

Sorry to be blunt, but I see little value in adding that because its RDBMS specific and redundant.
However, please feel free to submit a PR/Implementation if you are very interested in this particular statement.

**Comment by 134130** [comment]
@manticore-projects Never mind! thank you.
