### ISSUE TITLE
[BUG] JSQLParser Version 4.6: PostgreSQL: can not parse select

### ISSUE THREAD

**Issue by chenhong9** [JSQLParser/JSqlParser#1839]
### Failing SQL Feature:
can not parse select

### SQL Example:
    ```sql
    select bk_date,
              cast(now() as date) -integer '7' as last_7_date,
              cast(now() as date) -integer '30' as last_30_date 
   from fdm.dimtime 
    ```

### Software Information:
- JSqlParser version 4.6
- PostgreSQL,

### error info:
net.sf.jsqlparser.JSQLParserException:  Encountered unexpected token: "as" "AS"
    at line 2, column 41.

**Comment by manticore-projects** [comment]
Greetings.

Postgres' implicit cast `integer '7'` is not supported.
Please use the explicit cast, e.g. `Cast('7' as INTEGER)` or `'7'::int`.
