### ISSUE TITLE
ALTER TABLE XXX DROP COLUMN "YYY"; statement is not recognized

### ISSUE THREAD

**Issue by schweighart** [JSQLParser/JSqlParser#184]
The statment:
ALTER TABLE XXX DROP COLUMN "YYY";

produces following error:

net.sf.jsqlparser.parser.ParseException: Encountered " "DROP" "DROP "" at line 1, column 17.
Was expecting:
    "ADD" ...

**Comment by wumpz** [comment]
The main focus was to support selects. Alter, Create, etc. support in depth is now added step by step. BTW thx to contributors. This one is simply not yet implemented. Pull requests are wellcome.
