### ISSUE TITLE
[BUG] JSQLParser Version : 4.6

### ISSUE THREAD

**Issue by Lvbuqing** [JSQLParser/JSqlParser#1840]
![image](https://github.com/JSQLParser/JSqlParser/assets/32841009/03d19b01-9b59-44b6-a3ae-75a71391be4e)

java.lang.ClassCastException: class net.sf.jsqlparser.statement.select.Select cannot be cast to class net.sf.jsqlparser.statement.select.PlainSelect (net.sf.jsqlparser.statement.select.Select and net.sf.jsqlparser.statement.select.PlainSelect are in unnamed module of loader 'app')

**Comment by Lvbuqing** [comment]
![image](https://github.com/JSQLParser/JSqlParser/assets/32841009/65fb07be-c90c-41cf-89f1-1602b2f33dfc)

**Comment by manticore-projects** [comment]
Please note, that the WebSite relates to the latest API for JSQLParser 4.7 Snapshot (only).

If you use JSQLParser 4.6, then you will need to cast `Statement` into a `Select` which will have a property `PlainSelect` with a `SelectBody`. Download the old JSQLParser 4.6 JAVA API for reference.
