### ISSUE TITLE
[BUG] JSQLParser 4.6: RDBMS : TokenMgrError (chinese character)

### ISSUE THREAD

**Issue by weixiaonan1** [JSQLParser/JSqlParser#1845]
### Failing SQL Feature:
In version4.6, when we use chinese characters in SQL, TokenMgrError occurs. However, this issue was not present in previous versions like 3.2.
### SQL Example:
- use chinese characters in column alias without backquote. errors: TokenMgrException: Lexical error at line 1, column 14.  Encountered: '23383' (23383)
    ```sql
       select f1 as 字段 from table1
    ```
- use backquote, it works
    ```sql
       select f1 as `字段` from table1
    ```
- in version3.2, both the two sqls work well

**Comment by manticore-projects** [comment]
Greetings,

this has been fixed in JSQLParser 4.7 already.
[You can try it online here.](http://jsqlformatter.manticore-projects.com/jsqlformatter/demo.html?args=-c%20MoUQMiDCAqAEBmBGWBBYtDq2oVusBQAxAJQHkBZWAFwEMAjAGwFNEcBuIA)
