### ISSUE TITLE
Homepage badges aren't clickable

### ISSUE THREAD

**Issue by sivaraam** [JSQLParser/JSqlParser#1852]
The badges in [the homepage](https://jsqlparser.github.io/JSqlParser/index.html) such as JavaDocs and Maven Central aren't clickable. It would be nice if they could be made clickable so that it would be easy to access the corresponding resources from the website.

## Screenshot to clarify the badges I'm referring to
![image](https://github.com/JSQLParser/JSqlParser/assets/12448084/4833a273-40ee-4a73-ae64-07f2a2094854)

### Side plugs
1. In case the logo found in the website is indeed the one chosen for the library, consider updating the same in the GitHub org page too 🙂
2. Also, the website link could be updated in the [repository description on GitHub](https://github.com/JSQLParser/JSqlParser). This might mean the wiki may get less discoverable. We could address that by possibly linking to the wiki from the website so that it isn't missed.

cc @wumpz

**Comment by manticore-projects** [comment]
Greetings!

> In case the logo found in the website is indeed the one chosen for the library, consider updating the same in the GitHub org page too

Please elaborate, since the logos are identical.

**Comment by sivaraam** [comment]
> Please elaborate, since the logos are identical.

I suppose you're mentioning about the logo in the README and website. My suggestion is to upload the logo in the [organization page](https://github.com/JSQLParser). Right now it only shows the default logo.

![image](https://github.com/JSQLParser/JSqlParser/assets/12448084/10aedd3a-0e82-430d-9375-3359103bbf34))

**Comment by manticore-projects** [comment]
Thank you for the clarification.
You are right of course but only @wumpz was able to do that and as far as I understand it, he does not have any spare time at the moment.

**Comment by manticore-projects** [comment]
I will make the Badges clickable though.

**Comment by manticore-projects** [comment]
fixed via https://github.com/JSQLParser/JSqlParser/commit/be55d269536ab7916a5b5b0550d1e53ad90698f8
