### ISSUE TITLE
[BUG] JSQLParser 4.5 : PostgreSQL: Each parse statement creates extra temporary thread

### ISSUE THREAD

**Issue by skallod** [JSQLParser/JSqlParser#1853]
### Failing SQL Feature:
- Each parse statement creates extra temporary thread

### SQL Example:
- 
    ```
    select 1
    from dual
    ```

### Software Information:
- JSqlParser 4.5 +
- PostgreSQL

### Tips:
I talk about method `net.sf.jsqlparser.parser.CCJSqlParserUtil#parseStatement`.  
Body of it method in library version 4.1 :

```
try {
    return parser.Statements();
} catch (Exception var2) {
    throw new JSQLParserException(var2);
}
```
Body of it method in library version 4.5 :

```
Statements statements = null;
try {
    ExecutorService executorService = Executors.newSingleThreadExecutor();
    Future<Statements> future = executorService.submit(new Callable<Statements>() {
        @Override
        public Statements call() throws Exception {
            return parser.Statements();
        }
    });
    executorService.shutdown();

    statements = future.get( parser.getConfiguration().getAsInteger(Feature.timeOut) , TimeUnit.MILLISECONDS);
} catch (TimeoutException ex) {
    parser.interrupted = true;
    throw new JSQLParserException("Time out occurred.", ex);
} catch (Exception ex) {
    throw new JSQLParserException(ex);
}
return statements;
```
As we can see parseStatement method creates temporary thread every time when parse statement. Therefore our highloaded application perfomance goes down then application is restarted.

Can sqlparser 4.5 library be configured to parse statement in the invokation thread (i.e. not create extra thread) ?

**Comment by manticore-projects** [comment]
Greetings,

the problem has been acknowledged and we provide additional methods in JSQL 4.7-Snapshot, which accept an existing  `ExecutorService` instead of creating one. Please refer to https://jsqlparser.github.io/JSqlParser/javadoc_snapshot.html#ccjsqlparserutil

*Method:*
parse (sql, executorService, consumer) → [Statement](https://jsqlparser.github.io/JSqlParser/javadoc_snapshot.html#net-sf-jsqlparser-statement-statement)

**Comment by skallod** [comment]
Thank you for your answer !

Do you know, when is the 4.7-release planned ?

**Comment by manticore-projects** [comment]
Greetings, unfortunately I can't tell because @wumpz is under serious time constrains.

1) I try to get Maven Snapshot deployment up
2) then we can release 4.7-Snapshot as JSQLParser 5 (since it breaks a lot of API)

**Comment by manticore-projects** [comment]
Can we close this or do you expect me to do anything else here?

**Comment by manticore-projects** [comment]
A new version of JSQLParser including this improvement just has been released.
I am closing this.
