### ISSUE TITLE
[BUG] JSQLParser Version 4.7 : Redshift : Unable to parse SQL statement that worked fine with 4.6

### ISSUE THREAD

**Issue by zaza** [JSQLParser/JSqlParser#1858]
With JSQLParser 4.6 we used the following code to parse a SQL statement:

```java
      var timeoutTime = (int) TimeUnit.SECONDS.toMillis(parserTimeout);
      var parser = CCJSqlParserUtil.newParser(sql).withAllowComplexParsing(false).withTimeOut(timeoutTime);
      var statement = CCJSqlParserUtil.parseStatement(parser);
```
After upgrading to 4.7 we were forced to adjust it a bit so now it's:

```java
      var timeoutTime = TimeUnit.SECONDS.toMillis(parserTimeout);
      var statement = CCJSqlParserUtil.parse(sql,
              parser -> parser.withTimeOut(timeoutTime).withAllowComplexParsing(false));
```

Which is fine, less code, same effect. So we thought. Unfortunately it soon turned out the latest version of the parser fails to parse the statement below (for Redshift), while the previous one (4.6) had no issue with it:

```sql
CREATE TABLE "foo"
(
    event_sk               bigint identity             NOT NULL encode RAW,
 -- other columns ...
) compound sortkey (      date_key      );
```

The error we get is:
```
Caused by: net.sf.jsqlparser.JSQLParserException: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "RAW" "RAW"
    at line 3, column 72.

Was expecting one of:

    ")"
    ","
    "."

	at app//net.sf.jsqlparser.parser.CCJSqlParserUtil.parseStatement(CCJSqlParserUtil.java:315)
```

We also tried tweaking the code above a bit but to no avail:

```java
   var timeoutTime = TimeUnit.SECONDS.toMillis(parserTimeout);
      var parser = CCJSqlParserUtil.newParser(sql).withAllowComplexParsing(false).withTimeOut(timeoutTime);
      var executorService = Executors.newSingleThreadExecutor();
      var statement = CCJSqlParserUtil.parseStatement(parser, executorService);
```

Did we miss anything or is this a regression?

**Comment by manticore-projects** [comment]
Greetings!

It should work and I will figure out what is going on.

**Comment by manticore-projects** [comment]
Please give me the full statement, just in case.

**Comment by manticore-projects** [comment]
`ENCODE RAW` is the problem.
Without it, the statement works:

```java
@Test
void testIssue1858() throws JSQLParserException {
     String sqlStr = "CREATE TABLE \"foo\"\n"
                    + "(\n"
                    + "    event_sk               bigint identity             NOT NULL\n"
                    + ") compound sortkey (      date_key      )";
    assertSqlCanBeParsedAndDeparsed(sqlStr, true);
}
```

**Comment by zaza** [comment]
Can you please confirm `ENCODE RAW` is not an issue with the previous release i.e 4.6?

**Comment by manticore-projects** [comment]
> Can you please confirm `ENCODE RAW` is not an issue with the previous release i.e 4.6?

It does not matter, I'd rather focus on fixing/implementing it for you.
(Although DDL statements will always be problematic when not following SQL:2016 strictly.)

**Comment by manticore-projects** [comment]
Ok, so more precisely "RAW" is an issue since it is a predefined TOKEN (and thus not just any keyword).
I think, this particular token has changed/was introduced and so caused the problem.

**Comment by zaza** [comment]
Does this mean we should avoid [assigning RAW compression](https://docs.aws.amazon.com/redshift/latest/dg/c_Compression_encodings.html) to columns if we would like to parse the CREATE TABLE statement?

**Comment by zaza** [comment]
Oh sorry, missed the fact that you closed it _with a fix_. I guess we need to wait now for the next release and skip 4.7. Thanks a lot!

**Comment by manticore-projects** [comment]
> Does this mean we should avoid [assigning RAW compression](https://docs.aws.amazon.com/redshift/latest/dg/c_Compression_encodings.html) to columns if we would like to parse the CREATE TABLE statement?

Not necessarily. All we need to do is ensuring that all possible values of `RAW` are allowed and not collide with existing tokens.  If you really need this `RAW` clause, then maybe contribute a Test case covering all type of variants and then it would always checked before release.

(I do not use those syntax and have little interest in parsing DDL statements myself.)

**Comment by manticore-projects** [comment]
> I guess we need to wait now for the next release and skip 4.7.

I will provide you with a JAR which serves as drop in replacement, just a few minutes please.

**Comment by zaza** [comment]
No need for that, I can build the jar myself. Thanks again for fixing it so quickly.

**Comment by manticore-projects** [comment]
http://manticore-projects.com/download/jsqlparser-4.7/JSQLParser-4.8-SNAPSHOT.jar

Your are most welcome. Thanks for reporting.
