### ISSUE TITLE
[BUG] JSQLParser Version 4.7 : Support of the FETCH clause is incomplete

### ISSUE THREAD

**Issue by mdg1349** [JSQLParser/JSqlParser#1859]
### Failing SQL Feature:
Can't parse CASE WHEN expressions when the condition contains a sub select

### SQL Example:
This query is correctly executed by both PostgreSQL and IBM DB2 (others not tested)
`select a.*,case when (select 1 from test.dual fetch first row only)=1 then 'Y' else 'N' end from test.dual a`

### Software Information:
- JSqlParser versions: 4.7, 4.1, 3.2 (versions in between not tested)
- Databases: IBM DB2, PostgreSQL, probably others

### Tips:
Online test: http://jsqlformatter.manticore-projects.com/jsqlformatter/demo.html?args=-c%20M4UwNiDGAuAECGA6AVAGkvUsDuALEAdrABSgQywCMsAZgE4D2AtrNCMNIgCYCu8YtENEi5aASzodYjbLAYEwATwCUAXmrR8RAOQBNbbHBZtAOQOEutRizYdufAfCA

**Comment by manticore-projects** [comment]
Greetings.

```fetch first row only``` is unsupported syntax (though valid).
[Without it your statement works.](http://jsqlformatter.manticore-projects.com/jsqlformatter/demo.html?args=-c%20MoUQMiDCAqAEsEMB0AqAUPTmA0tIEFQMsTSB1ACRADlYAKeUCGWARmNM69gDEAlAPIBZWABcApgGdRSACYBXBABtYAehSwAZuNEBjABZaAlgCdpsEwHsA7rEsA7JQE8Uq2AEpYAXjYduXaCpaAHIATWC-f3hwUFhg6gio2BoAETR+YTEpGQVlRDQAbjQgA)

**Comment by manticore-projects** [comment]
Support for the [`FETCH` clause](http://217.160.215.75:8080/jsqlformatter/JSQLParser/syntax_snapshot.html#fetch) seems incorrect, since `Expression` is optional:

```sql
-- Failing
SELECT 1 FROM test.dual fetch first row only
```


![image](https://github.com/JSQLParser/JSqlParser/assets/18080123/674ef377-00ca-428a-9f46-64e283b40b05)

**Comment by manticore-projects** [comment]
I will fix this.

**Comment by mdg1349** [comment]
Thank you, in the meantime we will just substitute `fetch first row only` with `fetch first 1 rows only`.
As a side note, doing this substitution in the online test and trying the format SQL button truncates the whole fetch clause; the AST seems correct though

**Comment by manticore-projects** [comment]
Updated JAR from here: http://manticore-projects.com/download/jsqlparser-4.7/JSQLParser-4.8-SNAPSHOT.jar
