### ISSUE TITLE
[BUG] JSQLParser Version 4.6+, parse fail when sql with 3 or more '\n' 

### ISSUE THREAD

**Issue by tortoi-huang** [JSQLParser/JSqlParser#1860]
### Failing SQL Feature:
- any sql with 3 or more empty line

### SQL Example:
- Simplified Query Example, focusing on the failing feature
    ```sql
    -- parse this sql would throw an 'Encountered unexpect token' excption
    select 1,\n\n\n2 from dual
    ```

### Software Information:
- JSqlParser 4.6+
- Database ALL

### Tips:
test case
```java
final String sql = "select 1,\n\n\n2 from dual";
// throw exception
CCJSqlParserUtil.parse(sql);
```

**Comment by manticore-projects** [comment]
Greetings!

Its a feature, not a bug.
Why would you need 3 empty lines within your statement?

**Comment by tortoi-huang** [comment]
my job is review sql from different team, i can stop them to write the sql like this. this feature severely breaks the campatibility of version 4.3. maybe we should a switch to turn it off.

**Comment by manticore-projects** [comment]
> maybe we should set a switch to turn it off.

Its a Token in JavaCC (but not a production) and so it was very difficult to make it optional.
Also, its is not really needed since all you need to do was replacing the redundant empty lines before parsing, e. g.

```java
CCJSqlParserUtil.parse(sql.replace("\\n+", ""));
```

**Comment by manticore-projects** [comment]
Last but not least, I assume you come from `MyBatis Plus` (which is the main producer of those statements).
They have provided a fix for their behavior already.
