### ISSUE TITLE
[FEATURE] Add statement CREATE INDEX IF NOT EXISTS

### ISSUE THREAD

**Issue by zabojpetr** [JSQLParser/JSqlParser#1861]
### Grammar or Syntax Description
jSQLParser not support `CREATE INDEX IF NOT EXISTS`. 

### SQL Example
- Simplified Query Example, focusing on the failing feature
    ```sql
    CREATE INDEX IF NOT EXISTS test_test_idx ON test.test USING btree ("time");
    ```

### Additional context
The used JSQLParser 4.7.
Postgresql 12
https://www.postgresql.org/docs/current/sql-createindex.html

**Comment by suryaaki2** [comment]
@manticore-projects Waiting for this fix, when is the next release?
