### ISSUE TITLE
[BUG] JSQLParser 4.7: Postgresql: select nextval parse error

### ISSUE THREAD

**Issue by skallod** [JSQLParser/JSqlParser#1863]
### Failing SQL Feature:
- Example: `SELECT nextval ('client_id_seq');` can't be parsed

### SQL Example:
- Query Example
    ```SELECT nextval ('client_id_seq');```

### Software Information:
- JSqlParser version 4.7
- PostgreSQL

Parse of query `SELECT nextval ('client_id_seq');` throws exception:

```
ParseException: Encountered unexpected token: "SELECT" <K_SELECT>
    at line 4, column 1.

Was expecting one of:

    "WITH"
    <ST_SEMICOLON>
```
PS This sql query has been parsed fine in jsqlparser 4.6 version.

**Comment by manticore-projects** [comment]
Greetings!

Confirmed, thank you for reporting.
I will look into this immediately.

**Comment by manticore-projects** [comment]
Thank you for reporting. Rather embarrasing, that 3000plus tests did not contain 1 single unit for the Postgres `NextVal()` function.

I have added and fixed this and [you can test it online here.](http://jsqlformatter.manticore-projects.com/jsqlformatter/demo.html?args=-c%20MoUQMiDCAqAEByBTAHgFwG4EMA2AKWA5ALYCeA+gM6ICOArogHYDGiBsAlAFADcQA)

Latest Snapshot from here: http://manticore-projects.com/download/jsqlparser-4.7/JSQLParser-4.8-SNAPSHOT.jar

**Comment by skallod** [comment]
Thank you!
