### ISSUE TITLE
[BUG] JSQLParser4.7 : mysql : alter sql error 

### ISSUE THREAD

**Issue by lifejwang11** [JSQLParser/JSqlParser#1864]
Always check against the **Latest SNAPSHOT of JSQLParser** and the [Syntax Diagram](https://jsqlparser.github.io/JSqlParser/syntax_snapshot.html)

### Failing SQL Feature:
`FIRST` can't be parsed

### SQL Example:
- Simplified Query Example, focusing on the failing feature
    ```sql
    ALTER TABLE `test`.`test_table` MODIFY COLUMN `test` varchar(251) CHARACTER SET armscii8 COLLATE armscii8_bin NULL DEFAULT NULL FIRST
    ```

### Software Information:
- JSqlParser version 4.7
- Database mysql5.7

**Comment by manticore-projects** [comment]
Greetings.

Support for DDL statement is limited to standard compliant syntax: https://manticore-projects.com/JSQLParser/syntax_snapshot.html#createparameter
You will need to sponsor or provide an implementation if you need your specific syntax.

**Comment by manticore-projects** [comment]
There you go: https://manticore-projects.com/JSQLParser/syntax_snapshot.html#joinhint
Snapshot available here: http://manticore-projects.com/download/jsqlparser-4.7/JSQLParser-4.8-SNAPSHOT.jar

**Comment by tmlx1990** [comment]
> There you go: https://manticore-projects.com/JSQLParser/syntax_snapshot.html#joinhint Snapshot available here: http://manticore-projects.com/download/jsqlparser-4.7/JSQLParser-4.8-SNAPSHOT.jar

Hello, when will version 4.8 be released?

**Comment by manticore-projects** [comment]
Greetings!

Within a few days, as soon as @Wumpz finds a time.
