### ISSUE TITLE
[BUG] JSQLParser Version : 4.6  RDBMS : postgresql  jsonb_to_recordset

### ISSUE THREAD

**Issue by qiqingli** [JSQLParser/JSqlParser#1865]
### Failing SQL Feature:
- net.sf.jsqlparser.JSQLParserException: Encountered unexpected token: "jsonb_to_recordset" <S_IDENTIFIER>

### SQL Example:
- Simplified Query Example, focusing on the failing feature
```
select x.order_info->'esb'->'route'->>'msg_id' as msgId,
    x.order_info->'esb'->'interfacemsg'->>'REMIND_TYPE' as remindType,
    'del' as action,
    y."FILE_ID" as fileId,
    y."FILE_NAME" as fileName,
    y."FILE_PATH" as remoteDir,
    y."ENCODING" as fileEncoding,
    y."FTP_ADDRESS" as host,
    y."PORT" as port,
    y."USERNAME" as username,
    y."PASSWORD" as password
from oss_order_to_send x
    left join lateral jsonb_to_recordset(
        x.order_info->'esb'->'interfacemsg'->'REMIND_CONTENT'->'ATTACH_DEL'
    ) as y(
        "FILE_ID" text,
        "FILE_NAME" text,
        "FILE_PATH" text,
        "ENCODING" text,
        "IS_GPEOMS_SERV" text,
        "FTP_ADDRESS" text,
        "PORT" text,
        "USERNAME" text,
        "PASSWORD" text
    ) on true
```

### Software Information:
- JSqlParser version 4.6
- Database PostgreSQL

**Comment by manticore-projects** [comment]
Greetings, your statement seems to work with JSQLParser 4.8-Snapshot.
[Try it online here,](http://jsqlformatter.manticore-projects.com/jsqlformatter/demo.html?args=-c%20M4UwNiDGAuAEAeA6A9gJwCYlQfQJYDsAzZAWgD4ByEYAIwvItWQFdoR6zKBbYAcz3QVYAQ2CwevAJLoANAChYihCgxY8RUpWp0GBNqkLDIICR0oAlAKIBZSQDkAItgAqATQAKloaNioTBdGcATwAHEHklWApMMG8xI2hcZHwIpSDEACIAMUkAGUtsSQcMkTFCXAhpVMV07LyCuwBBa0sSn3KIO2EucIU0zJz87HdG5wAJNrE-LmQ2B1xUathayzsAYQB5B3sAcUnYDpBLfEhkdAJeJdqs53dsRocHKwBlZ-2AC2RgaCvM9w3zM59iE0D8+jVMgBVZ6WcxNFr7ZigVD4bq9SK1EavADqAOKpVgIVEwAA7mh0HJCEwuLAvsBsOS1NBkNhQPh0AhwbAIIQ4AArZAEbnCfTCMCwPnAZI0bDM7B+U4YUDQAAUXMiSEZOAIxAY2g4FD0WEMxlMDCstkc2E2dmcq2cBtGzkaazG2AcllyFC5AEoCUE1ZFInUhkUSmx4GCg0oQw1mq1YBGo9HYLHhqMJomQJGlsHVpttnY9lmc+qY5Jntgdp4NtZKzDzAA1cPZ5PR7K3e6PF5vEttoMZf6AlullOp6Gw+EJpO5mNY5648z4pO+2n4ROoZggIA)

(Although the formatter won't reflect it correctly.)

**Comment by manticore-projects** [comment]
Thank you for this documentation.
Based on the information provided, I am going to implement this for you.

**Comment by manticore-projects** [comment]
sorry, wrong issue.
