### ISSUE TITLE
[Feature] sql server 2012 left hash join support

### ISSUE THREAD

**Issue by jhd147350** [JSQLParser/JSqlParser#1866]
### Failing SQL Feature:
“left hash join” can't be parsed

### SQL Example:
```sql
select a.id, b.name
from table_a as a
         left hash join table_b as b on a.zid = b.id
where a.id > ?
```

### Software Information:
- JSqlParser version : 4.6
- Database: MS SQL Server 2012

### Exception:
```
java.util.concurrent.ExecutionException: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "left" "LEFT"
    at line 3, column 10.

Was expecting one of:

    "CONNECT"
    "EMIT"
    "GROUP"
    "HAVING"
    "PIVOT"
    "START"
    "WINDOW"
    <EOF>
    <ST_SEMICOLON>
```

**Comment by manticore-projects** [comment]
Greetings.

This MS SQL Server specific syntax is not supported.
You will need to provide or sponsor an implementation if you want to see that working.

**Comment by manticore-projects** [comment]
Greetings.

This MS SQL Server specific syntax is not supported.
You will need to provide or sponsor an implementation if you want to see that working.

**Comment by jhd147350** [comment]
> Greetings.
> 
> This MS SQL Server specific syntax is not supported. You will need to provide or sponsor an implementation if you want to see that working.

Thanks for your reply!

**Comment by jhd147350** [comment]
> I can't even find this feature for T-SQL: https://learn.microsoft.com/en-us/sql/t-sql/queries/from-transact-sql?view=sql-server-ver16
> 
> So I would like to suggest not using it.

https://learn.microsoft.com/en-us/sql/t-sql/queries/hints-transact-sql-join?view=sql-server-ver16

><join_hint> ::=   
     { LOOP | HASH | MERGE | REMOTE }

Sometimes we need to optimize the query speed
