### ISSUE TITLE
[BUG] JSQLParser Version 4.7 : MYSQL: Fail to parse delete statement with columns

### ISSUE THREAD

**Issue by human-user** [JSQLParser/JSqlParser#1868]
### Failing SQL Feature:
- Fail to parse delete statement with columns, it throws `JSQLParserException`
``` text
net.sf.jsqlparser.JSQLParserException: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "." "."
    at line 1, column 9.
```

### SQL Example:
- which parsing failed:
    ```sql
    delete a.* from test a
    ```

- which is ok:
   ```sql
    delete a from test a
    ```

### Software Information:
- JSqlParser version: 4.7
- Database: MYSQL

### Tips:
[example link](http://jsqlformatter.manticore-projects.com/jsqlformatter/demo.html?args=-c%20CYUwNiAuIAQIYDoBUMBmAnA9gWxtAzpPEA)

**Comment by manticore-projects** [comment]
Greetings!

Sorry, but your syntax does not make sense since you always delete rows from tables, not just certain columns.

**Comment by human-user** [comment]
@manticore-projects right, it's unnecessary to delete with columns, but these sql is still executable in MYSQL. 
In my case, I am using JSqlPaser to validate sql before execute and  in my options these sql should be pass.

**Comment by manticore-projects** [comment]
You could take a look at the Validator package and overwrite/amend the `Delete` validation for your own needs. You can always overwrite the Visitor methods quite easily.

However, I won't implement it or take it upstream.

**Comment by human-user** [comment]
thank you for helps
