### ISSUE TITLE
[BUG] 4.7: Failing to parse double quotes inside identifiers

### ISSUE THREAD

**Issue by kiranchitturi** [JSQLParser/JSqlParser#1869]
### Lexical error parsing double quotes inside a quoted name:
- JSQL parser (4.7) is not able to parse double quotes inside an already quoted identifier. What is the right way to escape double quotes inside a quoted identifier? 
- Example: `mean("a"/b") > 2.0` fails with conditional parsing. `mean("a\"/b") > 2.0` fails too

### SQL Example:
- Simplified Query Example, focusing on the failing feature
    ```sql
      project_id = 'projId' AND mean("a"/b") > 2.0
    ```
- Parsed using
 ```
       Expression expr = CCJSqlParserUtil.parseCondExpression(
              whereClause,
              false);
```
### Software Information:
- JSqlParser version 4.7

**Comment by kiranchitturi** [comment]
I have a related question too:

I want to extract the full string value present inside the function (E.g., eval from `mean(eval)`) but that's not possible if the value has special characters (division character) like `mean(eval/loss)`. Is there a way to get the full string inside the agg function by configuring jsql parser to ignore special characters inside agg functions?

**Comment by manticore-projects** [comment]
Greetings.

You can't escape or quote inside an Identifier, but only within char literals.
Any identifier like `"a/b"` valid. Why exactly would you want to quote the slash `/`?

**Comment by kiranchitturi** [comment]
Thanks for your quick reply. Sorry for the confusion, I didn't mean to quote the slash character. The quote can be present anywhere within the value.

This does work `"a""/b"`. Thank you! Does this only work with 4.7?

**Comment by kiranchitturi** [comment]
Since the quote is actually within the quoted identifier, would it be possible to not require extra escaping using `"`?

**Comment by manticore-projects** [comment]
Within a quoted identifier you don't need to escape anything but the double-quotes `"` because otherwise you would close the quotes.
