### ISSUE TITLE
[BUG] 4.7 : ANY : sqls with 3 new lines fail

### ISSUE THREAD

**Issue by anilpuliyeril** [JSQLParser/JSqlParser#1871]
Always check against the **Latest SNAPSHOT of JSQLParser** and the [Syntax Diagram](https://jsqlparser.github.io/JSqlParser/syntax_snapshot.html)

### Failing SQL Feature:
- Any sql with 3 or more new lines using a `with` clause fails. 
- if you remove couple of new lines it will work

### SQL Example:
- Simplified Query Example, focusing on the failing feature

```sql

WITH A AS (
  SELECT
    a1, a2
  FROM
    abc
)



select a1, a2 from A
```

### Software Information:
- 4.7
- Database Any

### Tips:
Please write in English and avoid Screenshots (as we can't copy and paste content from it).
[Try your example online with the latest JSQLParser](http://jsqlformatter.manticore-projects.com) and share the link in the error report.
Do provide Links or References to the specific Grammar and Syntax you are trying to use.

**Comment by manticore-projects** [comment]
It's a feature, not a bug. 2 empty lines `\n\n\n` terminate a statement.
Why exactly would you want to have more than 1 empty line within your statement? The only known software doing this was `My Batis Plus` and they fixed their code.

If you really need to work with such statements, then strip the empty lines before parsing.

**Comment by anilpuliyeril** [comment]
Thanks @manticore-projects. To give some background i use jsqlparser to validate sqls that my clients paste into a sqleditor. Since the sqls run on snowflake or postgres env in most use cases and both support multiple \n I don't restrict the client from adding multiple new lines. 
This used to work with earlier versions and so came up as a regression for me and hence asked.

**Comment by manticore-projects** [comment]
Greetings!

Thank you, I do understand and appreciate your feedback.
This feature has been introduced with JSQLParser 4.6 for a simple reason:

Image a SQL Editor where you write many queries like
```sql
select * from table_a


select * from table_b


update table table_a set a=b
````

Nobody would write the terminating Semicolons but you still want to get an error based parser message for the third statement only.

Of course this applies to parsing statements (plural) only and could be ignored when parsing one statement (singular), but that JavaCC does not provide the flexibility.
We could filter line breaks when parsing single statements but that may mess up token positions (relevant for formatters).

For that reason we delegated forcefully the responsibility to you:
1) statements should not contain more than 1 empty line (which is still reasonable I believe)
2) if your statements contain more than 1 empty line, you can simple replace those (when calling the parser

```java
CCJSQLParserUtils.parse(sqlStr.replace("\n\n*","\n");
```

One more thing:
The Validation capabilities are largely unmaintained and may be split off in a future release unless a strong maintainer or sponsor shows up. Right now the Validation may verify statements successfully which may fail on a certain RDBMS, its not guaranteed to work.

**Comment by manticore-projects** [comment]
Btw, I did my very best to document the features, use cases and behaviour: https://manticore-projects.com/JSQLParser/usage.html

Please feel very welcome to point out what was missing or unclear.
Thank you again for your feedback and interest!

**Comment by anilpuliyeril** [comment]
Thanks @manticore-projects the documentation is perfect just that i hadn't read this update.
