### ISSUE TITLE
[BUG] Date literals mistaken as doubles

### ISSUE THREAD

**Issue by Walrus2028** [JSQLParser/JSqlParser#1876]
Using this query: `SELECT * FROM users WHERE born > '1967-01-01'`

When I try to traverse the expression this method is never called:
`public void visit(DateValue dateValue) { ... }`

Instead, the `public void visit(String stringValue){ ... }` method is called.

JSqlParser version is 4.7

Thanks

EDIT: title should be changed to Date literals mistaken with strings

**Comment by Walrus2028** [comment]
In fact I would like how I have to write the SQL query so this methods are called:

```
public void visit(DateValue dateValue) {}
public void visit(DateTimeLiteralExpression) {}
public void visit(TimeValue timeValue) {}
public void visit(TimestampValue timestampValue) {}
```

Thanks

**Comment by manticore-projects** [comment]
Greetings.

You do provide a String and so you would get a String.
If you want to get a Date, you would need to provide a Date:

```sql
SELECT * FROM users WHERE born > {d '1967-01-01'};
SELECT * FROM users WHERE born > {ts '1967-01-01 00:00:00.00000'};
```

[You can test it online here.](http://jsqlformatter.manticore-projects.com/jsqlformatter/demo.html?args=-c%20MoUQMiDCAqAEBUsBiAlA8gWVgVwM4FMAnXWAdQAkQURYAjAe0IDtYA+WAbwBNYByARgCcANgDsAWgAM-Kf14BfIA)

![image](https://github.com/JSQLParser/JSqlParser/assets/18080123/d2a10b83-6828-43ff-a430-60af177b10eb)

**Comment by manticore-projects** [comment]
Btw, the fact that your RDBMS allows comparing `Dates` and `Strings` is a courtesy implemented inside the `Equals` Expression. You should not take it for granted, meaning `JSQLParser` won't do that because its not its job.

**Comment by Walrus2028** [comment]
Thanks, also this literals can be used to tell the parser the type:

DATE 'str'
TIME 'str'
TIMESTAMP 'str'
