### ISSUE TITLE
[BUG] JSQLParser Version : RDBMS : failing feature description

### ISSUE THREAD

**Issue by qianying1** [JSQLParser/JSqlParser#1877]
Always check against the **Latest SNAPSHOT of JSQLParser** and the [Syntax Diagram](https://jsqlparser.github.io/JSqlParser/syntax_snapshot.html)

### Failing SQL Feature:
net.sf.jsqlparser.parser.CCJSqlParserUtil#parse(java.lang.String, java.util.function.Consumer<net.sf.jsqlparser.parser.CCJSqlParser>)
parse sql ERROR

The value was parsed into VALUES

### SQL Example:
select * from tableName t where (value in (?,?))
![image](https://github.com/JSQLParser/JSqlParser/assets/20952019/a0987cb0-3b8f-4616-9e9d-97ed825eb036)

### Software Information:
- JSqlParser version    4.7
- Database (e. g. Oracle, MS SQL Server, H2, PostgreSQL, IBM DB2 )
H2 Version 2.2.224 (2023-09-17)

### Tips:
Please write in English and avoid Screenshots (as we can't copy and paste content from it).
select * from tableName t where (value in (?,?))
![image](https://github.com/JSQLParser/JSqlParser/assets/20952019/6379ee5a-7d76-4ba8-9f75-d70ab108ab4f)

**Comment by manticore-projects** [comment]
Greetings.

Yes, of course. `VALUE` is a valid statement:

```sql
-- VALUE is a protected keyword
 -- Because this is a valid useful statement
VALUE ( 1 )
;

-- Quote the keyword when referring to a column name
SELECT *
FROM tablename t
WHERE ( "VALUE" IN ( ?, ? ) )
;
```

[You can try it online here.](http://jsqlformatter.manticore-projects.com/jsqlformatter/demo.html?args=-c%20LTAEDUEEBkFUFFQEsDOoCGoAOAnA9gC4CmAxsQCagDWRAngO547kBQoIoAQqegK4pFQBABapkaTADd0AGySV+RAGa8ZoFAXTEAtkQB2BFlDiIAFKACMoAJQsA3CxYcAir0KCRgmgyaV6w-VAcZSIcHCQ9AHMhPAxQEjwZXm09UD10XRYAZXhoeABhABVQACoWADEAJQB5AFkhdAAjGX0MjxYAdQAJeEqzUAAiYwQB0ABJADlQcwB+ABpQGZsbeyA)

**Comment by manticore-projects** [comment]
Here is the list of Restricted keywords: https://manticore-projects.com/JSQLParser/keywords.html

**Comment by qianying1** [comment]
Copied! Thank you for your time to reply this question!

**Comment by manticore-projects** [comment]
You are most welcome.
I would closed this as explained and resolved.
