### ISSUE TITLE
[BUG] JSQLParser 4.7 : PostgreSQL: columns prefixed by "public" not accepted in schema parse

### ISSUE THREAD

**Issue by ndepomereu** [JSQLParser/JSqlParser#1879]
Hi,

### Failing SQL Feature:
- It's not possible to parse on PostgreSQL a create table that contains a column with a **public** prefix.

### SQL Example:

```
CREATE TABLE public.film (
    film_id integer DEFAULT nextval('public.film_film_id_seq'::regclass) NOT NULL,
    title character varying(255) NOT NULL,
    description text,
    release_year public.year,
    language_id smallint NOT NULL,
    rental_duration smallint DEFAULT 3 NOT NULL,
    rental_rate numeric(4,2) DEFAULT 4.99 NOT NULL,
    length smallint,
    replacement_cost numeric(5,2) DEFAULT 19.99 NOT NULL,
    rating public.mpaa_rating DEFAULT 'G'::public.mpaa_rating,
    last_update timestamp without time zone DEFAULT now() NOT NULL,
    special_features text[],
    fulltext tsvector NOT NULL
);
```
The parse of the table will fail on the line:
   **rating public.mpaa_rating DEFAULT 'G'::public.mpaa_rating,**

and throw:
```
net.sf.jsqlparser.JSQLParserException: Encountered unexpected token: "public" "PUBLIC"
    at line 1, column 127.

Was expecting one of:
...
```

### Software Information:
- JSqlParser 4.7
- PostgreSQL 11.3+.

**Comment by manticore-projects** [comment]
Greetings.

It seems to boil down to Keyword/Tokens:

```sql
-- works in general
select 1::private.integer;

-- PUBLIC fails
select 1::public.integer;
```

I will see what I can do about this.

**Comment by manticore-projects** [comment]
Please note:

When using the custom type, the the schema name does not allow restricted keywords (except `PUBLIC`, which I allowed explicitly) unless quotes.
The type name itself allows all tokens now.

I still would recommend proper quoting since custom types are use-cases I do not have much experience with.
Do let me know when facing any more hurdles with this, examples are welcome.
