### ISSUE TITLE
DateValue toString() not correct

### ISSUE THREAD

**Issue by thaichat04** [JSQLParser/JSqlParser#188]
We should use an explicite DateFormat to parser input date in net.sf.jsqlparser.expression.DateValue, and write back in toString():
@Override
    public String toString() {
        return "{d '" + value.toString() + "'}";
    }

Default SQL format should be 'yyyy/DD/mm'.

**Comment by wumpz** [comment]
Proper jdbc escape format is yyyy-mm-dd. Slash is not valid there.

-------- Ursprüngliche Nachricht --------
Von: Hong-Thai Nguyen <notifications@github.com> 
Datum: 27.10.2015  17:33  (GMT+01:00) 
An: JSQLParser/JSqlParser <JSqlParser@noreply.github.com> 
Betreff: [JSqlParser] DateValue toString() not correct (#188) 

We should use an explicite DateFormat to parser input date in net.sf.jsqlparser.expression.DateValue, and write back in toString():

@Override

    public String toString() {

        return "{d '" + value.toString() + "'}";

    }

Default SQL format should be 'yyyy/DD/mm'.

**Comment by wumpz** [comment]
By the way, here is the comment from java.sql.Date.toString()

~~~
    /**
     * Formats a date in the date escape format yyyy-mm-dd.
     * <P>
     * @return a String in yyyy-mm-dd format
     */
    public String toString () {
~~~

exactly what it should do.

**Comment by thaichat04** [comment]
OK, I passed java.util.Date instead of java.sql.Date into DateValue
Can close.

**Comment by thaichat04** [comment]
FYI, I used 0.9.4 without toString() implementation on DateValue, that's was the reason of this bug. BTW, 0.9.5-snapshot fixed already.

Thanks
