### ISSUE TITLE
[FEATURE] MERGE  ON without ()

### ISSUE THREAD

**Issue by cverdela** [JSQLParser/JSqlParser#1880]
### Grammar or Syntax Description
Hello, when I use JSqlParser to parse 'MERGE' statement and there are missing parentheses after 'ON,' it throws an error. 

### SQL Example
merge into table1 USING ( select * from table2) c on table1.aa=c.aa WHEN NOT MATCHED THEN INSERT ( bb,aa ) VALUES (c.aa, c.bb ,c.cc)

**Comment by manticore-projects** [comment]
Greetings.

For SQL:2016 and JSQLParser, the Brackets are mandatory for the `Merge` statement.
