### ISSUE TITLE
[JavaCC] JavaCC compilation issue

### ISSUE THREAD

**Issue by cverdela** [JSQLParser/JSqlParser#1882]
I'm trying to compile a JJT file using JavaCC on my own, but I'm not sure if the placement of the comment at line 743, which is 'Block Block() #Block,' is correct. 
`Block Block() #Block :`
Or could it be an issue with my JavaCC version? The compiler no longer reports an error when I change it to 'Block Block() :.' I apologize, as I am new to using JavaCC.
`Block Block() :`

**Comment by manticore-projects** [comment]
I am sorry, but this is not a JSQLParser issue, but rather a question about how to use JavaCC.
You could easily use the Maven or Gradle JavaCC plugin as shown in the JSQLParser build.
