### ISSUE TITLE
use javacc to generate java files, but JSqlParserCC.jjt file it didn't work

### ISSUE THREAD

**Issue by kukuxian** [JSQLParser/JSqlParser#1885]
some error mes like this, i use cmd to use javacc .but it error.what's problem. hava anyone  ever encountered this problem?

D:\pjx\1_project\javacc_test\demo6>javacc JSqlParserCC.jjt
Java Compiler Compiler Version 4.1d1 (Parser Generator)
(type "javacc" with no arguments for help)
Reading from file JSqlParserCC.jjt . . .
Warning: Line 20, Column 5: Bad option name "JAVA_TEMPLATE_TYPE".  Option setting will be ignored.
Warning: Line 24, Column 5: Bad option name "NODE_DEFAULT_VOID".  Option setting will be ignored.
Warning: Line 25, Column 5: Bad option name "TRACK_TOKENS".  Option setting will be ignored.
Warning: Line 26, Column 5: Bad option name "VISITOR".  Option setting will be ignored.
Warning: Line 27, Column 5: Bad option name "GRAMMAR_ENCODING".  Option setting will be ignored.
org.javacc.parser.ParseException: Encountered " "#" "# "" at line 505, column 23.
Was expecting one of:
    "throws" ...
    ":" ...

Detected 1 errors and 5 warnings.

**Comment by manticore-projects** [comment]
Greetings.

`Java Compiler Compiler Version 4.1d1`
You are using an ancient version of `JavaCC`. Please retry with recent `JavaCC-7.12`.

**Comment by manticore-projects** [comment]
I am closing this, since it is not a JSQLParser problem.
