### ISSUE TITLE
[BUG] JSQLParser 4.7 : any : some CASE-based expressions takes too long to process

### ISSUE THREAD

**Issue by mateusmeyer** [JSQLParser/JSqlParser#1889]
Always check against the **Latest SNAPSHOT of JSQLParser** and the [Syntax Diagram](https://jsqlparser.github.io/JSqlParser/syntax_snapshot.html)

### Failing SQL Feature:
- When parsing expressions like `CASE WHEN [...] END = value` in certain nesting depth, there's a massive slowdown in parsing.
- When replacing the offending snippet with `CASE WHEN CASE WHEN [...] END = value THEN 0, 1 END`, the parse works way more faster.

### SQL Example:
- Simplified Query Example, showing the slow parsing:
    ```sql
    SUM(SUM(CASE
                   WHEN IssueDeadline IS NULL THEN 'Indeterminate'
                   WHEN IssueDeadline < CONVERT(DATETIME, CONVERT(DATE, COALESCE(IssueClosedOn, CONVERT(DATETIME, CONVERT(DATE, GETDATE()), 121)))) THEN 'PastDue'
                   WHEN (IssueDeadline>=CONVERT(DATETIME, CONVERT(DATE, GETDATE()), 121)
                         AND IssueDeadline<=CONVERT(DATETIME, CONVERT(DATE, GETDATE()+3), 121)) THEN 'Alert'
                   ELSE 'OnTime'
               END = 'PastDue'))

    ```
- Replacing the offending SQL with this makes the parsing much faster:
    ```sql
    SUM(SUM(CASE
                   WHEN CASE
                            WHEN IssueDeadline IS NULL THEN 'Indeterminate'
                            WHEN IssueDeadline < CONVERT(DATETIME, CONVERT(DATE, COALESCE(IssueClosedOn, CONVERT(DATETIME, CONVERT(DATE, GETDATE()), 121)))) THEN 'PastDue'
                            WHEN (IssueDeadline>=CONVERT(DATETIME, CONVERT(DATE, GETDATE()), 121)
                                  AND IssueDeadline<=CONVERT(DATETIME, CONVERT(DATE, GETDATE()+3), 121)) THEN 'Alert'
                            ELSE 'OnTime'
                        END = 'PastDue' THEN 1
                   ELSE 0
               END))
    ```

### Software Information:
- JSqlParser version: 4.7
- Database (e. g. Oracle, MS SQL Server, H2, PostgreSQL, IBM DB2 ): SQL Server syntax

### Tips:
Please write in English and avoid Screenshots (as we can't copy and paste content from it).
[Try your example online with the latest JSQLParser](http://jsqlformatter.manticore-projects.com) and share the link in the error report.
Do provide Links or References to the specific Grammar and Syntax you are trying to use.

**Comment by manticore-projects** [comment]
Greetings!

Interestingly, it's not about the `CASE WHEN` itself, but particularly about the 2nd `WHEN` condition. Without it the statement runs in 2 seconds, with it 44 seconds:

```java
    @Test
    void testPerformanceIssue() throws JSQLParserException {
        String sqlStr = "SELECT "
                        + "SUM(SUM(CASE\n"
                        + "               WHEN IssueDeadline IS NULL THEN 'Indeterminate'\n"
                        + "               -- WHEN IssueDeadline < CONVERT(DATETIME, CONVERT(DATE, COALESCE(IssueClosedOn, CONVERT(DATETIME, CONVERT(DATE, GETDATE()), 121)))) THEN 'PastDue'\n"
                        + "               WHEN (IssueDeadline>=CONVERT(DATETIME, CONVERT(DATE, GETDATE()), 121)\n"
                        + "                     AND IssueDeadline<=CONVERT(DATETIME, CONVERT(DATE, GETDATE()+3), 121)) THEN 'Alert'\n"
                        + "               ELSE 'OnTime'\n"
                        + "           END = 'PastDue'))\n";

        Statement stmt2 = CCJSqlParserUtil.parse(
                sqlStr
                , parser -> parser
                                    .withAllowComplexParsing(true)
                                    .withTimeOut(60000)
        );
    }
```

**Comment by manticore-projects** [comment]
I have tried various things on the Grammar to make your statement faster, especially about function parameters.
I was able to find better Grammar for your particular statement (bringing the time down to 9 seconds from 44) -- but every attempt broke other Tests, especially about `JSON` related stuff.

The deeply nested expressions are an issue for us (and we are aware of this) but I am unable to resolve that.

**Comment by manticore-projects** [comment]
We brought this down to 450 ms, while still keeping all other test cases intact.
Beware: the new production `SimpleFunction` is pretty much tailored to fit this particular use-case of deeply nested, single parameter function calls. Even a rather simple deviation may render this solution in-effective. Please feel welcome to post more examples.
