### ISSUE TITLE
[FEATURE] Configure used statement separators

### ISSUE THREAD

**Issue by serhiizapalskyi** [JSQLParser/JSqlParser#1891]
### Grammar or Syntax Description
Starting from jsqlparser version 4.6 my queries started to fail with errors like below:

```
Error: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "\n\n\n" <ST_SEMICOLON>
    at line 7, column 31.

Was expecting one of:

    "&"
    ")"
    "::"
    "<<"
    ">>"
    "CONNECT"
    "EMIT"
    "GROUP"
    "HAVING"
    "START"
    "WINDOW"
    "["
    "^"
    "|"
```

It happens because I have multiple blank lines in a row in a query caused by the behavior of my sql generation engine. It worked fine before 4.6. 

From the other side I see in the documentation: 

> Supported Statement Separators are Semicolon ;, GO, Slash / or two empty lines \n\n\n.

Is it possible to somehow configure the list of Statement Separators to avoid treating the  \n\n\n as delimiter?

### SQL Example
- Simplified Query Example, focusing on the failing feature
    ```sql

   SELECT unified.id

   FROM db.events_qa unified



   WHERE unified.time >= TIMESTAMP_MILLIS(1657843200000) AND unified.time <= TIMESTAMP_MILLIS(1657929600000)
   AND (unified.id IS NOT NULL AND coalesce(unified.env, 0) = 0)
   AND unified.uid = 'fff'


   ORDER BY my_key
   limit 100
    ```

### Additional context
The used JSQLParser Version 4.7

Thank you in advance!
Best regards, Serhii Zapalskyi

**Comment by manticore-projects** [comment]
Greetings.

2 empty lines `\n\n\n` are terminating a statement. This has been explained in a couple of issues, please look it up in the issue history.

**Comment by serhiizapalskyi** [comment]
I know, But is there a way to configure this?

**Comment by manticore-projects** [comment]
No, because its a Token and Token can't be changed in the Grammar.
However, you can easily strip empty lines before handing the string to the parser: `String.replace("\n\n+", "\n")`

**Comment by serhiizapalskyi** [comment]
Yep, it's clear. Thank you very much for the explanation.
