### ISSUE TITLE
Unable to parse insert into table syntax

### ISSUE THREAD

**Issue by GdHuni** [JSQLParser/JSqlParser#1892]
If your SQL statements is insert into the table the table would be an error net. Sf. Jsqlparser. JSQLParserException: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "." "."

**Comment by manticore-projects** [comment]
Please provide a specific SQL example.

**Comment by GdHuni** [comment]
String sql = "insert into table xy_temp.tb select * from test.tbl";
        String sql = "insert overwrite xy_temp.tb select * from test.tbl";
        String sql = "insert overwrite table xy_temp.tb select * from test.tbl";
Scenes like these

**Comment by GdHuni** [comment]
> Please provide a specific SQL example.
    String sql = "insert into table xy_temp.tb select * from test.tbl";
    String sql = "insert overwrite xy_temp.tb select * from test.tbl";
    String sql = "insert overwrite table xy_temp.tb select * from test.tbl";

**Comment by manticore-projects** [comment]
Your syntax is invalid and not standard compliant, your keywords `OVERWRITE` and `TABLE` are not supported.
[You can check for the valid syntax here.](http://217.160.215.75:8080/jsqlformatter/JSQLFormatter/syntax.html#insert)
[You can test your corrected statements interactively here.](http://jsqlformatter.manticore-projects.com/jsqlformatter/demo.html?args=-c%20JIOQygogSgKgBKGB5OB6AVAFwIYCMA2ApuqnAB4CeA+poQLYAOAdJrgCYBQkAMhAMLx0HAGJQkAWTi0AzphYEOAbg6hIsNOgD2AN0IAnAO56AlrRIIQyctVqN5XCLwFwhoiVMKz5+JSvDR4DB19I1NiUkQUDBwCcOsaemZWBydBETFJGTlWH0UgA)

**Comment by GdHuni** [comment]
> Your syntax is invalid and not standard compliant, your keywords `OVERWRITE` and `TABLE` are not supported. [You can check for the valid syntax here.](http://217.160.215.75:8080/jsqlformatter/JSQLFormatter/syntax.html#insert) [You can test your corrected statements interactively here.](http://jsqlformatter.manticore-projects.com/jsqlformatter/demo.html?args=-c%20JIOQygogSgKgBKGB5OB6AVAFwIYCMA2ApuqnAB4CeA+poQLYAOAdJrgCYBQkAMhAMLx0HAGJQkAWTi0AzphYEOAbg6hIsNOgD2AN0IAnAO56AlrRIIQyctVqN5XCLwFwhoiVMKz5+JSvDR4DB19I1NiUkQUDBwCcOsaemZWBydBETFJGTlWH0UgA)

However, in hive and spark engines, the above syntax is valid. Can't this be supported? Many users use this syntax, causing me to fail with jsqlparse

**Comment by manticore-projects** [comment]
You can provide or sponsor an implementation, when you are interested in this particular feature.
