### ISSUE TITLE
[BUG] JSQLParser 4.6: PostgreSQL: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "(" "("

### ISSUE THREAD

**Issue by young0098** [JSQLParser/JSqlParser#1901]
Always check against the **Latest SNAPSHOT of JSQLParser** and the [Syntax Diagram](https://jsqlparser.github.io/JSqlParser/syntax_snapshot.html)

### Failing SQL Feature:
- Brief description of the failing SQL feature
net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "(" "(" at line 58, column 11.

### SQL Example:
- Simplified Query Example, focusing on the failing feature
    ```sql
    -- Replace with your ACTUAL example
  INSERT INTO  CORP_LNACC_BSC_INF_W(
    ALRDYREPY_PRD_NUM,
    NONACR_INT,
    RCVBUTNT_INT,
    COLL_NOT_CLTINT,
    ASTSCRTZ_BAL,
    CNCLAFVERF_INT,
    FST_REPYPNP_DT,
    FTM_REPYINT_DT,
    TFRCOLLRGLRPNPINT_AMT,
    TFRCOLLODUEPNPINT_AMT,
    TFRCOLLRGLRPICDINTAMT,
    TFRCOLLODUEPICDINTAMT,
    ODUE_PNAMT,
    GRP_INNR_DEALG_INSID,
    BSN_CLCD,
    DSBR_DEP_BNK_ACCNO,
    REPY_BNK_ACCNO,
    NONACR_NEXP_PNAMT,
    NONACRALRDY_EXP_PNAMT,
    CNCLAFVERF_NEXP_PNAMT,
    CNCLAFVERFALYEXPPNAMT,
    CNCLAFVERFNANEXPPNAMT,
    ORI_CST_ACCNO,
    SBARSN,
    DFLT_INTRT_CND_ID,
    CRNPRDRGLRPNP_INT_AMT,
    CRNPRDODUEPNP_INT_AMT,
    EXPDTR_DTL_ID,
    ETL_JOB_NM,
    ETL_SRC_TBL_NM,
    BTCH_NO,
    UDT_TMS
  ) SELECT
  COALESCE(P1.ALRDYREPY_PRD_NUM, 0) AS ALRDYREPY_PRD_NUM,
  COALESCE(P1.NONACRNEXPPNP_INT_AMT, 0) + COALESCE(P1.NONACRALRDYEPNPINTAMT, 0) + 
  COALESCE(P1.NONACRNEPPICMPDINTAMT, 0) + COALESCE(P1.NONACRALRDYEPICINTAMT, 0) AS NONACR_INT,
  CASE
    WHEN P1.ACC_STCD = '0002006'
    OR P1.LN_CNCLAFVERF_TPCD IN('1', '2') THEN 0
    ELSE COALESCE(P1.RGLR_PNP_INT_AMT, 0) + COALESCE(P1.ODUE_PNP_INT_AMT, 0)
  END AS RCVBUTNT_INT,
  CASE
    WHEN P1.ACC_STCD = '0002006'
    OR P1.LN_CNCLAFVERF_TPCD IN('1', '2') THEN 0
    ELSE COALESCE(P1.RGLRPNPINTCMPDINT_AMT, 0) + COALESCE(P1.ODUEPNPINTCMPDINT_AMT, 0) + COALESCE(P1.NONACRNEXPPNP_INT_AMT, 0) + COALESCE(P1.NONACRALRDYEPNPINTAMT, 0) + COALESCE(P1.NONACRNEPPICMPDINTAMT, 0) + COALESCE(P1.NONACRALRDYEPICINTAMT, 0) + COALESCE(P1.TFRCOLLRGLRPNPINT_AMT, 0) + COALESCE(P1.TFRCOLLODUEPNPINT_AMT, 0) + COALESCE(P1.TFRCOLLRGLRPICDINTAMT, 0) + COALESCE(P1.TFRCOLLODUEPICDINTAMT, 0)
  END AS COLL_NOT_CLTINT,
  CASE
    WHEN P1.ACC_STCD = '0002006'
    OR P1.LN_SCRTZ_TPCD NOT IN('1', '2') THEN 0
    ELSE COALESCE(P1.RGLR_PNAMT, 0) + COALESCE(P1.ODUE_PNAMT, 0) + COALESCE(P1.NONACR_NEXP_PNAMT, 0) + COALESCE(P1.NONACRALRDY_EXP_PNAMT, 0) + COALESCE(P1.CNCLAFVERF_NEXP_PNAMT, 0) + COALESCE(P1.CNCLAFVERFALYEXPPNAMT, 0) + COALESCE(P1.CNCLAFVERFNANEXPPNAMT, 0) + COALESCE(P1.CNCLAFVERFNAAEXPPNAMT, 0)
  END AS ASTSCRTZ_BAL,
  CASE
    WHEN P1.LN_CNCLAFVERF_TPCD NOT IN('1', '2') THEN 0
    ELSE COALESCE(P1.CNCLAFVERFNEPNPINTAMT, 0) + COALESCE(P1.CNCLAFVERFAEPNPINTAMT, 0) + COALESCE(P1.CNCLAFVERFNEPICINTAMT, 0) + COALESCE(P1.CNCLAFVERFAEPICINTAMT, 0) + COALESCE(P1.CNCLAFVERFNANEPINTAMT, 0) + COALESCE(P1.CNCLAFVERFNAAEPINTAMT, 0) + COALESCE(P1.CNCLAFVFNANEPICINTAMT, 0) + COALESCE(P1.CNCLAFVFNAAEPICINTAMT, 0) + COALESCE(P1.CNCLAFVERFTCRPPINTAMT, 0) + COALESCE(P1.CNCLAFVERFTCOPPINTAMT, 0) + COALESCE(P1.CNCLAFVEFTCRPICINTAMT, 0) + COALESCE(P1.CNCLAFVEFTCOPICINTAMT, 0)
  END AS CNCLAFVERF_INT,
  COALESCE(
    CASE
      WHEN P2.RPMD_CD IN('300', '311', '312', '320') THEN P10.CAL_FST_SETL_DATE :: DATE
      WHEN P2.RPMD_CD = '100' THEN CASE
        WHEN P2.LN_CLROFF_CODT = '' THEN '${NULLDATE}'
        ELSE COALESCE(P2.LN_CLROFF_CODT, '${NULLDATE}')
      END :: DATE
      WHEN P2.RPMD_CD = '200' THEN CASE
        WHEN P2.LN_CLROFF_CODT = '' THEN '${NULLDATE}'
        ELSE COALESCE(P2.LN_CLROFF_CODT, '${NULLDATE}')
      END :: DATE
      WHEN P2.RPMD_CD = '330' THEN P10.CAL_FST_SETL_DATE :: DATE
    END,
    DATE('${NULLDATE}')
  ) AS FST_REPYPNP_DT,
  COALESCE(
    CASE
      WHEN P2.RPMD_CD IN('300', '311', '312', '320') THEN P10.CAL_FST_SETL_DATE :: DATE
      WHEN P2.RPMD_CD = '100' THEN CASE
        WHEN P2.LN_CLROFF_CODT = '' THEN '${NULLDATE}'
        ELSE COALESCE(P2.LN_CLROFF_CODT, '${NULLDATE}')
      END :: DATE
      WHEN P2.RPMD_CD = '200' THEN CASE
        WHEN P1.FST_DSBR_DT = '' THEN '${NULLDATE}'
        ELSE COALESCE(P1.FST_DSBR_DT, '${NULLDATE}')
      END :: DATE
      WHEN P2.RPMD_CD = '330' THEN P9.ARR_LAST_INRT_ADJ_DT :: DATE
    END,
    DATE('${NULLDATE}')
  ) AS FTM_REPYINT_DT,
  COALESCE(P1.TFRCOLLRGLRPNPINT_AMT, 0) AS TFRCOLLRGLRPNPINT_AMT,
  COALESCE(P1.TFRCOLLODUEPNPINT_AMT, 0) AS TFRCOLLODUEPNPINT_AMT,
  COALESCE(P1.TFRCOLLRGLRPICDINTAMT, 0) AS TFRCOLLRGLRPICDINTAMT,
  COALESCE(P1.TFRCOLLODUEPICDINTAMT, 0) AS TFRCOLLODUEPICDINTAMT,
  COALESCE(P1.ODUE_PNAMT, 0) AS ODUE_PNAMT,
  COALESCE(P2.GRP_INNR_DEALG_INSID, '') AS GRP_INNR_DEALG_INSID,
  COALESCE(P2.BSN_CLCD, '') AS BSN_CLCD,
  COALESCE(P2.DSBR_DEP_BNK_ACCNO, '') AS DSBR_DEP_BNK_ACCNO,
  COALESCE(P2.REPY_BNK_ACCNO, '') AS REPY_BNK_ACCNO,
  COALESCE(P1.NONACR_NEXP_PNAMT, 0) AS NONACR_NEXP_PNAMT,
  COALESCE(P1.NONACRALRDY_EXP_PNAMT, 0) AS NONACRALRDY_EXP_PNAMT,
  COALESCE(P1.CNCLAFVERF_NEXP_PNAMT, 0) AS CNCLAFVERF_NEXP_PNAMT,
  COALESCE(P1.CNCLAFVERFALYEXPPNAMT, 0) AS CNCLAFVERFALYEXPPNAMT,
  COALESCE(P1.CNCLAFVERFNANEXPPNAMT, 0) AS CNCLAFVERFNANEXPPNAMT,
  COALESCE(P12.ORI_CST_ACCNO, '') AS ORI_CST_ACCNO,
  COALESCE(P12.SBARSN, 0) AS SBARSN,
  COALESCE(P2.DFLT_INTRT_CND_ID, '') AS DFLT_INTRT_CND_ID,
  COALESCE(P7.CRNPRDRGLRPNP_INT_AMT, 0),
  COALESCE(P7.CRNPRDODUEPNP_INT_AMT, 0),
  COALESCE(P13.DTL_ID, '0') AS EXPDTR_DTL_ID,
  'TP03_CORP_LNACC_BSC_INF_W__A9999_A0200.PL' AS ETL_JOB_NM,
  'TBCLLAC0_H' AS ETL_SRC_TBL_NM,
  '${BRANCH_ID}' AS BTCH_NO,
  NOW() AS UDT_TMS 
  FROM TBCLLAC0_H P1
  LEFT JOIN TBCLLAR0_H P2 ON P2.START_DATE <= TO_DATE('${TXNDATE}', 'YYYY-MM-DD')
  AND P2.END_DATE > TO_DATE('${TXNDATE}', 'YYYY-MM-DD')
  AND P1.LNAR_ID = P2.LNAR_ID
  AND P1.MULTI_TENANCY_ID = P2.MULTI_TENANCY_ID
  AND SUBSTR(P2.SPLIT_BRANCH_CD, 1, 5) = '${MTID}'
  LEFT JOIN TBCLCRI0_H P3 ON P3.START_DATE <= TO_DATE('${TXNDATE}', 'YYYY-MM-DD')
  AND P3.END_DATE > TO_DATE('${TXNDATE}', 'YYYY-MM-DD')
  AND P1.LNAR_ID = P3.LNAR_ID
  AND SUBSTR(P3.SPLIT_BRANCH_CD, 1, 5) = '${MTID}'
  LEFT JOIN TBCLLIH0_A P7 ON P7.DATA_DATE = TO_DATE('${TXNDATE}', 'YYYY-MM-DD')
  AND P7.CST_ACCNO = P1.CST_ACCNO
  AND P7.MULTI_TENANCY_ID = P1.MULTI_TENANCY_ID
  AND P7.BOOKENTRDT = P1.ACT_DT
  AND DATE(P7.BOOKENTRDT) = TO_DATE('${TXNDATE}', 'YYYY-MM-DD')
  AND SUBSTR(P7.SPLIT_BRANCH_CD, 1, 5) = '${MTID}'
  LEFT JOIN TMP_CORP_LNACC_BSC_INF_W03 P8 ON P8.LOAN_ACCNO = P1.CST_ACCNO
  AND P8.MULTI_TENANCY_ID = P1.MULTI_TENANCY_ID
  LEFT JOIN TMP_ARR_LAST_INRT_ADJ_DT P9 ON P1.LNAR_ID = P9.PDAR_ID
  LEFT JOIN TMP_CAL_FST_SETL_DATE P10 ON P1.CST_ACCNO = P10.LOAN_ACCNO
  LEFT JOIN TBCLPAC0_H P12 ON P12.START_DATE <= TO_DATE('${TXNDATE}', 'YYYY-MM-DD')
  AND P12.END_DATE > TO_DATE('${TXNDATE}', 'YYYY-MM-DD')
  AND P12.CST_ACCNO = P1.CST_ACCNO
  AND P12.MULTI_TENANCY_ID = P1.MULTI_TENANCY_ID
  AND SUBSTR(P12.SPLIT_BRANCH_CD, 1, 5) = '${MTID}'
  LEFT JOIN ARRANGEMENT_H P13 ON P13.START_DATE <= TO_DATE('${TXNDATE}', 'YYYY-MM-DD')
  AND P13.END_DATE > TO_DATE('${TXNDATE}', 'YYYY-MM-DD')
  AND P13.LNAR_ID = P2.LNAR_ID
  AND P13.CONTRACT_NUM = P2.CRLN_CTR_ID
  AND P13.MULTI_TENANCY_ID = P2.MULTI_TENANCY_ID
  AND SUBSTR(P13.SPLIT_BRANCH_CD, 1, 5) = '${MTID}'
  AND P13.DEL_FLAG = '0'
  AND P13.LNAR_ID <> ''
  WHERE
  P1.START_DATE <= TO_DATE('${TXNDATE}', 'YYYY-MM-DD')
  AND SUBSTR(P1.SPLIT_BRANCH_CD, 1, 5) = '${MTID}'
  AND P1.END_DATE > TO_DATE('${TXNDATE}', 'YYYY-MM-DD')
    ```

### Software Information:
- JSqlParser 4.6
- PostgreSQL

### Tips:
Please write in English and avoid Screenshots (as we can't copy and paste content from it).
[Try your example online with the latest JSQLParser](http://jsqlformatter.manticore-projects.com) and share the link in the error report.
Do provide Links or References to the specific Grammar and Syntax you are trying to use.

**Comment by manticore-projects** [comment]
Your statement parses fine with JSQLParser 4.8 Snapshot and [you can try it online here](http://jsqlformatter.manticore-projects.com/jsqlformatter/demo.html?args=-c%20LTAECUFMAcBsEMDGlQHcCWAXAFqAngPYCuATqAIIDCAKgKrkAyokAHvALZyQBQAkgHIBlAKLhqoAdQDyoRARLQA+rAB2SRIoBGAZw3oVAM0WpQACm6hLoeLBIATPCRh5F0e4pVF2FqwBpQKgRqiCSK+pg+lv4kiABumkSYKphhyZGg-nKwsB4EKYiwmOHp-vDamLokmABeWjYlsioF8AaxkCRGxVYZoAblik7QeNAqSnYR3f4GmOwDzuGK4w2YBjEE2SQA5rYj0AscE36gK2vZBHZEMKP77IdRx6tZttsK6Ih24QfLj+uw55d7d6fW4Nf6QVxqEGTUCbBSpFShOyQGybVLadB2Bo6FSKArvBp2bSaREwLQqADWinUgQagxcmgpVMQiBp0MCwVCKlYShGXzZQSQJBs9hc3IhfKOLOarXaRi5LB5kLuPSlCBlHRseG5vKhkqaaraHTU8ugOuV-nk6Fx-WpBAaRPgJG0KgJBkKqUwVVxKjsYUx0JCo3sWx2ow9VN190DbjsYN24Yl92540RmByGIakDTigAVgRNB5vNCszltDFFJhNDkVEWjppMIhsLkGkRxhX2NpQABKbgiBjCGiWSgEGyQXSQUygaAARgAdMKHHTXO5POx-AAGbsUQTWWyL5zL32r9LQ4ej8eTmez9mCk3xm6YDdbgDUoDPsDHyEvc5vIQXWt2YFH1ATcu1AV930-Ccpx-AVAxgQFOA+ZIDifHtugwzDLAgkcPwvGDrzgoU9wAt4gLQ7cAiIj0TyOShyBEWisKsAB1AAJYR+AI9RFHKd5QAAXlAABydcxIAJjEgA2YSmOY+SpHAAjVG9aVDSMTBoH4gQzBE6dhP8YTxOE7s5PkqxqA4rj1zMrDhAYEQ31wqDv1nENQnvZII2A0DwKc88vwIsEISUB80NsyxOIAEUomJ4kSLyuiw-x6MY8zMPYzjuOZXiGzsQSRLE9dJPXGSIvSyxFOUnFVRadSKy0-KdMnYT9MM4zTIq5jLKymyuqsezHMg-Cr3cwDkkQJCwpAl9-LwwKrzja4JqmrzUJmsCcIC6Cr1-Eg7zDabfK2+adtgjl-yuPYUNuCiTpcgi9q5U03lWzB1uOuaHt2ojLsBciNr84aFrnE4njG5aUg+2bgbO2cwd+Jbrqh27AfukbQZ+DYXkBZD3tRz7YdchGzguGA3jx6H0PS6LKKeXJ8kKJLMJShjhHK7pMq4q8eL4-KhNEiTpNk-rzKqq8VMqGoGv4-gpHEZq9IMkSOup0WLKskCOYGhzhC+jG3JecUCZh5yDeCs07v1kHCI5DwxUttHrbhvb-0UB2lStomCNq9U5Q9qmgbNm3ffUzVtU9p3vavUPZWNCPA-RkP9TquP4HgBOTbV+TaYY6xyil2pNHqZjWbS0Wueq1SDVlGX8rlhWuJatqVZM7P1Z66ztci3Xndc2OjSugHCeDuGB4MDPxvxnzTe2-uU7956yJumfNr7n2F7D8nEGH2fTvntS06XlevdHg+a6NdPyZPqOz43tSDHj-6b5Huf74NR+r+f6fT7fmPN9lA2BQyNE7r3-ofDoDYCAvRfnvb6c5Y7TBCN-UB0cEEAKQdA5eP8NrlVzjuceNFS7r1SuzdWldoDiTctAdgvptJN26MJAAzGJEW6t2EsxEkw6c+lu4cOSlw6cxk+H8IwoZJhkk24iI1llGc65ZyIBsIoPoKRtAlkWPATAkAABc2iorkGoGQiumtKHUNobifmelWHSMsJ3N8bMbGgAoVQlSBQSAEAMEYOQ4wCrCTYaI2xmthIABIADe-BaAMAYPowxABffx7DBp62ji4mqtgPFePOMBEJ4TInRIMcIeJnVRa010TEox-VnFmLoZYoy1jRF2NIY4qprj0meNxFk3xCSGlBLCREqJ5T4mOKSWA1JuI2mZPGIZPpeTBlSPVqUvRBS+FVIUOY-iAsmEsO6aLOxciFFKJUbxdRdhNE6KWYYvB-AYr+CimclqMyBkFKKWBMCecjl0njEsYh3smnkJMVQtZNSJAMKsMw+pASOHiJ4TsyFFVoXCLhew8RkjikcL2dOeRiichHLUdmU5WiynLP+bIwFNDgUC0xeuWFXVGkONES0tJ7j2neMwF0xx3Q7E5P6fkuJNKKojJSbOVpzLJnZMebywp8ySnXNAESy5JLuZkvWbUkq-L0p0vLhwihc4jmEmJIsNlAt1X9S5RKuZwze5oNnHqokqZpm5KeXytFXVFnlJWQC6pFjfFbOpY4vZABOecJBQgIH6PoL08A7A5kNfKipOdZW3PuSJc1zy25bneTMOYQwFjfIEdakmzxQzI28hRPOhaIYlsTGIsBmNTh-DJlPUtgNy1YwbQCSG3k5IpTvleCtOMKa7zeTuftOxB0r27bW+Gba4zjpwb5Vt9bZ1AgnT83tc4LaRwXTuTd1bTy9qobCUKKgESLGRLAVE+h0R2EMumvOR74QkhRGiDMa6-5UOxOM94t6M07k-Xif0+aD2zn1SSJQDJKS2h-cO0AoGz3gcZLaSdQqlwQaZCyAg0HYoHjQ0ht9+9HrURNMbVelE9r2wVCR5D67baCjdgHLOZHfokXdpRs01G-7oIgf7NjW7f2NG4xRxUe66I0fHuHBUjtt0CYvhPWAWpJNKg4wR8Bsn46KcDnnce6nTRKfw-AqhlprRQ2ZIELDecjOIBtKZu0+mMZUIdE6FQZadyOedMp76VC7BuhSOEL0LJfQYnMzubz7o-P5B9H6DzI0ADsCj9oxkrQmLO0WFpxejPYJGyXV6pbOkwkD2YguFTvTuZMnpDXpkA5w4S1AAAK64mGKEoIpWrigGD8CoJQRQAAhQQXWBAADFFAsUUIocgAaJsBrG8VMSs5asMBMnndReYCw1knTV7rlAolUHXIoNii3SvZjLBoSs1ZazVbCd18A5B+CUDYooXgUUil53rI2ZsxD+AEFQKYGDrYUgzG0NwAb4ApAAFljiaAKAgRAu3cAznSP2Ab4gABSUgdKVih46WHU5xJySkEq2c5RHQpAJSgAAPEJagBBFB3K0Q80J1AAAa1y02GQAJoc7Z8AUHoPgBRSitK8yN2YqmMgJF0noAAB8oAqc0+TTkpnLO+Xs859z3n-PBfyWF9VR0foCqmNULr196VtdXnYEQJmFYxfwCaC4DE+uqHm8t1o40iA7dVa17KwQRAdCekvA5uAWAtBCiaE2b9oBpz+AAKxbgFmE0H1BHtDO6IjlHaOuIY9gCEdA2PoBMLx9zfLROvQS4pzL6ntPoIK+Z3MlXHO1d84Fy65ipv8ti99BL6XsvK-08V7XkSnOuc88b5rlvsqJZqFCPboSefhWT6ixVbX3vfckEvEXwPKRiQ27e+HyPoAY9gTj6EhPSeEmp9AKj9HkPsjoGwLt+AU4YsF8fyBzR8ANFaIKt3+XYS++s4H6rsPhrs3lhKbultZhhvrgghAayCbuPnFk7kUFbq7u7lAbOIgVaC7tvu7uVGAbOJoAQAQOSGLp6D4jPnOEgCTsqGPjFD3i-gQUQSQfYGyofuXnLnTimgzjXv-sJIPg3sAe3KAV7j7uUKvi-toBvsHtvmHjehHtHrHpwSfk9mfsIEjhfunscJwB0nCIbjlDoHoIYMYA1lOAABzP7QAmHCojg4i2hoFWYmYYa4Hj6WEYHIHYF67kHoEW5IFYG24L5WDn6X4Z5aGOihplC+YIhQzRqGpTgBrmFziG5T6WLQBBrQCnJJEI6qFp7o5aHYrKL9B4o5AS5yLxEKIwEEBQHyJ-A27oawGWCBEaGZ7QBIC55CLxEObvQl5nKgBl7f4cHV5K5Sp15D7q5N6CGYSm5CKzjt4f4oBd4V4-5cGDHxLDH8FjFOEi5TH2G1EVGeHbF4ZwGbGO7eGYHW5+HT4ESuG+Fu7+FC7CEr7fgB6wBB5b6h4WL+B74H6+Lx6J7KGZFqFBHWAho26bCQDsAkGKBw7Tj57MT44wRF6dEk7dG9ELH9G-7cHK4AH15AHrGL7j7QnTHi7dHzHsFV7onLHKy8GAGjGj5CGbH5aJEeE45z5G4e40HwkKJBCeiUEeBeAO7xauLlbG53H0leHO5nE3EXGmJXESk4F4kxTL6iHfjr7PGb4h476yGfEKE5JKHJ6HEclIg4oICbC+J+rykcmMn25k7S5+LcCZTgB6xXjF5Imf4omkm94YlDFYkjEj4upL4iF+4EQSGqlSFvG77yGsE6m-F6mWCTGEkd7ElsF0EDH95UnYk0mmQADcQAA)

**Comment by luweiwei2222** [comment]
this site "HTTP ERROR 502"
