### ISSUE TITLE
[BUG] JSQLParser 4.7 : Bigquery : escaped with backslash quote not parsing

### ISSUE THREAD

**Issue by serhiizapalskyi** [JSQLParser/JSqlParser#1902]
Hello, migrating from 4.0 to 4.7. 

### Failing SQL Feature:
Quote escaped with backslash failed to parse. Version 4.0 parse this SQL without errors. 
Found this [issue](https://github.com/JSQLParser/JSqlParser/issues/1541) which says it should parse.

### SQL Example:
- Simplified Query Example, focusing on the failing feature
    ```sql
    WITH user_assigned_service_to_users_events AS (select
                euid,
                count(distinct ( case when  m.childname = 'You'||'\'ve' then e.euid else null end)) as fromunassigningmcafee
            from db.events e
            group by 1,2
            HAVING (
                   count(distinct ( case when  m.childname = 'You'||'\'ve' then e.euid else null end)) > 0
                )
                )
              select user_assigned_service_to_users_events.euid from user_assigned_service_to_users_events
    ```

### Software Information:
- JSqlParser version 4.7
- Database Bigquery

### Tips:
this [SQL](http://jsqlformatter.manticore-projects.com/jsqlformatter/demo.html?args=-c%20OoSQKgEgBArgzgUwE4H0CGc4EsDmA7BAExUSQDcsBjBFAFwHsV5k4UEyE9a4oBBAZSgAKRABsElWgCgosufIVQA7gFs2MLIQA0MxXtmV6MLkMJY4tLHknColDAmUALTrJUA6Sk6yjCeNCqOALxQAOQAmkahAD7RofEcoVC0LnhQCO6q6prpoohQeDCioul4hACU5VAYUABmSPQqxhjY+FY4Kva1CAi6+rL1jemUrIQARu4ADg3E42wcXDy9-XI4DTCTUGMAnlAAjFoATH39ELwAaiAAcgDiwicrCobGtKbmlta0tvb5Sqlunm8vn8gSgIQiUVi8VCiWS-wyWQQGkIuXyhWKpQqVQAfFAAAwPR7lQkrYmPORiCRfZioFq4AjEUgUah0Rg01jsTjcTJqJE5QYqWCkdCYelEEjIZk0BhMUgchbcIA) works 

this [SQL](http://jsqlformatter.manticore-projects.com/jsqlformatter/demo.html?args=-c%20LTAEDMEMEsBsFMAmoAuB7CaBOBbSLQBnFSLFAKAHUBJAFQAlQBXQ+LAfUkMOgHMA7JO1ZYAbtADG8dunYs2hdvFHx+KQqACCAZVAAKVggkVQps+YugA7jiVNoiADTlLrsxLRM1exNGLR+Y31QCS54awALVVMcADoJCLhEfkgccIBeUAByAE1PLIAfAqyAHSyVLNQo-lB4WJs7B1rYVlB+JlhYWv5EAEpe0C4ILDQcLy4eAQDeHFDweHgXNzNwEZxaiUVEACNYgAcRxHYdpRU1DUXls14Rpj3QbYBPUABGRwAmJav6TQA1agAcgBxfRfK6WDxeFA+PwoAJBPQhMKRaKgOIJJIpNKgTK5fJFUrleCVFDVWr1WzwezIeAtcLtTrdPoDAB8oAADGDwaBelzwbzuaZDPAgvIOBM+IIjiJxFIZGg5CJFMpVOoKY1kKtRswRJxuJKhDLJNJZGLlWd1OQQBAYAhkOhMLh8EygA) can't be parsed

Thank you in advance.
Regards

**Comment by manticore-projects** [comment]
Greetings.

For `Backslash` Quoting, you need to activate `BackSlashEscapeCharacter` as [explained here](http://217.160.215.75:8080/jsqlformatter/JSQLParser/usage.html#how-to-use-it).
[You can try your statement online and interactively here.](http://jsqlformatter.manticore-projects.com/jsqlformatter/demo.html?args=-c%20OoSQKgEgBArgzgUwE4H0CGc4EsDmA7BAExUSQDcsBjBFAFwHsV5k4UEyE9a4oBBAZSgAKAFBRxE8fwCiAGWkBhMOIDuAWzYwshMZL36ANFAX0YXIVAAiIfmBAA5JcOMDpu-R897gEafahqAHSUABZYADaEeGhqCFAAvFAA5ACapklQAD6ZyQA6SRxJ7l4lJZB+UAiB6praxaUNUHIyUPYAqrKy9Y36fpZQAJSDfIIAZkj0amYY2PhYeDhqlGijCAjd4gBiAEoA8gCylZSshABGgQAOE8RnbBxcPOueAOJ7bQAKUABCKZIAjBtGkYAEyAiC8ABqDmezhMZloFmstgcTgsClcgJ6+h8FSCoQiURicUSqXSWRySXyhUxWM85X8VRqCC0OlpDWa0laHS6bI8fWGQwAfFAAAwCkQyeROZioGa4AjEUgUah0Rgy1jsTjcaoaZl1HYHWCkdCYeVEEjIZU0BhMUga+7cEQAbiAA)
