### ISSUE TITLE
[BUG] JSQLParser Version : RDBMS : failing feature description net.sf.jsqlparser.JSQLParserException: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "AND" "AND"     at line 4, column 1.  Was expecting:      <EOF>

### ISSUE THREAD

**Issue by oymy** [JSQLParser/JSqlParser#1905]
Always check against the **Latest SNAPSHOT of JSQLParser** and the [Syntax Diagram](https://jsqlparser.github.io/JSqlParser/syntax_snapshot.html)

### Failing SQL Feature:
- sql parse failed when sql has two empty lines before AND.
-  the exception is 
```java
net.sf.jsqlparser.JSQLParserException: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "AND" "AND"
    at line 4, column 1.

Was expecting:

    <EOF>

	at app//net.sf.jsqlparser.parser.CCJSqlParserUtil.parseStatement(CCJSqlParserUtil.java:315)
	at app//net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:116)
	at app//net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:85)
```

### SQL Example:
- Simplified Query Example, focusing on the failing feature
    ```java
    @Test
    void test_fail_because_2_new_lines() throws JSQLParserException {
        String sqlStr =
                "select * from t where id = 1\n\n\nAND name = '2'";
        TestUtils.assertSqlCanBeParsedAndDeparsed(sqlStr, true);
    }

    @Test
    void test_succcess_when_1_new_line() throws JSQLParserException {
        String sqlStr =
                "select * from t where id = 1\n\nAND name = '2'";
        TestUtils.assertSqlCanBeParsedAndDeparsed(sqlStr, true);
    }
    ```

### Software Information:
- JSqlParser master branch

### Tips:

http://jsqlformatter.manticore-projects.com/jsqlformatter/demo.html?args=-c%20MoUQMiDCAqAEBUAoAYgJQPIFlYBdEHUAJEVEWASwBNYBeWARkSdhdgEEA5AEVgDsBDALYBTWrADkAJnGIA3EA

**Comment by manticore-projects** [comment]
Greetings.

2 empty lines `\n\n\n` terminate a statement. Please look-up the issue history for more verbose explanations.

**Comment by oymy** [comment]
thx, is there a way to change this behavior ? 

my sql has ; as terminate.

**Comment by manticore-projects** [comment]
You can simply strip empty lines from your sql text before passing it to JSQLParser.
```java
String.replaceAll("\\n\\n+", "\\n");
```

**Comment by oymy** [comment]
> You can simply strip empty lines from your sql text before passing it to JSQLParser.
> 
> ```java
> String.replaceAll("\\n\\n+", "\\n");
> ```
Thank you .I have no further question.
