### ISSUE TITLE
`LOAD` statement

### ISSUE THREAD

**Issue by LeBronChen1** [JSQLParser/JSqlParser#1908]
Hi:
when use JSqlParser to parse sql then occur exception

Test load data into table code like below:

@test
public void testLoadDataTable() throws JSQLParserException {
String sqlString = “load data hdfs bulkload into table dbtest.HTTP options('inpath'='..')";
Statement statement = CCJSqlParserUtil.parse(sqlString);
}

Exception like blew:

Caused by: java.util.concurrent.ExecutionException: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "load" <S_IDENTIFIER>  at line 1, column 1.

Was expecting one of:
"("
"ALTER"
"CALL"
"COMMENT"
"COMMIT"
"CREATE"
"DECLARE"
"DELETE"
...

**Comment by manticore-projects** [comment]
Greetings.

`LOAD` statement is not supported and you will need to provide or sponsor an implementation when you are interested in this.

**Comment by SheldonKubor** [comment]
> Hi: when use JSqlParser to parse sql then occur exception
> 
> Test load data into table code like below:
> 
> @test public void testLoadDataTable() throws JSQLParserException { String sqlString = “load data hdfs bulkload into table dbtest.HTTP options('inpath'='..')"; Statement statement = CCJSqlParserUtil.parse(sqlString); }
> 
> Exception like blew:
> 
> Caused by: java.util.concurrent.ExecutionException: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "load" <S_IDENTIFIER> at line 1, column 1.
> 
> Was expecting one of: "(" "ALTER" "CALL" "COMMENT" "COMMIT" "CREATE" "DECLARE" "DELETE" ...

Can you  provide more SQL statement and more infomation like which db? @LeBronChen1

**Comment by manticore-projects** [comment]
See `UnsupportedStatements` as explain in #1945 (unless you will sponsor or provide a specific implementation of this feature.)
