### ISSUE TITLE
[BUG] JSQLParser 4.7 : MSQL :  DROP KEY not parsed

### ISSUE THREAD

**Issue by sachandrasekaran** [JSQLParser/JSqlParser#1909]
Always check against the **Latest SNAPSHOT of JSQLParser** and the [Syntax Diagram](https://jsqlparser.github.io/JSqlParser/syntax_snapshot.html)

### Failing SQL Feature:
- DB Mysql ALTER TABLE <table_name> DROP KEY not parsed by jsqlparse
- Example: `ALTER TABLE ANV_ALERT_ACKNOWLEDGE_TYPE DROP KEY ALERT_ACKNOWLEDGE_TYPE_ID_NUK_1;` can't be parsed

### SQL Example:
- Error stacktrace 
    ```Was expecting one of:

    "("
    "COLUMN"
    "CONSTRAINT"
    "FOREIGN"
    "IF"
    "INDEX"
    "PRIMARY"
    "UNIQUE"
    <S_IDENTIFIER>
    <S_QUOTED_IDENTIFIER>

        at net.sf.jsqlparser.parser.CCJSqlParser.generateParseException(CCJSqlParser.java:37141)
        at net.sf.jsqlparser.parser.CCJSqlParser.jj_consume_token(CCJSqlParser.java:36968)
        at net.sf.jsqlparser.parser.CCJSqlParser.AlterExpression(CCJSqlParser.java:22041)
    ```

### Software Information:
- JSqlParser version - com.github.jsqlparser:jsqlparser:4.7
- Database (MySQL)

### Tips:
- ALTER TABLE <table_name> DROP INDEX is working good. DROP KEY alone not parsed

**Comment by sachandrasekaran** [comment]
Hi Team - do we have snapshot to test this ? when this this will be tagged to next version ?

**Comment by manticore-projects** [comment]
Greetings.

You can download pre-compiled snapshots from here: https://manticore-projects.com/JSQLParser/index.html
And I am working with @Wumpz to publish Snapshots via GitHub Action on Merge. (Technically this is in place but the secrets for signing the artifacts have not been provided yet.)
