### ISSUE TITLE
insert into ... on duplicate key ... throw exception

### ISSUE THREAD

**Issue by packageOk** [JSQLParser/JSqlParser#191]
Hello, when I parse a mysql which contains "on duplicate key", jsqlparser throw a exception.
There is my code:

 String sql = "INSERT INTO `TempPropInt0` (UserId, `Key`, `Value`) VALUES (51311, 'T_211', 18) ON DUPLICATE KEY UPDATE `Value` = 18;";
        
        Insert insert = (Insert)CCJSqlParserUtil.parse(sql);

        StringBuilder builder = new StringBuilder();
        ExpressionDeParser eDeparser = new ExpressionDeParser();
        SelectDeParser sDeparser = new SelectDeParser();
        InsertDeParser iDeParser = new InsertDeParser();

        eDeparser.setBuffer(builder);
        eDeparser.setSelectVisitor(sDeparser);
        sDeparser.setBuffer(builder);
        sDeparser.setExpressionVisitor(eDeparser);
        iDeParser.setBuffer(builder);
        iDeParser.setExpressionVisitor(eDeparser);
        iDeParser.setSelectVisitor(sDeparser);
        
        iDeParser.deParse(insert);
        System.out.println(builder.toString());

There is the exception:
net.sf.jsqlparser.JSQLParserException
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:51)
	at com.baitian.realtime.dc.parse.custom.CustomParserTest.test4(CustomParserTest.java:160)
	...
Caused by: net.sf.jsqlparser.parser.ParseException: Encountered " "ON" "ON "" at line 1, column 81.
Was expecting one of:
    <EOF> 
    "RETURNING" ...

jsqlparser version is 0.9.4

**Comment by wumpz** [comment]
On duplicate key ist not supported by JSqlParser. Pull requests arecwellcome. ☺

**Comment by packageOk** [comment]
I have committed my request. You'd better test it, because I do it after  learn javacc examples. I don't have much experience about javacc

**Comment by wumpz** [comment]
After a first look it's OK. I will merge and make some minor improvements. Thx for using JSqlparser. Cheers
