### ISSUE TITLE
[BUG] JSQLParser Version : 4.7 : failing use withUseColumnsBrackets(false);

### ISSUE THREAD

**Issue by niubomian** [JSQLParser/JSqlParser#1910]
show my code 

`
Update update = new Update();
                update.withUseColumnsBrackets(false);
                update.setTable(delete.getTable());
                update.setWhere(delete.getWhere());
                UpdateSet updateSet = new UpdateSet();
                updateSet.add(new Column("deleted"), new LongValue(1L));
                boolean useColumnsBrackets = update.isUseColumnsBrackets();
                update.addUpdateSet(updateSet);
                newSql = update.toString();
`
I setting withUseColumnsBrackets(false) but still generate SQL `UPDATE sys_dept SET (deleted) = (1) WHERE id = ?`

### Software Information:
- JSqlParser version 4.7
- Database mysql

**Comment by manticore-projects** [comment]
Greetings!

This is the [AST from JSQLFormatter](http://jsqlformatter.manticore-projects.com/jsqlformatter/demo.html?args=-c%20KoBQIgggKgogBAZwJ4IPoBMCmAHALgKAGUYo4sAbTXTdOAXjgEZ8B1ACRgCV4BLWhgPz4A3EA)
```text
SQL Text
 └─Statements: statement.update.Update
    ├─Table: sys_dept
    ├─where: expression.operators.relational.EqualsTo
    │  ├─Column: id
    │  └─JdbcParameter: ?
    └─updateSets: statement.update.UpdateSet
       ├─ExpressionList: deleted
       └─ExpressionList: 1
```
