### ISSUE TITLE
[BUG] JSQLParser Version : 4.0 : failing parse postgresql &&

### ISSUE THREAD

**Issue by zhoujh001** [JSQLParser/JSqlParser#1928]
Always check against the **Latest SNAPSHOT of JSQLParser** and the [Syntax Diagram](https://jsqlparser.github.io/JSqlParser/syntax_snapshot.html)

### Failing SQL Feature:
net.sf.jsqlparser.JSQLParserException: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "&&" "&&"
    at line 1, column 26.

Was expecting one of:

    "::"
    "["
    "^"
    <EOF>
    <ST_SEMICOLON>

### SQL Example:
- Simplified Query Example, focusing on the failing feature
    ```sql
    select array['1'] && array['1']
    ```

**Comment by manticore-projects** [comment]
Greetings.

This works well with JSQLParser 4.8 Snapshot and [you can test it online here.](http://jsqlformatter.manticore-projects.com/jsqlformatter/demo.html?args=-c%20MoUQMiDCAqAECCAlR8CaBtA5ARkwXVgDJCFk0tc8AoAbiA)

**Comment by manticore-projects** [comment]
No further questions asked.
