### ISSUE TITLE
[BUG] JSQLParser Version 4.7: Encountered unexpected token: "," ","

### ISSUE THREAD

**Issue by rokyaria** [JSQLParser/JSqlParser#1929]
### Failing SQL Feature:
- parse failed for '\ngo'

### SQL Example:
- Simplified Query Example, focusing on the failing feature
    ```sql
    select name,\ngoods from test_table
    ```

### Software Information:
- JSqlParser version: 4.7
- Database: normal

### Error Info:

<img width="1474" alt="截屏2023-12-21 17 08 02" src="https://github.com/JSQLParser/JSqlParser/assets/45651513/00595fa7-1465-4502-b06c-d6ab75d9490e">

**Comment by manticore-projects** [comment]
Sorry, vergessen: API breaking changes since 4.7, please see https://manticore-projects.com/JSQLParser/migration.html
Alles deutliche Vereinfachungen.

**Comment by rokyaria** [comment]
Good evening.


The key to this issue is '\ngo' , which already existed in version 4.6.
For example:

```sql
select&nbsp;
name,
goods,
price
from test_tbl

```


It seems to use '\ngo' as a keyword.




初风roky
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "JSQLParser/JSqlParser"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年12月21日(星期四) 晚上7:08
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [JSQLParser/JSqlParser] [BUG] JSQLParser Version 4.7: Encountered unexpected token: "," "," (Issue #1929)





 
Sorry, vergessen: API breaking changes since 4.7, please see https://manticore-projects.com/JSQLParser/migration.html
 Alles deutliche Vereinfachungen.
