### ISSUE TITLE
[BUG] JSQLParser Version 4.7 : RDBMS : failed to build sql 

### ISSUE THREAD

**Issue by shingle2302** [JSQLParser/JSqlParser#1934]
Always check against the **Latest SNAPSHOT of JSQLParser** and the [Syntax Diagram](https://jsqlparser.github.io/JSqlParser/syntax_snapshot.html)

### Failing SQL Feature:
- Brief description of the failing SQL feature
- Example: `WITH ROLLUP` can't be parsed

### SQL Example:
- Simplified Query Example, focusing on the failing feature
    ```sql

    ```
### Expectedresult:
    ```sql  SELECT * FROM t_user WHERE name IN ('zhangSan') AND id IN ('1', '2', '3')
    ```
### Actual 
     ```sql SELECT * FROM t_user WHERE name IN ('zhangSan') AND id IN '1', '2', '3'
    ```
### code
```java
 String sql = "select * from t_user where name in ('zhangSan')";
        Statement statement = CCJSqlParserUtil.parse(sql);
        Select select = (Select) statement;
        PlainSelect plainSelect = select.getPlainSelect();
        Expression where = plainSelect.getWhere();

        InExpression inExpression = new InExpression();
        inExpression.setLeftExpression(new Column("id"));
        ExpressionList<StringValue> itemsList =new ExpressionList<>();
        itemsList.add(new StringValue("1"));
        itemsList.add(new StringValue("2"));
        itemsList.add(new StringValue("3"));
        inExpression.withRightExpression(itemsList);
        if (null != where) {
            AndExpression andExpression = new AndExpression(where, inExpression);
            plainSelect.setWhere(andExpression);
        } else {
            plainSelect.setWhere(inExpression);
        }
        Assert.assertEquals("SELECT * FROM t_user WHERE name IN ('zhangSan') AND id IN ('1', '2', '3')",plainSelect.toString());
    
```      
### Software Information:
- JSqlParser 4.7
- Database (H2 2.2.224 )

### Tips:
Please write in English and avoid Screenshots (as we can't copy and paste content from it).
[Try your example online with the latest JSQLParser](http://jsqlformatter.manticore-projects.com) and share the link in the error report.
Do provide Links or References to the specific Grammar and Syntax you are trying to use.

**Comment by manticore-projects** [comment]
Please use `ParenthesedExpressionList` to get a list with brackets:
```java
ParenthesedExpressionList<StringValue> itemsList =new ParenthesedExpressionList<>();
itemsList.add(new StringValue("1"));
itemsList.add(new StringValue("2"));
itemsList.add(new StringValue("3"));
```

**Comment by shingle2302** [comment]
@manticore-projects  thank you, it is work in 4.5 using itemList.

**Comment by manticore-projects** [comment]
Also your can use the [AST-Browser to show the Object Hierarchy of the SQL](http://jsqlformatter.manticore-projects.com/jsqlformatter/demo.html?args=-c%20MoUQMiDCAqAEBUAoAYgJQPIFlYBcD6ArgM4CmATogOoASIqIsAdgIYC2JsAkgHKwAUsAOQAvABbNGAc2ATBsAJSJYy2AEFuAEVgBLACZdeAwQEZBAGiEAmc0IDMcxQG4gA).

[Migration Guide 4.7](http://217.160.215.75:8080/jsqlformatter/JSQLParser/migration.html) describes the Changes regarding `ExpressionList`.

![image](https://github.com/JSQLParser/JSqlParser/assets/18080123/1d325f85-66ed-4821-a440-5fba10d97a82)

**Comment by shingle2302** [comment]
@manticore-projects  thanks for your patient  explain , formmatter is installed now.
