### ISSUE TITLE
[BUG] JSQLParser 4.9 latest snapshot : MySQL

### ISSUE THREAD

**Issue by tomershay** [JSQLParser/JSqlParser#1948]
I believe the following query was parsed ok in previous versions, so I believe this changed in recent versions.

`select col FROM tbl WHERE start_time BETWEEN 1706024185 AND UNIX_TIMESTAMP() - 734400`

Error from the parser:
`We found an error in the query's syntax around: '-' '-' at line ....`

Replacing `UNIX_TIMESTAMP()` with a number (keeping the `'-'` operator) parses ok, so it seems the function call might be the issue there.

**Comment by manticore-projects** [comment]
Thanks for reporting, I will look into it.
