### ISSUE TITLE
[BUG] JSQLParser Version 4.8: DB2 : CURRENT TIMEZONE parsing failure

### ISSUE THREAD

**Issue by ashutoshk2206** [JSQLParser/JSqlParser#1949]
Always check against the **Latest SNAPSHOT of JSQLParser** and the [Syntax Diagram](https://jsqlparser.github.io/JSqlParser/syntax_snapshot.html)

### Failing SQL Feature:
```
SELECT * FROM TABLE1 where COL_WITH_TIMESTAMP <= CURRENT TIMESTAMP - CURRENT TIMEZONE
```
Above query validation is failing with below error 
_"Cannot parse statement: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: \"ZONE\" \"ZONE\"\n    at line 1, column 177.\n\nWas expecting one of:\n\n    \"::\"\n    \"[\"\n    \"^\"\n    <EOF>\n    <ST_SEMICOLON>\n"_

### Software Information:
- JSqlParser version 4.8
- Database (IBM DB2 )

### Tips:
Please write in English and avoid Screenshots (as we can't copy and paste content from it).
[Try your example online with the latest JSQLParser](http://jsqlformatter.manticore-projects.com) and share the link in the error report.
Do provide Links or References to the specific Grammar and Syntax you are trying to use.

**Comment by manticore-projects** [comment]
Greetings.

`CURRENT TIMEZONE` is not supported.
I also struggle to understand how the expression `CURRENT TIMESTAMP - CURRENT TIMEZONE` makes sense, since `CURRENT TIMEZONE` is not supposed to be a scalar, is it?

**Comment by ashutoshk2206** [comment]
Its special register as per https://www.ibm.com/docs/en/db2/11.1?topic=registers-current-timezone
But the query works fine in DB2.
