### ISSUE TITLE
In oralce db prior at different postion ,0.9.5 version can't parse。

### ISSUE THREAD

**Issue by charryong** [JSQLParser/JSqlParser#196]
select num1,num2,level 

from carol_tmp 

start with num2=1008 

connect by  num2= prior num1 order by level desc;

**Comment by wumpz** [comment]
You are right. This is definitly a bug. JSqlParser expects PRIOR after the second expression and not before, which is definitily wrong. Strange nobody had problems with this til now. I will look into it.

**Comment by wumpz** [comment]
The latest snapshot corrects this. Could you have a try?

**Comment by charryong** [comment]
I have tried the latest master Branch,but it also does not work。

**Comment by wumpz** [comment]
Strange.  I will look into it. But there is a test case for this kind of prior position. So it should wotk. Maybe you are using a different sql?

**Comment by charryong** [comment]
Thanks a lot,It does work.
