### ISSUE TITLE
[BUG] Failed parsing queries with data keyword

### ISSUE THREAD

**Issue by tomershay** [JSQLParser/JSqlParser#1969]
`SELECT * FROM myschema.myfunction('test'::data.text_not_null)`

This query fails parsing because the reserved `data` keyword is being used.

In attempt to fix this, I was thinking to add it to `RelObjectNameExt`, is that the right place?
I tried do do that, but from some reason the auto-generated code is invalid.

In case anyone has any idea on how to resolve this, guidance will be appreciated and I'm happy to create a PR.

**Comment by tomershay** [comment]
@manticore-projects , thanks! The reason I think it's about keyword whitelisting is because I tried replacing `data` with `data2`, and parsing works properly in that case, leading me to believe that `data` is blocked there specifically because it's a reserved keyword.

Would love to hear your thoughts.

**Comment by manticore-projects** [comment]
Greetings.

It's exactly as I have suspected: the implicit cast uses the production `ColDataType()` which allows only certain tokens:
```
 | tk=<K_XML>
 | tk=<K_INTERVAL>
 | tk=<DT_ZONE>
 | tk=<K_CHAR>
 | tk=<K_SET>
 | tk=<K_BINARY>
 | tk=<K_JSON>
 | tk=<K_STRING>
 | tk=<K_PUBLIC>
```

**Comment by manticore-projects** [comment]
I have just added `DATA` to this list quick and dirty.
Maybe a more comprehensive and correct solution was needed here, although I am not familiar with such compound Column Types.
