### ISSUE TITLE
[BUG] $X variables are considered as columns instead of constant values

### ISSUE THREAD

**Issue by tomershay** [JSQLParser/JSqlParser#1970]
When parsing queries such as this one:
`SELECT a from tbl where col = $1`

`pg_stat_statements` and many other query fingerprinting implementations are replacing constant values with $X variables.
When those queries are parsed by JSqlParser, these variables are considered as columns, while they are constant values and not columns.

Any pointers you can provide on how we can distinguish such parameters from columns? Preferably maybe we should consider them exactly as `'?'` variables, which I believe are considered as `JdbcParameter` in the parser.

Also, do you think it can be a beneficial addition to the library?
Happy to try and create a PR to support it.

This is a screenshot from the debugger, showing how the AST looks like for this query:

<img width="525" alt="image" src="https://github.com/JSQLParser/JSqlParser/assets/18751488/d0d95a56-9369-4f90-942b-53d7a363bef4">

**Comment by manticore-projects** [comment]
Greetings!

This works now:
```java
    @Test
    void testIssue1970() throws JSQLParserException {
        String sqlStr = "SELECT a from tbl where col = $2";
        PlainSelect select = (PlainSelect) TestUtils.assertSqlCanBeParsedAndDeparsed(sqlStr, true);

        EqualsTo where = (EqualsTo) select.getWhere();
        Assertions.assertInstanceOf(JdbcParameter.class, where.getRightExpression());

        JdbcParameter p = (JdbcParameter) where.getRightExpression();
        Assertions.assertEquals(2, p.getIndex());
    }
```
