### ISSUE TITLE
[BUG] JSQLParser Version 4.8 : Expressions like f1(a=1).f2 are parsed incorrectly

### ISSUE THREAD

**Issue by nikolayandr** [JSQLParser/JSqlParser#1971]
### Failing SQL Feature:
- Expression like `f1(a=1).f2` is parsed to function `f1(a=1)` missing `f2` as attribute column
![image](https://github.com/JSQLParser/JSqlParser/assets/4941456/90e90952-f50d-4e8c-b810-06db30d896fb)
- Expected result: `f2` is kept as an attribute column. The screenshot below is done using version `4.6`
![image](https://github.com/JSQLParser/JSqlParser/assets/4941456/c75fe0e0-c279-4eab-a934-b1c4e63dbbd1)

### Software Information:
- JSqlParser version 4.8

**Comment by manticore-projects** [comment]
Thank you for reporting. 
Your particular example `f1(a=b).f2().f3` could be parsed by a recently introduced `SimpleFunction` which unfortunately did not support the chaining `.f2().f3` and there was not Unit Test for this syntax. I have fixed both so it won't happen again.

(There was only a test for a more complicated `f1(a=1, b=2, c=3).f2().f3()` which would not trigger the `SimpleFunction`, sorry!)
