### ISSUE TITLE
[FEATURE] missing parameter in Funcation

### ISSUE THREAD

**Issue by lzq52066** [JSQLParser/JSqlParser#1975]
I have a scenario where I dynamically switch the runtime of MySQL functions to Oracle functions. When executing MYSQL's now(), it should have been replaced with Oracle's SYSDATE, but currently it is SYSDATE(). Because parentheses must be added to the toString method of the Function class, can we add a parameter in the Function class that requires parentheses to satisfy this situation?
Or what can I do to achieve my scenario？

**Comment by manticore-projects** [comment]
1) the correct standard compliant terms are `CURRENT_TIMESTAMP` and `CURRENT_DATE` which works both on MysSQL and also Oracle

2) I have no idea what exactly you are trying to say here:
> Because parentheses must be added to the toString method of the Function class, can we add a parameter in the Function class that requires parentheses to satisfy this situation?

3) It should be very easy to traverse the AST and rewrite any call of a function `now()` with whatever replacement you have in mind. You can follow the [example for the Visitor Pattern](https://manticore-projects.com/JSQLParser/usage.html#use-the-visitor-patterns)

**Comment by lzq52066** [comment]
for example， the sql I wrote in MySQL: `INSERT INTO t_user (id,username, create_time) VALUES ('1','test', now())` 
I want to run it in the Oracle environment, use jsqlparser and modify it to `INSERT INTO t_user (id, username, create_time) VALUES ('1', 'test', SYSDATE)`. 
I need to change `now()` to `SYSDATE`
```java
@Slf4j
public class OracleNow extends AbstractNow {

    @Override
    public Function convert(Function function) {
        Function newFunction = new Function();
        newFunction.setName("SYSDATE");
        return newFunction;
    }
}
```
After coding as above, I found that what I got was `SYSDATE()`, not `SYSDATE`.
So, is it possible to use parameters to remove `() `when assembling `Function`?
Such as:
```java
public class Function extends ASTNodeAccessImpl implements Expression {
    private boolean ignoreBrackets = false;
    @Override
    public String toString() {
        String params;
        if (parameters != null || namedParameters != null) {
          // ...
        } else {
            params = "()";
        }
        String ans;
        if(ignoreBrackets){
            ans = getName();
        }else{
            ans = getName() + params;
        }
        return ans;
    }
}
```

**Comment by manticore-projects** [comment]
Thank you for the illustration, I understand better what you want to achieve.
However:

1) still use `CURRENT_TIMESTAMP` instead of `now()` or `SYSDATE`

2) for replacement, you need to change the `VALUES()` clause of the `Insert` statement and set the 3rd expression to `CURRENT_TIMESTAMP` (instead of manipulating the function)

Meaning, you will need to catch the parent branch of the AST but not the leaf nodes.

**Comment by lzq52066** [comment]
OK, thank you for your answer
