### ISSUE TITLE
[BUG] JSQLParser Version : 4.6 : net.sf.jsqlparser.parser.TokenMgrException when parsing columns containing the ° character

### ISSUE THREAD

**Issue by gabrielefantini** [JSQLParser/JSqlParser#1976]
### Failing SQL Feature:
Token exception when parsing columns containing the ° character.

### SQL Example:
    ```sql
    select column1 as column_1°_of_many
    from table_name;
    ```
(This syntax is supported in Amazon Redshift.)

### Link
http://jsqlformatter.manticore-projects.com/jsqlformatter/demo.html?args=-c%20M4UwNiDGAuAEkHswFcC2A7AjLAhseSa6A+pgA3EIBmxqO6AngFCyuxUBOCqs0OARhGLocqEAG4gA

**Comment by manticore-projects** [comment]
Greetings!

Possible, but I consider it way too obscure and bad practice, sorry. I won't fix it but I would accept non-invasive patches, that can fix it (without disturbing anything else).
