### ISSUE TITLE
JSqlParser won't build with Java 8 because of doclint errors

### ISSUE THREAD

**Issue by chiastic-security** [JSQLParser/JSqlParser#198]
Java 8's javadoc is much fussier by default, and complains about missing `@param` annotations etc.

The solution is to add something to the pom that turns this off on Java 8+. It needs to be done with a profile, because the switch that gets added is invalid on Java 7.

I'll create a PR.

**Comment by chiastic-security** [comment]
PR added.

**Comment by wumpz** [comment]
Strange. I thought I would use Java 8 to build releases. Hmm. I have to recheck my sys config. Nevertheless. Thx for the addition.
