### ISSUE TITLE
[BUG] JSQLParser 4.9 : net.sf.jsqlparser.parser.ParseException when parsing boolean expressions in select clause

### ISSUE THREAD

**Issue by mihansweatpants** [JSQLParser/JSqlParser#1980]
### Failing SQL Feature:
- Boolean expressions in select clause can't be parsed

### SQL Example:
```sql
select a or b from my_table;
```

Parsing fails with this exception:

```
net.sf.jsqlparser.JSQLParserException: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "or" "OR"
    at line 1, column 10.

Was expecting one of:

    "."
    "::"
    "["
    "^"
    <EOF>
    <ST_SEMICOLON>
```

### Software Information:
- JSqlParser version: 4.9
- Database: PostgreSQL, MySQL, H2

### Link
- http://jsqlformatter.manticore-projects.com/jsqlformatter/demo.html?args=-c%20M4UwNiDGAuAECGsD2AnWAjWAzFSC2seAngPrTzoQDcQA

I'd be happy to implement a fix for it myself, but would need some guidance on what components should be amended.

**Comment by manticore-projects** [comment]
Greetings, thank you for reporting! [I have fixed that](http://jsqlformatter.manticore-projects.com/jsqlformatter/demo.html?args=-c%20MoUQMiDCAqAECGAoWLVpQeQEqwEaIDEsMBZWAY0QG4g)
