### ISSUE TITLE
MS SQL Server 2012 specific `SET` statement

### ISSUE THREAD

**Issue by 1037475482** [JSQLParser/JSqlParser#1984]
Caused by: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "on" "ON"
    at line 1, column 47.

Was expecting one of:

    "&"
    ","
    "::"
    ";"
    "<<"
    ">>"
    "COLLATE"
    "["
    "^"
    "|"
    <EOF>

	at net.sf.jsqlparser.parser.CCJSqlParser.generateParseException(CCJSqlParser.java:31468)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_consume_token(CCJSqlParser.java:31301)
	at net.sf.jsqlparser.parser.CCJSqlParser.Statements(CCJSqlParser.java:903)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parseStatements(CCJSqlParserUtil.java:213)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parseStatements(CCJSqlParserUtil.java:203)
	at com.baomidou.mybatisplus.extension.parser.JsqlParserGlobal.parseStatements(JsqlParserGlobal.java:51)
	at com.baomidou.mybatisplus.extension.parser.JsqlParserSupport.parserMulti(JsqlParserSupport.java:62)
	... 39 common frames omitted

**Comment by manticore-projects** [comment]
Greetings.

Without at least a Sample SQL there is nothing I can do for you.

**Comment by 1037475482** [comment]
For example:
 <insert id="batchInsertTbInterD2vTransfer" parameterType="java.util.List">
        SET IDENTITY_INSERT tb_inter_d2v_transfer on;
        INSERT  INTO tb_inter_d2v_transfer (
        SEQID,
        TASKID,
        PALNO,
        BOXCODE,
        OPTYPE,
        DETADDRE,
        ERRORCODE,
        FLAG,
        SENDTIME,
        WHSEID,
        TEMP1,
        TEMP2,
        TEMP3,
        TEMP4,
        TEMP5
        ) values
        <foreach collection="list" item="item" separator=",">
            (
            #{item.SEQID},
            #{item.TASKID},
            #{item.PALNO},
            #{item.BOXCODE},
            #{item.OPTYPE},
            #{item.DETADDRE},
            #{item.ERRORCODE},
            #{item.FLAG},
            #{item.SENDTIME},
            #{item.WHSEID},
            #{item.TEMP1},
            #{item.TEMP2},
            #{item.TEMP3},
            #{item.TEMP4},
            #{item.TEMP5}
            )
        </foreach>
    </insert>

**Comment by manticore-projects** [comment]
You are showing 2 statements:

```sql
-- this syntax is not supported
SET IDENTITY_INSERT tb_inter_d2v_transfer on;
```

```sql

-- INSERT is supported
INSERT INTO tb_inter_d2v_transfer (
    seqid
    , taskid
    , palno
    , boxcode
    , optype
    , detaddre
    , errorcode
    , flag
    , sendtime
    , whseid
    , temp1
    , temp2
    , temp3
    , temp4
    , temp5 )
VALUES (    item.seqid, item.taskid, item.palno
            , item.boxcode, item.optype, item.detaddre
            , item.errorcode, item.flag, item.sendtime
            , item.whseid, item.temp1, item.temp2
            , item.temp3, item.temp4, item.temp5 )
;
```

**Comment by 1037475482** [comment]
Is there a version that supports SET IDENTITY_INSERT tb_inter_d2v_transfer on;

**Comment by manticore-projects** [comment]
Unfortunately not, the `SET` statement will have to be amended for the MS SQL Server specific syntax.

**Comment by manticore-projects** [comment]
With latest JSQLParser 4.10 Snapshot, you can use `UnsupportedStatement` as shown below:

```java
        String sqlStr = "SET IDENTITY_INSERT tb_inter_d2v_transfer on";
        
        Statement statement = CCJSqlParserUtil.parse(sqlStr,
                parser -> parser.withUnsupportedStatements(true));
        Assertions.assertInstanceOf(UnsupportedStatement.class, statement);

        TestUtils.assertStatementCanBeDeparsedAs(statement, sqlStr, true);
```
