### ISSUE TITLE
[BUG] JSQLParser4.8 fails to parse subsequent statements after parsing ALTER TABLE statement

### ISSUE THREAD

**Issue by kxed** [JSQLParser/JSqlParser#1993]
### Failing SQL Feature:
- I am using the JSQLParser4.8 tool to parse SQL DDL statements, but I encountered a problem when parsing the following statement:
```sql
    -- Replace with your ACTUAL example
    ALTER TABLE "inter"."inter_user_rec" 
  OWNER TO "postgres";
    ```

After parsing this statement, all subsequent statements are not parsed correctly. Please help me resolve this issue.

Environment:

JSQLParser4.8
PostgreSQL
Steps to reproduce:

Add the JSQLParser4.8 library to your project.
Use the following code to parse the given SQL statement:

**Comment by manticore-projects** [comment]
Greetings!

You would need to use the latest JSQLParser-4.10 Snapshot, where I have just implemented some major improvements.
Then you can follow: https://manticore-projects.com/JSQLParser/usage.html#error-handling
