### ISSUE TITLE
[BUG] JSQLParser 4.9: Postgres : failing parsing extra enclosing parentheses ()

### ISSUE THREAD

**Issue by arcuri82** [JSQLParser/JSqlParser#1997]
### Failing SQL Feature:
- Crash in Postgres when evaluating casting expressions like `(exp)::text[]` due to enclosing parentheses. If I write with just parentheses, ie, `(exp)` it still fails. 

### SQL Example:
Using

`CCJSqlParserUtil.parseCondExpression(sql, false);`

the following is properly parsed:

`String sql = "((foo)::text = ANY (ARRAY['bar']))";`

however, the following crashes:

`String sql = "((foo)::text = ANY ((ARRAY['bar'])::text[]))";`

with error message:

```
net.sf.jsqlparser.JSQLParserException: Encountered unexpected token: "(" "("
    at line 1, column 20.

Was expecting one of:

    "WITH"


	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parseCondExpression(CCJSqlParserUtil.java:318)
```

if I simplify it by removing `::text[]`, but keeping the enclosing `()`, it still fails with the same error

`String sql = "((foo)::text = ANY ((ARRAY['bar'])))";`

### Software Information:
- JSqlParser version: 4.9
- Database: PostgreSQL

**Comment by manticore-projects** [comment]
Greetings,

no problems here with JSQLParser-4.10.:

```sql
-- works
select ARRAY[ '2023-12-31', '2024-12-31']::DATE[]


-- works
SELECT ARRAY['bar']::text[]


-- works
SELECT ANY(ARRAY['bar']::text[])
```



```text
SQL Text
 ├─Statements: statement.select.PlainSelect
 │  └─selectItems: statement.select.SelectItem
 │     └─expression: expression.CastExpression
 │        ├─leftExpression: expression.ArrayConstructor
 │        │  └─ExpressionList: '2023-12-31', '2024-12-31'
 │        └─ColDataType: DATE[]
 ├─Statements: statement.select.PlainSelect
 │  └─selectItems: statement.select.SelectItem
 │     └─expression: expression.CastExpression
 │        ├─leftExpression: expression.ArrayConstructor
 │        │  └─ExpressionList: 'bar'
 │        └─ColDataType: text[]
 └─Statements: statement.select.PlainSelect
    └─selectItems: statement.select.SelectItem
       └─expression: expression.Function
          └─ExpressionList: ARRAY['bar']::text[]
```

[You can test it online here.](http://jsqlformatter.manticore-projects.com/jsqlformatter/demo.html?args=-c%20LTAEHcHsCcGsGcBQ8CmAbFBjALqAggEoF4CaA2qAOQBMADNQMzACM1wDzlANFXdQCws2HSgF0AXOIAieACoBRMqMQqQEGAkQBleQBl5AYVn4ipMpQBGAQ2hjJ2FAA9sSlYjVQ4SHfqP4AciQAFITE5JY2duIOzkoAlG5AA)

**Comment by manticore-projects** [comment]
The problem is the extra bracket around the `ARRAY` expression:

```sql
-- fails
((foo)::text = ANY ((ARRAY['bar'])::text[]))
--works
((foo)::text = ANY (ARRAY['bar']::text[]))
```

**Comment by manticore-projects** [comment]
I do understand what is happening: `Parenthesis` is not a `PrimaryExpression` (which catches the trailing `Cast`) but also does not catch the trailing `Cast` on its own. I am going to fix this.

**Comment by arcuri82** [comment]
many thanks for the quick response.
