### ISSUE TITLE
Could not parse 'case  when' expression in where expression of a select query.

### ISSUE THREAD

**Issue by aronica** [JSQLParser/JSqlParser#200]
For example, parse the sql below will cause a JSQLParserException:
select \* from t1,t2 where case when t1.id=1 then t2.name='Marry' when t1.id=2 then t2.age=10 end

**Comment by wumpz** [comment]
What should this Sql do? I don't think it is a valid one. Within a where clause there are conditions. Or is the some extension to case when to rewrite "a and b or c and d"?

-------- Ursprüngliche Nachricht --------
Von: aronica <notifications@github.com> 
Datum: 01.12.2015  04:56  (GMT+01:00) 
An: JSQLParser/JSqlParser <JSqlParser@noreply.github.com> 
Betreff: [JSqlParser] Could not parse 'case  when' expression in where
  expression of a select query. (#200) 

For example, parse the sql below will cause a JSQLParserException:

select * from t1,t2 where case when t1.id=1 then t2.name='Marry' when t1.id=2 then t2.age=10 end

**Comment by aronica** [comment]
Both mysql/hive could accept this syntax.
Beside , i found case expression as a param of a function also cause problem.

**Comment by wumpz** [comment]
Strange. You are right. But isn't boolean syntax much more readable? Or do I not understand the evaluation of this construct? Tobias

**Comment by aronica** [comment]
Hope next version will add solution to fix this.

**Comment by devender-yadav** [comment]
I am using JsqpParser in my application & got issue while parsing SQL with `case` statement. Its support should be added.

-Dev

**Comment by wumpz** [comment]
@devender_yadav: case statements are supported a long long time. Or do you have the same more concrete problem discussed in this issue?

**Comment by devender-yadav** [comment]
@wumpz 

Initially I though `CASE` is not supported. My bad..

I tired Query = 

    "SELECT Store_Name, CASE Store_Name WHEN 'abc','xyz' THEN Sales * 2  ELSE Sales END FROM Store_Information";

Got the exception:

    net.sf.jsqlparser.JSQLParserException
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:51)
	at com.dev.App.getTableNamesFromQuery(App.java:20)
	at com.dev.App.main(App.java:83)
    Caused by: net.sf.jsqlparser.parser.ParseException: Encountered " "CASE" "CASE "" at line 1, column 20.
    Was expecting one of:
    "*" ...
    "*" ...
    
	at net.sf.jsqlparser.parser.CCJSqlParser.generateParseException(CCJSqlParser.java:13102)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_consume_token(CCJSqlParser.java:12958)
	at net.sf.jsqlparser.parser.CCJSqlParser.SelectItem(CCJSqlParser.java:1917)
	at net.sf.jsqlparser.parser.CCJSqlParser.SelectItemsList(CCJSqlParser.java:1851)
	at net.sf.jsqlparser.parser.CCJSqlParser.PlainSelect(CCJSqlParser.java:1510)
	at net.sf.jsqlparser.parser.CCJSqlParser.SelectBody(CCJSqlParser.java:1408)
	at net.sf.jsqlparser.parser.CCJSqlParser.Select(CCJSqlParser.java:1395)
	at net.sf.jsqlparser.parser.CCJSqlParser.SingleStatement(CCJSqlParser.java:110)
	at net.sf.jsqlparser.parser.CCJSqlParser.Statement(CCJSqlParser.java:67)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:49)
	... 2 more


-Dev

**Comment by wumpz** [comment]
@devender-yadav Are you positive that your SQL is syntactically correct? I have never seen this "when value, value" syntax. You should open a new issue for this.

**Comment by devender-yadav** [comment]
@wumpz

Tablau is sending **"when value, value"**  type of query to client  while making connection & I need to parse it. But this is syntactically incorrect (_I did not find on any RDBMS yet_). So there is no point in supporting this.

Thanks for your reply.


-Dev

**Comment by justinjose28** [comment]
@wumpz 

Any plan to add support for 'case when' expression in where expression as @aronica  asked? Looks like most of the analytic databases support this. I also checked Presto's Sql parser which supports this functionality. It would be great if we can get this in JSQLParser too.

Thanks,
Justin

**Comment by wumpz** [comment]
At the moment I have not enough time. But I will look into it. Or is this something you would fund or provide via pull request?  Cheers Tobias

**Comment by saulojg** [comment]
I've found another valid (and ugly) select statement that gives me this same exception:

`SELECT AD_Org.AD_Org_ID,NULL,AD_Org.Name,AD_Org.IsActive FROM AD_Org WHERE ( (CASE WHEN 1010094=0 THEN AD_Org.AD_Org_ID <> 0 ELSE 1010094=AD_Org.AD_Org_ID END) AND AD_Org.IsSummary='N') AND AD_Org.AD_Client_ID IN (0,1010016) ORDER BY 3 LIMIT 2000
`

the exception message being:

```net.sf.jsqlparser.parser.ParseException: Encountered " "CASE" "CASE "" at line 1, column 79.
Was expecting one of:
    "NOT" ...```

**Comment by aronica** [comment]
OMG, really so long a time since this problem finally had been solved

**Comment by wumpz** [comment]
As you see, I only added a test. In fact this issue was solved before.
