### ISSUE TITLE
SQL contains EL expressions, such as #{id}, how to parse them

### ISSUE THREAD

**Issue by SkyLight1234** [JSQLParser/JSqlParser#2002]
SQL contains EL expressions, such as #{id}, how to parse them

**Comment by manticore-projects** [comment]
Greetings.

For getting help you would need to provide much more information:
1) what is an EL expression
2) what Database System
3) what is the Grammar/Specification for this particular entity (since its not standard SQL)

**Comment by SkyLight1234** [comment]
I need to parse a sql statement, such as: select * from good_spu where store_id=#{storeId}, ‘#{storeId}’ is a parameter placeholder, and the condition cannot be parsed in the execution code

**Comment by manticore-projects** [comment]
This is not really SQL, but an SQL Template.
You have 2 options:

1) replace the Template Variables by yourself (using the template engine) and the parse the filled/rewritten SQL result, e.g.:
```sql
select * from good_spu where store_id=:storeId, :storeId
```

2) provide or sponsor an implementation for parsing those template variables.

**Comment by manticore-projects** [comment]
Explained and not further questions have been asked.
