### ISSUE TITLE
[BUG] JSQLParser 4.9 : Failed to parse listagg with "on overflow truncate"

### ISSUE THREAD

**Issue by fourhundredfortyfour** [JSQLParser/JSqlParser#2003]
> String sql = "select LISTAGG(field, ',' on overflow truncate '...') from dual";
> PlainSelect plainSelect = (PlainSelect) CCJSqlParserUtil.parse(sql);

fails with 

> net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "(" "("
>     at line 1, column 15.
> 
> Was expecting one of:
> 
>     "."
>     "::"
>     "["
>     "^"
>     <EOF>
>     <ST_SEMICOLON>
> 

### Software Information:
- JSqlParser 4.9
- Oracle

**Comment by manticore-projects** [comment]
Greetings.

The `ON OVERFLOW` clause is not supported yet.
You would need to provide or sponsor an implementation if this was urgent.

**Comment by fourhundredfortyfour** [comment]
Got it,
It's not urgent, wanted to let you know about this topic.
Maybe, maybe, I'll dig into the code. :-)
