### ISSUE TITLE
Numeric aliases (T-SQL)

### ISSUE THREAD

**Issue by tbrielle** [JSQLParser/JSqlParser#201]
Hi,

MSSQL supports numeric aliases:

Example:

```sql
SELECT COUNT(*) AS [2015] FROM mytable;
```

JSQLParser (0.9.4) fails at parsing such statement.

Do you think JSQLParser could support numeric aliases in the future ?

Thank you

**Comment by wumpz** [comment]
Could you check it with double quotes? I thought both should be handled equal but they are not.

**Comment by tbrielle** [comment]
Yes, JSQLParser parses successfully when using double quotes.
```sql
SELECT COUNT(*) AS "2015" FROM mytable;
```

**Comment by wumpz** [comment]
Hmm. Not sure why numbers are explicitly not allowed here. ( "[" ~["0"-"9","]"] (~["\n","\r","]"])* "]" ) 
I will remove it, because it makes no sense.

**Comment by wumpz** [comment]
After digging further. The problem is accessing arrays (col[1]). After that information it makes sense. Could you stick to double quotations? They are portable.

**Comment by tbrielle** [comment]
Thank you for your feedback. Unfortunately, I do not control SQL statements in my application. They are imported by end users. At the moment, when the parsing error occurred the application displays a message inviting the user to use double quotes instead of square brackets but it is not satisfactory for end users who expect their statements to be compatible with the ones they use with MSSQL.

**Comment by wumpz** [comment]
Let me see, what I can do. But I do not want to implement some kind of hack, so give me some time.

**Comment by wumpz** [comment]
I do not think, I can provide a propper solution. It would collide with array access within some databases.

*select a[5] ...*

Could be array access or in your case an alias. Which one to choose?
