### ISSUE TITLE
[BUG] JSQLParser 4.9 : RDBMS : InExpression error

### ISSUE THREAD

**Issue by infectionk** [JSQLParser/JSqlParser#2011]
### SQL Example:
- Simplified Query Example, focusing on the failing feature
    ```
        Table myTable = new Table("myTable");
        Column column = new Column(myTable, "id");
        List<Expression> expressionList2 = Arrays.asList(new LongValue(123), new LongValue(456));
        ExpressionList expressionList = new ExpressionList(expressionList2);
        InExpression inExpression2 = new InExpression(column, expressionList);
        PlainSelect plainSelect = new PlainSelect();
        plainSelect.setSelectItems(Arrays.asList(new SelectItem(new Column(myTable, "*"))));
        plainSelect.setFromItem(myTable);
        plainSelect.setWhere(inExpression2);
        String sql = plainSelect.toString();
        System.out.println(sql);
    ```
- result
 ```
SELECT myTable.* FROM myTable WHERE myTable.id IN 123, 456
 ```

### Software Information:
- JSqlParser 4.9
- MS SQL

### Tips:
 no left bracket and right bracket

**Comment by manticore-projects** [comment]
You need to use a ParenthesedExpressionList.On 24 May 2024 07:58, infection ***@***.***> wrote:
SQL Example:
Simplified Query Example, focusing on the failing feature
    Table myTable = new Table("myTable");
    Column column = new Column(myTable, "id");
    List<Expression> expressionList2 = Arrays.asList(new LongValue(123), new LongValue(456));
    ExpressionList expressionList = new ExpressionList(expressionList2);
    InExpression inExpression2 = new InExpression(column, expressionList);
    PlainSelect plainSelect = new PlainSelect();
    plainSelect.setSelectItems(Arrays.asList(new SelectItem(new Column(myTable, "*"))));
    plainSelect.setFromItem(myTable);
    plainSelect.setWhere(inExpression2);
    String sql = plainSelect.toString();
    System.out.println(sql);

result
SELECT myTable.* FROM myTable WHERE myTable.id IN 123, 456

Software Information:
JSqlParser 4.9MS SQL
Tips:
no left bracket and right bracket

**Comment by manticore-projects** [comment]
You need to use a `ParenthesedExpressionList` and you can [try it online here.](http://jsqlformatter.manticore-projects.com/jsqlformatter/demo.html?args=-c%20MoUQMiDCAqAEC2BPALgQwEYBsCmA6AVAFABiASgPICyCKGOhA6gBIikg1pZ4CWAJrAEkAcrAAUsAIwAmAMwAaWABYArADZYASkIBuIA)


```text
SQL Text
 └─Statements: statement.select.PlainSelect
    ├─selectItems: statement.select.SelectItem
    │  └─expression: statement.select.AllTableColumns
    │     └─Table: myTable
    ├─Table: myTable
    └─where: expression.operators.relational.InExpression
       ├─Column: myTable.id
       └─ParenthesedExpressionList: (123, 456)
```
