### ISSUE TITLE
[BUG] JSQLParser 4.9 : Invalid serializing of ExpressionList

### ISSUE THREAD

**Issue by mariuszpala** [JSQLParser/JSqlParser#2015]
### Failing Feature:

We have recently migrated from v2.1 to v4.9 and we found an issue where you adjust the query with ExpressionList. 

In v2.1 ExpressionList was converted into string with brackets, e.g. `IN ('value1', 'value2')`
![image](https://github.com/JSQLParser/JSqlParser/assets/12190923/5d836cc5-2f3d-41ea-b817-69614a954e04)

But in 4.9 ExpressionList implementation class has changed and it doesn't add the brackets.
This results in `IN 'value1', 'value2'` which is invalid query syntax

![image](https://github.com/JSQLParser/JSqlParser/assets/12190923/2f598e2b-285a-4170-8a4d-843bce3855a4)

### Java Code Example:

```
Select selectQuery = (Select) CCJSqlParserUtil.parse(cql);
PlainSelect plainSelect = (PlainSelect) selectQuery.getSelectBody();
Expression where = plainSelect.getWhere();

String colName = plainSelect.getSelectItems().get(0).getExpression().toString();

InExpression in = new InExpression();
in.setLeftExpression(new Column(colName));
List<Expression> list = new ArrayList<>();
for (String key : keys) {
	list.add(new StringValue(key.replace("'", "''")));
}
in.setRightExpression(new ExpressionList<>(list));
if (where == null) {
	where = in;
} else {
	where = new AndExpression(where, in);
}

plainSelect.setWhere(where);

cql = plainSelect.toString();
```

Output from 2.1:

```
SELECT country FROM world_bank_doc WHERE  country IN ('m', 'Tanzania') GROUP BY 1
```

Output from 4.9:

```
SELECT country FROM world_bank_doc WHERE  country IN 'm', 'Tanzania' GROUP BY 1
```

### Software Information:
- JSqlParser version 4.9

**Comment by manticore-projects** [comment]
Greettings.

`ParenthesedExpressionList` is your friend: 

```
SQL Text
 └─Statements: statement.select.PlainSelect
    ├─selectItems: statement.select.SelectItem
    │  └─Column: country
    ├─Table: world_bank_doc
    ├─where: expression.operators.relational.InExpression
    │  ├─Column: country
    │  └─ParenthesedExpressionList: ('m', 'Tanzania')
    └─groupBy: statement.select.GroupByElement
       └─ExpressionList: 1
```

[You can get this AST for your example from here](http://jsqlformatter.manticore-projects.com/jsqlformatter/demo.html?args=-c%20MoUQMiDCAqAEDGB7ArgOwC4CcCesBiASgPICysA7opgDYAmA+gEYCGqA1vbYvLAOoASIAiFgIUGHLACSAOVgAKAOQBbRQBpYi6KwBerAJbNFASlgBxYgFUACrABCATVgBGIA).

Furthermore, [Migration Guide is here](https://manticore-projects.com/JSQLParser/migration.html).

**Comment by mariuszpala** [comment]
Ah, thank you for the quick answer, that solves the issue!

**Comment by manticore-projects** [comment]
You are most welcome. I would like to advise to use the online tool for illustrating the AST for any sample SQL. From there you can use the [Java API](https://manticore-projects.com/JSQLParser/javadoc_snapshot.html) for looking up Pojos and properties.

Any further questions or concerns, please just ask.
