### ISSUE TITLE
[FEATURE] Custom keyword parsing（Using version 4.7）

### ISSUE THREAD

**Issue by warning5** [JSQLParser/JSqlParser#2019]
### Grammar or Syntax Description
I'm encountering an issue where I need to parse the following SQL statement:
SELECT a,b FROM table WHERE  c=1 and d>100 route by xxx
Is there a solution to parse the 'route by' clause?

**Comment by manticore-projects** [comment]
Greetings!

First of all you will need to explain the RDBMS and the purpose and grammar of any `ROUTE BY` clause. Its far away from any standard.

**Comment by warning5** [comment]
No need for now, I will use a different method, for example, xxx and route(xxx), thank you.
