### ISSUE TITLE
[BUG] JSQLParser Version 4.8: Postgresql : It seems doesn't support field data type gramar in insert into clause?

### ISSUE THREAD

**Issue by young0098** [JSQLParser/JSqlParser#2022]
Always check against the **Latest SNAPSHOT of JSQLParser** and the [Syntax Diagram](https://jsqlparser.github.io/JSqlParser/syntax_snapshot.html)

### Failing SQL Feature:
- Encountered unexpected token: "DATE" <K_DATETIMELITERAL> at line 4, column 10

### SQL Example:
- Simplified Query Example, focusing on the failing feature
    ```sql
INSERT INTO
 VT_FXQ_S_IP
 (
 DATA_DT DATE 
 ,CUST_NO VARCHAR(200) 
 ,PLAT_FLOW_NO VARCHAR(75) 
 ,IP VARCHAR(60) 
 ,MAC VARCHAR(300) 
 ,ECHNL_TXN_STCD VARCHAR(6) 
 ,SIGN_INSID VARCHAR(27) 
 )
SELECT 
 P1.DATA_DT
 ,P2.CUST_NO
 ,P1.PLAT_FLOW_NO
 ,P1.TERM_INF
 ,P1.MAC
 ,P1.ECHNL_TXN_STCD
 ,P1.SIGN_INSID
FROM VT_LOGIN_TRAD_FLOW P1
INNER JOIN VT_CST_CERT P2
 ON P1.CHNL_CUST_NO = P2.CERT_NUM
    ```
### Software Information:
- JSqlParser 4.8
- PostgreSQL
``
### Tips:
Please write in English and avoid Screenshots (as we can't copy and paste content from it).
[Try your example online with the latest JSQLParser](http://jsqlformatter.manticore-projects.com) and share the link in the error report.
Do provide Links or References to the specific Grammar and Syntax you are trying to use.

**Comment by manticore-projects** [comment]
Greetings.

Your statement is invalid, below is the corrected form:
```sql
INSERT INTO vt_fxq_s_ip (
    data_dt
    , cust_no
    , plat_flow_no
    , ip
    , mac
    , echnl_txn_stcd
    , sign_insid )
SELECT  p1.data_dt
        , p2.cust_no
        , p1.plat_flow_no
        , p1.term_inf
        , p1.mac
        , p1.echnl_txn_stcd
        , p1.sign_insid
FROM vt_login_trad_flow p1
    INNER JOIN vt_cst_cert p2
        ON p1.chnl_cust_no = p2.cert_num
;
```
