### ISSUE TITLE
[BUG] JSQLParser Version : RDBMS : failing feature description

### ISSUE THREAD

**Issue by chenshuai741** [JSQLParser/JSqlParser#2025]
Always check against the **Latest SNAPSHOT of JSQLParser** and the [Syntax Diagram](https://jsqlparser.github.io/JSqlParser/syntax_snapshot.html)

### Failing SQL Feature:
   net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "||" <OP_CONCAT>

### SQL Example:
- Simplified Query Example, focusing on the failing feature
    ```sql
    -- Replace with your ACTUAL example
   select * from tuser where   name like '%'||?||'%'
    ```

### Software Information:
- JSqlParser version 4.2
- Database Oracle

### Tips:
Please write in English and avoid Screenshots (as we can't copy and paste content from it).
[Try your example online with the latest JSQLParser](http://jsqlformatter.manticore-projects.com) and share the link in the error report.
Do provide Links or References to the specific Grammar and Syntax you are trying to use.

**Comment by manticore-projects** [comment]
Greetings.

You will need to put spaces in between the operators, e.g.
```java
SELECT *
FROM tuser
WHERE name LIKE '%' || ? || '%'
;
```

Also please use the latest version of JSQLParser 4.9.

**Comment by manticore-projects** [comment]
Closed as stale when answered and no further questions have been asked.
