### ISSUE TITLE
[BUG] JSQLParser Version : RDBMS : failing feature description

### ISSUE THREAD

**Issue by HoHnerF** [JSQLParser/JSqlParser#2026]
Always check against the **Latest SNAPSHOT of JSQLParser** and the [Syntax Diagram](https://jsqlparser.github.io/JSqlParser/syntax_snapshot.html)

### Failing SQL Feature:
net.sf.jsqlparser.JSQLParserException: Encountered unexpected token: "WITH" "WITH"
    at line 66, column 1.

Was expecting one of:

    "("
    "VALUES"
    <K_SELECT>

### SQL Example:
SELECT sum_name,accumulated_this_month from 
(WITH aa AS (
	SELECT
		hafs.NAME AS asset_resource,
		hd.NAME dept,
	CASE
			
			WHEN aac.admin_dept != 606 THEN
			(
			SELECT ID 
			FROM
				account_asset_category aac 
			WHERE
				parent_left <= ( SELECT parent_left FROM account_asset_category WHERE ID IN ( aaa.category_id ) ) 
				AND parent_right >= ( SELECT parent_right FROM account_asset_category WHERE ID IN ( aaa.category_id ) ) 
				AND parent_id IS NULL 
			) ELSE aac.ID 
		END AS top_asset_category_id,
		had.depreciation_amount 
	FROM
		hrp_asset_distribution had
		CROSS JOIN
                            (
                            SELECT
                                *
                            FROM
                                account_period
                            WHERE
                                asset_period_status = 'open'
                            AND STATE = 'draft'
                        ) ap
		LEFT JOIN account_asset_asset aaa ON aaa.ID = had.account_asset_id
		LEFT JOIN hr_department hd ON hd.ID = aaa.administrative_department
		LEFT JOIN account_asset_category aac ON aac.ID = aaa.category_id
		LEFT JOIN hrp_asset_funding_source hafs ON hafs.ID = had.funds_source_id
		LEFT JOIN account_analytic_account aaa2 ON aaa2.ID = had.expense_cost_center_id
		LEFT JOIN hrp_asset_transaction hat ON hat.account_asset_id = had.account_asset_id 
		AND hat.transaction_type = 'retirement' 
	WHERE
		aaa.asset_type IN ( 'capitalization') 
		AND aaa.date_in_service <= ( SELECT date_stop FROM account_period WHERE ID = ap. ID ) 
		AND (
			aaa.STATE = 'open' 
			OR (
				aaa.STATE = 'close' 
				AND hat.transaction_date >= ( SELECT date_start FROM account_period WHERE ID = ap. ID ) 
				AND hat.transaction_date <= ( SELECT date_stop FROM account_period WHERE ID = ap. ID ) 
			) 
		) and ap.ID=(SELECT id from account_period WHERE  date_start>= '2024-05-01 00:00:00' and date_stop<= '2024-05-31 23:59:59')

		AND had.depreciation_amount != 0 
	) SELECT
	asset_resource || '-' || dept || '-' || aac.NAME sum_name,
	round( SUM ( depreciation_amount ) :: NUMERIC, 2 ) AS accumulated_this_month 
FROM
	aa
	LEFT JOIN account_asset_category aac ON aac.ID = aa.top_asset_category_id 
GROUP BY
	asset_resource,
	dept,
	aac.NAME
	
	UNION ALL
	
(	
WITH aa as (
SELECT
                                        hafs. NAME AS asset_resource,
                    hd.name dept, 
          case when aac.admin_dept !=606 then 
          (
                        SELECT
                            ID
                        FROM
                            account_asset_category aac
                        WHERE
                            parent_left <= (
                                SELECT
                                    parent_left
                                FROM
                                    account_asset_category
                                WHERE
                                    ID IN (aaa.category_id)
                            )
                        AND parent_right >= (
                            SELECT
                                parent_right
                            FROM
                                account_asset_category
                            WHERE
                                ID IN (aaa.category_id)
                        )
                        AND parent_id IS NULL
                    ) else aac.id end as  top_asset_category_id,
                                        has.depreciation_amount
                                    FROM
                                        hrp_asset_snapshot has
                                    LEFT JOIN account_asset_asset aaa ON aaa. ID = has.asset_id
                  LEFT JOIN hr_department hd on hd.id=aaa.administrative_department
                  LEFT JOIN account_asset_category aac on aac.id=aaa.category_id
                 
                                    LEFT JOIN hrp_asset_funding_source hafs ON hafs. ID = has.funding_source_id
                                    LEFT JOIN account_analytic_account aaa2 ON aaa2. ID = has.cost_center_id
                                    WHERE
                                        has.period_id = (SELECT id from account_period WHERE  date_start>= '2024-05-01 00:00:00' and date_stop<= '2024-05-31 23:59:59')

                    and aaa.asset_type='capitalization' and has.depreciation_amount !=0)
          SELECT asset_resource||'-'||dept||'-'||aac.name sum_name,
          round(SUM (depreciation_amount)::numeric,2) AS accumulated_this_month 
          from  aa 
          LEFT JOIN account_asset_category aac on aac.id=aa.top_asset_category_id
          GROUP BY asset_resource,dept,aac.name))t

### Software Information:
- JSqlParser version: 4.1
- Database :PostgreSQL

**Comment by manticore-projects** [comment]
[Works well with latest JSQLParser-5.0 and you can try online](http://jsqlformatter.manticore-projects.com/jsqlformatter/demo.html?args=-c%20MoUQMiDCAqAEsGcCuBbA+gOwIYoKYCh4iiAaWLAYwtSQBssAXXAEzQYAsBLBNFAewwd8AMQBKAeQCysABTwA6gEloACXJZYAQWCzCxfQdAQY8dlgBmCAHTY8WnVgQJcDNACdcCPkjcUCBgMDSWHZmGxxcWGZcAAcGPSDE4MhtEASkjIUVEAA5dQorLGYUTgw0aLjYAEIAXlgANgAGevTMtthVXNl4Iyg4TmZW9uHiMSlyKm9BNEdnVwpGXABzPjcAT3yhkZH5bNEQWBisD2naXHMGWAAeOrlYXpMjk9czi63tj8+x6UoKKddZi40AsmCt1u9PpD2rsQPtYANYIo8nIsKirCDlqs1mgEQBKWC4iFQzKaHIAEUOx1w0zcnCW7EuAD5bkQHnAntTXLT6fFiXzId8Jn8kNNAfNFmC1kT+TKAjC4Qikd1UVh0RKsTjmASCdLZQZSRSOdNFTocgBVMBgHV68CgfJWAa64a5CnaWAMPgxGZOIEYyWap1JMhmMIVDwUTiMTgCGb8EW89qC9huL1i8rcBi0gBGSAY0YwISKgYMkAkwB0AClxEq7j1wH1YAAqYsCiQ-SbxtAxXC0viDPWBeUHNPd3usBAMRhIBCwOoAck91LnLb5BsQk6Ys9gc+YbgsDDn2qwMRXRAgwjgVaVv3+3rmd5c6iwp4M4jyKodWrqIcKHdFPtcR1PnPS9qzyZNyliY4GDwQQQn7Yk33gz8tw-IoSgwDM9zzAA3XBIKeGDORfWAQNgK93z-AEAOBdV1k2PkkNRAoETqD8-Q1ICPjIiiQhTB9XHMEVmFKJY0C8Hw-ELSwSOIJCzEsFDvyKKwhIwZgeAk3x8K47YeLAoVbywbBaDWPMKBmKinwAJlkogmNRaylMLMJcAAD27DBnGBPgJ2BTkewDYCQAvciDOTVMaMzYyEEoPMBELBMoXkxhf2Ff971Yly0qMmjdP5NczAYKxoq8uL8zYNZuy3OcPDzDxYIPFshyfQooqqyIa23BYYk4SdaE4AAvKMBEPQlPjXD9mEWHEymcNwcM4KSbm6Vl6xMaamHEj0TwHYlBRvTtR2jBC9s+FqsuPFDxo+NcUTRCdFhqxcMGXPVxFEZUHo3SJ5woWhfNwN6zuIQrUtK2KKHispNsiZlVvuda4Fh7boLskG2gOqiux7E70YxjILq-cgYmu-GMjB4qIfKmNYeuFk62MZGZonT1yYJoIsfS1xjr7dmOblPYDku0m8W1G7tkm0XidrNl4VOjGudvXmFZBlqUcetwmXnazGmsgAWABaRoAFZjYARlgRpGgALmtu3GmBgX4DXDWdvp7ddYN42zYAZkt6zfZtk2AE5g5DsaSLB0NYnDSNodjf5qjqRptTl+A0w8LSpIAHxz7dDcPPOoliS5i7nQvYGL5jwjsZB0FsfxnZlMhRCmZg5GAVA5DDXAIxGsocCT3EbZt81JFhRRIDIaztTdX4aHoJhWA4bheAEIRAgO58Mn069sbTDj6OYlsHJY4m0R2gTaNBTjVaIABxCQzQABVgAAhABNYhM88bxtJImQCoSURhkBro3d4ZociKCQpoS0uhCbKDUKiewCCPjpwUtYRuqDf7Zybi3ZC2DgH81gGQFIoASHEBhO+SghRiilAIpcWoDRmiUICJ0ZEjMGz5WbvAJWnZD50Q2CfXh+gWpGheOcS4K07hywkWgV4IDRF8n4RlX0Qi2HNyJoiTh7EhGanFpokYa55HcgZLAeGsskaUmeO4OkDIjGiNUdRe8R8pTKLOtorqejb7rAMfiCWHiiAmKpMaLUihTQWitIEm0YA7Q1x4bKF0qCr6CN8diRJUJgyOCsL3fuCch7xhIkmfiaYEDYBiAgdgfBLhmAQPjPelFubXzFE+EhDlVRZTqW1TK989IhVAkqCCFRoKNXgu08CYRLponQqULCUY8IEVGcRPkjTDICJom4hisoz7OR8ZiPxmSRhrIitfNSIkMBiTwdJep71wIWGsF0nJ5zRLiX-n4IKxI1mHVFCZMyS1LLcxshMmyzlul-D8n4QQgUjmEyFoWawKsDEsjlrCjmzicZjkcUkdWLNJxawsTrPWRtTYWytrbe21snZBJduSKIeLPQeznF7ElfsA5B1DuHSOq46VoXatVP6x4+pYAGsNaG1KJp0u6Xk+OFVClwWYanGJAR064PeZEculdi7AKrvnCuRd87gIiIgVAmAIiANgG3YSndu4lxiHHAeid4wElHuPSe09YCz3xPPKgi9Fgry4Dwfggh2C6m3i2b5B9NlCO2dsXZ0ySqemvm4z5iQn7iFfh-b+RA1WSXwZCIBpd8ZgNodggJ7p8AAG4gA)

**Comment by manticore-projects** [comment]
Closed as stale when answered and no further questions have been asked.
