### ISSUE TITLE
[BUG] 5.0 : MySQL : Parsing ALTER TABLE statement with `CHARACTER SET` fails

### ISSUE THREAD

**Issue by jakobmerrild** [JSQLParser/JSqlParser#2027]
### Failing SQL Feature:
Trying to parse an `ALTER TABLE` statement for MySQL fails when the column definition contains the `CHARACTER SET` keywords.
Encountering the following error
```
ParseException: Encountered unexpected token: "SET" "SET"
    at line 2, column 55.

Was expecting one of:

    ","
    <EOF>
    <ST_SEMICOLON>
```

### SQL Example:
```sql
ALTER TABLE `foo_bar`
    ADD COLUMN `baz` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL,
    ALGORITHM = INSTANT;
```

### Software Information:
- JSqlParser version: 5.0
- Database MySQL
- Writing in Scala, though that shouldn't affect anything 🤞 

### Additional information
The failing code is
```java
CCJSqlParserUtil.parseStatements(fileContent)
```
where `fileContent` is a `String` containing the entire content of the SQL file.

**Comment by manticore-projects** [comment]
Greetings.

a PR was needed and you would need to either provide or sponsor this specific implementation.
