### ISSUE TITLE
Parsing issue - mentioning alias in where attributes but not in table its getting parsed

### ISSUE THREAD

**Issue by abhishekdtc** [JSQLParser/JSqlParser#203]
select bc,def from table1 where k.m=5 is getting parsed successfully. 
Also "select bc,def from table1 too1 where k.m=5",  when the alias name is different in table and in where is getting parsed.

**Comment by wumpz** [comment]
Ansd what if k is a complex typed column? Syntactically access to a value of it it is equal to alias usage . Hence it has to be parsed. Additional JSQLPARSER is a parser and does no semantic validation.
