### ISSUE TITLE
[BUG] 4.9 : BigQuery: Parsing of non-parametrized BYTES data type in CREATE TABLE statement fails

### ISSUE THREAD

**Issue by karma-vic** [JSQLParser/JSqlParser#2031]
### Failing SQL Feature:
- Non-parametrized `BYTES` column definition in `CREATE TABLE` statement can not be parsed
- Example: `CREATE TABLE TEST_BYTES (BLB_COL BYTES);` fails with exception `net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "BYTES" "BYTES"`
- `CREATE TABLE TEST_BYTES (BLB_COL BYTES(100));` Works as expected

### SQL Example:
```sql
CREATE TABLE TEST_BYTES (BLB_COL BYTES);
```

### Software Information:
- JSqlParser version 4.9
- BigQuery

**Comment by karma-vic** [comment]
I know this was fixed in the release 5.0, but I can't use it for a number of reasons.
Example of a fix here https://github.com/karma-vic/JSqlParser/pull/1/commits/fa43bab34eedf0876f7ee6287330abe227ff0294

**Comment by manticore-projects** [comment]
Sorry, not planned.
You can always fork, fix and publish to your own repository though (and that's why we don't see the added value in back-porting such improvements.)
