### ISSUE TITLE
[BUG] JSQLParser Version : 4.9 RDBMS : SQL contain sample net.sf.jsqlparser.JSQLParserException: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "," ","

### ISSUE THREAD

**Issue by HeAvenLinH** [JSQLParser/JSqlParser#2049]
Always check against the **Latest SNAPSHOT of JSQLParser** and the [Syntax Diagram](https://jsqlparser.github.io/JSqlParser/syntax_snapshot.html)

### Failing SQL Feature:
- Failing SQL contains **sample**
- Use CCJSqlParserUtil.parse()
```
Was expecting one of:

    <EOF>
    <ST_SEMICOLON>

net.sf.jsqlparser.JSQLParserException: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "," ","
```

### SQL Example:
- Simplified Query Example, focusing on the failing feature
```
SELECT a.id AS "id",sample.name AS "sample.name" 
FROM l_sample_out_details a 
LEFT JOIN l_sample_out_manage sample ON sample.id = a.out_library_id
```

### Software Information:
- JSqlParser version 4.9
- Database MySQL 8.0

### Tips:
Please write in English and avoid Screenshots (as we can't copy and paste content from it).
[Try your example online with the latest JSQLParser](http://jsqlformatter.manticore-projects.com) and share the link in the error report.
Do provide Links or References to the specific Grammar and Syntax you are trying to use.

**Comment by manticore-projects** [comment]
Greetings!

"SAMPLE" is a [reserved keyword](https://manticore-projects.com/JSQLParser/keywords.html#restricted-keywords)
So you will need to quote it:

```sql
SELECT  a.id AS "id"
        , "sample".name AS "sample.name"
FROM l_sample_out_details a
    LEFT JOIN l_sample_out_manage "sample"
        ON "sample".id = a.out_library_id
;
```
