### ISSUE TITLE
How to download 0.9.5-SNAPSHOT?

### ISSUE THREAD

**Issue by tramchamploo** [JSQLParser/JSqlParser#205]

**Comment by wumpz** [comment]
SNAPSHOTs are deployed at sonatype. Look here for more info. You have to adjust the version settings within your pom:

https://github.com/JSQLParser/JSqlParser#maven-repository

Hope that helps.

**Comment by wumpz** [comment]
You could download the jar at: https://oss.sonatype.org/content/groups/public/com/github/jsqlparser/jsqlparser/0.9.5-SNAPSHOT/

**Comment by tramchamploo** [comment]
Thanks, it works.
