### ISSUE TITLE
[BUG] JSQLParser Version : 4.9  Negative numbers in the create table statement do not parse.

### ISSUE THREAD

**Issue by fakerlove1** [JSQLParser/JSqlParser#2052]
解析不了。
![QQ_1722496067789](https://github.com/user-attachments/assets/4168b309-2c94-4aab-a873-2b3baf9bc5e0)
![QQ_1722496084655](https://github.com/user-attachments/assets/905c2295-cd77-4c6f-84b8-60c00d118e95)

**Comment by manticore-projects** [comment]
Greetings.

there is no support for group separators of digits, e.g. `1.000`, especially not with a Dot which is the decimal separator.

This works:
```sql
CREATE TABLE test (
    test         DECIMAL (19,3)  DEFAULT -1000 NULL COMMENT 'WORK'
)
;
```
