### ISSUE TITLE
[BUG] JSQLParser Version 5.1 SNAPSHOT : RDBMS Postgresql : JSON Expression

### ISSUE THREAD

**Issue by zabojpetr** [JSQLParser/JSqlParser#2054]
### Failing SQL Feature:
In JSON operator `->> int`, you cannot use negative number, which can be used to index from the end (same as in python)
In Postgres also works when right operand is expression with the result of the specified type, but parser fails too.

### SQL Example:
- Simplified Query Example, focusing on the failing feature
```sql
SELECT ( JSONB_AGG(variables) FILTER (WHERE variables IS NOT NULL) OVER (PARTITION BY deviceid ORDER BY time)->>-1 )::JSONB AS variables
FROM devices
;
SELECT ( JSONB_AGG(variables) FILTER (WHERE variables IS NOT NULL) OVER (PARTITION BY deviceid ORDER BY time)->>(0-1) )::JSONB AS variables
FROM devices
;
SELECT ( JSONB_AGG(variables) FILTER (WHERE variables IS NOT NULL) OVER (PARTITION BY deviceid ORDER BY time)->>(jsonb_array_length(JSONB_AGG(variables) FILTER (WHERE variables IS NOT NULL) OVER (PARTITION BY deviceid ORDER BY time))-1) )::JSONB AS variables
FROM devices
;
```

### Software Information:
- JSqlParser 5.1 SNAPSHOT
- Database PostgreSQL

### Tips:
This example is used for fill forward values and I think it is quite common:
https://stackoverflow.com/a/75642951/4945871

**Comment by manticore-projects** [comment]
Greetings!

This is not about the JSON operator `->>` itself, which will accept both chars and numbers:
```
"->>" (token=<S_CHAR_LITERAL> | token=<S_LONG>) { jsonIdents.add(new AbstractMap.SimpleEntry<String, String>(token.image,"->>")); }
```

I think instead, the Analytic Function does not support (any) JSon Operator there.

**Comment by manticore-projects** [comment]
Although this works:

```sql

SELECT ( JSONB_AGG(variables) FILTER (WHERE variables IS NOT NULL) OVER (PARTITION BY deviceid ORDER BY time)->>'test' )::JSONB AS variables
FROM devices
;

```

**Comment by manticore-projects** [comment]
ok, you were so right! `S_LONG` is only positive, while `SignedExpression` does the trick!

**Comment by manticore-projects** [comment]
Thank you for reporting, `JsonExpressions` became just much more powerful and all your 3 examples parse now.
Cheers!
