### ISSUE TITLE
[BUG] SQL parsing timeout

### ISSUE THREAD

**Issue by elcnu986** [JSQLParser/JSqlParser#2057]
version：com.github.jsqlparser:jsqlparser:4.6

method: net.sf.jsqlparser.parser.CCJSqlParserUtil#parseStatement
    /**
     * @param parser
     * @return the statement parsed
     * @throws JSQLParserException
     */
    public static Statement parseStatement(CCJSqlParser parser) throws JSQLParserException {
        Statement statement = null;
        try {
            ExecutorService executorService = Executors.newSingleThreadExecutor();
            Future<Statement> future = executorService.submit(new Callable<Statement>() {
                @Override
                public Statement call() throws Exception {
                    return parser.Statement();
                }
            });
            executorService.shutdown();

            statement = future.get( parser.getConfiguration().getAsInteger(Feature.timeOut), TimeUnit.MILLISECONDS);
        } catch (TimeoutException ex) {
            parser.interrupted = true;
            throw new JSQLParserException("Time out occurred.", ex);
        } catch (Exception ex) {
            throw new JSQLParserException(ex);
        }
        return statement;
    }
    
    parser.getConfiguration().getAsInteger(Feature.timeOut), TimeUnit.MILLISECONDS

parser.getConfiguratgion() :
  public FeatureConfiguration getConfiguration() {
          return token_source.configuration;
      }
      
      
      the FeatureConfiguration field fill:
public CCJSqlParser(Provider stream) {
	 jj_input_stream = new SimpleCharStream(stream, 1, 1);
	 token_source = new CCJSqlParserTokenManager(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 599; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }
  
  there is a default  field of FeatureConfiguration in CCJSqlParserTokenManage ：
public FeatureConfiguration configuration = new FeatureConfiguration();

How can I modify this timeout in the FeatureConfiguration?

**Comment by manticore-projects** [comment]
Please see here: https://manticore-projects.com/JSQLParser/usage.html#define-the-parser-features
