### ISSUE TITLE
[BUG] JSQLParser Version : 5.1-SNAPSHOT : select count(*) fails in simple  mode

### ISSUE THREAD

**Issue by serge-rider** [JSQLParser/JSqlParser#2059]
### Failing SQL Feature:
In JSQLParser 5.x.

If run run with disabled complex parsing it fails on trivial queries if they contain `func(*)`.

(we cannot enable complex parsing because parser still hangs on queries with big number of brackets).

Java snippet:

```java
    public static void main(String[] args) throws Exception {
        CCJSqlParser parser = new CCJSqlParser(new StringProvider("select count(*) from zzz"));
        parser.withAllowComplexParsing(false);
        parser.Statement();
   }
```
Fails with error
```
Exception in thread "main" net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "(" "("
    at line 1, column 13.

Was expecting one of:

    "."
    "::"
    "^"
    <EOF>
    <ST_SEMICOLON>

	at net.sf.jsqlparser.parser.CCJSqlParser.generateParseException(CCJSqlParser.java:42285)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_consume_token(CCJSqlParser.java:42106)
	at net.sf.jsqlparser.parser.CCJSqlParser.Statement(CCJSqlParser.java:341)
```

### SQL Example:
Parser fails if query contains any functions call with asterisk (e.g. `count(*)` or `func_name(*)`)

Looks like a quite serious issue.

**Comment by manticore-projects** [comment]
Greetings @serge-rider and thank you for reporting this issue.

I have fixed it, but still would like to encourage you to NOT insist in simple parsing only and to let the parser check and decide for you.
Unfortunately there are statements failing in simple parsing mode and there are other statements failing in complex parsing mode.

To work around this effectively, please use `CCJSqlParserUtil.parse()` methods instead in order run supervised by an `ExecutorService` with fine-granular timeout. You can also provide your own (global) `ExecutorService` for it.

This works quite reliable and fast for us. (Manticore has it's own SQL Editor similar to DBeaver using JSQLParser and JSQLFormatter extensively for rather complex queries.)

**Comment by serge-rider** [comment]
Thank you for the fix and for the hint 👍 
We will try to migrate and rework the approach after 5.1

**Comment by manticore-projects** [comment]
@serge-rider and team, you are always very welcome!

You can count on our support and I also would like to invite you eying the sister projects:
a) JSQLFormatter for powerful pretty printing: https://manticore-projects.com/JSQLFormatter/index.html
b) JSQLTranspiler for Lineage and Dialect Rewriting: https://manticore-projects.com/JSQLTranspiler/index.html

(I always wanted to provide you with some plugins but struggle with the Eclipse platform and never had the time to really dive into it, sorry)
