### ISSUE TITLE
[BUG] JSQLParser 5.1-NAPSHOT : DUCKDB : net.sf.jsqlparser.JSQLParserException: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "SUMMARIZE" <S_IDENTIFIER>

### ISSUE THREAD

**Issue by hayssams** [JSQLParser/JSqlParser#2064]
Minor issue:
Would it be possible to accept the SUMMARIZE token as described here: https://duckdb.org/docs/guides/meta/summarize.html#:~:text=The%20SUMMARIZE%20command%20launches%20a,NULL%20values%20in%20the%20column.

eq:

```
SUMMARIZE tbl;
SUMMARIZE SELECT * FROM tbl

```

**Comment by manticore-projects** [comment]
certainly, thanks for your request.

**Comment by manticore-projects** [comment]
These two very specific variants are not supported:
```sql

CREATE TABLE tbl_summary AS SELECT * FROM (SUMMARIZE tbl);
SUMMARIZE TABLE 'https://blobs.duckdb.org/data/Star_Trek-Season_1.csv';

```

Is there any solid need for it please?

**Comment by hayssams** [comment]
Absolutely not !
Thank you for implementing this in such a short amount of time
