### ISSUE TITLE
[BUG] JSQLParser Version : RDBMS : net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "(" "("

### ISSUE THREAD

**Issue by wustydj** [JSQLParser/JSqlParser#2075]
Always check against the **Latest SNAPSHOT of JSQLParser** and the [Syntax Diagram](https://jsqlparser.github.io/JSqlParser/syntax_snapshot.html)

### Failing SQL Feature:
- When multiple nesting is performed using concat, parsing fails

### SQL Example:
```
select concat('the',cast(t.dim_week_upd as Nullable(String)),'week',cast(t.min_date as Nullable(String)),'-',cast(t.max_date as Nullable(String)),'') as `weekofyear` from table
```

### Software Information:
- JSqlParser version 5.0
- Database (e. g. Oracle, MS SQL Server, H2, PostgreSQL, IBM DB2 )

### Tips:
Detailed error log：
```
net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "(" "("
    at line 1, column 14.

Was expecting one of:

    "."
    "::"
    "^"
    <EOF>
    <ST_SEMICOLON>

	at net.sf.jsqlparser.parser.CCJSqlParser.generateParseException(CCJSqlParser.java:42285)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_consume_token(CCJSqlParser.java:42106)
	at net.sf.jsqlparser.parser.CCJSqlParser.Statement(CCJSqlParser.java:341)
```

**Comment by manticore-projects** [comment]
Greeting.

This is not about nested functions, but about the unsupported ColumnType `Nullable(String)`.
When using a plain standard column type, everything is working as expected. [You can test it online here.](http://jsqlformatter.manticore-projects.com/jsqlformatter/demo.html?args=-c%20MoUQMiDCAqAEkHsB2BjAhgFwBS1gcgwAsBTPAGl0jQGdtYMA6AEwEsBbAfQHdjiBrDgFcADk1gBBYLGggAGnACUFPD354AULi3aduCvBp1GbFkg5NMxCVJnzYS-AFpylQzmNoAHucvXpcxU1dYL18PHs-AANVPgQAMwBPYjQAJ0j1ADEAJQB5AFl6NAAjABtidQBuIA)

**Comment by manticore-projects** [comment]
Closing as answered, when no further question has been asked.
