### ISSUE TITLE
[BUG] JSQLParser Version : SQL syntax is correct, but parsing failed in 5.1-SNAPSHOT version

### ISSUE THREAD

**Issue by shenshihala** [JSQLParser/JSqlParser#2086]
### Failing SQL Feature:
- SQL syntax is correct, but parsing failed
- [example url](http://jsqlformatter.manticore-projects.com/jsqlformatter/demo.html?args=-c%20M4UwNiDGAuAECWATANIkxICd4AdrwHsA7ZYAQwFscJYAzTAi2YaAVwH14jaD3oQqYMv2bw4AdwAWITCFHQAdAANoATxwglsALywA-LDJFE8hWjDtaQgOY7YAcgAM92AUxpMsAEarYIRByQwiDWbqrISEA)

### SQL Example:
```select id,description,sample from stu_info_template sit where sit.`type` = 1 and sit.del_flag = '0' order by edu_category,id```
### Software Information:
- JSqlParser version 5.1-SNAPSHOT
- Mysql 8.0

**Comment by manticore-projects** [comment]
Greetings!

`SAMPLE` is a reserved keyword and needs to be quoted.
See https://manticore-projects.com/JSQLParser/keywords.html
