### ISSUE TITLE
[BUG] JSQLParser Version 5.1-SNAPSHOT: Lateral View with two aliases recognizes second alias as table

### ISSUE THREAD

**Issue by arodriguezdlc** [JSQLParser/JSqlParser#2088]
### Failing SQL Feature:

When using a LATERAL VIEW with two aliases, the second alias is incorrectly being interpreted as a JOIN with a table. Instead, it should be detected as a second alias for the exploded data.

The LateralView class currently has a method getColumnAlias that returns only one alias. This behavior could be incorrect because in cases where there are multiple aliases, such as with exploded arrays or maps, the method should return a list of aliases, not just one.

### SQL Example:

```sql
SELECT k, v 
FROM table 
LATERAL VIEW EXPLODE(a) exploded_data AS k, v;
```

In this query, the alias k is correctly detected as the first alias for the exploded data. However, the alias v is mistakenly identified as a table named v, instead of being treated as the second alias for the exploded data.

The expected behavior is that both k and v should be recognized as aliases for the exploded data, with no table join implied.

### Software Information:
- JSqlParser version: 5.1-SNAPSHOT
- Database: Spark SQL

**Comment by manticore-projects** [comment]
Greetings!

Would that not be a `Struct` based Alias? We support this already, but not in the form of a  plain comma separated column list.
We support compound aliases like `A(k,v)`.

**Comment by manticore-projects** [comment]
A bit quick and dirty, but it works now. Cheers!

**Comment by arodriguezdlc** [comment]
Thank you @manticore-projects !! We are testing with the new snapshot. Any plans for a 5.1 release? Cheers!
