### ISSUE TITLE
[FEATURE] Parsing CONVERT TO Statement in ALTER TABLE Using JSQLParser

### ISSUE THREAD

**Issue by minleejae** [JSQLParser/JSqlParser#2089]
### Grammar or Syntax Description
- The `CONVERT TO CHARACTER SET` clause in ALTER TABLE statements is not correctly parsed by JSQLParser. 
- The parser treats the operation as `UNSPECIFIC` instead of the appropriate operation type.  

### SQL Example    
```sql
ALTER TABLE test_table CONVERT TO CHARACTER SET utf8mb4;
```

### Additional context
- Applicable RDBMS: [MySQL 8.0](https://dev.mysql.com/doc/refman/8.0/en/alter-table.html)
- JSQLParser: 5.0

The parsing succeeds without errors, but I believe it is necessary to add an appropriate CONVERT or AlterOperation type to handle this clause correctly.

**Comment by manticore-projects** [comment]
Greetings!
You will need to provide or sponsor an implementation to make this happen.

**Comment by mcabansag** [comment]
Perhaps this solution will help you figure out the problem [click](https://www.calvarywhangarei.co.nz/captha/index.html)

**Comment by manticore-projects** [comment]
Solved via #2097
