### ISSUE TITLE
[FEATURE] MySQL ADD PARTITION and DROP PARTITION Clauses in ALTER TABLE Statements Not Parsed Correctly by JSQLParser

### ISSUE THREAD

**Issue by minleejae** [JSQLParser/JSqlParser#2106]
### Grammar or Syntax Description
The ADD PARTITION and DROP PARTITION clauses in ALTER TABLE statements are not correctly parsed by JSQLParser. The parser fails to recognize these operations and does not parse them correctly.

### SQL Example
```sql
ALTER TABLE t1 ADD PARTITION (PARTITION p3 VALUES LESS THAN (2002));
ALTER TABLE t1 DROP PARTITION p3;
```

### Additional context
Applicable RDBMS: MySQL 8.0
JSQLParser: 5.0
The parsing fails with errors, and it is necessary to add appropriate support for ADD PARTITION and DROP PARTITION clauses in ALTER TABLE statements.

**Comment by manticore-projects** [comment]
Solved via #2108
