### ISSUE TITLE
[BUG] JSQLParser Version : RDBMS : ClassCastException in ParenthesedSelect#getSetOperationList

### ISSUE THREAD

**Issue by marcgise-prode** [JSQLParser/JSqlParser#2113]
### Failing SQL Feature:
- Error in **ParenthesedSelect** when invoking **getSetOperationList** method. It always make an unchecked cast to **SetOperationList** of **select** attribute, but it could be a **PlainSelect** object.

### SQL Example:
- Simplified Query Example, focusing on the failing feature
    ```sql
    select
	*
    from
	    (
	    select
		    name
	    from
		    users
    ) as a
    ```

### Software Information:
- JSqlParser version: 5.0
- Database: PostgreSQL

**Comment by manticore-projects** [comment]
Greetings.

`getSetOperationList` should be only called when there is a anything like a `UNION` involved.
In your example there is no `SetOperation` but only `PlainSelects`. Nothing to fix.

**Comment by marcgise** [comment]
But it's not clear that this method only work in this case. We're using this method to parse any SQL, and we're forced to use a try...catch to deal with this exception that, taking into account the signature of the method, it should never occur...

**Comment by manticore-projects** [comment]
You should either use the `SELECT`  visitor or `INSTANCE OF`.
