### ISSUE TITLE
[FEATURE] Support for MySQL-specific ALTER TABLE options (ENCRYPTION, AUTO_INCREMENT, ENGINE) missing in JSQLParser

### ISSUE THREAD

**Issue by minleejae** [JSQLParser/JSqlParser#2114]
### Grammar or Syntax Description
- **Brief description:** The parser does not support specific features like `ENCRYPTION`, `AUTO_INCREMENT`, and `ENGINE` options in `ALTER TABLE` statements, categorizing them as `UnspecifiedOperation`. These features are part of MySQL-specific extensions to the `ALTER TABLE` syntax.

### SQL Example
- Simplified Query Examples focusing on the failing features:
    ```sql
    ALTER TABLE confidential_data ENCRYPTION = 'Y';
    ALTER TABLE tt AUTO_INCREMENT = 101;
    ALTER TABLE city2 ENGINE = InnoDB;
    ```

### Additional Context
- **JSQLParser Version:** 5.0
- **Applicable RDBMS:** MySQL 8.0 and later versions.
- **Reference Documentation:**
  - [MySQL ALTER TABLE Syntax](https://dev.mysql.com/doc/refman/8.0/en/alter-table.html)

**Comment by manticore-projects** [comment]
Solved via #2115.
