### ISSUE TITLE
Performance - Stuck parsing

### ISSUE THREAD

**Issue by ryanmurf** [JSQLParser/JSqlParser#215]
Try and parse this and it goes on forever

SELECT (CASE  WHEN ((`value` LIKE '%t1%') OR (`value` LIKE '%t2%')) THEN 't1s' WHEN ((((((((((((((((((((((((((((`value` LIKE '%t3%') OR (`value` LIKE '%t3%')) OR (`value` LIKE '%t3%')) OR (`value` LIKE '%t4%')) OR (`value` LIKE '%t4%')) OR (`value` LIKE '%t5%')) OR (`value` LIKE '%t6%')) OR (`value` LIKE '%t6%')) OR (`value` LIKE '%t7%')) OR (`value` LIKE '%t7%')) OR (`value` LIKE '%t7%')) OR (`value` LIKE '%t8%')) OR (`value` LIKE '%t8%')) OR (`value` LIKE '%CTO%')) OR (`value` LIKE '%cto%')) OR (`value` LIKE '%Cto%')) OR (`value` LIKE '%t9%')) OR (`value` LIKE '%t9%')) OR (`value` LIKE '%COO%')) OR (`value` LIKE '%coo%')) OR (`value` LIKE '%Coo%')) OR (`value` LIKE '%t10%')) OR (`value` LIKE '%t10%')) OR (`value` LIKE '%CIO%')) OR (`value` LIKE '%cio%')) OR (`value` LIKE '%Cio%')) OR (`value` LIKE '%t11%')) OR (`value` LIKE '%t11%')) THEN 't' WHEN ((((`value` LIKE '%t12%') OR (`value` LIKE '%t12%')) OR (`value` LIKE '%VP%')) OR (`value` LIKE '%vp%')) THEN 'Vice t12s' WHEN ((((((`value` LIKE '% IT %') OR (`value` LIKE '%t13%')) OR (`value` LIKE '%t13%')) OR (`value` LIKE '% it %')) OR (`value` LIKE '%tech%')) OR (`value` LIKE '%Tech%')) THEN 'IT' WHEN ((((`value` LIKE '%Analyst%') OR (`value` LIKE '%t14%')) OR (`value` LIKE '%Analytic%')) OR (`value` LIKE '%analytic%')) THEN 'Analysts' WHEN ((`value` LIKE '%Manager%') OR (`value` LIKE '%manager%')) THEN 't15' ELSE 'Other' END ) FROM tab1

We tracked the problem down to lines 1878-1880 in JSqlParserCC.jjt release 9.4. We reverted back to 9.2 for those lines because we noticed 9.2 didn't have this problem.

**Comment by wumpz** [comment]
Could you give me this modified grammar part? I could reproduce it with 0.9.5 Snapshot.

**Comment by ryanmurf** [comment]
In master

2030     | LOOKAHEAD([sign="+" | sign="-"] "(" SubSelect() ")")     [sign="+" | sign="-"] "(" retval=SubSelect() ")"
2031
2032         | LOOKAHEAD(3)   [sign="+" | sign="-"] "(" retval=BitwiseAndOr() ")" {retval = new Parenthesis(retval); }

to

2030         | LOOKAHEAD(2)                            [sign="+" | sign="-"] "(" retval=PrimaryExpression() ")" {retval = new Parenthesis(retval); }
2031
2032         |                                         [sign="+" | sign="-"] "(" retval=SubSelect() ")"

**Comment by ryanmurf** [comment]
This fixes the issue but causes a test to break.

**Comment by wumpz** [comment]
That is a hard one. I tackled ist down to resolving parenthesis parsing. Due to needed lookups it slows the parser down to be unusable. The new grammar part is needed to parse some boolean expressions within a select list. Unfortunatly I could not find a proper solution at a quick search. This seems to result in a massive grammar change :(.

**Comment by ryanmurf** [comment]
We also noticed that this can affect performance on much smaller number of parenthesis then the example above. The time required grows exponentially with the number of parenthesis.

**Comment by wumpz** [comment]
I cleaned up some lookaheads. All tests are passing. I included a test with less parenthesis. I seems as if there is a speedup but not enough for your first example.

**Comment by wumpz** [comment]
I think now I provided a proper solution. The actual snapshot parses and deparses your statement within 0.2 secs. No test is failing. Could you check it? 
By the way, the changes to the grammar were not as big as I thought. The problem were some duplications regarding parenthesis usage.

Cheers Tobias

**Comment by ryanmurf** [comment]
@wumpz works great. Thank you.
