### ISSUE TITLE
Fail to parse simple query with column named "Separator"

### ISSUE THREAD

**Issue by donshop11** [JSQLParser/JSqlParser#217]
"SELECT T.Separator AS x"

Fails with 

Caused by: net.sf.jsqlparser.parser.ParseException: Encountered " "." ". "" at line 1, column 9.
Was expecting one of:
    <EOF> 
    "AS" ...
    "DO" ...
    "ANY" ...
    "KEY" ...
    "PERCENT" ...
    "INTO" ...
    "FROM" ...
    "OPEN" ...
    "WHERE" ...
    "FOR" ...
    "XML" ...
    "GROUP" ...
    "VALUE" ...
    "HAVING" ...
    "VALUES" ...
    "REPLACE" ...
    "TRUNCATE" ...
    "CAST" ...
    "OVER" ...
    "PARTITION" ...
    "EXTRACT" ...
    "MATERIALIZED" ...
    "START" ...
    "CONNECT" ...
    "SIBLINGS" ...
    "COLUMN" ...
    "NULLS" ...
    "FIRST" ...
    "LAST" ...
    "ROWS" ...
    "RANGE" ...
    "FOLLOWING" ...
    "ROW" ...
    "COLLATE" ...
    "OPTION" ...
    <S_IDENTIFIER> ...
    <S_QUOTED_IDENTIFIER> ...
    ";" ...
    "," ...
    "||" ...
    "^" ...
    "::" ...
    "COLLATE" ...
    "COLLATE" ...
    "::" ...
    "^" ...
    "||" ...
    "COLLATE" ...
    "AS" ...
    <S_IDENTIFIER> ...
    <S_QUOTED_IDENTIFIER> ...
    "CAST" ...
    "DO" ...
    "EXTRACT" ...
    "FIRST" ...
    "FOLLOWING" ...
    "LAST" ...
    "MATERIALIZED" ...
    "NULLS" ...
    "PARTITION" ...
    "RANGE" ...
    "ROW" ...
    "ROWS" ...
    "SIBLINGS" ...
    "VALUE" ...
    "XML" ...
    "COLUMN" ...
    "REPLACE" ...
    "TRUNCATE" ...
    "KEY" ...
    "ANY" ...
    "OPEN" ...
    "OVER" ...
    "VALUES" ...
    "PERCENT" ...
    "," ...
    "INTO" ...
    "FROM" ...
    "WHERE" ...
    "START" ...
    "CONNECT" ...
    "GROUP" ...
    "HAVING" ...
    "FOR" ...
    "OPTION" ...
    "COLLATE" ...
    "COLLATE" ...
    "::" ...
    "^" ...
    "||" ...
    "COLLATE" ...
    "AS" ...
    <S_IDENTIFIER> ...
    <S_QUOTED_IDENTIFIER> ...
    "CAST" ...
    "DO" ...
    "EXTRACT" ...
    "FIRST" ...
    "FOLLOWING" ...
    "LAST" ...
    "MATERIALIZED" ...
    "NULLS" ...
    "PARTITION" ...
    "RANGE" ...
    "ROW" ...
    "ROWS" ...
    "SIBLINGS" ...
    "VALUE" ...
    "XML" ...
    "COLUMN" ...
    "REPLACE" ...
    "TRUNCATE" ...
    "KEY" ...
    "ANY" ...
    "OPEN" ...
    "OVER" ...
    "VALUES" ...
    "PERCENT" ...
    "PERCENT" ...
    "PERCENT" ...
    "PERCENT" ...
    "PERCENT" ...
    "PERCENT" ...
    "PERCENT" ...
    "PERCENT" ...
    "PERCENT" ...
    "PERCENT" ...
    "PERCENT" ...
    "PERCENT" ...
    "PERCENT" ...
    "PERCENT" ...
    "PERCENT" ...
    "PERCENT" ...
    "PERCENT" ...
    "COLLATE" ...
    "COLLATE" ...
    "::" ...
    "^" ...
    "||" ...
    "COLLATE" ...
    "COLLATE" ...
    "::" ...
    "^" ...
    "COLLATE" ...
    "COLLATE" ...

**Comment by wumpz** [comment]
Looks like you are sending the quotes to the parser.

**Comment by donshop11** [comment]
No, just try  you can try also:
SELECT Separator  FROM T

**Comment by wumpz** [comment]
Ok. Didn't saw the points between the quotes on my mobile.
