### ISSUE TITLE
Support for Postgresql ARRAY operators

### ISSUE THREAD

**Issue by design4it** [JSQLParser/JSqlParser#222]
see http://www.postgresql.org/docs/9.4/static/functions-array.html

**Comment by opeongo** [comment]
I am interested in this one also and am willing to help out.  Is anyone working on it?

**Comment by wumpz** [comment]
Which operators are not processed? Arrays should be parsed successfully. Is there a problem? As far as I know nobody is working on this theme at the moment. Tobias

**Comment by opeongo** [comment]
Here is a fragment of a pg SQL statement that causes a parsing exception.  There is more to the statement, but probably not relevant: 

```sql
SELECT 
        CASE
            WHEN p.col1::text <> ALL (ARRAY['ISL'::text, 'OTH'::text, 'NAT'::text, 'LUD'::text, 'GEO'::text]) THEN 'A'::text
            ELSE 'U'::text
        END AS avail,

```

The parser trips up when it reaches the ALL keyword.  Also, I looked through the source for the jjt file and could not see any reference to the ARRAY[] construct, so I assumed that this has not been added yet.

**Comment by opeongo** [comment]
Here is a link to the postgres docs describing the array syntax.  In particular section 8.15.5 Searching in Arrays.

[https://www.postgresql.org/docs/current/static/arrays.html#ARRAYS-SEARCHING](url)

**Comment by opeongo** [comment]
I had a look over the `JSqlParser.jjt` file to try to understand the grammar.  It looks like there are two things needed here.  

The first is an addition to the grammar to parse array literals.

The second is that the `AnyComparisonExpression` and `AllComparisonExpression` elements should accept an ArrayLiteral or a column in addition to a `SubSelect`.  

Does this sound reasonable?  If so then I can try to add this.  I am a bit wary however, because I have tried modifying complicated grammars before and it can cause unexpected side effects.  Also, this will be my first contribution using GitHub, so some pointers here would help also.

**Comment by opeongo** [comment]
I have an implementation working, but there is a syntax conflict.  So many dialects of SQL, so much conflict.  Is a universal SQL parser even possible?

In the Postgres dialect an array literal is enclosed with [ ].  However, some other dialect (SQL Server?) uses [ ] to delineate quoted identifiers. An example of the former is
```sql
 SELECT 
         CASE
             WHEN p.access1::text = ALL (ARRAY['ISL'::text, 'OTH'::text, 'NAT'::text, 'LUD'::text, 'GEO'::text]) THEN 'A'::text
             ELSE 'U'::text
        END AS avail1,
```
and of the latter (from the test suite) is
```sql
        final String statement = "SELECT columnName FROM [server-name\\server-instance].databaseName.schemaName.tableName";
```
In the JSqlParserCC.jjt file the token `<S_QUOTED_IDENTIFIER>` catches the entire contents of the literal array, so the individual elements are not getting parsed.  I am not a JavaCC expert, but I suspect that there might be a way to selectively enable/disable the quoted identifier behaviour based on context.  For example, by default it is on when looking for an identifier, but turn it off after finding an `<K_ARRAY>` token when expecting a list of array elements.  I think that this has to do with changing lexical state.  Can anyone give me some hints on how to do this?

My progress so far is in my tree at [https://github.com/opeongo/JSqlParser/tree/arrayLiteral](https://github.com/opeongo/JSqlParser/tree/arrayLiteral)

**Comment by opeongo** [comment]
I figured out a simple way to resolve the syntax conflict between the array literal and the SqlServer quoted identifier, and both seem to be working now.  I'll send in a pull request for this tree: 
https://github.com/opeongo/JSqlParser/tree/arrayLiteral

I would like to add a test case for this new syntax but I am not familiar with the way that tests are set up.  Let me know where to add the test and I will do that also.
