### ISSUE TITLE
When use toString of SetOperationList it

### ISSUE THREAD

**Issue by ABRUZI** [JSQLParser/JSqlParser#226]

**Comment by ABRUZI** [comment]
I have a sql statement like this

select  a from ( select 1 as a from a union all select 2 as a from b ) temp


when I try to use toString method I found SetOperationList  add brackets automatically


in the line 104 , here is the code:

buffer.append("(").append(selects.get(i).toString()).append(")");

can anybody fix this ? 

Thank you

**Comment by wumpz** [comment]
I think it was introduced to avoid optional bracket parsing within these set operations. Nevertheless I will look into it. Give me more time.
