### ISSUE TITLE
merge into using dual - fails to parse (valid for oracle)

### ISSUE THREAD

**Issue by donshop11** [JSQLParser/JSqlParser#232]
in oracle, this is valid:

MERGE INTO xyz  using dual 
ON ( custom_id = ?  ) 
WHEN NOT matched THEN 
	INSERT (custom_id) VALUES (?)
WHEN matched THEN 
	UPDATE SET abc = sysdate
 

it fails to parse with 
Encountered " <S_IDENTIFIER> "dual "" at line 1, column 28.

see documentation :
http://docs.oracle.com/cd/B19306_01/server.102/b14200/statements_9016.htm

**Comment by wumpz** [comment]
The parenthesis problem is solved (not yet commited). Are you sure your statement is valid? I always though the update part must be before the insert part. Therefore
~~~SQL
MERGE INTO xyz using dual
ON ( custom_id = ? )
WHEN matched THEN
UPDATE SET abc = sysdate
WHEN NOT matched THEN
INSERT (custom_id) VALUES (?)
~~~

**Comment by wumpz** [comment]
If your statement is indeed correct, we should introduce some more modificiations.

**Comment by donshop11** [comment]
unfortunately this is the case - it is executing (on Oracle) also when the INSERT is before the UPDATE.
