### ISSUE TITLE
can't parser MSSQL  with(nolock、noexpand...)

### ISSUE THREAD

**Issue by boying52** [JSQLParser/JSqlParser#236]
with(nolock/noexpand) can not support

**Comment by wumpz** [comment]
I assume this is kind of an optimizer setting. Could you provide an complete sql?

**Comment by boying52** [comment]
SELECT 
						COUNT(1)
					FROM [sales].[vi_HM_HouseDelList] v WITH(NOEXPAND)
						left join [sales].[vi_HM_Sales_VALHOUSE_SEARCH] valhouse on valhouse.HOUSE_ID=v.HOUSE_ID 
						left join [sales].[vi_HM_Sales_DEL_TAGS]  tags on tags.DEL_CODE=v.HOUDEL_CODE
						left join [sales].[vi_HM_Sales_DEL_EXC] exc WITH (NOLOCK) ON exc.DEL_CODE=v.HOUDEL_CODE 
						LEFT JOIN (
							SELECT
							 DEL_CODE ,COUNT(1) AS trcomCount,
							 SUM(CASE WHEN RECOM_SCOPE='10040001' THEN 1 ELSE 0 END) grptrcomCount,
							 SUM(CASE WHEN RECOM_SCOPE='10040002' THEN 1 ELSE 0 END) areatrcomCount,
							 SUM(CASE WHEN RECOM_SCOPE='10040003' THEN 1 ELSE 0 END) allscopetrcomCount
							from sales.T_HM_RECOM
							where DATEDIFF(day,GETDATE(),END_DATE)>=0 AND STATUS='1'
							and ((RECOM_SCOPE='10040001' and GROUP_ID=#USER_BUSIGRPID#) OR (RECOM_SCOPE='10040002' and AREA_ID=#USER_BUSIARID#) OR (RECOM_SCOPE='10040003'))
							GROUP BY DEL_CODE
						) t1 on t1.DEL_CODE = v.HOUDEL_CODE
attention:  
1、[sales].[vi_HM_HouseDelList]  is Index_View in MSSQL2014，it must be set WITH(NOEXPAND) for reference index views,because it can improve performence for query.  
2、WITH(NOLOCK) means never care transaction，it will be affected by uncommited transaction

**Comment by boying52** [comment]
SELECT 
COUNT(1)
FROM [sales].[vi_HM_HouseDelList] v WITH(NOEXPAND)
left join [sales].[vi_HM_Sales_VALHOUSE_SEARCH] valhouse on valhouse.HOUSE_ID=v.HOUSE_ID 
left join [sales].[vi_HM_Sales_DEL_TAGS] tags on tags.DEL_CODE=v.HOUDEL_CODE
left join [sales].[vi_HM_Sales_DEL_EXC] exc WITH (NOLOCK) ON exc.DEL_CODE=v.HOUDEL_CODE 
LEFT JOIN (
SELECT
DEL_CODE ,COUNT(1) AS trcomCount,
SUM(CASE WHEN RECOM_SCOPE='10040001' THEN 1 ELSE 0 END) grptrcomCount,
SUM(CASE WHEN RECOM_SCOPE='10040002' THEN 1 ELSE 0 END) areatrcomCount,
SUM(CASE WHEN RECOM_SCOPE='10040003' THEN 1 ELSE 0 END) allscopetrcomCount
from sales.T_HM_RECOM
where DATEDIFF(day,GETDATE(),END_DATE)>=0 AND STATUS='1'
and ((RECOM_SCOPE='10040001' and GROUP_ID=#USER_BUSIGRPID#) OR (RECOM_SCOPE='10040002' and AREA_ID=#USER_BUSIARID#) OR (RECOM_SCOPE='10040003'))
GROUP BY DEL_CODE
) t1 on t1.DEL_CODE = v.HOUDEL_CODE
attention:

1、[sales].[vi_HM_HouseDelList] is Index_View in MSSQL2014，it must be set WITH(NOEXPAND) for reference index views,because it can improve performence for query.

2、WITH(NOLOCK) means never care transaction，it will not be affected by uncommited transaction

**Comment by boying52** [comment]
https://msdn.microsoft.com/library/ms175972(v=sql.120).aspx

**Comment by boying52** [comment]
WITH common_table_expression in:

https://msdn.microsoft.com/library/ms175972(v=sql.120).aspx

**Comment by boying52** [comment]
FROM (Transact-SQL):
https://msdn.microsoft.com/en-us/library/ms177634(v=sql.120).aspx

Table Hints (Transact-SQL):
https://msdn.microsoft.com/en-us/library/ms187373(v=sql.120).aspx

**Comment by wumpz** [comment]
first support is implemented
