### ISSUE TITLE
Support for MAX type argument

### ISSUE THREAD

**Issue by mlkammer** [JSQLParser/JSqlParser#245]
Currently, the MAX type argument does not seem to be supported by JSQLParser. The following query gives a ParseException:
`SELECT CAST('foo' AS NVARCHAR(MAX))`

The following query can be parsed successfully:
`SELECT CAST('foo' AS NVARCHAR(3))`

It would be great if the MAX type argument were supported. Implementing this could be done without having to change the signature of the `getArgumentsStringList` method in `net.sf.jsqlparser.statement.create.table.ColDataType`.

On a side note: the JSQLParser library is greatly appreciated by us. Thanks to the authors!

**Comment by mlkammer** [comment]
It's really great to see such a fast and adequate response to issues that are reported, especially in an open source library. Thanks, @wumpz!

**Comment by wumpz** [comment]
Thx for using JSqlParser. :)
