### ISSUE TITLE
Support for Alter Table Add Multi Columns Statement

### ISSUE THREAD

**Issue by imben1109** [JSQLParser/JSqlParser#246]
the Alter table statement would throw JSQLParserException. 

It mean JSQLParser does not support it.

**Comment by mlkammer** [comment]
I'm not an author of JSqlParser but as far as I know JSqlParser does have support for ALTER TABLE statements, although maybe not for all forms of them.

The following query can be parsed successfully as a `net.sf.jsqlparser.statement.alter.Alter` object:
`ALTER TABLE MyTable ADD COLUMN MyColumn Int`

Could you post a (simplified) version of your ALTER TABLE statement which throws a parse exception?

**Comment by imben1109** [comment]
I am using CCJSqlParserUtil.parse to parse the alter table statement and it throw JSQLParserException

**Comment by wumpz** [comment]
You should post your exact alter statement. As mlkammer mentioned, JSqlParser does support it to a certain degree.

**Comment by imben1109** [comment]
ALTER TABLE TABLE1 ADD ( COLUMN1 VARCHAR2(751), COLUMN2 VARCHAR2(600) )
This is tested alter statement.

**Comment by mlkammer** [comment]
There seem to be two things that JSqlParser does not seem to support here (@wumpz, can you confirm this?):

- adding multiple columns in a single ALTER TABLE statement
- adding columns without the COLUMN keyword

If you add the COLUMN keyword and make two separate statements out of it, it can be parsed successfully. The following statements work:
`ALTER TABLE TABLE1 ADD COLUMN COLUMN1 VARCHAR2(751);`
`ALTER TABLE TABLE1 ADD COLUMN COLUMN2 VARCHAR2(600);`

@imben1109, does this work for you?

**Comment by imben1109** [comment]
Tested the below statement. 
"ALTER TABLE TABLE1 ADD COLUMN COLUMN1 VARCHAR2(751);"

It works.

**Comment by wumpz** [comment]
@mlkammer: confirmed. JSqlParser does not support adding multiple columns through one sql.
