### ISSUE TITLE
Support For Tablespace for create table statement

### ISSUE THREAD

**Issue by imben1109** [JSQLParser/JSqlParser#247]
I tested create table with using tablespace statment.
The CCJSqlParserUtil would throws ParseException. The below is my tested statement.
CREATE TABLE TABLE1  (
	COLUMN1 VARCHAR2(15),
	COLUMN2 VARCHAR2(15)
   CONSTRAINT P_PK PRIMARY KEY (COLUMN1) USING INDEX TABLESPACE "T_INDEX"
) TABLESPACE "T_SPACE";

**Comment by eolivelli** [comment]
I will find this very usefull for my project:
https://github.com/diennea/herddb

**Comment by wumpz** [comment]
Is this indeed a valid SQL? If a constaint defines a column, I thought it should be divided from the rest with a comma.
