### ISSUE TITLE
sql with schema occur error

### ISSUE THREAD

**Issue by benkris1** [JSQLParser/JSqlParser#249]
`String sql = "delete from 568c84b9e9db730001bb1454.product where 1=1";
 Statement stmt = CCJSqlParserUtil.parse(sql);
Delete delete = (Delete) stmt;
`
ERROR:
`Caused by: net.sf.jsqlparser.parser.ParseException: Encountered " <S_LONG> "568 "" at line 1, column 13.
Was expecting one of:
    "DO" ...
    "ANY" ...
    "KEY" ...
    "PERCENT" ...
    "OPEN" ...
    "XML" ...
    "VALUE" ...
    "VALUES" ...
    "REPLACE" ...
    "TRUNCATE" ...
    "CAST" ...
    "OVER" ...
    "PARTITION" ...
    "EXTRACT" ...
    "MATERIALIZED" ...
    "PRIOR" ...
    "SIBLINGS" ...
    "COLUMN" ...
    "NULLS" ...
    "FIRST" ...
    "LAST" ...
    "ROWS" ...
    "RANGE" ...
    "FOLLOWING" ...
    "ROW" ...
    "SEPARATOR" ...
    "CASCADE" ...
    "NO" ...
    "ACTION" ...
    <S_IDENTIFIER> ...
    <S_QUOTED_IDENTIFIER> ...
    <S_IDENTIFIER> ...
    <S_QUOTED_IDENTIFIER> ...
    "CAST" ...
    "DO" ...
    "EXTRACT" ...
    "FIRST" ...
    "FOLLOWING" ...
    "LAST" ...
    "MATERIALIZED" ...
    "NULLS" ...
    "PARTITION" ...
    "RANGE" ...
    "ROW" ...
    "ROWS" ...
    "SIBLINGS" ...
    "VALUE" ...
    "XML" ...
    "COLUMN" ...
    "REPLACE" ...
    "TRUNCATE" ...
    "KEY" ...
    "ANY" ...
    "OPEN" ...
    "OVER" ...
    "VALUES" ...
Disconnected from the target VM, address: '127.0.0.1:61671', transport: 'socket'
    "PERCENT" ...
    "PRIOR" ...
    "SEPARATOR" ...
    "NO" ...
    "ACTION" ...
    "CASCADE" ...
    <S_IDENTIFIER> ...
    <S_QUOTED_IDENTIFIER> ...
    "CAST" ...
    "DO" ...
    "EXTRACT" ...
    "FIRST" ...
    "FOLLOWING" ...
    "LAST" ...
    "MATERIALIZED" ...
    "NULLS" ...
    "PARTITION" ...
    "RANGE" ...
    "ROW" ...
    "ROWS" ...
    "SIBLINGS" ...
    "VALUE" ...
    "XML" ...
    "COLUMN" ...
    "REPLACE" ...
    "TRUNCATE" ...
    "KEY" ...
    "ANY" ...
    "OPEN" ...
    "OVER" ...
    "VALUES" ...
    "PERCENT" ...
    "PRIOR" ...
    "SEPARATOR" ...
    "NO" ...
    "ACTION" ...
    "CASCADE" ...
    <S_IDENTIFIER> ...
    <S_QUOTED_IDENTIFIER> ...
    "CAST" ...
    "DO" ...
    "EXTRACT" ...
    "FIRST" ...
    "FOLLOWING" ...
    "LAST" ...
    "MATERIALIZED" ...
    "NULLS" ...
    "PARTITION" ...
    "RANGE" ...
    "ROW" ...
    "ROWS" ...
    "SIBLINGS" ...
    "VALUE" ...
    "XML" ...
    "COLUMN" ...
    "REPLACE" ...
    "TRUNCATE" ...
    "KEY" ...
    "ANY" ...
    "OPEN" ...
    "OVER" ...
    "VALUES" ...
    "PERCENT" ...
    "PRIOR" ...
    "SEPARATOR" ...
    "NO" ...
    "ACTION" ...
    "CASCADE" ...
    
	at net.sf.jsqlparser.parser.CCJSqlParser.generateParseException(CCJSqlParser.java:13996)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_consume_token(CCJSqlParser.java:13852)
	at net.sf.jsqlparser.parser.CCJSqlParser.Table(CCJSqlParser.java:1780)
	at net.sf.jsqlparser.parser.CCJSqlParser.TableWithAlias(CCJSqlParser.java:1817)
	at net.sf.jsqlparser.parser.CCJSqlParser.Delete(CCJSqlParser.java:991)
	at net.sf.jsqlparser.parser.CCJSqlParser.SingleStatement(CCJSqlParser.java:123)
	at net.sf.jsqlparser.parser.CCJSqlParser.Statement(CCJSqlParser.java:68)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:52)
	... 2 more`

**Comment by benkris1** [comment]
`delete from 568c84b9e9db730001bb1454.ama_member_relation_2 where 1=1;` can execute in mysql commond

**Comment by wumpz** [comment]
JSqlParser does not support this **568c84b9e9db730001bb1454** schema name. It does not fit the identifier rule. You need to quote the schema. Then it should work:

`delete from "568c84b9e9db730001bb1454".ama_member_relation_2 where 1=1;`

**Comment by benkris1** [comment]
but it can run by JDBC or mysql command line. can support it. ?

**Comment by benkris1** [comment]
In my mysql proxy project,need parse user's sql.  when user connect mysql proxy,they can run any sql which Mysql can support.  Thank you . anybody

**Comment by wumpz** [comment]
You are right, this is a mysql specific. JSqlParser allowes to parse a lot of SQLs from different database management systems. But it does not parse all SQLs of each DBMS. IMHO an identifier should never start with a digit. I consider this a bad practice. Nevertheless bringing JSqlParser to parse this would probably result in a rewrite of large parts of the parser.

**Comment by wumpz** [comment]
I decided not to implement it.
