### ISSUE TITLE
JSqlParser  cann't parser sql correctly

### ISSUE THREAD

**Issue by sixtrees** [JSQLParser/JSqlParser#250]
I use JSqlParser to parser user'sql , when user input a sql ,such as select * from tabl1 "tabl1(city)"，it will meet a exception.

**Comment by wumpz** [comment]
Please provide the concrete exception. Tobias

**Comment by mlkammer** [comment]
Cannot reproduce the exception. The following code works:
`CCJSqlParserUtil.parse("select * from tabl1 \"tabl1(city)\"");`

**Comment by wumpz** [comment]
@mlkammer Thx for testing it. 

So could we close this issue or are there more informations?
