### ISSUE TITLE
Failed to parse CREATE PROCEDURE statement

### ISSUE THREAD

**Issue by amalikumuduni** [JSQLParser/JSqlParser#251]
Statement statement = CCJSqlParserUtil.parse("CREATE PROCEDURE Test" +
                "AS" +
                "BEGIN" +
                "SELECT \* FROM MyTable" +
                "END");

Above code failed.

Exception in thread "main" net.sf.jsqlparser.JSQLParserException
    at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:54)
    at com.zone24x7.Main.main(Main.java:14)
Caused by: net.sf.jsqlparser.parser.ParseException: Encountered " "_" "_ "" at line 1, column 36.
Was expecting one of:
    "ON" ...
    "KEY" ...
    "NOT" ...
    "NULL" ...
    "INDEX" ...
    "DELETE" ...
    "UPDATE" ...
    "PRIMARY" ...
    "FOREIGN" ...
    "REFERENCES" ...
    "ROWS" ...
    "COMMIT" ...
    "UNIQUE" ...
    "CASCADE" ...
    <S_DOUBLE> ...
    <S_LONG> ...
    <S_IDENTIFIER> ...
    <S_CHAR_LITERAL> ...
    "=" ...
    "(" ...
    "+" ...
    "-" ...

**Comment by wumpz** [comment]
create procedure and create function is not supported by JSqlParser. There are open issues for this. But as the name tells you, JSqlParser is a SQL parser and not a PL/SQL or TSQL parser. So there are no plans to support it. Maybe a light variation proposed in one of the create function issues to deliver the function body as a non parsed string, but not more.
