### ISSUE TITLE
"Select ... For Update" SQL Parser	Error

### ISSUE THREAD

**Issue by tejoe** [JSQLParser/JSqlParser#255]
Is it planned to support the select ... for update syntax soon?

Could not parse statement SELECT * FROM emp WHERE empno = ? FOR UPDATE due to following exception:
Encountered " "FOR" "FOR "" at line 1, column 35.
Was expecting one of:
    <EOF> 
    "GROUP" ...
    "HAVING" ...
    "START" ...
    "CONNECT" ...
    ";" ...
    "START" ...
    "CONNECT" ...
    "GROUP" ...
    "HAVING" ...

**Comment by wumpz** [comment]
Hmm. As a matter of fact for update is already supported. I am not sure sinve what version. Look at test `SelectTest.testSelectForUpdate`.
I added your statement as a test and was able to parse it successfully. What version do you use?

**Comment by wumpz** [comment]
I pushed the source code including your sql. Are you able to build it successfully?

**Comment by tejoe** [comment]
I was at version 0.9. I will try with current version and close this issue then

**Comment by tejoe** [comment]
Test successfull. Done.
