### ISSUE TITLE
Error parsing select from table (Keyword)

### ISSUE THREAD

**Issue by donshop11** [JSQLParser/JSqlParser#261]
in the following "table" is considered as KW

select column_value from table(VARCHAR_LIST_TYPE())

Caused by: net.sf.jsqlparser.parser.ParseException: Encountered " "TABLE" "table "" at line 1, column 26.
Was expecting one of:
    "DO" ...

changing it from table to something else parses just fine...

**Comment by wumpz** [comment]
I will look into it. Seems as if relobjname needs another keyword.
