### ISSUE TITLE
Error parsing expression inside CASE

### ISSUE THREAD

**Issue by donshop11** [JSQLParser/JSqlParser#262]
the following query is parsed successful:

SELECT X1, (CASE WHEN T.ID IS NULL THEN CASE P.WEIGHT
        WHEN 0 THEN NULL  ELSE P.WEIGHT END 
                ELSE SUM(T.QTY)  END) as W
FROM A
LEFT  JOIN T ON T.ID = ? 
RIGHT JOIN P ON P.ID = ?

but when adding an expression to the case, it gives an error:

SELECT X1, (CASE WHEN T.ID IS NULL THEN CASE P.WEIGHT*SUM(T.QTY) 
        WHEN 0 THEN NULL  ELSE P.WEIGHT END 
                ELSE SUM(T.QTY)  END) as W
FROM A
LEFT  JOIN T ON T.ID = ? 
RIGHT JOIN P ON P.ID = ?

Caused by: net.sf.jsqlparser.parser.ParseException: Encountered " "(" "( "" at line 1, column 11.

if we remove the '(' and ')' from the CASE we get:

Caused by: net.sf.jsqlparser.parser.ParseException: Encountered " "_" "_ "" at line 1, column 52.

**Comment by donshop11** [comment]
any idea?

**Comment by wumpz** [comment]
Looks like case dies not accept multiplicative expressions but only Primary expression.

**Comment by wumpz** [comment]
That is indeed the case:

```
<K_CASE>
	(
    	    ( clause=WhenThenSearchCondition() { whenClauses.add(clause); } )+
             [<K_ELSE> elseExp=SimpleExpression()]
		|
		    switchExp=PrimaryExpression()
             ( clause=WhenThenValue() { whenClauses.add(clause); } )*
             [<K_ELSE> elseExp=SimpleExpression()]
	)
    <K_END>
```

**Comment by wumpz** [comment]
A first solution should be to put your expression in parenthesis. 

`( P.WEIGHT*SUM(T.QTY) )`

**Comment by donshop11** [comment]
unfortunately this is not an option for me, since it is a pre-canned application.
looking forward for a fix. thanks!
