### ISSUE TITLE
Issue with SimpleNode

### ISSUE THREAD

**Issue by devWaleed** [JSQLParser/JSqlParser#263]
I am trying to use this and I get errors. Netbeans can't resolve for class SimpleNode.

**Comment by wumpz** [comment]
Could you give a concrete example?

**Comment by FlorianPer** [comment]
Hello,

devWaleed has most likely taken the source of the project without looking a the dependency on other libraries. As soon you use maven with the pom.xml provided along with the project, the dependencies resolution is solved and there is no more issue with the class SimpleNode.

Thanks and regards,

Florian
