### ISSUE TITLE
Parsing With statements

### ISSUE THREAD

**Issue by devWaleed** [JSQLParser/JSqlParser#264]
Is it possible to parse a query starting with 'WITH' clause?

Like:

with cross_items as ...

**Comment by mlkammer** [comment]
I believe a WITH clause like above is not standard SQL, but supported by at least Oracle and SQLServer. See:
- [http://www.brighthub.com/internet/web-development/articles/91893.aspx]
- [https://msdn.microsoft.com/en-us/library/ms175972.aspx]

It looks like JSQLParser does not have a problem with it (I am using version 0.9.4). The following statement parses just fine:
`WITH MySubQuery AS (SELECT Col1, Col2 FROM MyTable) SELECT * FROM MySubQuery`

The following also parses correctly and saves you from using non-standard SQL:
`SELECT MySubQuery.* FROM (SELECT Col1, Col2 FROM MyTable) AS MySubQuery`

**Comment by devWaleed** [comment]
I am having some problems with the following: http://pastebin.com/ryhU1Gc5

**Comment by mlkammer** [comment]
I see that it's a large file containing multiple statements separated by semicolons. Have you tried breaking that down into separate statements and then parsing each one individually? I'd try that first.

**Comment by mujiqadri** [comment]
It's probably not the with statement but "x" operators you have which look like a cross product between queries which might be a problem. Remove those and test

**Comment by wumpz** [comment]
**WITH ** statements are supported. As **mujiqadri** mentioned this 'x' operator is not supported by JSqlParser. Therefore the first thing to try is a query without it.

**Comment by wumpz** [comment]
Could we close this issue?
