### ISSUE TITLE
Error with "WITH" clause

### ISSUE THREAD

**Issue by ghaffar-mallah** [JSQLParser/JSqlParser#265]
I have a query and i am trying to parse it using JSQLParser. Every time i try to execute the code it throws below error.

Exception in thread "main" net.sf.jsqlparser.JSQLParserException
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:54)
	at jsqldemo.JSQLDEMO.main(JSQLDEMO.java:13)
Caused by: net.sf.jsqlparser.parser.ParseException: Encountered " "WITH" "with "" at line 102, column 1.
Was expecting:
    <EOF> 
    
	at net.sf.jsqlparser.parser.CCJSqlParser.generateParseException(CCJSqlParser.java:14039)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_consume_token(CCJSqlParser.java:13895)
	at net.sf.jsqlparser.parser.CCJSqlParser.Statement(CCJSqlParser.java:78)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:52)
	... 1 more
Caused by:
net.sf.jsqlparser.parser.ParseException: Encountered " "WITH" "with "" at line 102, column 1.
Was expecting:
    <EOF> 
    
	at net.sf.jsqlparser.parser.CCJSqlParser.generateParseException(CCJSqlParser.java:14039)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_consume_token(CCJSqlParser.java:13895)
	at net.sf.jsqlparser.parser.CCJSqlParser.Statement(CCJSqlParser.java:78)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:52)
	at jsqldemo.JSQLDEMO.main(JSQLDEMO.java:13)
C:\Users\Ghaffar\AppData\Local\NetBeans\Cache\8.1\executor-snippets\run.xml:53: Java returned: 1

**This is the query i am trying to parse:**

with  cross_items as
 (select i_item_sk ss_item_sk
 from item,
 (select iss.i_brand_id brand_id
     ,iss.i_class_id class_id
     ,iss.i_category_id category_id
 from store_sales
     ,item iss
     ,date_dim d1
 where ss_item_sk = iss.i_item_sk
   and ss_sold_date_sk = d1.d_date_sk
   and d1.d_year between 1999 AND 1999 + 2
 intersect 
 select ics.i_brand_id
     ,ics.i_class_id
     ,ics.i_category_id
 from catalog_sales
     ,item ics
     ,date_dim d2
 where cs_item_sk = ics.i_item_sk
   and cs_sold_date_sk = d2.d_date_sk
   and d2.d_year between 1999 AND 1999 + 2
 intersect
 select iws.i_brand_id
     ,iws.i_class_id
     ,iws.i_category_id
 from web_sales
     ,item iws
     ,date_dim d3
 where ws_item_sk = iws.i_item_sk
   and ws_sold_date_sk = d3.d_date_sk
   and d3.d_year between 1999 AND 1999 + 2) x
 where i_brand_id = brand_id
      and i_class_id = class_id
      and i_category_id = category_id
),
 avg_sales as
 (select avg(quantity*list_price) average_sales
  from (select ss_quantity quantity
             ,ss_list_price list_price
       from store_sales
           ,date_dim
       where ss_sold_date_sk = d_date_sk
         and d_year between 1999 and 2001 
       union all 
       select cs_quantity quantity 
             ,cs_list_price list_price
       from catalog_sales
           ,date_dim
       where cs_sold_date_sk = d_date_sk
         and d_year between 1998 and 1998 + 2 
       union all
       select ws_quantity quantity
             ,ws_list_price list_price
       from web_sales
           ,date_dim
       where ws_sold_date_sk = d_date_sk
         and d_year between 1998 and 1998 + 2) x)
  select  channel, i_brand_id,i_class_id,i_category_id,sum(sales), sum(number_sales)
 from(
       select 'store' channel, i_brand_id,i_class_id
             ,i_category_id,sum(ss_quantity*ss_list_price) sales
             , count(*) number_sales
       from store_sales
           ,item
           ,date_dim
       where ss_item_sk in (select ss_item_sk from cross_items)
         and ss_item_sk = i_item_sk
         and ss_sold_date_sk = d_date_sk
         and d_year = 1998+2 
         and d_moy = 11
       group by i_brand_id,i_class_id,i_category_id
       having sum(ss_quantity*ss_list_price) > (select average_sales from avg_sales)
       union all
       select 'catalog' channel, i_brand_id,i_class_id,i_category_id, sum(cs_quantity*cs_list_price) sales, count(*) number_sales
       from catalog_sales
           ,item
           ,date_dim
       where cs_item_sk in (select ss_item_sk from cross_items)
         and cs_item_sk = i_item_sk
         and cs_sold_date_sk = d_date_sk
         and d_year = 1998+2 
         and d_moy = 11
       group by i_brand_id,i_class_id,i_category_id
       having sum(cs_quantity*cs_list_price) > (select average_sales from avg_sales)
       union all
       select 'web' channel, i_brand_id,i_class_id,i_category_id, sum(ws_quantity*ws_list_price) sales , count(*) number_sales
       from web_sales
           ,item
           ,date_dim
       where ws_item_sk in (select ss_item_sk from cross_items)
         and ws_item_sk = i_item_sk
         and ws_sold_date_sk = d_date_sk
         and d_year = 1998+2
         and d_moy = 11
       group by i_brand_id,i_class_id,i_category_id
       having sum(ws_quantity*ws_list_price) > (select average_sales from avg_sales)
 ) y
 group by rollup (channel, i_brand_id,i_class_id,i_category_id)
 order by channel,i_brand_id,i_class_id,i_category_id
 limit 100;
with  cross_items as
 (select i_item_sk ss_item_sk
 from item,
 (select iss.i_brand_id brand_id
     ,iss.i_class_id class_id
     ,iss.i_category_id category_id
 from store_sales
     ,item iss
     ,date_dim d1
 where ss_item_sk = iss.i_item_sk
   and ss_sold_date_sk = d1.d_date_sk
   and d1.d_year between 1999 AND 1999 + 2
 intersect
 select ics.i_brand_id
     ,ics.i_class_id
     ,ics.i_category_id
 from catalog_sales
     ,item ics
     ,date_dim d2
 where cs_item_sk = ics.i_item_sk
   and cs_sold_date_sk = d2.d_date_sk
   and d2.d_year between 1999 AND 1999 + 2
 intersect
 select iws.i_brand_id
     ,iws.i_class_id
     ,iws.i_category_id
 from web_sales
     ,item iws
     ,date_dim d3
 where ws_item_sk = iws.i_item_sk
   and ws_sold_date_sk = d3.d_date_sk
   and d3.d_year between 1999 AND 1999 + 2) x
 where i_brand_id = brand_id
      and i_class_id = class_id
      and i_category_id = category_id
),
 avg_sales as
(select avg(quantity*list_price) average_sales
  from (select ss_quantity quantity
             ,ss_list_price list_price
       from store_sales
           ,date_dim
       where ss_sold_date_sk = d_date_sk
         and d_year between 1998 and 1998 + 2
       union all
       select cs_quantity quantity
             ,cs_list_price list_price
       from catalog_sales
           ,date_dim
       where cs_sold_date_sk = d_date_sk
         and d_year between 1998 and 1998 + 2
       union all
       select ws_quantity quantity
             ,ws_list_price list_price
       from web_sales
           ,date_dim
       where ws_sold_date_sk = d_date_sk
         and d_year between 1998 and 1998 + 2) x)
  select  * from
 (select 'store' channel, i_brand_id,i_class_id,i_category_id
        ,sum(ss_quantity*ss_list_price) sales, count(*) number_sales
 from store_sales 
     ,item
     ,date_dim
 where ss_item_sk in (select ss_item_sk from cross_items)
   and ss_item_sk = i_item_sk
   and ss_sold_date_sk = d_date_sk
   and d_week_seq = (select d_week_seq
                     from date_dim
                     where d_year = 1998 + 1
                       and d_moy = 12
                       and d_dom = 16)
 group by i_brand_id,i_class_id,i_category_id
 having sum(ss_quantity*ss_list_price) > (select average_sales from avg_sales)) this_year,
 (select 'store' channel, i_brand_id,i_class_id
        ,i_category_id, sum(ss_quantity*ss_list_price) sales, count(*) number_sales
 from store_sales
     ,item
     ,date_dim
 where ss_item_sk in (select ss_item_sk from cross_items)
   and ss_item_sk = i_item_sk
   and ss_sold_date_sk = d_date_sk
   and d_week_seq = (select d_week_seq
                     from date_dim
                     where d_year = 1998
                       and d_moy = 12
                       and d_dom = 16)
 group by i_brand_id,i_class_id,i_category_id
 having sum(ss_quantity*ss_list_price) > (select average_sales from avg_sales)) last_year
 where this_year.i_brand_id= last_year.i_brand_id
   and this_year.i_class_id = last_year.i_class_id
   and this_year.i_category_id = last_year.i_category_id
 order by this_year.channel, this_year.i_brand_id, this_year.i_class_id, this_year.i_category_id
 limit 100;

**Here is my code:**

        Statement statement = CCJSqlParserUtil.parse("with cross_items as\n" +
" (select i_item_sk ss_item_sk\n" +
" from item,\n" +
" (select iss.i_brand_id brand_id\n" +
"     ,iss.i_class_id class_id\n" +
"     ,iss.i_category_id category_id\n" +
" from store_sales\n" +
"     ,item iss\n" +
"     ,date_dim d1\n" +
" where ss_item_sk = iss.i_item_sk\n" +
"   and ss_sold_date_sk = d1.d_date_sk\n" +
"   and d1.d_year between 1999 AND 1999 + 2\n" +
" intersect \n" +
" select ics.i_brand_id\n" +
"     ,ics.i_class_id\n" +
"     ,ics.i_category_id\n" +
" from catalog_sales\n" +
"     ,item ics\n" +
"     ,date_dim d2\n" +
" where cs_item_sk = ics.i_item_sk\n" +
"   and cs_sold_date_sk = d2.d_date_sk\n" +
"   and d2.d_year between 1999 AND 1999 + 2\n" +
" intersect\n" +
" select iws.i_brand_id\n" +
"     ,iws.i_class_id\n" +
"     ,iws.i_category_id\n" +
" from web_sales\n" +
"     ,item iws\n" +
"     ,date_dim d3\n" +
" where ws_item_sk = iws.i_item_sk\n" +
"   and ws_sold_date_sk = d3.d_date_sk\n" +
"   and d3.d_year between 1999 AND 1999 + 2) x\n" +
" where i_brand_id = brand_id\n" +
"      and i_class_id = class_id\n" +
"      and i_category_id = category_id\n" +
"),\n" +
" avg_sales as\n" +
" (select avg(quantity*list_price) average_sales\n" +
"  from (select ss_quantity quantity\n" +
"             ,ss_list_price list_price\n" +
"       from store_sales\n" +
"           ,date_dim\n" +
"       where ss_sold_date_sk = d_date_sk\n" +
"         and d_year between 1999 and 2001 \n" +
"       union all \n" +
"       select cs_quantity quantity \n" +
"             ,cs_list_price list_price\n" +
"       from catalog_sales\n" +
"           ,date_dim\n" +
"       where cs_sold_date_sk = d_date_sk\n" +
"         and d_year between 1998 and 1998 + 2 \n" +
"       union all\n" +
"       select ws_quantity quantity\n" +
"             ,ws_list_price list_price\n" +
"       from web_sales\n" +
"           ,date_dim\n" +
"       where ws_sold_date_sk = d_date_sk\n" +
"         and d_year between 1998 and 1998 + 2) x)\n" +
"  select  channel, i_brand_id,i_class_id,i_category_id,sum(sales), sum(number_sales)\n" +
" from(\n" +
"       select 'store' channel, i_brand_id,i_class_id\n" +
"             ,i_category_id,sum(ss_quantity*ss_list_price) sales\n" +
"             , count(*) number_sales\n" +
"       from store_sales\n" +
"           ,item\n" +
"           ,date_dim\n" +
"       where ss_item_sk in (select ss_item_sk from cross_items)\n" +
"         and ss_item_sk = i_item_sk\n" +
"         and ss_sold_date_sk = d_date_sk\n" +
"         and d_year = 1998+2 \n" +
"         and d_moy = 11\n" +
"       group by i_brand_id,i_class_id,i_category_id\n" +
"       having sum(ss_quantity*ss_list_price) > (select average_sales from avg_sales)\n" +
"       union all\n" +
"       select 'catalog' channel, i_brand_id,i_class_id,i_category_id, sum(cs_quantity*cs_list_price) sales, count(*) number_sales\n" +
"       from catalog_sales\n" +
"           ,item\n" +
"           ,date_dim\n" +
"       where cs_item_sk in (select ss_item_sk from cross_items)\n" +
"         and cs_item_sk = i_item_sk\n" +
"         and cs_sold_date_sk = d_date_sk\n" +
"         and d_year = 1998+2 \n" +
"         and d_moy = 11\n" +
"       group by i_brand_id,i_class_id,i_category_id\n" +
"       having sum(cs_quantity*cs_list_price) > (select average_sales from avg_sales)\n" +
"       union all\n" +
"       select 'web' channel, i_brand_id,i_class_id,i_category_id, sum(ws_quantity*ws_list_price) sales , count(*) number_sales\n" +
"       from web_sales\n" +
"           ,item\n" +
"           ,date_dim\n" +
"       where ws_item_sk in (select ss_item_sk from cross_items)\n" +
"         and ws_item_sk = i_item_sk\n" +
"         and ws_sold_date_sk = d_date_sk\n" +
"         and d_year = 1998+2\n" +
"         and d_moy = 11\n" +
"       group by i_brand_id,i_class_id,i_category_id\n" +
"       having sum(ws_quantity*ws_list_price) > (select average_sales from avg_sales)\n" +
" ) y\n" +
" group by rollup (channel, i_brand_id,i_class_id,i_category_id)\n" +
" order by channel,i_brand_id,i_class_id,i_category_id\n" +
" limit 100;\n" +
"with  cross_items as\n" +
" (select i_item_sk ss_item_sk\n" +
" from item,\n" +
" (select iss.i_brand_id brand_id\n" +
"     ,iss.i_class_id class_id\n" +
"     ,iss.i_category_id category_id\n" +
" from store_sales\n" +
"     ,item iss\n" +
"     ,date_dim d1\n" +
" where ss_item_sk = iss.i_item_sk\n" +
"   and ss_sold_date_sk = d1.d_date_sk\n" +
"   and d1.d_year between 1999 AND 1999 + 2\n" +
" intersect\n" +
" select ics.i_brand_id\n" +
"     ,ics.i_class_id\n" +
"     ,ics.i_category_id\n" +
" from catalog_sales\n" +
"     ,item ics\n" +
"     ,date_dim d2\n" +
" where cs_item_sk = ics.i_item_sk\n" +
"   and cs_sold_date_sk = d2.d_date_sk\n" +
"   and d2.d_year between 1999 AND 1999 + 2\n" +
" intersect\n" +
" select iws.i_brand_id\n" +
"     ,iws.i_class_id\n" +
"     ,iws.i_category_id\n" +
" from web_sales\n" +
"     ,item iws\n" +
"     ,date_dim d3\n" +
" where ws_item_sk = iws.i_item_sk\n" +
"   and ws_sold_date_sk = d3.d_date_sk\n" +
"   and d3.d_year between 1999 AND 1999 + 2) x\n" +
" where i_brand_id = brand_id\n" +
"      and i_class_id = class_id\n" +
"      and i_category_id = category_id\n" +
"),\n" +
" avg_sales as\n" +
"(select avg(quantity*list_price) average_sales\n" +
"  from (select ss_quantity quantity\n" +
"             ,ss_list_price list_price\n" +
"       from store_sales\n" +
"           ,date_dim\n" +
"       where ss_sold_date_sk = d_date_sk\n" +
"         and d_year between 1998 and 1998 + 2\n" +
"       union all\n" +
"       select cs_quantity quantity\n" +
"             ,cs_list_price list_price\n" +
"       from catalog_sales\n" +
"           ,date_dim\n" +
"       where cs_sold_date_sk = d_date_sk\n" +
"         and d_year between 1998 and 1998 + 2\n" +
"       union all\n" +
"       select ws_quantity quantity\n" +
"             ,ws_list_price list_price\n" +
"       from web_sales\n" +
"           ,date_dim\n" +
"       where ws_sold_date_sk = d_date_sk\n" +
"         and d_year between 1998 and 1998 + 2) x)\n" +
"  select  * from\n" +
" (select 'store' channel, i_brand_id,i_class_id,i_category_id\n" +
"        ,sum(ss_quantity*ss_list_price) sales, count(*) number_sales\n" +
" from store_sales \n" +
"     ,item\n" +
"     ,date_dim\n" +
" where ss_item_sk in (select ss_item_sk from cross_items)\n" +
"   and ss_item_sk = i_item_sk\n" +
"   and ss_sold_date_sk = d_date_sk\n" +
"   and d_week_seq = (select d_week_seq\n" +
"                     from date_dim\n" +
"                     where d_year = 1998 + 1\n" +
"                       and d_moy = 12\n" +
"                       and d_dom = 16)\n" +
" group by i_brand_id,i_class_id,i_category_id\n" +
" having sum(ss_quantity*ss_list_price) > (select average_sales from avg_sales)) this_year,\n" +
" (select 'store' channel, i_brand_id,i_class_id\n" +
"        ,i_category_id, sum(ss_quantity*ss_list_price) sales, count(*) number_sales\n" +
" from store_sales\n" +
"     ,item\n" +
"     ,date_dim\n" +
" where ss_item_sk in (select ss_item_sk from cross_items)\n" +
"   and ss_item_sk = i_item_sk\n" +
"   and ss_sold_date_sk = d_date_sk\n" +
"   and d_week_seq = (select d_week_seq\n" +
"                     from date_dim\n" +
"                     where d_year = 1998\n" +
"                       and d_moy = 12\n" +
"                       and d_dom = 16)\n" +
" group by i_brand_id,i_class_id,i_category_id\n" +
" having sum(ss_quantity*ss_list_price) > (select average_sales from avg_sales)) last_year\n" +
" where this_year.i_brand_id= last_year.i_brand_id\n" +
"   and this_year.i_class_id = last_year.i_class_id\n" +
"   and this_year.i_category_id = last_year.i_category_id\n" +
" order by this_year.channel, this_year.i_brand_id, this_year.i_class_id, this_year.i_category_id\n" +
" limit 100;");
        
        Select selectStatement = (Select) statement;
        TablesNamesFinder tablesNamesFinder = new TablesNamesFinder();
        List<String> tableList = tablesNamesFinder.getTableList(selectStatement);

        for(String table : tableList){
            System.out.println(table);
        }

**Comment by wumpz** [comment]
I was able to parse your "statement" successfully. Besides your statement is in fact two statements. Therefore you have to use:
~~~
 Statements stmts = CCJSqlParserUtil.parseStatements(sqls);
~~~
I included a test for your statement as well.
