### ISSUE TITLE
Error while parsing variable named 'top'

### ISSUE THREAD

**Issue by mlkammer** [JSQLParser/JSqlParser#266]
It seems that JSqlParser cannot handle variables that are named 'top'.
The following gives a ParseException: `SELECT @top`
The case of the variable name does not matter: `SELECT @Top` and `SELECT @TOP` also fail.

But if 'top' is only a part of the variable name, it is successfully parsed:
`SELECT @topVar`
So now we are using this as a workaround.

The motivation for this use case is as follows: we have an application in which the user can control the number of displayed rows, and this should directly influence the underlying query executed in the database like this: `SELECT TOP @topVar * FROM MyTable` (which should now be supported because of the fix for #243).

(I do not know if it adds some useful information, but using 'top' as an alias name does not give the same problems.
The following parses just fine: `SELECT 1 AS [top]`
The following fails, but that's understandable since the alias is not double-quoted or delimited: `SELECT 1 AS top`)

I am using JSqlParser version 0.9.5.

**Comment by wumpz** [comment]
already solved, but I don't know when

**Comment by mlkammer** [comment]
Great, thank you!
