### ISSUE TITLE
Support for Unicode string prefix in SQL Server

### ISSUE THREAD

**Issue by mlkammer** [JSQLParser/JSqlParser#267]
Microsoft SQLServer requires that you prefix Unicode strings with the 'N' character like this:
`SELECT N'SomeUnicodeString'`
But this gives a ParseException with JSqlParser.

It would be great if JSqlParser also supported the Unicode prefix.
Maybe by adding a method `isMarkedAsUnicode` to `net.sf.jsqlparser.expression.StringValue`?

More about this subject can be found here:
- https://support.microsoft.com/nl-nl/kb/239530
- http://programmers.stackexchange.com/questions/155859/why-do-we-need-to-put-n-before-strings-in-microsoft-sql-server

There are no other database systems I know of that need the N prefix, but unfortunately we are using SQLServer.

I am using JSqlParser version 0.9.5.

**Comment by wumpz** [comment]
"Unfortunately we are using SQLServer" ;)

Maybe one could introduce more than this prefix. Using postgresql there is a `E'test'` for an escaped string.

**Comment by mlkammer** [comment]
Thanks for the quick response, Tobias.
We are not that unhappy with SQLServer, just with this 'feature' ;-)

You are right of course, did not know about that feature in PostgreSQL!

Maybe `net.sf.jsqlparser.expression.StringValue` could have a `getMark` method which returns an enum constant, such as `StringValueMark.UNICODE` or `StringValueMark.ESCAPED`?
This would remain relatively generic. Or do you think that the mark should rather be just a `String` for greater flexibility/generality?

**Comment by thomaszbz** [comment]
@freepath-it provided a patch in #438 (WIP)

**Comment by wumpz** [comment]
@thomaszbz he calls itself a potential PR since tests are failing.

**Comment by wumpz** [comment]
finally included

**Comment by mlkammer** [comment]
Great work, Tobias!
