### ISSUE TITLE
Can't parse type in Oracle's varchar2

### ISSUE THREAD

**Issue by vincent-fuchs** [JSQLParser/JSqlParser#273]
Hi,

Using v0.9.5, parsing this valid Oracle statement, I'm getting an error : 

```
CREATE TABLE IF NOT EXISTS "TABLE_OK"  ("SOME_FIELD"    VARCHAR2(256 BYTE));
```

error : 

```
Caused by: net.sf.jsqlparser.parser.ParseException: Encountered " <S_IDENTIFIER> "BYTE "" at line   1, column 70.
Was expecting one of:
<S_LONG> ...
<S_CHAR_LITERAL> ...
```

If I don't specify BYTE, it works. 

Note : both BYTE and CHAR should be accepted : https://docs.oracle.com/cd/B28359_01/server.111/b28318/datatype.htm#i1835

**Comment by wumpz** [comment]
took a long way, sorry, but now it is fixed
