### ISSUE TITLE
Not able to use unique key word 

### ISSUE THREAD

**Issue by vkesav** [JSQLParser/JSqlParser#277]
Hi i am trying to parse this sql
"select unique * from ABCD"

I am getting below exception,

net.sf.jsqlparser.JSQLParserException
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:54)
	at parser.JSQL_Parser.App.getTables(App.java:31)
	at parser.JSQL_Parser.App.main(App.java:20)
Caused by: net.sf.jsqlparser.parser.ParseException: Encountered " "UNIQUE" "unique "" at line 1, column 8.
Was expecting one of:
    "DO" ...
    "ALL" ...
    "ANY" ...
    "KEY" ...

 Is UNIQUE keyword not supported?

**Comment by wumpz** [comment]
This one is easy to tackle, since a lot of keywords are already recognized as identifiers. Unique simply has to be included into this list. I will look into it.

**Comment by wumpz** [comment]
After reading your issue the second time, it is not about including **unique** as a keyword. Your statement is not recognized by JSqlParser but 

`select distinct * from abc `

is.

**Comment by vkesav** [comment]
Yeah, **distinct** is working, but I think unique should also work.

"select unique * from ABCD" is a valid sql statement.

**Comment by wumpz** [comment]
fixed by another issue
