### ISSUE TITLE
SQL datetime literals not recognized

### ISSUE THREAD

**Issue by whelmberger** [JSQLParser/JSqlParser#278]
Hi, 

I'm facing parsing errors when using a SQL standard timestamp literal: 

`SELECT * FROM tab1 WHERE a > TIMESTAMP'2004-04-30 04:05:34.56'`

results in 
```
Encountered " <S_CHAR_LITERAL> "\'2004-04-30 04:05:34.56\' "" at line 1, column 39.
Was expecting one of:
    <EOF> 
    "FOR" ...
    "GROUP" ...
[...]
```
The same is true for 
TIME'04:05:34.56' 
and
DATE'2004-04-30'
Note: Whitespace is allowed before TIME/DATE/TIMESTAMP and the opening single-quote.

See [https://books.google.de/books?id=8y823V4-5ioC&lpg=PA702&ots=Yp7yautITZ&dq=sql%20standard%20%22timestamp%20literal%22&pg=PA702#v=onepage&q=sql%20standard%20%22timestamp%20literal%22&f=false] for a very brief overview of datetime literals in Standard SQL.

**Comment by wumpz** [comment]
could you check it?
