### ISSUE TITLE
Issue parsing Merge

### ISSUE THREAD

**Issue by mnadeem** [JSQLParser/JSqlParser#279]
The following test fails, 

private static final String MERGE_USING_TABLE = "MERGE INTO employees e " +
	" USING hr_records h " +
    " ON (e.id = h.emp_id)"+
    " WHEN MATCHED THEN"+
    " UPDATE SET e.address = h.address"+
    " WHEN NOT MATCHED THEN"+
    " INSERT (id, address)"+
    " VALUES (h.emp_id, h.address);";

	@Test
	public void test() throws JSQLParserException {
		
		Statement statement = CCJSqlParserUtil.parse(MERGE_USING_TABLE);
		
		Merge mergeStatement = (Merge) statement;
		
	}

If we change the SQL, i.e, put hr_records within parenthesis then it works, ideally parenthesis should be required only for subqueries, further if we put parantheis, the sql would seize to execute. appreciate if grammer can be changed accordingly. 

private static final String MERGE_USING_TABLE = "MERGE INTO employees e " +
	" USING (hr_records) h " +
    " ON (e.id = h.emp_id)"+
    " WHEN MATCHED THEN"+
    " UPDATE SET e.address = h.address"+
    " WHEN NOT MATCHED THEN"+
    " INSERT (id, address)"+
    " VALUES (h.emp_id, h.address);";

**Comment by wumpz** [comment]
Which version of JSqlParser do you use? At a first glance at least the actual snapshot should already accept your SQL.

**Comment by mnadeem** [comment]
0.9.5, 

I think 0.9.6 should fix the issue
