### ISSUE TITLE
subselect in function is not recogniezed!!

### ISSUE THREAD

**Issue by whisler83** [JSQLParser/JSqlParser#284]
SELECT NVL( (SELECT 1 FROM DUAL), 1) AS A
FROM TEST1

In this case, tablesnamesfinder can find just table TEST1.
Table DUAL is not found.
In where, the same situation is occurring.....

please help me.

Thanks in advance.

**Comment by whisler83** [comment]
It's the same things in other functions(decode, to_number...).ㅠㅠ

**Comment by wumpz** [comment]
Tested your first statement and it is parsed perfectly well using JSqlParser 0.9.6-SNAPSHOT. Dont know when this change happened.

**Comment by wumpz** [comment]
Oops. You are refering to table names finder and not to parse errors. Sorry my fault.

**Comment by whisler83** [comment]
I refered to tablesnamesfonder class in jsqlparser 0.9.6 snapshot version..Did I use that class in wrong usage? I hope it was just my fault..OTL..

**Comment by wumpz** [comment]
No. The inner scan for functions isn't yet implenented. Should be easy to do. I will look into it. Tobias

**Comment by whisler83** [comment]
Thanks so much, @wumpz!!

**Comment by wumpz** [comment]
your welcome and thx for using and supporting JSqlParser   :)
