### ISSUE TITLE
ExpressionVisitor.visit(CustomExpression)

### ISSUE THREAD

**Issue by jesperpedersen** [JSQLParser/JSqlParser#287]
It would be nice to have a
```java
void visit(CustomExpression ce)
```
in ```ExpressionVisitor``` such that custom implementations could be visited as part of the processing.

Useful for
```java
List<Expression> newList = new ArrayList<>();
if (expression instanceof JdbcParameter)
   newList.add(new MyCustomExpression());
else
  newList.add(expression);

update.setExpressions(newList); 
```

**Comment by wumpz** [comment]
I am not sure if I understand you. You want one additional method that will only be called if one uses your custom class? What is the difference in overriding e.g. Expression visitors Expression visit method? I don't see any advantage.

**Comment by jesperpedersen** [comment]
The Update.getColumns() and Update.getExpressions() isn't visited in a "pair" so in
```
UPDATE MY_TABLE SET COL1 = ?, COL2 = ?, ...
```
the visit(JdbcParameter) doesn't have a visit(Column) before it. One can fix that with keeping track of the number of parameters processed and manually getting the correct column.

The ```WHERE``` is processed correctly.

Using custom deparser's is likely a better solution, so I think we can close this.

**Comment by wumpz** [comment]
After digging deeper I recognized, that the Update deparser does not use the ExpressionVisitor, to work on the columns. Is that the problem you described as "not visited in pair"? 

That is definitly a visitor problem and therefore a bug that should be resolved.

**Comment by jesperpedersen** [comment]
Could be, Update.getExpressions() and Update.getWhere() are visited.

https://github.com/jesperpedersen/postgres-tools/blob/master/QueryAnalyzer/QueryAnalyzer.java#L365-L376

because

https://github.com/jesperpedersen/postgres-tools/blob/master/QueryAnalyzer/QueryAnalyzer.java#L354

isn't called until Update.getWhere()

**Comment by wumpz** [comment]
Could you check it. I corrected the visitor calling for update statements. If you find similar problems for other kind of statements, please file an issue.

**Comment by jesperpedersen** [comment]
:+1:
