### ISSUE TITLE
Table with partition clause is not supperted.

### ISSUE THREAD

**Issue by whisler83** [JSQLParser/JSqlParser#289]
SELECT COUNT(1) 
FROM TEST PARTITION (PT_2016)

This sql could be parsed by Jsqlparser.

What's the problem? Is not supported yet?
Or it was my mistake?

Thanks, your replies.

**Comment by wumpz** [comment]
Sorry I never had to use within a partition query. So I can not say if this is indeed a valid SQL. Nevertheless JSqlParser does not support this syntax.

**Comment by whisler83** [comment]
Okay, I got it. Anyway, thanks for your faithful answer always, wumpz. ^^

**Comment by AnEmortalKid** [comment]
@wumpz  I think this can be closed, this parses at least even if it is awkward

![image](https://user-images.githubusercontent.com/3474369/85960719-60821b00-b96b-11ea-828f-0b7f665d3dbd.png)
