### ISSUE TITLE
Please build JAR with OSGi support

### ISSUE THREAD

**Issue by lichtin** [JSQLParser/JSqlParser#290]
It'd be great to build the JAR so its MANIFEST is OSGi-enhanced.
In case of building with Maven it's done by adding a build plugin:

            <plugin>
                <groupId>org.apache.felix</groupId>
                <artifactId>maven-bundle-plugin</artifactId>
                <extensions>true</extensions>
            </plugin>

and by specifying the packaging:

    <packaging>bundle</packaging>

**Comment by wumpz** [comment]
I have never done that. For normal JAR usage this should change nothing, right?

**Comment by lichtin** [comment]
Yes, it's transparent for users of the JAR.
The effect of the plugin is that a few lines (important for OSGi) are added to the MANIFEST.MF

**Comment by wumpz** [comment]
could you check the latest snapshot
