### ISSUE TITLE
CREATE GLOBAL TEMPORARY TABLE support

### ISSUE THREAD

**Issue by mnadeem** [JSQLParser/JSqlParser#293]
HI,

I see that https://github.com/JSQLParser/JSqlParser/blob/master/src/main/jjtree/net/sf/jsqlparser/parser/JSqlParserCC.jjt#L2593

has some support for global temporary tables which is commented, uncommenting it breaks lots of things

As of now I just want to be able to parse statements like the following (without needing know if it is global temporary or not)
CREATE GLOBAL TEMPORARY TABLE T1 (PROCESSID VARCHAR (32))

Appreciate if you could provide some help(code snippet, which I could just copy/paste and do the build) would be greatly appreciated.

**Comment by wumpz** [comment]
This line you described was not needed. The problem was a problematic lookup.
