### ISSUE TITLE
TablesNamesFinder Merge Support

### ISSUE THREAD

**Issue by mnadeem** [JSQLParser/JSqlParser#296]
Appreciate if Merge is supported for    TablesNamesFinder , here is the code I have added to TablesNamesFinder  

    public List<String> getTableList(Merge merge) {
		init();
		merge.accept(this);
		if (merge.getUsingTable() != null) {
			merge.getUsingTable().accept(this);
		} else if (merge.getUsingSelect() != null) {
			merge.getUsingSelect().accept((FromItemVisitor) this);
		}

		return tables;
	}

    
    @Override
    public void visit(Merge merge) {
    	tables.add(merge.getTable().getName());
    }

Here is the test cases      

    @Test
	public void testGetTableListForMerge() throws Exception {
		String sql = "MERGE INTO employees e  USING hr_records h  ON (e.id = h.emp_id) WHEN MATCHED THEN  UPDATE SET e.address = h.address  WHEN NOT MATCHED THEN    INSERT (id, address) VALUES (h.emp_id, h.address);";
		net.sf.jsqlparser.statement.Statement statement = pm.parse(new StringReader(sql));

		Merge selectStatement = (Merge) statement;
		TablesNamesFinder tablesNamesFinder = new TablesNamesFinder();
		List<String> tableList = tablesNamesFinder.getTableList(selectStatement);
		assertEquals(2, tableList.size());
		assertEquals("employees", (String) tableList.get(0));
		assertEquals("hr_records", (String) tableList.get(1));
	}
     
    @Test
	public void testGetTableListForMergeUsingQuery() throws Exception {
		String sql = "MERGE INTO employees e USING (SELECT * FROM hr_records WHERE start_date > ADD_MONTHS(SYSDATE, -1)) h  ON (e.id = h.emp_id)  WHEN MATCHED THEN  UPDATE SET e.address = h.address WHEN NOT MATCHED THEN INSERT (id, address) VALUES (h.emp_id, h.address)";
		net.sf.jsqlparser.statement.Statement statement = pm.parse(new StringReader(sql));

		Merge selectStatement = (Merge) statement;
		TablesNamesFinder tablesNamesFinder = new TablesNamesFinder();
		List<String> tableList = tablesNamesFinder.getTableList(selectStatement);
		assertEquals(2, tableList.size());
		assertEquals("employees", (String) tableList.get(0));
		assertEquals("hr_records", (String) tableList.get(1));
	}

**Comment by wumpz** [comment]
Next time I would prefer a pull request.
