### ISSUE TITLE
UNIQUE keyword not managed

### ISSUE THREAD

**Issue by benoitbb** [JSQLParser/JSqlParser#299]
Hello,

I have a bug when I try to parse a query with the "**UNIQUE**" keyword. I have the following error :

net.sf.jsqlparser.parser.ParseException: Encountered " "UNIQUE" "UNIQUE "" at line 21, column 16. Was expecting one of: "DO" ...

Can you have a look ?
Thank you.

Best Regards.

**Comment by wumpz** [comment]
Do you have a test sql?

**Comment by benoitbb** [comment]
`SELECT UNIQUE trunc(timez(ludate)+ 8/24) bus_dt, 
j.object j_name , timez(j.starttime) START_TIME , timez(j.endtime) END_TIME FROM TEST_1 j `

**Comment by wumpz** [comment]
I understand. Recently another issue requested this. JSqlParser knows only distinct in this case.

**Comment by benoitbb** [comment]
Ok. It is an oracle query. Is it possible to add this specific '**UNIQUE**' keyword when parsing ? Or Do we have to replace this keyword before parsing the query ?

**Comment by wumpz** [comment]
It is possible. Pullrequests are welcome or want to support JSqlParser in other ways?
