### ISSUE TITLE
Column.getTable() is null

### ISSUE THREAD

**Issue by jesperpedersen** [JSQLParser/JSqlParser#300]
When checking a query (PlainSelect.getWhere()) like
```
SELECT COL2 FROM MY_TABLE WHERE COL1 = ?
```
then ```col1.getTable()``` is null.

Tested against 0.9.6-SNAPHOT (3ccca01bbc85778e01698d02c1fe3bd032e56452)

**Comment by wumpz** [comment]
This is the expected behaviour.

**Comment by wumpz** [comment]
Look here : http://stackoverflow.com/a/37383901/3275788
