### ISSUE TITLE
Failed to parse properly formatted MSQL syntax.

### ISSUE THREAD

**Issue by gir489** [JSQLParser/JSqlParser#301]
I am trying to parse the following SQL select with the SQL parser:

`String stmt = "SELECT CAST((MAX(CAST(IIF(isnumeric(license_no) = 1, license_no, 0) AS INT )) + 2) as varchar) FROM lcps.t_license WHERE profession_id = 60 and license_type = 100 and YEAR(issue_date) % 2 = case when YEAR(issue_date) % 2 = 0 then 0 else 1 end and ISNUMERIC(license_no) = 1";
Statements stmts = CCJSqlParserUtil.parseStatements(stmt);`

The exception is given:

`Caused by: net.sf.jsqlparser.parser.ParseException: Encountered " "(" "( "" at line 1, column 12.
Was expecting one of:
    <EOF> 
    "AS" ...
    "DO" ...
    "ANY" ...
    "KEY" ...
    "PERCENT" ...
    "INTO" ...
    "FROM" ...
    "OPEN" ...
    "WHERE" ...
    "FOR" ...
    "XML" ...
    "GROUP" ...
    "VALUE" ...
    "HAVING" ...
    "VALUES" ...
    "REPLACE" ...
    "TRUNCATE" ...
    "CAST" ...
    "OVER" ...
    "PARTITION" ...
    "EXTRACT" ...
    "MATERIALIZED" ...
    "START" ...
    "CONNECT" ...
    "PRIOR" ...
    "SIBLINGS" ...
    "COLUMN" ...
    "NULLS" ...
    "FIRST" ...
    "LAST" ...
    "ROWS" ...
    "RANGE" ...
    "FOLLOWING" ...
    "ROW" ...
    "SEPARATOR" ...
    "CASCADE" ...
    "NO" ...
    "ACTION" ...
    <S_IDENTIFIER> ...
    <S_QUOTED_IDENTIFIER> ...
    ";" ...
    "," ...
    "+" ...
    "||" ...
    "|" ...
    "&" ...
    "-" ...
    "^" ...
    "::" ...
    "::" ...
    "^" ...
    "+" ...
    "-" ...
    "||" ...
    "|" ...
    "&" ...
    "AS" ...
    <S_IDENTIFIER> ...
    <S_QUOTED_IDENTIFIER> ...
    "CAST" ...
    "DO" ...
    "EXTRACT" ...
    "FIRST" ...
    "FOLLOWING" ...
    "LAST" ...
    "MATERIALIZED" ...
    "NULLS" ...
    "PARTITION" ...
    "RANGE" ...
    "ROW" ...
    "ROWS" ...
    "SIBLINGS" ...
    "VALUE" ...
    "XML" ...
    "COLUMN" ...
    "REPLACE" ...
    "TRUNCATE" ...
    "KEY" ...
    "ANY" ...
    "OPEN" ...
    "OVER" ...
    "VALUES" ...
    "PERCENT" ...
    "PRIOR" ...
    "SEPARATOR" ...
    "NO" ...
    "ACTION" ...
    "CASCADE" ...
    "," ...
    "INTO" ...
    "FROM" ...
    "WHERE" ...
    "START" ...
    "CONNECT" ...
    "GROUP" ...
    "HAVING" ...
    "FOR" ...

```
at net.sf.jsqlparser.parser.CCJSqlParser.generateParseException(CCJSqlParser.java:13996)
at net.sf.jsqlparser.parser.CCJSqlParser.jj_consume_token(CCJSqlParser.java:13852)
at net.sf.jsqlparser.parser.CCJSqlParser.Statements(CCJSqlParser.java:236)
at net.sf.jsqlparser.parser.CCJSqlParserUtil.parseStatements(CCJSqlParserUtil.java:122)
... 1 more
```

Caused by:
net.sf.jsqlparser.parser.ParseException: Encountered " "(" "( "" at line 1, column 12.
Was expecting one of:
    <EOF> 
    "AS" ...
    "DO" ...
    "ANY" ...
    "KEY" ...
    "PERCENT" ...
    "INTO" ...
    "FROM" ...
    "OPEN" ...
    "WHERE" ...
    "FOR" ...
    "XML" ...
    "GROUP" ...
    "VALUE" ...
    "HAVING" ...
    "VALUES" ...
    "REPLACE" ...
    "TRUNCATE" ...
    "CAST" ...
    "OVER" ...
    "PARTITION" ...
    "EXTRACT" ...
    "MATERIALIZED" ...
    "START" ...
    "CONNECT" ...
    "PRIOR" ...
    "SIBLINGS" ...
    "COLUMN" ...
    "NULLS" ...
    "FIRST" ...
    "LAST" ...
    "ROWS" ...
    "RANGE" ...
    "FOLLOWING" ...
    "ROW" ...
    "SEPARATOR" ...
    "CASCADE" ...
    "NO" ...
    "ACTION" ...
    <S_IDENTIFIER> ...
    <S_QUOTED_IDENTIFIER> ...
    ";" ...
    "," ...
    "+" ...
    "||" ...
    "|" ...
    "&" ...
    "-" ...
    "^" ...
    "::" ...
    "::" ...
    "^" ...
    "+" ...
    "-" ...
    "||" ...
    "|" ...
    "&" ...
    "AS" ...
    <S_IDENTIFIER> ...
    <S_QUOTED_IDENTIFIER> ...
    "CAST" ...
    "DO" ...
    "EXTRACT" ...
    "FIRST" ...
    "FOLLOWING" ...
    "LAST" ...
    "MATERIALIZED" ...
    "NULLS" ...
    "PARTITION" ...
    "RANGE" ...
    "ROW" ...
    "ROWS" ...
    "SIBLINGS" ...
    "VALUE" ...
    "XML" ...
    "COLUMN" ...
    "REPLACE" ...
    "TRUNCATE" ...
    "KEY" ...
    "ANY" ...
    "OPEN" ...
    "OVER" ...
    "VALUES" ...
    "PERCENT" ...
    "PRIOR" ...
    "SEPARATOR" ...
    "NO" ...
    "ACTION" ...
    "CASCADE" ...
    "," ...
    "INTO" ...
    "FROM" ...
    "WHERE" ...
    "START" ...
    "CONNECT" ...
    "GROUP" ...
    "HAVING" ...
    "FOR" ...

```
at net.sf.jsqlparser.parser.CCJSqlParser.generateParseException(CCJSqlParser.java:13996)
at net.sf.jsqlparser.parser.CCJSqlParser.jj_consume_token(CCJSqlParser.java:13852)
at net.sf.jsqlparser.parser.CCJSqlParser.Statements(CCJSqlParser.java:236)
at net.sf.jsqlparser.parser.CCJSqlParserUtil.parseStatements(CCJSqlParserUtil.java:122)
at com.sa.v4.business.process.LicenseNumberGenerator.main(LicenseNumberGenerator.java:2462)`
```

But if I run the query in SQL Server Management Studio, I get a return of 30000 from the server.``

**Comment by wumpz** [comment]
If I remember correctly,  there is an open issue regarding if or boolean conditions as function parameters.  That would be my first guess,  why the parse failed. Tobias

**Comment by gir489** [comment]
Do you have a workaround? This is causing problems with a production environment.

**Comment by wumpz** [comment]
At the moment using JSqlParser there is no workaround available. I looked at the parser and found it difficult to build in this kind of parameters the "easy" way. Somehow the parse complexity explodes and the parser got very slow, so not the way to go.

**Comment by wumpz** [comment]
JSqlParser 4.0 parses this.
