### ISSUE TITLE
Can not proccess the ‘PRIMARY KEY ( 字段1 , iii )’ words，how to resolve it

### ISSUE THREAD

**Issue by gaoda1234** [JSQLParser/JSqlParser#302]
CREATE TABLE `back_user` (
	`字段` varchar(20) NOT NULL COMMENT '用户名',
	PRIMARY KEY ( 字段 , iii ),
	KEY bbb (bbb),KEY dd (dd),
	CONSTRAINT back_user_ibfk_1 FOREIGN KEY (字段) REFERENCES `tbug` (CID),
	CONSTRAINT back_user_ibfk_2 FOREIGN KEY (dd) REFERENCES `tdic` (CID)
	) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8 COMMENT='后台用户表';

the first ‘字段’ is processed successful， the second ‘字段’  and the third ‘字段’ can not processed，how to resolve it？

**Comment by gaoda1234** [comment]
use the new version，chinese words are processed，
may be the jar is used wrong，the new jar is download from
https://oss.sonatype.org/content/groups/public/com/github/jsqlparser/jsqlparser/0.9.5-SNAPSHOT/

**Comment by wumpz** [comment]
That is right. I included all UTF8 letter ranges in identifier processing. It was taken from a JavaCC java grammar.  I thought it was complete. If I missed something there please correct my modifications. Cheers Tobias
