### ISSUE TITLE
Absolute start and end position of a tag

### ISSUE THREAD

**Issue by Markus8000** [JSQLParser/JSqlParser#303]
Hello,
I was wondering if we could enhance the parser for the recognition of the absolute position if a statement expands over several lines.

A example could be found here: http://ramkulkarni.com/blog/capturing-absolute-offsets-for-javaccjjtree-tokens/

This involves changes to the following items (not final):
- jjt file
- New class BaseToken
- Move class SimpleCharStream to the main/src/java folder
- Adjust interfaces like Expression, Select, Update, LongValue, etc.

The main driver behind this idea is to write a parser that acts as online validator and is able to visually simplify demanding queries.

Please let me know what your 2 cents are.

Kind Regards,
Markus

**Comment by wumpz** [comment]
Hmm I support already the parse tree construct and the delivery Ast nodes contain absolute position information. Tobias

**Comment by wumpz** [comment]
I was expecting some comments here. Was my information enough to solve the problem? May I close this issue?

**Comment by Markus8000** [comment]
Hi Tobias,

I thought only a limited amount of classes support the ASTNodes.

Please let me know if I am mistaken :)

**Comment by wumpz** [comment]
You are right. I avoided to construct AST - Nodes for every Object because it as a significant performance impact.

**Comment by wumpz** [comment]
So for which objects do you need position. I fear the answer: for all ;).

**Comment by wumpz** [comment]
A second question: why isnt it enough to add some #node jjt additions? For what this basetoken, etc. changes?

**Comment by Markus8000** [comment]
Hi,

It would be greate if we could add the start, startParameter and end position for:

- SubSelect
- Function
- CaseWhen (SWITCH, CASE WHEN, ELSE)
- WithItem

I guess the base token allows you to have more precise index: What if I have a function? There is the start of the function name, the function name itself and the parameters, followed by a closing parenthesis.

I would like to know if you would include/merge a pull request containing start, startParemeters and end position via base token.
