### ISSUE TITLE
Method determine if an expression consists of sub expression

### ISSUE THREAD

**Issue by Markus8000** [JSQLParser/JSqlParser#304]
From time to time I want to check if an expression is a pure `Expression` (on columns, values) or if it consists of nested `Expression`.

Do you think there is a way to enhance the interface `Expression` with a method (i.e. hasEmbeddedExpressions)?

In my first attempt I would go an write a visitor to browse all Expression, Subselects, Joins, etc.)

**Comment by wumpz** [comment]
The visitor way is the one to go. You could choose the ExpressionVisitorAdapter for a already implemented one.

**Comment by Markus8000** [comment]
Hello,

I was aware of the visitor pattern but wanted a handy method to determine if the function consists of further function calls.

Please let me know if you permit me up to implement such a method and visitor

**Comment by wumpz** [comment]
Sorry. Overlooked your answer. I am not sure what you mean, could you give a concrete example, what method calls you would prefer?
