### ISSUE TITLE
sql check syntax

### ISSUE THREAD

**Issue by Horace1117** [JSQLParser/JSqlParser#307]
Hello, I wanna print out my  sql check syntax on console using JsqlParser.
However, I found check syntax message only in JSqlParserException.
Is there some api I can get sql check syntax message without using JSqlParserException?
Thank you very match!

**Comment by wumpz** [comment]
Could you give a concrete example of what you mean?

**Comment by Horace1117** [comment]
just like this:
`public class checksyntax {

	public static void main(String args[]) {
		TGSqlParser sqlparser = new TGSqlParser(EDbVendor.dbvmssql);
		sqlparser.sqltext = "SELEC e.last_name AS ," + " e.commission_pct comm,\n"
				+ " e.salary * 12 \"Annual Salary\"\n" + "FROM sott. AS e\n" + "WHERE e.salary > 1000\n" + "ORDER BY\n"
				+ " e.first_name,\n" + " e.last_name;";
		int ret = sqlparser.parse();
		if (ret == 0) {
			for (int i = 0; i < sqlparser.sqlstatements.size(); i++) {
				// analyzeStmt(sqlparser.sqlstatements.get(i));
				System.out.println(sqlparser.sqlstatements.get(i));
			}
		} else {
			System.out.println(sqlparser.getErrormessage());
		}
	}

}`
It's wrong message of check syntax  I can get from sqlparser.getErrormessage().

**Comment by wumpz** [comment]
Understand. You want some kind of error recovery during parse process and then get all found syntax error messages. 
A recent issue requests error recovery during the parse. So one should provide this first and then follow your advice to get all found error messages.

**Comment by Horace1117** [comment]
Understand。Look forward  to new feature
