### ISSUE TITLE
JSqlParser - position of parse errors

### ISSUE THREAD

**Issue by dprutean** [JSQLParser/JSqlParser#308]
Please add dedicated methods for the error position in JSqlParser. Like getPosition() or getColumn() and getLine(). This makes more easy to get the exact position when the parser is invoked in a text editor, for example.

**Comment by wumpz** [comment]
If you had a ParseException there you can get the positions you need:

~~~
ParseException.currentToken.beginLine
~~~

and so on. Is that enough or is this request as well for some kind of error recovery procedure.

**Comment by dprutean** [comment]
Great, thank you for quick answer. For me it would be fine only this for now, but to make the code more readable it would be nice to add a method.
 What I saw is that you throw a JSqlParseException which has a getCause() a ParseException. Why not throw directly a ParseException ? Is again an improvement, the embedded exception can be tricky.

**Comment by wumpz** [comment]
I added first support for error recovery. There are some tests within the StatementsTests. There you get a list of parse errors from the parser object itself. The error position is retrieved like decribed above.
