### ISSUE TITLE
SqlServer [ ]

### ISSUE THREAD

**Issue by dprutean** [JSQLParser/JSqlParser#310]
SqlServer uses square brackets for table or column names ( like other databases may use '...' if the names are mixed-case or contains spaces ). Please check this case if possible.

**Comment by wumpz** [comment]
SqlServer quotation using brackets is supported:
~~~
SELECT columnName FROM [server-name\\server-instance]...tableName
~~~
This is one tested statement.

**Comment by dprutean** [comment]
Please consider also something like this, is SqlServer typical : 
CREATE TABLE [HangFireSchema].[JobParameter](
        [Id] [int] IDENTITY(1,1) NOT NULL,
        [JobId] [int] NOT NULL,
        [Name] [nvarchar](40) NOT NULL,
        [Value] [nvarchar](max) NULL,
        CONSTRAINT [PK_HangFire_JobParameter] PRIMARY KEY ([Id])
    );

You can remove square brackets [ ] on any identifier or parameter, they are like on other databases the '...'.

**Comment by wumpz** [comment]
You may be right, that not all of your brackets are supported, e.g. around column types.

**Comment by shivaprasad573** [comment]
Can someone suggest me how to parse  

`SELECT [K].[a] as testColumn FROM [TestTable] as  [K] `
I have tried using 
`Select select = (Select) CCJSqlParserUtil.parse(sqlQuery) ;`
Earler V1.1 this as working fine but that is not working after I migrated to 3.0 and giving the bellow error

`net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "SELECT" <K_SELECT>
    at line 1, column 1.`

**Comment by wumpz** [comment]
Bracket parsing has to be enabled by flag. This was done to support other databases array constructs.

**Comment by wumpz** [comment]
As well there was an addition for

`CCJSqlParserUtil.parse("select * ...", parser -> parser.withSquareBracketQuotation(true));`

**Comment by wumpz** [comment]
Can we close this issue?

**Comment by shivaprasad573** [comment]
Yes, we can close this, and thanks for your help.
