### ISSUE TITLE
offset 不能为字符串， 问题怎样解决

### ISSUE THREAD

**Issue by XinCao** [JSQLParser/JSqlParser#312]
我使用您开发的jsqlpaser, 现在，有个需求是给hbase加上sql支持，使用jsqlparser做sql解析，但是，他不支持offset为字符串的情况，请告诉我应该咋做。

**Comment by wumpz** [comment]
In English please.

**Comment by XinCao** [comment]
I use you to develop the jsqlpaser, now, there is a need to add HBase support to SQL, using SQL to do jsqlparser parsing, but he does not support the offset as a string, please tell me what should I do.

**Comment by wumpz** [comment]
Could you give me a concrete SQL that fails?
