### ISSUE TITLE
I use you to develop the jsqlpaser, now, there is a need to add HBase support to SQL, using SQL to do jsqlparser parsing, but he does not support the offset as a string, please tell me what should I do.

### ISSUE THREAD

**Issue by XinCao** [JSQLParser/JSqlParser#313]
I use you to develop the jsqlpaser, now, there is a need to add HBase support to SQL, using SQL to do jsqlparser parsing, but he does not support the offset as a string, please tell me what should I do.

**Comment by XinCao** [comment]
I have to modify the source code, and now, no problem

**Comment by wumpz** [comment]
May I close this and the other issue then?

**Comment by XinCao** [comment]
Sure
