### ISSUE TITLE
Oracle PARTITION BY and Distinct

### ISSUE THREAD

**Issue by Markus8000** [JSQLParser/JSqlParser#316]
Hello,

At the moment the following SQL produces an error even though it is correct in SQL Developer:

`SELECT COUNT(DISTINCT(1)) OVER (PARTITION BY C1, C2) FROM DUAL`

The DISTINCT keyword lets parser assume that it is a function `COUNT(DISTINCT(1)) OVER`. I think, there must be some adjustment in the AnalyticExpression section.

**Comment by wumpz** [comment]
already solved
