### ISSUE TITLE
Just question - not issue

### ISSUE THREAD

**Issue by dprutean** [JSQLParser/JSqlParser#319]
Hi, 
I have a question - is not an issue:
Is it possible to implement a simple token parser using JSqlParser ? 
I want to implement an text autocompletion for SQL. I need only to recognize the keyworkds, text strings, etc. The parser sould not generate any error. 
I want only to check if this is possible.

Thank you,
Dragos

**Comment by wumpz** [comment]
I have never done this before, but you could give the token manager (CCJSqlParserTokenManager)  of JSqlParser a try.

**Comment by wumpz** [comment]
I started a Gitter room, where you could ask this kind of questions. To start is use the gitter-chat icon at JSqlParsers start page.

**Comment by dprutean** [comment]
Hello Tobias,
Thank you. I tried parsing by tokens, but I gave it for now. I didn't find a way to do this. I could only call statements(), etc.
Cheers,
Dragos 

    On Monday, August 15, 2016 8:02 AM, Tobias <notifications@github.com> wrote:
 

 I started a Gitter room, where you could ask this kind of questions. To start is use the gitter-chat icon at JSqlParsers start page.—
