### ISSUE TITLE
ALTER TABLE TB1 ADD CONSTRAINT C1 UNIQUE (COL1, COL2) not supported

### ISSUE THREAD

**Issue by titou10titou10** [JSQLParser/JSqlParser#320]
The following SQLstatement is not supported by the latest version of jSqlParser:
`ALTER TABLE TB1 ADD CONSTRAINT C1 UNIQUE (COL1, COL2)`

The following variation works (Issue  #105 talks about this syntax)
`ALTER TABLE TB1 ADD UNIQUE KEY C1 (COL1, COL2)`

This form of `ALTER` statement is generated by EclipseLink (`Persistence.generateSchema(..)`) with a DB2 dialect
Could it be possible to add this syntax to jSqlParser?
Thanks

**Comment by titou10titou10** [comment]
I'm a real newbie in that area, but basically the syntax is exactly the same as for the `ALTER TABLE .. ADD CONSTRAINT.. PRIMAY KEY..`, just replace the `K_PRIMARY`with `K_UNIQUE`and make `K_KEY`optional

Probably adding this block after line 3070 of `JSqlParserCC.jjt` could do the job (duplicate lines 3061-3070 and change K_PRIMARY and make K-KEY optional) :

( tk=\<K_UNIQUE> tk2=\<K_KEY> <- has to be optional...
                columnNames=ColumnsNamesList()
                {
                    index = new NamedConstraint();
                    index.setName(sk3);
                    index.setType(tk.image); <- removed K-KEY
                    index.setColumnsNames(columnNames);
                    alter.setIndex(index);
                }
)

**Comment by tmnsur** [comment]
ALTER TABLE tr_marks ADD UNIQUE KEY tr_marks_entity_id_create_date (entity_id, uuid, create_date)

is parsed successfully. But the following:

ALTER TABLE tr_marks ADD CONSTRAINT tr_marks_entity_id_create_date UNIQUE KEY (entity_id, uuid, create_date)

is failing with a ParseException stating that the token UNIQUE was unexpected. One of PRIMARY, FOREIGN or CHECK was expected instead.

**Comment by tmnsur** [comment]
ALTER TABLE tr_marks ADD CONSTRAINT tr_marks_idx1 KEY tr_marks_customer_id(customer_id)

fails for same reason with the above.

ALTER TABLE tr_marks ADD KEY tr_marks_idx1 tr_marks_customer_id(customer_id)

fails too. So there is no way of parsing this kind of alter statements in v1.1 I think.

**Comment by wumpz** [comment]
If you make any changes regarding this issue please provide a pull request.
