### ISSUE TITLE
Visiting all Selects from SQL statement

### ISSUE THREAD

**Issue by msbruno** [JSQLParser/JSqlParser#326]
Hi, I have a question over visiting.
In my sql statement I do "Select * from people where people.id in (select people_id from people_filter where id = 2". 
My problema is: I wanna visit all Select (and subSelect) statement to assert if all selected itens have alias. 
Is StatementVisitor the correct way to do it?

**Comment by wumpz** [comment]
The statement visitor is only the start. Maybe a better start would be class AddAliasesVisitor which does create missing aliases. So you could use the visiting and modify the behaviour if no alias is present. There is a little example in the wiki. Cheers Tobias

**Comment by wumpz** [comment]
A better place for this kind of questions may be the JSQLPARSER gitter room.
