### ISSUE TITLE
Parsing error having for cast as interval

### ISSUE THREAD

**Issue by saulojg** [JSQLParser/JSqlParser#330]
Using the latest version of the library I've got the following exception:

`net.sf.jsqlparser.parser.ParseException: Encountered " ">" "> "" at line 1, column 79.`

Caused by this statement:

`SELECT COUNT(*) FROM C_Invoice WHERE IsSOTrx='Y' AND (Processed='N' OR Updated>(current_timestamp - cast('90 days' as interval))) AND C_Invoice.AD_Client_ID IN(0,1010016) AND C_Invoice.AD_Org_ID IN(0,1010053,1010095,1010094)`

**Comment by wumpz** [comment]
The problem was not **>** but a cast to interval, where interval is a keyword.

**Comment by saulojg** [comment]
thank you very much!
