### ISSUE TITLE
SELECT statement with IN clause

### ISSUE THREAD

**Issue by saulojg** [JSQLParser/JSqlParser#331]
The following query ([see here for more legible version](http://paste.debian.net/794880/))

`SELECT C_DocType.C_DocType_ID,NULL,COALESCE(C_DocType_Trl.Name,C_DocType.Name) AS Name,C_DocType.IsActive FROM C_DocType LEFT JOIN C_DocType_TRL ON (C_DocType.C_DocType_ID=C_DocType_Trl.C_DocType_ID AND C_DocType_Trl.AD_Language='es_AR') WHERE C_DocType.AD_Client_ID=1010016 AND C_DocType.AD_Client_ID IN (0,1010016) AND C_DocType.c_doctype_id in ( select c_doctype2.c_doctype_id from c_doctype as c_doctype2 where substring( c_doctype2.printname from length(c_doctype2.printname) ) = ( select letra from c_letra_comprobante as clc where clc.c_letra_comprobante_id = 1010039) ) AND ( (1010094!=0 AND C_DocType.ad_org_id = 1010094) OR 1010094=0 ) ORDER BY 3 LIMIT 2000`

casts:

```
net.sf.jsqlparser.parser.ParseException: Encountered " "IN" "in "" at line 1, column 345.
Was expecting one of:
    <EOF> 
    "FOR" ...

```

Column 345 would be the part `C_DocType.c_doctype_id in ( select c_doctype2 ...`

**Comment by mdepak** [comment]
Shall I try fix this issue or anybody solved this already?

**Comment by wumpz** [comment]
Sorry. I missed your issue. The problem is not "in" but the substring(a from b) construct. JSqlParser does not support this one. There is already a pull request for this. In fact there are two.

**Comment by AnEmortalKid** [comment]
@wumpz this too is not an issue anymore

![image](https://user-images.githubusercontent.com/3474369/85214631-1aa5d100-b333-11ea-967d-97476377f86f.png)

**Comment by wumpz** [comment]
Cool. Thx for testing this.
