### ISSUE TITLE
Class Column toString() method do not output table alias.

### ISSUE THREAD

**Issue by xzleah** [JSQLParser/JSqlParser#332]
`Table myTable = new Table("myTable");`
`myTable.setAlias(new Alias("tb"));`
`Column myColumn = new Column(myTable, "myColumn");`
`System.out.println(myColumn);`
It output "myTable.myColumn". I think it's not correct. Why do not considerate table alias when column to string?

**Comment by wumpz** [comment]
sounds like a bug

**Comment by wumpz** [comment]
Which version do you use? 0.9.6 / 0.9.7-SNAPSHOT delivers tb.myColumn.

**Comment by xzleah** [comment]
I use 0.9.5 . 
`<dependency>
			<groupId>com.github.jsqlparser</groupId>
			<artifactId>jsqlparser</artifactId>
			<version>0.9.5</version>
		</dependency>`

**Comment by wumpz** [comment]
Look at #311. It is fixed.
