### ISSUE TITLE
This sql should work but failed to parse

### ISSUE THREAD

**Issue by ywang4362** [JSQLParser/JSqlParser#333]
SELECT choice.response_choice_id          AS uuid,  
       choice.digit                       AS digit,  
       choice.text_response               AS textResponse,  
       choice.voice_prompt                AS voicePrompt,  
       choice.action                      AS action,  
       choice.contribution                AS contribution,  
       choice.order_num                   AS order,  
       choice.description                 AS description,  
       choice.is_join_conference          AS joinConference,  
       choice.voice_prompt_language_code  AS voicePromptLanguageCode,  
       choice.text_response_language_code AS textResponseLanguageCode,  
       choice.description_language_code   AS descriptionLanguageCode,  
       choice.rec_phrase                  AS recordingPhrase  
FROM   response_choices choice  
WHERE  choice.presentation_id = ?
ORDER BY choice.order_num

**Comment by wumpz** [comment]
Any exception? My first guess is keyword "order" as column name. Cheers Tobias

**Comment by ywang4362** [comment]
I lost the exception. Yes, it complains ORDER is incorrect... You can simply try the above sql to reproduce the problem.

**Comment by wumpz** [comment]
Order is a hard column name or alias to parse. It would introduce lookaheads in various positions of the parser:

select * from tab1 order by test

Is order an alias or start of order by??

So I decided at the moment to not fix this.
