### ISSUE TITLE
Wrong parse result at "Select * from A limit ?,?"?

### ISSUE THREAD

**Issue by fanyongpeng** [JSQLParser/JSqlParser#334]
I parse this sql :
Select * from A limit ?,?
parse result is : 
SELECT * FROM A LIMIT ? OFFSET ?

I know if there are definite value it would be ok. But in my java program, i must change sql first and set value in  the end .  JSqlParser change the order. ..  it made me crazy, how to solve this problem?

**Comment by wumpz** [comment]
I corrected the deparser and toString to reproduce limit ?,? and not limit ? offset ?.

Hope that helps.
