### ISSUE TITLE
UPDATE TABLE JOIN not support

### ISSUE THREAD

**Issue by jujusharp** [JSQLParser/JSqlParser#335]
The following sql throws parse err:

`update tf_s_tbl a left join tf_s_tbl1 b on a.id =b.id set a.field1 = 1, b.field2 =2 where a.id =1`

> Caused by: net.sf.jsqlparser.parser.ParseException: Encountered " "LEFT" "left "" at line 1, column 19.
> Was expecting one of:
>     "SET" ...
>     "," ...
>     at net.sf.jsqlparser.parser.CCJSqlParser.generateParseException(CCJSqlParser.java:15112)
>     at net.sf.jsqlparser.parser.CCJSqlParser.jj_consume_token(CCJSqlParser.java:14968)
>     at net.sf.jsqlparser.parser.CCJSqlParser.Update(CCJSqlParser.java:359)
>     at net.sf.jsqlparser.parser.CCJSqlParser.SingleStatement(CCJSqlParser.java:133)
>     at net.sf.jsqlparser.parser.CCJSqlParser.Statement(CCJSqlParser.java:80)
>     at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:52)

The version of JSQLParser is 0.9.6

**Comment by AnEmortalKid** [comment]
@wumpz you also probably fixed this a long time ago

![image](https://user-images.githubusercontent.com/3474369/85235564-880d3c80-b3db-11ea-80f1-1e8493dbaf64.png)

**Comment by wumpz** [comment]
Thx for testing all this stuff.
