### ISSUE TITLE
Failed to parse valid "SELECT" statement containing some KEYWORDS

### ISSUE THREAD

**Issue by qiqingli** [JSQLParser/JSqlParser#343]
I have create a table named table1 with columns named with keywords in Oracle, the create table sql is:

CREATE TABLE
    TABLE1
    (
        TOP VARCHAR2(20),
        ILIKE VARCHAR2(20),
        JOIN VARCHAR2(20),
        LEFT VARCHAR2(20),
        CROSS VARCHAR2(20),
        SOME VARCHAR2(20),
        FULL VARCHAR2(20),
        PIVOT VARCHAR2(20),
        USING VARCHAR2(20),
        BEGIN VARCHAR2(20),
        INNER VARCHAR2(20),
        LIMIT VARCHAR2(20),
        OUTER VARCHAR2(20),
        RIGHT VARCHAR2(20),
        OFFSET VARCHAR2(20),
        ESCAPE VARCHAR2(20),
        PRIMARY VARCHAR2(20),
        FULLTEXT VARCHAR2(20),
        NATURAL VARCHAR2(20),
        EXCEPT VARCHAR2(20),
        LATERAL VARCHAR2(20),
        INTERVAL VARCHAR2(20),
        FOREIGN VARCHAR2(20),
        CONSTRAINT VARCHAR2(20),
        REFERENCES VARCHAR2(20),
        CHARACTER VARCHAR2(20),
        VARYING VARCHAR2(20),
        NOCYCLE VARCHAR2(20),
        UNBOUNDED VARCHAR2(20),
        PRECEDING VARCHAR2(20),
        RETURNING VARCHAR2(20),
        BINARY VARCHAR2(20),
        REGEXP VARCHAR2(20),
        UNLOGGED VARCHAR2(20),
        EXEC VARCHAR2(20),
        EXECUTE VARCHAR2(20),
        FETCH VARCHAR2(20),
        NEXT VARCHAR2(20),
        ONLY VARCHAR2(20),
        WITHIN VARCHAR2(20),
        IF VARCHAR2(20),
        RECURSIVE VARCHAR2(20),
        KEEP VARCHAR2(20),
        GROUP_CONCAT VARCHAR2(20),
        SKIP VARCHAR2(20),
        MERGE VARCHAR2(20),
        MATCHED VARCHAR2(20),
        RESTRICT VARCHAR2(20),
        DUPLICATE VARCHAR2(20),
        LOW_PRIORITY VARCHAR2(20),
        DELAYED VARCHAR2(20),
        HIGH_PRIORITY VARCHAR2(20),
        IGNORE VARCHAR2(20),
        SEMI VARCHAR2(20),
        DOUBLE VARCHAR2(20),
        PRECISION VARCHAR2(20),
        TABLESPACE VARCHAR2(20)
    ) ;

I am trying to parse a query which contains columns of table1 with jsqlparser-0.9.6, For example:

**SELECT TOP, ILIKE, JOIN, LEFT, CROSS, SOME, FULL, PIVOT, USING, BEGIN, INNER, LIMIT, OUTER, RIGHT, OFFSET, ESCAPE, PRIMARY, FULLTEXT, NATURAL, EXCEPT, LATERAL, INTERVAL, FOREIGN, CONSTRAINT, REFERENCES, CHARACTER, VARYING, NOCYCLE, UNBOUNDED, PRECEDING, RETURNING, BINARY, REGEXP, UNLOGGED, EXEC, EXECUTE, FETCH, NEXT, ONLY, WITHIN, IF, RECURSIVE, KEEP, GROUP_CONCAT, SKIP, MERGE, MATCHED, RESTRICT, DUPLICATE, LOW_PRIORITY, DELAYED, HIGH_PRIORITY, IGNORE, SEMI, DOUBLE, PRECISION, TABLESPACE FROM table1 a;**

gives me the following error:

net.sf.jsqlparser.JSQLParserException
    at net.sf.jsqlparser.parser.CCJSqlParserManager.parse(CCJSqlParserManager.java:40)
    at Test.main(Test.java:108)
Caused by: net.sf.jsqlparser.parser.ParseException: Encountered " "," ", "" at line 1, column 11.
Was expecting one of:
    <S_LONG> ...
    "(" ...
    "?" ...

**Comment by wumpz** [comment]
Why would someone build such sqls? Integrating your commit keyword does not mean, that every keyword have to be parseable. It is a desicion between usability, performance, implementation and good / bad practice. Look at keyword "select". Tobias

**Comment by qiqingli** [comment]
Thanks for your advices.
