### ISSUE TITLE
[Feature request] Support for "cross apply" syntax for SQL Server

### ISSUE THREAD

**Issue by sken130** [JSQLParser/JSqlParser#344]
As titled.
Is it easy to add and test this?
And if I want to try building the library locally, is there any quick-start tutorial for modifying JSqlParserCC.jjt to support "cross apply" syntax? It looks like it's using JavaCC.

Sample SQL:

``` sql
select s.*, c.*, calc2.summary
from student s
join class c on s.class_id = c.id
cross apply (
  select s.first_name + ' ' + s.last_name + ' (' + s.sex + ')' as student_full_name
) calc1
cross apply (
  select case c.some_styling_type when 'A' then c.name + ' - ' + calc1.student_full_name
            when 'B' then calc1.student_full_name + ' - ' + c.name
            else calc1.student_full_name end as summary
) calc2
```

This sample is not the only use case of "cross apply".

"cross apply" is also used when one needs to apply some db function for each row in the SQL result.

**Comment by wumpz** [comment]
My understanding of cross apply is very limited.  So til now I can not estimate the needed time to make it work. 
To build JSQLPARSER from scratch you need maven check JSQLPARSER out and do a mvn clean install and you are done. Cheers Tobias

**Comment by uanlgex** [comment]
Hello.
I bumped into the same issue using this great library.
Is there any progress to be expected ?
Thanks

**Comment by wumpz** [comment]
As always PRs are welcome.

**Comment by uanlgex** [comment]
I started looking at it :).
It won’t be easy for me though I’m afraid !
Best
Alex








________________________________

**Comment by sivaraam** [comment]
I also faced this issue as some queries that we would like to parse use MS SQL's CROSS APPLY clause.
