### ISSUE TITLE
[Q] Oracle: column names v keywords

### ISSUE THREAD

**Issue by kontchakov** [JSQLParser/JSqlParser#345]
It appears that the following is a legal query for Oracle

select INTERVAL, OFFSET from TABLE1

(provided that TABLE1 has columns INTERVAL and OFFSET). JSqlParser, however, throws an exception. Is there a straightforward fix for it? 

Thanks
Roman

**Comment by wumpz** [comment]
Including those into RelObjectName should be enough. Sometimes there is a little lookup correction needed. Tobias

**Comment by wumpz** [comment]
I have to correct myself. It collides with some parsing rules in quite a way. So a simple way seems not possible.

**Comment by rjahn** [comment]
same problem with #994 

It would be nice to parse select statements with another mapping than functions, ...

**Comment by wumpz** [comment]
JSqlParser 4.0 parses this.
