### ISSUE TITLE
OPTIMIZE statement cannot be parsed

### ISSUE THREAD

**Issue by msbruno** [JSQLParser/JSqlParser#348]
SQL commands like the sql below cannot be parsed, an exception occurs.

SELECT *
  FROM EMP
  ORDER BY SALARY DESC
  OPTIMIZE FOR 20 ROWS;

Exception: "net.sf.jsqlparser.parser.ParseException: Encountered " <S_IDENTIFIER> "OPTIMIZE "" at line 4, column 3.
Was expecting one of:
    <EOF> 
    "FOR" ..."

**Comment by CodingFabian** [comment]
+1 here,
this seems to be trailing to statements:
e.g. in selects like:

LIMIT 1 OPTIMIZE FOR 1 ROWS
