### ISSUE TITLE
Failure to parse UPDATE with Functions in right-hand expression

### ISSUE THREAD

**Issue by wheredevel** [JSQLParser/JSqlParser#349]
I've this incredible(!!!) UPDATE statement:  
`UPDATE _OBJECT_ SET OBJECT_ID = SUBSTRING(OBJECT_ID, 1, POSITION('/' IN OBJECT_ID) + POSITION('/' IN SUBSTRING(OBJECT_ID, POSITION('/' IN OBJECT_ID) + 1)) + POSITION('/' IN SUBSTRING(OBJECT_ID, POSITION('/' IN OBJECT_ID) + POSITION('/' IN SUBSTRING(OBJECT_ID, POSITION('/' IN OBJECT_ID) + 1)) + 1))) || 'activity' || SUBSTRING(OBJECT_ID, POSITION('/' IN OBJECT_ID) + POSITION('/' IN SUBSTRING(OBJECT_ID, POSITION('/' IN OBJECT_ID) + 1)) + POSITION('/' IN SUBSTRING(OBJECT_ID,POSITION('/' IN OBJECT_ID) + POSITION('/' IN SUBSTRING(OBJECT_ID, POSITION('/' IN OBJECT_ID) + 1)) + 1))) WHERE DTYPE = 'type:2'`

It fails with the following exception:  
`net.sf.jsqlparser.parser.ParseException: Encountered " "(" "( "" at line 1, column 56.
Was expecting one of:
    <EOF>  
    "FROM" ...  
    "WHERE" ...  
    "LIMIT" ...  
    "ORDER" ...  
    "RETURNING" ...  
    ";" ...  
    "," ...  
    "|" ...   
    "&" ...  
    "^" ...  
    "::" ...  
    at net.sf.jsqlparser.parser.CCJSqlParser.generateParseException(CCJSqlParser.java:16171)
    at net.sf.jsqlparser.parser.CCJSqlParser.jj_consume_token(CCJSqlParser.java:16024)
    at net.sf.jsqlparser.parser.CCJSqlParser.Statement(CCJSqlParser.java:91)
    at net.sf.jsqlparser.parser.CCJSqlParserManager.parse(CCJSqlParserManager.java:38)
    ...`

From this...
`...
    <K_UPDATE> table=TableWithAlias() { tables.add(table); } 
          ("," table=TableWithAlias() { tables.add(table); } )*
    <K_SET> 
    (
    LOOKAHEAD(3) tableColumn=Column() "=" value=SimpleExpression() { columns.add(tableColumn); expList.add(value); }
        ("," tableColumn=Column() "=" value=SimpleExpression() { columns.add(tableColumn); expList.add(value); } )*

```
|

["(" { useColumnsBrackets = true; }] tableColumn=Column() { columns.add(tableColumn); } ("," tableColumn=Column() { columns.add(tableColumn); } )* [ ")" ] "="
    "("
    (
        { update.setUseSelect(true); }
        select = Select()
    )
    ")"
```

   )
...  
`   

...it seems like the parser deals only with SET column = SimpleExpression().  
Simple - does not mean function calls. (Correct me if I'm wrong.)

I'd really appreciate help on fixing the grammar to support the above _function-reach_ UPDATE statement.

**Comment by wumpz** [comment]
SimpleExpression goes a long way down to PrimaryExpression with supports functions. This simple example is parsed:

`UPDATE tablename SET col = SUBSTRING(col2, 1, 2)`

My first guess is the **position** syntax using an inner **in** - expression. If I remember right, there should by an open pull request or an issue for this. I had not the time to process it.

**Comment by wumpz** [comment]
Look at #173.

**Comment by wheredevel** [comment]
Thanks. I will take a look.

**Comment by AnEmortalKid** [comment]
@wumpz this too is no longer an issue

![image](https://user-images.githubusercontent.com/3474369/85214622-e3372480-b332-11ea-895d-ad4d16e6ebf8.png)

**Comment by wumpz** [comment]
Thx. I close it.
