### ISSUE TITLE
Problems getting started with JSQLParser

### ISSUE THREAD

**Issue by JulianWagner91** [JSQLParser/JSqlParser#350]
Hello, 

I am trying to use JSQLParser in my current project to parse SQL Statements. So I downloaded the hole master branch and copied the src folder into my project. After solving some small issues by myself I have got some problems in the class CCJsqlParser

In the method getAstRoot() is a return statement of jjtree.rootNode() but unfortunatelly this can not be resolved. Although there is a call linkAST(col, jjtThis) - within method final public Column Column() - , but the variable jjtThis is also not resolvable. 

When I compiled the JSqlParserCC.jjt file with JavaCC 5.0 or 6.0 there allways came an error on lines with an "#String:" at the end like in "Statement Statement() #Statement:". After changing this into "Statement Statement():" the file could be compiled. Is it possible, that the problems above were caused through this changes?

Thanks a lot for your help

**Comment by wumpz** [comment]
I assume you do not have a maven build process. So first of all you should use a released version from maven central. There you can download the jars sources and javadocs.
The source folder alone is not compilable. All the generated classes are missing. So if you would use maven all needed deps, e.g. JavaCC are downloaded and used to produce a usable JSQLPARSER jar. 
The jjt-file is not a javacc but a jjtree file. Jjtree is another tool from the javacc framework which includes AST processing commands and produces a jj file which is usable with JavaCC.
You could publish your changes as pull requests, so those could easily merged into master.

Hope that helps
Tobias

**Comment by wumpz** [comment]
Here should be a maven central start: https://mvnrepository.com/artifact/com.github.jsqlparser/jsqlparser/0.9.6
As well older versions of the parser are there.

**Comment by JulianWagner91** [comment]
Thanks for your comment. You are right. Mavent itself wasnot installed. I will try all your suggestions today, and come back to you :-)

**Comment by JulianWagner91** [comment]
Hi Tobias, 
thanks for your help. My main problem was, that I did not know, what to do with that jjt file as this was my first touch to the JavaCC Framework. No after reading some menues I got it and all my problems were gone. 

Kind regards
