### ISSUE TITLE
could you add a plugin for jacoco as below?

### ISSUE THREAD

**Issue by mhe12** [JSQLParser/JSqlParser#351]
I added this plugin in pom file and it works. It's really convenient if this could be added for a coverage report using jacoco.

`<plugin>
                  <groupId>org.jacoco</groupId>
                  <artifactId>jacoco-maven-plugin</artifactId>
                  <version>0.7.5.201505241946</version>
                  <executions>
                      <execution>
                          <id>prepare-agent</id>
                          <goals>
                              <goal>prepare-agent</goal>
                          </goals>
                      </execution>
                  </executions>
                  </plugin>`

**Comment by mhe12** [comment]
`<plugin>
                  <groupId>org.jacoco</groupId>
                  <artifactId>jacoco-maven-plugin</artifactId>
                  <version>0.7.5.201505241946</version>
                  <executions>
                      <execution>
                          <id>prepare-agent</id>
                          <goals>
                              <goal>prepare-agent</goal>
                          </goals>
                      </execution>
                  </executions>
                  </plugin>`

**Comment by wumpz** [comment]
It's not needed. All coverage is done using travis and you can access it from the coverage button on the main page.

**Comment by wumpz** [comment]
I am using coveralls.io.

**Comment by wumpz** [comment]
Does this help you? Can I close this issue?

**Comment by mhe12** [comment]
Yes ,thank you!
