### ISSUE TITLE
Question about dual licensing

### ISSUE THREAD

**Issue by sgustafsson** [JSQLParser/JSqlParser#353]
Can you explain how the dual-licensing got introduced? It seems as if it was added here https://github.com/JSQLParser/JSqlParser/commit/83899f824659012e1e77ac97c75a968e5c32403c , saying  "revived Apache Software License, Version 2.0" .

I understand the original code is a fork from Sourceforge.net https://sourceforge.net/p/jsqlparser/discussion/360150/thread/5718687c/?limit=25#9f50 , and the initial versions on sourceforge were LGPL only.

Is there any documentation stating that all past contributors (from the time when the code was under LGPL only) agreed to the dual-licensing under Apache v2 as well?

**Comment by wumpz** [comment]
Hi, the sourceforge site states clearly a triple license: Apache Lgpl and Gpl. The fork was introduced from version 0.7.0. As I stated already within the issue reintroducing Apache 2.0, I missed it migrating to a maven infrastructure. Do you see a problem with that? Tobias

**Comment by wumpz** [comment]
https://sourceforge.net/projects/jsqlparser/

Look at the license part.

**Comment by sgustafsson** [comment]
I see. The original sourceforge site for 0.7.0 stated a dual license (Apache and LGPL). However, previous versions of the site (as well as the source code) state LGPL only.

Feb 4, 2013 - https://web.archive.org/web/20130204161238/http://sourceforge.net/projects/jsqlparser/
Sep 22, 2013 - https://web.archive.org/web/20130922084013/http://sourceforge.net/projects/jsqlparser/

So sometime between Feb 4 and Sep 22 2013, the Apache license was added on the sourceforge project homepage. On both of those dates, version 0.7.0 was the latest version already.

There was a forum question from https://sourceforge.net/p/jsqlparser/discussion/360150/thread/63f59c71/ asking if the LGPL license could be changed. Apart from that, I wasn't able to find any documentation as to how the change has happened. Furthermore, the Apache license obligations (https://tldrlegal.com/license/apache-license-2.0-(apache-2.0)) like supplying a copy of the license text, were also not implemented.

But if you forked starting from 0.7.0, you relied on what was documented on the sourceforge site. So my initial question of "Can you explain how the dual-licensing got introduced" should go to the original authors of the software.

**Comment by wumpz** [comment]
So I am not a lawyer. What would be a problem if there was a problem going to dual licensing? What would / could be the consequences?

**Comment by sgustafsson** [comment]
IANAL either. The only potential problem I see is that in case not every original contributor of code on sourceforge agreed to the dual licensing approach, the code would only be governed by LGPL (and not Apache v2). In case all original code contributions had been made by one person only, and this one person only then decided to offer the code under two licenses, that would  mean the code is actually dual-licensed.
