### ISSUE TITLE
MySQL DB 'IF' bug

### ISSUE THREAD

**Issue by rainsponsor** [JSQLParser/JSqlParser#354]
if my sql contains 'IF' ,
Caused by: net.sf.jsqlparser.parser.ParseException: Encountered " "IF" "if "" at line 1, column 229.
Was expecting one of:
    "DO" ...
    "ANY" ...

my sql - > select .....  IF(pre.PROFESSIONAL_CODE is not null,0,1) as isExists from ......

**Comment by wumpz** [comment]
That is right. JSqlParser does not support this if constructs, but it parses case when expression. If you could change. Nevertheless there is already an open issue for this type of expression.

**Comment by rainsponsor** [comment]
thanks
