### ISSUE TITLE
Alias Object is always Null in getTable of any Object

### ISSUE THREAD

**Issue by mdepak** [JSQLParser/JSqlParser#355]
When getTable() is done on any Column object, the returned Table object has Alias as null and it holds alias name as table name and it is wrong. Somebody provide info whether this library supports Alias ( even though class exists)

**Comment by wumpz** [comment]
JSqlParser is a parser. If you write `tab1.col`, it cannot decide, if it is a table name or an alias. This would be a task to be done after JSqlParser has parsed your statement.

What is the concrete problem you try to solve? Maybe there is another way.

**Comment by mdepak** [comment]
I want to get the column names and table names of the parameres in WHERE clause with IN operator.

**Comment by mdepak** [comment]
Period (.) can be used along with column name in SQL only when alias is used or otherwise it should be enclosed with brackets like [ name.name ] . So there is a way that Alias name column can be filled and the table names. I would like to add this feature to your lib as alias names are common in sql.  I am willing to do this change if you agree

**Comment by wumpz** [comment]
IMHO your last statement is wrong:
`alias.col, table.col`
`[alias].[col], [table].[col]`
are valid, while
`[alias.col], [table.col]`
are not. 
Or at least I dont know a dbms where this is the case. I tested this within SqlServer.

With this in mind, there is no possibility to differ between aliases and names during the parse. One has to postprocess the data. But this is not a trivial task to do having visibility of names or aliases in different blocks of one sql.

`select a.c from table1 a where exists (select a.d from table2 a)`

a.c should be derived from table1 while a.d should be from table2.

Using JSqlParser you could modify the TableNameFinder utility and process columns building a stack of defined aliases.

**Comment by mdepak** [comment]
Is there any way using JSqlParser for getting the table name associated with table name and column name.

**Comment by wumpz** [comment]
I outlined the way above. I litte more specific. To traverse the parse result you have to build a visitor. Look at the examples for some base info here. 
1. find all "Table" - objects. Here is the alias definition for a concrete tablename. 
2. scan through visibility block of this object: meaning for a simple sql walk through "Column" - objects and use alias definitions found under 1

Point 2 is the non trivial part.
