### ISSUE TITLE
Relational operators in expressions

### ISSUE THREAD

**Issue by gian** [JSQLParser/JSqlParser#356]
Hi there,

I've encountered problems with expressions of the form:

    SELECT foo <= 42 FROM mytable

Is this by design, or simply an omission? `SELECT foo + 42 FROM ...` works, and the (non-working) expression using relational operators is parsed correctly by MySQL.

Many thanks,

**Comment by wumpz** [comment]
That's right. JSqlParser does not support this. (Unfortunately)

**Comment by wumpz** [comment]
Any chance you could provide a pull request?

**Comment by gian** [comment]
Sure, I'll try to find some time to add these - thanks!

**Comment by tserr** [comment]
Hello Gian,

I just ran into the same issue. 

Did you already find some time to do some work on implementing this feature? Do you have some ideas how to implement? 

I'd like to use this feature in one of my projects ;-) Is there anything I can do to help?

Best regards

**Comment by wumpz** [comment]
JSqlParser 4.0 parses this.
