### ISSUE TITLE
Question about iterating over a sql parsed expressions

### ISSUE THREAD

**Issue by anderruiz** [JSQLParser/JSqlParser#357]
I would like to know if there is any way to iterate over all the query parts?. My problem is, I have an input sql and I want to know to which part of the query belong some parts of the original query, i.e.

UPDATE Customers
SET ContactName='Alfred Schmidt', City='Hamburg'
WHERE **CustomerName='Alfreds Futterkiste'**;

I want to know that this part is inside a WHERE expression, it may potentially happen that the part I want to analyze belongs to more than one part or the query, i.e. two expressions in a WHERE.

My question is, is there any way to do that?

**Comment by wumpz** [comment]
First if all "Alfreds Futterkiste" ... 😎  I like that. We could switch to German if you prefer. 

Traversing the parse tree is done by visitors. The standard way is a depth first search. Combined with a stack you could achieve what you want . There are some examples using this technique.  Cheers Tobias

**Comment by anderruiz** [comment]
Actually that was an example from W3Schools, even thought Ich kann ein bissen Deutsch sprechen :). Where can I find those examples?

**Comment by wumpz** [comment]
JSQLPARSER project wiki pages. If you need more, look at the tests.

**Comment by anderruiz** [comment]
Ok, I will read them again and try to figure out how to do it. Thanks

**Comment by wumpz** [comment]
If there are questions feel free to ask. Thx for using JSqlParser.
