### ISSUE TITLE
How to parse this sql? please

### ISSUE THREAD

**Issue by tangknives** [JSQLParser/JSqlParser#358]
Select a.* from (select *,concat(order_id, "") as order_sid from t_order order by order_id desc) a limit 0,5

**Comment by wumpz** [comment]
Are you sure, this is a valid sql? IMHO select star is only allowed without additional columns. But with an additional table name it is correct:

Select tablename.* ...

**Comment by wumpz** [comment]
Can we close this one?

**Comment by tangknives** [comment]
I can execute it on mysql server
