### ISSUE TITLE
sql parsing issue.

### ISSUE THREAD

**Issue by Shashi-GS** [JSQLParser/JSqlParser#359]
I am trying to parse the below sql its throwing the parse exception.

Select 50ofcourses From tableName Group by 50ofcourses

As it contains the number in the column name of group by section. could you please provide the fix for it ASAP or is there any alternative solution for this ?

**Comment by wumpz** [comment]
The problem is the numbers at the start. test50 does work well. Column names like yours have to be quoted "50test".
IMHO it is non standard to allow your column name.

**Comment by Shashi-GS** [comment]
yes I understand, most of the relational databases will allow this kind of column names and queries also.  that's the problem

**Comment by wumpz** [comment]
Most of relational database s will allow this kind of column names queried only with quotation. I dont know any dbms that would process the way you want

`select 50col from table`

oracle, sqlserver or postgresql do somethind like `select 50 as col from table`

**Comment by wumpz** [comment]
will not be solved, due to heavy impact on rest of parsing
