### ISSUE TITLE
SELECT EXISTS not work

### ISSUE THREAD

**Issue by stranger520** [JSQLParser/JSqlParser#362]
in my junit test case:
`String sql = "SELECT EXISTS (SELECT 1 FROM mytable where xx=xx)"; 
Statement statement = CCJSqlParserUtil.parse(sql);
            Select select = (Select) statement;`
But,this case not work. 
Exception:
`net.sf.jsqlparser.JSQLParserException
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:54)
	at com.le.platform.crispynews.testcase.SqlParserTester.testSelectExists(SqlParserTester.java:79)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:117)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:42)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:262)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:84)
Caused by: net.sf.jsqlparser.parser.ParseException: Encountered " "EXISTS" "EXISTS "" at line 1, column 8.
Was expecting one of:
    "DO" ...
    "ALL" ...
    "ANY" ...
    "KEY" ...
    "SET" ...
    "TOP" ...
    "PERCENT" ...
    "END" ...
    "NULL" ...
    "LEFT" ...
    "OPEN" ...
    "CASE" ...
    "TABLE" ...
    "XML" ...
    "RIGHT" ...
    "VALUE" ...
    "VALUES" ...
    "REPLACE" ...
    "TRUNCATE" ...
    "DISTINCT" ...
    "CAST" ...
    "OVER" ...
    "PARTITION" ...
    "EXTRACT" ...
    "MATERIALIZED" ...
    "INTERVAL" ...
    "PRIOR" ...
    "SIBLINGS" ...
    "COLUMN" ...
    "NULLS" ...
    "FIRST" ...
    "LAST" ...
    "ROWS" ...
    "RANGE" ...
    "FOLLOWING" ...
    "ROW" ...
    "UNIQUE" ...
    "GROUP_CONCAT" ...
    "SEPARATOR" ...
    "SKIP" ...
    "CASCADE" ...
    "NO" ...
    "ACTION" ...
    <K_DATETIMELITERAL> ...
    <K_TIME_KEY_EXPR> ...
    "DOUBLE" ...
    <S_DOUBLE> ...
    <S_LONG> ...
    <S_HEX> ...
    <S_IDENTIFIER> ...
    <S_CHAR_LITERAL> ...
    <S_QUOTED_IDENTIFIER> ...
    "(" ...
    "*" ...
    "?" ...
    "+" ...
    "@@" ...
    "-" ...
    "{d" ...
    "{t" ...
    "{ts" ...
    ":" ...
    "@" ...
    "{fn" ...
    "SKIP" ...
    "FIRST" ...
    "ALL" ...
    "DISTINCT" ...
    "UNIQUE" ...
    "TOP" ...
    "*" ...
    <S_IDENTIFIER> ...
    <S_QUOTED_IDENTIFIER> ...
    "CAST" ...
    "DO" ...
    "EXTRACT" ...
    "FIRST" ...
    "FOLLOWING" ...
    "LAST" ...
    "MATERIALIZED" ...
    "NULLS" ...
    "PARTITION" ...
    "RANGE" ...
    "ROW" ...
    "ROWS" ...
    "SIBLINGS" ...
    "VALUE" ...
    "XML" ...
    "COLUMN" ...
    "REPLACE" ...
    "TRUNCATE" ...
    "KEY" ...
    "ANY" ...
    "OPEN" ...
    "OVER" ...
    "VALUES" ...
    "PERCENT" ...
    "PRIOR" ...
    "SEPARATOR" ...
    "NO" ...
    "ACTION" ...
    "CASCADE" ...
    "END" ...
    "TABLE" ...
    <K_DATETIMELITERAL> ...
    <S_IDENTIFIER> ...
    <S_QUOTED_IDENTIFIER> ...
    "CAST" ...
    "DO" ...
    "EXTRACT" ...
    "FIRST" ...
    "FOLLOWING" ...
    "LAST" ...
    "MATERIALIZED" ...
    "NULLS" ...
    "PARTITION" ...
    "RANGE" ...
    "ROW" ...
    "ROWS" ...
    "SIBLINGS" ...
    "VALUE" ...
    "XML" ...
    "COLUMN" ...
    "REPLACE" ...
    "TRUNCATE" ...
    "KEY" ...
    "ANY" ...
    "OPEN" ...
    "OVER" ...
    "VALUES" ...
    "PERCENT" ...
    "PRIOR" ...
    "SEPARATOR" ...
    "NO" ...
    "ACTION" ...
    "CASCADE" ...
    "END" ...
    "TABLE" ...
    <K_DATETIMELITERAL> ...
    <S_IDENTIFIER> ...
    <S_QUOTED_IDENTIFIER> ...
    "CAST" ...
    "DO" ...
    "EXTRACT" ...
    "FIRST" ...
    "FOLLOWING" ...
    "LAST" ...
    "MATERIALIZED" ...
    "NULLS" ...
    "PARTITION" ...
    "RANGE" ...
    "ROW" ...
    "ROWS" ...
    "SIBLINGS" ...
    "VALUE" ...
    "XML" ...
    "COLUMN" ...
    "REPLACE" ...
    "TRUNCATE" ...
    "KEY" ...
    "ANY" ...
    "OPEN" ...
    "OVER" ...
    "VALUES" ...
    "PERCENT" ...
    "PRIOR" ...
    "SEPARATOR" ...
    "NO" ...
    "ACTION" ...
    "CASCADE" ...
    "END" ...
    "TABLE" ...
    <K_DATETIMELITERAL> ...
    <S_IDENTIFIER> ...
    <S_QUOTED_IDENTIFIER> ...
    "CAST" ...
    "DO" ...
    "EXTRACT" ...
    "FIRST" ...
    "FOLLOWING" ...
    "LAST" ...
    "MATERIALIZED" ...
    "NULLS" ...
    "PARTITION" ...
    "RANGE" ...
    "ROW" ...
    "ROWS" ...
    "SIBLINGS" ...
    "VALUE" ...
    "XML" ...
    "COLUMN" ...
    "REPLACE" ...
    "TRUNCATE" ...
    "KEY" ...
    "ANY" ...
    "OPEN" ...
    "OVER" ...
    "VALUES" ...
    "PERCENT" ...
    "PRIOR" ...
    "SEPARATOR" ...
    "NO" ...
    "ACTION" ...
    "CASCADE" ...
    "END" ...
    "TABLE" ...
    <K_DATETIMELITERAL> ...
    "NULL" ...
    "CASE" ...
    "+" ...
    "-" ...
    "?" ...
    "+" ...
    "-" ...
    ":" ...
    "+" ...
    "-" ...
    "@" ...
    "@@" ...
    "+" ...
    "-" ...
    ":" ...
    <S_IDENTIFIER> ...
    <S_IDENTIFIER> ...
    "EXTRACT" ...
    "GROUP_CONCAT" ...
    "+" ...
    "-" ...
    <S_IDENTIFIER> ...
    <S_QUOTED_IDENTIFIER> ...
    "CAST" ...
    "DO" ...
    "EXTRACT" ...
    "FIRST" ...
    "FOLLOWING" ...
    "LAST" ...
    "MATERIALIZED" ...
    "NULLS" ...
    "PARTITION" ...
    "RANGE" ...
    "ROW" ...
    "ROWS" ...
    "SIBLINGS" ...
    "VALUE" ...
    "XML" ...
    "COLUMN" ...
    "REPLACE" ...
    "TRUNCATE" ...
    "KEY" ...
    "ANY" ...
    "OPEN" ...
    "OVER" ...
    "VALUES" ...
    "PERCENT" ...
    "PRIOR" ...
    "SEPARATOR" ...
    "NO" ...
    "ACTION" ...
    "CASCADE" ...
    "END" ...
    "TABLE" ...
    <K_DATETIMELITERAL> ...
    <S_IDENTIFIER> ...
    <S_QUOTED_IDENTIFIER> ...
    "CAST" ...
    "DO" ...
    "EXTRACT" ...
    "FIRST" ...
    "FOLLOWING" ...
    "LAST" ...
    "MATERIALIZED" ...
    "NULLS" ...
    "PARTITION" ...
    "RANGE" ...
    "ROW" ...
    "ROWS" ...
    "SIBLINGS" ...
    "VALUE" ...
    "XML" ...
    "COLUMN" ...
    "REPLACE" ...
    "TRUNCATE" ...
    "KEY" ...
    "ANY" ...
    "OPEN" ...
    "OVER" ...
    "VALUES" ...
    "PERCENT" ...
    "PRIOR" ...
    "SEPARATOR" ...
    "NO" ...
    "ACTION" ...
    "CASCADE" ...
    "END" ...
    "TABLE" ...
    <K_DATETIMELITERAL> ...
    <S_IDENTIFIER> ...
    <S_QUOTED_IDENTIFIER> ...
    "CAST" ...
    "DO" ...
    "EXTRACT" ...
    "FIRST" ...
    "FOLLOWING" ...
    "LAST" ...
    "MATERIALIZED" ...
    "NULLS" ...
    "PARTITION" ...
    "RANGE" ...
    "ROW" ...
    "ROWS" ...
    "SIBLINGS" ...
    "VALUE" ...
    "XML" ...
    "COLUMN" ...
    "REPLACE" ...
    "TRUNCATE" ...
    "KEY" ...
    "ANY" ...
    "OPEN" ...
    "OVER" ...
    "VALUES" ...
    "PERCENT" ...
    "PRIOR" ...
    "SEPARATOR" ...
    "NO" ...
    "ACTION" ...
    "CASCADE" ...
    "END" ...
    "TABLE" ...
    <K_DATETIMELITERAL> ...
    <S_IDENTIFIER> ...
    <S_QUOTED_IDENTIFIER> ...
    "CAST" ...
    "DO" ...
    "EXTRACT" ...
    "FIRST" ...
    "FOLLOWING" ...
    "LAST" ...
    "MATERIALIZED" ...
    "NULLS" ...
    "PARTITION" ...
    "RANGE" ...
    "ROW" ...
    "ROWS" ...
    "SIBLINGS" ...
    "VALUE" ...
    "XML" ...
    "COLUMN" ...
    "REPLACE" ...
    "TRUNCATE" ...
    "KEY" ...
    "ANY" ...
    "OPEN" ...
    "OVER" ...
    "VALUES" ...
    "PERCENT" ...
    "PRIOR" ...
    "SEPARATOR" ...
    "NO" ...
    "ACTION" ...
    "CASCADE" ...
    "END" ...
    "TABLE" ...
    <K_DATETIMELITERAL> ...
    "+" ...
    "-" ...
    "{fn" ...
    <S_IDENTIFIER> ...
    <S_QUOTED_IDENTIFIER> ...
    "CAST" ...
    "DO" ...
    "EXTRACT" ...
    "FIRST" ...
    "FOLLOWING" ...
    "LAST" ...
    "MATERIALIZED" ...
    "NULLS" ...
    "PARTITION" ...
    "RANGE" ...
    "ROW" ...
    "ROWS" ...
    "SIBLINGS" ...
    "VALUE" ...
    "XML" ...
    "COLUMN" ...
    "REPLACE" ...
    "TRUNCATE" ...
    "KEY" ...
    "ANY" ...
    "OPEN" ...
    "OVER" ...
    "VALUES" ...
    "PERCENT" ...
    "PRIOR" ...
    "SEPARATOR" ...
    "NO" ...
    "ACTION" ...
    "CASCADE" ...
    "END" ...
    "TABLE" ...
    <K_DATETIMELITERAL> ...
    "LEFT" ...
    "RIGHT" ...
    "SET" ...
    "DOUBLE" ...
    "+" ...
    "-" ...
    <S_DOUBLE> ...
    "+" ...
    "-" ...
    <S_LONG> ...
    "+" ...
    "-" ...
    <S_HEX> ...
    "+" ...
    "-" ...
    "CAST" ...
    <K_TIME_KEY_EXPR> ...
    <K_DATETIMELITERAL> ...
    "+" ...
    "-" ...
    <S_IDENTIFIER> ...
    <S_QUOTED_IDENTIFIER> ...
    "CAST" ...
    "DO" ...
    "EXTRACT" ...
    "FIRST" ...
    "FOLLOWING" ...
    "LAST" ...
    "MATERIALIZED" ...
    "NULLS" ...
    "PARTITION" ...
    "RANGE" ...
    "ROW" ...
    "ROWS" ...
    "SIBLINGS" ...
    "VALUE" ...
    "XML" ...
    "COLUMN" ...
    "REPLACE" ...
    "TRUNCATE" ...
    "KEY" ...
    "ANY" ...
    "OPEN" ...
    "OVER" ...
    "VALUES" ...
    "PERCENT" ...
    "PRIOR" ...
    "SEPARATOR" ...
    "NO" ...
    "ACTION" ...
    "CASCADE" ...
    "END" ...
    "TABLE" ...
    <K_DATETIMELITERAL> ...
    <S_IDENTIFIER> ...
    <S_QUOTED_IDENTIFIER> ...
    "CAST" ...
    "DO" ...
    "EXTRACT" ...
    "FIRST" ...
    "FOLLOWING" ...
    "LAST" ...
    "MATERIALIZED" ...
    "NULLS" ...
    "PARTITION" ...
    "RANGE" ...
    "ROW" ...
    "ROWS" ...
    "SIBLINGS" ...
    "VALUE" ...
    "XML" ...
    "COLUMN" ...
    "REPLACE" ...
    "TRUNCATE" ...
    "KEY" ...
    "ANY" ...
    "OPEN" ...
    "OVER" ...
    "VALUES" ...
    "PERCENT" ...
    "PRIOR" ...
    "SEPARATOR" ...
    "NO" ...
    "ACTION" ...
    "CASCADE" ...
    "END" ...
    "TABLE" ...
    <K_DATETIMELITERAL> ...
    <S_IDENTIFIER> ...
    <S_QUOTED_IDENTIFIER> ...
    "CAST" ...
    "DO" ...
    "EXTRACT" ...
    "FIRST" ...
    "FOLLOWING" ...
    "LAST" ...
    "MATERIALIZED" ...
    "NULLS" ...
    "PARTITION" ...
    "RANGE" ...
    "ROW" ...
    "ROWS" ...
    "SIBLINGS" ...
    "VALUE" ...
    "XML" ...
    "COLUMN" ...
    "REPLACE" ...
    "TRUNCATE" ...
    "KEY" ...
    "ANY" ...
    "OPEN" ...
    "OVER" ...
    "VALUES" ...
    "PERCENT" ...
    "PRIOR" ...
    "SEPARATOR" ...
    "NO" ...
    "ACTION" ...
    "CASCADE" ...
    "END" ...
    "TABLE" ...
    <K_DATETIMELITERAL> ...
    <S_IDENTIFIER> ...
    <S_QUOTED_IDENTIFIER> ...
    "CAST" ...
    "DO" ...
    "EXTRACT" ...
    "FIRST" ...
    "FOLLOWING" ...
    "LAST" ...
    "MATERIALIZED" ...
    "NULLS" ...
    "PARTITION" ...
    "RANGE" ...
    "ROW" ...
    "ROWS" ...
    "SIBLINGS" ...
    "VALUE" ...
    "XML" ...
    "COLUMN" ...
    "REPLACE" ...
    "TRUNCATE" ...
    "KEY" ...
    "ANY" ...
    "OPEN" ...
    "OVER" ...
    "VALUES" ...
    "PERCENT" ...
    "PRIOR" ...
    "SEPARATOR" ...
    "NO" ...
    "ACTION" ...
    "CASCADE" ...
    "END" ...
    "TABLE" ...
    <K_DATETIMELITERAL> ...
    "+" ...
    "-" ...
    "(" ...
    "+" ...
    "-" ...
    "(" ...
    <S_CHAR_LITERAL> ...
    "{d" ...
    "{t" ...
    "{ts" ...
    "INTERVAL" ...
    "FIRST" ...
    <S_IDENTIFIER> ...
    <S_QUOTED_IDENTIFIER> ...
    "CAST" ...
    "DO" ...
    "EXTRACT" ...
    "FIRST" ...
    "FOLLOWING" ...
    "LAST" ...
    "MATERIALIZED" ...
    "NULLS" ...
    "PARTITION" ...
    "RANGE" ...
    "ROW" ...
    "ROWS" ...
    "SIBLINGS" ...
    "VALUE" ...
    "XML" ...
    "COLUMN" ...
    "REPLACE" ...
    "TRUNCATE" ...
    "KEY" ...
    "ANY" ...
    "OPEN" ...
    "OVER" ...
    "VALUES" ...
    "PERCENT" ...
    "PRIOR" ...
    "SEPARATOR" ...
    "NO" ...
    "ACTION" ...
    "CASCADE" ...
    "END" ...
    "TABLE" ...
    <K_DATETIMELITERAL> ...
    <S_IDENTIFIER> ...
    <S_QUOTED_IDENTIFIER> ...
    "CAST" ...
    "DO" ...
    "EXTRACT" ...
    "FIRST" ...
    "FOLLOWING" ...
    "LAST" ...
    "MATERIALIZED" ...
    "NULLS" ...
    "PARTITION" ...
    "RANGE" ...
    "ROW" ...
    "ROWS" ...
    "SIBLINGS" ...
    "VALUE" ...
    "XML" ...
    "COLUMN" ...
    "REPLACE" ...
    "TRUNCATE" ...
    "KEY" ...
    "ANY" ...
    "OPEN" ...
    "OVER" ...
    "VALUES" ...
    "PERCENT" ...
    "PRIOR" ...
    "SEPARATOR" ...
    "NO" ...
    "ACTION" ...
    "CASCADE" ...
    "END" ...
    "TABLE" ...
    <K_DATETIMELITERAL> ...
    <S_IDENTIFIER> ...
    <S_QUOTED_IDENTIFIER> ...
    "CAST" ...
    "DO" ...
    "EXTRACT" ...
    "FIRST" ...
    "FOLLOWING" ...
    "LAST" ...
    "MATERIALIZED" ...
    "NULLS" ...
    "PARTITION" ...
    "RANGE" ...
    "ROW" ...
    "ROWS" ...
    "SIBLINGS" ...
    "VALUE" ...
    "XML" ...
    "COLUMN" ...
    "REPLACE" ...
    "TRUNCATE" ...
    "KEY" ...
    "ANY" ...
    "OPEN" ...
    "OVER" ...
    "VALUES" ...
    "PERCENT" ...
    "PRIOR" ...
    "SEPARATOR" ...
    "NO" ...
    "ACTION" ...
    "CASCADE" ...
    "END" ...
    "TABLE" ...
    <K_DATETIMELITERAL> ...
    <S_IDENTIFIER> ...
    <S_QUOTED_IDENTIFIER> ...
    "CAST" ...
    "DO" ...
    "EXTRACT" ...
    "FIRST" ...
    "FOLLOWING" ...
    "LAST" ...
    "MATERIALIZED" ...
    "NULLS" ...
    "PARTITION" ...
    "RANGE" ...
    "ROW" ...
    "ROWS" ...
    "SIBLINGS" ...
    "VALUE" ...
    "XML" ...
    "COLUMN" ...
    "REPLACE" ...
    "TRUNCATE" ...
    "KEY" ...
    "ANY" ...
    "OPEN" ...
    "OVER" ...
    "VALUES" ...
    "PERCENT" ...
    "PRIOR" ...
    "SEPARATOR" ...
    "NO" ...
    "ACTION" ...
    "CASCADE" ...
    "END" ...
    "TABLE" ...
    <K_DATETIMELITERAL> ...
    
	at net.sf.jsqlparser.parser.CCJSqlParser.generateParseException(CCJSqlParser.java:15112)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_consume_token(CCJSqlParser.java:14968)
	at net.sf.jsqlparser.parser.CCJSqlParser.SelectItem(CCJSqlParser.java:2862)
	at net.sf.jsqlparser.parser.CCJSqlParser.SelectItemsList(CCJSqlParser.java:2712)
	at net.sf.jsqlparser.parser.CCJSqlParser.PlainSelect(CCJSqlParser.java:2351)
	at net.sf.jsqlparser.parser.CCJSqlParser.SelectBody(CCJSqlParser.java:2242)
	at net.sf.jsqlparser.parser.CCJSqlParser.Select(CCJSqlParser.java:2229)
	at net.sf.jsqlparser.parser.CCJSqlParser.SingleStatement(CCJSqlParser.java:129)
	at net.sf.jsqlparser.parser.CCJSqlParser.Statement(CCJSqlParser.java:80)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:52)
	... 23 more`

please help me!!! thanks a lot!!

**Comment by wumpz** [comment]
Sorry. At the moment JSqlParser does not support this construct (sql conditions) within the selector. Another example is
`select value in (select ... from) ...`

**Comment by extremesecrecy** [comment]
BUMP. I'm also trying to parse through code with T/SQL statements like the one above. Have we heard from PullRequest? :) Maybe there was a second attempt?

**Comment by sarxos** [comment]
Hello everyone :)

This still seems to be a limit in 2019, but... there is a workaround. To get rid of this issue you have to use  `CASE WHEN`. Just change query like this:

```sql
select exists(select 1 from test where id = :id)
```

Into this:

```sql
select case when exists(select 1 from test where id = :id) then 1 else 0 end
```

Weird? Yes. But it works.
