### ISSUE TITLE
ParseException on Informix outer join specific syntax

### ISSUE THREAD

**Issue by prldev** [JSQLParser/JSqlParser#364]
When trying to parse an Informix SQL query with specific OUTER syntax, JSqlParser
 throw 
`net.sf.jsqlparser.parser.ParseException: Encountered " "OUTER" "OUTER "" at line 1, column 39`

This is probably the same as issue #238 which was closed because of missing examples, therefore I open a new one.

Here are two sample SQL queries:
`SELECT DISTINCT t1.f1, t2.f2 FROM t1, OUTER t2 WHERE t1.f3=1 AND t1.f4=t2.f4`

`SELECT t1.f1, t3.f2 FROM t1, OUTER (t2, t3) WHERE t1.f4=t2.f4 AND t2.f5=t3.f5`

**Comment by manticore-projects** [comment]
Works with JSQLParser-4.2
