### ISSUE TITLE
Old style oracle join

### ISSUE THREAD

**Issue by mxdan** [JSQLParser/JSqlParser#366]
My query is correct for Oracle

```
SELECT
	A1.ID "#ID"
FROM
       SCHEME.Z#TAB1 A1
      ,SCHEME.C#TAB2 C3
WHERE 1=1
      AND A3.ID = C3.ID(+) AND nvl(C3.FIELD(+), 0) <> 256;

```
It's coorect to use (+) in some expressions like NVL. COALESCE, etc.
How can I fix it?

Thanks!

**Comment by wumpz** [comment]
That would be quite a change since the oracle operator is at the moment parsed as a part of a relation. You have to put it in expression but then the parser would allow + on both sides.  Tricky. IMHO normal join syntax should be the way to go, but I guess that is not an option for you.

**Comment by mxdan** [comment]
Thanks a lot. Yes, tricky. But I found another way for my case. Before parsing I comment all entries of (+) and it works.
