### ISSUE TITLE
Support for grave accent : `

### ISSUE THREAD

**Issue by dprutean** [JSQLParser/JSqlParser#370]
The character ` is used in some scripts as name delimiter. Now the code returns the table and column names including this character: `apmtsuserroletype`, etc. Could you please consider it as delimiter and reduce it ?

Thank you,
Dragos

CREATE TABLE `apmtsuserroletype` (
  `mtsUserRoleTypeID` int(10) NOT NULL AUTO_INCREMENT,
  `age` int(10) NOT NULL
);

CREATE TABLE `wfworkflowstepuserrole` (
  `workflowStepUserRoleID` int(10) NOT NULL AUTO_INCREMENT,
  `stepID` int(10) NOT NULL,
  `mtsUserRoleTypeID` int(10) NOT NULL,
  `needsReplication` int(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`workflowStepUserRoleID`),
  KEY `stepforrole` (`stepID`),
  KEY `roleforstep` (`mtsUserRoleTypeID`),
  CONSTRAINT `roleforstep` FOREIGN KEY (`mtsUserRoleTypeID`) REFERENCES `apmtsuserroletype` (`mtsUserRoleTypeID`) ON DELETE CASCADE,
  CONSTRAINT `stepforrole` FOREIGN KEY (`stepID`) REFERENCES `wfstep` (`stepID`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 
COMMENT='Pivot table to pull together a step and a user role. This would allow any user with a particular role to complete a workflow step.';

**Comment by wumpz** [comment]
Where in your example is this accent?

**Comment by dprutean** [comment]
The text I pasted has this character inside, but the forum software removed it and highlighted the text. 

    On Wednesday, December 14, 2016 5:05 PM, Tobias <notifications@github.com> wrote:
 

 Where in your example is this accent?—

**Comment by wumpz** [comment]
;). Markupstuggle. Now I now what you mean. 
This behaviour is by intention. JSqlParser supports different kinds of quotation of identifiers. ("col", [col], or `col`). As different dbms have different standard name case JSqlParser is not able to guess the right case. Therefore one could not get the original intention. 
Using Oracle "col" <> col but using PostgreSQL "col" = col.
