### ISSUE TITLE
support "force index"

### ISSUE THREAD

**Issue by sealedbook** [JSQLParser/JSqlParser#374]
e.g
SELECT 
    tel.*, ti.task_type
FROM
    HTtask.task_info AS ti,
    HTtask.task_exercise_log AS tel FORCE INDEX (IDX_T_E_L_MODIFY_DATE)
WHERE
    ti.id = tel.task_info_id

**Comment by dhlin** [comment]
Will `force/ignore/use index` key words be supported in the future?
