### ISSUE TITLE
Causing Exception [ia.attnum-1] - this type of expression

### ISSUE THREAD

**Issue by afariha** [JSQLParser/JSqlParser#378]
```
net.sf.jsqlparser.JSQLParserException
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parseStatements(CCJSqlParserUtil.java:124)
Caused by:
net.sf.jsqlparser.parser.ParseException: Encountered " <S_QUOTED_IDENTIFIER> "[ia.attnum-1] "" at line 1, column 439.
Was expecting one of:
    <EOF> 
    "FOR" ...
    "GROUP" ...
    "HAVING" ...
    "START" ...
    "CONNECT" ...
    ";" ...
    "(" ...
    "|" ...
    "&" ...
    "^" ...
    "::" ...
    "(" ...
    "(" ...
    "::" ...
    "^" ...
    "|" ...
    "&" ...
    "(" ...
    "START" ...
    "CONNECT" ...
    "GROUP" ...
    "HAVING" ...
    "FOR" ...
    "(" ...
    "(" ...
    "::" ...
    "^" ...
    "|" ...
    "&" ...
    "(" ...
    "(" ...
    "(" ...
    "(" ...
    "::" ...
    "^" ...
    "|" ...
    "&" ...
    "(" ...
    "(" ...
    "(" ...
    
	at net.sf.jsqlparser.parser.CCJSqlParser.generateParseException(CCJSqlParser.java:20535)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_consume_token(CCJSqlParser.java:20386)
	at net.sf.jsqlparser.parser.CCJSqlParser.Statements(CCJSqlParser.java:421)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parseStatements(CCJSqlParserUtil.java:122)
	
```
Query Was:

`select ta.attname, ia.attnum, ic.relname, n.nspname, tc.relname from pg_catalog.pg_attribute ta, pg_catalog.pg_attribute ia, pg_catalog.pg_class tc, pg_catalog.pg_index i, pg_catalog.pg_namespace n, pg_catalog.pg_class ic where tc.relname = 'business' and n.nspname = 'public' and tc.oid = i.indrelid and n.oid = tc.relnamespace and i.indisprimary = 't' and ia.attrelid = i.indexrelid and ta.attrelid = i.indrelid and ta.attnum = i.indkey[ia.attnum-1] and (not ta.attisdropped) and (not ia.attisdropped) and ic.oid = i.indexrelid order by ia.attnum`

**Comment by wumpz** [comment]
Unfortunately JSqlParser supports only numerical array indexes. Some DBMS using brackets to enclose object names 
`select [a]`
JSqlParser supports this. You see both scenarios are overlapping without a clean separation.
