### ISSUE TITLE
Alter tab support for 'change'

### ISSUE THREAD

**Issue by HeleneLf** [JSQLParser/JSqlParser#380]
This script cannot be parsed : Alter table X change column a b Double null default null;
It throws :
Caused by: net.sf.jsqlparser.parser.ParseException: Encountered " <S_IDENTIFIER> "CHANGE "" at line 5, column 1.
Was expecting one of:
    "DROP" ...
    "ADD" ...

Please add support for CHANGE.

Regards

**Comment by wumpz** [comment]
Pull requests are wellcome. Or is this something your want to contribute to differently ?

**Comment by HeleneLf** [comment]
This is a pull request.

**Comment by wumpz** [comment]
??? Where is the source code of your pull request? Did I overlooked it?

**Comment by wumpz** [comment]
No problem, I was only kind of suprised ;).

**Comment by liuluheng** [comment]
also not support `ALTER TABLE `t` ALTER COLUMN `c` set default 1;`

**Comment by wumpz** [comment]
Which database supports 'change'? I only know 'modify'.

**Comment by Gikkman** [comment]
Ah, I came here looking for a solution to this issue too. 
MySQL supports a query for the following form:

`
ALTER TABLE model
  CHANGE modelid modeluid INT(10) UNSIGNED NOT NULL;
`

As explained in [this StackOverflow answer](https://stackoverflow.com/a/14767467/1943559), CHANGE is used to rename a column. So what the above query means is basically "Change column modelid, rename it to modeluid, and then do the following changes to its type".
