### ISSUE TITLE
Failure to parse Select * from test  with(nolock) 

### ISSUE THREAD

**Issue by Dickfp** [JSQLParser/JSqlParser#383]
does JSqlParser support the keyword 'with'  now?

**Comment by wumpz** [comment]
The keyword is supported but not for your usecase. `With `is used for CTEs.
```
with t as (select c fom mytab)
select * from mytab2 inner join t on mytab2.a = t.c
```

**Comment by Dickfp** [comment]
oh , so  is there any way to solve this problem?

thanks!!

**Comment by wumpz** [comment]
Not yet. Unfortunately I have no time to do some stuff here, but merging pull requests. There are already issues regarding this:  #236 #248.

**Comment by Dickfp** [comment]
Anyway,thank you for your answers.

**Comment by AnEmortalKid** [comment]
I think this was fixed by https://github.com/JSQLParser/JSqlParser/commit/9ce74e234e09525f6af557095cf938c8bb456708

**Comment by wumpz** [comment]
Correct.
