### ISSUE TITLE
Does JSQLParser protect from injection?

### ISSUE THREAD

**Issue by salex89** [JSQLParser/JSqlParser#387]
Sorry for opening a request, but I didn't find another way to ask. Does building a query with JSQLParser protect from SQL injection in any way?

**Comment by wumpz** [comment]
Jsqlparser is more a parser than a builder. Nevertheless Sql injection is possible if parameters are included in a specific way. Using Prepared statements is here the way to go.

A posible way to ask questions is the Gitter Channel or stackoverflow. 

Cheers Tobias

**Comment by salex89** [comment]
Thanks!
