### ISSUE TITLE
Wrong parse replace into...

### ISSUE THREAD

**Issue by brozikcz** [JSQLParser/JSqlParser#389]
"replace into table(key, data) values(1, "aaa")" is parsed as "REPLACE TABLE(key, data) VALUES(1, "aaa")" without INTO... 

"insert or replace into..." ended with net.sf.jsqlparser.JSQLParserException

`/System.err: Caused by: net.sf.jsqlparser.parser.ParseException: Encountered " "OR" "OR "" at line 1, column 8.
01-24 14:33:39.471 8465-8465/? W/System.err: Was expecting one of:
01-24 14:33:39.471 8465-8465/? W/System.err:     "DO" ...`

Version: 0.9.6

**Comment by brozikcz** [comment]
Thx! :)

**Comment by wumpz** [comment]
resolved into issue
