### ISSUE TITLE
IntervalExpression parameter is a string not expression

### ISSUE THREAD

**Issue by ryanmurf** [JSQLParser/JSqlParser#391]
IntervalExpression
https://github.com/JSQLParser/JSqlParser/blob/master/src/main/java/net/sf/jsqlparser/expression/IntervalExpression.java

parameter is a string. This actually can be an expression.

**Comment by wumpz** [comment]
Its been a while ... :)

You are right. At the moment only string values or number + interval token values are allowed.

**Comment by wumpz** [comment]
Actually I tried to use expressions using Postgresql and was not able to get it syntactically right. As it is mentioned here: https://www.postgresql.org/docs/9.6/static/functions-datetime.html Postgresql does not seem to support expressions here. So what database do you use and could you give me some examples?

**Comment by ryanmurf** [comment]
Sorry for the slow response. It does look like Postgresql only supports strings. Mysql supports `select date_sub(CURDATE(), interval int_column+23 DAY) from table`. I haven't tested but I am sure other databases also support similar syntax. I will submit a PR if you think it will be helpful.

**Comment by ryanmurf** [comment]
https://github.com/JSQLParser/JSqlParser/pull/414

**Comment by wumpz** [comment]
JSqlParser 4.0 parses this.
