### ISSUE TITLE
select has sub query can't parse

### ISSUE THREAD

**Issue by kingj1261** [JSQLParser/JSqlParser#394]
There is a sql can't be parsed,the sql is very simple but why can't be parsed?

select aa.* , t.* from accenter.all aa , (select a.* from pacioli.emc_plan a) t

the error like this

Caused by: net.sf.jsqlparser.parser.ParseException: Encountered " "." ". "" at line 1, column 32.
Was expecting one of:
    <EOF> 
    "AS" ...
    "DO" ...
    "ANY" ...
    "KEY" ...
    "PERCENT" ...
    "END" ...
    "JOIN" ...
    "LEFT" ...
    "CROSS" ...
    "OPEN" ...
    "FULL" ...
    "TABLE" ...
    "WHERE" ...
    "FOR" ...
    "PIVOT" ...
    "XML" ...
    "GROUP" ...
    "INNER" ...
    "RIGHT" ...
    "VALUE" ...
    "HAVING" ...
    "VALUES" ...
    "NATURAL" ...
    "REPLACE" ...
    "TRUNCATE" ...
    "CAST" ...
    "OVER" ...
    "PARTITION" ...
    "EXTRACT" ...
    "MATERIALIZED" ...
    "START" ...
    "CONNECT" ...
    "PRIOR" ...
    "SIBLINGS" ...
    "COLUMN" ...
    "NULLS" ...
    "FIRST" ...
    "LAST" ...
    "ROWS" ...
    "RANGE" ...
    "FOLLOWING" ...
    "ROW" ...
    "SEPARATOR" ...
    "CASCADE" ...
    "NO" ...
    "ACTION" ...
    <K_DATETIMELITERAL> ...
    ";" ...
    <S_IDENTIFIER> ...
    <S_QUOTED_IDENTIFIER> ...
    "," ...
    "PIVOT" ...
    "PIVOT" ...
    "AS" ...
    <S_IDENTIFIER> ...
    <S_QUOTED_IDENTIFIER> ...
    "CAST" ...
    "DO" ...
    "EXTRACT" ...
    "FIRST" ...
    "FOLLOWING" ...
    "LAST" ...
    "MATERIALIZED" ...
    "NULLS" ...
    "PARTITION" ...
    "RANGE" ...
    "ROW" ...
    "ROWS" ...
    "SIBLINGS" ...
    "VALUE" ...
    "XML" ...
    "COLUMN" ...
    "REPLACE" ...
    "TRUNCATE" ...
    "KEY" ...
    "ANY" ...
    "OPEN" ...
    "OVER" ...
    "VALUES" ...
    "PERCENT" ...
    "PRIOR" ...
    "SEPARATOR" ...
    "NO" ...
    "ACTION" ...
    "CASCADE" ...
    "END" ...
    "TABLE" ...
    <K_DATETIMELITERAL> ...
    "LEFT" ...
    "RIGHT" ...
    "FULL" ...
    "INNER" ...
    "NATURAL" ...
    "CROSS" ...
    "JOIN" ...
    "," ...
    "WHERE" ...
    "START" ...
    "CONNECT" ...
    "GROUP" ...
    "HAVING" ...
    "FOR" ...
    
	at net.sf.jsqlparser.parser.CCJSqlParser.generateParseException(CCJSqlParser.java:15112)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_consume_token(CCJSqlParser.java:14968)
	at net.sf.jsqlparser.parser.CCJSqlParser.Statement(CCJSqlParser.java:90)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:52)
	... 30 more

**Comment by wumpz** [comment]
After digging into it, the main problem is the use of `all `as a tablename. This is a keyword. The query parses successfully if you use `all2`.

**Comment by wumpz** [comment]
I am not sure if one should allow all keywords as identifier names. That would make parsing a lot harder. All is one of these that would could trouble.

**Comment by wumpz** [comment]
So the minimum problem SQL is:
`select * from all`
