### ISSUE TITLE
Deparsing a LIKE expression produces an invalid syntax

### ISSUE THREAD

**Issue by MGelbana** [JSQLParser/JSqlParser#398]
The LIKE expression is considered a binary expression with 2 operators, the column and the compared value.

While [this method](https://github.com/JSQLParser/JSqlParser/blob/master/src/main/java/net/sf/jsqlparser/util/deparser/ExpressionDeParser.java#L281) deparses the LIKE expression, it could possible write **NOT** before the like expression, if it's negated. Leading to this: `NOT CNAME LIKE VALUE` where **CNAME** is the column name and **VALUE** is a user provided value

**Comment by wumpz** [comment]
Dont understand what you mean:
`select * from mytable where not col like 'test'`
is a valid sql syntax.

**Comment by MGelbana** [comment]
I didn't know that ! Pardon me.
