### ISSUE TITLE
Postgresql Create Table using UNION fails

### ISSUE THREAD

**Issue by Shivasish** [JSQLParser/JSqlParser#402]
Postgresql : SQL having create from the UNION of two tables throws parse exception.

Example query : 
create table temp.abc as (select sku from temp.a union select sku from temp.b)

Using : 0.9.7-SNAPSHOT version

Exception as below : 

Caused by:
net.sf.jsqlparser.parser.ParseException: Encountered " "UNION" "union "" at line 1, column 50.
Was expecting one of:
    "AS" ...
    "DO" ...
    "ANY" ...
    "KEY" ...
    "PERCENT" ...
    "END" ...
    "JOIN" ...
    "LEFT" ...
    "CROSS" ...
    "OPEN" ...
    "FULL" ...
    "TABLE" ...
    "WHERE" ...
    "FOR" ...
    "PIVOT" ...
    "XML" ...
    "GROUP" ...
    "INNER" ...
    "RIGHT" ...
    "VALUE" ...
    "HAVING" ...
    "VALUES" ...
    "NATURAL" ...
    "REPLACE" ...
    "TRUNCATE" ...
    "CAST" ...
    "OVER" ...
    "PARTITION" ...
    "EXTRACT" ...
    "MATERIALIZED" ...
    "START" ...
    "CONNECT" ...
    "PRIOR" ...
    "SIBLINGS" ...
    "COLUMN" ...
    "NULLS" ...
    "FIRST" ...
    "LAST" ...
    "ROWS" ...
    "RANGE" ...
    "FOLLOWING" ...
    "ROW" ...
    "COMMIT" ...
    "SEPARATOR" ...
    "CASCADE" ...
    "NO" ...
    "ACTION" ...
    <K_DATETIMELITERAL> ...
    "PRECISION" ...
    <S_IDENTIFIER> ...
    <S_QUOTED_IDENTIFIER> ...
    "," ...
    ")" ...
    "PIVOT" ...
    "PIVOT" ...
    "AS" ...
    <S_IDENTIFIER> ...
    <S_QUOTED_IDENTIFIER> ...
    "CAST" ...
    "DO" ...
    "EXTRACT" ...
    "FIRST" ...
    "FOLLOWING" ...
    "LAST" ...
    "MATERIALIZED" ...
    "NULLS" ...
    "PARTITION" ...
    "RANGE" ...
    "ROW" ...
    "ROWS" ...
    "SIBLINGS" ...
    "VALUE" ...
    "XML" ...
    "COLUMN" ...
    "REPLACE" ...
    "TRUNCATE" ...
    "KEY" ...
    "ANY" ...
    "OPEN" ...
    "OVER" ...
    "VALUES" ...
    "PERCENT" ...
    "PRIOR" ...
    "SEPARATOR" ...
    "NO" ...
    "ACTION" ...
    "CASCADE" ...
    "END" ...
    "TABLE" ...
    <K_DATETIMELITERAL> ...
    "COMMIT" ...
    "PRECISION" ...
    "LEFT" ...
    "RIGHT" ...
    "FULL" ...
    "INNER" ...
    "NATURAL" ...
    "CROSS" ...
    "JOIN" ...
    "," ...
    "WHERE" ...
    "START" ...
    "CONNECT" ...
    "GROUP" ...
    "HAVING" ...
    "FOR" ...
    
	at net.sf.jsqlparser.parser.CCJSqlParser.generateParseException(CCJSqlParser.java:16160)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_consume_token(CCJSqlParser.java:16013)
	at net.sf.jsqlparser.parser.CCJSqlParser.SelectBody(CCJSqlParser.java:2289)
	at net.sf.jsqlparser.parser.CCJSqlParser.Select(CCJSqlParser.java:2269)
	at net.sf.jsqlparser.parser.CCJSqlParser.CreateTable(CCJSqlParser.java:8653)
	at net.sf.jsqlparser.parser.CCJSqlParser.SingleStatement(CCJSqlParser.java:162)
	at net.sf.jsqlparser.parser.CCJSqlParser.Statement(CCJSqlParser.java:79)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:52)

**Comment by wumpz** [comment]
JSqlParser did not support the parenthesis syntax.

**Comment by preetbawa** [comment]
we are doing some query analytics and using jsqlparser - i had similar query like one posted above where within create statement nested select of union of two tables and wanted to extract setop, table name etc. Any plans to support this in future. please let me know.

**Comment by wumpz** [comment]
Do you want to provide a pull request or push someway this feature? Nevertheless I will look into it.
