### ISSUE TITLE
Unknown DEFERRABLE Keyword

### ISSUE THREAD

**Issue by cmoine** [JSQLParser/JSqlParser#407]
I am trying to parse the following string:

`ALTER TABLE TBL_S_TNE`
`ADD CONSTRAINT cst_pk_S_TNE`
`    PRIMARY KEY (S_I) DEFERRABLE NOVALIDATE;`

Am I obtain:
net.sf.jsqlparser.parser.ParseException: Encountered " <S_IDENTIFIER> "DEFERRABLE "" at line 3, column 23.
Was expecting one of:
    <EOF> 
    ";" ...
    "," ...

PS: you can ask me for a Pull Request if you are interested.

**Comment by wumpz** [comment]
Interested in PR ;).

**Comment by cmoine** [comment]
Here it is :) The coverage has slightly decreased because I am not testing getter and setter I think. Is it acceptable though ?
