### ISSUE TITLE
Compile Error on checkout master/some tags -  Missing classes? (CCJSqlParser.java)

### ISSUE THREAD

**Issue by mbecca** [JSQLParser/JSqlParser#408]
Hi,
(My english is bad)
I'm trying checkout master ( and tag: 0.9.7) and the project not compile (For example miss CCJSqlParser.java )

Thanks in advance.

M.

**Comment by wumpz** [comment]
This class is generated by javacc. To build JSQLPARSER you should use maven. Then all the missing files will be generated.

**Comment by mbecca** [comment]
Thanks!!!!, Sorry for not knowing

**Comment by wumpz** [comment]
No problem. Thx for using JSqlParser.
Cheers Tobias
