### ISSUE TITLE
Is JSqlParser ready for the first major version 1.0?

### ISSUE THREAD

**Issue by wumpz** [JSQLParser/JSqlParser#409]
Someone asked why **JSqlParser** (or me) is not following the maven standard versioning? That is a very good question. The time I got into this project, **JSqlParser** was at version 0.7 I think. The versioning kept the same format. So now version 0.9.8-SNAPSHOT is the actual one. 

_Are there any complaints to release it to version 1.0?_

So far JSqlParser has come a long way. Are there any **problems, issues, improvements** that should be adressed before going to the first major version?

**Comment by AnEmortalKid** [comment]
Looking through  the issues, I see a lot of:
- "Support for", "Does JsqlParser not support BLAH". 
 - To me, this would be enhancements and not a critical issue
- "My sql didn't parse"
 - Once again, not a critical issue. 

Regarding: 
> rewrite of SelectBody - production, reduce of needed lookaheads results in huge parser performance improvements at least in some cases
> please test it due to possible changes in the parse tree

Feels like a major release anyway. Even if we do break things, people would know based on semver that this change contains changes that would make them have to update their code / be cautious about updating and making sure they regression tested things. 

I have no problem with 0.9.8 being released as a 1.0.

**Comment by ryanmurf** [comment]
I agree
