### ISSUE TITLE
SourceCode conventions for comitters ...

### ISSUE THREAD

**Issue by wumpz** [JSQLParser/JSqlParser#415]
JSqlParser does not have a coding convention wiki page or stuff like that. It would be nice to have some kind of checks over this.

To adress this a checkstyle - plugin will be integreated.

At the moment it will test and **produce a fail** for:

* tabs instead of spaces within source code files
* usage of Windows or MAC Linefeeds

My intention was to activate this by default. 

Are there any complaints or suggestions for improvement?

**Comment by wumpz** [comment]
Travis seems to have problems using this plugin.

**Comment by wumpz** [comment]
Travis seems to have problems using this plugin. 

Some other rules are now configured.

At the moment the check is started using

checkstyle:check -Pcheck.sources

**Comment by wumpz** [comment]
I removed the linefeed stuff, because I dont know the git lf checkout type of a committer.

**Comment by AnEmortalKid** [comment]
It would be nice if we could have formatter files for the major ides:
- eclipse, intellij and netbeans

**Comment by AnEmortalKid** [comment]
@wumpz i've used checkstyle and I think it is fine. you can define the checkstyle conventions within the project under a src/etc/checkstyle :)

**Comment by wumpz** [comment]
What would be the drawback of defining it within the pom? Reusage? I included it already with some simple checks.
Other projects define an eclipse formatter config or a textual description, but I think checkstyle should be sufficient.
Linefeed check seems to be a problem due to gits autocrlf settings. Maybe that is something travis or codax could do.

-------- Ursprüngliche Nachricht --------
Von: AnEmortalKid <notifications@github.com> 
Datum: 15.04.2017  06:42  (GMT+01:00) 
An: JSQLParser/JSqlParser <JSqlParser@noreply.github.com> 
Cc: Tobias <t.warneke@gmx.net>, Mention <mention@noreply.github.com> 
Betreff: Re: [JSQLParser/JSqlParser] SourceCode conventions for comitters ...
  (#415) 

@wumpz i've used checkstyle and I think it is fine. you can define the checkstyle conventions within the project under a src/etc/checkstyle :)

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/JSQLParser/JSqlParser","title":"JSQLParser/JSqlParser","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/JSQLParser/JSqlParser"}},"updates":{"snippets":[{"icon":"PERSON","message":"@AnEmortalKid in #415: @wumpz i've used checkstyle and I think it is fine. you can define the checkstyle conventions within the project under a src/etc/checkstyle :)"}],"action":{"name":"View Issue","url":"https://github.com/JSQLParser/JSqlParser/issues/415#issuecomment-294271939"}}}​​

**Comment by wumpz** [comment]
checkstyle integrated as a main build part
