### ISSUE TITLE
Can Column  override equals() method?

### ISSUE THREAD

**Issue by ty332309254** [JSQLParser/JSqlParser#416]
```java
Update jsqlSql = (Update) CCJSqlParserUtil.parse(someSql);
List<Column> columns = jsqlSql.getColumns();
List<String> columnNames = new ArrayList<String>();
for (Column column : columns) {
columnNames.add(column.getColumnName());
}
columns.contains("xxxxx")
```

**What I want?**

```java
private static final Column xxx=new Column("xxxxx");

jsqlSql.getColumns().contains(xxx);

````

**Comment by wumpz** [comment]
That should not be a problem. But to be correct Table should get an equals as well. 

Do you want to provide a pull request?

**Comment by ty332309254** [comment]
Column has member Table, Table has member Database,Alias,Pivot.
so I dont't konw how to do with equals method.
In my opinion, they are the same as they have the same name.

**Comment by AnEmortalKid** [comment]
Two columns with the same name might not be the same column, it would depend on the table reference (if they both have one). Since you can have:

TABLE_A.COLUMN_A,
TABLE_B.COLUMN_A, 

Both would have getColumnName return COLUMN_A

**Comment by wumpz** [comment]
JSqlParser cannot know about different tables. Therefore it would be simple textual equality. One could use the toString Methods result to compare it. Since this would be true for all generated objects, one could build a baseclass with an equality check by using toString.

**Comment by wumpz** [comment]
After thinking a little bit longer, I withdraw my idea. There are at the moment already classes that could not be differed by using toString, e.g. JDBCParamter, which holds a sometimes invisible index. Also using columns someone wants a case insensitiv check.

@ty332309254: If you are using Java 8, you could do something like: 

```
List<String> values = Arrays.asList("column1", "column2", "column3", "COLUMN4", "column5");

System.out.println(values.stream().anyMatch(col -> col.equals("column3")));
System.out.println(values.stream().anyMatch(col -> col.equals("column4")));
System.out.println(values.stream().anyMatch(col -> col.equalsIgnoreCase("column4")));
```

which is more / simpler configurable (IMHO).

**Comment by ty332309254** [comment]
Thank U, I will have a try.
