### ISSUE TITLE
Create a working visitor

### ISSUE THREAD

**Issue by cmoine** [JSQLParser/JSqlParser#422]
There should a default visitor that automatically iterate over the Statements, call the corresponding visit() according to the statement type and so on.

Don't hesitate if you want a PR ;)

**Comment by wumpz** [comment]
Look at the visitor adapters. Another method would be to use a Deparser.

**Comment by cmoine** [comment]
The existing visitor doesn't fullfill my requirements:
- StatementVisitorAdapter has only default implementation
- DeParser output the AST into the string
I would like a default visitor to traverse AST nodes.

I did this for my purpose, I think it could be usefull for other users:
`package net.sf.jsqlparser.statement;

import net.sf.jsqlparser.statement.alter.Alter;
import net.sf.jsqlparser.statement.create.index.CreateIndex;
import net.sf.jsqlparser.statement.create.table.CreateTable;
import net.sf.jsqlparser.statement.create.view.AlterView;
import net.sf.jsqlparser.statement.create.view.CreateView;
import net.sf.jsqlparser.statement.delete.Delete;
import net.sf.jsqlparser.statement.drop.Drop;
import net.sf.jsqlparser.statement.execute.Execute;
import net.sf.jsqlparser.statement.insert.Insert;
import net.sf.jsqlparser.statement.merge.Merge;
import net.sf.jsqlparser.statement.replace.Replace;
import net.sf.jsqlparser.statement.select.Select;
import net.sf.jsqlparser.statement.truncate.Truncate;
import net.sf.jsqlparser.statement.update.Update;

public class SimpleStatementVisitor extends StatementVisitorAdapter {
	@Override
	public void visit(Statements stmts) {
		for (Statement stmt : stmts.getStatements())
			visit(stmt);
	}

	private void visit(Statement stmt) {
		if (stmt instanceof CreateTable) {
			visit((CreateTable) stmt);
		} else if (stmt instanceof Insert) {
			visit((Insert) stmt);
		} else if (stmt instanceof Alter) {
			visit((Alter) stmt);
		} else if (stmt instanceof AlterView) {
			visit((AlterView) stmt);
		} else if (stmt instanceof CreateIndex) {
			visit((CreateIndex) stmt);
		} else if (stmt instanceof CreateView) {
			visit((CreateView) stmt);
		} else if (stmt instanceof Delete) {
			visit((Delete) stmt);
		} else if (stmt instanceof Drop) {
			visit((Drop) stmt);
		} else if (stmt instanceof Execute) {
			visit((Execute) stmt);
		} else if (stmt instanceof Merge) {
			visit((Merge) stmt);
		} else if (stmt instanceof Replace) {
			visit((Replace) stmt);
		} else if (stmt instanceof Select) {
			visit((Select) stmt);
		} else if (stmt instanceof SetStatement) {
			visit((SetStatement) stmt);
		} else if (stmt instanceof Truncate) {
			visit((Truncate) stmt);
		} else if (stmt instanceof Update) {
			visit((Update) stmt);
		}
	}
}`

**Comment by wumpz** [comment]
I think you are missusing the visitor. One of its purposes is to get rid of this instanceof overuse. 

The visitor does not run only by itself but delegates to visit calls partially to the processed objects. Your point is the missing loop within StatementVisitorAdapter. Add added this. But it has to be implemented like this:

```
for (Statement statement : stmts.getStatements()) {
    statement.accept(this);
}
```
The statement itself calls the visitors method.

**Comment by cmoine** [comment]
Yes! You are right, I didn't figure out the entire pattern sorry. Your solution is clean. Could you please integrate it in the project ou do you prefer a PR ?

**Comment by wumpz** [comment]
Its already there ;). I pushed some minutes ago.
