### ISSUE TITLE
Failed to parse Create Table Query 

### ISSUE THREAD

**Issue by goti921** [JSQLParser/JSqlParser#423]
CREATE TABLE `merchant_param` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `merchantid` int(10) unsigned NOT NULL,
  `pg_id` int(5) DEFAULT NULL,
  `category` varchar(64) DEFAULT NULL,
  `ibibo_code` varchar(8) DEFAULT NULL,
  `key` char(64) NOT NULL,
  `value` mediumtext,
  `isactive` tinyint(1) NOT NULL,
  `addedon` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `updatedon` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `IDX_merchantid` (`merchantid`),
  KEY `idx_key` (`key`),
  KEY `merchantid_key` (`merchantid`,`key`)
) ENGINE=InnoDB AUTO_INCREMENT=371818 DEFAULT CHARSET=latin1

Exception Stack Trace:
Caused by: net.sf.jsqlparser.parser.ParseException: Encountered " "UPDATE" "UPDATE "" at line 1, column 431.
Was expecting one of:
    "ON" ...
    "KEY" ...
    "NOT" ...
    "NULL" ...
    "PRIMARY" ...
    "FOREIGN" ...
    "REFERENCES" ...
    "ROWS" ...
    "COMMIT" ...
    "UNIQUE" ...
    <S_DOUBLE> ...
    <S_LONG> ...
    <S_IDENTIFIER> ...
    <S_CHAR_LITERAL> ...
    "=" ...
    "," ...
    "(" ...
    ")" ...
    "+" ...
    "-" ...

       	at net.sf.jsqlparser.parser.CCJSqlParser.generateParseException(CCJSqlParser.java:13102)
       	at net.sf.jsqlparser.parser.CCJSqlParser.jj_consume_token(CCJSqlParser.java:12958)
       	at net.sf.jsqlparser.parser.CCJSqlParser.CreateTable(CCJSqlParser.java:6703)
       	at net.sf.jsqlparser.parser.CCJSqlParser.SingleStatement(CCJSqlParser.java:138)
       	at net.sf.jsqlparser.parser.CCJSqlParser.Statement(CCJSqlParser.java:67)
       	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:49)
       	... 30 common frames omitted

Maven Dependency:

        <dependency>
            <groupId>com.github.jsqlparser</groupId>
            <artifactId>jsqlparser</artifactId>
            <version>0.9.4</version>
        </dependency>

**Comment by wumpz** [comment]
Could you first go to the actual version? Does this work?

**Comment by goti921** [comment]
@wumpz 
I upgraded to version 0.9.7
It seems this release has the fix for my exception.

**Comment by wumpz** [comment]
The actual version is 1.0.

**Comment by goti921** [comment]
Yeah I have done that but I am facing another issue, this time with insert query parsing.
Please refer: https://github.com/JSQLParser/JSqlParser/issues/424

Meanwhile please go ahead and close this issue.
