### ISSUE TITLE
Include into readme some coding convention examples

### ISSUE THREAD

**Issue by wumpz** [JSQLParser/JSqlParser#432]

**Comment by AnEmortalKid** [comment]
Could this be done based on the checkstyle that you setup? (i might be able to look at the checkstyle and see what options you chose, ie:

```
blah() {
}
```
vs
```
 blah()
{

}
```

**Comment by wumpz** [comment]
I think not. The standard **LeftCurly** module has the default setting **eol**.
http://checkstyle.sourceforge.net/property_types.html#lcurly

**Comment by AnEmortalKid** [comment]
Yeah, I was asking what you wanted me to include in the readme, or what kind of examples :) I can try to edit something this weekend

**Comment by wumpz** [comment]
Didn't I push? A little example is already in the readme.

**Comment by AnEmortalKid** [comment]
Ah i hadn't seen your push to https://github.com/JSQLParser/JSqlParser/blob/master/README.md#source-code-conventions, I see it now :)
