### ISSUE TITLE
Caused by: net.sf.jsqlparser.parser.ParseException: Encountered " "IF" "if "" at line 3, column 5.

### ISSUE THREAD

**Issue by rogerxp** [JSQLParser/JSqlParser#435]
`<dependency>
		    <groupId>com.github.jsqlparser</groupId>
		    <artifactId>jsqlparser</artifactId>
		    <version>1.0</version>
		</dependency>`
This release edition is not supported "if" keyword in "select" clause. 
My SQL Caluse as below:
 
`select
    ap.id, -- 应付账款ID
    if(isnull(o.order_code), '集采退库', '集采入库') as business_type, -- 业务类型
    if(isnull(o.order_code), co.cancel_order_code, o.order_code) as order_code, -- 订单号
    si.stock_in_no,  -- 业务单据号
    si.erp_stock_in_no, -- ERP采购入库单号
    sid.stock_name as storage_name, -- 入库仓库名称
    ap.pay_object_code, -- 付款对象/供应商编号
    ap.pay_object_name, -- 付款对象/供应商名称
    si.asc_code, -- 店面编号/收款对象
    si.asc_name, -- 店面名称/收款对象
    li.logisticsName, -- 物流公司名称
    li.logistics_order_no, -- 物流单号
    ap.create_date, -- 发生日期/入账日期
    sum(sid.stock_in_count) as stock_in_count, -- 商品数量
    sum(sid.purchase_amount_taxed) as purchase_amount_taxed, -- 含税采购金额
    sum(sid.purchase_amount) as purchase_amount, -- 不含税采购金额
    0 as supplier_discount_amount, -- 供应商折扣金额
    0 as dec_discount_amount, -- 单品折扣金额
    sum(sid.purchase_amount_taxed) as pay_sub_discount  -- 折扣后应付
from account_payable ap
left join tm_order o on ap.tm_order_id = o.id and o.module_name = 'EP'
-- LEFT JOIN purchase_intention pi on o.purchase_intention_id = pi.id
left join tm_cancel_order co on ap.tm_cancel_order_id = co.id and co.module_name = 'EP'
-- LEFT JOIN cancel_purchase_intention cpi on co.cancel_purchase_intention_id = cpi.id
left join stock_in si on ap.stock_in_id = si.id
left join logistics_info li on si.logistics_info_id = li.id
left join stock_in_detail sid on si.id = sid.stock_in_id
where (o.order_code is not null or co.cancel_order_code is not null)`

**Comment by wumpz** [comment]
This was indeed a bug within the grammar, that was introduced recently by correcting some function name possibilities..
