### ISSUE TITLE
National character ( N'') syntax not supported 

### ISSUE THREAD

**Issue by freepath-it** [JSQLParser/JSqlParser#438]
Hi,
the following syntas is not parsable:
SELECT N'national character' FROM table;

the N prefix on string is meant to identify an unicode string. I didnt find a better reference then this one:
http://stackoverflow.com/questions/18521928/the-n-in-the-where-clause-of-sql

The syntax is supported, and in some case needed, for example union with a nvarchar and a literal string in the same position on two different sql of the union) both from oracle and postgresql (didnt test other databases).

Regards,
Silvano

**Comment by freepath-it** [comment]
Hi,
i have attached a pull request for this issuse. The parser is now able to correclty parse the query, but the test fails. The fix is missing something, any idea/suggestion how to properly fix it ?

**Comment by thomaszbz** [comment]
SQL Server (TSQL) also uses that (see #267).
