### ISSUE TITLE
Allow an ExpressionDeParser instance to be injected into StatementDeParser

### ISSUE THREAD

**Issue by chrycheng** [JSQLParser/JSqlParser#442]
Is there a reason why, unlike other `DeParser` s like `InsertDeParser` and `SelectDeParser`, you aren't allowed to inject an `ExpressionDeParser` instance?  I could see this being useful, for example, when you want to create a translator from one SQL dialect to another.  You would code the translation of, for example, string concatenation from `||` to `concat(...)` in the `visit(Concat)` method of an `ExpressionDeParser`.  Then in order to apply this translation to all statements where it could occur, you would use the proposed enhanced `StatementDeParser` and then pass your `ExpressionDeParser` instance.  This appears to be a straightforward enough change so I think I can manage a pull request if approved.

**Comment by wumpz** [comment]
You know,  JSqlParser is feature request driven. That's why it is not there. I can follow your argumentation. Looking forward to your pr.

**Comment by chrycheng** [comment]
Of course.  I wanted to create an issue first so we could take about it if necessary.  Working on the PR now.

**Comment by chrycheng** [comment]
Would it be acceptable to you if I picked only one `ExpressionDeParser` method to verify to have been called in the test?  Also, would it be OK if I use [Mockito](http://site.mockito.org/) in the test?

**Comment by chrycheng** [comment]
Sorry about that.  Clicked the wrong button.  It seems I don't have privileges to assign myself the issue.  Could you do that for me please?

**Comment by wumpz** [comment]
Assigned you ... , I have no problem including some kind of mocking framework, as long as it is only a test dependency.
I am not quit sure if I understand your question about the method called once. Could you make an example, what do you want to test.

**Comment by chrycheng** [comment]
Of course.  I will make sure that the Mockito dependency is added only within the test scope.

Please refer to [`StatementDeParserTest`](https://github.com/chrycheng/JSqlParser/blob/30ef321710ce124c480eb66332233662c5e0c332/src/test/java/net/sf/jsqlparser/util/deparser/StatementDeParserTest.java) for the following paragraphs.

The `shouldUseProvidedExpressionDeparserWhenDeParsingInsert` test is what I meant in my previous comment.  I give a concrete SQL statement as input and then verify that the `ExpressionDeParser` is interacted with as expected.  However, I only checked the interaction through one `visit` overload.  I think it would be too cumbersome to test for all the `visit` overloads in this style.

On the other hand, the `shouldUseProvidedExpressionDeparserWhenDeParsingDelete` test does not need to verify interaction with each `visit` overload in `ExpressionDeParser`.  Instead I only need to verify that the `ExpressionDeParser` is used to visit each of the statement parts where an expression could occur.

The first style is [black-box testing](https://en.wikipedia.org/wiki/Black-box_testing) but doesn't seem as comprehensive as the second style.  I myself prefer the latter but I would like to consider your opinion on the matter.

**Comment by wumpz** [comment]
I would go with the latter one as well.

By the way you are instaniating a CCJSqlParserManager. You could use CCJSqlParserUtil to avoid all that boiler plate stuff (new, StringReader, ..).

**Comment by chrycheng** [comment]
Just pushed more new commits.  It seems evident to me now that we should also inject the `SelectDeParser`.  The assertions in the tests for insert and replace seems to me to indicate that the [Law of Demeter](https://en.wikipedia.org/wiki/Law_of_Demeter) are being violated.  Would you have any concerns if I update the issue to include `SelectDeParser`?  `InsertDeParser` and `UpdateDeParser` are two other `DeParser`s that can accept `SelectDeParser`s in their constructors.

**Comment by wumpz** [comment]
@chrycheng: no concerns here

**Comment by chrycheng** [comment]
`ExecuteDeParser` doesn't use the `ExpressionVisitor` passed.  Is this intentional or may I go ahead and file a separate issue for this?  It would block this issue so I can assign it to myself as well.

**Comment by wumpz** [comment]
No it isnt. It's legacy code.

**Comment by chrycheng** [comment]
Created issue #446.  Please assign it to me.

**Comment by chrycheng** [comment]
Fixed by 9d680a6.
