### ISSUE TITLE
Array literal: Mismatich parenthesis parsing for ANY

### ISSUE THREAD

**Issue by tserr** [JSQLParser/JSqlParser#443]
The parsing of an AnyComparisonExpression skips closing bracket if an ArrayLiteral is enclosed.

```
ANY ( ARRAY [ 2, 3 ] )
```

leads to an parsing error. Instead
```
ANY ( ARRAY [ 2, 3 ] 
```
is expected.

The following patch fixes this for me:
```patch
diff --git a/src/main/jjtree/net/sf/jsqlparser/parser/JSqlParserCC.jjt b/src/main/jjtree/net/sf/jsqlparser/parser/JSqlParserCC.jjt
index 52760a2..bce415f 100644
--- a/src/main/jjtree/net/sf/jsqlparser/parser/JSqlParserCC.jjt
+++ b/src/main/jjtree/net/sf/jsqlparser/parser/JSqlParserCC.jjt
@@ -1881,13 +1881,13 @@ Expression AnyComparisonExpression() :
 {
  (<K_ANY> { anyType = AnyType.ANY; } | <K_SOME> { anyType = AnyType.SOME; } ) 
  "(" 
-    (subselect=SubSelect() ")" { retval = new AnyComparisonExpression(anyType, subselect); }
+    (subselect=SubSelect() { retval = new AnyComparisonExpression(anyType, subselect); }
      |array = ArrayLiteral() { 
        if (anyType == AnyType.SOME)
          throw new IllegalStateException("SOME not allowed with ARRAY");
        retval = new AnyArrayExpression(array); 
     } 
-    )
+    ) ")"
    {
       return retval;
    }
```

@opeongo: What do think about this patch? Should I generate a separate branch and a pull request?

**Comment by wumpz** [comment]
Skip this pull request. I will look into it. Seems like a grammar error.

**Comment by wumpz** [comment]
Ah. My mistake. You are disussing an existing branch but not main.

**Comment by opeongo** [comment]
I have sent in a pull request to fix this issue with the literal array
syntax, as well as implementing tests and deparsing correctly.  Hopefully
this feature is ready to pull in to the master branch.

Tom

**Comment by manticore-projects** [comment]
[This works with latest 4.1](http://jsqlformatter.manticore-projects.com/jsqlformatter/demo.html?args=-c%20M4UwNiDGAuAECCA5AmrAFAgSp+qDasATADSwDMsAurAJQBQQA+)
