### ISSUE TITLE
Cannot resolve "ROW_NUMBER() OVER(PARTITION BY COLUMN ORDER BY COLUMN)"

### ISSUE THREAD

**Issue by ulyn** [JSQLParser/JSqlParser#445]
ORACLE SQL: 
select  E.ID_NUMBER,row_number()over(partition by E.ID_NUMBER order by E.DEFINED_UPDATED desc) rn from T_EMPLOYMENT E

**Comment by wumpz** [comment]
What do you mean by cannot resolve? Using JSqlParser 1.1 I was able to parse your statement. Older versions should work as well.

**Comment by ulyn** [comment]
Thanks for your reply.It's my fault, sorry!
