### ISSUE TITLE
Use the ExpressionDeParser to de-parse AnalyticExpressions

### ISSUE THREAD

**Issue by chrycheng** [JSQLParser/JSqlParser#452]
Revision 066199c of `ExpressionDeParser` de-parses `AnalyticExpression`s by simply taking the value of the `toString` method.  Shouldn't the `ExpressionDeParser` be made to visit the `Expression`s that make up the `AnalyticExpression`?

I'd like to take a crack at this so please go ahead and assign it to me if you approve.

**Comment by wumpz** [comment]
You are digging deep 👍 .

**Comment by chrycheng** [comment]
Fixed by 81de7a6.

**Comment by wumpz** [comment]
So are these github squashed commits ok for you?

**Comment by chrycheng** [comment]
Actually, I personally prefer `--no-ff` merges but it's your repo so it's your rules 😃

**Comment by wumpz** [comment]
The question was about the squashing. Some developers prefer to squash by themselfs. And I prefer one commit PRs. So I use happily githubs Squash & Merge.

**Comment by chrycheng** [comment]
I see.  No problem!  I'll squash all subsequent PRs for this repo.
