### ISSUE TITLE
Parse JdbcNamedParameters with the same name as a keyword

### ISSUE THREAD

**Issue by chrycheng** [JSQLParser/JSqlParser#456]
An example statement is `select * from t where c = :from`.  [Attached](https://github.com/JSQLParser/JSqlParser/files/1013925/debug-output.txt) is the output of a test with [parser debugging enabled](https://github.com/JSQLParser/JSqlParser/wiki/Examples-of-SQL-parsing#visualize-parsing).  I'm not really familiar with JavaCC but from what I can tell from `JdbcNamedParameter`'s [definition](https://github.com/JSQLParser/JSqlParser/blob/275fbbe87fa0adab9181a1fd80ba313c88f32f3c/src/main/jjtree/net/sf/jsqlparser/parser/JSqlParserCC.jjt#L2254) in `JSqlParserCC.jjt`, it's expected to be composed of a `:` and an `S_IDENTIFIER`.  `S_IDENTIFIER`'s [definition](https://github.com/JSQLParser/JSqlParser/blob/275fbbe87fa0adab9181a1fd80ba313c88f32f3c/src/main/jjtree/net/sf/jsqlparser/parser/JSqlParserCC.jjt#L311) itself seems to have no restriction regarding keywords.  Please correct me if I'm wrong.

**Comment by wumpz** [comment]
Unfortunately you are wrong. That is a common problem of those kind of parser generators. The on front running tokenizer delivers at that point in the grammar the k_from token. The best fitting token is deliverered. The tokenizing is done before the grammar rules are being processed.

**Comment by chrycheng** [comment]
Do you mean this is a limitation of JavaCC which we cannot fix or work around?

**Comment by wumpz** [comment]
No. I  meant you cannot expect a char literal at this position.  One could improve by using RelObjectName which includes already a lot of keywords.
