### ISSUE TITLE
introduce absolute token positions 

### ISSUE THREAD

**Issue by wumpz** [JSQLParser/JSqlParser#457]
This one was already mentioned here #303. JSqlParser introduces thos col/line positions for tokens. That is not always sufficient. 

Therefore absolute positions should be introduced.

**Comment by AnEmortalKid** [comment]
I think as long as it still prints the col/line I am okay with having the extra information.

**Comment by wumpz** [comment]
Thus position does not replace col line information.

**Comment by AnEmortalKid** [comment]
Ah that's good, the samples from the article he had linked didn't have the line/col info :)
