### ISSUE TITLE
getFullyQualifiedName

### ISSUE THREAD

**Issue by MBP888** [JSQLParser/JSqlParser#461]
class Table method getFullyQualifiedName,the return value will have two "."

 @Override
    public String getFullyQualifiedName() {
        String fqn = "";

        if (database != null) {
            fqn += database.getFullyQualifiedName();
        }
        if (!fqn.isEmpty()) {
            fqn += ".";
        }

        if (schemaName != null) {
            fqn += schemaName;
        }
        if (!fqn.isEmpty()) {
            fqn += ".";
        }

        if (name != null) {
            fqn += name;
        }

        return fqn;
    }

**Comment by wumpz** [comment]
Look at #458.
