### ISSUE TITLE
WITH TIMEZONE

### ISSUE THREAD

**Issue by dprutean** [JSQLParser/JSqlParser#468]
Please check this statement:

CREATE TABLE country_region (
    regionid                       BIGINT
	                                   NOT NULL 
                                       CONSTRAINT pk_auth_region PRIMARY KEY,
    region_name                    VARCHAR(100)
	                                   NOT NULL,
    creation_date                  TIMESTAMP(0) WITH TIME ZONE
	                                   DEFAULT CURRENT_TIMESTAMP(0)
	                                   NOT NULL,
    last_change_date               TIMESTAMP(0) WITH TIME ZONE
	                                   DEFAULT CURRENT_TIMESTAMP(0),
    CONSTRAINT region_name_unique UNIQUE ( region_name )
); 

Encountered " <K_DATETIMELITERAL> "TIME "" at line 7, column 54.
Was expecting one of:
    "ON" ...
    "KEY" ...
    "NOT" ...
    "NULL" ...
    "WITH" ...
    "WHERE" ...
    "USING" ...
    "DELETE" ...
    "UPDATE" ...
    "PRIMARY" ...
    "FOREIGN" ...
    "CONSTRAINT" ...
    "REFERENCES" ...
    "CHECK" ...
    "ROWS" ...
    "COMMIT" ...
    "UNIQUE" ...
    "CASCADE" ...
    <K_TIME_KEY_EXPR> ...
    "TABLESPACE" ...
    "EXCLUDE" ...
    <S_DOUBLE> ...
    <S_LONG> ...
    <S_IDENTIFIER> ...
    <S_CHAR_LITERAL> ...
    "=" ...
    "," ...
    "(" ...
    ")" ...
    "+" ...
    "-" ...

**Comment by wumpz** [comment]
The problem is the precision for the timestamp type. JSqlParser does not support this. So
`TIMESTAMP(0) WITH TIME ZONE `
is a problem while
`TIMESTAMP WITH TIME ZONE`
is not.

The `DT_ZONE` token of JSqlParser should be improved to support this. 
Do you want to implement this feature or support it otherwise?

**Comment by wumpz** [comment]
fix not yet deployed to maven repo.
