### ISSUE TITLE
can not parser in expression

### ISSUE THREAD

**Issue by ghost** [JSQLParser/JSqlParser#471]
String in = "(SSN,SSM) IN (('11111111111111', '22222222222222'))";
 final List exprList = new ArrayList();
    Expression inExpr =  CCJSqlParserUtil.parseCondExpression(in);

 -- Exception --net.sf.jsqlparser.JSQLParserException

**Comment by AnEmortalKid** [comment]
Would you mind setting the parser to debug so we can see what tokens it ended up creating or anything that gives us more info about the exception?

**Comment by sennysun** [comment]
![image](https://user-images.githubusercontent.com/20810844/28310558-6e3afda2-6bdf-11e7-9504-e56982dde06a.png)

**Comment by sennysun** [comment]
@AnEmortalKid

**Comment by wumpz** [comment]
`(SSN,SSM) IN ('11111111111111', '22222222222222')`

is parsed perfectly well. JSqlParser does not accept your double parenthesis around the in expression list. Are you sure, this is valid and for which database?

**Comment by AnEmortalKid** [comment]
Should be fixed by #997

**Comment by wumpz** [comment]
Merged seconds ago.
