### ISSUE TITLE
ColumnsNameFinder

### ISSUE THREAD

**Issue by TimengHero** [JSQLParser/JSqlParser#472]
I want have a util class such as the demo of TablesNamesFinder.java 
  Now, I need parser the sql for my project. I want have a class that can find all used columns and it's alias within an statement.
Please teach me how to writer the class.
Thank you very march!

**Comment by wumpz** [comment]
Look here: https://stackoverflow.com/questions/40908062/parsing-table-and-column-names-from-sql-hql-java

Hope that helps.
