### ISSUE TITLE
Can CCJSqlParserUtil.parseExpression parse "a in (1,2)"

### ISSUE THREAD

**Issue by sennysun** [JSQLParser/JSqlParser#474]
I just want to parse the expression after where ,not all the sql :
```
Expression expression = CCJSqlParserUtil.parseExpression("a in (1,2)");
            expression.accept(visitor);
            System.out.println(exprList.get(0).toString()+"~~~~~~~~~~~~~~~~left expression");
            System.out.println(exprList.get(1)+"~~~~~~~~~~~~~~~left items list");
            System.out.println(exprList.get(2).toString()+"~~~~~~~~~~~~~~~~right items list");
```
But it turns out that expression is a column not an InExpression

**Comment by sennysun** [comment]
![1500370067 1](https://user-images.githubusercontent.com/20810844/28310264-77d5d856-6bde-11e7-9e3e-be32346178ee.png)

**Comment by wumpz** [comment]
You should use **CCJSqlParserUtil.parseCondExpression**. **parseExpression** parses the first complete expression. An expression is not a condition within JSqlParser.
JSqlParser does not check using parseExpression to parse all of its input.
