### ISSUE TITLE
can't parse the sql which the having before group by statement

### ISSUE THREAD

**Issue by TimengHero** [JSQLParser/JSqlParser#476]
When parse the sql :select e.job from emp e  group by e.job having count(e.job)>1 ; I can have a good result. But change the sql as select e.job from emp e having count(e.job)>1 group by e.job; the parser will throws ParseException at below:
Caused by: net.sf.jsqlparser.parser.ParseException: Encountered " "GROUP" "group "" at line 1, column 47.
Was expecting one of:
    <EOF> 
    "AND" ...
    "FOR" ...
    "UNION" ...
    "ORDER" ...
    "INTERSECT" ...
    "EXCEPT" ...
    "MINUS" ...
    ";" ...
    "(" ...
    "|" ...
    "&" ...
    "^" ...
    "::" ...
    "ORDER" ...
    "ORDER" ...
    "::" ...
    "^" ...

I want the parser can support the sql where is having before group by statement.
Please give support to us, thank you!

**Comment by wumpz** [comment]
JSqlParser only supports _group by ... having_.  Which database allows to change this order?

**Comment by wumpz** [comment]
Or did I miss understand you. Do you want to fund this feature? Was your question about getting technical support?

**Comment by TimengHero** [comment]
I am test the sql : select e.job from emp e having count(e.job)>1 group by e.job; at the oracle database, it is execute success. When I use "SimpleNode node = (SimpleNode) CCJSqlParserUtil.parseAST(sql);" it had throws the ParserException.
![default](https://user-images.githubusercontent.com/28652856/28551561-4bc99602-711b-11e7-98cf-2455daff60b4.png)

**Comment by AnEmortalKid** [comment]
That's because, currently the parser only supports `group by... having`, and not the other way around. If you wanted it to support `having ... group by`, someone would have to change the grammar.

**Comment by wumpz** [comment]
Like I already said :)
