### ISSUE TITLE
Cannot parse query

### ISSUE THREAD

**Issue by chumanhquang** [JSQLParser/JSqlParser#477]
SELECT
    *
FROM
    t1 a
    INNER JOIN (
        t2 b
        INNER JOIN t3 c ON (
            b.field1 = c.field1
        )
        INNER JOIN t4 d ON (
            b.field2 = d.field2
        )
    ) ON (
            a.field3 = b.field3
        AND
            a.field4 = b.field4
    )
    INNER JOIN t5 e ON (
            a.field5 = e.field5_cde
        AND
            e.field6 = '0'
    )
LEFT OUTER JOIN
    t6 f
ON (
        f.field3 = c.field3
);

Caused by: net.sf.jsqlparser.parser.ParseException: Encountered " "INNER" "INNER "" at line 1, column 138.
Was expecting one of:
    "AND" ...
    ")" ...
    "AND" ...

**Comment by wumpz** [comment]
JSqlParser does at the moment not support join hierarchies. I dont know the tech spec name for this construct. This will work:

```
select * from mytable
left join a on ....
left join b on ...
```
