### ISSUE TITLE
Expression to be used for boolean condition evaluation

### ISSUE THREAD

**Issue by thefragmenter** [JSQLParser/JSqlParser#478]
The following String:

`x=92 and y=29`

Produces a valid output: x=92 AND y=29 and it works fine with CCJSqlParserUtil.parseCondExpression but shouldn't it throw an exception for the following?

`x=92 lasd =29`

But the output is just: x=92

Furthermore which Expression one must use if I were to implement my own visitor? i.e,
```
CCJSqlParser c= new CCJSqlParser(new StringReader(str));
Expression e = c.Expression(); // or SimpleExpression, etc..
```

Which of the visit method will retrieve the 'lasd' (anything other than not,or,and) so that I can throw an exception?

**Comment by wumpz** [comment]
Using parseExpression and parsCond do not use the whole string like the normal parse does. It's all about the longest construct that is found. So a visitor will not help. Either one has to implement a new production for this or has to check the AST nodes if the whole thing was used.

**Comment by thefragmenter** [comment]
Can you elaborate on 'new production'?  With regards to checking AST nodes, any examples on this one or test cases that I can look into?

**Comment by thefragmenter** [comment]
I was able to validate it by prepending the condition string with a simple SELECT statement. Is this valid for my example or I'm overlooking at something? `CCJSqlParserUtil.parse("SELECT 1 from dual() WHERE "+str);`

**Comment by wumpz** [comment]
A production is an new rule within the grammar. If you search AST within the tests you should find some examples. 
Since you are not the first one to ask this I would go for the production way. 

I will look into it.

**Comment by wumpz** [comment]
introduced extention to parseExpression and parsCond to make a full parse.
