### ISSUE TITLE
My SQL contains “FOR XML PATH”, it can not pass the CCJSqlParserUtil.parse (SQL);

### ISSUE THREAD

**Issue by 305088020** [JSQLParser/JSqlParser#479]
my sql is 
```
SELECT
            SHEBEI_ID AS ID,*,(
                SELECT
                  *
                FROM
                  V_BANKA_NEW BANKA
                WHERE
                  BANKA.BANKA_DELETE_FLAG = 0
                AND SHEBEI.SHEBEI_ID = BANKA.BANKA_PEISHUSHEBEI
                FOR XML PATH('data')
            ) BANKA
        FROM
          V_SHEBEI_NEW SHEBEI

```
it contains "FOR XML PATH"
Run `CCJSqlParserUtil.parse(sql); `error reporting

**Comment by wumpz** [comment]
Give us the exception throwed.

**Comment by 305088020** [comment]
![e00beda4-d352-4d59-b871-e0a9f3229cc9](https://user-images.githubusercontent.com/15034602/28621726-76b73a8e-7244-11e7-9875-20c3f20d0fb2.png)

**Comment by wumpz** [comment]
Looked into it. JSqlParser does not yet support **for xml path** construct.

**Comment by thapld** [comment]
Have any idea can resolve this problem?

**Comment by wumpz** [comment]
@thapld Started analyzing problem. hope I can provide a solution soon.
