### ISSUE TITLE
Named parameter :date does not parse

### ISSUE THREAD

**Issue by CodingFabian** [JSQLParser/JSqlParser#485]
```
select * from tab where tab.date = :date
```

**Comment by wumpz** [comment]
This was solved recently. Nevertheless I included your testcase and it parses perfectly.

I dont know the issue id, but if you use 10.2-SNAPSHOT and still go this error, try to build JSqlParser from actual sources. I was a bit lazy publishing the latest 10.2-SNAPSHOT to sonatype.

**Comment by CodingFabian** [comment]
Right, I knew I saw this, but could not find it anymore (because the commit just said fixes #456) Tahnks fo the good woork. I might be opening a few more issues today, and then try to help resolving them. Unfortunately changing javacc or antlr grammer when you have not written them is quite hard.
