### ISSUE TITLE
Encountered " "CREATE" "create "" at line 10, column 1

### ISSUE THREAD

**Issue by david919** [JSQLParser/JSqlParser#486]
**Hi, I'm trying to parse a DDL script from MySQL and that gives me this exception:**

net.sf.jsqlparser.parser.ParseException: Encountered " "CREATE" "create "" at line 10, column 1.
Was expecting:
    <EOF> 
    
	at net.sf.jsqlparser.parser.CCJSqlParser.generateParseException(CCJSqlParser.java:16869)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_consume_token(CCJSqlParser.java:16722)
	at net.sf.jsqlparser.parser.CCJSqlParser.Statement(CCJSqlParser.java:91)
	at Parser.main(Parser.java:17)

**and the DDL script that I'm trying to parse is:**

CREATE TABLE `conf` (
  `conf_key` int NOT NULL COMMENT 'FK("code")',
  `conf_type` int NOT NULL COMMENT 'CODE("CONF_TYPE")',
  `conf_value` text NOT NULL COMMENT '配置值',
  `return_type` int NOT NULL COMMENT '返回类型:CODE("RETURN_TYPE")',
  `createddt` timestamp NULL COMMENT '插入时间',
  `updateddt` timestamp NULL COMMENT '更新时间',
  PRIMARY KEY (`conf_key`,`conf_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='配置表(CONF)';
create table conf_temp like conf;
CREATE TABLE `item_brand` (
  `item_url` varchar(255) NOT NULL,
  `brand_url` varchar(255) NOT NULL,
  `brand_name` varchar(100) DEFAULT NULL,
  `item_id` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`item_url`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
drop table `conf`,`item_brand`;
alter table conf drop column `createddt`;

**Thanks, David**

**Comment by wumpz** [comment]
Your example consists of multiple statements. To parse these you have to call:

`CCJSqlParserUtil.parseStatements`
