### ISSUE TITLE
exsits can't parse.

### ISSUE THREAD

**Issue by tjx222** [JSQLParser/JSqlParser#487]
parse sql : 
select a.*, b.*  from T1 a left join T2 b on a.id=b.id where 1=1 and exsits(select 1 from T3 r where r.gradeId = 12) and a.orgId = 11

excetion: 
net.sf.jsqlparser.util.TablesNamesFinderTest.testGetTableListWithLateral(TablesNamesFinderTest.java:175)
Caused by: net.sf.jsqlparser.parser.ParseException: Encountered " "(" "( "" at line 1, column 76.
Was expecting one of:
    <EOF> 
    "AND" ...
    "FOR" ...
    "UNION" ...
    "GROUP" ...
    "ORDER" ...
    "HAVING" ...
    "INTERSECT" ...
    "EXCEPT" ...
    "MINUS" ...
    "START" ...
    "CONNECT" ...
    ";" ...
    "ORDER" ...
    "ORDER" ...

**Comment by wumpz** [comment]
But in your query is not exists but exsits.

**Comment by AnEmortalKid** [comment]
does it work with `exists` ? @tjx222

**Comment by wumpz** [comment]
Exsits is not a valid sql keyword. Do you mean exists? Should I close this issue?
