### ISSUE TITLE
Encountered " "NULL" "null "" at line 1, column 1.

### ISSUE THREAD

**Issue by david919** [JSQLParser/JSqlParser#490]
**Hi, I'm trying to parse a DDL script from MySQL and that gives me this exception:**

net.sf.jsqlparser.JSQLParserException
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parseStatements(CCJSqlParserUtil.java:128)
	at Parser.main(Parser.java:47)
Caused by: net.sf.jsqlparser.parser.ParseException: Encountered " "NULL" "null "" at line 1, column 1.
Was expecting one of:
    "SET" ...
    "DROP" ...
    "WITH" ...
    "DELETE" ...
    "SELECT" ...
    "INSERT" ...
    "UPDATE" ...
    "UPSERT" ...
    "REPLACE" ...
    "TRUNCATE" ...
    "ALTER" ...
    "EXEC" ...
    "EXECUTE" ...
    "COMMIT" ...
    "MERGE" ...
    ";" ...
    "(" ...
    "ALTER" ...
    
	at net.sf.jsqlparser.parser.CCJSqlParser.generateParseException(CCJSqlParser.java:16869)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_consume_token(CCJSqlParser.java:16722)
	at net.sf.jsqlparser.parser.CCJSqlParser.SingleStatement(CCJSqlParser.java:200)
	at net.sf.jsqlparser.parser.CCJSqlParser.Statements(CCJSqlParser.java:241)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parseStatements(CCJSqlParserUtil.java:126)
	... 1 more
Caused by:
net.sf.jsqlparser.parser.ParseException: Encountered " "NULL" "null "" at line 1, column 1.
Was expecting one of:
    "SET" ...
    "DROP" ...
    "WITH" ...
    "DELETE" ...
    "SELECT" ...
    "INSERT" ...
    "UPDATE" ...
    "UPSERT" ...
    "REPLACE" ...
    "TRUNCATE" ...
    "ALTER" ...
    "EXEC" ...
    "EXECUTE" ...
    "COMMIT" ...
    "MERGE" ...
    ";" ...
    "(" ...
    "ALTER" ...
    
	at net.sf.jsqlparser.parser.CCJSqlParser.generateParseException(CCJSqlParser.java:16869)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_consume_token(CCJSqlParser.java:16722)
	at net.sf.jsqlparser.parser.CCJSqlParser.SingleStatement(CCJSqlParser.java:200)
	at net.sf.jsqlparser.parser.CCJSqlParser.Statements(CCJSqlParser.java:241)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parseStatements(CCJSqlParserUtil.java:126)
	at Parser.main(Parser.java:47)

**and the DDL script is:**

CREATE TABLE `conf` (
  `conf_key` int NOT NULL COMMENT 'FK("code")',
  `conf_type` int NOT NULL COMMENT 'CODE("CONF_TYPE")',
  `conf_value` text NOT NULL COMMENT '配置值',
  `return_type` int NOT NULL COMMENT '返回类型:CODE("RETURN_TYPE")',
  `createddt` timestamp NULL COMMENT '插入时间',
  `updateddt` timestamp NULL COMMENT '更新时间',
  PRIMARY KEY (`conf_key`,`conf_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='配置表(CONF)';
create table conf_temp like conf;
CREATE TABLE `item_brand` (
  `item_url` varchar(255) NOT NULL,
  `brand_url` varchar(255) NOT NULL,
  `brand_name` varchar(100) DEFAULT NULL,
  `item_id` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`item_url`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
drop table `conf`,`item_brand`;
alter table conf drop column `createddt`;

**Comment by wumpz** [comment]
Which statement is not parseable? Additional to your exception I assume that 

`create table conf_temp like conf;`

and 

`drop table conf,item_brand;`

are constructs not known to JSqlParser.

**Comment by david919** [comment]
None one of them is parseable. I tried each one particularlly, but it gives the same exception.

**Comment by wumpz** [comment]
Make a test from your SQL. This runs with JSqlParser 1.1. JSqlParser is not able to parse:
`create table conf_temp like conf;`
and
`drop table conf,item_brand;`

All other statements are parsed fine.

I did not get your exception. So I guess the SQL you are trying to parse is not the one in this issue.

```
public static void main(String args[]) {
        String sqlStr = "CREATE TABLE conf (\n"
                + "conf_key int NOT NULL COMMENT 'FK(\"code\")',\n"
                + "conf_type int NOT NULL COMMENT 'CODE(\"CONF_TYPE\")',\n"
                + "conf_value text NOT NULL COMMENT '配置值',\n"
                + "return_type int NOT NULL COMMENT '返回类型:CODE(\"RETURN_TYPE\")',\n"
                + "createddt timestamp NULL COMMENT '插入时间',\n"
                + "updateddt timestamp NULL COMMENT '更新时间',\n"
                + "PRIMARY KEY (conf_key,conf_type)\n"
                + ") ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='配置表(CONF)';\n"
                + "create table conf_temp like conf;\n"
                + "CREATE TABLE item_brand (\n"
                + "item_url varchar(255) NOT NULL,\n"
                + "brand_url varchar(255) NOT NULL,\n"
                + "brand_name varchar(100) DEFAULT NULL,\n"
                + "item_id bigint(20) DEFAULT NULL,\n"
                + "PRIMARY KEY (item_url)\n"
                + ") ENGINE=MyISAM DEFAULT CHARSET=utf8;\n"
                + "drop table conf,item_brand;\n"
                + "alter table conf drop column createddt;";
        
        for (String sql : sqlStr.split(";")) {
            try {
                Statements stmt = CCJSqlParserUtil.parseStatements(sql);
                System.out.println(stmt.toString());
            } catch (JSQLParserException ex) {
                Logger.getLogger(SimpleSqlParser9.class.getName()).log(Level.SEVERE, "problem sql=" + sql, ex);
            }
        }
    }
```

**Comment by david919** [comment]
Thank you for answer. Yes, the problem was those two statements.

**Comment by wumpz** [comment]
I have little time at the moment. Do you want to provide a PR für those MySql specials?

**Comment by david919** [comment]
I need all DDL statements to be parseable, but nothing special. This statements were just example. Thank you very much

**Comment by manticore-projects** [comment]
Except the `DROP table1, table2` statement, all can be [parsed with JSQLParser 4.8](http://jsqlformatter.manticore-projects.com/jsqlformatter/demo.html?args=-c%20MIJQogggKmAEUQEIBk4GMD2A7AZrAFAFCa4D6A1gKYCesAllgC6wByA8lKwKrLKzBsAsoLAtOAcgBiAaXwAiTABNKcgJTiANMWw5SjagAdK9Jqw7de-ISLGxxAgCJh5AlpNJQAmgAUwazdpkAG4AhgA2AK7GjJQAHszsnCw8fALCohKAsomAdv6APAoBAE6UjBEFWHqGxgwJ5smWaTYSgCvxgHtqgN4+gNHqAFyOznLgUFwgLB4+fupaaEUhMYqKzIx0ALaUAM6MIUsGFqnWGXaAS8aApoqAb6aAL6kBEQaKM5RzC8trG1s7Vum24oAvZoANpucB3iAAJKCCAgTywaRgcH4Ei6KjUDSwipGVSEVSwUQAcUBLDAAF5AVgsBgHIhYE5JBAeJxgAAJUEAZTAUDxEUYOAAHG9GnjxDlABYR+FcknUAG5iNMYrANgAjMLGJExF5hOhUWCw8WgSAweBIVD0JWkGUFEJYRQEQh0Q2lMKwUIFNAACxCBXwACYAKwe9GJHZaY2mxSkG12l1Ol3ur0+2opf0ms2kLCbYz28OugCMAAZM+iKVTkElY5bDXRzTK6ABzarunPksCU6l+wgA4Gg8GQ6FWyhLYMFMKo9FYnH4wTUQEMiCCOsNgv8ekgJkstmc8WKAoYbay+XqnSr9ebkJyqqGgNm8XhGIFaWH7ew2Brjc7yJLLDqyV3eaioA)
