### ISSUE TITLE
Quoting columns in primary key clause of CREATE TABLE statement does not work

### ISSUE THREAD

**Issue by olavloite** [JSQLParser/JSqlParser#491]
A ParseException is thrown when quoting the columns in the primary key clause of a CREATE TABLE statement. The following statement is parsed perfectly:
``CREATE TABLE `FOO` (`ID` INT64, `NAME` STRING(100)) PRIMARY KEY (ID)``

While this statement throws a ParseException:
``CREATE TABLE `FOO` (`ID` INT64, `NAME` STRING(100)) PRIMARY KEY (`ID`)``

**Comment by wumpz** [comment]
Definitly a bug. I will look into it.

**Comment by wumpz** [comment]
Did not deploy a corrected version of the jars. Please build it yourself for the moment.
