### ISSUE TITLE
Query analysis takes a long time.

### ISSUE THREAD

**Issue by hangum** [JSQLParser/JSqlParser#496]
* Environment : JSQLParser v1.1
The query is not parsed. The query is shown below. 
The query was incorrect. However, analysis is not possible.

Thanks.

`select isNull(charLen(TEST_ID,0)+ 
    isNull(charLen(TEST_DVC,0)+ 
    isNull(charLen(TEST_NO,0)+ 
    isNull(charLen(ATEST_ID,0)+ 
    isNull(charLen(TESTNO,0)+ 
    isNull(charLen(TEST_CTNT,0)+ 
    isNull(charLen(TEST_MESG_CTNT,0)+ 
    isNull(charLen(TEST_DTM,0)+ 
    isNull(charLen(TEST_DTT,0)+ 
    isNull(charLen(TEST_ADTT,0)+ 
    isNull(charLen(TEST_TCD,0)+
    isNull(charLen(TEST_PD,0)+ 
    isNull(charLen(TEST_VAL,0)+
    isNull(charLen(TEST_YN,0)+ 
    isNull(charLen(TEST_DTACM,0)+ 
    isNull(charLen(TEST_MST,0) 
from  test_info_m ;
`
* Debug output
##[start]##########Tue Aug 22 22:32:13 KST 2017
Consumed token: <"SELECT": "select" at line 1 column 1>
Call:	getOracleHint
Return: getOracleHint
Consumed token: <<S_IDENTIFIER>: "isNull" at line 1 column 8>
Return: RelObjectName
Return: Column
Return: PrimaryExpression
Return: BitwiseXor
Return: MultiplicativeExpression
Return: AdditiveExpression
Return: ConcatExpression
Return: BitwiseAndOr
Return: SimpleExpression
Return: SelectExpressionItem
Return: SelectItem
Return: SelectItemsList
Return: PlainSelect
Return: SetOperationList
Return: SelectBody
Return: Select
Return: SingleStatement
######## No more debug output. #########################

* Full source
import net.sf.jsqlparser.parser.CCJSqlParserManager;
import net.sf.jsqlparser.statement.select.Select;
import net.sf.jsqlparser.util.TablesNamesFinder;

import java.io.StringReader;
import java.util.Iterator;
import java.util.List;
import java.util.Date;

public class TDBTest {
    public static void main(String[] args) {
        System.out.println(String.format("##[start]##########" + new Date()));

        try {
            String sql = "select isNull(charLen(TEST_ID,0)+       " +
                    "	    isNull(charLen(TEST_DVC,0)+           " +
                    "	    isNull(charLen(TEST_NO,0)+            " +
                    "	    isNull(charLen(ATEST_ID,0)+           " +
                    "	    isNull(charLen(TESTNO,0)+             " +
                    "	    isNull(charLen(TEST_CTNT,0)+          " +
                    "	    isNull(charLen(TEST_MESG_CTNT,0)+     " +
                    "	    isNull(charLen(TEST_DTM,0)+           " +
                    "	    isNull(charLen(TEST_DTT,0)+           " +
                    "	    isNull(charLen(TEST_ADTT,0)+          " +
                    "	    isNull(charLen(TEST_TCD,0)+           " +
                    "	    isNull(charLen(TEST_PD,0)+            " +
                    "	    isNull(charLen(TEST_VAL,0)+           " +
                    "	    isNull(charLen(TEST_YN,0)+            " +
                    "	    isNull(charLen(TEST_DTACM,0)+         " +
                    "	    isNull(charLen(TEST_MST,0)            " +
                    "	   from  test_info_m ;";

            long longSt = System.currentTimeMillis();
            CCJSqlParserManager pm = new CCJSqlParserManager();
            net.sf.jsqlparser.statement.Statement statement = pm.parse(new StringReader(sql));

            if (statement instanceof Select) {
                Select selectStatement = (Select) statement;
                TablesNamesFinder tablesNamesFinder = new TablesNamesFinder();
                List<String> tableList = tablesNamesFinder.getTableList(selectStatement);
                System.out.println("table size is " + tableList.size());
                int i = 1;
                for (Iterator iter = tableList.iterator(); iter.hasNext(); i++) {
                    String tableName = (String) iter.next();
                    System.out.println("table name is " + tableName);
                }
            }

            long longEd = System.currentTimeMillis();
            System.out.println("##[end]######" +  new Date());
            System.out.println("Total : " + (longEd - longSt));
        } catch(Exception e) {
            e.printStackTrace();
        }
    }

}

**Comment by wumpz** [comment]
Could you activate lookahead debug as well? All kind of parenthesis parsing is very time consuming, I know. Do you know the JSQLPARSER performance test project. It tries to gathers me more interesting statistics. It's within Jsqlparser organisations at github too.

**Comment by hangum** [comment]
The above query is going through an infinite loop.
attach the log. 
Thanks.

[JSQLParser.log.zip](https://github.com/JSQLParser/JSqlParser/files/1243099/JSQLParser.log.zip)

**Comment by hangum** [comment]
@wumpz  What should I do?
Give me a hint.

**Comment by wumpz** [comment]
Sorry. Those problems are hard to tackle, I know. At the moment I have not that much time. But my first analysis showed that the lookahead for AnalyticFunction in PrimaryExpression is the first problem to correct. The parsing does not run endless but the time increases exponentially.

**Comment by hangum** [comment]
@wumpz  It is good open source and is well used. I'm sorry for asking for something.
Thank you for your hint. I will debug.

**Comment by wumpz** [comment]
Don't be sorry for asking. Thats the normal way a problem gets solved.

**Comment by wumpz** [comment]
analysis is now possible, parsing fails within 10 secs on my computer.
