### ISSUE TITLE
Is it allowed to change source code of jsqlparser and get it commercial used?

### ISSUE THREAD

**Issue by zhztheplayer** [JSQLParser/JSqlParser#499]
We are going to launch the development of a commercial project including some sql parsing abilities. And JSqlparser is a pretty nice choice. But we are not sure if it is allowed to modify the source code and use it in our project since this is dual licensed under LGPL 2.1 / Apache License 2.0. Is this legal or permitted？

**Comment by wumpz** [comment]
I am not a lawyer. As I know both licenses allow this, where LGPL seems to be more problematic. 

So I have no problem if you modify the source code. 

May I ask, why do you not want to share your improvements, or are they more or less not parsing relevant? 

Maybe we could discuss some extension variants for JSqlParser for your case, some plugin system. I think that would be interesting for more developers.

**Comment by zhztheplayer** [comment]
@wumpz 
Thank you for reply :)

We will be glad to share our changes on JSqlParser as soon as we have made any common improvements that could be able to benefit community. But our possible changes on JSqlParser is all about customizing a specific SQL Syntax to query a customized data source, which is fully developed by our team but still not open sourced yet.

So, do you agree us to continue making our change, and then just share the common part if there will be some?

**Comment by wumpz** [comment]
No problem from my side. I am not sure,  what the license force you to do. I think Apache requires you to mention the origin but not necessarily open your sources. Saying that again I am no lawyer.

**Comment by wumpz** [comment]
If you need help, feel free to ask.

**Comment by zhztheplayer** [comment]
OK, we will do our work by following the Apache License 2.0. And sorry I missed your suggestion about the plugin system part in your previous answer. 

For the business scenarios of us, the user input SQLs always follow one specific standard, then be converted to various protocols (could be some other different SQL types, could be some sort of text configs, not sure).

We can easily control the protocol converting rule by creating different visitor implementations, but still not able to change the input SQL syntax without customizing the Parser.jjt file. This is also the reason why we are going to custom JSqlParser deeply.

**Comment by wumpz** [comment]
Out of curiosity,  could you give an example?

**Comment by zhztheplayer** [comment]
@wumpz 
For example, boolean expression as a function parameter or be directly used in select list, this feature is something we need and Jsqlparser does not support natively, so we should add extra rules to jjtree to achieve this.

Can some plugin system could benefit these development works?

**Comment by wumpz** [comment]
That is a feature already requested. I would be cool if you could publish this addition. I hat til now not the time do it.

**Comment by zhztheplayer** [comment]
@wumpz 
I am glad to submit a PR right now，however we have a internal opensource workflow to avoid publishing intra-company source code without permission.

I will try to walk through the workflow and open source our change. Cause we don't really want to make the inner software ecosystem pretty close.
