### ISSUE TITLE
ParseException: Encountered " "||" "|| ""

### ISSUE THREAD

**Issue by mirinyeon** [JSQLParser/JSqlParser#501]
compile 'com.github.jsqlparser:jsqlparser:1.1'

My SQL Caluse as below:
```
select * from departs
where companyCode||departCode in (...)
```
was throwing 

> ParseException: Encountered " "||" "|| ""

**Comment by wumpz** [comment]
Appreciate. Always good to see someone digging deeper even after filing issues.  :)
