### ISSUE TITLE
left shift fail to parse

### ISSUE THREAD

**Issue by packageOk** [JSQLParser/JSqlParser#508]
hi, when i parse "update `user` set `num`=1<<1 where `id`=1", it throw a exception
`Caused by: net.sf.jsqlparser.parser.ParseException: Encountered " "<" "< "" at line 1, column 25.
Was expecting one of:
    <EOF> 
    "FROM" ...
    "WHERE" ...
    "LIMIT" ...
    "ORDER" ...
    "RETURNING" ...
    ";" ...
    "," ...
    "|" ...
    "&" ...
    "^" ...
    "::" ...
	at net.sf.jsqlparser.parser.CCJSqlParser.generateParseException(CCJSqlParser.java:17066)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_consume_token(CCJSqlParser.java:16919)
	at net.sf.jsqlparser.parser.CCJSqlParser.Statement(CCJSqlParser.java:91)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:54)
	... 27 more`

**Comment by packageOk** [comment]
when i want to add left shift, I'm confused. I find that  the precedence of ‘||’ is higher than '&' in jsqlParser.
for example expression "1&2||3" is parsed a bitwiseAnd expression. its left expression is 1, and right expression is a concat expression(2||3). but the precedence of '&' is higher than '||' in mysql document. the expression "1&2||3“ should be a concat expression, and its left expression is a bitwiseAnd expression(1&2).  @wumpz

**Comment by wumpz** [comment]
@packageOk Agreed. At least the concatenation is not higher. But there are differences between the database vendors. Nevertheless it seems appropriate to switch it.
