### ISSUE TITLE
Supporting MySql hint SQL_CALC_FOUND_ROWS for selecting row count.

### ISSUE THREAD

**Issue by KyongSik-Yoon** [JSQLParser/JSqlParser#509]
Parsing failed when sql contain MySql hint SQL_CALC_FOUND_ROWS so I added rule for parsing that.
I referred following documents.
https://dev.mysql.com/doc/refman/5.7/en/select.html

**Comment by KyongSik-Yoon** [comment]
@wumpz Please check it.

**Comment by wumpz** [comment]
But I already wrote some comments to your code.

**Comment by KyongSik-Yoon** [comment]
@wumpz I cannot find your comments.
Following link is my source code.
[](https://github.com/JSQLParser/JSqlParser/pull/504)

**Comment by wumpz** [comment]
That is right. There are my review comments.

**Comment by KyongSik-Yoon** [comment]
@wumpz I couldn't look your comments anywhere.
When I see #504 the participants are just me and coveralls(CI?).
I think your confusing with other issue.
Could you please check again?

**Comment by wumpz** [comment]
No I uses your link to it.

**Comment by wumpz** [comment]
Here are my review comments from your pull request. I that helps:

```
+/**
+ * @author sam
+ */
+public class MySqlSqlCalcFoundRows {
```

Why do you implement a whole class for this? As if using "distinct" isn't it enough to make it a boolean value in PlainSelect, triggered by some setMySqlSqlCalcFoundRows(true)?
```

     [LOOKAHEAD(2) first = First() { plainSelect.setFirst(first); } ]
 
+    { sqlCalcFoundRows = new MySqlSqlCalcFoundRows(); }
```

You are instantiating your class even if it is not needed.


```
+ */
+public class StatementVisitorFactory {
+    public static StatementVisitor create(final AtomicReference<MySqlSqlCalcFoundRows> ref) {
+       return new StatementVisitor() {
```

To shorten this you could use StatementVisitorAdapter. But look at my comment above. I am not yet convinced, if you need this.


```
+/**
+ * @author sam
+ */
+public class MySqlSqlCalcFoundRowsTest {
```

I would like to have a assertSqlCanBeParsedAndDeparsed test. That forces JSqlParser developers to adress extentions within deparsers as well.

**Comment by KyongSik-Yoon** [comment]
Thanks for your kindly code review.
I’ll push PR again after modify all by referring your advice.

**Comment by KyongSik-Yoon** [comment]
@wumpz I added additional commits on PR. 
In this phase I found my implementation could not pass assertSqlCanBeParsedAndDeparsed so I fixed it. 
Please check it.

**Comment by wumpz** [comment]
I simplified your test. There are adapter classes for visitors. Look at the test now, its much less code.
