### ISSUE TITLE
RESTRICT and CASCADE not parseable

### ISSUE THREAD

**Issue by david919** [JSQLParser/JSqlParser#510]
Hi, this statements are not parseable :

CONSTRAINT FK_table1_table2 FOREIGN KEY (Column)
REFERENCES UniIS.FAKULTET (Column) ON DELETE CASCADE ON UPDATE RESTRICT;

ALTER TABLE TABLE1 DROP COLUMN NewColumn CASCADE;

DROP TABLE TABLE2 RESTRICT;

**Comment by AnEmortalKid** [comment]
Would you mind running this with the debug mode and showing us the parsing? It looks like some part of [Cascade](https://github.com/JSQLParser/JSqlParser/blob/master/src/main/jjtree/net/sf/jsqlparser/parser/JSqlParserCC.jjt#L263) is supported.

**Comment by wumpz** [comment]
What is the first statement? Is is complete? Please file for this another issue.

The other two are resolved.
