### ISSUE TITLE
function fail to parse

### ISSUE THREAD

**Issue by packageOk** [JSQLParser/JSqlParser#511]
Hi, when I parse "update food set num=if(num > 1, 1, 0);", it throw a exception. but if I try "update food set num = if(1, 1, 0);", it works well. Is there anything wrong?

**Comment by wumpz** [comment]
JSqlParser does not (yet) support conditions as function parameters.

**Comment by zhztheplayer** [comment]
@wumpz 
I also wonder if the boolean expr parameter (or as select items) could be supported in later version of Jsqlparser.

As I known, some popular storages like postgreSQL supports this feature, and SQL-2003 standard explicitly declares this also.

**Comment by wumpz** [comment]
@zhztheplayer 
JSqlParser will support this. It is already a requested feature. But til now I had no plan, when to start.

**Comment by tserr** [comment]
@wumpz 
I'd like to see this feature implemented ;-)
Did you start implementing in the meantime? Is there already some code, I could base on to help you implementing this feature (in the bounds of my possibilities). Should I start a try on my own?

**Comment by wumpz** [comment]
Did not start implementing in this direction. Sorry.

**Comment by wumpz** [comment]
now supported for specific function names (e.g. if)
