### ISSUE TITLE
parse oracle listagg(c1, ';') within group (partition by 1 order by 1) failed

### ISSUE THREAD

**Issue by cncqycy** [JSQLParser/JSqlParser#514]
JSQLPARSER is the best free SQL parsing tool I've ever seen. Thanks.

Here is some problem with oracle statement parsing.

i'am using jsqlparser1.1.

This works fine.
`select listagg(c1, ';') within group (order by 1) col from dual`

This does not work.
`select listagg(c1, ';') within group (partition by 1 order by 1) col from dual`

----------------------------------------------- error stack -----------------------------------------------------
net.sf.jsqlparser.JSQLParserException
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:56)
	at test.TestSqlParser.main(TestSqlParser.java:23)
Caused by: net.sf.jsqlparser.parser.ParseException: Encountered " "WITHIN" "within "" at line 1, column 25.
Was expecting one of:
    <EOF> 
    "AS" ...
    "DO" ...
    "ANY" ...
    "KEY" ...
    "PERCENT" ...
    "END" ...
    "INTO" ...
    "FROM" ...
    "OPEN" ...
    "TABLE" ...
    "WHERE" ...
    "FOR" ...
    "XML" ...
    "UNION" ...
    "GROUP" ...
    "ORDER" ...
    "VALUE" ...
    "HAVING" ...
    "INSERT" ...
    "VALUES" ...
    "REPLACE" ...
    "TRUNCATE" ...
    "INTERSECT" ...
    "CAST" ...
    "EXCEPT" ...
    "MINUS" ...
    "OVER" ...
    "PARTITION" ...
    "EXTRACT" ...
    "MATERIALIZED" ...
    "START" ...
    "CONNECT" ...
    "PRIOR" ...
    "SIBLINGS" ...
    "COLUMN" ...
    "NULLS" ...
    "FIRST" ...
    "LAST" ...
    "ROWS" ...
    "RANGE" ...
    "FOLLOWING" ...
    "ROW" ...
    "COMMIT" ...
    "KEEP" ...
    "SEPARATOR" ...
    "CASCADE" ...
    "NO" ...
    "ACTION" ...
    <K_DATETIMELITERAL> ...
    "PRECISION" ...
    ";" ...
    <S_IDENTIFIER> ...
    <S_QUOTED_IDENTIFIER> ...
    "," ...
    "." ...
    "|" ...
    "&" ...
    "^" ...
    "}" ...
    "::" ...
    "ORDER" ...
    "ORDER" ...
    "KEEP" ...
    "OVER" ...
    "OVER" ...
    "OVER" ...
    "OVER" ...
    "OVER" ...
    "OVER" ...
    "OVER" ...
    "OVER" ...
    "OVER" ...
    "OVER" ...
    "OVER" ...
    "OVER" ...
    "OVER" ...
    "." ...
    "KEEP" ...
    "}" ...
    
	at net.sf.jsqlparser.parser.CCJSqlParser.generateParseException(CCJSqlParser.java:16869)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_consume_token(CCJSqlParser.java:16722)
	at net.sf.jsqlparser.parser.CCJSqlParser.Statement(CCJSqlParser.java:91)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:54)
	... 1 more
Caused by:
net.sf.jsqlparser.parser.ParseException: Encountered " "WITHIN" "within "" at line 1, column 25.
Was expecting one of:
    <EOF> 
    "AS" ...
    "DO" ...
    "ANY" ...
    "KEY" ...
    "PERCENT" ...
    "END" ...
    "INTO" ...
    "FROM" ...
    "OPEN" ...
    "TABLE" ...
    "WHERE" ...
    "FOR" ...
    "XML" ...
    "UNION" ...
    "GROUP" ...
    "ORDER" ...
    "VALUE" ...
    "HAVING" ...
    "INSERT" ...
    "VALUES" ...
    "REPLACE" ...
    "TRUNCATE" ...
    "INTERSECT" ...
    "CAST" ...
    "EXCEPT" ...
    "MINUS" ...
    "OVER" ...
    "PARTITION" ...
    "EXTRACT" ...
    "MATERIALIZED" ...
    "START" ...
    "CONNECT" ...
    "PRIOR" ...
    "SIBLINGS" ...
    "COLUMN" ...
    "NULLS" ...
    "FIRST" ...
    "LAST" ...
    "ROWS" ...
    "RANGE" ...
    "FOLLOWING" ...
    "ROW" ...
    "COMMIT" ...
    "KEEP" ...
    "SEPARATOR" ...
    "CASCADE" ...
    "NO" ...
    "ACTION" ...
    <K_DATETIMELITERAL> ...
    "PRECISION" ...
    ";" ...
    <S_IDENTIFIER> ...
    <S_QUOTED_IDENTIFIER> ...
    "," ...
    "." ...
    "|" ...
    "&" ...
    "^" ...
    "}" ...
    "::" ...
    "ORDER" ...
    "ORDER" ...
    "KEEP" ...
    "OVER" ...
    "OVER" ...
    "OVER" ...
    "OVER" ...
    "OVER" ...
    "OVER" ...
    "OVER" ...
    "OVER" ...
    "OVER" ...
    "OVER" ...
    "OVER" ...
    "OVER" ...
    "OVER" ...
    "." ...
    "KEEP" ...
    "}" ...
    
	at net.sf.jsqlparser.parser.CCJSqlParser.generateParseException(CCJSqlParser.java:16869)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_consume_token(CCJSqlParser.java:16722)
	at net.sf.jsqlparser.parser.CCJSqlParser.Statement(CCJSqlParser.java:91)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:54)
	at test.TestSqlParser.main(TestSqlParser.java:23)

**Comment by wumpz** [comment]
You are right. Partition by is not supported here. I am thinking already to merge "over" and "within group" expressions, to simplify stuff.

**Comment by cncqycy** [comment]
Thanks, very appreciated.
