### ISSUE TITLE
TableNamesFinder does not find tables referenced as a column

### ISSUE THREAD

**Issue by Airblader** [JSQLParser/JSqlParser#515]
When parsing only a conditional expression, TableNamesFinder does not find tables referenced in an expression like

    SOME_TABLE.COLUMN = 'A'

because `visit(Column tableColumn)` doesn't handle this case.

**Comment by wumpz** [comment]
But is this table not included in from? Is this indeed valid without from?

**Comment by Airblader** [comment]
When you parse it via parseCondExpression, yes. :-)

I've also noticed that when you have a complete select statement with an aliased table, referring to the alias in the where clause reports it as a table with that name rather than resolving it to the aliased table. I can open an issue with an example for that later.

**Comment by wumpz** [comment]
I love those edge cases ;).

**Comment by wumpz** [comment]
I fixed this issue, but avoided column processing for complete statements, due to problematic alias as table recognition:

`select a.c from mytable a`
