### ISSUE TITLE
Parser does not resolive aliases correctly

### ISSUE THREAD

**Issue by Airblader** [JSQLParser/JSqlParser#516]
Perhaps this is intended and by design, so correct me if I'm wrong, but when parsing something like

    SELECT * FROM TABLE T WHERE T.FOO IS NULL

and visiting the tree, I will get two tables:

1. A table named `TABLE` with alias `T`
2. A table named `T` without alias

This puts the burden of resolving the reference on the user while it really seems like that's exactly the kind of thing I'd expect a parser to do.

**Comment by wumpz** [comment]
That's a thing a parser does not do. A parser builds a traversable form of an input. JSqlParser does not a semantic analysis, which is what you expect it to do. Within your example the recognition is quite simple. But for complex situation one have to construct visibility blocks.

`select * from mytable t where id in (select id from t)`

**mytable** could even be a function. So you also need the database schema to make it complete.

**Comment by Airblader** [comment]
OK, fair enough, but doesn't that mean that the parser classes like `Table` are completely misnamed, given that we don't even know that it is a table?

**Comment by wumpz** [comment]
You are right. First of all its historically grown  ;).  Second what would be a better name? At least this gives the user a hint what it could be, what I think is better than naming all identifier. But that is a matter of taste I think. The same argument could be stated for columns, sequences, functions, ....

**Comment by Airblader** [comment]
Fair enough. In any case, closing. :-)
