### ISSUE TITLE
Access the renamed column name with as clause

### ISSUE THREAD

**Issue by kddesai11** [JSQLParser/JSqlParser#521]
I want to access the column names of a select query. But i am only able to access the real column names using the ((Column)PlainSelect.getSelectItems().get(i).getExpression()).getColumnName(). I want to access the columnname defined by as clause.(e.g. select col1 as newcol1 from mytable. I want to access newcol1). How to access that?

**Comment by wumpz** [comment]
Use the alias.

**Comment by kddesai11** [comment]
Hi wumpz. Can you explain what you mean by using the alias? Please provide the class and method name to use for that.

**Comment by wumpz** [comment]
@kddesai11 Look at SelectTest.testSelectItems. There are column aliases read.

**Comment by kddesai11** [comment]
Thanks @wumpz
