### ISSUE TITLE
Parsing problem with CASE statement and "*"

### ISSUE THREAD

**Issue by grkephart** [JSQLParser/JSqlParser#522]
SELECT mr.inventory_item_id, mr.wip_entity_id, mr.organization_id, mr.operation_seq_num,              i.segment1 concatenated_segments, i.description item_description, i.primary_uom_code item_primary_uom_code,
              mr.supply_subinventory, mr.supply_locator_id, mr.wip_supply_type, ml.meaning wip_supply_meaning,
             CASE mr.quantity_issued
               WHEN 0 THEN NULL
                ELSE mr.quantity_issued
              END quantity_issued,
             CASE mr.required_quantity - mr.quantity_issued
               WHEN 0 THEN NULL
               ELSE
                 CASE SIGN(mr.required_quantity)
                   WHEN -1 * SIGN(mr.quantity_issued) THEN mr.required_quantity - mr.quantity_issued    <<--- HERE!
                   ELSE
                     CASE SIGN(ABS(mr.required_quantity) - ABS(mr.quantity_issued))
                       WHEN -1 THEN NULL
                       ELSE mr.required_quantity - mr.quantity_issued
                      END
                  END
              END quantity_open,
             mr.quantity_per_assembly, mr.required_quantity
        FROM apps.wip_requirement_operations mr
   LEFT JOIN apps.mtl_system_items_b         i  ON i.inventory_item_id = mr.inventory_item_id AND i.organization_id = mr.organization_id
   LEFT JOIN apps.mfg_lookups                ml ON ml.lookup_code      = mr.wip_supply_type       WHERE ml.lookup_type = 'WIP_SUPPLY'

**Comment by wumpz** [comment]
Which exception was thrown? Which version do you use?

**Comment by wumpz** [comment]
Why does the star matter?

**Comment by grkephart** [comment]
I’m using version 1.1. I’ll get the exception back to you later today.

----
Gary Kephart        | ICU Medical
Software Engineer   | 951 Calle Amanecer
gkephart@icumed.com | San Clemente, CA  92673
949.366.4289        | http://icumed.com/

**Comment by grkephart** [comment]
Because the error message is this:

net.sf.jsqlparser.parser.ParseException: Encountered " "*" "* "" at line 1, column 644.
Was expecting one of:
    "THEN" ...
    "::" ...

Column 644 is the “*” in “WHEN -1 * SIGN(mr.quantity_issued)”

Gary
----
Gary Kephart        | ICU Medical
Software Engineer   | 951 Calle Amanecer
gkephart@icumed.com | San Clemente, CA  92673
949.366.4289        | http://icumed.com/

**Comment by wumpz** [comment]
Resolved and deployed. JSqlParser could not handle more complex expressions within case expr when expr then expr end.  Hope it helps.

**Comment by grkephart** [comment]
Thanks!
One more question: does the parser handle constraints in a “create table” statement? I’d like to get the tables in the foreign keys references. They don’t seem to be included in TablesNamesFinder and I can’t find a method to get them in the Table class. Should I just extend TablesNamesFinder?

Thanks,
  Gary
----
Gary Kephart        | ICU Medical
Software Engineer   | 951 Calle Amanecer
gkephart@icumed.com | San Clemente, CA  92673
949.366.4289        | http://icumed.com/
