### ISSUE TITLE
Modify SelectExpressionItem in List<SelectItem>

### ISSUE THREAD

**Issue by vherasme** [JSQLParser/JSqlParser#524]
In order to add a  (pobbibly) missing column in a SQL String I have done the following:

1. First I parse the SQL with:

`
		try {
			statement = CCJSqlParserUtil.parse(query);
		} catch (JSQLParserException e) {
			e.printStackTrace();
		}
		Select selectStatement = (Select) statement;
		SelectBody selectBody = selectStatement.getSelectBody();
`

2. I have created a **SQLSelectVisitor implements SelectVisitor** that returns the **plainSelect.getSelectItems()**

3. I want to loop through this list of SelectItems and add more selectItems (one for name and another for id) in case they're absent. How could I achieve this?

**Comment by wumpz** [comment]
If you have a List of SelectItems from plain select, then you could directly work with that. Maybe you could look at `SelectUtils.addExpression`. There an expression is adde to an existing select statement.

**Comment by vherasme** [comment]
Thanks a lot!

**Comment by wumpz** [comment]
Why reopened? What did not work?

**Comment by vherasme** [comment]
Sorry, I thought I would have another question, but I have worked it out. Closing definitely.

**Comment by wumpz** [comment]
OK. Thx for using JSqlParser ;)
