### ISSUE TITLE
there is a error when insert with alias

### ISSUE THREAD

**Issue by wonder2014** [JSQLParser/JSqlParser#526]
database ： oracle
sql           ： INSERT INTO account t (name, addr, phone) SELECT * FROM user
error         :  
Caused by: net.sf.jsqlparser.parser.ParseException: Encountered " <S_IDENTIFIER> "t "" at line 1, column 21.
Was expecting one of:
    "SET" ...
    "WITH" ...
    "SELECT" ...
    "(" ...
    "(" ...
    "(" ...
    "(" ...
    
	at net.sf.jsqlparser.parser.CCJSqlParser.generateParseException(CCJSqlParser.java:16970)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_consume_token(CCJSqlParser.java:16823)
	at net.sf.jsqlparser.parser.CCJSqlParser.Insert(CCJSqlParser.java:1043)
	at net.sf.jsqlparser.parser.CCJSqlParser.SingleStatement(CCJSqlParser.java:138)
	at net.sf.jsqlparser.parser.CCJSqlParser.Statement(CCJSqlParser.java:81)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:54)

**Comment by wumpz** [comment]
Is this valid sql?

**Comment by wonder2014** [comment]
yeah, it can exec in oracle dba tool !

**Comment by wumpz** [comment]
You are right. I didn't know that. Do you want to provide a pr?

**Comment by AnEmortalKid** [comment]
It would be probably somewhere around here (if I'm guessing correctly) https://github.com/JSQLParser/JSqlParser/blob/master/src/main/jjtree/net/sf/jsqlparser/parser/JSqlParserCC.jjt#L662

If you set the [debug mode](https://github.com/JSQLParser/JSqlParser/wiki/Examples-of-SQL-parsing#visualize-parsing) you should be able to see what spot you need to plug your stuff into.

**Comment by caosuwenwu** [comment]
解决方式：在JSqlParserCC.jjt里面做修改：
第一个地方：...
Insert Insert():
{
    Insert insert = new Insert();
    Table table = null;
    Column tableColumn = null;
    List<Column> columns = new ArrayList<Column>();
    List<Expression> primaryExpList = new ArrayList<Expression>();
    ItemsList itemsList = null;
    Expression exp = null;
    MultiExpressionList multiExpr = null;
    List<SelectExpressionItem> returning = null;
    Select select = null;
    boolean useValues = true;
    boolean useSelectBrackets = false;
    boolean useDuplicate = false;
    List<Column> duplicateUpdateColumns = null;
    List<Expression> duplicateUpdateExpressionList = null;
    Token tk = null;
    InsertModifierPriority modifierPriority = null;
    boolean modifierIgnore = false;
    boolean useSet = false;
    List<Column> setColumns = new ArrayList<Column>();
    List<Expression> setExpressionList = new ArrayList<Expression>();
}
{
    <K_INSERT>
    [(tk = <K_LOW_PRIORITY> | tk = <K_DELAYED> | tk = <K_HIGH_PRIORITY>)
    {if (tk!=null)
        modifierPriority = InsertModifierPriority.valueOf(tk.image.toUpperCase());
    }]
    [<K_IGNORE>{ modifierIgnore = true; }]
    //todo
    [<K_INTO>] table=TableWithAlias()//之前是Table()
....
第二个地方：
...
String RelObjectName() :
{    Token tk = null; }
{
//todo
    (tk=<S_IDENTIFIER> | tk=<S_QUOTED_IDENTIFIER>
      | tk=<K_CAST> | tk=<K_DO> | tk=<K_EXTRACT> | tk=<K_FIRST> | tk=<K_FOLLOWING> 
      | tk=<K_LAST> | tk=<K_MATERIALIZED> | tk=<K_NULLS> | tk=<K_PARTITION> | tk=<K_RANGE> 
      | tk=<K_ROW> | tk=<K_ROWS> | tk=<K_SIBLINGS> | tk=<K_VALUE> | tk=<K_XML>
      | tk=<K_COLUMN> | tk=<K_REPLACE> | tk=<K_TRUNCATE> | tk=<K_KEY> | tk=<K_ANY>
      | tk=<K_OPEN> | tk=<K_OVER> |/* tk=<K_VALUES> |*/ tk=<K_PERCENT> | tk=<K_PRIOR>
      | tk=<K_SEPARATOR> | tk=<K_NO> | tk=<K_ACTION> | tk=<K_CASCADE> | tk=<K_END>
      | tk=<K_TABLE> | tk=<K_DATETIMELITERAL> | tk=<K_COMMIT> | tk=<K_PRECISION>
      | tk=<K_INSERT>
      )

    { return tk.image; }
}
在第二地方去除这个条件” tk=<K_VALUES>“为防止这样sql：insert into table values (....)语句不能解析，可能还有其他遗漏，还望大家指出。

**Comment by wumpz** [comment]
Accidentally closed ....

**Comment by AnEmortalKid** [comment]
The language barrier for this is gonna be tough... I guess we can use google translate?

**Comment by wumpz** [comment]
aha comma lists for issues are not allowed
