### ISSUE TITLE
Changing column names in the 'where' expression

### ISSUE THREAD

**Issue by vherasme** [JSQLParser/JSqlParser#527]
I am trying to modify the column names in the 'where' part of the query, in a similar fashion to what I wanted to do in #524. An approach would be to loop through the expression recursively and get only the expressions -**leftExpression and rightExpression**- of type **Column**.  So when I find a Column expression I will substitute it for the value I want.

Is there any other way of doing this?

**Comment by wumpz** [comment]
Do you process more complex expressions or only simple sqls with one where?

**Comment by vherasme** [comment]
Complex in general. This is something I am building for users so they can retrieve objects from the database and view them in the front-end, so I won't be able to control how complex their queries will be.

**Comment by wumpz** [comment]
That would be my approach: 
1.  scanning the where clause for an occurance of Column
2. modifying its name directly.
3. done

Is this to complicated or what is the reason you ask for another solution?

**Comment by vherasme** [comment]
I don't know how to start. How do I get all the smaller Expressions contained in the **main where Expression**? Let's say that I got this:

`where name like 'android' and id = 1`

This is an `AndExpression` which consists of two expressions (of Type column). How do I break this into the two Column Expressions? In this case these would be:

`name like 'android'` 

and 

`id = 1`

Could you please give me a hint ? Thanks a lot for your help.

**Comment by wumpz** [comment]
Do you mean something like:

```Java
    public static void main(String args[]) throws JSQLParserException {
        String where = "prop = 1 and prop2 = 'ssdf' or date > 20121204";
        Expression expr = CCJSqlParserUtil.parseCondExpression(where);
        System.out.println("expr=" + expr);
        
        ExpressionVisitorAdapter visitor = new ExpressionVisitorAdapter() {
            @Override
            public void visit(Column column) {
                System.out.println("column=" + column);
                column.setColumnName(column.getColumnName() + "_new");
            }
        };
        
        expr.accept(visitor);
        
        System.out.println("expr with changed colnames=" + expr);
    }
```

with output:

```
expr=prop = 1 AND prop2 = 'ssdf' OR date > 20121204
column=prop
column=prop2
column=date
expr with changed colnames=prop_new = 1 AND prop2_new = 'ssdf' OR date_new > 20121204
```

**Comment by vherasme** [comment]
I have done this:

https://pastebin.com/QWNpcL25. The getExpressions(Expression expression) function is https://pastebin.com/xnRybuVb

Tell me if you can see it.

**Comment by wumpz** [comment]
I see your code. What's the question?

**Comment by vherasme** [comment]
Am I missing something? Am I covering all the cases? 

I just want to know if this is correct

**Comment by wumpz** [comment]
As I said, it is not clear to me, what you want to achieve. Which expressions when and how to process.

**Comment by vherasme** [comment]
I want to process the 'where' condition in order to extract all the column names and change those names. I wrote those functions before I saw your code. I think both approaches have the same effect. Do they?

**Comment by wumpz** [comment]
So why do you process And expressions?

**Comment by vherasme** [comment]
I processs them in order to get  `rightExpressions `and `leftExpressions`. And go recursively that way until I get to the columns and then change the name. I think what you did was what I was looking for anyway. I'm sorry for keeping the issue open so long. I have already solved it. Thanks a lot

**Comment by wumpz** [comment]
No problem. You are welcome.
