### ISSUE TITLE
replace ExpressionList by List<Expression>

### ISSUE THREAD

**Issue by wumpz** [JSQLParser/JSqlParser#529]

**Comment by AnEmortalKid** [comment]
What are the drawbacks of having it be `List<Expression>`, it's still iterable right? It already has a ` private List<Expression> expressions;` inside it. I'd be for this idea. I can check the repercussions of us consuming it (I don't think there'd be many since it all happens through the visitors)

**Comment by wumpz** [comment]
ExpressionList is a simple container. But there is a MultiExpressionList and both share the ItemList interface. So the impact would be a bit bigger I think. Nevertheless, one should keep it simple or make it simple.

**Comment by wumpz** [comment]
After digging arround I found it used in so many places, that I withdraw from doing it now.
