### ISSUE TITLE
关于插入语句别名的问题解决

### ISSUE THREAD

**Issue by caosuwenwu** [JSQLParser/JSqlParser#536]
解决方式：在JSqlParserCC.jjt里面做修改：
第一个地方：... 
Insert Insert（）：
{ 
Insert insert = new Insert（）; 
表表= null; 
列tableColumn = null; 
List columns = new ArrayList（）; 
列表primaryExpList = new ArrayList（）; 
ItemsList itemsList = null; 
表达式exp = null; 
MultiExpressionList multiExpr = null; 
列表返回= null; 
选择select = null; 
boolean useValues = true; 
boolean useSelectBrackets = false; 
boolean useDuplicate = false; 
列表duplicateUpdateColumns = null; 
列表duplicateUpdateExpressionList = null; 
令牌tk = null; 
InsertModifierPriority modifierPriority = null;
boolean modifierIgnore = false; 
boolean useSet = false; 
列表setColumns = new ArrayList（）; 
列表setExpressionList = new ArrayList（）; 
} 
{ 
<K_INSERT> 
[（tk = <K_LOW_PRIORITY> | tk = <K_DELAYED> | tk = <K_HIGH_PRIORITY>）
{if（tk！= null）
modifierPriority = InsertModifierPriority.valueOf（tk.image.toUpperCase（））; 
}] 
[<K_IGNORE> {modifierIgnore = true; }] 
// todo 
[<K_INTO>] table = TableWithAlias（）//之前是Table（）
.... 
第二个地方：
... 
String RelObjectName（）：
{Token tk = null; } 
{ 
// todo 
（tk = <S_IDENTIFIER> | tk = <S_QUOTED_IDENTIFIER>
| tk = <K_CAST> | tk = <K_DO> | tk = <K_EXTRACT> | tk = <K_FIRST> | tk = <K_FOLLOWING> 
| tk = <K_LAST> | tk = <K_MATERIALIZED> | tk = <K_NULLS> | tk = <K_PARTITION> | tk = <K_RANGE> 
| tk = <K_ROW> | tk = <K_ROWS> | tk = <K_SIBLINGS> | tk = <K_VALUE> | tk = <K_XML> 
| tk = <K_COLUMN> | tk = <K_REPLACE> | tk = <K_TRUNCATE> | tk = <K_KEY> | tk = <K_ANY> 
| tk = <K_OPEN> | tk = <K_OVER> | / * tk = <K_VALUES> | * / tk = <K_PERCENT> | tk = <K_PRIOR> 
| tk = <K_SEPARATOR> | tk = <K_NO> | tk = <K_ACTION> | tk = <K_CASCADE> | tk = <K_END> 
| tk = <K_TABLE> | tk = <K_DATETIMELITERAL> | tk = <K_COMMIT> | tk = <K_PRECISION> 
| TK = <K_INSERT>

{ return tk.image; }
} 
在第二地方去除这个条件“tk = <K_VALUES>”为防止这样sql：insert into table values（....）语句不能解析，可能还有其他遗漏，还望指出，多谢多谢。

**Comment by wumpz** [comment]
Please switch to english.

**Comment by caosuwenwu** [comment]
insert statement with alias of problem:
     I tried to make changes in the java file two places，The result is yes。
     Corresponding JSqlParserCC.jjt  file modify:
first:
...
Insert Insert():
{
    Insert insert = new Insert();
    Table table = null;
    Column tableColumn = null;
    List<Column> columns = new ArrayList<Column>();
    List<Expression> primaryExpList = new ArrayList<Expression>();
    ItemsList itemsList = null;
    Expression exp = null;
    MultiExpressionList multiExpr = null;
    List<SelectExpressionItem> returning = null;
    Select select = null;
    boolean useValues = true;
    boolean useSelectBrackets = false;
    boolean useDuplicate = false;
    List<Column> duplicateUpdateColumns = null;
    List<Expression> duplicateUpdateExpressionList = null;
    Token tk = null;
    InsertModifierPriority modifierPriority = null;
    boolean modifierIgnore = false;
    boolean useSet = false;
    List<Column> setColumns = new ArrayList<Column>();
    List<Expression> setExpressionList = new ArrayList<Expression>();
}
{
    <K_INSERT>
    [(tk = <K_LOW_PRIORITY> | tk = <K_DELAYED> | tk = <K_HIGH_PRIORITY>)
    {if (tk!=null)
        modifierPriority = InsertModifierPriority.valueOf(tk.image.toUpperCase());
    }]
    [<K_IGNORE>{ modifierIgnore = true; }]
    [<K_INTO>] table=TableWithAlias();//I modify

second:
...
Table TableWithAlias():
{
    Table table = null;
    Alias alias = null;
}
{
    table=Table() 
    [alias=Alias() { table.setAlias(alias); }]//but hope  filter  “ values”  condition
    { return table; }
}
 In the second place to remove the condition "tk = <K_VALUES>" To prevent this sql: insert into table values (....) statement can not be resolved, but I do not know to deal JSqlParserCC.jjt file . i hope you point out.this is java file:
   final public Table TableWithAlias() throws ParseException {
        Table table = null;
        Alias alias = null;
        table = Table();
        switch ((jj_ntk == -1) ? jj_ntk_f() : jj_ntk) {
            case K_ACTION:
            case K_ANY:
            case K_AS:
            case K_CASCADE:
            case K_CAST:
            case K_COLUMN:
            case K_COMMIT:
            case K_DATETIMELITERAL:
            case K_DO:
            case K_END:
            case K_EXTRACT:
            case K_FIRST:
            case K_FOLLOWING:
            case K_INSERT:
            case K_KEY:
            case K_LAST:
            case K_MATERIALIZED:
            case K_NO:
            case K_NULLS:
            case K_OPEN:
            case K_OVER:
            case K_PARTITION:
            case K_PERCENT:
            case K_PRECISION:
            case K_PRIOR:
            case K_RANGE:
            case K_REPLACE:
            case K_ROW:
            case K_ROWS:
            case K_SEPARATOR:
            case K_SIBLINGS:
            case K_TABLE:
            case K_TRUNCATE:
            case K_VALUE:
                //todo
            //case K_VALUES:-------------------modify
            case K_XML:
            case S_IDENTIFIER:
            case S_QUOTED_IDENTIFIER: {
                alias = Alias();
                table.setAlias(alias);
                break;
            }
            default:
                jj_la1[86] = jj_gen;
                ;
        }
        {
            if ("" != null) {
                return table;
            }
        }
        throw new Error("Missing return statement in function");
    }

Sorry，I'm not good at English ,thank you.

**Comment by wumpz** [comment]
fixed by commit
