### ISSUE TITLE
Limit issue language to english

### ISSUE THREAD

**Issue by wumpz** [JSQLParser/JSqlParser#537]
Our dev team has only limited knowledge of some languages. ;)

**Comment by AnEmortalKid** [comment]
+1

Also, format code properly?

Perhaps we should create an [Issue Template](https://github.com/blog/2111-issue-and-pull-request-templates) with a note ' Please ask in english, since it's the language most of the dev team knows'

**Comment by wumpz** [comment]
Issue Template is a Good idea. I have no idea how good the Google translation was.
