### ISSUE TITLE
insert statement with alias of problem

### ISSUE THREAD

**Issue by caosuwenwu** [JSQLParser/JSqlParser#540]
insert statement with alias of problem:
I tried to make changes in the java file two places，The result is yes。
Corresponding JSqlParserCC.jjt file modify:
first:
...
Insert Insert():
{
Insert insert = new Insert();
Table table = null;
Column tableColumn = null;
List columns = new ArrayList();
List primaryExpList = new ArrayList();
ItemsList itemsList = null;
Expression exp = null;
MultiExpressionList multiExpr = null;
List returning = null;
Select select = null;
boolean useValues = true;
boolean useSelectBrackets = false;
boolean useDuplicate = false;
List duplicateUpdateColumns = null;
List duplicateUpdateExpressionList = null;
Token tk = null;
InsertModifierPriority modifierPriority = null;
boolean modifierIgnore = false;
boolean useSet = false;
List setColumns = new ArrayList();
List setExpressionList = new ArrayList();
}
{
<K_INSERT>
[(tk = <K_LOW_PRIORITY> | tk = <K_DELAYED> | tk = <K_HIGH_PRIORITY>)
{if (tk!=null)
modifierPriority = InsertModifierPriority.valueOf(tk.image.toUpperCase());
}]
[<K_IGNORE>{ modifierIgnore = true; }]
[<K_INTO>] table=TableWithAlias();//I modify

second:
...
Table TableWithAlias():
{
Table table = null;
Alias alias = null;
}
{
table=Table()
[alias=Alias() { table.setAlias(alias); }]//but hope filter “ values” condition
{ return table; }
}
In the second place to remove the condition "tk = <K_VALUES>" To prevent this sql: insert into table values (....) statement can not be resolved, but I do not know to deal JSqlParserCC.jjt file . i hope you point out.this is java file:
final public Table TableWithAlias() throws ParseException {
Table table = null;
Alias alias = null;
table = Table();
switch ((jj_ntk == -1) ? jj_ntk_f() : jj_ntk) {
case K_ACTION:
case K_ANY:
case K_AS:
case K_CASCADE:
case K_CAST:
case K_COLUMN:
case K_COMMIT:
case K_DATETIMELITERAL:
case K_DO:
case K_END:
case K_EXTRACT:
case K_FIRST:
case K_FOLLOWING:
case K_INSERT:
case K_KEY:
case K_LAST:
case K_MATERIALIZED:
case K_NO:
case K_NULLS:
case K_OPEN:
case K_OVER:
case K_PARTITION:
case K_PERCENT:
case K_PRECISION:
case K_PRIOR:
case K_RANGE:
case K_REPLACE:
case K_ROW:
case K_ROWS:
case K_SEPARATOR:
case K_SIBLINGS:
case K_TABLE:
case K_TRUNCATE:
case K_VALUE:
//todo
//case K_VALUES:-------------------modify
case K_XML:
case S_IDENTIFIER:
case S_QUOTED_IDENTIFIER: {
alias = Alias();
table.setAlias(alias);
break;
}
default:
jj_la1[86] = jj_gen;
;
}
{
if ("" != null) {
return table;
}
}
throw new Error("Missing return statement in function");
}
thank you.

**Comment by AnEmortalKid** [comment]
What database lets you do `insert into table t` ? I didn't find that worked for PSQL or Oracle: https://www.techonthenet.com/oracle/insert.php

**Comment by caosuwenwu** [comment]
but I really  find "insert into table t " for Oracle ,  the sql  is  run.
