### ISSUE TITLE
Version 1.2

### ISSUE THREAD

**Issue by AnEmortalKid** [JSQLParser/JSqlParser#541]
I saw in the upcoming, that 1.2 has a breaking api change. 

IIRC following [semver](http://semver.org/), shouldn't that be a 2.0 release? since it is a breaking api change.

**Comment by wumpz** [comment]
I had never look into semantic versioning. Nevertheless I did no main version release dependent on Api changes and the change is so small I didn't even considered it.

**Comment by AnEmortalKid** [comment]
Ah, makes sense. Thanks for clarifying. I recall we had some versioning weirdness back in like 0.9.8 too
