### ISSUE TITLE
Index definition in CREATE TABLE doesn't support partial indexes

### ISSUE THREAD

**Issue by tomershay** [JSQLParser/JSqlParser#542]
MySQL allows to define partial indexes on VARCHAR columns.
For example, see the index on meta_key below, with the length 191, even though the entire column length is actually defined as 255.

```
CREATE TABLE `wp_commentmeta` (
    `meta_id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
    `comment_id` BIGINT(20) UNSIGNED NOT NULL DEFAULT '0',
    `meta_key` VARCHAR(255) COLLATE UTF8MB4_UNICODE_CI DEFAULT NULL,
    `meta_value` LONGTEXT COLLATE UTF8MB4_UNICODE_CI,
    PRIMARY KEY (`meta_id`),
    KEY `comment_id` (`comment_id`),
    KEY `meta_key` (`meta_key` (191))
)  ENGINE=MYISAM AUTO_INCREMENT=119 DEFAULT CHARSET=UTF8MB4 COLLATE = UTF8MB4_UNICODE_CI;
```

Trying to parse this statement will result in:
```
net.sf.jsqlparser.parser.ParseException: Encountered " "(" "( "" at ...
Was expecting one of:
    "," ...
    ")" ...
```

Will be glad to hear your recommendations on how to resolve this.
I looked into the Index class under /schema, and it seems that the columns of the index are just saved as a list of strings, so therefore there is no built-in way to define extra properties (such as length) on the index column.

Once we'll reach a common grounds I'll look into implementing the fix and adding a pull request.

Thanks!

**Comment by wumpz** [comment]
JSqlParser 4.0 parses this.
