### ISSUE TITLE
support for drop view if exists

### ISSUE THREAD

**Issue by MMLRDFly** [JSQLParser/JSqlParser#545]
drop view if exists v_wj_cqwj_zb

Caused by:
net.sf.jsqlparser.parser.ParseException: Encountered " "VIEW" "view "" at line 1, column 6.
Was expecting one of:
    "TABLE" ...
    "INDEX" ...
    <S_IDENTIFIER> ...
    
	at net.sf.jsqlparser.parser.CCJSqlParser.generateParseException(CCJSqlParser.java:16869)

**Comment by wumpz** [comment]
"if exists" seems not yet to be supported. Do you want to provide a pull request?

**Comment by MMLRDFly** [comment]
but “drop table if exists t” is right

**Comment by wumpz** [comment]
That is right, but not for "drop view".

**Comment by wumpz** [comment]
Drop view is not supported as well.
