### ISSUE TITLE
escape column names?

### ISSUE THREAD

**Issue by phingocchi** [JSQLParser/JSqlParser#547]
How can I escape column names in sql query:
`SELECT _id, [from] FROM post` ?
`SELECT _id, 'from' FROM post` ?

**Comment by wumpz** [comment]
Jsqlparser supports [col] "col" and `col`. The last are backticks and not single quotes.
Is this indeed called escaping?

**Comment by tshauck** [comment]
I don't think that's what is meant here... e.g. the column name is probably "from" in this example, so the question is how to make this a column name not the `from` reserved word.

**Comment by tshauck** [comment]
(knowing how to do this would be helpful, I couldn't find it myself in the docs)

**Comment by wumpz** [comment]
And my answer tells you exactly that. Or I really miss understood what you meant.
