### ISSUE TITLE
not supported mysql quoted string concat syntax

### ISSUE THREAD

**Issue by wmlgl** [JSQLParser/JSqlParser#553]
https://dev.mysql.com/doc/refman/5.7/en/string-literals.html

Quoted strings placed next to each other are concatenated to a single string. The following lines are equivalent:

'a string'
'a' ' ' 'string'

ps: used in mybatis like this:  select * from t where col like '%' ? '%'

**Comment by wumpz** [comment]
I did not know, this is possible. To be honest, I don't like this syntactic shortcut. What is the problem in writing '%' + ? + '%', which is more characters, but definitely better to read.

**Comment by wmlgl** [comment]
+ number cannot connect string in MySQL.

**Comment by wumpz** [comment]
Sorry. Use a double pipe.

**Comment by wumpz** [comment]
At this time this shortcut will not be implemented. Sorry.
