### ISSUE TITLE
fail to parse statement

### ISSUE THREAD

**Issue by dondank** [JSQLParser/JSqlParser#554]
select T.INDEX as INDEX133_ from myTable T

net.sf.jsqlparser.parser.ParseException: Encountered " "." ". "" at line 1, column 9.
Was expecting one of:
    "AS" ...
    "DO" ...
    "ANY" ...
    "KEY" ...
    "PERCENT" ...
    "END" ...
    "INTO" ...
    "FROM" ...
    "OPEN" ...
    "TABLE" ...
    "WHERE" ...

....

**Comment by wumpz** [comment]
Could you change column name index to maybe index2? Does it work now? Then it is a keyword collision for database object names.

**Comment by dondank** [comment]
yes, it does work with index2 ...
but I cannot ask my users to change it :-(

**Comment by wumpz** [comment]
No problem. I wanted to detect the concrete problem. I will look into it. 

Thx for using and supporting Jsqlparser.

**Comment by wumpz** [comment]
The snapshot is not (yet) deployed to sonatype. You have to compile it yourself.
