### ISSUE TITLE
Support renamed columns in the FROM clause

### ISSUE THREAD

**Issue by arouel** [JSQLParser/JSqlParser#556]
The following SQL query fails, because renamed columns in the FROM clause is not supported yet.
```SQL
select * from t as x(a,b)
```

**Comment by wumpz** [comment]
That is true. Any chance you provide a pull request?

**Comment by before** [comment]
Can you give me some small hints where to look at so that I can try to fix it?

**Comment by wumpz** [comment]
Does this kind of renaming only apply to tables?

**Comment by before** [comment]
I think the focus is on the FROM clause here. There is a good description at http://modern-sql.com/feature/table-column-aliases.

**Comment by wumpz** [comment]
After taking a quick look, I would say:

1. There needs to be a special Alias class to get column aliases.
1.1. maybe there should be an Alias with Columns production, to keep it all together.
2. This one needs to be used in FromItem() production

**Comment by wumpz** [comment]
JSqlParser 4.0 parses this.
