### ISSUE TITLE
Moving to ANTLR

### ISSUE THREAD

**Issue by ftomassetti** [JSQLParser/JSqlParser#557]
I saw this [old issue](https://github.com/JSQLParser/JSqlParser/issues/58) and the corresponding wiki page.
I wanted to let you know that I just developed a tool to translate a JavaCC grammar into an ANTLR 4 one.
Documentation is pretty poor because the project is very young, but I have tried it on the grammar for Java (tens of thousands of lines).
Is this something you would like to look into? I would be glad to help.
The project is named [JavaCC2Antlr](https://github.com/ftomassetti/JavaCC2ANTLR)

**Comment by wumpz** [comment]
Not yet. One of the main argument against ANTLR was performance (https://dzone.com/articles/antlr-and-javacc-parser-generators). Maybe this is somehow solved.

**Comment by ftomassetti** [comment]
In that discussion is interesting to read the comments from Terence Parr on how ANTLR can be configured to improve speed and on the methodology for measuring the performance, but right, performance is something to consider

**Comment by wumpz** [comment]
I made some little tests that time, digging though performance discussions and was not able to achieve a lot more performance. 
What advantages would ANTLR bring to JSqlParser?

**Comment by ftomassetti** [comment]
You have already identified some advantages (copied from your wiki):

* ANTRL 4 generates listener and visitors for the parse tree.
* semantic predicates to disable rules
* the grammar is much easiear to read
* automatic operator precedence

I would also add that ANTLR4 is well maintained, it has a large community and many persons are familiar with it while they are not with JavaCC so I would think it could make contributions easier

**Comment by wumpz** [comment]
JavaCc seems to get momentum again, if you look at the GitHub repository.

For me performance is a huge deal. Semantic rule disabling is not needed. Readability us not an argument, if you compare the clean grammar.  Visitor and listeners are generated as well using jjtree.

**Comment by ftomassetti** [comment]
I would disagree on JavaCC getting momentum: I tried to collaborate to the project because we are using JavaCC as part of JavaParser. However the team was unresponsive, they are using ant to build the project, there is no CI, the code is written in Java 1.5, using global variables all over the place... it got me scared and this is why I started looking into building a migration tool to ANTLR.

That said I saw your wiki page and I thought you could be interested in moving to ANTLR but it seems this is no longer the case, therefore I will close the issue. If you later want to discuss migrating to ANTLR just contact me and I will be happy to help.
