### ISSUE TITLE
Exception thrown when parentheses surrounds a table in the FROM clause

### ISSUE THREAD

**Issue by tomershay** [JSQLParser/JSqlParser#559]
The following query is valid (at least in MySQL), but an exception is thrown when trying to parse it.
``SELECT col from (`table1`)``
It seems that the same issue occurs for multiple tables as well:
``SELECT col from (`table1`), (`table2`)``

**Comment by wumpz** [comment]
I don't know the issue but this seems to be a duplicate.

**Comment by sh-tomer** [comment]
@wumpz, duplicate of which issue?

**Comment by wumpz** [comment]
JSqlParser 4.0 parses this.
