### ISSUE TITLE
throw exception when get table from select statement that table's name is start with number.

### ISSUE THREAD

**Issue by alanzhang211** [JSQLParser/JSqlParser#560]
i use version is v1.1. my sql statement likes "select * from 2t". 

my code

`public static String getTableName(String sql) throws Exception {
        if (sql == null) {
            throw new Exception("sql is null!");
        }
        CCJSqlParserManager ccjSqlParserManager = new CCJSqlParserManager();
        Statement statement = ccjSqlParserManager.parse(new StringReader(sql));
        if (statement instanceof Select) {
            Select selectStatement = (Select) statement;
            TablesNamesFinder tablesNamesFinder = new TablesNamesFinder();
            List<String> tables = tablesNamesFinder.getTableList(selectStatement);
            if(tables.size()>1){
                throw new Exception("sql contains more than one table name!");
            }
            return tables.get(0);
        }else{
            throw new Exception("sql is not select statement!");
        }
    }`

this,throw exception ：
`net.sf.jsqlparser.JSQLParserException
	at net.sf.jsqlparser.parser.CCJSqlParserManager.parse(CCJSqlParserManager.java:40)
	at com.greenline.wemeta.sqlparser.SqlParserHandler.getTableName(SqlParserHandler.java:116)
	at com.greenline.wemeta.sqlparser.SqlParserHandler.main(SqlParserHandler.java:336)
Caused by: net.sf.jsqlparser.parser.ParseException: Encountered " <S_LONG> "2 "" at line 1, column 15.
Was expecting one of:
    "DO" ...
    "ANY" ...`

**Comment by wumpz** [comment]
Jsqlparser does not support identifiers starting with a number. That would collide with e.g. scientific number notation like 1e.
