### ISSUE TITLE
ParseException: Encountered " "VALUES" "values "" 

### ISSUE THREAD

**Issue by mirinyeon** [JSQLParser/JSqlParser#561]
Query :: [ref](https://stackoverflow.com/questions/24258878/how-to-split-comma-separated-value-in-sqlite)
```
WITH split(word, str, hascomma) AS (
    values('', 'Auto,A,1234444', 1)
    UNION ALL SELECT
    substr(str, 0, 
        case when instr(str, ',')
        then instr(str, ',')
        else length(str)+1 end),
    ltrim(substr(str, instr(str, ',')), ','),
    instr(str, ',')
    FROM split
    WHERE hascomma
)
SELECT trim(word) FROM split WHERE word!='';
```

Exception ::

> 01-02 19:13:33.655 W/System.err: Caused by: net.sf.jsqlparser.parser.ParseException: Encountered " "VALUES" "values "" at line 3, column 13.
> 01-02 19:13:33.655 W/System.err: Was expecting one of:
> 01-02 19:13:33.655 W/System.err:     "SELECT" ...
> 01-02 19:13:33.655 W/System.err:     "(" ...
> 01-02 19:13:33.658 W/System.err:     
> 01-02 19:13:33.660 W/System.err:     at net.sf.jsqlparser.parser.CCJSqlParser.generateParseException(CCJSqlParser.java:16869)
> 01-02 19:13:33.662 W/System.err:     at net.sf.jsqlparser.parser.CCJSqlParser.jj_consume_token(CCJSqlParser.java:16722)
> 01-02 19:13:33.663 W/System.err:     at net.sf.jsqlparser.parser.CCJSqlParser.SetOperationList(CCJSqlParser.java:2821)
> 01-02 19:13:33.663 W/System.err:     at net.sf.jsqlparser.parser.CCJSqlParser.SelectBody(CCJSqlParser.java:2572)
> 01-02 19:13:33.663 W/System.err:     at net.sf.jsqlparser.parser.CCJSqlParser.WithItem(CCJSqlParser.java:3008)
> 01-02 19:13:33.663 W/System.err:     at net.sf.jsqlparser.parser.CCJSqlParser.WithList(CCJSqlParser.java:2952)
> 01-02 19:13:33.663 W/System.err:     at net.sf.jsqlparser.parser.CCJSqlParser.Select(CCJSqlParser.java:2556)
> 01-02 19:13:33.663 W/System.err:     at net.sf.jsqlparser.parser.CCJSqlParser.SingleStatement(CCJSqlParser.java:130)
> 01-02 19:13:33.663 W/System.err:     at net.sf.jsqlparser.parser.CCJSqlParser.Statement(CCJSqlParser.java:81)
> 01-02 19:13:33.663 W/System.err:     at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:54)
> 01-02 19:13:33.663 W/System.err: 	... 11 more
> 01-02 19:13:33.663 W/System.err: Caused by:
> 01-02 19:13:33.663 W/System.err: net.sf.jsqlparser.parser.ParseException: Encountered " "VALUES" "values "" at line 3, column 13.
> 01-02 19:13:33.663 W/System.err: Was expecting one of:
> 01-02 19:13:33.663 W/System.err:     "SELECT" ...
> 01-02 19:13:33.663 W/System.err:     "(" ...
> 01-02 19:13:33.663 W/System.err:     
> 01-02 19:13:33.663 W/System.err:     at net.sf.jsqlparser.parser.CCJSqlParser.generateParseException(CCJSqlParser.java:16869)
> 01-02 19:13:33.663 W/System.err:     at net.sf.jsqlparser.parser.CCJSqlParser.jj_consume_token(CCJSqlParser.java:16722)
> 01-02 19:13:33.663 W/System.err:     at net.sf.jsqlparser.parser.CCJSqlParser.SetOperationList(CCJSqlParser.java:2821)
> 01-02 19:13:33.663 W/System.err:     at net.sf.jsqlparser.parser.CCJSqlParser.SelectBody(CCJSqlParser.java:2572)
> 01-02 19:13:33.663 W/System.err:     at net.sf.jsqlparser.parser.CCJSqlParser.WithItem(CCJSqlParser.java:3008)
> 01-02 19:13:33.663 W/System.err:     at net.sf.jsqlparser.parser.CCJSqlParser.WithList(CCJSqlParser.java:2952)
> 01-02 19:13:33.663 W/System.err:     at net.sf.jsqlparser.parser.CCJSqlParser.Select(CCJSqlParser.java:2556)
> 01-02 19:13:33.663 W/System.err:     at net.sf.jsqlparser.parser.CCJSqlParser.SingleStatement(CCJSqlParser.java:130)
> 01-02 19:13:33.663 W/System.err:     at net.sf.jsqlparser.parser.CCJSqlParser.Statement(CCJSqlParser.java:81)
> 01-02 19:13:33.663 W/System.err:     at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:54)

**Comment by wumpz** [comment]
I think the values part is not accepted as a standalone select. Any chance you could provide a pull request?

**Comment by thebiguno** [comment]
Hello,

I am running into this issue as well.  When selecting values, JSQLParser requires that it be after a SELECT statement:
```sql
SELECT VALUES('foo', 'bar')
```
Trying to just select it via a VALUES clause does not work:
```sql
VALUES('foo', 'bar')
```

Unfortunately, DB2 is exactly the opposite: it only supports VALUES without a SELECT:
```
00001 00002
 ----- -----
 foo   bar

Elapsed Time:  0 hr, 0 min, 0 sec, 3 ms.
```

When you try to use the SELECT approach, it fails:
```
[SQL0104] Token <END-OF-STATEMENT> was not valid. Valid tokens: + - AS <IDENTIFIER>. Cause . . . . . :   A syntax error was detected at token <END-OF-STATEMENT>.  Token <END-OF-STATEMENT> is not a valid token.  A partial list of valid tokens is + - AS <IDENTIFIER>.  This list assumes that the statement is correct up to the token.  The error may be earlier in the statement, but the syntax of the statement appears to be valid up to this point. Recovery  . . . :   Do one or more of the following and try the request again: -- Verify the SQL statement in the area of the token <END-OF-STATEMENT>. Correct the statement.  The error could be a missing comma or quotation mark, it could be a misspelled word, or it could be related to the order of clauses. -- If the error token is <END-OF-STATEMENT>, correct the SQL statement because it does not end with a valid clause.


Elapsed Time:  0 hr, 0 min, 0 sec, 0 ms.
```

It appears that if you select from a named VALUES clause, that it works for both DB2 and JSQLParser:

```sql
SELECT * FROM (VALUES ('foo', 'bar')) AS TEMP
```
Unfortunately for us, this would require modifying our existing codebase of SQL queries.  If this case cannot be handled in the SQL parser, I will have to try and convince management to allow it.

Thank you very much for your support!

Cheers

**Comment by thebiguno** [comment]
Thank you very much!

**Comment by wumpz** [comment]
No problem. Was a pleasure 😀. Thanks for using Jsqlparser. Cheers Tobias
