### ISSUE TITLE
Keyword collision in SQL parsing for the column named primary in database table.

### ISSUE THREAD

**Issue by pvporus** [JSQLParser/JSqlParser#567]
SQL example: 

select primary, secondary from info

Through database client, the above query is working fine but this failing due to keyword collision.

Is this fixed earlier and already available?

Please let me know if any workaround is available for time being.

**Comment by wumpz** [comment]
Let me take a look into it. Fixing should not be a promblem.

**Comment by wumpz** [comment]
And thx for using JsqlParser ... :)
