### ISSUE TITLE
【AST】how can get an AST tree?

### ISSUE THREAD

**Issue by Voidly** [JSQLParser/JSqlParser#568]
how can I get an AST tree from JSqlParser?

**Comment by wumpz** [comment]
There is a unit test for it. But the AST is not complete. Only special nodes are preserved like table or column.

**Comment by wumpz** [comment]
Why do you need the AST tree? Why is the parse tree insufficient?

**Comment by Voidly** [comment]
Thanks for reply.I just want to analyze the lineage from AST
