### ISSUE TITLE
When "Task" is encountered in alias names it is converting to "tk"

### ISSUE THREAD

**Issue by pvporus** [JSQLParser/JSqlParser#572]
When "Task" is encountered in alias names it is converting to "tk".

Example: select task_id as "Task Id" from table test

After parsing the "Task Id" alias name is converted to "tk id".

This is a problem for us as we are using these alias names as view column names.

Can you please look into this.

**Comment by wumpz** [comment]
Very strange. I will look into it.

**Comment by wumpz** [comment]
Sorry, but I cant reproduce this behaviour. I made a test, as you see, which succeeds.

**Comment by pvporus** [comment]
Sorry Wumpz, this issue is at my side only. I am using the item.getAlias() only instead of  item.getAlias().getName() and replacing the "AS" with blank string, which is causing the issue.

Thanks for the prompt reply.

**Comment by wumpz** [comment]
No problem.
