### ISSUE TITLE
Oracle EXTRACT (XML) function

### ISSUE THREAD

**Issue by jsim5446** [JSQLParser/JSqlParser#579]
The EXTRACT(identifier FROM expression) production causes a parse error for [Oracle XML extract function](https://docs.oracle.com/cd/B19306_01/server.102/b14200/functions051.htm), which matches the typical function syntax.   I fixed this in my working copy by changing the lookahead for ExtractExpression production from 3 to 4.

**Comment by liuauto** [comment]
Hi I have the similar problem       extract(year from some_date) as some_year
Did the fix get released? 
Thanks,
Jie

**Comment by wumpz** [comment]
JSqlParser 4.0 parses this.
