### ISSUE TITLE
Parser does not like the column name "of"

### ISSUE THREAD

**Issue by rmahnovetsky** [JSQLParser/JSqlParser#580]
With the following sql 
`CCJSqlParserUtil.parse("select feeentity0_.of from vw_fee feeentity0_") `

I get this error. For some reason it does not like the "of" column. Is there anyway to fix this without altering the sql?

```
net.sf.jsqlparser.parser.ParseException: Encountered " "." ". "" at line 1, column 19.
Was expecting one of:
    <EOF> 
    "AS" ...
    "DO" ...
    "ANY" ...
    "KEY" ...
    "PERCENT" ...
    "END" ...
    "INTO" ...
    "FROM" ...
    "OPEN" ...
    "TABLE" ...
    "WHERE" ...
    "FOR" ...
    "XML" ...
    "UNION" ...
    "GROUP" ...
    "ORDER" ...
    "VALUE" ...
    "HAVING" ...
    "INSERT" ...
    "VALUES" ...
    "REPLACE" ...
    "TRUNCATE" ...
    "INTERSECT" ...
    "CAST" ...
    "EXCEPT" ...
    "MINUS" ...
    "OVER" ...
    "PARTITION" ...
    "EXTRACT" ...
    "MATERIALIZED" ...
    "START" ...
    "CONNECT" ...
    "PRIOR" ...
    "SIBLINGS" ...
    "COLUMN" ...
    "NULLS" ...
    "FIRST" ...
    "LAST" ...
    "ROWS" ...
    "RANGE" ...
    "FOLLOWING" ...
    "ROW" ...
    "COMMIT" ...
    "SEPARATOR" ...
    "CASCADE" ...
    "NO" ...
    "ACTION" ...
    <K_DATETIMELITERAL> ...
    "PRECISION" ...
    ";" ...
    <S_IDENTIFIER> ...
    <S_QUOTED_IDENTIFIER> ...
    "," ...
    "|" ...
    "&" ...
    "^" ...
    "::" ...
    "ORDER" ...
    "ORDER" ...
    ```

**Comment by artemsnisarenko** [comment]
It does not "like" it because `of` is a reserved word in standard SQL (http://developer.mimer.se/validator/sql-reserved-words.tml) and in this parser. You cannot use reserved words as database object names unless they are in double quotes or square brackets.

As you specifically mentioned that you don't want to modify the sql. Then you would have to modify the parser. Which means removing `of` from the list of keywords. So that "of" could be matched by the identifier rule.

**Comment by wumpz** [comment]
That is not quite true. JSqlParser supports keywords as identifiers. You have to adapt RegObjName rule and add there your keyword.

**Comment by rmahnovetsky** [comment]
ok fair enough it is a reserved word. Doesn't seem to be any easy way to ignore reserved words :(. I'll go down the path of updating the sql then.

**Comment by rmahnovetsky** [comment]
it was easy enough for me to alter the sql to have quotes around `of` and that fixed the issue.
