### ISSUE TITLE
parsing fails when tag around alias

### ISSUE THREAD

**Issue by dondank** [JSQLParser/JSqlParser#583]
### Steps to Reproduce the Problem

  1. parse "SELECT CASE WHEN T.ISC = 1 THEN T.EXTDESC WHEN T.b = 2 THEN '2' ELSE T.C END AS 'Test' from T"  - will fail

 2. will work: "SELECT CASE WHEN T.ISC = 1 THEN T.EXTDESC WHEN T.b = 2 THEN '2' ELSE T.C END AS Test from T"

### Specifications

  - Version:  latest
  - Platform: all
  - Subsystem:

**Comment by wumpz** [comment]
Jsqlparser does not support single quotes for dB object names or aliases. Only double quotes are supported. Single quotes are for string literals.

**Comment by dondank** [comment]
this query (which is part of a bigger query) executes on SQL Server in a correct manner.
