### ISSUE TITLE
net.sf.jsqlparser.JSQLParserException about index issue

### ISSUE THREAD

**Issue by Hackeruncle** [JSQLParser/JSqlParser#586]
VERSION: 1.1
**SQL:**
CREATE TABLE biz_add_fee (
  id bigint(20) NOT NULL AUTO_INCREMENT,
  operation_time timestamp ,
  warehouse_code varchar(32) ,
  customerid varchar(32) ,
  fees_type varchar(32),
  external_no varchar(128) ,
  PRIMARY KEY (id),
  UNIQUE KEY operation_time (operation_time)
) ;

ALTER TABLE BIZ_ADD_FEE DROP INDEX OPERATION_TIME , 
ADD UNIQUE INDEX OPERATION_TIME (OPERATION_TIME, WAREHOUSE_CODE, CUSTOMERID, FEES_TYPE, EXTERNAL_NO) USING BTREE;

**Error:**
net.sf.jsqlparser.JSQLParserException

**Comment by PraTrick** [comment]
Created [PR-752](https://github.com/JSQLParser/JSqlParser/pull/752)
