### ISSUE TITLE
Dependency Injection Isn't Working

### ISSUE THREAD

**Issue by brobusf21** [JSQLParser/JSqlParser#590]
### Actual Behavior
When copying and pasting the Maven dependency code in my POM, Maven tells me that the version does not exist. I have tried all versions. 
### Expected Behavior
I'm expecting to use the application within my project. 
### Steps to Reproduce the Problem

  1. Tried all versions within the POM. 

### Specifications

  - Version: 1.1, 1.0, 0.9, 0.8, etc.
  - Platform: 
  - Subsystem:

**Comment by wumpz** [comment]
All released versions are published and searchable at maven central: https://mvnrepository.com/artifact/com.github.jsqlparser/jsqlparser

Maybe you have a different problem. Do you have a concrete Exception?

Cheers Tobias

**Comment by brobusf21** [comment]
Tobias,

The issue cleared up the following day. Thanks for the help. For version 1.1, when will the documentation be updated? I noticed that the some of the packages do not exist such as  net.sf.jsqlparser.statement.SetStatement? Or maybe the updated documentation is posted elsewhere? 

Thanks,

Brandon

**Comment by wumpz** [comment]
Strange. The doc is generated by maven from the sources.

**Comment by wumpz** [comment]
SetStatement is an existing class. Just look into the sources here at GitHub.
