### ISSUE TITLE
TableNamesFinder refactoring

### ISSUE THREAD

**Issue by adriil** [JSQLParser/JSqlParser#591]
Hi !

This is more a proposal than an issue :)

I needed to go through the expression tree in order to retrieve columns names (a kind of TableNamesFinder for columns), and I've found that someone already created the issue #472. I've followed the link and managed to have the perfect solution.
However, I think having to extend TableNamesFinder is not smooth. What we really want by extending it is all the visitor engine. But because there's not such a (abstract) class, we extend TNF by default.

So I think it could be better to split TableNamesFinder in two classes : the first would be an AbstractFinder and will implement all visitor interfaces (what is already done by TNF), and the second would be a lighter TableNamesFinder which will extend AbstractFinder and override only what is needed to save tables names.
Plus, this way, it could be easy to add a built-in ColumnNamesFinder extending AbstractFinder, or anything else you want to look for in the whole expression.

Best regards.

**Comment by wumpz** [comment]
Do you know the already implemented adapter classes.

**Comment by adriil** [comment]
I admit I didn't see adapter classes before asking.

But if I'm not wrong, they just implement visitor interfaces and does not contain all the logic already written in TableNamesFinder to look through the whole tree. This is what they are for as Adapter, but if I want to go through the expression, wouldn't be better to reuse the whole-tree-visit logic of TNF, instead of making a clone of this (as 95% of code will be the same) using adapter for each type of node I could meet to be sure I'm looking through the whole tree ?

Or maybe I'm not seing the right way how Adapter can help me for this. Then I apologize for my misunderstanding.

**Comment by wumpz** [comment]
I agree with you a separation would have benefits. But I would not start at TableNamesFinder. It is designed in a way to stop at tables or columns. A better approach would be to use the deparsers for a basis, which does definitly run through the whole sql. But a problem would be to inject functionality between the logic of one visitor method. E.g. to scamble all string values that are part of a where binary expression and leave the rest untouched.

**Comment by wumpz** [comment]
Then you would again copy the method implementation and integrate your changes. I am unsure, what is the lesser problem.

**Comment by adriil** [comment]
I see, my mistake was to consider Table and Column as final nodes.
I was going to propose that the AbstractFinder could implement the IntoTableVisitor interface, so it could go through Table and Column as default behaviour. But then the TableNamesFinder, by extending the AbstractFinder, would implement an interface which is useless for it, as like you said it stops at tables...
