### ISSUE TITLE
Snowflake compatible query not parseable

### ISSUE THREAD

**Issue by Shivasish** [JSQLParser/JSqlParser#593]
Trying to parse this query using JSqlParser : 
select count(distinct case when client_organic_search_drop_flag=1 then brand end) over (partition by client,category_1,category_2,category_3,category_4 order)as client_brand_org_drop_count
 from sometable .

Getting the below stack trace :                                                                                       
 Caused by: net.sf.jsqlparser.parser.ParseException: Encountered " "(" "( "" at line 1, column 88.
Was expecting one of:

This query runs fine on Snowflake. Can someone help me out with tweaking the syntax so that it gets parsed by the parser.

Using maven version: 0.9.5 with java 1.8

**Comment by wumpz** [comment]
My first guess is to write out a complete **order by** statement. I reviewed the documentation of snowflake and could not find any hint of 

`over (partition by a,b,c order) ...`

Are you positive, the statement of yours is correct?

**Comment by Shivasish** [comment]
Yup this statement works on Snowflake. I removed the order by statement and
still tried. Same result.

**Comment by Shivasish** [comment]
The query gets parsed if I remove the distinct keyword.

select count( case when client_organic_search_drop_flag=1 then brand end) over (partition by client,category_1,category_2,category_3,category_4)as client_brand_org_drop_count
from sometable .

Can you suggest some workaround for the original query to make it parseable?

**Comment by wumpz** [comment]
Hmm. I was not aware, that a distinct is allowed within a window function. I will look into it. Cheers Tobias
