### ISSUE TITLE
A MySQL SQL statement cannot be parsed.

### ISSUE THREAD

**Issue by sentenes** [JSQLParser/JSqlParser#598]
Can't parse the following statement :

    ifnull(sum(if(o.bet_status=5,o.bet_fee,0)),0) as sumRefund
    ifnull(sum(if(o.bet_status=2,o.win_fee,0)),0) as sumPrize,
    ifnull(sum(if(o.bet_status=5,o.bet_fee,0)),0) as sumRefund,

The version of MySQL : 5.6.19
The version of jsqlparser : 1.1

Full SQL statement : 
    
    select
        ifnull(o.order_source,'1')  as channelName,
        tmp.date as `date`,
        "ETH" as betType,
        ifnull(sum(o.bet_fee),0) as sumBet,
        count(o.order_id) as countOrder ,
        ifnull(sum(if(o.bet_status=2,o.win_fee,0)),0) as sumPrize,
        ifnull(sum(if(o.bet_status=5,o.bet_fee,0)),0) as sumRefund,
        ifnull(sum(o.reward_fee),0) as sumReward
    from
    (
        SELECT
            @eth :=@eth + 1,
            DATE_FORMAT(ADDDATE(?,INTERVAL @eth DAY),"%Y-%m-%d") AS date
        FROM
          tab_day d,(SELECT @eth := 0) t
        WHERE
            ADDDATE(?,INTERVAL @eth DAY)  <  ADDDATE(?, '%Y-%m-%d')
    ) tmp left join
    t_loto_order o on tmp.date = date_format(o.create_time,"%Y-%m-%d")
                and (o.electronic_code = "ETH" or o.electronic_code is null)
                and (o.order_source = ? or o.order_source is null)
    group by tmp.date

Create the statement for the table: 

	CREATE TABLE `t_loto_order` (
	  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT '编号',
      `electronic_code` varchar(20) NOT NULL DEFAULT '' COMMENT '电子货币类型简称',
	  `order_id` varchar(50) NOT NULL DEFAULT '' COMMENT '投注编号',
	  `user_pin` varchar(50) NOT NULL DEFAULT '' COMMENT '用户pin',
	  `issue` varchar(50) NOT NULL DEFAULT '' COMMENT '期号',
	  `vsteam` varchar(80) NOT NULL DEFAULT '' COMMENT '对阵信息',
	  `vsresult` varchar(80) NOT NULL DEFAULT '' COMMENT '对阵结果   ',
	  `bet_fee` bigint(11) NOT NULL DEFAULT '0' COMMENT '投注金额',
	  `win_fee` bigint(11) NOT NULL DEFAULT '0' COMMENT '奖金,0表示未中奖',
	  `create_time` datetime NOT NULL COMMENT '创建时间',
	  `bet_type` int(7) NOT NULL DEFAULT '0' COMMENT '投注玩法,301胜平负305让球胜平负307胜负309大小分 501话题竞猜',
	  `bet_info` varchar(20) NOT NULL DEFAULT '' COMMENT '投注方案 had_h 胜, had_a负 had_d平',
	  `bet_status` int(2) NOT NULL DEFAULT '0' COMMENT '兑奖状态,0支付中,1已支付(待兑奖)，2已中奖，3未中奖，4已取消, 5不中返还',
	  `prize_status` int(2) NOT NULL DEFAULT '1' COMMENT '派奖状态,1未派奖2已派奖',
	  `prize_type` int(2) NOT NULL DEFAULT '1' COMMENT '派奖类型,1自动2手动',
	  `prize_cancel_time` datetime NOT NULL DEFAULT '1900-01-01 00:00:00' COMMENT '派奖(取消)时间',
	  `order_source` varchar(50) NOT NULL DEFAULT '' COMMENT '来源',
	  `match_result` varchar(50) NOT NULL DEFAULT '' COMMENT '比赛结果  比分  e.g.  3:2',
	  `memo` varchar(200) NOT NULL DEFAULT '' COMMENT '备注',
	  `options_one` varchar(50) NOT NULL DEFAULT '' COMMENT '选项1',
	  `options_two` varchar(50) NOT NULL DEFAULT '' COMMENT '选项2',
	  `options_three` varchar(50) NOT NULL DEFAULT '' COMMENT '选项3',
	  `play_method` varchar(100) NOT NULL DEFAULT '' COMMENT '话题标题',
	  `leaguename` varchar(50) NOT NULL COMMENT '比赛名称',
	  `reward_fee` varchar(50) NOT NULL DEFAULT '0' COMMENT '奖励金额',
	  `reward_user_pin` varchar(50) NOT NULL DEFAULT '' COMMENT '奖励用户UID',
	  `reward_bet_fee` varchar(50) NOT NULL DEFAULT '0' COMMENT '奖励投注金额, 使用猜球系统奖励的虚拟币进行投注的金额',
	  PRIMARY KEY (`id`),
	  KEY `ix_ORDER_ID` (`order_id`)
	) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

**Comment by smembers** [comment]
Provide several test data: 

    INSERT INTO `t_loto_order` (`id`, `electronic_code`, `order_id`, `user_pin`, `issue`, `vsteam`, `vsresult`, `bet_fee`, `win_fee`, `create_time`, `bet_type`, `bet_info`, `bet_status`, `prize_status`, `prize_type`, `prize_cancel_time`, `order_source`, `match_result`, `memo`, `options_one`, `options_two`, `options_three`, `play_method`, `leaguename`, `reward_fee`, `reward_user_pin`, `reward_bet_fee`) VALUES ('41', 'ETH', '6970e44aa5e842a7bb3689ee6fa62f28', 'yy001', '2018032218580000', '曼联vs曼城', '', '300', '1920', '2018-03-27 15:55:11', '501', 'options_three|6.4', '1', '1', '1', '1900-01-01 00:00:00', '1', '', 'yy', '0个', '1个', '1个以上', '梅西上半场能进几个球', '英超', '', '', '');
	INSERT INTO `t_loto_order` (`id`, `electronic_code`, `order_id`, `user_pin`, `issue`, `vsteam`, `vsresult`, `bet_fee`, `win_fee`, `create_time`, `bet_type`, `bet_info`, `bet_status`, `prize_status`, `prize_type`, `prize_cancel_time`, `order_source`, `match_result`, `memo`, `options_one`, `options_two`, `options_three`, `play_method`, `leaguename`, `reward_fee`, `reward_user_pin`, `reward_bet_fee`) VALUES ('42', 'ETH', 'ecc6a2676cf841078c20c15af6224536', 'yy001', '2018032218580000', '曼联vs曼城', '', '300', '1920', '2018-03-27 15:57:15', '501', 'options_three|6.4', '1', '1', '1', '1900-01-01 00:00:00', '1', '', 'yy', '0个', '1个', '1个以上', '梅西上半场能进几个球', '英超', '', '', '');
	INSERT INTO `t_loto_order` (`id`, `electronic_code`, `order_id`, `user_pin`, `issue`, `vsteam`, `vsresult`, `bet_fee`, `win_fee`, `create_time`, `bet_type`, `bet_info`, `bet_status`, `prize_status`, `prize_type`, `prize_cancel_time`, `order_source`, `match_result`, `memo`, `options_one`, `options_two`, `options_three`, `play_method`, `leaguename`, `reward_fee`, `reward_user_pin`, `reward_bet_fee`) VALUES ('43', 'ETH', '526d54723a9349c8bddfc776b4a1c8c7', 'yy001', '2018032218580000', '曼联vs曼城', '', '300', '1920', '2018-03-27 15:58:24', '501', 'options_three|6.4', '1', '1', '1', '1900-01-01 00:00:00', '1', '', 'yy', '0个', '1个', '1个以上', '梅西上半场能进几个球', '英超', '', '', '');

**Comment by yuechao4039** [comment]
is this question had bean fixed ? i encountered too

**Comment by yuechao4039** [comment]
@smembers

**Comment by smembers** [comment]
@yuechao4039  No

**Comment by manticore-projects** [comment]
The relevant part is parsed correctly with JSQLParser 4.3 Snapshot.
[Test it online here](http://jsqlformatter.manticore-projects.com/jsqlformatter/demo.html?args=-c%20MoUQMiDCAqAEsEkBmA7ArgGwwClgewDo8AnAEwFNiB9AZzzWIGNyAaWAcgEZ3YBKWAILBYjABYBDFCnIYU4gLbkAUPFWq2AF3kAHAqXEbyg4QAN9hkyrXrYAIhDQAEreOwARuQ0aAntuXWbZHQsXGA0eVxCDw0qJHIjXjYABj5XGnDoqwC2SHoUDUiiMkoqAEtSVKERPI0SCmIs6zYgzBxYMIjEJELo2g0DNBpYAF5YACY2QgB3UpRY+OTUxNgU-ir0nWJSgC9-ANhm1FbQ8NxkHs8+gaHRgFZJgl641hWlxbXhDeJyJDQUUkaakOwTaHUK3ym4jI8wS7zS4QhUIBADEAEoAeQAsrAtNpGhBkXAAFLohAAORxVAweFqVDqlHwgNU6IpuL0BiMowAIhyqMiSPIDIVGN9eRpSoo2LYAKQATQAtNL5IrSC5eEyAgIyVzYIUZORGBpiHgUKVGFRGHgKCM7A5nBr9gF0aj8AR9YbjabzZbrQhhGSAKpgMB8B1qLU6wr06h0BjMG0AfjDjuZLsI0do9CYRj9sEDwdDAHEMQGAAqwABCspxOnZhiUAG4gA+)
