### ISSUE TITLE
TablesNamesFinder loses schema in delete statement

### ISSUE THREAD

**Issue by besok** [JSQLParser/JSqlParser#600]
### TablesNamesFinder loses schema in delete statement
```
        String sql = "delete from schema.table where id = 1";
        Statement st = CCJSqlParserUtil.parse(sql);
        List<String> tbs = new TablesNamesFinder().getTableList(st);
```    
It returns = table without schema.

### Expected solution:
TablesNamesFinder can  describe schema for delete statement 
https://github.com/JSQLParser/JSqlParser/blob/652766264a2bb6163e72b2372e1cdf78f38bbc0f/src/main/java/net/sf/jsqlparser/util/TablesNamesFinder.java#L621

` delete.getTable().getName() => delete.getTable().getFullyQualifiedName() `

I can make pull request or you can fix it by yourself if it is correct of course.

**Comment by wumpz** [comment]
I looked into it. Its a mess. TableNamesFinder does use dependent of the starting statement getFullyQualifiedName or getName.

**Comment by wumpz** [comment]
OK. Now all table name extractor occurrences of TableNamesFinder are mapped through the Table visitor.

**Comment by besok** [comment]
Thank you.
