### ISSUE TITLE
OR not parsed correctly

### ISSUE THREAD

**Issue by dondank** [JSQLParser/JSqlParser#602]
following fails to parse:

`SELECT x OR y from T`

net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "OR" "OR"
    at line 1, column 10.

**Comment by wumpz** [comment]
At the moment this type of expression (x or y) is not supported as selected item.

**Comment by wheredevel** [comment]
Tested this on MySQL (example is based on Sakila):
```sql
SELECT city_id OR country_id FROM city
```
Also with `||`:
```sql
SELECT city_id || country_id FROM city
```
