### ISSUE TITLE
Options for Eclipse

### ISSUE THREAD

**Issue by MarcMazas** [JSQLParser/JSqlParser#606]
### Actual Behavior
When importing the project in Eclipse, with Automatic build, generated classes are in a temp directory in target. So compilation errors appear, and do not disappear after a mvn package.

### Expected Behavior
No compilation errors.

Just need to add the following options in the .jjt file : 
    OUTPUT_DIRECTORY = "../../../../../java/net/sf/jsqlparser/parser";
    VISITOR = true; // (default false)
    NODE_DEFAULT_VOID = true; // (default false)
    TRACK_TOKENS = true; // (default false)

And add the src/main/jjtree in the project's build path.

### Steps to Reproduce the Problem

  1.
  1.
  1.

### Specifications

  - Version:
  - Platform:
  - Subsystem:

**Comment by wumpz** [comment]
Why would you have to do that? JSqlParser is a maven project and therefore all directories and stuff are and should be controlled by maven.
The other options are specified as well using the maven build cycle within the pom.xml. But maybe that is a good idea to move it directly to the jjt file.

**Comment by wumpz** [comment]
Included options without the path.

**Comment by MarcMazas** [comment]
Hi
Sorry, I missed your replies.
"Why would you have to do that? JSqlParser is a maven project and therefore all directories and stuff are and should be controlled by maven."
It would be nice to do that as the project would be fine under maven (through the javacc maven plugin you use) **_and_** the javacc eclipse plugin (I use).
If I remember, there is no explicit maven parameter in you pom.xml to configure the directory, so maven takes the javacc maven plugin default under a temp directory under target. If you set the javacc option, it will be used by the maven plugin and the eclipse automatic build.
