### ISSUE TITLE
can't parse sql as follows

### ISSUE THREAD

**Issue by BazzJiang** [JSQLParser/JSqlParser#607]
### Actual Behavior
net.sf.jsqlparser.JSQLParserException
Caused by: net.sf.jsqlparser.parser.ParseException: Encountered " "(" "( "" at line 1, column 36.
### Expected Behavior
get tables list
### Steps to Reproduce the Problem
    @Test
    public void extractTableTest() throws Exception{
        String sqlString = "select * from User u where (u.name,u.age)=('bazz',20)";
        Statement statement = CCJSqlParserUtil.parse(sqlString);
        TablesNamesFinder tablesNamesFinder = new TablesNamesFinder();
        List<String> tableList = tablesNamesFinder.getTableList(statement);
        tableList.forEach(System.out::println);
    }

### Specifications

  - Version:jsqlparser 1.1
  - Platform: windows 7 mysql5.7
  - Subsystem:

**Comment by AnEmortalKid** [comment]
@wumpz this works with the latest version from master and prints user:
![image](https://user-images.githubusercontent.com/3474369/85214477-b97cfe00-b330-11ea-8611-71ba7eff9f54.png)
