### ISSUE TITLE
Dotted notation should be supported in UserVariable.

### ISSUE THREAD

**Issue by wheredevel** [JSQLParser/JSqlParser#608]
Query of interest:  
```sql
select @@session.tx_read_only
```

### Actual Behavior
```
Error parsing statement `select @@session.tx_read_only`: 
Encountered unexpected token: "." "."
    at line 1, column 17.
 
Was expecting one of:
 
    "&"
    ","
    "::"
    ";"
    "<<"
    ">>"
 ...
```
 
### Expected Behavior
As in the example query (`select @@session.tx_read_only`) one can use a UserVariable with **dotted notation**. See: https://dev.mysql.com/doc/refman/5.7/en/set-variable.html.

### Steps to Reproduce the Problem
Parse 
```
select @@session.tx_read_only
```  

### Specifications

  - Version:
  - Platform:
  - Subsystem:

**Comment by wumpz** [comment]
Same applies to column and table names. Especially if someone parses ORM sqls where tablenames could be class names. 

Maybe I should introduce some kind of "dotted notation" identifier and use it for tables and columns as well (sure some mapping should be done: servername, instancename, etc.)

**Comment by wumpz** [comment]
Using SqlServer you can write something like:

`SELECT columnName FROM [server-name\\server-instance].databaseName.schemaName.tableName`

What I ment was a production like

`RelObjName() ( "." RelObjName())*`

to accept this kind of uservariable, column or table and then make especially for table
a mapping to the sqlserver meaning if necessary. That would solve your problem, the ORM class name problem but introduce some overhead to get the schema name or database name.

Therefore I could introduce this dottedObjectName for all of this.

**Comment by wheredevel** [comment]
OK, that would be great.

**Comment by wumpz** [comment]
Here is a similar issue #163.

**Comment by wheredevel** [comment]
Thanks!
