### ISSUE TITLE
TRUNCATE not handled properly

### ISSUE THREAD

**Issue by ted-johnson** [JSQLParser/JSqlParser#613]
There are two related issues.
1) CASCADE is not handled even though it is valid postgresql syntax, e.g. the following does not parse
      truncate table global_uids CASCADE;
2) A TRUNCATE command is not rendered to SQL in the default StatementDeParser.
E.g., I wrote a utility to split a file with multiple SQL statements to multiple files each with one SQL statement, and the TRUNCATE statements were blank.

FIXES:
I did the following to fix this problem.

1) Truncate.java
  a) added the following class variable after line 33:
//        ADDED: by Ted Johnson to incorporate TRUNCATE TABLE ... CASCADE
    boolean cascade;
   b) Added two methods to get/set cascade:
//      ADDED: by Ted Johnson
    public boolean getCascade(){
        return cascade;
    }

//     ADDED: by Ted Johnson
    public void setCascade(boolean c){
        cascade=c;
    }

2) JSqlParserCC.jjt
Changed the Truncate() method, line 3372 or so, to the following:

Truncate Truncate():
{
    Truncate truncate = new Truncate();
    Table table;
}
/*	ADDED: optional K_CASCADE, can be used in postgresql */
{
    <K_TRUNCATE> <K_TABLE>
    table=Table() { truncate.setTable(table); truncate.setCascade(false); } [ <K_CASCADE> {truncate.setCascade(true);} ] 
    {
        return truncate;
    }
}

3) StatementDeParser.java
Filled in the body of the visit(Truncate truncate) method, line 146 or so, as follows

    @Override
    public void visit(Truncate truncate) {
//        ADDED: by ted johnson
        buffer.append("TRUNCATE TABLE ");
        buffer.append(truncate.getTable());
        if(truncate.getCascade()){
            buffer.append(" CASCADE");
        }
    }

With these changes JSqlParser will properly parse TRUNCATE ... CASCADE statements, and will
properly generate the SQL via the default SQL generation.
I rebuilt JSqlParser using
    mvn package
and the updated code passed all tests.

     Ted Johnson

**Comment by wumpz** [comment]
Please provide a pull request for your changes.

**Comment by wumpz** [comment]
Could you provide a valid pull request for this?

**Comment by ted-johnson** [comment]
Yes, and many more.
I needed to switch to an urgent and demanding project,
But will switch back soon.

                Ted

**Comment by manticore-projects** [comment]
This works with latest JSQLParser 4.6 so I am closing this.
