### ISSUE TITLE
how to iterate inner select query which is in select query column

### ISSUE THREAD

**Issue by Umesh-Markande** [JSQLParser/JSqlParser#618]
### Actual Behavior

select
  index_imsid,
  SUM(weighted_value) sumWeightedValue,
  **(
    select
      top 1 percentof
    from
      [v_PlanPerProvider1]
    where
      [PLAN_RANK] = 1
  )** percentof,
  **(
    concat (
      CAST(z_mkt_prdct_spclt.ptnt_gid AS string),
      CAST(z_mkt_prdct_spclt.prdct_gid AS string)
    ) NOT IN (
      SELECT
        top 1 [Plan_Name_OR_Payment_Type]
      from
        [v_PlanPerProvider1]
      where
        [PLAN_RANK] = 1
    )
  )** Plan_Name_OR_Payment_Type
from
  [v_PlanPerProvider1]
where
  plan_rank between 1
  and 10
group by
  index_imsid
order by
  1

I want to iterate this multiple select and change the where condition for all select which in select column.
How to iterate this, can anyone implemented using CCJSqlParserUtil or any other concern.

Thanks in advance.

**Comment by Umesh-Markande** [comment]
Any example of SubSelect using SelectItems, I have tried but SelectItem accept SelectItemVisitor interface. how to build a visitor for subselects.

Thank you.

**Comment by wumpz** [comment]
I looked into your sql. First of all it is not parsable due to this in - expression as a select item. Thats a lacking feature of JSqlParser.  I removed this item and here is a simple example of how to achieve, what you want. 

```Java
public static void main(String args[]) throws JSQLParserException {
	Select select = (Select)CCJSqlParserUtil.parse("select index_imsid, SUM(weighted_value) sumWeightedValue, ( select top 1 percentof from [v_PlanPerProvider1] where [PLAN_RANK] = 1 ) percentof from [v_PlanPerProvider1] where plan_rank between 1 and 10 group by index_imsid order by 1");

	 for (SelectItem item : ((PlainSelect)select.getSelectBody()).getSelectItems()) {
		 if (item instanceof SelectExpressionItem) {
			 Expression expr = ((SelectExpressionItem)item).getExpression();
			 if (expr instanceof SubSelect) {
				 replaceWhere(((SubSelect)expr).getSelectBody());
			 }
		 }
	}
	 
	System.out.println("changed sql = " + select.toString());
}

private static void replaceWhere(SelectBody selectBody) throws JSQLParserException {
	System.out.println("changing " + selectBody);
	((PlainSelect)selectBody).setWhere(CCJSqlParserUtil.parseCondExpression("mycol = 10"));
}
```

**Comment by wumpz** [comment]
So can we close this?

**Comment by Umesh-Markande** [comment]
Yes, thanks
