### ISSUE TITLE
Oracle SQL slash  (/) command parse error

### ISSUE THREAD

**Issue by pumpkinlink** [JSQLParser/JSqlParser#619]
The slash command is used to basically flush the SQL buffer on Oracle SQL. 
Documentation: https://docs.oracle.com/en/database/oracle/oracle-database/12.2/sqpug/slash.html#GUID-F5EEC10C-6E74-4CCE-A196-C591F83C3D44

### Actual Behavior
```
net.sf.jsqlparser.JSQLParserException
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parseStatements(CCJSqlParserUtil.java:154)
	at (...)
	at (...)
Caused by: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "/" "/"
    at line 5, column 1.

Was expecting one of:

    "("
    "+"
    "-"
    ";"
    "="
    "CASCADE"
    "CHECK"
    (...)
```
### Expected Behavior
interpret slash as an end of statement marker (like a semicolon)
### Steps to Reproduce the Problem

  1. 
```java
String script = "select * from test;\n" +
"/\n" +
"select * from test2\n";
```
  2.
```java
Statements s = CCJSqlParserUtil.parseStatements( script );
``` 
### Specifications

  - Version: JSqlParser 1.2
  - Platform: Oracle JRE 1.8.0_151

**Comment by wumpz** [comment]
But that is not a sql command but a sqlplus command of oracle. JSqlparser is a sql parser. this will not be implemented. sorry.

**Comment by pumpkinlink** [comment]
Oh, its ok then. my bad, sorry to bother
