### ISSUE TITLE
TRIM syntax unsupported

### ISSUE THREAD

**Issue by tomershay** [JSQLParser/JSqlParser#623]
In most databases, the TRIM function expects non standard parameters such as BOTH (and several others) to indicate the directions in which to trim the string.
https://dev.mysql.com/doc/refman/8.0/en/string-functions.html#function_trim

For example, this query is valid but unsupported by the latest JSqlParser:
SELECT TRIM(BOTH 'x' FROM 'xxxbarxxx');

The error from the parser:
Encountered unexpected token: "(" "("    at line 1, column 12.

**Comment by wumpz** [comment]
JSqlParser 4.0 parses this.
