### ISSUE TITLE
string field is ""

### ISSUE THREAD

**Issue by renjuncn** [JSQLParser/JSqlParser#627]
### Actual Behavior
where some_field = ""
### Expected Behavior
parse correct
### Steps to Reproduce the Problem

  1. any sql with where xxx=""
### Specifications

  - Version:1.2
  - Platform:mac
  - Subsystem:idea

**Comment by wumpz** [comment]
Double quotes are mainly used for referencing database object names. For string literals single quotes should be used. where xxx='' workds perfectly well.
