### ISSUE TITLE
Statements to check

### ISSUE THREAD

**Issue by dprutean** [JSQLParser/JSqlParser#633]
Please fix also this statements. They are not working in version 1.2, tested with Postgres. The first one is
more important, it pretty often generated by backup scripts.

ALTER TABLE  team_phases
    ADD CONSTRAINT team_phases_id_key UNIQUE (id)

CREATE INDEX idx_american_football_action_plays_1 ON american_football_action_plays USING btree (play_type)

**Comment by wumpz** [comment]
first statement now passes

**Comment by AnEmortalKid** [comment]
Both of these work:
```java
  public static void main(String[] args) throws Exception {
    System.out.println(
        CCJSqlParserUtil.parse(
            "ALTER TABLE team_phases\n" + "ADD CONSTRAINT team_phases_id_key UNIQUE (id)"));
  }
```
DEBUG:
https://gist.github.com/AnEmortalKid/339ad84e64bb80aab4bfcad1624d4806#file-alter_constraint_parse


```java
  public static void main(String[] args) throws Exception {
    System.out.println(
        CCJSqlParserUtil.parse(
            "CREATE INDEX idx_american_football_action_plays_1 ON american_football_action_plays USING btree (play_type)"));
  }
```
DEBUG:
https://gist.github.com/AnEmortalKid/339ad84e64bb80aab4bfcad1624d4806#file-create_index_parse

**Comment by AnEmortalKid** [comment]
@wumpz I believe this is fixed.

**Comment by wumpz** [comment]
@AnEmortalKid You are right.
