### ISSUE TITLE
Encountered unexpected token: "is" "IS" when has "is true"

### ISSUE THREAD

**Issue by yushengcao** [JSQLParser/JSqlParser#642]
### Actual Behavior
When sql contains 'is true'  throw:

net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "is" "IS"
    at line 1, column 32.
Was expecting one of:

    "."
    ";"
    "AND"
    "CONNECT"
    "EXCEPT"
    "FOR"
    "GROUP"
    "HAVING"
    "INTERSECT"
    "MINUS"
    "ORDER"
    "START"
    "UNION"
    <EOF>

### Steps to Reproduce the Problem

  1. parser sql : "select * from t_operate where b_switch is true"
  2. database postgresql

### Specifications

  - Version:1.2
  - Platform:postgresql
  - Subsystem:

**Comment by anderruiz** [comment]
We are having the same error, any available workaround?

**Comment by sivaraam** [comment]
This doesn't seem to be an issue with the latest version of the library (3.1). The following statement parses without issues:

```sql
select * from t_operate where b_switch is true
```

**Comment by wumpz** [comment]
You are right. It was solved some time ago. I just missed to close this one.
