### ISSUE TITLE
When sql contains column 'zone' throw

### ISSUE THREAD

**Issue by Neil-Zhou** [JSQLParser/JSqlParser#643]
### Actual Behavior
When sql contains column 'zone' throw:

net.sf.jsqlparser.parser.ParseException: Encountered " "ZONE" "zone "" at line 6, column 48.
Was expecting one of:
Was expecting one of:
    "DO" ...
    "ANY" ...
    "KEY" ...
    "SET" ...
    "PERCENT" ...
    "END" ...
    "NULL" ...
    "LEFT" ...
    "OPEN" ...
### Expected Behavior
1、parser sql : select id, bid, pid, devnum, pointdesc, sysid, zone, sort from fault order by id desc LIMIT ?, ?
2、database mysql

### Specifications

  - Version:1.0
  - Platform: mysql
  - Subsystem:

**Comment by wumpz** [comment]
At the moment I do not remember if zone is a keyword. Let me take a look.

**Comment by wumpz** [comment]
It's a keyword. It should be integrated into RelObjName. Pr is welcome.
