### ISSUE TITLE
Failed to Parse When exist bracket in SQL, like this : cc.scc[0]

### ISSUE THREAD

**Issue by uusnow** [JSQLParser/JSqlParser#645]
### Actual Behavior
`select username, signno, transtime, split(cc.scc[0],'-')[0] from ......`
When sql contains bracket throw:
net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "(" "("
Was expecting one of:
"&"
","
"."

### Expected Behavior
1、parser sql 
2、database oracle

### Steps to Reproduce the Problem

  1. String sql = "select username, signno, transtime, split(cc.scc[0],'-')[0] from cc"
  1. Select selectStmt = (Select)CCJSqlParserUtil.parse(sql);
  1. 

### Specifications

  - Version: 1.2
  - Platform: win10  
  - Subsystem: eclipse , jdk 1.8.0_172

**Comment by wumpz** [comment]
The problem is, that this is colliding with sqlservers [ .. ] object name quotation. So there is at the moment no solution for this.

**Comment by wumpz** [comment]
This is solved since 3.0. There array processing support was implemented.
