### ISSUE TITLE
How to make a SQL sentence in Oracle format from net.sf.jsqlparser.statement.select.Select;

### ISSUE THREAD

**Issue by awfssv** [JSQLParser/JSqlParser#646]
- Version: JSqlParser 1.2
  - Platform: jdk 1.8, Eclipse, Oracle
  - Subsystem:

I try to make a Oracle sentence by below code, but the code return a MySQL sentence.
May I know how to make a SQL sentence in Oracle format from net.sf.jsqlparser.statement.select.Select;?

===================
 if(selectBody instanceof PlainSelect){
	 PlainSelect plainSelect = (PlainSelect) selectBody;
	 if(plainSelect.getLimit() == null) plainSelect.setLimit(limit);
 }else if(selectBody instanceof SetOperationList){
	 SetOperationList setOperationList = (SetOperationList) selectBody;
         if(setOperationList.getLimit() == null) setOperationList.setLimit(limit);
	  }
 }
System.out.println(selectStatement.toString());
==============================

Thanks.

Lim.

**Comment by wumpz** [comment]
Tostring and deparser try to reconstruct the parsed SQL as good as possible. There is no oracle or mysql switch.

**Comment by awfssv** [comment]
@wumpz, I just want to make a Oracle sentence from JSqlParser PlainSelect instance, may I know how to realizing this demand?
Thank you very much!

**Comment by wumpz** [comment]
@awfssv Back online. Do you mean by sentence an oracle formatted sql?

**Comment by wumpz** [comment]
It would be nice to have a result sql and the expected sql you want to achieve.

**Comment by wumpz** [comment]
Should I close this? I expected some more data.

**Comment by AnEmortalKid** [comment]
Can probably close this since it's been 2 years?

**Comment by wumpz** [comment]
Since there was no answer at least for two years.
