### ISSUE TITLE
Escaped function broken since 0.96

### ISSUE THREAD

**Issue by xsgao-github** [JSQLParser/JSqlParser#647]
### Actual Behavior
CCJSqlParserUtil.parse("SELECT {fn CURRENT_TIMESTAMP(0)} AS COL") throws exception: Encountered " "{fn" "{fn "" at line 1, column 8.

### Expected Behavior
This call should return select statement.

### Steps to Reproduce the Problem

  1. This line works from 0.93 to 0.95.
  2. This line broken since 0.96, 0.97, 1.1 and 1.2

### Specifications

  - Version: 0.96+
  - Platform: Windows/JDK 7
  - Subsystem:

**Comment by wumpz** [comment]
My guess is that it depends on the function name. There are definitely tests for fun escaping. Could you please try another function?

**Comment by xsgao-github** [comment]
concat(a, b) does not work either. I cannot imagine this is caused by function name, there are infinite number of functions names if you include user defined functions.

**Comment by wumpz** [comment]
CURRENT_TIMESTAMP was introduced as a keyword. Thats why this was my first guess.

**Comment by wumpz** [comment]
I introduced a test for escaped functions. implementing current_timestamp is not possible at the moment due to its special handling of time key functions, which differs from other functions.

**Comment by xsgao-github** [comment]
Thanks. I confirm that some SQL92 reserved words (upper, extract, day, etc.) are working, some are not (current_date, current_timestamp, etc.).

**Comment by manticore-projects** [comment]
Works with JSQLParser 4.6 thanks to improved keyword management.
[Test it online.](http://jsqlformatter.manticore-projects.com/jsqlformatter/demo.html?args=-c%20MoUQMiDCAqAEsG8BiA7WkCuAnLBTFALgPrQCWAtrgM4ECG5ADgBSwAMsAlAL6wCCwsAMYB7ADYAoANxA)
