### ISSUE TITLE
Create index with 'DESC' specification is accepted, but not added to the object model

### ISSUE THREAD

**Issue by olavloite** [JSQLParser/JSqlParser#650]
### Actual Behavior
`create index myindex on mytable (mycol desc)` is accepted, but the `desc` is not added to the list of index specifications.

### Expected Behavior
The asc/desc specification should be added to the list of index specifications in the parsed object model.

### Steps to Reproduce the Problem

  1. Parse `create index myindex on mytable (mycol desc)`
  1. Verify that `CreateIndex#getIndex()#getIndexSpec()` returns null

### Specifications

  - Version: 1.2
  - Platform: Ubuntu 18.04
  - Subsystem:

**Comment by wumpz** [comment]
already solved
