### ISSUE TITLE
full text search isn't supported

### ISSUE THREAD

**Issue by tomershay** [JSQLParser/JSqlParser#654]
MySQL's full text search syntax (match ... against) isn't supported.
https://dev.mysql.com/doc/refman/8.0/en/fulltext-search.html

**Comment by manticore-projects** [comment]
Greetings.

This issue is left open for a long time and I think, in the meantime support for `FullTextSearch` has been arrived. Please also see PR #1278 which enhances it.

Would you like to verify please and close this issue, when successful. Thank you in advance.
