### ISSUE TITLE
LikeExpression.setNot() does not set not to true

### ISSUE THREAD

**Issue by xsgao-github** [JSQLParser/JSqlParser#660]
### Actual Behavior
LikeExpresion like = new LikeExpression();
like.setNot();
System.out.println(like.isNot());

### Expected Behavior
should print out true;

### Steps to Reproduce the Problem
  1. execute code snippet above.
  2. print out false.

Suggestion: LikeExpression defines its own not variable which shadown BinaryExpresion's not variable. But setNot() method (in parent) should still work along with isNot() (in child class), so you should override setNot() in LikeExpression:

	@Override
	public void setNot() {
		not = true;
	}

### Specifications

  - Version: 1.3
  - Platform:
  - Subsystem:

**Comment by wumpz** [comment]
fixed with the last commit
