### ISSUE TITLE
create table statement can not support "partition" sqlkeywords

### ISSUE THREAD

**Issue by google-tmac** [JSQLParser/JSqlParser#661]
### Actual Behavior
Caused by: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "partition" "PARTITION"
    at line 1, column 1372.

Was expecting one of:
    "("
    "+"
    "-"
    ";"
    "="
    "CASCADE"
    "CHECK"
    "COMMIT"
    "CONSTRAINT"
    "DELETE"
    "EXCLUDE"
    "FOREIGN"
    "KEY"
    "NOT"
    "NULL"
    "ON"
    "PRIMARY"
    "REFERENCES"
    "ROWS"
    "TABLESPACE"
    "TEMP"
    "TEMPORARY"
    "UNIQUE"
    "UNSIGNED"
    "UPDATE"
    "USING"
    "WHERE"
    "WITH"
    <EOF>
    <K_TIME_KEY_EXPR>
    <S_CHAR_LITERAL>
    <S_DOUBLE>
    <S_IDENTIFIER>
    <S_LONG>
    <S_QUOTED_IDENTIFIER>

### Expected Behavior
executing the statement such as `CreateTable create = (CreateTable) CCJSqlParserUtil.parse(sql);` successfully;
the parameter "sql" is a create table statement with "partition",for example:
`create table T_TEST_PARTITION
(
   PART_COLUMN              VARCHAR2(32)         not null,
   OTHER_COLS               VARCHAR2(10)         not null
)
tablespace TBS_DATA_01
partition by hash (PART_COLUMN)
partitions 4 store in (TBS_DATA_01) compress;`

### Steps to Reproduce the Problem

  1.Defining variable `sql` like this：
`String sql = " create table T_TEST_PARTITION "+
" ("+
"    PART_COLUMN              VARCHAR2(32)         not null,"+
"    OTHER_COLS               VARCHAR2(10)         not null"+
" )"+
" tablespace TBS_DATA_01"+
" partition by hash (PART_COLUMN)"+
" partitions 4 store in (TBS_DATA_01) compress";`
  2.execute statement
`CreateTable create = (CreateTable) CCJSqlParserUtil.parse(sql);`

### Specifications

  - Version: com.github.jsqlparser:jsqlparser:1.2 jdk1.8
  - Platform:windows eclipse
  - Subsystem:

**Comment by wumpz** [comment]
The snapshot is not yet compiled at sonatype. 
thx for using JsqlParser
