### ISSUE TITLE
Cannot parse queries containing MySql charset literals

### ISSUE THREAD

**Issue by gooh** [JSQLParser/JSqlParser#664]
### Actual Behavior

The query cannot be parsed.

### Expected Behavior

The query can be parsed

### Steps to Reproduce the Problem

Try parsing `SELECT foo FROM bar WHERE (foo.something NOT IN (_utf8'984711'))`
Then remove the prefix _utf8 and try again.

### Specifications

relevant docs: https://dev.mysql.com/doc/refman/8.0/en/charset-literal.html

**Comment by CodingFabian** [comment]
this looks surprisingly like #659

**Comment by wumpz** [comment]
#659 does add a fixed set of one or two character prefixes.

**Comment by sivaraam** [comment]
This seems to be fixed in fe28e88d948dc7e1873d02499fe8256c0c310880.

**Comment by wumpz** [comment]
Indeed it is fixed. I forgot to close it.
