### ISSUE TITLE
how to get selected columns name of a select sql

### ISSUE THREAD

**Issue by Jedda1314Jessie** [JSQLParser/JSqlParser#668]
i already have getted table names by TablesNamesFinder like this:

String sql = "select field1,field2 from  (select field1,field2 from table_a left outer join table_b on table_a.aa=table_b.bb)";
        Statement statement = CCJSqlParserUtil.parse(sql);
        Select selectStatement = (Select) statement;
        TablesNamesFinder tablesNamesFinder = new TablesNamesFinder();
        List<String> tableList = tablesNamesFinder.getTableList(selectStatement);
        for(String tableName : tableList){
            System.out.println(tableName);
        }

but I don't know how to get elected columns name of a select sql,please help

**Comment by wumpz** [comment]
Just use a deparser and override visit Column method to get all recognized columns.

**Comment by wumpz** [comment]
@gunaskr You can, but selectItems could contain complex expressions. Those have to be deparsed as well.

**Comment by gunaskr** [comment]
> @gunaskr You can, but selectItems could contain complex expressions. Those have to be deparsed as well.

You're right. But i specifically suggested the answer to find the selectItems. If you need to refine from their you could use SelectItemVisitor and ExpressionVisitor and pass any item of interest from the selectItems( given in my previous answer).

**Comment by wumpz** [comment]
You could look at https://stackoverflow.com/questions/40908062/parsing-table-and-column-names-from-sql-hql-java?rq=1. 

Maybe I should extend the wiki examples here.

**Comment by sivaraam** [comment]
Hi,

For the following select query:

```
SELECT F.* FROM FIRES F, (SELECT MAX(ESTLOSS) MAXLOSS FROM FIRES) M WHERE F.ESTLOSS = M.MAXLOSS;
```

I am able to get either of the following output by using various methods to retrueve the column names

```
F.*
```

(OR)

```
ESTLOSS
F.ESTLOSS
M.MAXLOSS
```

What is the method I should be using to get the following as the output?

```
ESTLOSS
```

Any help would be useful. Thanks in advance.

**Comment by wumpz** [comment]
Are there any problems applying the suggested stackoverflow solution?

**Comment by sivaraam** [comment]
Both the techniques mentioned in the StackOverflow solution give me the following output:

```
ESTLOSS
F.ESTLOSS
M.MAXLOSS
```

But I was wondering if there is a possibility to get the following output i.e., the `F.*` should be expanded to columns corresponding to the table `F` and the column names found in criteria should _not_ be included?

```
ESTLOSS
```

**Comment by wumpz** [comment]
Ok. Now I understand your problem. 

First of all JSqlParser is a parser and therefore not able to expand the definition of `F` because this is only known to your database schema. You need some kind of postprocessing JSqlParsers output.

The tablenames finder method visits all nodes within your parsed object tree. You need to first build a visitor that detects all SelectItems and for each SelectItem you should run the columns method above. The other possibility would be to switch of column name detection of TableNamesFinder if it is entering a where statement. 

The `F.*` expression is not matched as `Column `but as `AllTableColumns`.

**Comment by sivaraam** [comment]
Ok. Thanks for the clarification!

**Comment by wumpz** [comment]
@sivaraam So can we close this issue?

**Comment by sivaraam** [comment]
Yeah, I think we can given that there is only so much you could achieve with a parser alone 😉
