### ISSUE TITLE
Ampersand prefixed parameter causes JSQLParserException

### ISSUE THREAD

**Issue by mgierw** [JSQLParser/JSqlParser#669]
### Actual Behavior

```
Caused by: net.sf.jsqlparser.JSQLParserException
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:55)
	... 4 more
Caused by: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "=" "="
    at line 2, column 46.
```

### Expected Behavior
I think it should be recognized as regular parameter.

### Steps to Reproduce the Problem

```
CCJSqlParserUtil.parse("SELECT * from table t where t.id = &table_id");
```

### Specifications

  - Version: 1.2
  - Platform: Windows 10, Java 1.8
  - Subsystem: ?

**Comment by mgierw** [comment]
It is possible in Oracle. If you use SQL developer, then you will be promoted to provide value for such prefixed parameter.

**Comment by wumpz** [comment]
Aha.I see. So it is not part of SQL itself but will be replaced?

**Comment by mgierw** [comment]
Yeah, you're right. Closing...
