### ISSUE TITLE
Not support WHERE clauses in a MERGE UPDATE 

### ISSUE THREAD

**Issue by yiliachenh** [JSQLParser/JSqlParser#676]
### Steps to Reproduce the Problem

merge INTO M_KC21 USING
(SELECT AAA, BBB FROM I_KC21 WHERE I_KC21.aaa = 'li_kun'
) TEMP ON (TEMP.AAA = M_KC21.AAA)
WHEN MATCHED THEN
  UPDATE SET M_KC21.BBB = 6 ### WHERE enterprise_id IN (0, 1) 
WHEN NOT MATCHED THEN
  INSERT VALUES
    (TEMP.AAA,TEMP.BBB
    )

Do not support WHERE clauses in a MERGE UPDATE 

### Specifications

  - Version:
  - Platform:
  - Subsystem:

**Comment by wumpz** [comment]
In fact a where clause is supported. The problem here is the missing columns list in the insert part. I am already on it.
