### ISSUE TITLE
SQL parse Exception with where clause param starts with number

### ISSUE THREAD

**Issue by wangxucumt** [JSQLParser/JSqlParser#678]
### Steps to Reproduce the Problem

  1.If my sql like this:"select SQL_NONE_VALUE,sum(pv) as pv from tmp_table where str_to_date(date,'%Y%m%d')>=SQL_NONE_VALUE and str_to_date(date,'%Y%m%d')<=SQL_NONE_VALUE and 4g_version in (SQL_NONE_VALUE) group by SQL_NONE_VALUE;"
     SQL parser failed
     Exception:
     net.sf.jsqlparser.JSQLParserException
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:55)
	at xp.net.App.main(App.java:15)
Caused by: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "4" <S_LONG>
    at line 1, column 69.
    The reason is the where clause param starts with number 4 
  1.
  1.

### Specifications

  - Version:1.2
  - Platform:windows
  - Subsystem:

**Comment by wumpz** [comment]
Identifiers must not start with a digit. I know some databases allows this, but what about 1e10, which is a valid postgres number. JSqlParser will not support this. As a workaround you could double quote it.

**Comment by Labi0** [comment]
Mysql allows this and we are not allowed to modify the sql specified by the client. I would suggest some sort of configuration support to specify whether a particular semantic is permitted or not. One size cannot fit all :).

**Comment by wumpz** [comment]
You are right. One size can indeed not fit all. As of the architecture of JSqlParser and JavaCC it is not possible to allow or disallow this kind of tokenizer option. It would be a new parser with a new grammer. You have to change double parsing, ...
