### ISSUE TITLE
wrong parser for invoke CCJSqlParserUtil.parseStatements("somesqls")

### ISSUE THREAD

**Issue by softommy** [JSQLParser/JSqlParser#679]
code: 
    Statements statements = CCJSqlParserUtil.parseStatements("use chat;\nalter table tb_session_status add index idx_user_id(user_id);\n");
result: 
    USE chat;
    ALTER TABLE tb_session_status ADD COLUMN index idx_user_id (user_id);

 - Version: 1.2.0

**Comment by wumpz** [comment]
What do you mean by "wrong parser for invoke"?

**Comment by wumpz** [comment]
How do you get the result?  Normally it should be a Statements instance that holds a list of statements.

**Comment by softommy** [comment]
Statements statements = CCJSqlParserUtil.parseStatements("use chat;\nalter table tb_session_status add index idx_user_id(user_id);\n");
for (Statement stmt : statements.getStatements()) {
      System.out.println(stmt.toString());
}

output:
USE chat
ALTER TABLE tb_session_status ADD COLUMN index idx_user_id (user_id) // wrong sql

you can try it yourself

**Comment by softommy** [comment]
I need to list the statements based on the database name. My complete code is as follows, but I get the wrong result when parsing "use chat;\nalter table tb_session_status add index idx_user_id(user_id);\n"
`public static Map<String, List<String>> parserSQL(String sqls) {
        Map<String, List<String>> result = new HashMap<>();
        try {
            Statements statements = CCJSqlParserUtil.parseStatements(sqls);
            List<String> dbSqlList = new ArrayList<>();
            for (Statement statement : statements.getStatements()) {
                if (statement instanceof UseStatement) {
                    result.put(((UseStatement) statement).getName(), dbSqlList = new ArrayList<>());
                } else {
                    dbSqlList.add(statement.toString() + ";");
                }
            }
        } catch (JSQLParserException e) {
            logger.error(new SqlParserException(sqls));
        }
        return result;
    }`

**Comment by softommy** [comment]
Why didn't you understand what I meant from the beginning?
(^V^)

**Comment by wumpz** [comment]
Because you wrote parser and at the first look your sqls and the output looked fine and equal. You should have pointed to the difference. Then you mentioned you need an array and gave a string with linefeeds as a wrong example. So to which difference should I react? I did on the first I saw.

**Comment by wumpz** [comment]
Because I did not see the difference which is important for you.

**Comment by softommy** [comment]
> ```
> Statements statements = CCJSqlParserUtil.parseStatements("use chat;\nalter table tb_session_status add index idx_user_id(user_id);\n");
> for (Statement stmt : statements.getStatements()) {
>       System.out.println(stmt.toString());
> }
> ```
> output wrong result:
> 
> ```
> USE chat
> ALTER TABLE tb_session_status ADD COLUMN index idx_user_id (user_id) // this is wrong statement
> ```
> you can try it yourself

Is this issue still not confirmed?

**Comment by wumpz** [comment]
Yes, but I have no time at the moment. PRS are welcome.

**Comment by wumpz** [comment]
Closed by pr
