### ISSUE TITLE
Oracle RETURNING INTO Clause problem

### ISSUE THREAD

**Issue by averemee-si** [JSQLParser/JSqlParser#686]
### Actual Behavior
While parsing:
**UPDATE employees SET salary = salary * 1.1 WHERE employee_id = emp_id
      RETURNING last_name, salary INTO emp_info;**
get
Caused by: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "INTO" "INTO"
    at line 2, column 35.

Was expecting one of:

    "&"
    ","
    "."
    "::"
    ";"
    "<<"
    ">>"
    "ACTION"
    "ANY"
    "AS"
    "CASCADE"
    "CAST"
    "COLUMN"
    "COMMIT"
    "DO"
    "ENABLE"
    "END"
    "EXTRACT"
    "FIRST"
    "FOLLOWING"
    "INDEX"
    "INSERT"
    "KEY"
    "LAST"
    "MATERIALIZED"
    "NO"
    "NULLS"
    "OPEN"
    "OVER"
    "PARTITION"
    "PERCENT"
    "PRECISION"
    "PRIMARY"
    "PRIOR"
    "RANGE"
    "REPLACE"
    "ROW"
    "ROWS"
    "SEPARATOR"
    "SIBLINGS"
    "TABLE"
    "TEMP"
    "TEMPORARY"
    "TRUNCATE"
    "UNSIGNED"
    "VALUE"
    "VALUES"
    "XML"
    "^"
    "|"
    <EOF>
    <K_DATETIMELITERAL>
    <S_CHAR_LITERAL>
    <S_IDENTIFIER>
    <S_QUOTED_IDENTIFIER>

	at net.sf.jsqlparser.parser.CCJSqlParser.generateParseException(CCJSqlParser.java:18047)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_consume_token(CCJSqlParser.java:17900)
	at net.sf.jsqlparser.parser.CCJSqlParser.Statement(CCJSqlParser.java:91)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:53)
	... 2 more
Caused by:
net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "INTO" "INTO"
    at line 2, column 35.
.....

### Expected Behavior
Support of Oracle RETURNING INTO clause

### Steps to Reproduce the Problem
Try to parse following valid SQL
**UPDATE employees SET salary = salary * 1.1 WHERE employee_id = emp_id
      RETURNING last_name, salary INTO emp_info;**
with JSQLParser

### Specifications

  - Version:
1.2
  - Platform:
Generic
  - Subsystem:
jsqlparser

**Comment by averemee-si** [comment]
The same behaviour with v1.3.
Will try to propose changes to JSqlParserCC.jjt for block
   [ <K_RETURNING> (
              "*" { update.setReturningAllColumns(true); }
              | returning=ListExpressionItem()
              )
       ]

**Comment by manticore-projects** [comment]
Still relevant with JSQLParser 4.6-Snapshot:
```sql
-- failed to format start
UPDATE employees 
SET salary = salary * 1.1 
WHERE employee_id = emp_id
RETURNING last_name, salary INTO emp_info;
-- failed to format end
```
