### ISSUE TITLE
Does not support DB2 System naming convention

### ISSUE THREAD

**Issue by thebiguno** [JSQLParser/JSqlParser#687]
### Actual Behavior
Parser fails to parse statements using system naming convention.  See https://www.ibm.com/support/knowledgecenter/en/ssw_ibm_i_72/sqlp/rbafyterms.htm for details on system vs. sql naming conventions.

While this is obviously not standard SQL syntax, JSQLParser does support other special DB syntax, and it would be great if this DB2 syntax could be supported as well.

I would be happy to implement this if you could point me in the right direction.

### Expected Behavior
This statement should parse correctly.

### Steps to Reproduce the Problem

  1. Try running the parse statement:
CCJSqlParserUtil.parse("select 'foo' from sysibm/sysdummy1");
  1. Parse fails with error Encountered unexpected token: "/"
  1. Try running the parse statement to verify that SQL naming works:
CCJSqlParserUtil.parse("select 'foo' from sysibm.sysdummy1");

### Specifications

  - Version: JSqlParser 1.3
  - Platform: Java 1.7 / OSX
  - Subsystem:

**Comment by wumpz** [comment]
That is right. This would collide with numeric expressions (a/b). A solution would be to quote this object names. Since JSqlParser is a multi database sql dialect parser, it is difficult to include all specifics of all databases. I think this will not be supported.

**Comment by wumpz** [comment]
By the way I am not sure if this is possible without any deeper changes to the grammar. If you want to try, you should first provide a token for each of your special names and include thes in RelObjectNames() - production and hope the best.

**Comment by thebiguno** [comment]
Understood.  I agree that it is a stupid standard; unfortunately I am working with a large set of legacy SQL queries which were previously parsed with a proprietary tool.  We were hoping to move to the (much better) JSQLParser, but are unable / unwilling to manually modify thousands of queries.  I'll do some analysis and see if I can work around the issue in some other way.

Thanks for the help!

**Comment by thebiguno** [comment]
Thanks!

**Comment by thebiguno** [comment]
I have written some test cases to validate all of the existing SQL.  83% of it passes unmodified.  Of the remaining 17%, it looks like the majority of the issues are either due to DB2 date math (already reported by someone else in issue https://github.com/JSQLParser/JSqlParser/issues/649), and problems with VALUES clauses (which appears to be the same or similar issue as reported in https://github.com/JSQLParser/JSqlParser/issues/561).

Would you prefer that I update these tickets with more details and sample code?

**Comment by wumpz** [comment]
That would be great. Thanks
