### ISSUE TITLE
Parse error if there is a udf in statement

### ISSUE THREAD

**Issue by Mvpanswer7** [JSQLParser/JSqlParser#689]
### 
Get `Caused by: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "current_date" <K_TIME_KEY_EXPR> at line 1, column xx  
`
when I parse `select * from table where date = sub_date(current_date('yyyyMMdd'),'1','yyyyMMdd');`

### code 
  `val select = CCJSqlParserUtil.parse(sql).asInstanceOf[Select]`

**Comment by manticore-projects** [comment]
Parses fine with JSQLParser 4.6:
```sql
SELECT *
FROM table
WHERE date = Sub_Date( Current_Date( 'yyyyMMdd' ), '1', 'yyyyMMdd' )
;
```

Closed.
