### ISSUE TITLE
Error when using empty string in statement

### ISSUE THREAD

**Issue by Mvpanswer7** [JSQLParser/JSqlParser#693]
Error `net.sf.jsqlparser.parser.TokenMgrException: Lexical error at line 1, column 34.  Encountered: "\"" (34), after : "\""` will thrown when JSqlParser handle statement like : `select * from table where name <> "" ; `   where `name` is not empty string.
But it will work if I change `""` to `''`

**Comment by wumpz** [comment]
That is a decision by design. With double quotes, you are addressing in general a DBMS object name, while using single quotes you are defining a string literal.
