### ISSUE TITLE
lateral view explode support？

### ISSUE THREAD

**Issue by Mvpanswer7** [JSQLParser/JSqlParser#704]
Error throws `unexpected token: lateral at line 1` when I use a select statement with `lateral view explode`

**Comment by Mvpanswer7** [comment]
@wumpz

**Comment by Mvpanswer7** [comment]
My sql `select  * from ( select * from users where dt>='20180801' and dt<='20180916' and id>100 a lateral view explode(info) as adid`

**Comment by manticore-projects** [comment]
Duplicate #239
