### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by dvayanu** [JSQLParser/JSqlParser#713]
### Question

I am sorry to open a question in this matter, but I didn't see any other contact options. What I want to achieve is to create a prepared-like statement out of the real sql statement for monitoring purpose
For example I want for an input:

```
SELECT id,name,age from ACCOUNT where id = 'ert' 
SELECT id,name,age from ACCOUNT where id = '?' 
```
or 
```
SELECT id,name,age from ACCOUNT where id = 234
SELECT id,name,age from ACCOUNT where id = ? 
```

Is there already some easy way to achieve it, or do I have to traverse the whole Statement and Replace Expressions when I find them?

**Comment by wumpz** [comment]
So you want to input the first sql and want to produce for each value a question mark to get a prepared statement?

Look at https://github.com/JSQLParser/JSqlParser/wiki/Examples-of-SQL-building#replacing-string-values. This and the next topic should give you an idea of a way to achieve it.

**Comment by dvayanu** [comment]
Thank you this is perfect.
