### ISSUE TITLE
Parse error on MySql Boolean Literals

### ISSUE THREAD

**Issue by qbrent** [JSQLParser/JSqlParser#716]
Hi,

Running parse against:
CCJSqlParserUtil.parse("select * from table where false or clm1 = 3")

Is hitting the below exception. This sql does run in mySql; although I'm not sure if its some custom mySql syntax or not.

```
[error] (run-main-13) net.sf.jsqlparser.JSQLParserException
[error] net.sf.jsqlparser.JSQLParserException
[error] 	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:51)
[error] 	at Todo$.main(Todo.scala:15)
[error] 	at Todo.main(Todo.scala)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error] 	at java.lang.reflect.Method.invoke(Method.java:498)
[error] Caused by: net.sf.jsqlparser.parser.ParseException: Encountered " "TABLE" "table "" at line 2, column 16.
[error] Was expecting one of:
[error]     "DO" ...
[error]     "XML" ...
[error]     "VALUE" ...
[error]     "CAST" ...
...
```
Replacing the `false` with `1 = 0` parses successfully JSQLParser.

"select * from tbl where 1 = 0 or clm1 = 3"

Would it be possible so support, I believe it would be Boolean Literals? (https://dev.mysql.com/doc/refman/5.7/en/boolean-literals.html)

**Comment by wumpz** [comment]
I added a test and the following statement is parsed successfully 

    SELECT * FROM tbl WHERE true OR clm1 = 3

The exception of your request indicates, that the tablename **table** isn't allowed. It is a keyword and not allowed in this position. In your second sql you replaced it by **tbl**. 

However I don't know since which version this works. I used the actual snapshot.

**Comment by qbrent** [comment]
Whoops; yea I'm hitting the error when I replace it to tbl on 0.9; so will try against snapshot

Thanks

**Comment by qbrent** [comment]
Well its working in 1.3, thanks
