### ISSUE TITLE
mysql GROUP_CONCAT syntax not supported

### ISSUE THREAD

**Issue by mtruchard** [JSQLParser/JSqlParser#72]
I use mySql and so far jsqlparser has done an awesome job parsing fairly complex syntax, but there is one issue I ran into.  The full mysql GROUP_CONCAT syntax will not parse. The function expression just doesn't support all the parameter options:

GROUP_CONCAT([DISTINCT] expr [,expr ...]
             [ORDER BY {unsigned_integer | col_name | expr}
                 [ASC | DESC] [,col_name ...]]
             [SEPARATOR str_val])

DISTINCT works, but ORDER BY, and SEPARATOR do not.

http://dev.mysql.com/doc/refman/5.0/en/group-by-functions.html#function_group-concat

**Comment by fireflyk** [comment]
I also met the problem. Is there any solution?

**Comment by mtruchard** [comment]
No, we did not find a solution. Right now we are avoiding use of ORDER BY and SEPARATOR in the GROUP_CONCAT clause.

**Comment by wumpz** [comment]
You could provide a pull request. You know JSqlParser is somewhat feature request driven. I select the issues that seem to be the most needed.  But saying that my time (spare time ) is limited. So motivate me. 😉
