### ISSUE TITLE
postgreSQL Array Operators && cause problem

### ISSUE THREAD

**Issue by zsedcbm** [JSQLParser/JSqlParser#723]
### Actual Behavior
While parsing:
```
select count(0) from (select id,name from t_promotion_base
         where status != -1 and customer_base_ids && ?) tmp_count
```
get
Caused by: net.sf.jsqlparser.parser.ParseException: Encountered " "&" "& "" at line 7, column 40.

Was expecting one of:
```
"AND" ...
    "FOR" ...
    "UNION" ...
    "GROUP" ...
    "ORDER" ...
    "HAVING" ...
    "INTERSECT" ...
    "EXCEPT" ...
    "MINUS" ...
    "START" ...
    "CONNECT" ...
    ")" ...
    "ORDER" ...
    "ORDER" ...
```
### Expected Behavior
https://www.postgresql.org/docs/9.6/functions-array.html
support && (overlap (have elements in common))
### Steps to Reproduce the Problem

Try to parse following valid SQL
```
select count(0) from (select id,name from t_promotion_base
         where status != -1 and customer_base_ids && ?) tmp_count
```
with JSQLParser

customer_base_ids  field type is array, ? parameter type is Long[]

### Specifications

  - Version: 1.1
  - Platform: windows
  - Subsystem:

**Comment by wumpz** [comment]
JSqlParser 4.0 parses this.
