### ISSUE TITLE
'not like' where clause not correct

### ISSUE THREAD

**Issue by stjlcc** [JSQLParser/JSqlParser#726]
### Actual Behavior
Statement parsed = CCJSqlParserUtil.parse(new StringReader("SELECT * FROM tab1 WHERE a NOT LIKE 'test'"));
System.out.println(parsed.toString());

SELECT * FROM tab1 WHERE NOT a NOT LIKE 'test'
Note:There are TWO "NOT" in where clause
### Expected Behavior
SELECT * FROM tab1 WHERE a NOT LIKE 'test'
### Specifications

  - Version:1.3
  - Platform:jdk8
  - Subsystem:

**Comment by myrider** [comment]
I also met this situation.
I hope to solve this bug quickly. Thank you very much.

**Comment by wumpz** [comment]
This is already solved within SNAPSHOT. I am not sure, if I deployed it already.

**Comment by wumpz** [comment]
https://github.com/JSQLParser/JSqlParser/issues/694

**Comment by wumpz** [comment]
First this bug should be solved within the actual deployed SNAPSHOT. To be honest at the moment I did not plan to make a release. Maybe I should reconsider this.

I am thinking about the next major release with removed bracket quotation to be able to support array support.

**Comment by wumpz** [comment]
#731

**Comment by wumpz** [comment]
The release is done. It should take a while to get JSqlParser published to maven central.

**Comment by surli** [comment]
Great :+1: thanks for your reactivity!
