### ISSUE TITLE
failed to parse show columns query

### ISSUE THREAD

**Issue by oshai** [JSQLParser/JSqlParser#727]
### Actual Behavior
Caused by: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "SHOW" <S_IDENTIFIER>
    at line 1, column 1.

Was expecting one of:

### Expected Behavior

parse the following statement: "SHOW COLUMNS FROM table"

(this is mysql query)
### Steps to Reproduce the Problem

new CCJSqlParserUtil.parse("SHOW COLUMNS FROM table")

### Specifications

  - Version:1.3
  - Platform:unix
  - Subsystem:mac

**Comment by wumpz** [comment]
**Show** seems not to a a sql command but some specialized worksheet command. Right?  JSqlParser does not support it.

**Comment by oshai** [comment]
@wumpz - this is part of mysql syntax: https://dev.mysql.com/doc/refman/8.0/en/show.html

**Comment by wumpz** [comment]
@oshai obviously you are right. Nevertheless there are no plans to support it right now. Do you want to improve JSqlParser? Pull requests are wellcome.

**Comment by oshai** [comment]
Sure, can you give me a pointer where to start looking?

**Comment by wumpz** [comment]
Something to start would be production **SingleStatement**. **Set** or **Use** are some simple statements to learn from. In the same way I would implement a **Show** statement. However I the spec seems to be quite big. You should keep it simple for a start and stick to only your usecases.

**Comment by oshai** [comment]
one more question: should I do changes in JSqlParserCC.jjt or in java classes or both?

**Comment by oshai** [comment]
I managed to add it see this PR: https://github.com/JSQLParser/JSqlParser/pull/728
For some reason there is a test on oracle db failed, don't know if this is related.

**Comment by oshai** [comment]
@wumpz - Thanks for merging the PR. When do you think it will be released?

**Comment by wumpz** [comment]
The merge resulted in some test failures. I need a bit to clean it up.

**Comment by wumpz** [comment]
resolved
