### ISSUE TITLE
Initializing user variables and referencing them

### ISSUE THREAD

**Issue by GrubbyHalo** [JSQLParser/JSqlParser#732]
`SET @varname=1;`
gives this exception
`net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "@" "@"`
Also referencing a variable within a statement. e.g.
`SELECT @varname := @varname +1 as counter;`
produces the following exception
`net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: ":" ":"`

### Specifications

  - Version: 1.3

**Comment by wumpz** [comment]
This construct is not supported.
