### ISSUE TITLE
What does "dual licensing" related to JSqlParser in practice mean?

### ISSUE THREAD

**Issue by phlox** [JSQLParser/JSqlParser#735]
I know there were similar discussions here about this, but I read them and I didn't find an answer.

My company develops and sells a software product, and JSqlParser does a great job in one area. Now we got a new customer and they tell us that they accept 3rd party libraries in our product only when they are licensed under Apache V2, but not when they are licensed under LGPL. I'm not a lawyer (as probably most readers here), so I'm a bit confused what "dual licensing" actually means. 

Best case: Does it mean that I can apply one of the two licenses, i.e. the one I prefer? see http://www.dpscomputing.com/blog/2012/06/27/what-dual-licensing-means-in-terms-of-computer-software/
Worst case: Or does it mean that both licenses apply at the same time, i.e. one could pick the most restrictive points from each? see https://en.wikipedia.org/wiki/Multi-licensing

Which case applies?

Thanks in advance.

**Comment by wumpz** [comment]
In the last days the licensing was a field of change. 

1. The dual licence text was changed to reflect, that there is a "or" betewen both license and not an "and"
2. The header of each sourcecode file does now not anymore contain the LGPL license but a text refereing to both licenses

**Comment by phlox** [comment]
sounds great, thanks a lot!
