### ISSUE TITLE
why less some java class file when i clone from github to idea,like 'SimpleNode'、'CCJSqlParser'

### ISSUE THREAD

**Issue by PG123GG** [JSQLParser/JSqlParser#736]
### Steps to Reproduce the Problem

  1.
  1.
  1.

### Specifications

  - Version:
  - Platform:
  - Subsystem:

**Comment by wumpz** [comment]
I did not understand your issue?

**Comment by PG123GG** [comment]
> I did not understand your issue?

When I cloned from git, I was missing some Java class errors in the idea.

**Comment by wumpz** [comment]
You need to use maven to build this project. Some java sources are generated by javacc therefore deriven from the grammar file. All sources to build jsqlparser successfully are in github. By the way travis build is successful as well.

**Comment by wumpz** [comment]
So have you any more questions or can we close this issue?
