### ISSUE TITLE
not support sqlserver with(nolock)

### ISSUE THREAD

**Issue by yccool** [JSQLParser/JSqlParser#749]
### Actual Behavior
not support the sqlserver with(Nolock)
### Expected Behavior
hope suppert with(nolock) to sqlserver
### Steps to Reproduce the Problem

  ex:    select * from table1  A with(Nolock) Inner Join table2 B with(nolock) on a.id=b.aid
  

### Specifications

  - Version:
  - Platform:
  - Subsystem:

**Comment by AnEmortalKid** [comment]
I think this was fixed by https://github.com/JSQLParser/JSqlParser/commit/9ce74e234e09525f6af557095cf938c8bb456708

**Comment by wumpz** [comment]
Correct.
