### ISSUE TITLE
do not support mysql json grammar select

### ISSUE THREAD

**Issue by JiaMingLiu93** [JSQLParser/JSqlParser#758]
### Actual Behavior
such as：select from table where value->$.type = ''
### Expected Behavior
select relative result
### Steps to Reproduce the Problem

  1. mysql 5.7.8 that support json function
  2. do select according to Actual Behavior

### Specifications

  - Version: 0.9
  - Platform: Mac
  - Subsystem:

**Comment by manticore-projects** [comment]
This should just have been resolved. If not, please re-open and add a specific SQL statement to reproduce.
