### ISSUE TITLE
Mysql DDL Encountered unexpected token: "COMMENT" "COMMENT"

### ISSUE THREAD

**Issue by IceMimosa** [JSQLParser/JSqlParser#759]
Error when i execute `CCJSqlParserUtil.parseStatements(sqls).getStatements()` using JSqlParser 1.4.
But error is gone when JSqlParser version is  <=1.3

### Steps to Reproduce the Problem
sql is

```sql
CREATE TABLE IF NOT EXISTS `eai_applications`(
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '编号',
  `name` varchar(64) NOT NULL COMMENT '应用名称',
  `logo` varchar(128) DEFAULT NULL COMMENT '应用logo',
  `description` varchar(128) DEFAULT NULL COMMENT '应用描述',
  `type` int(11) NOT NULL COMMENT '类型',
  `status` tinyint(2) NOT NULL COMMENT '状态',
  `creator_id` bigint(20) NOT NULL COMMENT '应用ID',
  `created_at` datetime NOT NULL COMMENT '创建时间',
  `updated_at` datetime NOT NULL COMMENT '更新时间',
  PRIMARY KEY (`id`)
) COMMENT='应用表';
```

### Specifications

  - Version: 1.4
  - Platform: Mac
  - Subsystem:

**Comment by ainilili** [comment]
plz Improve the version to 2.1 xD

**Comment by wumpz** [comment]
I will look into it.

**Comment by wumpz** [comment]
This one seems to be already fixed. Unfortunately I cannot say which version. You should try the latest release.
