### ISSUE TITLE
How to escape the SQL properly

### ISSUE THREAD

**Issue by ckharide** [JSQLParser/JSqlParser#761]
### Steps to Reproduce the Problem

  1. 	String sql = "select abcd from emp where emp.id = 10 and value = 20 or val2 like 'xyz' or '10'='1'";

  1.         Run this with the following program 
              StringBuilder buffer = new StringBuilder();
               Select select = (Select) CCJSqlParserUtil.parse(sql);
	        ExpressionDeParser expr = new ReplaceColumnAndLongValues();

	        SelectDeParser selectDeparser = new SelectDeParser(expr, buffer);
	        expr.setSelectVisitor(selectDeparser);
	        expr.setBuffer(buffer);
	        StatementDeParser stmtDeparser = new StatementDeParser(expr, selectDeparser, buffer);
	        stmt.accept(stmtDeparser);
	        System.out.println(stmtDeparser.getBuffer().toString());

  it produces output SELECT abcd FROM emp WHERE emp.id = ? AND value = ? OR val2 LIKE ? OR ? = ?  

which is prone to SQL injection as all the five ? can be substituted  is there way i can change it to so that i can only 3 placeholders for substitution something like .

SELECT abcd FROM emp WHERE emp.id = ? AND value = ? OR val2 LIKE ?

I want to construct a prepared statement out of a resolved sql and then sanitize it to send it to the downstream. 

### Specifications

  - Version:
  - Platform:
  - Subsystem:

**Comment by AnEmortalKid** [comment]
Does the statement deparser contain the parameter values in a different field/method ?

**Comment by wumpz** [comment]
That is normal behaviour for `ReplaceColumnAndLongValues`. One way to go further is to overwrite 

`visitBinaryExpression`

There you have to check, if left and right expression will be replaced by a `?` and then skip this whole thing within the output. It would be simpler to replace it with` 1 = 1`.

**Comment by manticore-projects** [comment]
Closing when its not an error and no further questions have been asked since.
