### ISSUE TITLE
Problem with long qualified name

### ISSUE THREAD

**Issue by trishLEX** [JSQLParser/JSqlParser#763]
### Actual Behavior
When I try to parse statement: "SELECT mongodb.test.test.intField, postgres.test.test.intField, postgres.test.test.datefield FROM mongodb.test.test JOIN postgres.postgres.test.test ON mongodb.test.test.intField = postgres.test.test.intField WHERE mongodb.test.test.intField = 123"

(I write some alternative to Apache Drill or PrestoDB, so I wrote sql query to mongo, so I have qualified name with 4 parts)

I got exception:

net.sf.jsqlparser.JSQLParserException
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:55)
	at ru.bmstu.sqlfornosql.adapters.sql.SqlUtils.fillSqlMeta(SqlUtils.java:252)
	... 27 more
Caused by: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "." "."
    at line 1, column 65.

Was expecting one of:

    ","
    ";"
    "CONNECT"
    "CROSS"
    "EXCEPT"
    "FOR"
    "FULL"
    "GROUP"
    "HAVING"
    "INNER"
    "INTERSECT"
    "JOIN"
    "LEFT"
    "MINUS"
    "NATURAL"
    "ORDER"
    "PIVOT"
    "RIGHT"
    "START"
    "UNION"
    "WHERE"
    <EOF>

	at net.sf.jsqlparser.parser.CCJSqlParser.generateParseException(CCJSqlParser.java:19398)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_consume_token(CCJSqlParser.java:19248)
	at net.sf.jsqlparser.parser.CCJSqlParser.Statement(CCJSqlParser.java:93)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:53)
	... 28 more

Without WHERE clause that statement was parsed correctly, also it was parsed, when I removed one part of qualified name, for example I tried: "WHERE mongodb.test.intField = 123".
And also following statement was parsed correctly: "SELECT mongodb.test.test.intField, postgres.test.test.intField, postgres.test.test.datefield FROM mongodb.test.test JOIN postgres.postgres.test.test ON mongodb.test.test.intField = postgres.test.test.intField WHERE mongodb.test.test.intField = 123"

### Expected Behavior
I expected that my query will be parsed.
### Steps to Reproduce the Problem

  `CCJSqlParserUtil.parse(""SELECT mongodb.test.test.intField, postgres.test.test.intField, postgres.test.test.datefield FROM mongodb.test.test JOIN postgres.postgres.test.test ON mongodb.test.test.intField = postgres.test.test.intField WHERE mongodb.test.test.intField = 123"")`

### Specifications

  - Version: 1.4
  - Platform: Windows
  - Subsystem:

**Comment by wumpz** [comment]
This is strange. The solution should be included within V1.4. Long qualified names are supported since V1.2. However I checked it with the actual V2 relevase and it parsed successfully without change. I mean the V2 snapshot. At the moment I producing the V2 release. :)

**Comment by trishLEX** [comment]
Yes, long qualified names are parsed successfully in all other cases, it seems like there is some bug. You said that in v2 my statement was parsed successfully, is there any way to get v2-snapshot via gradle, maven or to get sources of v2? (I am writing my final qualification bachelor work, so it is sad, when some statements are not parsed :) )

**Comment by wumpz** [comment]
Look at the snapshot. I included your test as the last test statement.

**Comment by trishLEX** [comment]
So, thank you, I just have some strange problem. When I run in my test:
`Statement parsed = CCJSqlParserUtil.parse("SELECT mongodb.test.test.intField, postgres.test.test.intField, postgres.test.test.datefield " +
                "FROM mongodb.test.test JOIN postgres.postgres.test.test ON mongodb.test.test.intField = postgres.test.test.intField " +
                "WHERE mongodb.test.test.intField = 123");`
Everything is OK. But if make following:
`String query = "SELECT mongodb.test.test.intField, postgres.test.test.intField, postgres.test.test.datefield FROM mongodb.test.test " +
                "JOIN postgres.postgres.test.test ON mongodb.test.test.intField = postgres.test.test.intField " +
                "WHERE mongodb.test.test.intField = 123";
Table table = executor.execute(query);


public Table execute(String sql){
try {
            Statement statement = CCJSqlParserUtil.parse(new StringReader(sql));
} ...
}`
I got exception. That is not cool at all (((
Anyway thank you, I will try to resolve this strange behaviour.

**Comment by wumpz** [comment]
Thx for using Jsqlparser. 
Cheers Tobias
