### ISSUE TITLE
Cannot parse comparison operators < > <= >= in SELECT

### ISSUE THREAD

**Issue by michael-walker** [JSQLParser/JSqlParser#767]
### Actual Behavior
Cannot parse some operators in SELECT: 
- greater than
- less than
- greater than or equal to
- less than or equal to

### Expected Behavior
Can parse these operators

### Steps to Reproduce the Problem
  eg1. SELECT 15>14 FROM dual
  eg2. SELECT 15<14 FROM dual
  eg3. SELECT 15<=14 FROM dual
  eg4. SELECT 15>=14 FROM dual

https://www.w3resource.com/sql/comparison-operators/sql-comparison-operators.php

### Specifications

  - Version: 1.4, 2.0
  - Platform:
  - Subsystem:

**Comment by michael-walker** [comment]
duplicate issue - apologies

**Comment by michael-walker** [comment]
I was looking through the code, would it make sense to update FunctionWithCondParams with a few more patterns. eg.   
- (1 < 2)
- 1 < 2
- if( 1 < 2)
- iff(1 < 2)

**Comment by wumpz** [comment]
@michael-walker **FunctionWithCondParams**  was introduced due to performance issues. Nevertheless one could try to merge it again with **Function** because of recent grammar refactorings. There is a chance the performance impact is not so big.

**Comment by wumpz** [comment]
I have looked into this problem. The solution would be to change this rule and replace **SimpleExpression** by **Condition**:

```
SelectExpressionItem SelectExpressionItem():
{
    SelectExpressionItem selectExpressionItem = null;
    Expression expression = null;
    Alias alias = null;
}
{
     expression=SimpleExpression() { selectExpressionItem = new SelectExpressionItem(); selectExpressionItem.setExpression(expression); }
             [alias=Alias() { selectExpressionItem.setAlias(alias); }] { return selectExpressionItem; }
}
```

The problem here is, that the **Condition** production is way to slow. This would nearly double the parsing time of some statements. 

However, the way seems right. One has to refactor the grammar to cope better with this construct. If this is achieved, then even the problem with conditions as function parameters would disappear.

**Comment by michael-walker** [comment]
Cheers! Tried the change - works for me (only the testPivot5 unit test failed). Even if the parsing times increase, this seems to solve quite a few open issues in the interim.

**Comment by wumpz** [comment]
Is this problem solved by recent changes? At least **if(a<b)** should work.

Look at test: **testFuncConditionParameter**.

**Comment by yuzhougit** [comment]
Version 2.1, parse below statement will report exception
SELECT `NAME` = 'dgadmin' AS IS_SUPER  FROM  `AD_USER`

Caused by: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "=" "="
    at line 1, column 15.

Was expecting one of:

    "&"
    ","
    "::"
    ";"
    "<<"
    ">>"
    "ACTION"
    "ANY"
    "AS"
    "BYTE"
    "CASCADE"
    "CAST"
    "CHAR"
    "COLLATE"
    "COLUMN"
    "COLUMNS"
    "COMMENT"
    "COMMIT"
    "CONNECT"
    "DESCRIBE"
    "DO"
    "ENABLE"
    "END"
    "EXCEPT"
    "EXTRACT"
    "FIRST"
    "FN"
    "FOLLOWING"
    "FOR"
    "FROM"
    "GROUP"
    "HAVING"
    "INDEX"
    "INSERT"
    "INTERSECT"
    "INTERVAL"
    "INTO"
    "ISNULL"
    "KEY"
    "LAST"
    "MATERIALIZED"
    "MINUS"
    "NEXTVAL"
    "NO"
    "NULLS"
    "OPEN"
    "ORDER"
    "OVER"
    "PARTITION"
    "PATH"
    "PERCENT"
    "PRECISION"
    "PRIMARY"
    "PRIOR"
    "RANGE"
    "REPLACE"
    "ROW"
    "ROWS"
    "SEPARATOR"
    "SIBLINGS"
    "START"
    "TABLE"
    "TEMP"
    "TEMPORARY"
    "TOP"
    "TRUNCATE"
    "TYPE"
    "UNION"
    "UNSIGNED"
    "VALUE"
    "VALUES"
    "WHERE"
    "WINDOW"
    "XML"
    "ZONE"
    "^"
    "|"

**Comment by wumpz** [comment]
Actual version parses this.
