### ISSUE TITLE
how to iterate inner select query which is in where clause

### ISSUE THREAD

**Issue by Umesh-Markande** [JSQLParser/JSqlParser#768]
I have query with sub select in where condition 

SELECT  hallprefs.studentname AS fdsf , ferwfsdfs frere 
				FROM            students 
				WHERE gh=jgjh 
				AND   tsfds = (select test from testtable where test = test1);

how to iterate this subselect in where condtion.
Thank You.

**Comment by wumpz** [comment]
Do you want to process this with a visitor?

**Comment by Umesh-Markande** [comment]
yes

**Comment by wumpz** [comment]
Isn't there a simple visit with Expression visitor that catches subqueries? Have to take a look myself.

**Comment by wumpz** [comment]
Do you mean something like:

    Select select = (Select) CCJSqlParserUtil.parse("SELECT hallprefs.studentname AS fdsf , ferwfsdfs frere FROM students WHERE gh=jgjh AND tsfds = (select test from testtable where test = test1)");
        select.getSelectBody().accept(new SelectVisitorAdapter() {
            @Override
            public void visit(PlainSelect plainSelect) {
                plainSelect.getWhere().accept(new ExpressionVisitorAdapter() {
                    @Override
                    public void visit(SubSelect subSelect) {
                        System.out.println(subSelect.toString());
                    }
                });
            }
        });

**Comment by Umesh-Markande** [comment]
Thank you.
