### ISSUE TITLE
How to judge the expression type?

### ISSUE THREAD

**Issue by bigfacewo** [JSQLParser/JSqlParser#771]
I have two expressions:

``` `A1` ```
``` `A1` > 1000```

When i use ```parseExpression``` or ```parseCondExpression``` get an expression;

So,How to distinguish which expression?

Thanks!

**Comment by wumpz** [comment]
So you say you are able to parse it using both utility methods? Recently the expression was extended to support relational expressions as well.  So my guess is, that one of these methods is superfluous.

**Comment by bigfacewo** [comment]
I mean，if i have an expression, just called ```exp```, How to judge whether the ```exp``` has only one element,like ``` `A1` ```,not ``` `A1` > 1000 ```.

**Comment by wumpz** [comment]
Maybe something like:

        Expression exprCond = CCJSqlParserUtil.parseCondExpression("`A1` > 1000");
        Expression expr = CCJSqlParserUtil.parseCondExpression("`A1`");

        ExpressionVisitorAdapter visitor = new ExpressionVisitorAdapter() {
            @Override
            public void visit(Column column) {
                System.out.println("column=" + column);
            }

            @Override
            protected void visitBinaryExpression(BinaryExpression expr) {
                System.out.println("binary=" + expr);
            }
        };

        System.out.println(expr.toString());
        expr.accept(visitor);
        System.out.println(exprCond.toString());
        exprCond.accept(visitor);


Or more simple, you could check the class type of your expression. Those conditions are extended from a binary expression.

**Comment by wumpz** [comment]
Can we close this issue?
