### ISSUE TITLE
How create sql to oracle or other database?

### ISSUE THREAD

**Issue by bigfacewo** [JSQLParser/JSqlParser#772]
I build a Select object,just called ```select```, and I use ```limit``` clause .Then the ```select.toString()``` contains string ```limit 200000```.

Then,How can I make the ```select``` create an sql statements used by Oracle?

**Comment by wumpz** [comment]
JSqlParser tries to give you a structured look at your sql. There is no possibility to transform from one to another database dialect. Using visitors and stuff you should replace this by your own.

I assume you want to transform the `limit 200000` to something like `rownum<=200000`.

**Comment by bigfacewo** [comment]
Thanks, I already know what to do.
