### ISSUE TITLE
how should I user 'hibernate_sequence.nextval ' in jsqlparser2.0

### ISSUE THREAD

**Issue by hw1986232** [JSQLParser/JSqlParser#773]
hi:
 There is a problem when I use 2.0 to parse sql string "`INSERT INTO tableA(ID,c1,c2) select hibernate_sequence.nextval,c1,c2 from tableB`", 

`CCJSqlParser parser = new CCJSqlParser(new StreamProvider(statementReader))
`
the error message is 

**Caused by:net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "." "."
    at line 1, column 101.**

How should i to dealwith '.' which in "hibernate_sequence.nextval" ? Could You send a email to hw1986232@163.com?

thanks!

**Comment by wumpz** [comment]
It was simply a bug. **nextval** is a keyword to **JSqlParser**, but was not allowed to be used in column or table names.
