### ISSUE TITLE
sql contains the not function error

### ISSUE THREAD

**Issue by qmdx** [JSQLParser/JSqlParser#775]
### Actual Behavior
    @Test
    void notLikeParser() throws Exception {
        final String targetSql = "SELECT * FROM mybatis-plus WHERE id NOT LIKE ?";
        Select select = (Select) CCJSqlParserUtil.parse(targetSql);
        assertThat(select.toString()).isEqualTo(targetSql);
    }

### Expected Behavior
sql:            column not like 
parser result:      not column like

### Specifications

  - Version: 1.3 +

**Comment by wumpz** [comment]
done
