### ISSUE TITLE
Greater than symbol or less than symbol resolution error in sql

### ISSUE THREAD

**Issue by yinjunonly** [JSQLParser/JSqlParser#776]
### Actual Behavior
When parsing the following statement:
`		String sql = "select 1<2 from table_name";
		CCJSqlParserUtil.parse(sql);
`
Throw an exception：
`
Encountered unexpected token: "<" "<"
`
### Expected Behavior
Normal parsing
### Specifications

  - Version:2.0.0
  - Platform:
  - Subsystem:

**Comment by wumpz** [comment]
JSqlParser 4.0 parses this.
