### ISSUE TITLE
High RAM consumption with big files

### ISSUE THREAD

**Issue by osgger** [JSQLParser/JSqlParser#777]
Hello,

I'm trying to parse a big sql file. It contains about 600,000 insert statements. I'm not really interested in the whole object tree, but rather getting those statements divided into single statements. Using the Statements() method works just fine - except the enormous amount of memory used for allocating the statements object. (At least I guess that's the reason.)

Is there a way of iterating through the statements in the file without creating the whole object tree for all statements (like xml SAX vs. DOM)? Or is this just not a typical use case for this lib?

I would appreciate if someone could give me a little hint.

Thanks in advance!

Alex

**Comment by wumpz** [comment]
I think at the moment single statement parse expects an EOF at the and. One could provide a variant like parseExpression that only parses eager but does not need the whole expression string accept.

**Comment by wumpz** [comment]
Do you want to provide a pull request? This seems to be a useful feature.

**Comment by osgger** [comment]
Thanks for your answer and for your trust in my competence, but I haven't dealt with lexer nor the visitor pattern so far. It seems you're using JJTree, right? I guess it would take months of after work studies to be ready to code something. Therefore I'm not positive about being the man solving this issue.

The Statement() method expects EOF just as you've stated. So this won't help.

The parseExpression() method I haven't tried yet. And I don't know, if it's a good idea to create my own parsing, since your parser is doing a great job splitting the statements, except for its eagerness. Or is it really easy?

My statements are separated by ";\n". But what if if a statement looks like the second one:

`select "lastname" || ';' || chr(10) || "forename" from "names";`

`select "lastname" || ';`
`' || "forename" from "names";`


Your parser comes up correctly with 2 statements. My naive implementation using parseExpression() would probably find 3.

**Comment by wumpz** [comment]
I implemented your issue: there is a new method within **CCJSqlParserUtil**:

`public static void streamStatements(StatementListener listener, InputStream is, String encoding)`

that does what you want. Look as well into test **testStreamStatementsIssue777**
