### ISSUE TITLE
Table in Column is not populated

### ISSUE THREAD

**Issue by arcuri82** [JSQLParser/JSqlParser#780]
Hi,
 I am trying to update JSqlParser from 1.1 to 2.0, but it breaks (having same issue as well when trying 1.4). In my code, given a `Column`, I was accessing its `Table`. This worked in 1.1 (although it fails in the following example, albeit differently), but it is seems it is null in both 1.4 and 2.0. Considering the following simple test case:

    @Test
    public void testIssue() throws Exception{

        String sql = "SELECT x From Foo";
        Select select = (Select) CCJSqlParserUtil.parse(sql);

        PlainSelect plainSelect = (PlainSelect) select.getSelectBody();

        Table table = (Table) plainSelect.getFromItem();
        assertNotNull(table);
        assertEquals("Foo", table.getName());

        Column column = (Column) ((SelectExpressionItem) plainSelect.getSelectItems().get(0)).getExpression();
        assertEquals("x", column.getColumnName());
        assertNotNull(column.getTable()); // 1.4 and 2.0 fail being "null"
        assertEquals("Foo", column.getTable().getName()); // 1.1 fails being "null"
    }

I would have expected that `plainSelect.getFromItem()` and `column.getTable()` would return a valid `Table` with the same information, but it does not. Is this expected or indeed a bug?

**Comment by wumpz** [comment]
You are right, that older versions returned some empty table object.  This is now not the case anymore.
JSqlParser is only a parser. The semantics is up to you :). 

JSqlParser cannot derive the table name from your SQL because it does not know about your database schema. Imagine something like:

`select a, c from mytab1, mytab2`

**Comment by arcuri82** [comment]
thanks. That's a very valid point, which I did not think about.
but, then, wouldn't make it sense to  either:
1) remove `Column.getTable()` from the API? 
2) discuss this issue in its JavaDocs? 
3) trying to infer the `Table`, but then either throw an exception when it is ambiguous, or return a list of possibilities for it?

**Comment by arcuri82** [comment]
sorry, digging bit more into it, and if writing `SELECT t.x From Foo t`, then `Column.getTable()` would return information for `t`. However, the two `Table`  ( `Column.getTable()`  and `plainSelect.getFromItem()`) objects would be different (i.e, the former having name `t`, whereas the latter having name `Foo` with an extra field `alias` for `t`).

Now it makes sense... :)

**Comment by wumpz** [comment]
So we can close this one?

**Comment by arcuri82** [comment]
yes, but I would suggest to add some comments in the code. After your explanation, it was clear. But I guess other people like me trying to use JSqlParser for first time might get confused by a `getTable` method that does return `null` when the table is well defined and its resolution is non-ambiguous.

**Comment by wumpz** [comment]
You are right. as you can see, there is already an issue to do more comments. In fact, multiple comments were stripped while adding the new license header. 

Do you want to provide some documentation, javadocs or examples? You know, developers tend to skip it :).

**Comment by arcuri82** [comment]
fair enough :)  I can provide some JavaDocs for `getTable` in a PR based on this discussion, likely later today

**Comment by wumpz** [comment]
Included. Thx. I will not stop you from doing more :).
