### ISSUE TITLE
a mysql SQL statement cannot be parsed

### ISSUE THREAD

**Issue by shmily2038** [JSQLParser/JSqlParser#783]
### Actual Behavior
目前SQL报错
### Expected Behavior
能够正常运行
### Steps to Reproduce the Problem

  1.使用mybatis-plus 3.1.0,采用JSqlParser2.0
  1.具体问题，请查阅https://github.com/baomidou/mybatis-plus/issues/1023
  1.mybatis-plus采用JSqlParser报错
`UPDATE fb_oms_es_template_config
        SET status = 0,
        rec_ver = rec_ver + 1,
        modify_time = SYSDATE()
        WHERE
         
                (id,tenant_id) IN
                 (  
                    (?,?)
                 )`
### Specifications

  - Version:
  - Platform:
  - Subsystem:

**Comment by wumpz** [comment]
Could you please rewrite your issue in English? I myself could use google translator, but others that try to find issues would not find it.

**Comment by AnEmortalKid** [comment]
The query mentioned here is at least parseable now: 

![image](https://user-images.githubusercontent.com/3474369/85235144-4929b780-b3d8-11ea-92a3-b7697fb5b46f.png)
