### ISSUE TITLE
Failed to parse ALL keyword in SQL statement

### ISSUE THREAD

**Issue by kulbhushan333** [JSQLParser/JSqlParser#784]
**### Issue** - Failed to parse **ALL** keyword in query.

**Issue Description** - Failed to parse All keyword in query. 
My query is 
**SELECT * FROM Employee WHERE  salary > ALL (10000, 25000, 40000);**
This query is valid query. 
But JSqlParser throws exception while parsing.

**### Steps to Reproduce the Problem**

Statements statements = CCJSqlParserUtil.parseStatements("SELECT * FROM Employee WHERE  salary > ALL (10000, 25000, 40000);");

**### Specifications**
  - Version: 2.0
  - Platform: Windows
  - Subsystem: Java 8

**Comment by AnEmortalKid** [comment]
The root here is the `>` symbol

![image](https://user-images.githubusercontent.com/3474369/85235119-0ec01a80-b3d8-11ea-9d46-aab71043d777.png)

Related to #776

**Comment by manticore-projects** [comment]
[Successfully tested with JSQLParser-4.2](http://jsqlformatter.manticore-projects.com/jsqlformatter/demo.html?args=-c%20MoUQMiDCAqAEBUAoAYgJQPIFlYFMC2ADgDYD2AnjjogOoASIqIsAzgIZGsBOZsAfLAEEiRABSwAjAAZpkgDSwATAFYZ8gCwzJsAJSIA3EA+)
