### ISSUE TITLE
Column.getTable() is not working 

### ISSUE THREAD

**Issue by Hyunsuk-Baek** [JSQLParser/JSqlParser#792]
### Actual Behavior

using this query  ==>
[ 
select
    col1, col2, (select c44 from T4 where col4 = dt.col3) col3
from (
    select
        t1.c1 as col1, 
        t2.c2 as col2,
        t3.c3 as col3
    from T1 t1, dbo.T2 t2
    inner join public.T3 t3 on t1.tc1 = t3.tc33
    where t1.tc11 = t2.tc22
) dt
]
2019-05-09 17:41:44.969  INFO 28244 --- [           main] c.s.s.service.impl.ParserServiceImpl     : **[T4, T1, dbo.T2, public.T3]**

### Expected Behavior
[T1.c1,
T1.tc1,
T1.tc11,
T4.c44,
T4.col4,
dbo.T2.c2,
dbo.T2.tc22,
public.T3.c3,
public.T3.tc33]

### Steps to Reproduce the Problem

 1. I want to get columns information related above tables info using  **Columns.getTable()**
 2. I got [T4, T1, dbo.T2, public.T3] table's list using by  TablesNamesFinder and its function getTableList()
 3. So would you like to help me how to get columns information related table info? 

### Specifications

  - Version: 2.0
  - Platform: win10 / mysql/ postgreSql
  - Subsystem:nothing

**Comment by wumpz** [comment]
Maybe this helps you: https://stackoverflow.com/questions/40908062/parsing-table-and-column-names-from-sql-hql-java?rq=1.

**Comment by Hyunsuk-Baek** [comment]
> Maybe this helps you: https://stackoverflow.com/questions/40908062/parsing-table-and-column-names-from-sql-hql-java?rq=1.

i confirmed your link stackoverflow. 
thanks for your reply 
but, that link doesn't have answer about "relationship" with columns and tables. it just get all columns and tables. 
i want to know table-columns relation.. 
Could you inform me that how can i get.../

**Comment by wumpz** [comment]
JSqlParser is simple a parser. It does not provide a semantic process of the parsed data, it does not follow aliases and so on. A large part of this semantics cannot even be derived, due to JSqlParser does not know about your database schema. 

select a from mytab1, mytab2

From which table a comes cannot be derived from the sql only.

The main problem you are facing here is to find out, from which subsql a column comes. Even if Column.getTable seems to deliver the real table of the column, it is in fact only the parsed part or alias name in front of the column: **mytab.col1**.

**Comment by wumpz** [comment]
So may I close this one?

**Comment by khalidcawl** [comment]
@wumpz If I have the schema/metadata information, is it possible to produce the column-table relation?

**Comment by wumpz** [comment]
The naive way would be a check if a column name is included within a table. The column and tables could be retrieved using the TableNamesFinder. Aliases should be followed. 

But to get it right, you have to check visibility for tables and columns within your statement. I am not quite sure, if one could implement this, by implementing a special visitor or if there is more. Hmm.

@khalidcawl How far have you come?

**Comment by khalidcawl** [comment]
Well, I was playing around with ANTLR until a hit a wall to solve this problem (column-table relation). That is why I came here, hoping JSqlParser has this structure somewhere already. 

Printing table and column names is not an issue. Deducing the relationship is. 

I thought of creating a symbol table out of the parse tree, but I dont' know how to scope SQL statements. I am not a compiler expert, unfortunately. 

I am now trying to design an algorithm where I can traverse each node and try to map the columns in the SELECT with the tables in the FROM clause (might have to recursively resolve derived tables in subqueries). 

Do you have any ideas, @wumpz ?

**Comment by wumpz** [comment]
No. JSqlParser has this structure not. It is only a parser.

Scoping will be really hard. You have to check in both directions.

`SELECT a, b, (SELECT b FROM mytab2) c FROM mytab1`

**b** comes from **mytab1**. It is used within the subselect. Therefore if **mytab2** has no **b** it comes from the outer SQL.

You have to use some kind of stack to collect the columns used and try to map it to the tables.

**Comment by khalidcawl** [comment]
Yeah, it is not a trivial problem. Nevertheless, thanks for the input @wumpz

**Comment by latincross** [comment]
This may solve your problem. @khalidcawl
https://github.com/alibaba/druid/wiki/SchemaStatVisitor
