### ISSUE TITLE
How to replace "between expression" with "regular condition"?

### ISSUE THREAD

**Issue by jp2475** [JSQLParser/JSqlParser#793]
For example:

I have a query like this:
select a,b,c from t where t.a between 1 and 3 and t.b = 20 

I want to reformulate it into:

select a,b,c from t where t.a>=1 and t.a<=3 and t.b=20

Basically, I want to replace every occurrence of between with regular conditions.

I tried to delete the ast node of between expression but it seems that there's no delete method for AST node. BTW, I also tried to add child to replace it but I don't know how to locate and identify the between expression since it is parsed into three nodes(as far as I can observe).

**Comment by wumpz** [comment]
The AST - tree cannot be changed in that way. You have two options. 
First: with the position within your original text, you are able to replace the expression within your SQL. 
Two: You use the parsed object tree (not AST), using a visitor implementation, that searches and replaces your expressions.

**Comment by wumpz** [comment]
Can we close this one?

**Comment by peijialing** [comment]
yes thx! I solved it

**Comment by jp2475** [comment]
Yes Pls close it
