### ISSUE TITLE
Is the JqlParser support parser Pl/sql of Oracle or pl/pgSql of Postgre?

### ISSUE THREAD

**Issue by ducpm1310** [JSQLParser/JSqlParser#794]
### Actual Behavior
I hava a  example procedure as below, and i try to extract it to a list of statement as raw SQL query
String pl = ""
				+ "DECLARE\r\n" + "\r\n" 
				+ "  N VARCHAR2;\r\n" 
				+ "  P NUMBER;\r\n" + "\r\n"
				+ "	 BEGIN\r\n" + "  /* NORMAL SQL */\r\n" 
				+ "  SELECT C.NAME, P.PRICE\r\n" + "  INTO N, P\r\n"
				+ "  FROM CUSTOMER C, PRODUCT P\r\n" 
				+ "  WHERE C.G_ID1 = P.G_ID1\r\n" + "    AND C.AMOUNT > :BA\r\n"
				+ "  ORDER BY C.NAME;\r\n" + "END;";
System.out.println(CCJSqlParserUtil.parseStatements(procedureLanguage));
### Expected Behavior
But, i give a error as below : 
Caused by:
net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "DECLARE" <S_IDENTIFIER>
    at line 1, column 1.

**Comment by wumpz** [comment]
Like I said in the Email. JSqlParser is only a SQL parser.
