### ISSUE TITLE
Can you provide a method to get the table and the fields it contains?

### ISSUE THREAD

**Issue by latincross** [JSQLParser/JSqlParser#795]
Like this：
```
a(id ,name ,bid)
b(id ,name)
c(id ,name)

  insert into a
    select b.id bid ,c.id ,c.name
      from b ,c
    where b.id=c.id
```
Expect:

|    a  |  insert   |  bid ,id ,name  |
|-----|--------|--------|
|    b  |  select  | id          |
|    c  |  select  | id ,name|

**Comment by wumpz** [comment]
You could join the discussion here: #792. This is a hard problem to tackle. If there is no table definition, what would you expect the output to be?

`select a, c from mytab1, mytab2`

**Comment by latincross** [comment]
|    mytab1  |   a  |
|-----|--------|
|    mytab2 |  a    |

**Comment by wumpz** [comment]
Means you are going a probabilistic approach at first. Nevertheless, the visibility problem still exists.

**Comment by manticore-projects** [comment]
Closing this since its not an error and no further question has been asked,
