### ISSUE TITLE
Exception parsing valid statement: Encountered unexpected token: "COLLATE"

### ISSUE THREAD

**Issue by ngrash** [JSQLParser/JSqlParser#798]
### Actual Behavior

Exception raised parsing the statement ```CREATE TABLE `comment` (`text_hash` varchar(32) COLLATE utf8_bin)```:

```
net.sf.jsqlparser.JSQLParserException
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parseStatements(CCJSqlParserUtil.java:123)

Caused by: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "COLLATE" "COLLATE"
    at line 1, column 383.

Was expecting one of:

    "("
    ")"
    "+"
    ","
    "-"
    "="
    "BY"
    "CASCADE"
    "CHECK"
    "COMMENT"
    "COMMIT"
    "CONSTRAINT"
    "DELETE"
    "EXCLUDE"
    "FOREIGN"
    "IN"
    "KEY"
    "NOT"
    "NULL"
    "ON"
    "PARTITION"
    "PRIMARY"
    "REFERENCES"
    "ROWS"
    "TABLESPACE"
    "TEMP"
    "TEMPORARY"
    "TYPE"
    "UNIQUE"
    "UNSIGNED"
    "UPDATE"
    "USING"
    "WHERE"
    "WITH"
    <K_TIME_KEY_EXPR>
    <S_CHAR_LITERAL>
    <S_DOUBLE>
    <S_IDENTIFIER>
    <S_LONG>
    <S_QUOTED_IDENTIFIER>
```

### Expected Behavior

Parses statement without exception.

### Steps to Reproduce the Problem

Run this snippet:

 ```
CCJSqlParserUtil.parseStatements("CREATE TABLE `comment` (`text_hash` varchar(32) COLLATE utf8_bin)");
```

### Specifications

  - Version: 2.0 Release
  - Platform: openjdk version "1.8.0_212" on Arch Linux

**Comment by ivantichy** [comment]
The same problem here:
CREATE TABLE `parent` (
  `PARENT_ID` int(11) NOT NULL AUTO_INCREMENT,
  `PCN` varchar(100) NOT NULL,
  `IS_DELETED` char(1) NOT NULL,
  `STRUCTURE_ID` int(11) NOT NULL,
  `DIRTY_STATUS` char(1) NOT NULL,
  `BIOLOGICAL` char(1) NOT NULL,
  `STRUCTURE_TYPE` int(11) NOT NULL,
  `CST_ORIGINAL` varchar(1000) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `MWT` decimal(14,6) DEFAULT NULL,
  `RESTRICTED` int(11) NOT NULL,
  `INIT_DATE` datetime DEFAULT NULL,
  `MOD_DATE` datetime DEFAULT NULL,
  `CREATED_BY` varchar(255) NOT NULL,
  `MODIFIED_BY` varchar(255) NOT NULL,
  `CHEMIST_ID` varchar(255) NOT NULL,
  `UNKNOWN_ID` int(11) DEFAULT NULL,
  `STEREOCHEMISTRY` varchar(256) DEFAULT NULL,
  `GEOMETRIC_ISOMERISM` varchar(256) DEFAULT NULL,
  PRIMARY KEY (`PARENT_ID`),
  UNIQUE KEY `PARENT_PCN_IDX` (`PCN`),
  KEY `PARENT_SID_IDX` (`STRUCTURE_ID`),
  KEY `PARENT_DIRTY_IDX` (`DIRTY_STATUS`)
) ENGINE=InnoDB AUTO_INCREMENT=2663 DEFAULT CHARSET=utf8

**Comment by wumpz** [comment]
Was already fixed within the actual snapshot.
