### ISSUE TITLE
parseCondExpression() does not reject non-conditional expressions

### ISSUE THREAD

**Issue by matthieu-vergne** [JSQLParser/JSqlParser#803]
### Actual Behavior

Code:
```java
try {
	Expression expression = CCJSqlParserUtil.parseCondExpression("myColumn", false);
	System.out.println("Type: " + expression.getClass());
	System.out.println("Expr: " + expression);
} catch (JSQLParserException cause) {
	cause.printStackTrace();
}
```

Result:
```java
Type: class net.sf.jsqlparser.schema.Column
Expr: myColumn
```

### Expected Behavior

It should throw a `JSQLParserException` because it is not a condition. Indeed, the Javadoc of `parseCondExpression()` says that:
```
Parse an conditional expression. This is the expression after a where clause.
```

### Steps to Reproduce the Problem

  1.Run the provided code
  2.Observe the result

It does the same with other pieces of SQL:
```
Type: class net.sf.jsqlparser.expression.StringValue
Expr: 'my string value'
```
```
Type: class net.sf.jsqlparser.expression.LongValue
Expr: 123
```
```
Type: class net.sf.jsqlparser.expression.NullValue
Expr: NULL
```

### Specifications

  - Version: 2.0 (through POM dependency)
  - Platform: Ubuntu 16.04
  - Subsystem: ?

**Comment by matthieu-vergne** [comment]
I have tried to play a bit on #806 to try fixing it, but with no avail.
It looks to me like the grammar is too permissive.
Someone with more expertise may have a better conclusion, though.

**Comment by wumpz** [comment]
Using e.g. postgresql, this is a valid statement:

```
alter table mytab add bo_value boolean;
update mytab set bo_value = true;

select * from feature where bo_value; 
```

Therefore bo_value is a valid condition, even a string literal is valid, if it is **'true'** or **'false'**.

Since JSqlParser does not know about the database schema and the column type, it cannot skip your single column statements. One has to check, if this is valid in conjunction with the database schema.

**Comment by matthieu-vergne** [comment]
I understand for the boolean values, and for the boolean column. I can see some uses to it.

But what about the string value? Is it still valid? It seems logical that it should be a boolean expression rather than any expression. Or do you know about any DB accepting that?

**Comment by wumpz** [comment]
`select * from feature where 'true'`

is valid for postgresql.

**Comment by matthieu-vergne** [comment]
Oh, that is tricky. {>_<}

Then I guess I should not rely on the generic parsing to have something more restricted.

My context is the following: I have a Web server which returns a list of resources when requesting a given URL (REST API), and I want to add parameters with SQL-like queries to filter the list to return. I assume I should pick the specific classes of Expression I want to support on my server and apply a parsing on them directly. Is there a recommended way to do it?

**Comment by wumpz** [comment]
Maybe you should use parseCondExpression with allowPartialParse set to false. This means the whole string as to be matched. Shouldn' t this solve your problem?

**Comment by matthieu-vergne** [comment]
If you look at my first post, you can see it is already the case.
If you meant "true" then it does not solve my problem either, since it accept invalid queries.

**Comment by wumpz** [comment]
Ops. Sorry. Overlooked that.

**Comment by matthieu-vergne** [comment]
I tried to do it another way, and so far it works.
Since going further on this matter would be out of the scope of this issue, I close it.
Thank you for your time.
