### ISSUE TITLE
Failed to parse PostgreSQL recursive query with "::"

### ISSUE THREAD

**Issue by k2ketan** [JSQLParser/JSqlParser#808]
**Failed to parse below query :**

with recursive objectModelRelationTree (id, relation_name, parent_ice_object_model_id, child_ice_object_model_id, child_ice_object_id, parent_ice_object_id, hierlevel, context_path_display_value, context_path, path, cycle) as  ( select iom.id, relation_name, parent_ice_object_model_id, child_ice_object_model_id, child_ice_object_id, parent_ice_object_id,  1, relation_name||'', iom.id||'', array[cast(child_ice_object_id as varchar)]::varchar[], false  from   ICE_OBJECT_MODEL_RELATION iom, ICE_RESOURCE ir  where  parent_ice_object_id = ? and parent_ice_object_model_id = ? and iom.id = ir.id  union all select child.id,child.relation_name,child.parent_ice_object_model_id,child.child_ice_object_model_id,child.child_ice_object_id,child.parent_ice_object_id, tree.hierlevel + 1, tree.context_path_display_value||'>‘|| child.relation_name, tree.context_path||'/‘|| child.id, (cast(tree.path as varchar)::varchar[] || cast(child.child_ice_object_id as varchar))::varchar[], cast(child.child_ice_object_id as varchar) = ANY(path)  from  ICE_OBJECT_MODEL_RELATION child join ICE_RESOURCE ir on  ir.id = child.id  join objectModelRelationTree tree on (tree.child_ice_object_id =child.parent_ice_object_id)  where child.parent_ice_object_model_id = ? and not cycle )  select context_path, context_path_display_value, child_ice_object_id, child_ice_object_model_id, id, parent_ice_object_id from objectModelRelationTree

**Exception stacktrace :**

 Caused by: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "::" "::"
pbs-backend_1      | 04:45:48,233 ERROR [stderr] (default task-11)     at line 1, column 436.
pbs-backend_1      | 04:45:48,233 ERROR [stderr] (default task-11) 
pbs-backend_1      | 04:45:48,234 ERROR [stderr] (default task-11) Was expecting one of:
pbs-backend_1      | 04:45:48,234 ERROR [stderr] (default task-11) 
pbs-backend_1      | 04:45:48,235 ERROR [stderr] (default task-11)     ")"
pbs-backend_1      | 04:45:48,235 ERROR [stderr] (default task-11)     ","
pbs-backend_1      | 04:45:48,236 ERROR [stderr] (default task-11)     "CONNECT"
pbs-backend_1      | 04:45:48,236 ERROR [stderr] (default task-11)     "EXCEPT"
pbs-backend_1      | 04:45:48,237 ERROR [stderr] (default task-11)     "FOR"
pbs-backend_1      | 04:45:48,237 ERROR [stderr] (default task-11)     "FROM"
pbs-backend_1      | 04:45:48,238 ERROR [stderr] (default task-11)     "GROUP"
pbs-backend_1      | 04:45:48,238 ERROR [stderr] (default task-11)     "HAVING"
pbs-backend_1      | 04:45:48,239 ERROR [stderr] (default task-11)     "INTERSECT"
pbs-backend_1      | 04:45:48,239 ERROR [stderr] (default task-11)     "INTO"
pbs-backend_1      | 04:45:48,240 ERROR [stderr] (default task-11)     "MINUS"
pbs-backend_1      | 04:45:48,240 ERROR [stderr] (default task-11)     "ORDER"
pbs-backend_1      | 04:45:48,240 ERROR [stderr] (default task-11)     "START"
pbs-backend_1      | 04:45:48,241 ERROR [stderr] (default task-11)     "UNION"
pbs-backend_1      | 04:45:48,241 ERROR [stderr] (default task-11)     "WHERE"
pbs-backend_1      | 04:45:48,242 ERROR [stderr] (default task-11) 
pbs-backend_1      | 04:45:48,243 ERROR [stderr] (default task-11) 	at net.sf.jsqlparser.parser.CCJSqlParser.generateParseException(CCJSqlParser.java:20872)
pbs-backend_1      | 04:45:48,244 ERROR [stderr] (default task-11) 	at net.sf.jsqlparser.parser.CCJSqlParser.jj_consume_token(CCJSqlParser.java:20722)
pbs-backend_1      | 04:45:48,245 ERROR [stderr] (default task-11) 	at net.sf.jsqlparser.parser.CCJSqlParser.WithItem(CCJSqlParser.java:3802)
pbs-backend_1      | 04:45:48,245 ERROR [stderr] (default task-11) 	at net.sf.jsqlparser.parser.CCJSqlParser.WithList(CCJSqlParser.java:3745)
pbs-backend_1      | 04:45:48,246 ERROR [stderr] (default task-11) 	at net.sf.jsqlparser.parser.CCJSqlParser.Select(CCJSqlParser.java:3238)
pbs-backend_1      | 04:45:48,246 ERROR [stderr] (default task-11) 	at net.sf.jsqlparser.parser.CCJSqlParser.SingleStatement(CCJSqlParser.java:119)
pbs-backend_1      | 04:45:48,247 ERROR [stderr] (default task-11) 	at net.sf.jsqlparser.parser.CCJSqlParser.Statement(CCJSqlParser.java:70)
pbs-backend_1      | 04:45:48,248 ERROR [stderr] (default task-11) 	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:36)
pbs-backend_1      | 04:45:48,249 ERROR [stderr] (default task-11) 	... 322 more
pbs-backend_1      | 04:45:48,249 ERROR [stderr] (default task-11) Caused by:
pbs-backend_1      | 04:45:48,250 ERROR [stderr] (default task-11) net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "::" "::"
pbs-backend_1      | 04:45:48,251 ERROR [stderr] (default task-11)     at line 1, column 436.
pbs-backend_1      | 04:45:48,251 ERROR [stderr] (default task-11) 
pbs-backend_1      | 04:45:48,252 ERROR [stderr] (default task-11) Was expecting one of:
pbs-backend_1      | 04:45:48,252 ERROR [stderr] (default task-11) 
pbs-backend_1      | 04:45:48,253 ERROR [stderr] (default task-11)     ")"
pbs-backend_1      | 04:45:48,254 ERROR [stderr] (default task-11)     ","
pbs-backend_1      | 04:45:48,254 ERROR [stderr] (default task-11)     "CONNECT"
pbs-backend_1      | 04:45:48,255 ERROR [stderr] (default task-11)     "EXCEPT"
pbs-backend_1      | 04:45:48,256 ERROR [stderr] (default task-11)     "FOR"
pbs-backend_1      | 04:45:48,256 ERROR [stderr] (default task-11)     "FROM"
pbs-backend_1      | 04:45:48,257 ERROR [stderr] (default task-11)     "GROUP"
pbs-backend_1      | 04:45:48,257 ERROR [stderr] (default task-11)     "HAVING"
pbs-backend_1      | 04:45:48,258 ERROR [stderr] (default task-11)     "INTERSECT"
pbs-backend_1      | 04:45:48,259 ERROR [stderr] (default task-11)     "INTO"
pbs-backend_1      | 04:45:48,259 ERROR [stderr] (default task-11)     "MINUS"
pbs-backend_1      | 04:45:48,259 ERROR [stderr] (default task-11)     "ORDER"
pbs-backend_1      | 04:45:48,260 ERROR [stderr] (default task-11)     "START"
pbs-backend_1      | 04:45:48,260 ERROR [stderr] (default task-11)     "UNION"
pbs-backend_1      | 04:45:48,261 ERROR [stderr] (default task-11)     "WHERE"
pbs-backend_1      | 04:45:48,261 ERROR [stderr] (default task-11) 
pbs-backend_1      | 04:45:48,262 ERROR [stderr] (default task-11) 	at net.sf.jsqlparser.parser.CCJSqlParser.generateParseException(CCJSqlParser.java:20872)
pbs-backend_1      | 04:45:48,263 ERROR [stderr] (default task-11) 	at net.sf.jsqlparser.parser.CCJSqlParser.jj_consume_token(CCJSqlParser.java:20722)
pbs-backend_1      | 04:45:48,264 ERROR [stderr] (default task-11) 	at net.sf.jsqlparser.parser.CCJSqlParser.WithItem(CCJSqlParser.java:3802)
pbs-backend_1      | 04:45:48,264 ERROR [stderr] (default task-11) 	at net.sf.jsqlparser.parser.CCJSqlParser.WithList(CCJSqlParser.java:3745)
pbs-backend_1      | 04:45:48,265 ERROR [stderr] (default task-11) 	at net.sf.jsqlparser.parser.CCJSqlParser.Select(CCJSqlParser.java:3238)
pbs-backend_1      | 04:45:48,266 ERROR [stderr] (default task-11) 	at net.sf.jsqlparser.parser.CCJSqlParser.SingleStatement(CCJSqlParser.java:119)
pbs-backend_1      | 04:45:48,266 ERROR [stderr] (default task-11) 	at net.sf.jsqlparser.parser.CCJSqlParser.Statement(CCJSqlParser.java:70)
pbs-backend_1      | 04:45:48,267 ERROR [stderr] (default task-11) 	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:36)

**Comment by wumpz** [comment]
You are hitting problem #677. Unfortunately, there is no solution at the moment.

**Comment by wumpz** [comment]
Issue #677 is solved. Now #948 is the problem. JSqlParser does not (yet) allow conditions as select items.

**Comment by wumpz** [comment]
Solved within JSqlParser 4.0-SNAPSHOT.
