### ISSUE TITLE
Issue while parsing sql server query "SELECT top 5 FROM test_address1;"

### ISSUE THREAD

**Issue by sunitapatro** [JSQLParser/JSqlParser#813]
### Actual Behavior
Issue while parsing **sql server** query "SELECT top 5 FROM test_address1;"
Error:
net.sf.jsqlparser.JSQLParserException
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:38)
	at JsqlParserTest.main(JsqlParserTest.java:46)
Caused by: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "FROM" "FROM"
    at line 1, column 14.

Was expecting one of:

    "!"
    "("
    "*"
    "+"
    "-"
### Expected Behavior
SELECT top 5 FROM test_address1;
### Steps to Reproduce the Problem
 CCJSqlParserUtil.parse("SELECT top 5 FROM test_address1;");

I am using jsqlparser2.0 jar.
Is there any specific setting/configuration i need to do to define that its SQL server?

Thank you!

**Comment by wumpz** [comment]
Is this valid? I assumed top has always to have a numeric parameter.

**Comment by sunitapatro** [comment]
Thank you for quick response.

Sorry, this is not valid. SELECT top 5 * FROM test_address1; is valid one and that works.

Basically I am checking if there is a way I can make jsqlparser to parse sql based on given DB.
For example: SELECT top 5 * FROM test_address1; is valid only for SQL Server but not a valid query with DBs like mysql, postgres, etc

So how can I make jsqlparser throw error for this example query, if this query meant for mysql.

Thank you!

**Comment by wumpz** [comment]
A discussion regarding this is ongoing, to switch of features by flags. However, at the moment you have to consider **JSqlParser** a parser and not a validator. Because it supports many specialities from different database vendors you could theoretically build parsable mixed dialect sqls, e.g.

`select top 5 * from mytable1, mytable2 where mytable1.col1 = mytable2.col2(+)`

(`top` from **sqlserver**, `(+)` join from **oracle**)

To check if it is correct e.g. for **mysql** you could implement a visitor, e.g. use the deparser and catch any constructs not valid for your database.

**Comment by sunitapatro** [comment]
Thanks for your inputs.
Yes I agree, jsqlparser is amazing in building parsable mixed dialect sqls.
However we are looking for a library for offline syntax checking, pretty printing, etc. Hence I was evaluating jsqlparser to use as a offline syntax checker for a given DB (mainly sqlserver/mysql/postgres/oracle).

Thank you!

**Comment by wumpz** [comment]
Not at the moment. 

But why don't you give my visitor implementation a try?

I assume this will be a very hard task to achieve if you take differences between versions of one database system in account.

Here was a little discussion about pretty printing: https://stackoverflow.com/questions/43902141/jsqlparser-pretty-print-where-clause

To check if database specific clauses are used you could e.g. use the `ExpressionDeParser`. To detect **(+)** syntax look at `visitOldOracleJoinBinaryExpression`.

**Comment by sunitapatro** [comment]
Not sure of the complexities involved to deal with different DBs. However I am having one more issue.
I earlier tried to work on a sample by adding jsqlparser2.0.jar as a external jar dependency, it works fine. But when added the pom dependency to my project, but it does not seem to download the jar. 
I tried install the jar to my local .m2 repository as well, but its not helping either.
Here is the pom entry.
<dependency>
            <groupId>com.github.jsqlparser</groupId>
            <artifactId>jsqlparser</artifactId>
            <version>2.0</version>
        </dependency>
Any idea where is it going wrong? Thank you!

**Comment by wumpz** [comment]
I tested it with a little example and had no problems downloading it. Could you make a maven build of your project using the -U flag to force actualizing all artifacts?

**Comment by sunitapatro** [comment]
Thanks, yes that helped!

**Comment by wumpz** [comment]
So can we close this issue?

**Comment by sunitapatro** [comment]
Yes, closing.
Just for information, my project's requirement priorities changed. So would be working on using sql parser a little later.
Thank you so much for your quick replies.
