### ISSUE TITLE
Is there any need for a Java 7 JSqlParser build, or can we move on to at least Java 8?

### ISSUE THREAD

**Issue by wumpz** [JSQLParser/JSqlParser#814]

**Comment by AnEmortalKid** [comment]
+1 on java 8.

**Comment by wumpz** [comment]
Fine. First comment on this.
 I remember an issue not long ago eve Java 6 was mentioned. 

I hope the complaints do not start after I switch.

**Comment by AnEmortalKid** [comment]
Well, my consideration was that java 6 wasn’t supported. Java 8 probably loses support for enterprises soon. 

I might have been the one that asked about java 6, maybe like 3 years ago :)

There are configurations to produce two artifacts with different jdks from the same maven, but that just adds complications we might not need it no one needs jdk6 or jdk7

**Comment by wumpz** [comment]
So I will switch and remove Java 7 support with the next release.

**Comment by wumpz** [comment]
Done. JSqlParser 2.2-SNAPSHOT uses Java 8 at the minimum and is JDK 11 buildable.
