### ISSUE TITLE
Timeline for next release 2.1

### ISSUE THREAD

**Issue by AnEmortalKid** [JSQLParser/JSqlParser#815]
### Actual Behavior

There's a fix for #773  in master but it seems 2.0 was released with this bug. 

I was wondering if you had any idea or plans (maybe rough estimate) for when a released version with this fix would be available? I can use a local 2.1-SNAPSHOT at the moment and everything is fine (just started upgrading to 2.0 for my stuff and ran into this).

### Specifications

  - Version: 2.0
  - Platform: Mac OS X
  - Subsystem:

**Comment by wumpz** [comment]
No plans yet, but there are no show stoppers. So I will release tonight, if there are no problems.

**Comment by AnEmortalKid** [comment]
Thx @wumpz
