### ISSUE TITLE
function object not valid to initialize analytic expression

### ISSUE THREAD

**Issue by huihui1230** [JSQLParser/JSqlParser#817]
I have encountered the following situation： 
    function object not valid to initialize analytic expression
why ？ 
I see that the number of sql function parameters can not be greater than 3. 
But Why?

**Comment by wumpz** [comment]
Is there a function for analytic purposes with more than three parameters? Is it possible to use any function here?

**Comment by wumpz** [comment]
Can you give an example of a valid SQL using there a function with more than three arguments?

**Comment by wumpz** [comment]
So can we close this issue?
