### ISSUE TITLE
NoSuchMethodError: net.sf.jsqlparser.statement.select.PlainSelect.getGroupByColumnReferences()

### ISSUE THREAD

**Issue by MrHeXi** [JSQLParser/JSqlParser#820]
Dear author,when i use version 2.0 or 2.1, getGroupByColumnReferences() was removed,PageHelper(5.1.2) throws that exception. how cloud i solve this problem,thanks.
version 1.4 does not have this problem,but 1.4 not support 'AGAINST'.and  throws ParseException: Encountered " <S_IDENTIFIER> "AGAINST ""  exception

**Comment by wumpz** [comment]
This method was removed within version 2.0. The complete group by handling was now refactored in a new class GroupByElement. To get your group by expressions just use:

`PlainSelect.getGroupBy().getGroupByExpressions`

The refactoring was needed to support grouping sets.

**Comment by MrHeXi** [comment]
thanks ，so i need upgrade PageHelper with using the new ways to solve this problem
