### ISSUE TITLE
ParseException: Encountered unexpected token: "inner" "INNER"

### ISSUE THREAD

**Issue by bruceauyeung** [JSQLParser/JSqlParser#826]
sql: 
~~~
update message_topic inner join message_topic_config on
 message_topic.id=message_topic_config.topic_id 
set message_topic_config.enable_flag='N', 
message_topic_config.updated_by='test', 
message_topic_config.update_at='2019-07-16' 
where message_topic.name='test' 
AND message_topic_config.enable_flag='Y'
~~~
### Expected Behavior
the sql runs well on MariaDB-server-10.1.40-1.el7.centos.x86_64, i expect jsqlparser parses it also well

### Actual Behavior
~~~
net.sf.jsqlparser.JSQLParserException: null
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:43)
	at com.zte.itp.seo.commons.sql.SqlTableNameCaseHandler.handle(SqlTableNameCaseHandler.java:72)
	at com.zte.itp.seo.Main.main(Main.java:214)
Caused by: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "inner" "INNER"
    at line 1, column 22.

Was expecting one of:

    ","
    "ACTION"
    "ANY"
    "AS"
    "BYTE"
    "CASCADE"
    "CAST"
    "CHAR"
    "COLUMN"
    "COLUMNS"
    "COMMENT"
    "COMMIT"
    "DESCRIBE"
    "DO"
    "ENABLE"
    "END"
    "EXTRACT"
    "FIRST"
    "FN"
    "FOLLOWING"
    "INDEX"
    "INSERT"
    "INTERVAL"
    "ISNULL"
    "KEY"
    "LAST"
    "MATERIALIZED"
    "NEXTVAL"
    "NO"
    "NULLS"
    "OPEN"
    "OVER"
    "PARTITION"
    "PATH"
    "PERCENT"
    "PRECISION"
    "PRIMARY"
    "PRIOR"
    "RANGE"
    "REPLACE"
    "ROW"
    "ROWS"
    "SEPARATOR"
    "SET"
    "SIBLINGS"
    "TABLE"
    "TEMP"
    "TEMPORARY"
    "TOP"
    "TRUNCATE"
    "TYPE"
    "UNSIGNED"
    "VALUE"
    "VALUES"
    "XML"
    "ZONE"
    <K_DATETIMELITERAL>
    <K_DATE_LITERAL>
    <S_CHAR_LITERAL>
    <S_IDENTIFIER>
    <S_QUOTED_IDENTIFIER>

	at net.sf.jsqlparser.parser.CCJSqlParser.generateParseException(CCJSqlParser.java:20951)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_consume_token(CCJSqlParser.java:20798)
	at net.sf.jsqlparser.parser.CCJSqlParser.Update(CCJSqlParser.java:745)
	at net.sf.jsqlparser.parser.CCJSqlParser.SingleStatement(CCJSqlParser.java:127)
	at net.sf.jsqlparser.parser.CCJSqlParser.Statement(CCJSqlParser.java:70)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:41)
	... 2 common frames omitted
~~~

### Specifications

  - Version: 2.1
  - Platform: centos 7 64bit
  - Java version: 1.8.0_211

@wumpz

**Comment by bruceauyeung** [comment]
@wumpz would you like take a look ?
thanks !

**Comment by wumpz** [comment]
This syntax **update table1 join table2 ... set ...** is not (yet) supported. PRs are welcome.

**Comment by wumpz** [comment]
At the moment there are no plans to support this. Or is this an urgent request?

**Comment by bruceauyeung** [comment]
@wumpz  it's urgent to me. i have tried SQL parser in Alibaba druid library, it supports table join,
thanks for your effort!

**Comment by wumpz** [comment]
I will look into it.

**Comment by wumpz** [comment]
Sorry, it took a while. Now I am on it.

**Comment by wumpz** [comment]
Could you check it? I changed the version to 3.0-SNAPSHOT due to API changes introduced by the solution of your request.

**Comment by mantou16** [comment]
@wumpz could you please kindly share why getTables() is removed and replaced with getTable(), seems like roll back to the version before 5/25/2014 commit. Thank you!!

**Comment by wumpz** [comment]
@mantou16 this was indeed an API change. So maybe this had to be in version 4. Sorry about that. 

The cause was #826. Now JSqlParser supports not only multiple tables, but joins at the start. (https://github.com/JSQLParser/JSqlParser/commit/01296c302471a9c48eb4599116e86612a126d9a8#diff-609c7e6ed30a0309ddb39397703f93f1)
As you see it is not a step backward but a step forward.

So to get what you want is now a combination of **getTable** + **getStartJoins**.

**Comment by wumpz** [comment]
@mantou16 as you see here: https://github.com/JSQLParser/JSqlParser/blob/678ac96b59481751a4f3ed361e6e97304a298ff3/src/test/java/net/sf/jsqlparser/statement/update/UpdateTest.java#L64
the test for multi table list is still intact.

**Comment by mantou16** [comment]
> @mantou16 as you see here:
> 
> https://github.com/JSQLParser/JSqlParser/blob/678ac96b59481751a4f3ed361e6e97304a298ff3/src/test/java/net/sf/jsqlparser/statement/update/UpdateTest.java#L64
> 
> 
> the test for multi table list is still intact.

got it! thank you so much!!!
