### ISSUE TITLE
Parsing declare statements

### ISSUE THREAD

**Issue by perNyfelt** [JSQLParser/JSqlParser#828]
Are there any plans to support T-SQL declare statements? 
Would a pull request to add support for that be welcome?

### Actual Behavior
```
StringBuffer sql = new StringBuffer()
        .append("declare @extractDate date = (select max(dateExtracted) from creditInformation);\n")
        .append("declare @ciTable table (ciId numeric(19,0));\n")
        .append("insert into @ciTable ")
        .append("select surrogateId as ciId\n")
        .append("from creditInformation\n")
        .append("where dateExtracted = @extractDate");

Statements stmt = CCJSqlParserUtil.parseStatements(sql.toString());
```
Thows: 
Caused by: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "declare" <S_IDENTIFIER>

### Expected Behavior
should be parsed into 3 statements.

### Specifications

  - Version: 
```
    <dependency>
      <groupId>com.github.jsqlparser</groupId>
      <artifactId>jsqlparser</artifactId>
      <version>2.1</version>
    </dependency>
```
  - Platform: Windows 10
  - Subsystem: Java 8

**Comment by perNyfelt** [comment]
Yes it should be a variant of SetStatement. I'll try to implement it and create a PR...

**Comment by perNyfelt** [comment]
Turns out to be quite complicated so I'm giving up. The following 5 variations of Declare exists in SQL Server:

DECLARE @find varchar(30);

DECLARE @find varchar(30) = 'Man%';

DECLARE @Group nvarchar(50), @Sales money;

DECLARE @MyTableVar table(
     EmpID int NOT NULL,
     OldVacationHours int,
     NewVacationHours int,
     ModifiedDate datetime);

 DECLARE @LocationTVP AS LocationTableType;

**Comment by wumpz** [comment]
So why are you closing this issue?

**Comment by perNyfelt** [comment]
Sorry about that. Should have just left this as a comment.

**Comment by wumpz** [comment]
@perNyfelt Started implementing this feature.

**Comment by wumpz** [comment]
Could you check it. I implemented all of your test sql types.

**Comment by perNyfelt** [comment]
Yes, it works fine! Thank you so much!

**Comment by wumpz** [comment]
You were right. It was only at the first sight similar to set. However thx for using Jsqlparser. Cheers Tobias
