### ISSUE TITLE
Not recognize CHARACTER SET in table creation

### ISSUE THREAD

**Issue by macleanliu** [JSQLParser/JSqlParser#829]
When use below table creation DDL, JSqlParser cannot find out the encoding for `name` column.  It only recognizes "NOT NULL" as column spec strings for `name` column . 

CREATE TABLE `test` (
  `id` int(11) NOT NULL,
  `name` varchar(64) **CHARACTER SET GBK** NOT NULL,
  `age` int(11) NOT NULL,
  `score` decimal(8,2) DEFAULT NULL,
  `description` varchar(64) DEFAULT NULL,
  `creationDate` datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

JSqlParser version: 2.1

**Comment by wumpz** [comment]
That is because JSqlParser stores the character set within the column data type and not within the additional parameters:

```
CreateTable stmt = (CreateTable) CCJSqlParserUtil.parse(sql);
ColumnDefinition colName = stmt.getColumnDefinitions().stream()
                .filter(col -> col.getColumnName().equals("name"))
                .findFirst().orElse(null);
assertNotNull(colName);
assertEquals("GBK", colName.getColDataType().getCharacterSet());
```
I introduced a test like this within JSqlParser, as well.

**Comment by macleanliu** [comment]
I got the character set successfully through the test codes. 
Close the issue now,  thank you.
