### ISSUE TITLE
How to deal without NOT attribute for BinaryExpression in version 2.1? (( 

### ISSUE THREAD

**Issue by canatoly** [JSQLParser/JSqlParser#834]
I am forced to stay with 2.0 now. Hope we'll it back soon. Thanx

**Comment by wumpz** [comment]
The **not** was refactored out into a new class that is now used for nearly every **not**:

Therefore `NOT a = b `does not result in a `BinaryExpression` (`EqualTo`) with a not attribute, but in a
`NotExpression ` that encloses a `BinaryExpression` (`EqualTo`).

This is / was an API change. Maybe I should have followed semantic versioning, but I didn't.

So what is the problem using this new structure or was this the needed information?

**Comment by canatoly** [comment]
This information is exactly what I needed. Thank you
