### ISSUE TITLE
With read only is not supported

### ISSUE THREAD

**Issue by weijunlu1** [JSQLParser/JSqlParser#838]
### Actual Behavior
net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "WITH" "WITH"
### Expected Behavior
Support with read only
### Steps to Reproduce the Problem

  1.String sql = CREATE VIEW v14 (c1, c2) AS SELECT c1, C2 FROM t1 WITH READ ONLY;
  1.Statement statement = CCJSqlParserUtil.parse(sql);
  1.Parse failure

### Specifications

  - Version:2.1
  - Platform:window
  - Subsystem:

**Comment by wumpz** [comment]
Isn't the actual syntax **for read only**?

**Comment by weijunlu1** [comment]
The view sql is for read only, but The JSQLParser cann't parse the view sql(create view as select * from t with read only)



junlu.wei@esgyn.cn
 
From: Tobias
Date: 2019-08-09 05:48
To: JSQLParser/JSqlParser
CC: weijunlu1; Author
Subject: Re: [JSQLParser/JSqlParser] With read only is not supported (#838)
Isn't the actual syntax for read only?

**Comment by wumpz** [comment]
I know. You wrote that already within the issues description text. I was wondering if this is syntactically correct, because I only know

`select * from mytable for read only`

Which database uses your syntax?

**Comment by weijunlu1** [comment]
hi，
oracle database has this sql



junlu.wei@esgyn.cn
 
From: Tobias
Date: 2019-08-09 14:27
To: JSQLParser/JSqlParser
CC: weijunlu1; Author
Subject: Re: [JSQLParser/JSqlParser] With read only is not supported (#838)
I know. You wrote that already within the issues description text. I was wondering if this is syntactically correct, because I only know
select * from mytable for read only
Which database uses your syntax?

**Comment by wumpz** [comment]
Aha. So this is not an extension to a subquery but to the view definition itself. I already was thinking about how the plain select parsing of JSqlParser is adapted. In fact it should be the create view rule.

**Comment by wumpz** [comment]
Your view is parsed now. What do you mean by **procedure SQL**? JSqlParser is a SQL parser and not an pl/sql parser.

**Comment by weijunlu1** [comment]
good job，thanks!



junlu.wei@esgyn.cn
 
From: Tobias
Date: 2019-08-10 05:26
To: JSQLParser/JSqlParser
CC: weijunlu1; Author
Subject: Re: [JSQLParser/JSqlParser] With read only is not supported (#838)
Your view is parsed now. What do you mean by procedure SQL? JSqlParser is a SQL parser and not an pl/sql parser.
