### ISSUE TITLE
TableNamesFinder return less tables than it should

### ISSUE THREAD

**Issue by donshop11** [JSQLParser/JSqlParser#84]
considering the following sql (Oracle)

SELECT cid,
 (SELECT name 
  FROM tbl0 
  WHERE tbl0.id = cid) AS name, 
  original_id AS bc_id 
FROM tbl 
WHERE crid = ? 
        AND user_id is null 
START WITH ID = (SELECT original_id 
    FROM tbl2 
    WHERE USER_ID = ?) CONNECT BY prior parent_id = id  AND rownum = 1

Clearly tables involved are "tbl0", "tbl" and "tbl2", 
TableNamesFinder visits only "tbl"

**Comment by santosh-erra** [comment]
Has this bug been fixed,  if yes in which version of JSqlParser?  please let me know

**Comment by wumpz** [comment]
As you see using github, there is a commit, that closes this issue. It is implemented. Use the most recent version of JSqlParser (0.9.2) and it should work. If you need exactly the version at that time, you should consider a git clone til that specific commit.
