### ISSUE TITLE
Oracle UNPIVOT operator

### ISSUE THREAD

**Issue by losserfpv** [JSQLParser/JSqlParser#840]
Hi,
I have parse errors on queries with the UNPIVOT operator in it.
In this project I found some sql scripts with the UNPIVOT operator and these also fail to parse:
- statement/oracle-tests/pivot01.sql
- statement/oracle-tests/pivot04.sql
- statement/oracle-tests/pivot12.sql
I found out that these ones are not in SpecialOracleTest.java. So it looks like these not included in the tests.

**Comment by wumpz** [comment]
Not yet. I got this whole bunch of Oracle tests and try to fix it slowly. However it's a matter of time. Do you want to contribute or support the implementation in other ways. PRS are welcome.

**Comment by losserfpv** [comment]
I'm working on an UNPIVOT implementation right now. I have added some grammer to the JSqlParserCC.jjt. I'm now having compilation errors:

[ERROR] /home/mulder/ijprojects/JSqlParser/target/generated-sources/javacc/net/sf/jsqlparser/parser/CCJSqlParser.java:[5059,16] cannot find symbol
  symbol:   class UnPivotClause
  location: class net.sf.jsqlparser.parser.CCJSqlParser

I'm not sure if I need to generate the new classes somehow or if I need to make them manually in the package net.sf.jsqlparser.statement.select?

**Comment by wumpz** [comment]
The data classes are not generated automatically. For needed interfaces look at pivot operator. Don't forget to implement the deparser. 
Thx for improving Jsqlparser.

**Comment by losserfpv** [comment]
I have added a pull request for this issue. I have activated the already existing test pivot01.sql that proves that the feature is working. 

Unfortunately I have not activated pivot04.sql and pivot12.sql as my fix does not cover these tests yet. When it is fixed for pivot04 it should also be fixed for pivot12.

**Comment by wumpz** [comment]
JSqlParser 4.0 parses this.  I included those missing pivot files.
