### ISSUE TITLE
Matrix of Supported SQL statements

### ISSUE THREAD

**Issue by sivaraam** [JSQLParser/JSqlParser#843]
Hi,

I was just exploring JSqlParser for using it in some projects. It was nice and my preliminary evaluation gave me some idea. I read that special SQL statements of Oracle, SqlServer, MySQL, PostgreSQL are supported. I was curious to know to what extent the support goes. So, I searched for a support matrix but couldn't find any.

It would be nice if there was any way to know the list **list of SQL statements supported** by JSqlParser (including the special ones). Also if such thing is defined, it would nice to know the version compatibility of the various databases (in terms of the SQL statements supported by them, of course).

BTW, thanks for the great work! 🙂

**Comment by wumpz** [comment]
There is no such thing included, except the changelog. Additional to statements there are different SQL dialects, different order of keywords. And so on. 
It will be difficult to get such a matrix. However it is a good idea. Do you want to provide one or make a first version?

**Comment by sivaraam** [comment]
Thanks for the information. I'll see if you could come up with something when I find time.

**Comment by sivaraam** [comment]
For the sake of completion, a page that lists the supported syntax is now available in the library's website: https://jsqlparser.github.io/JSqlParser/syntax.html
