### ISSUE TITLE
LIMIT clause dropped when in appears after OFFSET

### ISSUE THREAD

**Issue by sivaraam** [JSQLParser/JSqlParser#845]
**Describe the bug**
When parsing a query in which the `LIMIT` clause appears **after** the `OFFSET` clause the `LIMIT` clause seems to be dropped i.e, it is not possible to access the LIMIT.

**To Reproduce**
```
    public static void main(String[] args) throws JSQLParserException {
        Statement st =  CCJSqlParserUtil.parse("SELECT * FROM employee ORDER BY emp_id OFFSET 2 LIMIT 10;");
        System.out.println(st);
    }
```

**Expected behavior**
The LIMIT clause is printed in the query:
```
SELECT * FROM employee ORDER BY emp_id OFFSET 2 LIMIT 10
```

**Actual behaviour**
The LIMIT clause is missing from the query:
```
SELECT * FROM employee ORDER BY emp_id OFFSET 2
```

**System**
- Java Version: 11.0.3
- JSqlParser version: 2.1

**Comment by wumpz** [comment]
The fix does not preserve the order of offset and limit. The limit clause comes always first.
