### ISSUE TITLE
Oracle NEXTVAL statement throws parsing exception

### ISSUE THREAD

**Issue by luiznazari** [JSQLParser/JSqlParser#846]
**Describe the bug**
I'm facing exceptions when I try to parse Oracle SQL with `sequence.nextval` statements.

**To Reproduce**
<hr>
1. Example SELECT SQL

```sql
select SEQUENCE_NAME.nextval from dual
```

2. Parsing this SQL using JSqlParser with this statements

```java
net.sf.jsqlparser.parser.CCJSqlParserUtil.parse("sql");
```

3. Exception

> Caused by: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "." "."
>     at line 1, column n.
> 
> Was expecting one of:
> 
>     "&"
>     ","
>     "::"
>     ";"
>     "<<"
>     ">>"
>     "ACTION"
>     "ANY"
>     "AS"
>     "BYTE"
>     "CASCADE"
>     "CAST"
>     "CHAR"
>     "COLLATE"
>     "COLUMN"
>     "COLUMNS"
>     "COMMENT"
>     "COMMIT"
>     "CONNECT"
>     "DESCRIBE"
>     "DO"
>     "ENABLE"
>     "END"
>     "EXCEPT"
>     "EXTRACT"
>     "FIRST"
>     "FN"
>     "FOLLOWING"
>     "FOR"
>     "FROM"
>     "GROUP"
>     "HAVING"
>     "INDEX"
>     "INSERT"
>     "INTERSECT"
>     "INTERVAL"
>     "INTO"
>     "ISNULL"
>     "KEY"
>     "LAST"
>     "MATERIALIZED"
>     "MINUS"
>     "NO"
>     "NULLS"
>     "OPEN"
>     "ORDER"
>     "OVER"
>     "PARTITION"
>     "PATH"
>     "PERCENT"
>     "PRECISION"
>     "PRIMARY"
>     "PRIOR"
>     "RANGE"
>     "REPLACE"
>     "ROW"
>     "ROWS"
>     "SEPARATOR"
>     "SIBLINGS"
>     "START"
>     "TABLE"
>     "TEMP"
>     "TEMPORARY"
>     "TOP"
>     "TRUNCATE"
>     "TYPE"
>     "UNION"
>     "UNSIGNED"
>     "VALUE"
>     "VALUES"
>     "WHERE"
>     "XML"
>     "ZONE"
>     "^"
>     "|"
>     <EOF>
>     <K_DATETIMELITERAL>
>     <K_DATE_LITERAL>
>     <S_CHAR_LITERAL>
>     <S_IDENTIFIER>
>     <S_QUOTED_IDENTIFIER>
> 
> 	at net.sf.jsqlparser.parser.CCJSqlParser.generateParseException(CCJSqlParser.java:20872)
> 	at net.sf.jsqlparser.parser.CCJSqlParser.jj_consume_token(CCJSqlParser.java:20722)
> 	at net.sf.jsqlparser.parser.CCJSqlParser.Statement(CCJSqlParser.java:80)
> 	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:36)
> 	... 25 more

<hr>

1. Example INSERT SQL
```sql
INSERT INTO TABLE_NAME " +
			" (id, random_column)" +
			" VALUES " +
			" (SEQUENCE_NAME.nextval, 'wololo')
```

2. Parsing this SQL using JSqlParser with this statements
```java
net.sf.jsqlparser.parser.CCJSqlParserUtil.parse("sql");
```
3. Exception

> Caused by: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "." "."
>     at line 1, column n.
> 
> Was expecting one of:
> 
>     "&"
>     ")"
>     ","
>     "::"
>     "<<"
>     ">>"
>     "COLLATE"
>     "^"
>     "|"
> 
> 	at net.sf.jsqlparser.parser.CCJSqlParser.generateParseException(CCJSqlParser.java:20872)
> 	at net.sf.jsqlparser.parser.CCJSqlParser.jj_consume_token(CCJSqlParser.java:20722)
> 	at net.sf.jsqlparser.parser.CCJSqlParser.Insert(CCJSqlParser.java:1520)
> 	at net.sf.jsqlparser.parser.CCJSqlParser.SingleStatement(CCJSqlParser.java:132)
> 	at net.sf.jsqlparser.parser.CCJSqlParser.Statement(CCJSqlParser.java:70)
> 	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:36)
> 	... 25 more

<hr>

**Expected behavior**
Successfully parse the SQLs as a `net.sf.jsqlparser.statement.select.Select` and `net.sf.jsqlparser.statement.insert.Insert` instances, respectively.

**System**
- Database you are using: Oracle 11g
- Java Version: 1.8.0_181
- JSqlParser version: 2.0

**Comment by wumpz** [comment]
Thx. Obviously forgot to close it myself.
