### ISSUE TITLE
Queries with Postgres crosstab function could not be parsed

### ISSUE THREAD

**Issue by sivaraam** [JSQLParser/JSqlParser#849]
**Describe the bug**
Trying to parse a query with [crosstab function of Postgres](https://www.postgresql.org/docs/9.2/tablefunc.html) fails.

**To Reproduce**
1. Trying to parse the following query throws an exception.
```
SELECT *
FROM crosstab(
  'select rowid, attribute, value
   from ct
   where attribute = ''att2'' or attribute = ''att3''
   order by 1,2')
AS ct(row_name text, category_1 text, category_2 text, category_3 text);
```
2. Related JSqlParser code:
```
    try {
            Statement selectWithCrosstab = CCJSqlParserUtil.parse(
                    "SELECT *\n" +
                    "FROM crosstab(\n" +
                    "  'select rowid, attribute, value\n" +
                    "   from ct\n" +
                    "   where attribute = ''att2'' or attribute = ''att3''\n" +
                    "   order by 1,2')\n" +
                    "AS ct(row_name text, category_1 text, category_2 text, category_3 text);"
            );
    } catch (JSQLParserException e) {
        e.printStackTrace();
    }
```

**Expected behavior**
It is possible to parse the statement.

**Actual behaviour**
The following exception is thrown:

```
net.sf.jsqlparser.JSQLParserException
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:51)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:40)
	at com.zoho.mickey.sql_parser.TableNameFindExplore.main(TableNameFindExplore.java:226)
Caused by: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "(" "("
    at line 8, column 6.

Was expecting one of:

...
```
**System**
 - Database you are using: Postgres
- Java Version: 11.0.3
- JSqlParser version: 3.0

**Comment by wumpz** [comment]
I think the problem is this multi name alias.

**Comment by sivaraam** [comment]
I don't think `ct(row_name text, category_1 text, category_2 text, category_3 text)` is a multi-name alias. The syntax for the crosstab function extends the usual alias and the parser doesn't seem to be handling this.

Is it possible to make this work?

**Comment by wumpz** [comment]
I will look into it. But not today.
