### ISSUE TITLE
Unsupported "!" in sql ?

### ISSUE THREAD

**Issue by zyplayer** [JSQLParser/JSqlParser#850]
JSqlParser vesion: 3.0

```sql
select * from task_info where id=1 and !(id=1 and id=2)
```

Excetion:
net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "!" "!"
    at line 1, column 40.

Does not support this grammar? Thank you

**Comment by wumpz** [comment]
This is not yet supported, only for primary expressions. I will look into it.

**Comment by wumpz** [comment]
The ! variant of not was already implemented, but it was missing at some relation parts of the grammar. You could use the new version, if you compile it yourself. I could not yet deploy it.

**Comment by zyplayer** [comment]
666  Thank's
