### ISSUE TITLE
Supports eval utility classes.  

### ISSUE THREAD

**Issue by 654894017** [JSQLParser/JSqlParser#852]
Supports eval utility classes.? 
For example:
 // between 
  Assert.assertEquals(false, SQLEvalVisitorUtils.evalExpr(JdbcConstants.MYSQL, "? between 1 and 3", 0));
  Assert.assertEquals(true, SQLEvalVisitorUtils.evalExpr(JdbcConstants.MYSQL, "? between 1 and 3", 2));

  // not between
  Assert.assertEquals(true, SQLEvalVisitorUtils.evalExpr(JdbcConstants.MYSQL, "? not between 1 and 3", 0));
  // case when
  Assert.assertEquals(111, SQLEvalVisitorUtils.evalExpr(JdbcConstants.MYSQL, "case ? when 0 then 111 else 222 end", 0));
  
  // in 
  Assert.assertEquals(true, SQLEvalVisitorUtils.evalExpr(JdbcConstants.MYSQL, "? NOT IN (1, 2, 3)", 0));
  Assert.assertEquals(false, SQLEvalVisitorUtils.evalExpr(JdbcConstants.MYSQL, "? IN (1, 2, 3)", 0));
  
  // is null
  Assert.assertEquals(false, SQLEvalVisitorUtils.evalExpr(JdbcConstants.MYSQL, "? is null", 0));
  Assert.assertEquals(true, SQLEvalVisitorUtils.evalExpr(JdbcConstants.MYSQL, "? is null", (Object) null));
  
  // right function
  Assert.assertEquals("rbar", SQLEvalVisitorUtils.evalExpr(JdbcConstants.MYSQL, "right('foobarbar', 4)"));
  
  // instr function
  Assert.assertEquals(4, SQLEvalVisitorUtils.evalExpr(JdbcConstants.MYSQL, "instr('foobarbar', 'bar')"));

**Comment by wumpz** [comment]
JSqlParser does not (yet) support this. However within the wiki (https://github.com/JSQLParser/JSqlParser/wiki/Example-of-expression-evaluation) there is a simple expression evaluator. This could be a good start. I have to keep in mind, that function like instr, right has to be implemented. 
Pull requests are wellcome. But this would not be a 5 minute task. 

What is **JdbcConstants.MYSQL** provided for?
