### ISSUE TITLE
CREATE/ALTER/DROP SCHEMA

### ISSUE THREAD

**Issue by robert-egan-305** [JSQLParser/JSqlParser#855]
Is there any interest in support for the CREATE/ALTER/DROP SCHEMA commands?

**Comment by wumpz** [comment]
Sure. PRs are welcome.

**Comment by robert-egan-305** [comment]
Have started work. Probably won't have anything PR quality for a few days.

**Comment by wumpz** [comment]
If you need any help, feel free to ask. However all PRs are reviewed so you could create a pull request from a potentially unfinished commit. After that I will do a squash and merge to avoid seeing those multiple commits within the history.

**Comment by robert-egan-305** [comment]
Question. I have a comma separated list of schema names. It looks like
AList() would be perfect, except the list is not surrounded by
parenthesis. RelObjectNameList() looks good, except I'm pretty sure schema
names do not include a dot. Is there a construct for this already, because
I cannot seem to see one.

**Comment by robert-egan-305** [comment]
Apologies. Alist contains extra tokens like S_LONG and S_DOUBLE. My
requirement is
<S_IDENTIFIER> ("," <S_IDENTFIER>)*

**Comment by robert-egan-305** [comment]
I had some issues with github. I am attaching the files here instead.

It seems there is no ANSI specification for ALTER SCHEMA, although a few vendors do support some form of it. Additionally, there are many sub-expressions in CREATE SCHEMA that are not yet supported by this parser.

<schema element> ::=
      <table definition> 
  |   <view definition> 
  |   <domain definition> 
  |   <character set definition> 
  |   <collation definition> 
  |   <transliteration definition> 
  |   <assertion definition> 
  |   <trigger definition> 
  |   <user-defined type definition> 
  |   <user-defined cast definition> 
  |   <user-defined ordering definition> 
  |   <transform definition> 
  |   <schema routine> 
  |   <sequence generator definition> 
  |   <grant statement> 
  |   <role definition> 

And this section will need to be updated as support for these components is added.

[CreateSchema.zip](https://github.com/JSQLParser/JSqlParser/files/3767958/CreateSchema.zip)

**Comment by gvdelst** [comment]
Any further support planned for ALTER statements?

**Comment by wumpz** [comment]
I am sorry but I completly missed @robert-egan-305 additions.

**Comment by wumpz** [comment]
I am on it. However for further additions you should use GitHub.

**Comment by robert-egan-305** [comment]
I am not going to contribute any more. But thank you for indulging me. It
was an enlightening experience.

Regards,
Robert Egan
