### ISSUE TITLE
Cannot parse window function with named windows 

### ISSUE THREAD

**Issue by sivaraam** [JSQLParser/JSqlParser#863]
## Describe the bug
The PostgreSQL and MySQL databases allow users to give an alias for a window specification which can be after the OVER clause instead of the window specification. This allows users to avoid redundantly specifying the window in multiple places in a query. The parser is unable to parse queries containing the `WINDOW` clause.

**References**
* [WINDOW Clause - PostgreSQL documentation](https://www.postgresql.org/docs/9.1/sql-select.html#SQL-WINDOW)
* [Window Function Calls - PostgreSQL documentation](https://www.postgresql.org/docs/9.1/sql-expressions.html#SYNTAX-WINDOW-FUNCTIONS)
* [Window Functions - PostgreSQL tutorial](https://www.postgresql.org/docs/9.1/tutorial-window.html)
* [Named Windows - MySQL documentation](https://dev.mysql.com/doc/refman/8.0/en/window-functions-named-windows.html)

## To Reproduce
1. Example SQL
```sql
SELECT type, day, MIN(days_since_previous) days_since_previous FROM (
    SELECT 
        type, 
        day,
        (COUNT(*) OVER win = 2) valid,
        (last_value(day) OVER win - first_value(day) OVER win) as days_since_previous  
    FROM weather
    WINDOW win AS (PARTITION BY type ORDER BY day ROWS BETWEEN 1 PRECEDING AND CURRENT ROW)
```
2. Parsing this SQL using JSqlParser with this statements
```java
        try {
            Statement st = CCJSqlParserUtil.parse("SELECT type, day, MIN(days_since_previous) days_since_previous FROM (\n" +
                    "    SELECT \n" +
                    "        type, \n" +
                    "        day,\n" +
                    "        (COUNT(*) OVER win = 2) valid,\n" +
                    "        (last_value(day) OVER win - first_value(day) OVER win) as days_since_previous  \n" +
                    "    FROM weather\n" +
                    "    WINDOW win AS (PARTITION BY type ORDER BY day ROWS BETWEEN 1 PRECEDING AND CURRENT ROW)\n"
            );
        } catch (JSQLParserException e) {
            e.printStackTrace();
        }

```
3. Exception
```
net.sf.jsqlparser.JSQLParserException
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:51)
...
Caused by: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "OVER" "OVER"
    at line 5, column 19.

Was expecting one of:

    "&"
    ")"
    "."
    "::"
    "<<"
    ">>"
    "COLLATE"
    "["
    "^"
    "|"
...
```

**Expected behavior**
It should possible to parse a query with a WINDOW clause.

## System
- Database you are using: PostgreSQL, MySQL
- Java Version 11.0.3
- JSqlParser version: 3.0

**Comment by manticore-projects** [comment]
1) a closing bracket is missing at the end
2) `ROWS BETWEEN 1 PRECEDING AND CURRENT ROW` is the problematic/unsupported part.

[The rest works fine with JSQLParser 4.7](http://jsqlformatter.manticore-projects.com/jsqlformatter/demo.html?args=-c%20MoUQMiDCAqAEAuBPADgUwDSwCYENGYFkBJAOQApdEBnAfSoEsA7AY1RuQCdUA3egewCuVAJTY8tBizace-IbABiAJQDyBWGQBQsHbFAQYsbbpNI0mYyZ2V0lq2UgqAqiWhkAVKJUA1EEtgA7kywALywAEyi3DgANvRYtla6ZDE4VPA00TECqBR4Xr7+QYywALSwAGb0HOmZsTl5iAV+gUyiaWLUdEys7Fy8glQ6dspqgag48AAWqBx2AOqkACIq860lAILAGgAKG0rQRIcqJLAAQgCaCCiosCpKSy2XncLCQA)
