### ISSUE TITLE
Cannot parse queries which has a PARTITION BY clause with parentheses surrounding multiple column names

### ISSUE THREAD

**Issue by sivaraam** [JSQLParser/JSqlParser#865]
## Describe the bug
It is not possible to parse a query which has a `PARTITION BY` clause with parentheses surrounding multiple column names. Corresponding queries without parentheses surrounding multiple column names works without issues.

## To Reproduce
1. Example SQL
It is **not possible** to parse the following query with the parser:
    ```sql
    select subject_id, student_id, sum(mark) over (partition by (subject_id, student_id)) from marks;
    ```
    ... but it is **possible** to parse the following query, which is the query above query without parentheses surrounding the column names in the `PARTITION BY` clause.
    ```sql
    select subject_id, student_id, sum(mark) over (partition by subject_id, student_id) from marks;
    ```
    and it is also **possible** to successfully parse a query which has a *single column* in the `PARTITION BY` clause surrounded by parentheses.
    ```sql
    select subject_id, student_id, sum(mark) over (partition by (subject_id)) from marks;
    ```

2. Parsing this SQL using JSqlParser with this statements
```java
        try {
            Statement st = CCJSqlParserUtil.parse(
                    "select subject_id, student_id, sum(mark) over (partition by (subject_id, student_id)) from marks;"
            );
        } catch (JSQLParserException e) {
            e.printStackTrace();
        }
```
3. Exception
```
net.sf.jsqlparser.JSQLParserException
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:51)
...
Caused by: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "," ","
    at line 1, column 72.

Was expecting one of:

    "&"
    ")"
    "::"
    "<<"
    ">>"
    "COLLATE"
    "["
    "^"
    "|"
```

**Expected behavior**
It should be possible to successfully parse queries containing parentheses surrounding multiple column names in the `PARTITION BY` clause.

## System
- Database you are using: MySQL, Postgres and MS SQL Server.
- Java Version: 11.0.3
- JSqlParser version: 3.0

**Comment by wumpz** [comment]
Looking at https://www.postgresql.org/docs/10/sql-expressions.html#SYNTAX-WINDOW-FUNCTIONS there is written:

> where window_definition has the syntax
> 
> [ existing_window_name ]
> [ PARTITION BY expression [, ...] ]
> [ ORDER BY expression [ ASC | DESC | USING operator ] [ NULLS { FIRST | LAST } ] [, ...] ]
> [ frame_clause ]

Therefore a parenthesis around multiple **partition by** expressions should not be allowed. However PostgreSQL does indeed accept it. 

I will look into it.

**Comment by sivaraam** [comment]
That's interesting. I happened to notice a similar case with the GROUP BY clause. Postgres allows to wrap the multiple columns in the GROUP BY clause with parentheses. But other databases like MySQL and MS SQL server don't allow it.
