### ISSUE TITLE
Incorrect interpretation of double quotes escaped within double quotes

### ISSUE THREAD

**Issue by sivaraam** [JSQLParser/JSqlParser#870]
## Describe the bug
In Postgres and MS SQL server, it is possible for column (or) table names to have double quotes. This can be given in the query by wrapping column (or) table name within double quotes and escaping the double quotes in the name by using two double quotes ("") as follows:
```sql
select "col""name" from table
```
The parser incorrectly interprets this as two strings. So, `"name"` is interpreted as an alias of `"col"`.

In MySQL too it is possible to escape double quotes within double quotes even when double quotes is considered to be used for strings.

## To Reproduce
1. Example SQL
```sql
select "col""name" from table
```
2. Parsing this SQL using JSqlParser with this statements
```java
        try {
            Statement st = CCJSqlParserUtil.parse("select \"col\"\"name\" from table");
        }
        catch (JSQLParserException jsqle) {
            jsqle.printStackTrace();
            Assertions.fail();
        }
```

**Expected behavior**
The escaped double quote should be interpreted properly and `"col""name"` should be interpreted as a column name.

## System
- Database you are using: Postgres, MS SQL Server and MySQL
- Java Version: 11.0.3
- JSqlParser version: 8.0

**Comment by wumpz** [comment]
I know the parsing behaviour here is very problematic because Jsqlparser wants to support escaping by doubling and by backslash. Til now I was not able to make it optional.

**Comment by sivaraam** [comment]
Sorry, but I do not follow. Do you mean the parser already supports escaping by doubling? (OR) do you mean you couldn't figure out how to support escaping both by doubling and by using backslash?

**Comment by wumpz** [comment]
The second. It supports both but there are problems with that.

**Comment by manticore-projects** [comment]
Greetings.

[Works with JSQLParser 4.7](http://jsqlformatter.manticore-projects.com/jsqlformatter/demo.html?args=-c%20MoUQMiDCAqAEBEBjA9gG3vAdgQwLYFN4AoAMQCUB5AWVgBdsAjVfIgbiA)

So I am closing this.
