### ISSUE TITLE
if I use that sql,I can not get the right  pair return

### ISSUE THREAD

**Issue by cristicmf** [JSQLParser/JSqlParser#871]
**Describe the bug**

if I use that sql,I can not get the right return
String sql = "SELECT * FROM  mytable WHERE temperate > 40 AND temperate < 50";

**To Reproduce**

if I use that sql,I can not get the right return

`String sql = "SELECT * FROM  mytable WHERE temperate > 40 AND temperate < 50";
        Statement stmnt = CCJSqlParserUtil.parse(sql);

        final Stack<Pair<String, String>> params = new Stack<Pair<String, String>>();
        stmnt.accept(new StatementVisitorAdapter() {
            @Override
            public void visit(Select select) {
                select.getSelectBody().accept(new SelectVisitorAdapter() {
                    @Override
                    public void visit(PlainSelect plainSelect) {
                        plainSelect.getWhere().accept(new ExpressionVisitorAdapter() {
                            @Override
                            protected void visitBinaryExpression(BinaryExpression expr) {
                                if (!(expr instanceof AndExpression)) {
                                    params.push(new Pair<String, String>(null, null));
                                }
                                super.visitBinaryExpression(expr);
                            }

                            @Override
                            public void visit(Column column) {
                                params.push(new Pair<String, String>(column.getColumnName(), params.
                                        pop().getRight()));
                            }

                            @Override
                            public void visit(JdbcNamedParameter parameter) {
                                params.
                                        push(new Pair<String, String>(params.pop().getLeft(), parameter.
                                                getName()));
                            }
                        });
                    }
                });
            }
        });

        log.info("param:{}", params.size());
        int len =  params.size();
        for (int t = 0; t <len; t++) {
            Pair<String, String> param = params.pop();
            log.info("t:{},param:{}", t, param.toString());
        }

`

**Expected behavior**

print...
param:2
param:Pair{left=temperate, right=null}
param:Pair{left=temperate, right=null}

I think the right ,should be
print...
param:2
param:Pair{left=temperate, right=50}
param:Pair{left=temperate, right=40}

**System**
 - Database you are using  mysql
- Java Version  java8
- JSqlParser version      compile group: 'com.github.jsqlparser', name: 'jsqlparser', version: '3.0'

**Comment by wumpz** [comment]
You simply missing to override another method:

```
@Override
public void visit(LongValue value) {
       params.push(new MutablePair<String, String>(params.pop().getLeft(), value.toString()));
}
```

**40** is a **LongValue** and not a **JDBCNamedParameter**.
