### ISSUE TITLE
how to get a priority from a sql 

### ISSUE THREAD

**Issue by cristicmf** [JSQLParser/JSqlParser#872]
**Describe the bug**
how to get a priority from a sql 

**To Reproduce**

`select * from mytable where a>10 and b>1 and c>100 or d>10 or e>4  `

such `a>10 and b>1 and c>100 ` priority higher than `d>10 or e>4 `

which part can provide the function?

**Expected behavior**

**System**
 - Database you are using
- Java Version
- JSqlParser version

**Comment by wumpz** [comment]
JSqlParser builds an object tree that is ordered exactly for this priority. The computation should go from the leaves to the root of the tree.

**Comment by cristicmf** [comment]
would you mind give me a demo. thx

**Comment by wumpz** [comment]
Here is a little example doing this for addition and multiplication: https://github.com/JSQLParser/JSqlParser/wiki/Example-of-expression-evaluation

**Comment by wumpz** [comment]
So was this enough help? Can we close this issue?
