### ISSUE TITLE
JSqlParser cannot recognize \'

### ISSUE THREAD

**Issue by yanbeipang** [JSQLParser/JSqlParser#875]
**Describe the bug**
Got JSQLParserException when parsing the following SQLs:

**To Reproduce**
Cannot parse:
insert into standard_table(gmt_create, gmt_modified, config_name, standard_code) values (now(), now(),  null, 'if
    @fac.sql_type in
     [ \'UPDATE\',\'DELETE\',\'INSERT\',\'INSERT_SELECT\']
	then
   	 	@act.allow_submit
	end
');

Will work:
insert into standard_table(gmt_create, gmt_modified, config_name, standard_code) values (now(), now(),  null, 'if
    @fac.sql_type in
     [ "UPDATE","DELETE","INSERT","INSERT_SELECT"]
	then
   	 	@act.allow_submit
	end
');

**Expected behavior**

**System**
 - Database you are using
MySQL
- Java Version
Unimportant
- JSqlParser version
2.1

**Comment by manticore-projects** [comment]
Greetings!

You will need to escape the single Quotes `'` inside your `Character Literal` either SQL:2016 compliant with `''` or lenient with `\'` and `backslashEscaping` activated. Please note that the later depends on PR #1715.

Example
```java
        String sqlStr="insert into standard_table(gmt_create, gmt_modified, config_name, standard_code) values (now(), now(), null, 'if \n"
                      + "@fac.sql_type in \n"
                      + "[ ''UPDATE'', ''DELETE'', ''INSERT'', ''INSERT_SELECT''] \n"
                      + "then \n"
                      + "@act.allow_submit \n"
                      + "end \n"
                      + "')"
                      ;
        TestUtils.assertSqlCanBeParsedAndDeparsed(
                sqlStr
                , true
                , parser -> parser.withBackslashEscapeCharacter(false)
        );

        sqlStr="insert into standard_table(gmt_create, gmt_modified, config_name, standard_code) values (now(), now(), null, 'if \n"
                      + "@fac.sql_type in \n"
                      + "[ \\'UPDATE\\', \\'DELETE\\', \\'INSERT\\', \\'INSERT_SELECT\\'] \n"
                      + "then \n"
                      + "@act.allow_submit \n"
                      + "end \n"
                      + "')"
                ;
        TestUtils.assertSqlCanBeParsedAndDeparsed(
                sqlStr
                , true
                , parser -> parser.withBackslashEscapeCharacter(true)
        );
```
