### ISSUE TITLE
JSqlParser cannot parser impala grammar "show create table"

### ISSUE THREAD

**Issue by ZzzHzzZ** [JSQLParser/JSqlParser#883]
JSqlParser cannot parse impala grammar "show create table"
For example
`String sql = "show create table a.b";
        net.sf.jsqlparser.statement.Statement statement = CCJSqlParserUtil.parse(sql);`
Comes with:
`Caused by: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "create" "CREATE"
    at line 1, column 6.

Was expecting one of:

    "ACTION"
    "ANY"
    "BYTE"
    "CASCADE"
    "CAST"
    "CHAR"
    "COLUMN"
    "COLUMNS"
    "COMMENT"
    "COMMIT"
    "DESCRIBE"
    "DO"
    "DOUBLE"
    "DUPLICATE"
    "ENABLE"
    "END"
    "EXTRACT"
    "FALSE"
    "FIRST"
    "FN"
    "FOLLOWING"
    "IF"
    "INDEX"
    "INSERT"
    "INTERVAL"
    "ISNULL"
    "KEY"
    "LAST"
    "LEFT"
    "LIMIT"
    "MATERIALIZED"
    "NEXTVAL"
    "NO"
    "NULLS"
    "OFFSET"
    "OPEN"
    "OPTIMIZE"
    "OVER"
    "PARTITION"
    "PATH"
    "PERCENT"
    "PRECISION"
    "PRIMARY"
    "PRIOR"
    "RANGE"
    "READ"
    "REPLACE"
    "RIGHT"
    "ROW"
    "ROWS"
    "SEPARATOR"
    "SET"
    "SIBLINGS"
    "TABLE"
    "TEMP"
    "TEMPORARY"
    "TOP"
    "TRUE"
    "TRUNCATE"
    "TYPE"
    "UNSIGNED"
    "VALUE"
    "VALUES"
    "XML"
    "ZONE"
    <K_DATETIMELITERAL>
    <K_DATE_LITERAL>
    <S_IDENTIFIER>
    <S_QUOTED_IDENTIFIER>

	at net.sf.jsqlparser.parser.CCJSqlParser.generateParseException(CCJSqlParser.java:21726)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_consume_token(CCJSqlParser.java:21573)
	at net.sf.jsqlparser.parser.CCJSqlParser.RelObjectNameExt(CCJSqlParser.java:3213)
	at net.sf.jsqlparser.parser.CCJSqlParser.Show(CCJSqlParser.java:803)
	at net.sf.jsqlparser.parser.CCJSqlParser.SingleStatement(CCJSqlParser.java:200)
	at net.sf.jsqlparser.parser.CCJSqlParser.Statement(CCJSqlParser.java:75)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:49)
	... 2 more
Caused by:
net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "create" "CREATE"
    at line 1, column 6.`

version is 3.0

**Comment by wumpz** [comment]
At the moment only 

    show mytable
    show columns from mytable

are supported.

**Comment by manticore-projects** [comment]
Works with 4.7 Snapshot, [you can test it here.](http://jsqlformatter.manticore-projects.com/jsqlformatter/demo.html?args=-c%20MoCQ8g6gBAxgTgUwIYBcFRUgRgG3UgOiwCgBuIA)
