### ISSUE TITLE
Column is final - can Column not be final?

### ISSUE THREAD

**Issue by lscoughlin** [JSQLParser/JSqlParser#885]
net.sf.jsqlparser.schema.Column is final.  I would be really psyched if it were _not_ final :)

**Comment by wumpz** [comment]
Psyched? ;) 
Why should it be non final? Do you want to hold more data within those data clases?

**Comment by lscoughlin** [comment]
I do actually.  For a thing I'm working on, I would like to be able to mix jooq like generated queries static sql and pass them through the same validation and enhancement framework/direction framework, and I would like to use this project for that.  But _doing_ some of this stuff isnt' really jsqlparser's job, so i would like to be able to extend the classes to have them do more things in another context - if that makes sense.

**Comment by wumpz** [comment]
Agreed. Since **Table** isn't final as well I will accept it.
