### ISSUE TITLE
MySQL ' where columnName not regexp '*'' clause doesn't work.

### ISSUE THREAD

**Issue by zyh12** [JSQLParser/JSqlParser#887]
It throws 'Encountered unexpected token: not' exception when parsing this clause. I tried v1.4, v2.1, v3.0, but nothing helped.

**Comment by wumpz** [comment]
Please provide a complete test sql.

**Comment by zyh12** [comment]
> Please provide a complete test sql.

`select * from t_test where  c_test not regexp '[0-9]{18}|[0-9]{17}X|[0-9]{15}';`
