### ISSUE TITLE
it seems that JSqlParser don't support mysql  LPAD function

### ISSUE THREAD

**Issue by Eternalisland** [JSQLParser/JSqlParser#888]
**Describe the bug**
**select  LPAD(@rn := @rn + 1, 5, '0') AS POSNR from DOC_ORDER_HEADER ,this sql work well in mysql ,but JSqlParser don't support it .** 

**To Reproduce**
1. Example SQL  
 **select  LPAD(@rn := @rn + 1, 5, '0') AS POSNR from DOC_ORDER_HEADER**
2. Parsing this SQL using JSqlParser with this statements  
**CCJSqlParserUtil.parse(“select  LPAD(@rn := @rn + 1, 5, '0') AS POSNR from DOC_ORDER_HEADER”)**
3. Exception
**Encountered " "(" "( "" at line 1, column 13.**

**Expected behavior**

**System**
 - Database you are using  mysql
- Java Version 1.8
- JSqlParser version jsqlparser-1.1

**Comment by wumpz** [comment]
Jsqlparser dies not support this variable assignment expression within it.

**Comment by greensland** [comment]
Not supported for if function

**Comment by wumpz** [comment]
@greensland I could not understand your comment.

**Comment by wumpz** [comment]
JSqlParser 4.0 parses this.
