### ISSUE TITLE
Mysql ParseException: Encountered unexpected token: "(" "("

### ISSUE THREAD

**Issue by FamousCodee** [JSQLParser/JSqlParser#889]
**Describe the bug**

**To Reproduce**
1. Example SQL
my sql have many keys :
`category` INT(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '订单类别',
    PRIMARY KEY (`order_id`),
    KEY `user_id` (`user_id`),
    KEY `p_order_id` (`p_order_id`),
    KEY `pickup_id` (`pickup_id`),
    KEY `add_time` (`add_time`),
    KEY `i_e` (`express_sn`),
    KEY `i_os_oi_ei_pi` (`order_status` , `order_id` , `express_id` , `pickup_id`),
    KEY `idx_ttl` (`ttl`),
    KEY `ix_order_flow` (`order_flow`),
    KEY `consignee` (`consignee`),
    KEY `ix_tel` (`tel` (10)),
    KEY `idxw_c` (`consignee`),
    KEY `idx_order_type` (`order_type`),
    KEY `idx_sales_type` (`sales_type`),
    KEY `idx_acc_f_os` (`order_status` , `order_flow` , `wms_acc`),
    KEY `idx_s_p` (`order_status` , `push_time`),
    KEY `idx_country_name` (`country_name`),
    KEY `idx_order_from` (`order_from`),
    KEY `idx_close_time` (`close_time`),
    KEY `idx_update_time` (`update_time`),
    KEY `idx_pay_time` (`pay_time`),
    KEY `idx_related_order_id` (`related_order_id`),
    KEY `idx_sg_order_email` (`email`),
    KEY `idx_tel_idx` (`tel_idx`),
    KEY `idx_consignee_idx` (`consignee_idx`),
    KEY `top_order_id_idx` (`top_order_id`),
    KEY `idx_at_cn_wn` (`add_time` , `country_name` , `wms_name`),
    KEY `idx_pt_cn_wn` (`pay_time` , `country_name` , `wms_name`),
    KEY `email_idx` (`email_idx`),
    KEY `idx_trade_id` (`trade_id`)

2. Parsing this SQL using JSqlParser with this statements
use parse will throw exception:
net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "(" "("
    at line 84, column 25.

Was expecting one of:

    ")"
    ","
3. Exception

**Expected behavior**
when my sql have many keys , it will throws exception
when i detele keys , reverse primary key. it works
why?
**System**
 - Database you are using
- Java Version
- JSqlParser version

**Comment by manticore-projects** [comment]
(Works with JSQLParser 4.7](http://jsqlformatter.manticore-projects.com/jsqlformatter/demo.html?args=-c%20MYJwpghgLmAEUQEYBs4wM5VgCgFDGjAHMB7EAT1gEkA5AFWwEYAGASlgFUaBlKgcRoBRACKwaAeTpiOAGRmxhggGIBBWVIDkzDbADC4gLIHB9WBsBF0YFVlQN4+gaiUNAGlwAFAEpUDK1wE1YAaUFfbDIAEzAQAH0ASxDWJwDfAFd0cOiQnGTUmLjcBNgABwjQrPTsQuLI7PjAgqjgAGtEwpicfLrG5tjq3wgQkIioKIBbOGxe-sGRnLyoiNGwAA988HR0CPQAO2ma2ZI1klmwWbacCvWEKGTYB1gzlpvF5bBVtOvahqa07d8YhYGoZA4KAA76wKJ-M4AM2QJAA7qcQGFItC4aDgCQNugokQNmBRujMdjcWBQeCBmBAdgYJSWKxSSEFrCIsAcASsTi8fSIYjUlByPlRmc+QKuesIKg1sLRuhxc8BvySd0wQyIhBgMAIpCiugEUjztArjcoTD4TdYUM1mrgKK1vldalMAadTd8skABYDYaK3I7FXoxIbKAUCIbCAjVkkANB8ghsPemYqqEgEhDe3I5NDUXAGEpT3h7DZvZgPPx31-JohQgljL5SswEui-IQGOTUZNlte0XgZCEfp3Urd3tFHmVLo+n4q9BEYd6sBDCBRSlzhfIUXUtILIEUjdZjHs4kbiOEjnF36gqAkcojtKHqmXmclUXQZkbCKwjY4cbVm7+wPB0PhmaFqxlMSq-BE+RQC+b4fmUzbfrAv7RiBcBAWsAGlr4y6Lre2HIDuYEqkGvSnqUxFhF8uCsEAA)
