### ISSUE TITLE
It can't parse the schema name in the "case" part witch the column name contains catalog and schema.

### ISSUE THREAD

**Issue by esg-guoqing** [JSQLParser/JSqlParser#894]
**Describe the bug**
The statement:
SELECT TRAFODION.USER1.EMP.ENAME, CASE TRAFODION.USER1.EMP.ENAME ||
    TRAFODION.USER1.EMP.EMPNO WHEN '091' THEN '2' ELSE '1' END AS C11 FROM
    TRAFODION.USER1.EMP ;
In this case, the TRAFODION is catalog, the USER1 is schema name. When I try to replace the schema name from "USER1" to "XXX".  The schema name in the part of  "case"  will not be replaced.

The table ddl:
CREATE TABLE TRAFODION.USER1.EMP
  ( 
    ENAME                            VARCHAR(10 BYTES) CHARACTER SET UTF8
      COLLATE DEFAULT DEFAULT NULL NOT SERIALIZED
  , EMPNO                            VARCHAR(10 BYTES) CHARACTER SET UTF8
      COLLATE DEFAULT DEFAULT NULL NOT SERIALIZED
  , SAL                              NUMERIC(7, 2) DEFAULT NULL NOT SERIALIZED
  );
The view ddl:
CREATE OR REPLACE VIEW TRAFODION.USER1.V_EMP (ENAME, C11) AS
  SELECT TRAFODION.USER1.EMP.ENAME, CASE TRAFODION.USER1.EMP.ENAME ||
    TRAFODION.USER1.EMP.EMPNO WHEN '091' THEN '2' ELSE '1' END AS C11 FROM
    TRAFODION.USER1.EMP ;

**To Reproduce**
1. Example SQL:  
SELECT TRAFODION.USER1.EMP.ENAME, CASE TRAFODION.USER1.EMP.ENAME ||
    TRAFODION.USER1.EMP.EMPNO WHEN '091' THEN '2' ELSE '1' END AS C11 FROM
    TRAFODION.USER1.EMP ;

2. Replace "USER1" using "XXX"；
3.The result:
SELECT TRAFODION.XXX.EMP.ENAME, CASE TRAFODION.USER1.EMP.ENAME || TRAFODION.USER1.EMP.EMPNO WHEN '091' THEN '2' ELSE '1' END AS C11 FROM TRAFODION.XXX.EMP；

**Expected behavior**
Expect sql:
SELECT TRAFODION.XXX.EMP.ENAME, CASE TRAFODION.XXX.EMP.ENAME || TRAFODION.XXX.EMP.EMPNO WHEN '091' THEN '2' ELSE '1' END AS C11 FROM TRAFODION.XXX.EMP；

**System**
 - Database: apache trafodion
- Java Version: 1.8
- JSqlParser version: 3.1

**Comment by wumpz** [comment]
I am not sure, if I understand your problem. Do you try to replace one part within an sql and expecting JSqlParser replaces the rest?

**Comment by esg-guoqing** [comment]
> I am not sure, if I understand your problem. Do you try to replace one part within an sql and expecting JSqlParser replaces the rest?

Sorry, maybe I expressed not well!  Yeah! I hope JSqlParser replaces all the part like "TRAFODION.USER1.EMP" to "TRAFODION.XXX.EMP" in the select statement.Thanks!

**Comment by wumpz** [comment]
So what code do you use replacing this schema name? Do you modify a deparser for this visitor stuff?

**Comment by esg-guoqing** [comment]
I don't know if it is easy to modify, I just make a suggestion.
Thanks!
Here's a code example :
`
import java.util.ArrayList;
import java.util.List;
import net.sf.jsqlparser.JSQLParserException;
import net.sf.jsqlparser.expression.Expression;
import net.sf.jsqlparser.parser.CCJSqlParserUtil;
import net.sf.jsqlparser.schema.Column;
import net.sf.jsqlparser.schema.Table;
import net.sf.jsqlparser.statement.Statement;
import net.sf.jsqlparser.statement.select.FromItem;
import net.sf.jsqlparser.statement.select.PlainSelect;
import net.sf.jsqlparser.statement.select.Select;
import net.sf.jsqlparser.statement.select.SelectExpressionItem;
import net.sf.jsqlparser.statement.select.SelectItem;

public class sqlparser {

	public static void main(String[] args) throws JSQLParserException {
		//Create the object
		Sql sql = new Sql();
		
		//Set the text which need to be parser
		sql.setText("SELECT TRAFODION.USER1.EMP.ENAME, CASE TRAFODION.USER1.EMP.ENAME || " + 
				"TRAFODION.USER1.EMP.EMPNO WHEN '091' THEN '2' ELSE '1' END AS C11 FROM " + 
				"TRAFODION.USER1.EMP");
		sql.setTable(new ArrayList<Table>());
		
		//Print the text before parsing
		//SELECT TRAFODION.USER1.EMP.ENAME, CASE TRAFODION.USER1.EMP.ENAME || TRAFODION.USER1.EMP.EMPNO WHEN '091' THEN '2' ELSE '1' END AS C11 FROM TRAFODION.USER1.EMP
		System.out.println(sql.getText());
		
		//Create the parser object by JSqlParser
		Statement statement = CCJSqlParserUtil.parse(sql.getText());
		
		//Get the select statement
		Select select = (Select) statement;
		PlainSelect body = (PlainSelect)select.getSelectBody();
		
		//Part of from statement
		FromItem fromItem = body.getFromItem();
		if (fromItem instanceof Table) {
			sql.getTables().add((Table) fromItem);
		}
		
		//Part of the columns in select statement
		List<SelectItem> selectItems = body.getSelectItems();
		if (selectItems != null) {
			for (SelectItem item : selectItems) {
				if (item instanceof SelectExpressionItem) {
					SelectExpressionItem slectItem = (SelectExpressionItem) item;
					Expression expression = slectItem.getExpression();
					if(expression instanceof Column) {
						Table table = ((Column)expression).getTable();
						if(table != null) {
							sql.getTables().add(table);
						}
					}
				}
			}
		}
		
		//Change the schema name
		sql.setSchemaName("XXX");
		
		//Update the schema name in parser object
		List<Table> tableList = sql.getTables();
		if(tableList != null) {
			for(Table table : tableList) {
				String schemaName = table.getSchemaName();
				if(schemaName != null && !"".equals(schemaName)
						&& !schemaName.equalsIgnoreCase(sql.getSchemaName())) {
					table.setSchemaName(sql.getSchemaName());
				}
			}
			//Result: 
			sql.setText(statement.toString());
			System.out.println(sql.getText());
			//SELECT TRAFODION.XXX.EMP.ENAME, CASE TRAFODION.USER1.EMP.ENAME || TRAFODION.USER1.EMP.EMPNO WHEN '091' THEN '2' ELSE '1' END AS C11 FROM TRAFODION.XXX.EMP
			
			//The excepted result is:
			//SELECT TRAFODION.XXX.EMP.ENAME, CASE TRAFODION.XXX.EMP.ENAME || TRAFODION.XXX.EMP.EMPNO WHEN '091' THEN '2' ELSE '1' END AS C11 FROM TRAFODION.XXX.EMP
		}
	}
}

class Sql {
	private String text;
	
	private String schemaName;
	
	private List<Table> tables;
	
	public List<Table> getTables() {
		return tables;
	}

	public void setTable(List<Table> tables) {
		this.tables = tables;
	}

	public String getText() {
		return text;
	}
	
	public void setText(String text) {
		this.text = text;
	}

	public String getSchemaName() {
		return schemaName;
	}

	public void setSchemaName(String schemaName) {
		this.schemaName = schemaName;
	}

}
`

**Comment by sivaraam** [comment]
@esg-guoqing There's an [example in the wiki](https://github.com/JSQLParser/JSqlParser/wiki/Examples-of-SQL-building#replacing-string-values) that demonstrates how to replace string values found in a query with alternate values.

You can take a look at that example and then with the help of the javadoc for the [ExpressionDeParser](https://www.javadoc.io/static/com.github.jsqlparser/jsqlparser/3.0/net/sf/jsqlparser/util/deparser/ExpressionDeParser.html) you can come up with a way to solve your problem in a much simpler way.

**Comment by esg-guoqing** [comment]
Thank you very much. I read it carefully and try to solve my problem. I find the CaseExpression and sovled this issue. Thanks again!

**Comment by sivaraam** [comment]
@esg-guoqing Good to know you found a solution!

Anyways, rather than overriding the `CaseExpression` if you just override the `Column` and `Table` methods you **would not** have to handle all kinds of expressions separately (e.g., AndExpression, OrExpression).

**Comment by esg-guoqing** [comment]
Thanks for your kind advices. I wikk!

**Comment by wumpz** [comment]
Glad to see it's going forward here. However I would like to have suggestions to to make more examples or to improve the docs.

**Comment by sivaraam** [comment]
>  However I would like to have suggestions to to make more examples or to improve the docs.

Improving the docs would be very valuable!

I initially had some friction with using the library. Though, I have a better understanding now. It would really be nice if the Javadocs were improved a little. I found that the docs were limited in some places e.g., the [CCJParserUtil# parse(String sql, Consumer<CCJSqlParser> consumer)](https://www.javadoc.io/static/com.github.jsqlparser/jsqlparser/3.1/net/sf/jsqlparser/parser/CCJSqlParserUtil.html#parse-java.lang.String-java.util.function.Consumer-). It is one that should be used to switch between square brackets in queries being interpreted as arrays (or) as MS SQL specific notation. Documenting it would be helpful.

Regarding examples, one idea that comes to my mind is demonstrating how to change column names found in specific parts of the query. I better illustrate it with an example. Consider the following query,

```sql
SELECT col1 AS a, col2 AS b, col3 AS c FROM table WHERE col_1 = 10 AND col_2 = 20 AND col_3 = 30;
```

It would be nice if we use an example to demonstrate how to use the object constructed by the parser to change the query such that the modified query is like this:

```sql
SELECT col1 AS a, col2 AS b, col3 AS c FROM table WHERE col1 = 10 AND col2 = 20 AND col3 = 30;
```

This would be better than the string value replacement example in the Wiki as the new value depends on the existing value.

Another example could be how to get a map of aliases and the corresponding SelectItems. For example, for the above query. The example should construct the following map:
```
a => col1
b => col2
c => col3
```

**Comment by wumpz** [comment]
@sivaraam I added a javadoc to the method you referenced. As well I introduced two more wiki pages with your suggested examples: https://github.com/JSQLParser/JSqlParser/wiki/Examples-of-SQL-building--part-2  and  https://github.com/JSQLParser/JSqlParser/wiki/Examples-of-SQL-analyzing.
Hope that helps. More input is appreciated. Saying that, you know, I am a developer and in that writing documentation is a problem ;). So PRs or even new Wiki pages are welcome. 
I already thought about creating a jsqlparser.gihub.io (github pages) website. But maintaining is scaring. :(

**Comment by sivaraam** [comment]
>  I already thought about creating a jsqlparser.gihub.io (github pages) website. But maintaining is scaring. :(

Interesting. I would be glad to help you with that, if you wish. What do you think of hosting in the website?

**Comment by wumpz** [comment]
@sivaraam What do you mean with "What do you think of hosting in the website?"? Those io sites are hosted by github itself. Or did I misunterstand you?

**Comment by sivaraam** [comment]
> Or did I misunterstand you?

I suppose you did. I was asking what information you were thinking of providing in the website. Obviously, you would like that to serve as a home page. What else do you think of hosting there? A Getting started guide? User manual?

**Comment by wumpz** [comment]
Right. As you already saw, I barely came out of writing examples.

**Comment by sivaraam** [comment]
Just wanted to confirm, would you like any help with setting up the website?

**Comment by wumpz** [comment]
Confirmed. :) I think we should go with GitHub pages. Do you know a fitting template. Maybe "minimal mistakes"?

**Comment by sivaraam** [comment]
[That theme](https://mmistakes.github.io/minimal-mistakes/) does look good @wumpz!

I've created #898 to track the discussion about the website. I think we can move the conversation there :-)

**Comment by wumpz** [comment]
So can we close this issue?
