### ISSUE TITLE
1 update user set name = 'lily' where id = 1; update user set name = 'locy' where id = 2

### ISSUE THREAD

**Issue by weiyq** [JSQLParser/JSqlParser#895]
**Describe the bug**

**To Reproduce**
1. Example SQL
2. Parsing this SQL using JSqlParser with this statements
3. Exception

**Expected behavior**

**System**
 - Database you are using
- Java Version
- JSqlParser version

**Comment by wumpz** [comment]
I am sorry as well. ;)
