### ISSUE TITLE
Oracle 10+ aggregate functions extension (FIRST, LAST) not supported by the parser

### ISSUE THREAD

**Issue by iszilagyigit** [JSQLParser/JSqlParser#90]
The followin sql (valid in Oracle 11) is not accepted by the parser.

<b>select col1, min(col2) KEEP (DENSE_RANK FIRST ORDER BY col3), col4  from table1 group by col5 order by col3</b>
see:
https://docs.oracle.com/cd/B19306_01/server.102/b14200/functions056.htm#i1000901

**Comment by wumpz** [comment]
Implemented this using your patch as a base. Could you check if it does what you need?

**Comment by iszilagyigit** [comment]
Thanks! From the first test today with 0.9.3-SNAPSHOT all my sqls got parsed so it looks really good. Will verify the results in the following days...
