### ISSUE TITLE
Multiple inner query inside IN clause does not work

### ISSUE THREAD

**Issue by jobert21** [JSQLParser/JSqlParser#905]
**Describe the bug**
SQL with multiple inner query inside **IN clause** does not work. Example below

**To Reproduce**
1. `select * from table_a where other_id in ((select id from table_b where name like '%aa%'), (select id from table_b where name like '%bb%'))`
2. `CCJSqlParserUtil.parse(sql)`
3. `Encountered unexpected token: "in" "IN"`

**Expected behavior**
The query runs properly when executing in SQL Server.

**System**
 - Database: MSSQL 2012
- Java Version: 1.7
- JSqlParser version: 2.1

**Comment by wumpz** [comment]
Did you already try the actual version 3.1?

**Comment by jobert21** [comment]
@wumpz yes. it did not work. but i already have the fix now. :) can i submit pull request for JSqlParserCC.jjt? tested in 2.1.

**Comment by wumpz** [comment]
Sure. But I will integrate it in version 3.1. You want to stay with 2.1?

**Comment by jobert21** [comment]
@wumpz - we still have clients using JRE 1.7. Until we fully migrate to JRE 12 or JRE 1.8 minimum, need to use 2.1.

**Comment by wumpz** [comment]
@jobert21 I see. 1.7 was along time ago, at least for me. Do you want your patch merged into some version 2.1.1?

**Comment by jobert21** [comment]
@wumpz yes. will submit a pull request.

**Comment by manticore-projects** [comment]
This is still relevant/open for 4.2-Snapshot.
Todo:
1) test if actually permitted in H2/Oracle/PostgreSQL
2) implement
