### ISSUE TITLE
Preserve keyword case

### ISSUE THREAD

**Issue by ddugovic** [JSQLParser/JSqlParser#906]
Some users prefer that the original case of SQL keywords be preserved, for example:
`System.out.println(CCJSqlParserUtil.parseStatements("select * from sysdatabases").toString());`

Desired behavior:
Optionally (or by some other means) preserve keyword case, for example print:
`select * from sysdatabases`

System:
JSqlParser version 3.1 (latest)
Java 8

**Comment by wumpz** [comment]
That would some work to do. JavaCC only accepts keyword tokens. Therefore the used case for an input statement is not preserved.

**Comment by ddugovic** [comment]
Thanks, I have filed https://github.com/javacc/javacc/issues/120 (in the interim, time permitting I might experiment with case-sensitive matches since I don't expect my users to type keywords like `FroM`).

**Comment by wumpz** [comment]
I don't think, the request you filed at javacc will have any influence on this. The grammar of JSqlParser itself uses this tokens and build an object hierarchy from this. The case of object names is preserved, but when you use a **toString** or a deparser, the keywords do not come from the accepted tokens, but from string constants like **"SELECT"**.

One solution here would be to write or adapt the deparsers to be able to use upper case or lower case **keywords**. 

You could file a PR.

**Comment by wumpz** [comment]
So may we close this one?

Additionally, you have the original SQL. There the case is not attached.

As I said, the deparsers could be changed in a way, to make some case changes on used keywords.

**Comment by ddugovic** [comment]
Sorry, yes I will close this.  I did put forth some effort but am not ready to change the deparsers in the near future.

**Comment by wumpz** [comment]
So maybe you could share your efforts so far ...

**Comment by ddugovic** [comment]
9f8ca07 is how far I got before being tasked with a different project to work on.
