### ISSUE TITLE
Encountered unexpected token: "->>" "->>"

### ISSUE THREAD

**Issue by wjc1243** [JSQLParser/JSqlParser#909]
**Describe the bug**
Encountered unexpected token: "->>" "->>"

**To Reproduce**
1. Example SQL
      select uc."id", u.nickname, u.avatar, b.title, uc.images, uc.created_at as createdAt
      from library.ugc_comment uc
      INNER JOIN library.book b on (uc.books_id ->> 0)::INTEGER = b."id"
      INNER JOIN library.users u ON uc.user_id = u.user_id
      where uc.id = 1
2. Parsing this SQL using JSqlParser with this statements
     mybatis-3.2.0
3. Exception
     Caused by: net.sf.jsqlparser.JSQLParserException
     at net.sf.jsqlparser.parser.CCJSqlParserUtil.parseStatements(CCJSqlParserUtil.java:128)
     at com.baomidou.mybatisplus.core.parser.AbstractJsqlParser.parser(AbstractJsqlParser.java:60)
     ... 156 more
      Caused by: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "->>" "->>"
     at line 3, column 45.
     Was expecting one of:
     "&"
     "&&"

**Expected behavior**
     I want to retrieve the first data in JSON. The PostgreSQL syntax is "- > >", but this place has 
     reported an error.

**System**
- postgresql
- mybatis 3.2.0
- Java 8
- JSqlParser 1.4/3.0/3.1

**Comment by wumpz** [comment]
Please use English as the issue language.

**Comment by wjc1243** [comment]
> Please use English as the issue language.
@wumpz 
I've revised the issue. Please help me with it. Thank you

**Comment by wjc1243** [comment]
Find an imperfect method, use @ sqlparser (filter = true) on the mapper method to exclude SQL parsing.

Be careful!! Global configuration sqlparsercache is set to true to take effect. (MP 3.1.1 does not need this step at first)

If there's a better way, please let me know. Thank you very much.

**Comment by wumpz** [comment]
? Sorry. I didn't get it.

**Comment by lizhuoxuan** [comment]
I think when sql use "<" or ">",such as "select 1 > 2;" ,it will throw Exception like "Encountered unexpected token: "->>" "->>".

**Comment by wumpz** [comment]
JSqlParser does til now only support textual parameters for this json operation. I am on it to change that.
