### ISSUE TITLE
SQL Server variable assignment in a select does not parse | SELECT @var = 1

### ISSUE THREAD

**Issue by cdandoy** [JSQLParser/JSqlParser#913]
**Describe the bug**
SQL Server supports assigning a value to a variable from a selected expression.
For example:
```
DECLARE @var INT;
CREATE TABLE tableName (id INT);

SELECT @var = 1;
SELECT @var = id FROM tableName;
```

**To Reproduce**
` assertSqlCanBeParsedAndDeparsed("SELECT @var = 1");`

**System**
 - SQL Server 2017
- JSqlParser 3.1

**Comment by wumpz** [comment]
Do I see it right, that every expression is assignable in this form?

**Comment by cdandoy** [comment]
Yes it is.
Here is another example (tested on SQL Server 2017) that calculates 5!
```
DROP TABLE tableName;
CREATE TABLE tableName (id INT);
INSERT INTO tableName VALUES (1),(2),(3),(4),(5)

DECLARE @var INT = 1;
SELECT @var = @var * id FROM tableName;
SELECT @var -- 120
```

**Comment by cdandoy** [comment]
See https://docs.microsoft.com/en-us/sql/t-sql/language-elements/select-local-variable-transact-sql?view=sql-server-2017#examples

**Comment by wumpz** [comment]
Should work now.
