### ISSUE TITLE
Value in DateTimeLiteralExpression type doesn't ignore the leading and ending single quote in the input

### ISSUE THREAD

**Issue by lichader** [JSQLParser/JSqlParser#919]
Hi,

I have an input like this: 
```
column1 > date '2020-01-01' 
```

After parsing, it generates a **DateTimeLiteralExpression** type of instance:

```
Type: Date
Value: '2020-01-01'
```

My question is that the single quotes at the beginning and ending shouldn't be included as part of the value since they are only used to denote this is a **String**. 

I think the correct value should be
```
Type: Date
Value: 2020-01-01 
```

**Comment by wumpz** [comment]
If I remember right, the problem was to reconstruct the right quotation while deparsing. For instance **_utf8'2010-10-10'**.

**Comment by lichader** [comment]
@wumpz Thanks for your response. I tried to use your suggested way but it seems not working.

I was expecting something like the constructor of **StringValue** that escapes special characters for example leading and ending quotes.  I think the [setter](https://github.com/JSQLParser/JSqlParser/blob/master/src/main/java/net/sf/jsqlparser/expression/DateTimeLiteralExpression.java#L24) of **DateTimeLiteralExpression** so consumer of this library won't bother using special characters to escape quotes.

If you agree, I can start a PR on this.

**Comment by wumpz** [comment]
@lichader I am not sure, if I understand you. Maybe it is the best way to make a PR and discuss this one.

**Comment by manticore-projects** [comment]
Postgres' Implicit Cast is not supported.
