### ISSUE TITLE
After the source code is imported in eclipse, the Provider interface and implementation classes do not exist

### ISSUE THREAD

**Issue by 18408290250** [JSQLParser/JSqlParser#920]
My environment:
1.eclipse
2.Jdk1.8
3.eclipse javacc plugin: sf.eclipse.javacc-1.5.33-updatesite

When I downloaded the source code and imported it in eclipse, I used javacc to generate all the classes in the JSqlParserCC.jjt file, but lacked the necessary Provider interface and xxProvider class, such as StreamProvider, StringProvider. What is the reason? What should I do?

This is the class I generated after compiling through javacc：
![image](https://user-images.githubusercontent.com/21328922/71778390-41bc5080-2fe8-11ea-81af-731f2349d6b0.png)

Problems：
This is the class structure diagram under the parser package：
![image](https://user-images.githubusercontent.com/21328922/71789590-f39a6200-3066-11ea-890c-7c1c7f590e31.png)

But the class marked with red box does not exist：
![image](https://user-images.githubusercontent.com/21328922/71789578-d796c080-3066-11ea-9ee5-803604b403ab.png)

![image](https://user-images.githubusercontent.com/21328922/71789568-c6e64a80-3066-11ea-96dc-72cc0f4592da.png)

**Comment by wumpz** [comment]
Please use English and give an example of the failing SQL.

**Comment by wumpz** [comment]
I guess your JavaCc version is too old. Since V6 I think it generates the Stream provider. Don't use your workflow to build Jsqlparser. Use maven with clean install to create Jsqlparser.jar.

**Comment by wumpz** [comment]
So can we close this one?
