### ISSUE TITLE
Oracle Report Query Parser using JsqlParser.

### ISSUE THREAD

**Issue by Nividhan** [JSQLParser/JSqlParser#923]
Hello Team,

Could you please help me  to parse the SQL file which is generated by SAP Business Object.
I have written sample code using JsqlParser API  , its working fine for simple SQL query , where as  complex query i am getting Null pointer exception.

Software using : 
Java version 1.8
Jsql parser 0.9

More information on given below link.
[https://stackoverflow.com/questions/59607960/sap-business-object-sql-query-parser-in-java](url)

Please refer the given below sample query.
[OPR042 -Source.txt](https://github.com/JSQLParser/JSqlParser/files/4029347/OPR042.-Source.txt)

You can suggest me , List of  format changes, that  i have to do in SQL file ( which is  generated by SAP Business Object ) before invoking the JsqlParser API.

Thanks in Advance.

Regards
Vasanth D

**Comment by wumpz** [comment]
@Nividhan The first problem I found, was the useage of a function to provide the **in** set. So something like

    select * from mytable where func(a) in func(b) 

is not (yet) supported. 

By the way: that is an SQL!!! ;)

**Comment by wumpz** [comment]
I thought, this weekend was the time to check it, but as always some other things dropped in. But this issue is not forgotten. 

Sorry

**Comment by Nividhan** [comment]
Thanks bunch for your response. 
Please refer the attached query which is contain all the  complex scenarios which is generated by SAP BO.
[KIN_Query.txt](https://github.com/JSQLParser/JSqlParser/files/4074199/KIN_Query.txt)

**Comment by wumpz** [comment]
No problem. As I said, there is a time problem at the moment but I will pin this issue to get to it as one of the next.

**Comment by wumpz** [comment]
The function expression type is now supported in the last snapshot. The next problem are these @Prompt constructs. JSqlParser only supports user variables starting with an @.

**Comment by wumpz** [comment]
Within your large SQL I found an **in** expression with a literal. This is not yet supported.

**Comment by wumpz** [comment]
May I include your large SQLs as test statements for JSqlParser?

**Comment by Nividhan** [comment]
Thanks for the response.
As per your advise ,
1. i will remove the @prompt.
2. i will remove the Literal in expression  
( This is bit complex :) , even though i will do it )

Please go ahead and use sql query as test statement's.

**Comment by wumpz** [comment]
@Nividhan You could keep the literal expression. Sorry if I said it clear. I am on it to support **in** expressions with functions, literal and stuff. Maybe the whole set of **PrimaryExpressions** could be supported. We will see. :)

**Comment by wumpz** [comment]
The complete change is to complicated. So I added functions and character literals. I could now successfully parse your large SQL.

**Comment by Nividhan** [comment]
Thats awesome ! , Could you please explain me  , what are all changes i have to do from my end ? to parse the sql query .

**Comment by wumpz** [comment]
Hm. I am not sure, if I updated the SNAPSHOT version. So in general you need to add JSqlParser version **3.2-SNAPSHOT** as a dependency to your project instead of the release version. 
I deploy those at: **https://oss.sonatype.org/content/groups/public/**. Look at the start readme page at the bottom. There is the repository maven definition.

So using this snapshot should be all to do, except you already implemented some visitor stuff regarding **Functions**.

**Comment by wumpz** [comment]
I just deployed a 3.2-SNAPSHOT version. You could check it.

**Comment by Nividhan** [comment]
Thank you , Could you please  share the link  to download the jar.

**Comment by wumpz** [comment]
Look at the readme. The snapshots go to sonatype.

**Comment by wumpz** [comment]
Ups. I assumed you use maven. If not I have to lookup the link as well.

**Comment by wumpz** [comment]
The last version is deployed:

https://oss.sonatype.org/content/repositories/snapshots/com/github/jsqlparser/jsqlparser/3.2-SNAPSHOT/jsqlparser-3.2-20200202.215826-5.jar

**Comment by Nividhan** [comment]
Hello Wumpz ,

Thanks for the jar .
I have added the jar and executed the program which i have written , i am getting the below error.

net.sf.jsqlparser.JSQLParserException
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:65)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:40)
	at ReportSqlParser.processQuery(ReportSqlParser.java:197)
	at ReportSqlParser.main(ReportSqlParser.java:97)
Caused by: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "IN" "IN"
    at line 1, column 7957.

Could you please explain me , what are changes i have to do before invoking Jsqlparser .

**Comment by wumpz** [comment]
@nhanitvn I used your original one. My parser stops at those already mentioned **@Propmpt** function calls. Unfortunately I am not able to remove this in a workable manner, due to the syntax of this methods parameters.

**Comment by Nividhan** [comment]
Hello Wumpz ,

I got this error , after i replace the @prompt with empty space .

`fileContentAsString=fileContentAsString.replace("@Prompt","");`

Please advise .

Thanks .

**Comment by wumpz** [comment]
Unfortunately it is not as easy as this to remove this prompt stuff because the remaining part in brackets is not syntactically correct.
