### ISSUE TITLE
Unable to parse keyword columns if prefixed by alias

### ISSUE THREAD

**Issue by SerialVelocity** [JSQLParser/JSqlParser#932]
**Describe the bug**
Columns named as keywords should be accepted if prefixed by an alias.

Seems similar to #790 / #791

This happens with `order` and `group`. Could you please add both to the whitelist?

**To Reproduce**
1. Example SQL:
```
# SELECT order FROM tmp3;
ERROR:  syntax error at or near "FROM"
LINE 1: SELECT order FROM tmp3;

# SELECT tmp3.order FROM tmp3;
 order
-------
(0 rows)
```

3. JSQLParser Exception:
```
Caused by: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "." "."
    at line 1, column 12.
```

**Expected behavior**
The query to be parsed successfully.

**System**
- Database you are using: Postgres
- Java Version: 11
- JSqlParser version: 3.1

**Comment by wumpz** [comment]
This is addressed in the next snapshot. I did not yet push it due to other issues not completely done.

**Comment by SerialVelocity** [comment]
@wumpz Could you add "group" as well to that list?

**Comment by wumpz** [comment]
@SerialVelocity Did it. ;) But I could not yet deploy the actual snapshot. You need to rebuild JSqlParser from the actual sources or wait, til I make a deploy.
