### ISSUE TITLE
When SQL query contains an IN operator with multi-column expressions JSQLParserException is thrown

### ISSUE THREAD

**Issue by meelistolk** [JSQLParser/JSqlParser#939]
**Describe the bug**
When SQL query contains an IN operator with multi-column expressions (made with row constructors) and the query is parsed with CCJSqlParserUtil.parseStatements(sql) the parse method throws JSQLParserException.

**To Reproduce**
1. Oracle query:
select code,name
from users
where (code,name) in ((1,'name1'),(86,'name2'))
2. CCJSqlParserUtil.parseStatements(sql).getStatements();
3. JSQLParserException is thrown

**Expected behavior**
This query should be parseable and should not throw an exception

**System**
 - Oracle DB
- Java Version 11
- JSqlParser version 3.1

**Comment by jerryleooo** [comment]
Is JSqlParser supporting customized syntax? If so maybe we can support it ourselves

**Comment by jerryleooo** [comment]
@meelistolk see https://github.com/JSQLParser/JSqlParser/issues/737

**Comment by AnEmortalKid** [comment]
@wumpz this is now fixed by #997
