### ISSUE TITLE
Parsing when field name is keyword

### ISSUE THREAD

**Issue by morvael** [JSQLParser/JSqlParser#941]
This is correct statement in Informix:
```
SELECT b.create FROM table b WHERE b.id=1
```
It does not parse:
```
net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "." "."
    at line 1, column 9.
```
I think semi-reserved words should be parseable correctly given their context.

**Comment by wumpz** [comment]
This has to be done keyword by keyword.

**Comment by morvael** [comment]
It would be great if parser would be configurable, so that it would be possible to add certain words as keywords or remove them. But I guess with how the parser code is generated it's more or less static, which is unfortunate.

**Comment by morvael** [comment]
Did a quick test on MySQL, it's no longer angry that select is a keyword nor requires it to be put in ` ` if preceded by table alias:
```
select f.select from `from` f
```

**Comment by wumpz** [comment]
I added this create - keyword. The problem with your idea is it would introduce the need for massive lookaheads and a great refactoring of the grammar. Doing it keyword by keyword seems to be the appropriate way.

**Comment by morvael** [comment]
No lookahead, just branching after table alias in column expression - without alias there would be column-name-no-keyword-allowed token, with alias there would be column-name-keyword-allowed token.

**Comment by wumpz** [comment]
But since javacc grammars are LL(1) you need to know there is an alias, you need to lookahead. Since column names are multipart this lookahead could be costly. You have even to know more regarding e.g. cast statements where the keyword **as** does not indicate an alias.

**Comment by morvael** [comment]
I think it's possible to use LL(2) for a piece of grammar in javacc.
https://www.cs.purdue.edu/homes/hosking/javacc/doc/lookahead.html (see "SETTING A LOCAL LOOKAHEAD SPECIFICATION")

**Comment by morvael** [comment]
MySQL specification says:
https://dev.mysql.com/doc/refman/8.0/en/keywords.html

> Nonreserved keywords are permitted as identifiers without quoting. Reserved words are permitted as identifiers if you quote them

but

> Exception: A word that follows a period in a qualified name must be an identifier, so it need not be quoted even if it is reserved

I believe many systems work like that.

**Comment by wumpz** [comment]
Yes LL(2) is possible and means lookahead of 2 at each token.
Your second statement is quite interesting. I never thought about this but for this keywords could be accepted without branching. I will look into this.

**Comment by wumpz** [comment]
The grammar change due to your second statement was minimal. Not all keywords are supported now but can easily added. The production used now is **RelObjectNameExt2** for following parts.

**Comment by morvael** [comment]
I guess this is a good as it can get (without serious rework that would never look for any keywords after a period in a qualified name, so they wouldn't have to be added manually to a list of exclusions), thanks!

**Comment by wumpz** [comment]
@morvael You are right. Hope it helps. File new keywords that are needed.
