### ISSUE TITLE
DISABLE Keyword causing parser if used as column name

### ISSUE THREAD

**Issue by naumaan123** [JSQLParser/JSqlParser#945]
Bug 1

I reported a similar issue with the CHANGE keyword. We have a legacy app that uses the Mysql keyword "DISABLE" as a column name. Since it's legacy, we can't easily change the column name, and it is causing the sql parser to break. 

To Reproduce
2. Parsing "INSERT INTO SOMESCHEMA.TEST (DISABLE, TESTCOLUMN) VALUES(1, 1)" SQL using JSqlParser throws JsqlParserException.

Caused by: net.sf.jsqlparser.JSQLParserException at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:51) at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:40) ... 53 more Caused by: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: “DISABLE” “DISABLE” at line 1, column 15. Was expecting one of: “(” “ACTION” “ANY”...

Configuration

Mysql
Java 8
JSqlParser 2.1

Bug 2

Double quotes seem to not get parsed correctly

1. Parsing SELECT
(IFNULL(DOCUMENT_TABLE.TITLE,"") || ", " || IFNULL(WF.DISPLAY_NAME,"") || IFNULL(" # " || DOCUMENT_TABLE.SOME$NUMBER,"")  || IFNULL(" rev. " || DOCUMENT_TABLE.REVISION,"")) AS REQUIRMENT_DESCRIPTION

FROM
DOC.DOC_DOCUMENT AS DOCUMENT_TABLE
LEFT JOIN ENGINE.PHASE_SETTINGS AS PHASE ON (DOCUMENT_TABLE.SOME$CURRENT_PHASE = PHASE.PHASE_ID)
LEFT JOIN ENGINE.WF_SETTINGS AS WF ON (PHASE.WORKFLOW_ID = WF.WORKFLOW_ID)

WHERE
DOCUMENT_TABLE.DOC_ID = 2113978200

Causes  Jsqlparser exception on the quotation marks simliar to above statement.

**Comment by wumpz** [comment]
I will look into it.
