### ISSUE TITLE
Caused by: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "(" "("    

### ISSUE THREAD

**Issue by WangHone** [JSQLParser/JSqlParser#946]
**Describe the bug**
Caused by: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "(" "("
    at line 7, column 37.

**To Reproduce**
***Example SQL***
`with rount as
(select es.expense_account_id,s.name as site_name,es.seq
from gwcx_expense_site es
left join gwcx_site s on es.site_id = s.id)
select t.id,t.expense_time,s.name as departure_site,t.expense_category,
d.dict_value as reason,t.remark,t.cost,t.status,t.creation_time,
s.name || '->' || string_agg(r.site_name,'->' ) AS trip_route
from (select * from gwcx_expense_account where creator_user_id = 2) t
left join gwcx_site s on t.departure_site_id = s.id
left join blade_dict d on t.reason_id = d.id
left join rount r on t.id = r.expense_account_id
group by t.id,t.expense_time,s.name,t.expense_category,
d.dict_value,t.remark,t.cost,t.status,t.creation_time
order by t.creation_time desc`
***Exception***
`Caused by: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "(" "("  at line 7, column 37.
Was expecting one of:
    "&"
    ","
    "::"
    ";"
    "<<"
    ">>"
    "ACTION"
    "ANY"
    "AS"
    "BYTE"
    "CASCADE"
    "CAST"
    "CHANGE"
    "CHAR"
    "CHARACTER"
    "COLLATE"
    "COLUMN"
    "COLUMNS"
    "COMMENT"
    "COMMIT"
    "CONNECT"
    "DESCRIBE"
    "DO"
    "DUPLICATE"
    "ENABLE"
    "END"
    "EXCEPT"
    "EXTRACT"
    "FALSE"
    "FIRST"
    "FN"
    "FOLLOWING"
    "FOR"
    "FROM"
    "GROUP"
    "HAVING"
    "INDEX"
    "INSERT"
    "INTERSECT"
    "INTERVAL"
    "INTO"
    "ISNULL"
    "KEY"
    "LAST"
    "MATERIALIZED"
    "MINUS"
    "NEXTVAL"
    "NO"
    "NULLS"
    "OPEN"
    "ORDER"
    "OVER"
    "PARTITION"
    "PATH"
    "PERCENT"
    "PRECISION"
    "PRIMARY"
    "PRIOR"
    "RANGE"
    "READ"
    "REPLACE"
    "ROW"
    "ROWS"
    "SEPARATOR"
    "SESSION"
    "SIBLINGS"
    "SIZE"
    "START"
    "TABLE"
    "TEMP"
    "TEMPORARY"
    "TOP"
    "TRUE"
    "TRUNCATE"
    "TYPE"
    "UNION"
    "UNSIGNED"
    "VALUE"
    "VALUES"
    "WHERE"
    "WINDOW"
    "XML"
    "ZONE"
    "["
    "^"
    "|"
    <EOF>
    <K_DATETIMELITERAL>
    <K_DATE_LITERAL>
    <S_CHAR_LITERAL>
    <S_IDENTIFIER>
    <S_QUOTED_IDENTIFIER>
	at net.sf.jsqlparser.parser.CCJSqlParser.generateParseException(CCJSqlParser.java:22439) ~[jsqlparser-3.1.jar:na]
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_consume_token(CCJSqlParser.java:22286) ~[jsqlparser-3.1.jar:na]
	at net.sf.jsqlparser.parser.CCJSqlParser.Statements(CCJSqlParser.java:577) ~[jsqlparser-3.1.jar:na]
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parseStatements(CCJSqlParserUtil.java:135) ~[jsqlparser-3.1.jar:na]
	... 133 common frames omitted`
**Expected behavior**

**System**
 - PostgreSQL 11.6 
- jdk 1.8
- jsqlparser3.1

**Comment by AnEmortalKid** [comment]
@WangHone this doesn't seem like an issue now

![image](https://user-images.githubusercontent.com/3474369/85642984-88663b80-b658-11ea-92eb-0afe5d7d9eca.png)

**Comment by bai020** [comment]
me too，my sql is ：
select t0_.full_station_id as col_0_0_, t0_.connector_name as col_1_0_, t0_.connector_type as col_2_0_, t0_.is_removed as col_3_0_, t2_.city_name as col_4_0_, t0_.voltage_upper_limits as col_5_0_, t0_.voltage_lower_limits as col_6_0_, t0_.current as col_7_0_, t0_.dd_status as col_8_0_, t0_.op_connector_statusas col_9_0_, t1_.id as col_10_0_, t1_.operator_id as col_11_0_, t1_.operator_name as col_12_0_, t2_.address as col_13_0_, t2_.dd_status as col_14_0_, t2_.station_name as col_15_0_, t2_.station_id as col_16_0_, stationequ3_.equipment_id as col_17_0_, t2_.city_area_code as col_18_0_, t2_.merchant_id as col_19_0_, t2_.station_lat as col_20_0_, t2_.station_lng as col_21_0_, t2_.gate_lat as col_22_0_, t2_.gate_lng as col_23_0_ from table0 t0_
cross join table1 t1_
cross join table2 t2_
cross join table3 stationequ3_
where t0_.connector_id=? and stationequ3_.full_equipment_id=t0_.full_equipment_id and t2_.full_station_id=t0_.full_station_id and t1_.operator_id=t2_.operator_id

**Comment by wumpz** [comment]
So this can be closed, right?

**Comment by bai020** [comment]
YES
