### ISSUE TITLE
net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "=" "="

### ISSUE THREAD

**Issue by balzaron** [JSQLParser/JSqlParser#948]
**Describe the bug**
jsqlparser cannot parse the expression with "=" in select statement.
**To Reproduce**
1. Example SQL  select sum(case when companyid not in (null) then 1 else 0 end)=1 as validate_companyid from table1;
2. Parsing this SQL using JSqlParser with this statements
CCJSqlParserManager ccjSqlParserManager = new CCJSqlParserManager();
        Statement statement;
        List<String> columns = new ArrayList<String>();
        try {
            statement = ccjSqlParserManager.parse(new StringReader(singleSql));
3. Exception
Caused by: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "=" "="
    at line 1, column 64.
Was expecting one of:

    "&"
    ","
    "."
    "::"
    ";"
    "<<"
    ">>"
...
**Expected behavior**
 
**System**
 - Database you are using postgres
- Java Version 1.8_222
- JSqlParser version 3.1

**Comment by wumpz** [comment]
Solved within JSqlParser 4.0-SNAPSHOT.
