### ISSUE TITLE
How do I replace the table name in select from

### ISSUE THREAD

**Issue by chen-ABC** [JSQLParser/JSqlParser#949]
example：
`select * from a,b,c where a.id=c.id and a.id=b.id`

replace the table name：
`select * from tableA,tableB,tableC where a.id=c.id and a.id=b.id`

I tried to use  getFromItem()  visit(Table table),  But  only had the first table name.

**Comment by wumpz** [comment]
Using all this visitor stuff you are able to scan for all occurances of **Table**. Then you could just reset its name. 

This example does modify columns and add some aliases but the modification to use tables should be trivial:

    Select select = (Select) CCJSqlParserUtil.parse("select a,b,c from test");
    final AddAliasesVisitor instance = new AddAliasesVisitor();
    select.getSelectBody().accept(instance);

Hope that helps.

**Comment by chen-ABC** [comment]
@wumpz  Thanks
