### ISSUE TITLE
Nested statement, insert statement contains select

### ISSUE THREAD

**Issue by lnnnogithub** [JSQLParser/JSqlParser#950]
like this : insert into A(X) values((SELECT X from B WHERE ID = 8))

Can I get all the tables and get the corresponding relationship？
eg: insert -> A , select -> B

**Comment by wumpz** [comment]
To achieve what you want, this code should be sufficient:

    Insert insert = (Insert)CCJSqlParserUtil.parse(" insert into A(X) values((SELECT X from B WHERE ID = 8))");
    TablesNamesFinder finder = new TablesNamesFinder();

    System.out.println("all tables = "  + finder.getTableList(insert));

    System.out.println("insert tables = " + insert.getTable());

    insert.getItemsList().accept(new ItemsListVisitorAdapter() {
        @Override
        public void visit(ExpressionList expressionList) {
            for (Expression expr : expressionList.getExpressions()) {
                System.out.println("expr = " + expr + " tables = " 
                        + finder.getTableList(expr));
            }
        }
    });

With the **TablesNamesFinder** you can extract all used tables from a statement or an expression. As you see **finder.getTableList** extracts this for you.

To get the table of your insert you just need **insert.getTables**. To get the tables from all values / expressions, you should use the **ItemsListVistor** to get the right item types you need to process. The visitor gives you a hint what type of expressions you are dealing with.
