### ISSUE TITLE
Could not resolve NOT REXGEP

### ISSUE THREAD

**Issue by nasodaengineer** [JSQLParser/JSqlParser#951]
**Describe the bug**
RegExpMySQLOperator should also have an attribute like InExpression to determine if it is 'not', otherwise it cannot parse the SQL statement containing not Regexp

**To Reproduce**
1. Example SQL
SELECT * FROM t_city WHERE city_name NOT REGEXP 'a | b | c'
2. Parsing this SQL using JSqlParser with this statements
CCJSqlParserUtil.parse("SELECT * FROM t_city WHERE city_name NOT REGEXP 'a | b | c'")
3. Exception
net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "not" "NOT"

**Expected behavior**
Can parse sql containing NOT REXGEP

**System**
 - Database you are using
mysql5.7
- Java Version
java8
- JSqlParser version
3.1

**Comment by johnxiaohe** [comment]
me too

**Comment by johnxiaohe** [comment]
I I also encountered this mistake。
System
```
Database you are using
mysql5.7
Java Version
java8
JSqlParser version
3.1 or 1.4
```


And   This is true that 
```
SELECT count(1) from ewmsj_yhxx where 1=1
           AND ZJHM REGEXP('130629')
          AND GZDW   REGEXP('无|否|家|没有|务农|退休|农民|自由|学生')
```
This is fail that
```
select count(1) from ewmsj_yhxx where 1=1
           AND ZJHM REGEXP('130629') 
          AND GZDW   not  REGEXP('无|否|家|没有|务农|退休|农民|自由|学生')
```
Just one more `not`

**Comment by wumpz** [comment]
JsqlParser parses this

**Comment by 2406450951** [comment]
me too ,无法解析这个东西，NOT REGEXP ，在数据库中是可执行的，但是解析就是失败的

**Comment by manticore-projects** [comment]
JSQL Parser 4.1 Snapshot parses your statement correctly, you can [try it online here](http://217.160.215.75:8080/jsqlformatter/demo.html?args=-c%20MoUQMiDCAqAEsEsAmAoe70BpYDsCGAtgKYoBiASgPICysALkXgMYAWRATigOoASI5IWAAcWAexxFYAOUpwBAcRAANAAqwA5AD0AFAEYAzAG0ADAFoAnAF0AProAshgKzWA7Dd2OTt6wCZr+6ztrZwA2V2sADmsrWwivXV9-YOswl0joywBKAB0kAG8IgF8AEnUUAG4gA+)
