### ISSUE TITLE
JSQLParser said sql valid for not valid sql

### ISSUE THREAD

**Issue by kaplan441** [JSQLParser/JSqlParser#957]
### Example SQL
SELECT 	managers.first_name, 
	managers.last_name, 
	d.department_name
FROM
(
	SELECT first_name, last_name, department_id 
	FROM employees WHERE 
	manager_id IS NULL 
	OR employee_id IN (
		SELECT manager_id 
		FROM employees
	)
) managers 
INNER JOIN departments d ON a.department_id = m.department_id;

I'm running belowing code in Java
CCJSqlParserUtil.parseStatements(sql)

### Then result is;

selectBody: SELECT managers.first_name, managers.last_name, d.department_name FROM (SELECT first_name, last_name, department_id FROM employees WHERE manager_id IS NULL OR employee_id IN (SELECT manager_id FROM employees)) managers INNER JOIN departments d ON a.department_id = m.department_id
fromItem:(SELECT first_name, last_name, department_id FROM employees WHERE manager_id IS NULL OR employee_id IN (SELECT manager_id FROM employees)) managers
joins : INNER JOIN departments d ON a.department_id = m.department_id

there has no errors but in joins conditions "m" and "a" alias is wrong.

I expected throw an parsing exception.

### System

No Database connection, only script
Java Version 1.8
JSqlParser version 3.1

**Comment by wumpz** [comment]
JSqlParser is only a parser and does not check semantics. I assume you expected JSqlParser to do this.

**Comment by kaplan441** [comment]
Yes I expected JsqlParser work like this.
Thank you so much.

**Comment by wumpz** [comment]
By the way we had a discussion about how to implement at least a start for it but did not came to a proper defined start unfortunately.
