### ISSUE TITLE
JSqlParser v3.0 doesn't support some foreign key reference option

### ISSUE THREAD

**Issue by FoxInNorth** [JSQLParser/JSqlParser#958]
**Describe the bug**
JSqlParser v3.0 doesn't support some foreign key reference option, include **RESTRICT, SET NULL, SET DEFAULT.**

Reference:

> [CONSTRAINT [symbol]] FOREIGN KEY
>     [index_name] (col_name, ...)
>     REFERENCES tbl_name (col_name,...)
>     [ON DELETE reference_option]
>     [ON UPDATE reference_option]
> 
> reference_option:
>     RESTRICT | CASCADE | SET NULL | NO ACTION | SET DEFAULT

[https://dev.mysql.com/doc/refman/8.0/en/create-table-foreign-keys.html#foreign-key-referential-actions](https://dev.mysql.com/doc/refman/8.0/en/create-table-foreign-keys.html#foreign-key-referential-actions)

**To Reproduce**
When use JSqlParser parse below creation table SQL for table: foreign_key_reference_option_sample, there was exception:

> create table foreign_key_reference_option_sample
> (
> id int primary key,
> country_id int not null,
> state_id int not null,
> city_id int null,
> person_id int not null,
> career_id int not null,
> key countryKey(country_id),
> key stateKey(state_id),
> key cityKey(city_id),
> key personKey(person_id),
> key careerKey(career_id),
> CONSTRAINT `fk_a` FOREIGN KEY (`country_id`) REFERENCES `t1` (`country`) ON UPDATE RESTRICT,
> CONSTRAINT `fk_b` FOREIGN KEY (`state_id`) REFERENCES `t1` (`state`) ON UPDATE CASCADE,
> CONSTRAINT `fk_c` FOREIGN KEY (`city_id`) REFERENCES `t1` (`city`) ON UPDATE SET NULL,
> CONSTRAINT `fk_d` FOREIGN KEY (`person_id`) REFERENCES `t1` (`person`) ON UPDATE NO ACTION,
> CONSTRAINT `fk_e` FOREIGN KEY (`country_id`) REFERENCES `t1` (`country`) ON DELETE RESTRICT,
> CONSTRAINT `fk_f` FOREIGN KEY (`state_id`) REFERENCES `t1` (`state`) ON DELETE CASCADE,
> CONSTRAINT `fk_g` FOREIGN KEY (`city_id`) REFERENCES `t1` (`city`) ON DELETE SET NULL,
> CONSTRAINT `fk_h` FOREIGN KEY (`person_id`) REFERENCES `t1` (`person`) ON DELETE NO ACTION
> );

> create table t1 (
> id int primary key,
> city int null,
> country int not null,
> state int not null,
> person int not null,
> career int not null,
> key cityindex (city),
> key countryindex (country),
> key stateindex (state),
> key personindex (person),
> key careerindex (career)
> );
> 

**Expected behavior**
JSqlParser need to parse the table# foreign_key_reference_option_sample creation SQL successfully.

**System**
 - Database you are using:  MySQL 8.0
- Java Version:    java 8
- JSqlParser version:  3.0

**Comment by gitmotte** [comment]
duplicate #985

**Comment by wumpz** [comment]
Thx so I will close this one.
