### ISSUE TITLE
parse sql contain count(if()) will throws JSQLParserException

### ISSUE THREAD

**Issue by cc69001210** [JSQLParser/JSqlParser#959]
version:
   jsqlparser 3.1
database:
   mysql5.7
sql: 
   select count(version=1 or null ) as versionCount from t_version
excepiton:
   net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "(" "(",Was expecting one of:
  "&",",",":"

which version can ignore this exception

**Comment by wumpz** [comment]
JSqlParser does not (yet) support this kind of expressions within a count.

**Comment by totoro52** [comment]
Excuse me, when will you support it?

**Comment by manticore-projects** [comment]
[Works with 4.1](http://jsqlformatter.manticore-projects.com/jsqlformatter/demo.html?args=-c%20MoUQMiDCAqAEkHsCuA7ALgClgNwKYCcBnASwRVgF5YBGAKFgcaYYHkAlWAOQFUwxYAlLACCwHARJkAxsnS0AYmxYBZWGgD6eIqRS0A3EA+)
