### ISSUE TITLE
Cannot parse CASE statements

### ISSUE THREAD

**Issue by naumaan123** [JSQLParser/JSqlParser#961]
Jsqlparser failing when a sql CASE statement is involved

I have posted similar bugs for otehr keywords
**To Reproduce**
SELECT OrderID, Quantity,
CASE
    WHEN Quantity > 30 THEN 
    WHEN Quantity = 30 THEN 
    ELSE 
END AS QuantityText
FROM OrderDetails;

Exception: 

net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "CASE" "CASE"
    at line 7, column 67.
 
Was expecting one of:
 
    "!"
    "("
    "NOT"

**Expected behavior**
CASE should be parsed correctly

**System**
 - Mysql 5.7
- Java 8
- JSqlParser version 3.2-SNAPSHOT

**Comment by wumpz** [comment]
Case is parsed correctly but your SQL is not valid.

**Comment by naumaan123** [comment]
You're right, here is another example of the SQL. It looks like it is parsing CASE correctly, but when it sees 'UNSIGNED', it fails. This runs correctly on local DB , the parser is just blowing up. ANy idea why? If you swap out UNSIGNED for CHAR it works fine. 

SELECT COLUMN1,COLUMN2,  CASE WHEN COLUMN1.DATA NOT IN ('1','3') THEN CASE WHEN CAST(COLUMN2 AS UNSIGNED) IN ('1','2','3') THEN 'Q1'  ELSE 'Q2' END END AS YEAR FROM TESTTABLE

Note that this is a condensed version of the select statement, the original has a lot of nested CASE statements which is why it looks the way it looks.

**Comment by wumpz** [comment]
Looks as if unsigned is treated like some keyword and is not allowed there. I will look into it.

**Comment by wumpz** [comment]
The problem was, that this unsigned could not stand alone for a type cast. This is now allowed.
