### ISSUE TITLE
Encountered unexpected token: "validate" "VALIDATE"

### ISSUE THREAD

**Issue by zs1314zt** [JSQLParser/JSqlParser#962]
jdk 1.7
jsqlparser version 2.1

when i run the test 

String sql = "update tbl_user_card SET validate = '1' identityCodeFlag = 1 where id=9150000293816";
Statement stmt = CCJSqlParserUtil.parse(new StringReader(sql));

i got a error
net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "validate" "VALIDATE"
    at line 1, column 26.

Was expecting one of:

**Comment by wumpz** [comment]
Looks like some kind of keyword problem. I will look into it.
