### ISSUE TITLE
GRANT statement not supported

### ISSUE THREAD

**Issue by zhumaliev-rv** [JSQLParser/JSqlParser#965]
**Describe the bug**
GRANT statement not supported 

**To Reproduce**
1. GRANT SELECT ON Student TO P2
2. Parsing this SQL using JSqlParser with this statements
3. Encountered unexpected token: "GRANT" <S_IDENTIFIER>
    at line 1, column 1.

Was expecting one of:

    "ALTER"
    "CALL"
    "COMMENT"
    "COMMIT"
    "DECLARE"
    "DELETE"
    "DESCRIBE"
    "DROP"
    "EXEC"
    "EXECUTE"
    "EXPLAIN"
    "INSERT"
    "MERGE"
    "REPLACE"
    "SET"
    "SHOW"
    "TRUNCATE"
    "UPDATE"
    "UPSERT"
    "USE"
    "VALUES"
    "WITH"
'

**Expected behavior**
Must be processed

**System**
 - Oracle
- 1.8
- JSqlParser 3.1

**Comment by wumpz** [comment]
That's right. PRs are welcome. I even could not get the latest issues done. To less time.
