### ISSUE TITLE
Extending the parser

### ISSUE THREAD

**Issue by nickfla1** [JSQLParser/JSqlParser#968]
Would it be possibile to add a mechanism to extend the parser with custom rules, so that we can implement unsupported or custom statements by ourselves?

EDIT:
I'm willing to contribute if this feature will be found useful

**Comment by wumpz** [comment]
Sure. JSqlParser uses JavaCC as its parser generator. The grammar itself is here: https://github.com/JSQLParser/JSqlParser/blob/master/src/main/jjtree/net/sf/jsqlparser/parser/JSqlParserCC.jjt and the parser is built every time you do a maven clean and build. 
Pull requests are welcome. If you have any questions feel free to ask. If you need support don't hesitate to ask.

**Comment by wumpz** [comment]
Just follow the coding rules and please my strict reviewer eyes and your PR is merged. :)
