### ISSUE TITLE
Create constraint inside create table not supported

### ISSUE THREAD

**Issue by ogabeezle** [JSQLParser/JSqlParser#969]
**Describe the bug**
i want to parse this sql
```
CREATE TABLE "public"."orders" (
    "source" character varying(255),
    CONSTRAINT check_source CHECK (((source)::text = 'MBCA'::text)),
);
```
it give me this error
```
Caused by: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: ")" ")"
    at line 1, column 73.
```
**To Reproduce**
1. CREATE TABLE "public"."orders" (
        "source" character varying(255),
        CONSTRAINT check_source CHECK (((source)::text = 'MBCA'::text)),
    );
2. Parsing this SQL using JSqlParser with this statements
3. ParseException

**Expected behavior**

**System**
 - Postgres
- Java 1.8
- JSqlParser 3.1

**Comment by AnEmortalKid** [comment]
The problem here was that extra `,` wasn't it?

```
CREATE TABLE "public"."orders" (
    "source" character varying(255),
    CONSTRAINT check_source CHECK (((source)::text = 'MBCA'::text)), <- THIS RIGHT HERE
);
```
