### ISSUE TITLE
JJTree - AST for JSqlParser

### ISSUE THREAD

**Issue by wumpz** [JSQLParser/JSqlParser#97]
I am thinking about integrating JavaCCs AST building using JJTree into the parser. After investigation I could say:

Pro:
- AST is a different view, how the parser accepts an SQL
- Position of tokens can be extracted
- Visitor pattern automatically included (JJTree option)

Con:
- this comes at the cost of 20 percent performance at worst and more memory consumption.

As this functionality could not be switched off (or is there a way?) I am curious if this is a lacking feature or more or less a burden to the parser. I am not quite sure.

Any comments to this are appreciated. ;)

**Comment by wumpz** [comment]
So no opinion here???

**Comment by alessiostalla** [comment]
How is an AST different from current "deparsers"? Would those remain with JJTree?
Personally, I don't care about the performance impact.

**Comment by wumpz** [comment]
The deparsers would remain. An advantage is that the complete traversal structure is generated by JavaCC. So no visitors have to be implemented.
