### ISSUE TITLE
Create default value for array when creating table

### ISSUE THREAD

**Issue by ogabeezle** [JSQLParser/JSqlParser#970]
**Describe the bug**
i want to parse this sql
```
CREATE TABLE "public"."reconciliation_file_configs" (
    "delimiter" text DEFAULT ','::text,
    "organization_codes" text[] DEFAULT ARRAY[]::text[] NOT NULL,
);
```
it give me this error
```
Caused by: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "ARRAY" <S_IDENTIFIER>
    at line 1, column 1220.
```
**To Reproduce**
1. CREATE TABLE "public"."table" (
        "delimiter" text DEFAULT ','::text,
        "text_array" text[] DEFAULT ARRAY[]::text[] NOT NULL,
    );

2. Parsing this SQL using JSqlParser with this statements
3. ParseException

**Expected behavior**

**System**
 - Postgres
- Java 1.8
- JSqlParser 3.1

**Comment by manticore-projects** [comment]
[Tested successfully with JSQLParser-4.2](http://jsqlformatter.manticore-projects.com/jsqlformatter/demo.html?args=-c%20MIJQogggKmAEUQEIBk4CIAOBXARgGwEsBjNAOjQCcBTIgewDsiDCBDAFwIYH0AzZqrnXp8A5gGc0sABQAoWPNhoAJlUIBbAmyoVJCvfv0wAGlD0ARMADEIAVWSmA5ABoHsAFxv4YE3IVPFtBQiLPQEAF7snPSCtCoSBl4mANoAuvIW1namECAgEACaqe6exlBFAHIA8qbldsgyAJQyANxAA+)
