### ISSUE TITLE
ON DELETE CASCADE not parsing in add FK

### ISSUE THREAD

**Issue by naumaan123** [JSQLParser/JSqlParser#971]
**Describe the bug**
Adding FK constraint does not parse correctly, fails at "ON CASCADE DELETE"
**To Reproduce**
ALTER TABLE RATING.SUPPLI_RATI_REPO_ADDITION_FILT ADD CONSTRAINT SRRAF_RATING_R_572785312_FK FOREIGN KEY (RATING_REPORT_ID) REFERENCES RATING.RATING_REPORT(RATING_REPORT_ID) ON DELETE CASCADE

Exception on parse - 
Caused by: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "ON" "ON"

**Expected behavior**
Statement gets parsed correctly

**System**
 - MYSQL 5.7
- Java 8
-  latest

**Comment by wumpz** [comment]
Fixed with one of the last commits. Could you check it?
