### ISSUE TITLE
Can function resolution be extended

### ISSUE THREAD

**Issue by mi521** [JSQLParser/JSqlParser#976]
Hello, for functions that cannot be parsed, is it possible for JsqlParser that we can implement a class by ourselves or override a method to add this function for the program to recognize

**Comment by wumpz** [comment]
Could you give an example?

**Comment by mi521** [comment]
> 你能举个例子吗？

eg: SELECT GROUP_CONCAT(a.REGION_ID) FROM t_region a;

Behind I would like to parse the select function, the function in the example above is a resolution not to come out, I am a beginner, can't understand the inside of the source, just want to ask, is there any way this can't parse function can be written by their own code into the program, and then let the program to meet it, and put him into function, if has been achieved, what is the method to realize it, also please advice

Inherited the TablesNamesFinder class and overwrote the following methods to get the function
@Override
    public void visit(SelectExpressionItem item) {
        super.visit(item);
        item.accept(new ExpressionVisitorAdapter() {
            @Override
            public void visit(Function function) {
                super.visit(function);
                System.out.println("function name is : "+function.getName());
            }
        }
    }
Would you please give directions

**Comment by wumpz** [comment]
I think I still don't get your point. 

At first your SQL is parsed perfectly fine:
```sql
SELECT GROUP_CONCAT(a.REGION_ID) FROM t_region a
```
So you are asking if you could implement your own extensions to JSqlParsers parser?
Sure you can. But this cannot be done in a dynamical manner or some kind of plugin. You have to extent the grammar itself (look into the .jjt file).

**Comment by mi521** [comment]
Yes, we can implement our own extension of JSqlParsers parser. Thank you for your reply. I am from China and very happy to learn your JsqlParser，It helped me a lot，I will continue to learn JsqlParser，
You are an excellent designer，thanks again！
