### ISSUE TITLE
Support for GROUPING in HAVING and ORDER BY

### ISSUE THREAD

**Issue by SerialVelocity** [JSQLParser/JSqlParser#979]
**Describe the bug**

These queries should parse successfully in JSqlParser (these queries work for both Oracle and Postgres. Not sure what other languages):
```
SELECT * FROM (SELECT 1 AS id) t GROUP BY CUBE(id) ORDER BY GROUPING(id);
SELECT * FROM (SELECT 1 AS id) t GROUP BY CUBE(id) HAVING GROUPING(id) = 1;
SELECT * FROM (SELECT 1 AS id) t GROUP BY CUBE(id) HAVING GROUPING(id) = 1 ORDER BY GROUPING(id);
```

**To Reproduce**
1. Example SQL above
2. Parsing this SQL using JSqlParser with this statements
3. Exception:
```
Caused by: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "GROUPING" "GROUPING"
    at line 1, column 61.

Was expecting one of:

    "!"
    "("
    "NOT"
```
**Expected behavior**
The query to be parsed successfully.

**System**
- Database you are using: Postgresql 9.6.x
- Java Version: 11
- JSqlParser version: 3.1

**Comment by manticore-projects** [comment]
[Tested successfully with JSQLParser-4.2](http://jsqlformatter.manticore-projects.com/jsqlformatter/demo.html?args=-c%20MoUQMiDCAqAEBUAoAYgJQPIFlYApa1AhlgEZYBBYWASwBN8BKWAF0QHEMBVABVgCEAmrEgBXAEYBTPHVgNE6VABEQqfkLYAnAPYiADtQB2Ac2n05AbkRXCUOEjRZc+G8TKUa9WS3Zdeg4eJSHrKIABLkAGoAkgBybLCaOvrGpl4AvKSIltbgtggoGNh4BLmuFFQyXqwc6DxqAZKpcuHRcQnaeoYmwUwZJPJKKvWJnSk9WUA+)
