### ISSUE TITLE
Parse column bug

### ISSUE THREAD

**Issue by BreatherLeiYu** [JSQLParser/JSqlParser#982]
**Describe the bug**
could not parse table

**To Reproduce**
1. Example SQL
2. Parsing this SQL using JSqlParser with this statements
3. Exception
 Expression expression = CCJSqlParserUtil.parseExpression("ads_coupon_use_i_d.2_channel");
 expression.table  = null
 expression.columnName = ads_coupon_use_i_d

**Expected behavior**
 expression.table  = ads_coupon_use_i_d
 expression.columnName = 2_channel

**System**
 - Database you are using mysql
- Java Version 1.8
- JSqlParser version 3.1

**Comment by wumpz** [comment]
JSqlParser does not support object names starting with a number **2_channel** have to be quoted.

**Comment by BreatherLeiYu** [comment]
Got it thx
