### ISSUE TITLE
how to get tablename from column

### ISSUE THREAD

**Issue by wuguowei19880907** [JSQLParser/JSqlParser#983]
my sql is 
```
select u.id,u.name as username,u.age,r.name as rolename 
from user u left join user_role ur on u.id=ur.user_id 
left join role r on ur.role_id = r.id 
where r.name like 'zhang%';
```
i can get the where expression by code like this:
```
Select selectStatement = (Select) statement;
PlainSelect plainSelect = (PlainSelect) selectStatement.getSelectBody();
Expression where = plainSelect.getWhere();
LikeExpression likeExpression = (LikeExpression) where;
Expression leftExpression = likeExpression.getLeftExpression();
Column expression = (Column) leftExpression;
String tableName = expression.getTable().getName();
```
the **tableName** I get is "r" not "role" ,
Can I get the tablename not the table alias name from the api

**Comment by wumpz** [comment]
No you can't. JSqlParser is only a parser. To do this kind of mapping you need some post processing of the resulted parsed data. There were efforts, at least discussions about this but an implementation does not seem at hand. However if you have a solution for this, pull requests are welcome. 

There are some problems to solve here, e.g.:
- visibility boundary of aliases and object names
- columns without tablename or alias (only solvable with database schema at hand) (but this is not your question)
- How to return data? one could extend Table object. But every named object here (tables, functions, columns) could be in a schema, could be aliased.

**Comment by wumpz** [comment]
Can we close this issue?
