### ISSUE TITLE
Support for COMMENT ON TABLE, COMMENT ON COLUMN...

### ISSUE THREAD

**Issue by wise-coders** [JSQLParser/JSqlParser#984]
Please add support for the following constructs ( used by Postgres, Oracle, Redshift ) :

COMMENT ON TABLE `texto_fichero` is "This is a sample comment";
COMMENT ON COLUMN `texto_fichero.fichero_id` is 'This is a comment';

MySql uses:
ALTER TABLE `texto_fichero` COMMENT "This is a sample comment";
ALTER TABLE `texto_fichero` MODIFY id COMMENT 'some comment';

**Comment by wumpz** [comment]
So first of all JSqlParser does not allow this double quoted string literals. For JSqlParser those are always object names.

So using single quotes these statements are parsed successfully using JSqlParser 3.2-SNAPSHOT:

    COMMENT ON TABLE texto_fichero is 'This is a sample comment';
    COMMENT ON COLUMN texto_fichero.fichero_id is 'This is a comment';

These alter statements are not yet supported.

**Comment by wumpz** [comment]
The normal **comment** statement was introduced late 2018 for issue #685.

**Comment by wise-coders** [comment]
Right, thank you, I found it.
One small issue on Comment:
it has two methods comment.getTable() and comment.getColumn()

When using 'COMMENT ON COLUMN 'myTable.myColumn' is 'Some comment'
it returns comment.getColumn().getColumnName() = "myTable.myColumn"
and comment.getColumn().getTable() = null

Wouldn't be correct that the column has also the Table set ( and not the table in the column name ) ?
Please make sure the that it works also  COMMENT ON COLUMN 'mySchema.myTable.myColumn' is 'Some comment'

Best regards,
 Dragos Pruteanu

--
 DbSchema - Wise Coders GbmH
82256 Fürstenfeldbruck bei München
 Email: support@dbschema.com - Web: [1] http://dbschema.com/

--

[1] http://www.example.com/

**Comment by wumpz** [comment]
You are right. I will change this. 

I will look into the **alter** statement to change the comments. Lets see how far I get with my somewhat limited time :).

**Comment by wumpz** [comment]
OK. I looked into it. The **Comment** class differs between commenting a table or a column exactly by setting the table or the column. I tested your example and could not reproduce your error report. Here is my test:

        Comment comment = (Comment) CCJSqlParserUtil.parse("COMMENT ON COLUMN myTable.myColumn is 'Some comment'");
        assertThat(comment.getTable()).isNull();
        assertThat(comment.getColumn().getColumnName()).isEqualTo("myColumn");
        assertThat(comment.getColumn().getTable().getFullyQualifiedName()).isEqualTo("myTable");

It produces not this combined name **myTable.myColumn** like you described.

The second example including a schema name works as expected too:

        Comment comment = (Comment) CCJSqlParserUtil.parse("COMMENT ON COLUMN mySchema.myTable.myColumn is 'Some comment'");
        assertThat(comment.getTable()).isNull();
        assertThat(comment.getColumn().getColumnName()).isEqualTo("myColumn");
        assertThat(comment.getColumn().getTable().getFullyQualifiedName()).isEqualTo("mySchema.myTable");
        assertThat(comment.getColumn().getTable().getName()).isEqualTo("myTable");
        assertThat(comment.getColumn().getTable().getSchemaName()).isEqualTo("mySchema");

**Comment by wumpz** [comment]
So do you want go have this **mysql** variant of commenting using **alter** as well?

**Comment by wise-coders** [comment]
Yes, it would be nice to implement it.

Best regards,
 Dragos Pruteanu

--
 DbSchema - Wise Coders GbmH
82256 Fürstenfeldbruck bei München
 Email: support@dbschema.com - Web: [1] http://dbschema.com/

--

[1] http://www.example.com/

**Comment by wumpz** [comment]
So implementing those new constructs will take its time. So I will see, if I could get on it in the next days. OK?

**Comment by wise-coders** [comment]
Great, thank you !

Best regards,
 Dragos Pruteanu

--
 DbSchema - Wise Coders GbmH
82256 Fürstenfeldbruck bei München
 Email: support@dbschema.com - Web: [1] http://dbschema.com/

--

[1] http://www.example.com/
