### ISSUE TITLE
Support Foreign Key ON UPDATE CASCADE 

### ISSUE THREAD

**Issue by dprutean** [JSQLParser/JSqlParser#985]
Two more statements to check ( ON UPDATE [RESTRICT | CASCADE | SET NULL | NO ACTION | SET DEFAULT})

ALTER TABLE `texto`
  ADD CONSTRAINT `texto_autor_id_foreign` FOREIGN KEY (`autor_id`) REFERENCES `users` (`id`) ON UPDATE CASCADE,
  ADD CONSTRAINT `texto_tipotexto_id_foreign` FOREIGN KEY (`tipotexto_id`) REFERENCES `tipotexto` (`id`) ON UPDATE CASCADE

Encountered unexpected token: "UPDATE" "UPDATE"
    at line 2, column 97.

ALTER TABLE `texto_fichero`
  ADD CONSTRAINT `texto_fichero_fichero_id_foreign` FOREIGN KEY (`fichero_id`) REFERENCES `fichero` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  ADD CONSTRAINT `texto_fichero_texto_id_foreign` FOREIGN KEY (`texto_id`) REFERENCES `texto` (`id`) ON DELETE CASCADE ON UPDATE CASCADE

Encountered unexpected token: "ON" "ON"
    at line 2, column 126.

**Comment by wumpz** [comment]
JSqlParser supports only **ON DELETE** (at the moment). Pull requests are welcome.

**Comment by gitmotte** [comment]
this is merged already an can be closed.
