### ISSUE TITLE
Unable to parse `SELECT 0 IS NULL`

### ISSUE THREAD

**Issue by auntyellow** [JSQLParser/JSqlParser#991]
**Describe the bug**
Unable to parse `SELECT 0 IS NULL`

**To Reproduce**
1. `SELECT 0 IS NULL` or `SELECT 1 IS NOT NULL` or `SELECT 2 IN (0, 1)`
2. Parsing this SQL using JSqlParser with this statements
3. Exception: `net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "IS" at line 1, column 9. Was expecting one of: ...`

**Expected behavior**
Should be able to parse statement.

**System**
- Database: MySQL (returns `0`) and PostgreSQL (returns `false`)
- Java Version: 8
- JSqlParser version: 3.1, 3.2-SNAPSHOT (with latest `master`)

**Comment by auntyellow** [comment]
Looks duplicated with #720

**Comment by wumpz** [comment]
JsqlParser 4 parses this
