### ISSUE TITLE
Unable to parse `EXPLAIN VERBOSE ...`

### ISSUE THREAD

**Issue by auntyellow** [JSQLParser/JSqlParser#993]
**Describe the bug**
Unable to parse `EXPLAIN VERBOSE ...`

**To Reproduce**
1. `EXPLAIN VERBOSE SELECT * FROM test`
2. Parsing this SQL using JSqlParser with this statements
3. Exception: `Encountered unexpected token: "VERBOSE" <S_IDENTIFIER> at line 1, column 9. Was expecting one of: ...`

**Expected behavior**
Should be able to parse statement.

**System**
- Database: PostgreSQL
- Java Version: 1.8
- JSqlParser version: 3.1

**Comment by wumpz** [comment]
This *verbose* keyword is not (yet) allowed there. PRs are wellcome.

**Comment by AnEmortalKid** [comment]
@auntyellow mind checking that pr out and letting me know what version of postgres you're using. I found some conflicting syntax between requiring `explain (verbose buffers) ...` or `explain ANALYZE ...`

**Comment by auntyellow** [comment]
Sorry for missing system context.

I'm implementing a Java Database with PostgreSQL compatibility, and testing it with different SQL clients. One client `Valentina Studio` will send this kind of SQL.

I tested my database with your PR `AnEmortalKid:explain-verbose` and the SQL is well parse. Thanks for your help.

**Comment by AnEmortalKid** [comment]
This was fixed by #996

**Comment by wumpz** [comment]
@AnEmortalKid if you comment your commits with **fixes #1234** it will close the issue if your pr is merged.

**Comment by AnEmortalKid** [comment]
Yeah... I forgot to do it for that one PR :(
