### ISSUE TITLE
net.sf.jsqlparser.JSQLParserException

### ISSUE THREAD

**Issue by shuxiaoxiao** [JSQLParser/JSqlParser#994]
SELECT count(CHANNEL IS NULL) as channelCount FROM `t_user`

net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "(" "("
    at line 1, column 13.

**System**
 - Database you are using  mysql
- Java Version  1.8
- JSqlParser version  3.1

**Comment by shuxiaoxiao** [comment]
druid   MySqlSchemaStatVisitor  可以解析出来

**Comment by rjahn** [comment]
Same problem:


```java
String select = "SELECT D.ID\r\n" + 
		            " ,D.NAME AS LABEL\r\n" + 
		            " ,D.DATY_ID\r\n" + 
		            " ,DT.NAME AS CONTENT_\r\n" + 
		            " ,DT.DATATYPE AS DT_DATATYPE\r\n" + 
		            " ,DT.LENGTH DT_LENGTH\r\n" + 
		            " ,DT.PRECISION_ AS DT_PRECISION_\r\n" + 
		            " ,DT.SCALE AS DT_SCALE\r\n" + 
		            " ,DT.SIGNED AS DT_SIGNED\r\n" + 
		            " ,L.CODE AS LANG_CODE\r\n" + 
		       " FROM  DICTIONARY D\r\n" + 
		            " ,DATATYPES DT\r\n" + 
		            " ,LANGUAGES L\r\n" + 
		      " WHERE D.DATY_ID = DT.ID\r\n" + 
		            " and L.ID = D.LANG_ID";

Statement stmt = CCJSqlParserUtil.parse(select);

TablesNamesFinder visitor = new TablesNamesFinder();
visitor.getTableList(stmt);
```

**Comment by rjahn** [comment]
The problem in my case is the SIGNED "keyword"

**Comment by kontchakov** [comment]
Using quoted identifiers, e.g., "SIGNED" instead of SIGNED, should help avoid the JSQLParser problem.

**Comment by rjahn** [comment]
right, this will solve the problem with my example code. 

The select is read programmatically and it's not impossible but hard to change JSqlParser keywords at runtime....

Is it possible to ignore keywords for Statement parsing?
Parsing should work anyway. The keywords are db specific and not relevant in "statement parsing".

**Comment by wumpz** [comment]
Adding keywords as proper object names is possible. But not each keyword is easy to add. But if I understand this right it should be a different issue, right?

**Comment by rjahn** [comment]
Understood. How is this possible, but maybe I'll try it different :)

I tried to parse above statement and it didn't work because of keyword detection. The keywords are DB/dialect specific.
So, is parsing of such statements possible with JSqlParser without keyword detection - with current release/snapshot?

If this isn't possible, it's a feature request.

**Comment by wumpz** [comment]
It has to be added to the RelObjectName productions. Unfortunately this change could be hard sometimes.

**Comment by rjahn** [comment]
Same problem with this statement

```java
sStmt = "SELECT DISTINCT rw.role_id,"+
	    "r.name AS rolename,"+
	    "rw.wosc_id,"+
	    "w.classname,"+
	    "w.lifecyclename,"+
	    "w.text,"+
	    "w.sidebar_text,"+
	    "w.menu_structure,"+
	    "w.image,"+
	    "w.sidebar_image,"+
	    "w.\"sequence\","+
	    "w.shortcut,"+
	    "w.env_desktop,"+
	    "w.env_web,"+
	    "w.env_mobile"+
	   "FROM roles ra,"+
	    "role_wosc rw,"+
	    "workscreens w"+
	  "WHERE ((r.id = rw.role_id) AND (rw.wosc_id = w.id))";
```

SEQUENCE keyword

Any example/help/suggestions how to fix this?

**Comment by manticore-projects** [comment]
[Sample 1 tested successfully with JSQLParser-4.2](http://jsqlformatter.manticore-projects.com/jsqlformatter/demo.html?args=-c%20MoUQMiDCAqAEkHsCuA7ALgClgYwBYEMUUBTAG1gElhYA5AVTDFgEpYBBavQk07ZdAFAAxAEoB5ALKw0AfSQBnYgCcBAbiA+)

[Sample 2 tested successfully with JSQLParser-4.2](http://jsqlformatter.manticore-projects.com/jsqlformatter/demo.html?args=-c%20MoUQMiDCAqAEsBMB0BLBAoeWsBpFIDsBDAWwFNYBBYWAGyICMzbNtd8EiAXATwH00rNrDwIuhUhWqwAxgHsCXMor5C2o8Zy7ceAByk0xfLTv1rsGpLWUBzLgAtEXPtYJ3759mKS6ATmRkUAGcUBT4qQ2c-AODQglVheEsgmSJrCKc+FLSyTySnJBCbAjIEDKMikoxEkTokeQQDOiI3PgbcgDEAJQB5AFlEFBkuOKJfHkQ1UW5TMiCnKea3AFciGzm6dAB1AAkQLpAOHQEygF4CwWxKADkAETq0WHPkelbBAG4gA+)

[Sample 3 tested successfully with JSQLParser-4.2](http://jsqlformatter.manticore-projects.com/jsqlformatter/demo.html?args=-c%20MoUQMiDCAqAEAiBJY1EDkYChY9gJwHcA6PAewBsBTAfQEsATbXAGnyIDsBDAW0tgEFg+CpS68mOVoSIFSAZwDGdRrlitiC8pzlyxlCWtjFytAGaUFAT02ie+1eqIAXSgA8nBx3IaUARpzxqF3dPIyJedgBXajknPEiFJ0i8exYw2m5OAHNUyTDvej8Aukyc0OIAIjlKAEdI0QVKCvKiOQALUjwnBUiPBzDRADdqQrkAaydSAAcWoeoCP1n2Ye5SX1oqTAAxACUAeQBZYSo5fE5Qsip5+QV8AnLOscUU0VP7gHUACRAdkFgACgBbAYsAAvHcSCJlLAAJQGVT8NDwIHSWSKaHg4ggmGwzAAbiAA+)
