### ISSUE TITLE
CCJSqlParserUtil.parse && return AND

### ISSUE THREAD

**Issue by KNMD** [JSQLParser/JSqlParser#999]
**Describe the bug**
Version:3.1
Database:Postgres
Postgres database has some spec symbol like "&&" to do some operate，But,  CCJSqlParserUtil.parse method parse result is change to "AND", How to resovle or work around

**To Reproduce**
1. Example SQL: SELECT * from Table WHERE (field_1 && ?)
2. Parsing this SQL using CCJSqlParserUtil.parse with this statements
3. Return SelectBody is SELECT * from Table WHERE (field_1 AND ?)

**Comment by KNMD** [comment]
how to resovle

**Comment by KNMD** [comment]
how to resolve

**Comment by wumpz** [comment]
JSqlParser at the moment parses **&&** directly into an **AndExpression**.  It does not yet preserve the input syntax. I will look into this.

**Comment by KNMD** [comment]
enough，thx
